### ISSUE TITLE
issue in Meitrack MVT340

### ISSUE THREAD

**Issue by brhom89** [tananaev/traccar#1002]
hello sir 

i have some devices from china model MVT340 the devices was working probably but from some time i notice signal stop but car moving and in free are means np in GSM but GPS stop why ?

**Comment by brhom89** [comment]
yes loses GPS signal and also didn't report location how will report location without gps signal?

**Comment by tananaev** [comment]
It can report old location.

**Comment by brhom89** [comment]
yes old location you have sometime ignition on and with speed more than 100 km/h but when you send reboot GPS command working well.

**Comment by tananaev** [comment]
Sounds like a device issue.

**Comment by brhom89** [comment]
Aha yes i think that what you think ecxactly the problem and soultion
