### ISSUE TITLE
Please support a new tracker - 3G GS902

### ISSUE THREAD

**Issue by victor-alpha** [tananaev/traccar#1007]
Dear Mr. Tananaev,

First let me congratulate you on your efforts on this fine piece of software!

Unfortunately my skills in java are useless, therefore I need to ask you to please be kind enough to add support for the following tracker model number GS902:

http://www.3gtrack.com/product/GPRS_DataLogger_GPS.pdf

An example of the TCP stream during regular operation is (lon and lat removed for security reasons):

```
#STA:0000000000;TM:30/11/2008,20:01:01;V:14.0;A1:0.000;A2:0.000;K:00000;SD:12.68km/h,1;TH:0000000#%$GPRMC,113112.000,A,XXXX.XXXXXX,N,XXXXX.XXXXXX,E,6.84,161.97,231114,,,A*6D
$GPVTG,161.97,T,,M,6.84,N,12.68,K,A*02%
```

or in hex:

```
235354413a303030303030303030303b544d3a33302f31312f323030382c32303a30313a30313b563a31342e303b41313a302e3030303b41323a302e3030303b4b3a30303030303b53443a31322e36386b6d2f682c313b54483a303030303030302325244750524d432c3131333131322e3030302c412c585858582e5858585858582c4e2c58585858582e5858585858582c452c362e38342c3136312e39372c3233313131342c2c2c412a36440d0a2447505654472c3136312e39372c542c2c4d2c362e38342c4e2c31322e36382c4b2c412a303225
```

if the tracker does not have a gps fix, it sends:

```
#STA:0000000000;TM:30/11/2008,19:58:06;V:0.00;A1:0.000;A2:0.000;K:00000;SD:0.00km/h,1;TH:0000000#%GPS orientation information is invalidation! %
```

where 0000000000 is the station number (changeable)
V:0.00   is the system (car/bus/boat) voltage
A1:0.000 is channel 1 analog voltage
A2:0.000 is channel 2 analog voltage
K:00000  are 5 digital inputs
SD:0.00  is the current speed (the last ,1 indicates km/h and ,0 indicates miles/h)
TH:00000000 indicate misc alarm bits such as speed alarm, out-of-area alarm etc (not relevant to basic tracking)

Note that the tracker sends both local date/time (in #STA part)  and gps/nmea date/time (in $GPRMC).
Also, reply to the tracker is not required in any case.

Thank you in advance for your help

Chris

**Comment by paulobiero** [comment]
Hello @tananaev was this added?
