### ISSUE TITLE
Syrus reporting wrong speed

### ISSUE THREAD

**Issue by daremen** [tananaev/traccar#1014]
Hi:
I have found that all my Syrus devices are reporting speed about half the real speed and I have found in the SyrusProtocolDecoder.java in line 167 : 
```
        // Speed and Course
        position.setSpeed(Double.valueOf(parser.group(index++)) \* 0.868976);
        position.setCourse(Double.valueOf(parser.group(index++)));
```
Why multiply the speed by 0.868976 ?
I have tried to change it to 1 for testing purposes editing the file in Eclipse Luna but I can´t package the file in tracker-server.jar, I don´t know how to do it with GWT? any ideas?

**Comment by daremen** [comment]
Hi Anton: 
how can I add some code to TrackerEventHandler.java to append and write the whole "sentence" received  in tracker.server.log , in order to analize the syrus message.?

**Comment by tananaev** [comment]
If you want to do it probably the best place is decoder.
