### ISSUE TITLE
Haicom not working

### ISSUE THREAD

**Issue by Xav59** [tananaev/traccar#1021]
Hi,

I first woul like to thank you for your great work!

I'm using traccar under linux, with MySQL and integrated with OpenGTS. It's working very well with a tk102b device (using the same protocol as the 103) and with the smartphone app, but I have a problem with a Haicom wich does not populate the db..
The device is declared in the db (the same way I did with the tk102b).
The noly message I get in the log is the following:
`2014-12-31 16:22:35 DEBUG: [5063 <- 80.215.210.154] - HEX: 24475052533031323439373030373130313235302c543130303030312c3134313233312c3135323233352c373530333733333630303330353634332c303030302c323238352c3030303030312c2c2c312c303023563034312a`
or in ascii
`$GPRS012497007101250,T100001,141231,152235,7503733600305643,0000,2285,000001,,,1,00#V041*`
The log does not say the IMEI is unknown, but it also doesn't show the info message decoded.

Any advice on were I should search to find the problem?

Xavier

**Comment by tananaev** [comment]
I tried your example and it works for me.

**Comment by Xav59** [comment]
Do you have any advice on how I can investigate on this? Or how I can test step by step? I don't even know where in the process the problem occurs...

**Comment by tananaev** [comment]
Are you using latest official release?

**Comment by Xav59** [comment]
Yes, and OpenGTS latest release also.

**Comment by tananaev** [comment]
Can I see full log file please. You can find my email address in profile.

**Comment by tananaev** [comment]
The problem might be with the leading zero in IMEI number. It is not supported with the official config.

**Comment by tananaev** [comment]
See #61 for more info.

**Comment by nwohaibi** [comment]
I faced this issue as well and took me a while to figure it out. we might need to add a comment into conf file.
e.g.

> Configuration:
> Default device_id behavior will treat IMEI numbers as integers (leading zeros will be truncated ). To change this; in config file:
> ```
> :device_id
> ```
> to
> ```
> RIGHT(CONCAT('000000000000000', :device_id), 15)
> ```
