### ISSUE TITLE
problem after upgrade to 2.10

### ISSUE THREAD

**Issue by alucionet** [tananaev/traccar#1025]
Hello,

My setup was running perfectly fine on older version with patches for Meitrack devices that you helped me with sometimes ago. I just recently upgraded the traccar software to the latest 2.10 and it seems like there is a problem processing the data. 
I can see from "netstat -an" that there are streams of data coming in, but only few devices were able to update the database.

I then tried to feed data locally using wifi and traccar client.
From the log file (level ALL), when I started the client, I can see data coming in, but it is not doing anything:
2015-01-08 17:45:26 DEBUG: [5005 <- 10.8.8.161] - HEX: 24504749442c41303030303032464542373136352a33310d0a

There will be nothing happening until I turn of the client service, which then will log the following:
2015-01-08 17:46:33  INFO: Closing connection by disconnect

For the other devices, the logfile does not have anything logged.
I only see from "netstat -an" report that there are open established streams of data that never got disconnected (until I restart the traccar and I see multiple "Closing connection by disconnect").

Do you have any ideas on what may be happening?

**Comment by alucionet** [comment]
I am not sure if this is related ... but I found the following error messages:
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/01/08 17:48:06 | Caused by: 
INFO   | jvm 1    | 2015/01/08 17:48:06 | javax.persistence.EntityNotFoundException: Unable to find org.traccar.web.shared.model.Position with id -1
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.ejb.Ejb3Configuration$Ejb3EntityNotFoundDelegate.handleEntityNotFound(Ejb3Configuration.java:155)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:210)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:260)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:148)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1078)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1005)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:651)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.type.EntityType.resolve(EntityType.java:471)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:167)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:137)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1103)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.processResultSet(Loader.java:960)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.doQuery(Loader.java:910)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:341)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:311)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.loadCollection(Loader.java:2228)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.collection.CollectionLoader.initialize(CollectionLoader.java:61)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:678)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:80)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1804)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.collection.internal.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:681)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:1024)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:346)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.doList(Loader.java:2516)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.doList(Loader.java:2502)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2332)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.Loader.list(Loader.java:2327)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:490)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1247)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:264)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:130)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/01/08 17:48:06 | 	at java.lang.Thread.run(Thread.java:745)

**Comment by tananaev** [comment]
Seems like the problem is on the Client side. There were no major changes on the server to T55 protocol.

The error in the log is not related to the original issue.

**Comment by alucionet** [comment]
I was using the Traccar Client. Should I upgrade the Client too?

There are other errors:
INFO   | jvm 1    | 2015/01/08 17:58:34 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/01/08 17:59:20 | 2015-01-08 17:59:19.976:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/01/08 17:59:20 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.Device org.traccar.web.client.model.DataService.addDevice(org.traccar.web.shared.model.Device)' threw an unexpected exception: java.lang.IllegalStateException: Transaction not active



INFO   | jvm 1    | 2015/01/08 17:58:34 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/01/08 17:59:20 | 2015-01-08 17:59:19.976:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/01/08 17:59:20 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.Device org.traccar.web.client.model.DataService.addDevice(org.traccar.web.shared.model.Device)' threw an unexpected exception: java.lang.IllegalStateException: Transaction not active

**Comment by tananaev** [comment]
Protocol hasn't changed, but you might want to update Client because recent versions contain important bug fixes.

**Comment by alucionet** [comment]
I have been running the latest software provided via Google Play.
I just reinstalled the server and client to the latest version.

I found other error message:
2015-01-09 09:53:20  WARN: Connection reset by peer - java.io.IOException (FileDispatcherImpl.java:-2)
2015-01-09 09:53:20  INFO: Closing connection by exception
2015-01-09 09:53:20  INFO: Closing connection by disconnect

I just tried playing with the GPS source provider, with the source set to GPS, the client reports the following:
2015-01-09 09:55:18 DEBUG: [5005 <- 10.8.8.161] - HEX: 24504749442c41303030303032464542373136352a33310d0a
and no response from the server.

When I use Mixed source as GPS provider, it has better result:
2015-01-09 09:55:33 DEBUG: [5005 <- 10.8.8.161] - HEX: 244750524d432c3032353533362e3634382c412c303731362e313338372c532c31313234342e353939342c452c302e30302c302e30302c3039303131352c2c2a31310d0a
2015-01-09 09:55:33 DEBUG: [5005 -> 10.8.8.161] - HEX: 4f4b310d0a


Do you know why?

**Comment by alucionet** [comment]
From netstat, it seems like the connections were made to tcp6 instead of tcp.
tcp6       0      1 10.8.9.1:8500           124.195.117.127:36658   FIN_WAIT1  
tcp6       0      1 10.8.9.1:8500           120.168.1.146:39494     FIN_WAIT1  
tcp6       0      1 10.8.9.1:8500           120.164.46.148:1936     FIN_WAIT1  


I just disabled tcp6 and now no data is shown on the logs. 
I still see data coming in from the devices by sniffing packets on my router, but traccar is not processing it.
I see it listening to the right ports:
[root@estore logs]# netstat -an | grep 8500
tcp        0      0 0.0.0.0:8500            0.0.0.0:*               LISTEN     
[root@estore logs]# netstat -an | grep 5005
tcp        0      0 0.0.0.0:5005            0.0.0.0:*               LISTEN     



2015-01-09 10:11:59  INFO: Starting server...
2015-01-09 10:11:59  INFO: Operating System name: Linux version: 3.14.23-100.fc19.x86_64 architecture: amd64
2015-01-09 10:11:59  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.65-b04
2015-01-09 10:11:59  INFO: Memory Limit heap: 1310mb non-heap: 214mb
^C
[root@estore logs]# service iptables status
Redirecting to /bin/systemctl status  iptables.service
iptables.service - IPv4 firewall with iptables
   Loaded: loaded (/usr/lib/systemd/system/iptables.service; disabled)
   Active: inactive (dead)

**Comment by tananaev** [comment]
Note that GPS does not work indoors, so no location updates is expected behavior. On the other hand mixed provider can use network location which is available all the time. That explains why one works and another one doesn't.

**Comment by alucionet** [comment]
Yes, but is that the expected behaviour?
Data coming in and no response from server until the connection is somehow timed out or disconnected?

**Comment by tananaev** [comment]
Yes, the first message is just a login with IMEI. It doesn't have any location info.

**Comment by alucionet** [comment]
OK. But the connection is still active. Is there a time out mechanism? How long?

**Comment by tananaev** [comment]
You can enable timeout on the server, but by default there is none.

**Comment by alucionet** [comment]
How to enable the timeout on the server? 
If a device, with no GPS data has active connection to the server and just waits forever like the case that I have now, moves to an area with GPS data...what should happen?
Why don't the server just disconnect/release the connection even the device only sends login data?
That way, once the device has valid GPS data, it can resume sending data to the server.

This still has not resolved the main issue I reported.
Do you have any ideas on the tcp/tcp6 problem?

**Comment by alucionet** [comment]
I setup a new server on a different machine, and disable IPv6.
I still see the following:
root@bear:~ $ netstat -an | grep 5020
tcp        0      0 0.0.0.0:5020            0.0.0.0:*               LISTEN     
tcp        0      0 10.11.3.2:5020          120.168.1.144:38628     ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.112.208:35983   ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.0.239:35167     ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.1.75:41835      ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.118.14:33793    ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.113.136:32762   ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.1.107:33414     ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.114.5:33725     ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.1.165:32751     ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.119.80:35418    ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.113.196:32846   ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.0.163:35145     ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.0.44:40999      ESTABLISHED
tcp        0      0 10.11.3.2:5020          114.4.23.126:16902      ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.115.118:32955   ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.115.152:35328   ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.164.46.108:2265     ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.0.208:35018     ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.1.113:35236     ESTABLISHED
tcp        0      0 10.11.3.2:5020          114.4.23.102:4318       ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.164.44.69:1971      ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.164.40.246:2222     ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.164.43.181:2892     ESTABLISHED
tcp        0      0 10.11.3.2:5020          114.4.23.106:10785      ESTABLISHED
tcp        0      0 10.11.3.2:5020          124.195.117.254:35174   ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.164.46.194:2348     ESTABLISHED
tcp        0      0 10.11.3.2:5020          120.168.1.97:41767      ESTABLISHED




Many hung connections while on the log file there are no activities.
These connection come from Meitrack devices.

**Comment by tananaev** [comment]
Are you using the latest version? In the latest one all the issues you mentioned are fixed.

**Comment by alucionet** [comment]
yes..as i mentioned ...yesterday i setup yet another completely different server to host traccar. I downloaded the latest 64 bit linux version from traccar website.  The problem stays the same. Now i have 2 traccar servers giving me the same behavior.

**Comment by alucionet** [comment]
I can let you login to one of the servers if you want. Or if you can tell me how to troubleshoot this further, i would be more than willing to help.

**Comment by alucionet** [comment]
I can let you login to one of the servers if you want. Or if you can tell me how to troubleshoot this further, i would be more than willing to help.

**Comment by tananaev** [comment]
Please try following version:
https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

If still doesn't work I need tracker-server.log file for further investigation.

**Comment by alucionet** [comment]
Here's the logfile output:

2015-01-10 11:43:53  INFO: Operating System name: Linux version: 3.14.23-100.fc19.x86_64 architecture: amd64
2015-01-10 11:43:53  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.65-b04
2015-01-10 11:43:53  INFO: Memory Limit heap: 1310mb non-heap: 214mb
2015-01-10 11:43:53  INFO: Version: 2.10-SNAPSHOT


No data whatsoever is recorded, although my router records that there are traffic going and and out from the device. 


Here's what happen when I telnet manually to the meitrack port:

2015-01-10 11:49:35  INFO: Closing connection by disconnect
2015-01-10 11:49:38 DEBUG: [5020 <- 10.8.8.11] - HEX: 0d0a
2015-01-10 11:49:38 DEBUG: [5020 <- 10.8.8.11] - HEX: 0d0a
2015-01-10 11:49:39 DEBUG: [5020 <- 10.8.8.11] - HEX: fff4fffd06
2015-01-10 11:49:39  INFO: Closing connection by disconnect




So, the tracker listens on the right port, but when there is data from the device, somehow it is not doing anything. Not even logging the raw data.
I tested this on both my servers and both give the same behavior.

Have you looked into the data from my router?
ether2
0000: 00 24 81 06 36 ed 00 0c 42 f4 72 e0 08 00 45 00 .$..6... B.r...E.
0010: 00 2c 01 1b 00 00 30 06 87 4f 7c c3 72 96 0a 08 .,....0. .O|.r...
0020: 09 01 8d b4 13 9c 02 2d 87 00 00 00 00 00 60 02 .......- ......`.
0030: 7d 78 ee 31 00 00 02 04 05 50 }x.1.... .P

0010: 00 2c 00 00 40 00 40 06 38 6a 0a 08 09 01 7c c3 .,..@.@. 8j....|.
0020: 72 96 13 9c 8d b4 a7 88 3a ac 02 2d 87 01 60 12 r....... :..-..`.
0030: 72 10 16 f0 00 00 02 04 05 b4 00 00 r....... ....

0000: 00 24 81 06 36 ed 00 0c 42 f4 72 e0 08 00 45 00 .$..6... B.r...E.
0010: 00 28 01 1c 00 00 30 06 87 52 7c c3 72 96 0a 08 .(....0. .R|.r...
0020: 09 01 8d b4 13 9c 02 2d 87 01 a7 88 3a ad 50 10 .......- ....:.P.
0030: 7d 78 23 45 00 00 }x#E..



This is communication between the device and the server. It seems like traccar responded somehow, but I cannot tell what kind of respond and why does it not log to the logfile?

**Comment by tananaev** [comment]
All data should be logged. Maybe it's just TCP handshake messages?

**Comment by alucionet** [comment]
If they were just handshake messages, why do you keep the connections open for so long? My Traccar crashed after a few days running with error Too Many Open Files.
![traccar error](https://cloud.githubusercontent.com/assets/7633285/5873798/dd29e918-a32c-11e4-8129-a20da9da7edd.jpg)

**Comment by alucionet** [comment]
I just found a fresh log with the following messages leading to Traccar stalling...

There are hundreds of lines like the following and no data is recorded:
2015-01-23 18:32:32  WARN: netty warning: Failed to accept a connection.
2015-01-23 18:32:33  WARN: netty warning: Failed to accept a connection.
2015-01-23 18:32:34  WARN: netty warning: Failed to accept a connection.
2015-01-23 18:32:35  WARN: netty warning: Failed to accept a connection.
2015-01-23 18:32:36  WARN: netty warning: Failed to accept a connection.

I then restarted the machine:
2015-01-23 18:32:36  INFO: Shutting down server...
Immediately followed by hundreds of the following messages:
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect
2015-01-23 18:32:37  INFO: Closing connection by disconnect

then it restarts the traccar:

2015-01-23 18:32:41  INFO: Starting server...
2015-01-23 18:32:41  INFO: Operating System name: Linux version: 3.17.7-300.fc21.x86_64 architecture: amd64
2015-01-23 18:32:41  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 25.25-b02
2015-01-23 18:32:41  INFO: Memory Limit heap: 763mb non-heap: 0mb
2015-01-23 18:32:41  INFO: Version: 2.10-SNAPSHOT

Data starts coming in again:
2015-01-23 18:32:54 DEBUG: [5020 <- 120.168.1.61] - HEX: 2424693134372c3031333737373030313137383233332c4141412c33352c2d372e3236363531362c3131322e3734333535352c3135303132333131323231392c412c352c31372c302c3232342c312e372c35302c333131323731382c31323533343533382c3531307c317c333530347c454246422c303030302c303030307c303030307c303030307c304132357c304242382c2c2a41430d0a

**Comment by tananaev** [comment]
Nothing changed in terms of managing connections. If you want to close connections after some timeout you can set `resetDelay` parameter.

**Comment by alucionet** [comment]
Where do I set it? in the conf file? <entry key='resetDelay'>xxxx</entry>  ?
What is the unit of xxx ? ms ? s?

**Comment by alucionet** [comment]
I found https://github.com/tananaev/traccar/issues/887.

Seems like after setting resetDelay, everything works normal now.
Devices that were not registering data starts to show up properly now.

I really think you need to dig down to solving this issue permanently rather than setting the resetDelay data.

**Comment by tananaev** [comment]
There is no way to solve it permanently.

**Comment by alucionet** [comment]
I found https://github.com/tananaev/traccar/issues/887.

Seems like after setting resetDelay, everything works normal now.
Devices that were not registering data starts to show up properly now.

I really think you need to dig down to solving this issue permanently rather than setting the resetDelay data.
