### ISSUE TITLE
Teltonika Remote Config

### ISSUE THREAD

**Issue by pallavt** [tananaev/traccar#1031]
Has anyone succeeded in configuring teltonika device remotely (via GPRS, not SMS) without send the initial push/binary SMS?

In other words:
Under normal circumstance :
Device -> Server = IMEI
Server -> Device = 1 or 0
Device -> Server = Location and other Data.

Is the following possible:
Device -> Server = IMEI
Server -> Device = Config Data

**Comment by DjameleddineBourahla** [comment]
It's impossible
