### ISSUE TITLE
identify traccar version

### ISSUE THREAD

**Issue by undee123** [tananaev/traccar#1032]
Hi!

How can I identify the traccar version I've installed on my web server?

**Comment by tananaev** [comment]
Unfortunately there is no easy way, but if you really need to know then tell me what libraries you have in the lib folder and I'll try to find out Traccar version based on that info.

**Comment by vitalidze** [comment]
Actually you can look at `pom.properties` file in `tracker-server.jar`, for example.

````
$ unzip -p tracker-server.jar META-INF/maven/org.traccar/traccar/pom.properties
#Generated by Maven
#Thu Feb 28 20:51:18 NZDT 2013
version=2.1-SNAPSHOT
groupId=org.traccar
artifactId=traccar
````

This means that the version is 2.1
