### ISSUE TITLE
Tracker LK106 protocol H02 SOS option

### ISSUE THREAD

**Issue by joepr** [tananaev/traccar#1034]
Hello traccar team

I have 2 LK106 trackers that are working perfectly fine with traccar however this trackers have a SOS button that when is pressed for 3 seconds it sends a SMS to the admin phone number and it also sends a signal to the server. When testing this option I receive the following data string . Note: this log file is not from traccar is just the raw data received from the computer.

This is when its in normal reporting mode
```
13.01.2015 03:43:41.637 |-> Length: 101
13.01.2015 03:43:41.637 |-> ASCII:  *HQ,4106012030,V1,034334,A,1828.3057,N,06704.8021,W,016.20,344,130115,FFFFFBFD,310,410,51217,61252,6#
13.01.2015 03:43:41.637 |-> Hex:    2a48512c343130363031323033302c56312c3033343333342c412c313832382e333035372c4e2c30363730342e383032312c572c3031362e32302c3334342c3133303131352c46464646464246442c3331302c3431302c35313231372c36313235322c3623
13.01.2015 03:43:41.713 |-> Dez:    [42,72,81,44,52,49,48,54,48,49,50,48,51,48,44,86,49,44,48,51,52,51,51,52,44,65,44,49,56,50,56,46,51,48,53,55,44,78,44,48,54,55,48,52,46,56,48,50,49,44,87,44,48,49,54,46,50,48,44,51,52,52,44,49,51,48,49,49,53,44,70,70,70,70,70,66,70,68,44,51,49,48,44,52,49,48,44,53,49,50,49,55,44,54,49,50,53,50,44,54,35]
```
This is when the SOS button is  pressed
```
13.01.2015 03:43:42.245 |-> Length: 90
13.01.2015 03:43:42.245 |-> ASCII:  $A 0@()�pG������6)��D
$A 0@()�pG������6)��D
13.01.2015 03:43:42.245 |-> Hex:    24410601203003401213011518282990060670479706000000fbfffbffff000e0400000000013629c811ef440d24410601203003401713011518282990060670479706000000fbfffbffff000e0500000000013629c811ef440e
13.01.2015 03:43:42.320 |-> Dez:    [36,65,6,1,32,48,3,64,18,19,1,21,24,40,41,144,6,6,112,71,151,6,0,0,0,251,255,251,255,255,0,14,4,0,0,0,0,1,54,41,200,17,239,68,13,36,65,6,1,32,48,3,64,23,19,1,21,24,40,41,144,6,6,112,71,151,6,0,0,0,251,255,251,255,255,0,14,5,0,0,0,0,1,54,41,200,17,239,68,14]
```
Ok so I will like to  know if anyone here can point me to the right direction. How do I decode this SOS message or if any expert here could decode and tell me what info its shown when that SOS button is pressed. I hope it says info about the IMEI, date and time. 

Best Regards 
Joe

**Comment by tananaev** [comment]
You can find description here:
https://dl.dropboxusercontent.com/s/6e6yrsjdc4q62nj/GPS%E6%9D%9E%EF%B9%81%E6%B5%87%E7%92%81%E6%83%A7%EE%98%AC%E9%8D%97%E5%BF%9A%EE%86%85%28%E6%BE%B6%E2%95%83%E6%83%94%E9%8D%8F%E3%84%A6%E6%9E%83%29%E7%91%99%E5%8B%AD%E2%96%BC.doc

Unfortunately the document is in Chinese, but you can use Google Translate to get some info from it.
