### ISSUE TITLE
Geocoding table

### ISSUE THREAD

**Issue by cristianormoraes** [tananaev/traccar#1037]
@tananaev 

Hi friend, how you doing ?

Last night I was thinking to save the geocoding in a table like:

[ id / latitude / longitude / address ]

So before request the geocoding from Google API I check it in this table, if have row with a coordinate less than 50 meters I get this geocoding id and put it in position table, else I will get this geocode from Google API and insert it in this table.

What you think about this?

**Comment by tananaev** [comment]
I think it will bloat very fast.
