### ISSUE TITLE
can't get location data in gt06

### ISSUE THREAD

**Issue by Anurag912** [tananaev/traccar#1039]
hello

i have created own application by refering traccar code. My device is gt06. The code works fine and i am getting login message from terminal which is having protocol no. 0x01 (Please refer concox protocol guide for gt06) and i am sending it response correctly.After that terminal sends me packet having protocol no. 0x13, i am sending responce to this packet too and at last i am getting packet with protocol no.  0x8b which is meaningless and i am getting no location data from terminal.Please help me in this issue..
Thanx..

**Comment by tananaev** [comment]
Can you provide messages that you receive and send in hex format?

**Comment by Anurag912** [comment]
Following is my program's output what i get from terminal and what response i sent to terminal:

First Packet Received:
78   78	d	1	3	58	89	90	50	97	91	22	0	8	7f	f6	d	a

IMEI NO:358899050979122

Response packet sent:78	78	5	1	0	8	44	1d	d	a

Second Packet Received:78	78	a	13	4	5	4	0	2	0	9	fa	e7	d	a

Response packet sent:78	78	5	13	0	9	65	b9	d	a

Third Packet Received:
78   78	 d	8b	1	94	5a	c	21	0	7b	eb	0	a	2f	14	d	a

**Comment by bernamaxim** [comment]
I have this function :

```private static void sendResponse(Channel channel, int type, int index) {
		if (channel != null) {
			ChannelBuffer response = ChannelBuffers.directBuffer(10);
			response.writeByte(0x78);
			response.writeByte(0x78); // header
			response.writeByte(0x05); // size
			response.writeByte(type);
			response.writeShort(index);
			response.writeShort(Crc.crc16Ccitt(response.toByteBuffer(2, 4)));
			response.writeByte(0x0D);
			response.writeByte(0x0A); // ending
			channel.write(response);
		}
	}
```

I have many type of Msg from GT06, and I tried to solve :

My Type MSG :
```private static final int MSG_LOGIN = 0x01;
	private static final int MSG_GPS = 0x10;
	private static final int MSG_LBS = 0x11;
	private static final int MSG_GPS_LBS = 0x12;
	private static final int MSG_STATUS = 0x13;
	private static final int MSG_SATELLITE = 0x14;
	private static final int MSG_STRING = 0x15;
	private static final int MSG_GPS_LBS_STATUS = 0x16;
	private static final int MSG_LBS_PHONE = 0x17;
	private static final int MSG_LBS_EXTEND = 0x18;
	private static final int MSG_LBS_STATUS = 0x19;
	private static final int MSG_GPS_PHONE = 0x1A;
	private static final int MSG_GPS_LBS_EXTEND = 0x1E;
	private static final int MSG_INITIALIZATION = 0x5B;
	private static final int MSG_UNKNOWN = 0x8B; ```

And I separated this type with :

```int type = buf.readUnsignedByte();```

Then I declared it :

```else if (type == MSG_UNKNOWN) {
			
			if (buf.readableBytes() > 6) {					
				buf.skipBytes(buf.readableBytes() - 6);
			}
			int index = buf.readUnsignedShort();			
			sendResponse(channel, type, index);			
			Log.info("Unknown Protocol: " + deviceId + " -> " + imei);
			
		}
```

msg_unknown will be ignored and then device will send location.

**Comment by Anurag912** [comment]
Thanks for your reply,

I have done what you told me to do but its still not working. 
 After getting MSG_UNKNOWN packet, I am getting login packet again

**Comment by tananaev** [comment]
I checked responses and they seem to be correct. I think the problem is on the device side. Maybe you need to configure it to send data.

**Comment by Anurag912** [comment]
You were right tananaev. Actually terminal was unable to connect with satelite. But Its working now.
thanks for your valuable help.

Thanks   tananaev and bernamaxim
You both helped me a lot..

**Comment by bernamaxim** [comment]
Sure, If device was not connect to satellite, it not send location data (Msg Type : 12).

It just repeated login, heartbeat, login, heartbeat and so on.

You also can check status with SMS Command : 
```
status#
```

Check parameter of GPS, if GPS :OFF, it cannot be send location data.

**Comment by Anurag912** [comment]
Yah sure,
Thanks

**Comment by testapp99912** [comment]
Hi,
Traccar server(open source java based one ) is able to get the location data from terminal(GPS unit) after a successful login message. 
However, it doesn't seem to work with the python server, the terminal seems to be sending only the login messages even if the python script(TCP) responded to that. I don't see the location data coming from terminal.  I compared the login success response sent by the Traccar server(java) with the python script, both look same but the terminal doesn't respond to python based server. Can you please let me know if I need to change something to make the python server work. The terminal (GPS unit) is based on GT06 protocol. 
I came across the following thread but don't find a solution to this.
https://stackoverflow.com/questions/43697257/gt06-gps-module-tcp-server-in-python

Please help me with this issue.

**Comment by tananaev** [comment]
Use Wireshark and compare responses from Traccar and your Python application.

**Comment by testapp99912** [comment]
Thanks tananaev. I don't have direct access to the desktop GUI and I am a novice  wireshark user. So, I prepared a small tcp client to send the data to Traccar and as well as python servers to see how do they respond. To my surprise, both the servers replied the same. 
7878050104E51F960D0A --> ACK to login message sent by terminal(GPS UNIT).

Please let me know if you sense something wrong. 

socket options: 
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

**Comment by tananaev** [comment]
If response is exactly the same then it should work.

**Comment by testapp99912** [comment]
hmm, I am lost, not sure what is going on...  thanks tananaev

**Comment by tananaev** [comment]
You are clearly missing something. If the response is exactly the same, it would work both or neither.

**Comment by testapp99912** [comment]
please let me know if you would like to view the code , I can put the relevant part of the code on this thread.

**Comment by tananaev** [comment]
I don't want to look at the code. I want to look at the pcap file for both Traccar and your app.

**Comment by Saudbintariq1** [comment]
Dears I have a shortcut for the login msg and response problem. I am sending back the same data to terminal that i am receiving on my server and it looks good for me but i am facing the big issue which is when i receive data from terminals how i can know that the data is from which terminal?
I have this Data from terminal: 78-78-1F-12-11-06-12-07-28-31-C8-01-AD-EB-C2-03-7F-FF-AC-24-D5-0B-02-7A-02-00-AB-00-4F-93-00-1D-BF-56-0D-0A

How i can find out that this data is from device 1 or device 2 or device 100?

**Comment by tananaev** [comment]
@Saudbintariq1, first of all your problem has nothing to do with the topic, so if you want to discuss it, you should create a separate thread.

As for the problem itself, each TCP connection uses different socket object, so you can easily identify which device data is coming from.

**Comment by ashish2002** [comment]
Hi,

I have written code to parse GT06 protocol on our server, I am able to get login information, but not getting location information. As per blog, comments on forum, i have kept the device in open space means under the sky however, not getting location points but getting login details continuously.  here, I just came to know that "information check" and "error check" values are different in response from device, i could not figure out anything from error log value in below values. 

78 78 0D 01 	xx xx 51 10 22 63 63 06 	   00 04 		BA B6 		0D 0A
78 78 0D 01 	xx xx 51 10 22 63 63 06 	00 06 		99 A4 		0D 0A
78 78 0D 01 	xx xx 51 10 22 63 63 06 	00 08 		70 DA 		0D 0A
78 78 0D 01 	xx xx 51 10 22 63 63 06 	00 0A 		53 C8 		0D 0A
78 78 0D 01 	xx xx 51 10 22 63 63 06 	00 0C 		36 FE 		0D 0A
78 78 0D 01 	xx xx 51 10 22 63 63 06 	00 0E 		15 EC 		0D 0A
78 78 0D 01 	xx xx 51 10 22 63 63 06 	00 10 		EC 13 		0D 0A

even i am sending response to login request from device as per document. however, not getting location information.

please help me out, i have already spend lot of efforts to get the solutions.

Thanks in advance

**Comment by tananaev** [comment]
You provided login messages. If that's all you get, it probably means that you are not sending proper acknowledgement.

**Comment by ashish2002** [comment]
Hi Tananaev,

I have passed acknowledgement with different values like

default one:  
byte [] b1 = new byte[]{(byte)0x78, (byte)0x78, (byte)0x05, (byte)0x01, (byte)0x00, (byte)0x01, (byte)0xD9, (byte)0xDC, (byte)0x0D, (byte) 0x0A};

Tried below one:
byte [] b1 = new byte[]{(byte)0x78, (byte)0x78, (byte)0x05, (byte)0x12, (byte)0x00, (byte)0x01, (byte)0xD9, (byte)0xDC, (byte)0x0D, (byte) 0x0A};

can you please tell me what exact values i need to pass as an acknowledgement. 

I am stuck here for more than 3 days.

Thanks

**Comment by tananaev** [comment]
If you want to discuss it I would recommend creating a separate thread.

**Comment by ashish2002** [comment]
Hi Tananaev,

i have posted new issue #3282 as per your suggestion, please provide me solution.

Thanks and Regards
