### ISSUE TITLE
HTTP protocol logfile

### ISSUE THREAD

**Issue by Bazowsky** [tananaev/traccar#1041]
Where to find HTTP servlet logfile.

"tracker-server.log" gives nothing.
Trying to change logger.level in .conf to DEBUG or TRACE, but get nothing new.

**Comment by vitalidze** [comment]
It's in `wrapper.log*` files located under same folder.

**Comment by Bazowsky** [comment]
Да, я изучал его, но там совсем нет никаких записей кроме INFO уровня jwm1
Ожидал что-то по типу access \ error log апача, jetty вообще имеет подробный лог?
'25.34.218.168 - - [22/Jan/2015:14:32:03 +0500] "GET /pages/login.html HTTP/1.1" 200 1922'

**Comment by vitalidze** [comment]
Не знаю, по умолчанию нет. Но можно поставить перед jetty апач или nginx, если нужен такой лог.

**Comment by tananaev** [comment]
Вот тут есть пример кода как включить лог:
http://www.eclipse.org/jetty/documentation/9.1.1.v20140108/configuring-jetty-request-logs.html

**Comment by Bazowsky** [comment]
То что нужно, попробую!
*thumb_UP
