### ISSUE TITLE
Traccar on Ubuntu Server 14

### ISSUE THREAD

**Issue by bossb2** [tananaev/traccar#1042]
Hello,

I'm trying to install traccar in Ubuntu Server 14.04. It's already running when using the default database (h2), but when I tried using mysql, it got an error

Unable to get the path for 'opt.traccar/bin/./wrapper' -Success

I only changed the following lines in the configuration file.

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar_gps?allowMultiQueries=true&amp;autoReconnect=true</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'>admin</entry>

When I looked at the wrapper log, it mentioned 

oejsh.ContextHandler:stopped o.e.j.w.WebAppContext{/,file:/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-/webapp/},opt/traccar/traccar-web.war

My java version is 1.7.0_65 (IcedTea 2.5.3)

Hope you can help me with this problem.

Thanks
Antonio

**Comment by tananaev** [comment]
Are you sure you haven't touched any other files? Can I see full wrapper.log?

**Comment by bossb2** [comment]
STATUS | wrapper  | 2015/01/23 12:57:48 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/01/23 12:57:48 | Java Service Wrapper Community Edition 64-bit 3.5.25
STATUS | wrapper  | 2015/01/23 12:57:48 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/01/23 12:57:48 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/01/23 12:57:48 | 
STATUS | wrapper  | 2015/01/23 12:57:49 | Launching a JVM...
INFO   | jvm 1    | 2015/01/23 12:57:49 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/01/23 12:57:50 | 2015-01-23 12:57:50.512:INFO:oejs.Server:jetty-8.1.16.v20140903
INFO   | jvm 1    | 2015/01/23 12:57:50 | 2015-01-23 12:57:50.529:INFO:oejw.WebInfConfiguration:Extract jar:file:/opt/traccar/traccar-web.war!/ to /tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-/webapp
INFO   | jvm 1    | 2015/01/23 12:57:51 | 2015-01-23 12:57:51.079:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
INFO   | jvm 1    | 2015/01/23 12:57:51 | 2015-01-23 12:57:51.117:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8082
STATUS | wrapper  | 2015/01/23 13:16:28 | TERM trapped.  Shutting down.
INFO   | jvm 1    | 2015/01/23 13:16:29 | 2015-01-23 13:16:29.236:INFO:oejsh.ContextHandler:stopped o.e.j.w.WebAppContext{/,file:/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-/webapp/},/opt/traccar/traccar-web.war
STATUS | wrapper  | 2015/01/23 13:16:29 | <-- Wrapper Stopped


Now that I looked at it again, it did say no support for JSP. But it was working when I was using the h2 database.

**Comment by tananaev** [comment]
Ignore JSP support warning. Traccar does not use JSP.

How did you start the service?

**Comment by bossb2** [comment]
I just used the command from the Linux Installation Guide.

sudo /opt/traccar/bin/traccar start

**Comment by tananaev** [comment]
Does it work if you change back to H2 database?

**Comment by bossb2** [comment]
Hi again,

I tried a few things and done some re-installing of traccar and reboot of the machine.

What I noticed was that when I changed the configuration file (I did not change the content, just save the file again), it would give cause an error like the one I mentioned. 

If I don't change the configuration it will work fine no matter how times I restart the service. But when I change something something in the configuration, it does't work anymore even if revert it back to its original configuration.

**Comment by tananaev** [comment]
Just use different text editor.

**Comment by bossb2** [comment]
Hi anton,

I got off from office yesterday so I wasn't able to continue.
Just earlier, I think I found the reason though I tried it on Ubuntu 12. 
When I edited the configuration file, I change the ownership of the file and I think that's what caused it cause when I change the ownership back to root, it already works fine.

Anyway, thanks and sorry for the trouble.
antonio
