### ISSUE TITLE
Error running script ./package.sh

### ISSUE THREAD

**Issue by guilhermesouza** [tananaev/traccar#1043]
Error running script ./package.sh                                                              
```
Web application archive found
Java wrapper package found
updating: tracker-server.jar (deflated 7%)
updating: README.txt (deflated 38%)
sed: 1: "out/bin/traccar": invalid command code o
sed: 1: "out/bin/traccar": invalid command code o
sed: 1: "out/bin/traccar": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
/usr/local/bin/makeself: line 328: test: too many arguments
Header is 498 lines long

About to compress 23156 KB of data...
Adding files to archive named "traccar.run"...
a .
a ./bin
a ./conf
a ./data
a ./lib
a ./logs
a ./traccar-web.war
a ./tracker-server.jar
a ./lib/h2-1.3.176.jar
a ./lib/javax.servlet-api-3.0.1.jar
a ./lib/jetty-all-server-8.1.15.v20140411.jar
a ./lib/libwrapper.so
a ./lib/log4j-1.2.17.jar
a ./lib/mysql-connector-java-5.1.30.jar
a ./lib/netty-3.9.0.Final.jar
a ./lib/postgresql-9.1-901-1.jdbc4.jar
a ./lib/wrapper-3.2.3.jar
a ./lib/wrapper.jar
a ./conf/traccar.cfg
a ./conf/wrapper.conf
a ./bin/traccar
a ./bin/wrapper
CRC: 1249613439
MD5: c9faa0ceee9825c93446162393be2dd1

Self-extractable archive "traccar.run" successfully created.
updating: traccar.run (deflated 0%)
updating: README.txt (deflated 44%)
```

**Comment by guilhermesouza** [comment]
I'm running the command on mac osx to package the traccar and this occurring the following error:

sed -i 's/tail -1/tail -n 1/g' out/bin/traccar
sed -i 's/@app.name@/traccar/g' out/bin/traccar
sed -i 's/@app.long.name@/traccar/g' out/bin/traccar
sed -i '/wrapper.java.classpath.1/i\wrapper.java.classpath.2=../tracker-server.jar' out/conf/wrapper.conf
sed -i '/wrapper.app.parameter.1/i\wrapper.app.parameter.2=$app/conf/traccar.cfg' out/conf/wrapper.conf
sed -i 's/<YourMainClass>/org.traccar.Main/g' out/conf/wrapper.conf
sed -i 's/@app.name@/traccar/g' out/conf/wrapper.conf
sed -i 's/@app.long.name@/traccar/g' out/conf/wrapper.conf
sed -i 's/@app.description@/traccar/g' out/conf/wrapper.conf
sed -i 's/wrapper.logfile=..\/logs\/wrapper.log/wrapper.logfile=..\/logs\/wrapper.log.YYYYMMDD\nwrapper.logfile.rollmode=DATE/g' out/conf/wrapper.conf

sed: 1: "out/bin/traccar": invalid command code o
sed: 1: "out/bin/traccar": invalid command code o
sed: 1: "out/bin/traccar": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o
sed: 1: "out/conf/wrapper.conf": invalid command code o

/usr/local/bin/makeself: line 328: test: too many arguments

**Comment by tananaev** [comment]
The script is intended for Linux. I recommend Ubuntu.
