### ISSUE TITLE
SQLException 

### ISSUE THREAD

**Issue by cristianormoraes** [tananaev/traccar#1046]
What this exception means ?

 WARN: Could not retrieve transation read-only status server                        - java.sql.SQLException (SQLError.java:996)

There are a lot of connections in database and the server is locking the table?

**Comment by tananaev** [comment]
Are you using MySQL database?

**Comment by cristianormoraes** [comment]
Yes

**Comment by tananaev** [comment]
I think it's a problem with MySQL config or maybe a bug in your version.
