### ISSUE TITLE
installation issue.

### ISSUE THREAD

**Issue by KrishnaKumar12391** [tananaev/traccar#1048]
we need to configure the mvt340 .which one is supporting version and how to install? i had download 2.0 its didnt have the .exe file so please help me,, how to install 2.0? to we need to configure the mvt340 .which one is supporting version in windows 7 and how to install? i had download 2.0 its didnt have the .exe file so please help me,, how to install 2.0?

**Comment by tananaev** [comment]
Can you please move your topic into description and add short topic name.

**Comment by KrishnaKumar12391** [comment]
please ans me..

**Comment by KrishnaKumar12391** [comment]
please ans me..

**Comment by KrishnaKumar12391** [comment]
please ans me..

**Comment by gioramies** [comment]
Hi.

traccar-windows-32-2.11 has an exe.file, is the latest version.

**Comment by tananaev** [comment]
You should install latest version from here:
https://www.traccar.org/download.jsp

On the device list page version 2.0 means that all Traccar version starting from 2.0 support your device. It doesn't mean that you need to get that specific version.

**Comment by KrishnaKumar12391** [comment]
ok,, thank you..
