### ISSUE TITLE
configure issue.

### ISSUE THREAD

**Issue by KrishnaKumar12391** [tananaev/traccar#1049]
i had install the traccar2.11 for mvt340. and now need to configure the device so want ip and port but i was open the server use this (localhost:8082).. what is the ip and port of this..

**Comment by gioramies** [comment]
Hi.
You can check the ports at https://www.traccar.org/devices/

MVT340	Yes	2.0 (meitrack/5020)

Regards.

**Comment by tananaev** [comment]
Port is 5020. IP address is your public IP address.

**Comment by KrishnaKumar12391** [comment]
ok nice.. and how to develop the menus or additional features in traccar server? i was import the traccar-server.war but its not working in eclipse. so how to configure to eclipse for development and which file i need to import..

**Comment by KrishnaKumar12391** [comment]
i was set ip 2.50.57.42 and port is 5020 but didn't get any data from device..

**Comment by tananaev** [comment]
Your port is closed. Check here: http://www.yougetsignal.com/tools/open-ports/.

As for development, you need to import a project not war file.

**Comment by KrishnaKumar12391** [comment]
how to get the database to sqlserver ?
and i need to import a project, where it's available?

**Comment by tananaev** [comment]
Do you mean MS SQL server? You need to get JDBC driver for it and modify database connection properties in Traccar config file.

Project is here: https://github.com/tananaev/traccar.

**Comment by KrishnaKumar12391** [comment]
how to get Jdbc driver which one is suitable for this?

and, i was import that zip file in eclipse but after run this project its showing this error popup (The selection can't be launched, and there are no recent launches)

**Comment by tananaev** [comment]
You can try official Microsoft driver or jTDS.

Last time I tried there were some compatibility issues with Eclipse maven plugin. I recommend to use NetBeans.
