### ISSUE TITLE
Проблемы с версией 2.11

### ISSUE THREAD

**Issue by napaster** [tananaev/traccar#1053]
Доброго времени суток. Столкнулся со следующей проблему при запуске версии 2.11
Установил mysql, не maridb, установил jre8
при дапуске ./traccar console с включенным debug в wrapper получаю следущий вывод в консоль:
Running traccar...

<pre>wrapper  | --&gt; Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.25
wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Release time: 2014/06/12 00:00:00
wrapper  | Build time:   2014/06/13 16:02:00
wrapper  | Timezone:     NOVT (NOVT) Offset: -21600, hasDaylight: 0
wrapper  | Using tick timer.
wrapper  |
wrapper  | Environment variables (Source | Name=Value) BEGIN:
wrapper  |   P---- | _=/opt/traccar/bin/./wrapper
wrapper  |   P---- | HISTCONTROL=ignorespace
wrapper  |   P---- | HOME=/root
wrapper  |   P---- | LANG=en_US.UTF-8
wrapper  |   P---- | LOGNAME=root
wrapper  |   P---- | MAIL=/var/spool/mail/root
wrapper  |   P---- | MC_SID=312
wrapper  |   P---- | MC_TMPDIR=/tmp/mc-root
wrapper  |   P---- | PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_                                                                                                               perl:/usr/bin/core_perl
wrapper  |   P---- | PWD=/opt/traccar/bin
wrapper  |   P---- | SHELL=/bin/bash
wrapper  |   P---- | SHLVL=3
wrapper  |   P---- | SSH_CLIENT=192.168.1.8 50108 22
wrapper  |   P---- | SSH_CONNECTION=192.168.1.8 50108 192.168.1.12 22
wrapper  |   P---- | SSH_TTY=/dev/pts/0
wrapper  |   P---- | TERM=xterm
wrapper  |   P---- | USER=root
wrapper  |   ---W- | WRAPPER_ARCH=x86
wrapper  |   ---W- | WRAPPER_BIN_DIR=/opt/traccar/bin
wrapper  |   ---W- | WRAPPER_BITS=64
wrapper  |   ---W- | WRAPPER_CONF_DIR=/opt/traccar/conf
wrapper  |   ---W- | WRAPPER_FILE_SEPARATOR=/
wrapper  |   ---W- | WRAPPER_HOST_NAME=gpstest
wrapper  |   ---W- | WRAPPER_HOSTNAME=gpstest
wrapper  |   P--W- | WRAPPER_INIT_DIR=/opt/traccar/bin
wrapper  |   ---W- | WRAPPER_LANG=en
wrapper  |   ---W- | WRAPPER_OS=linux
wrapper  |   ---W- | WRAPPER_PATH_SEPARATOR=:
wrapper  |   ---W- | WRAPPER_PID=441
wrapper  |   ---W- | WRAPPER_WORKING_DIR=/opt/traccar/bin
wrapper  |   P---- | XDG_RUNTIME_DIR=/run/user/0
wrapper  |   P---- | XDG_SESSION_ID=c2
wrapper  | Environment variables END:
wrapper  |
wrapper  | Use tick timer mutex=FALSE
wrapper  | active log file changed: ../logs/wrapper.log.20150129
wrapper  | Preparing to restart with mode 1.
wrapperp | server listening on port 32000.
wrapper  | Unable to resolve the real path of wrapper.java.command as a relative reference: java
wrapper  | Attempt to locate wrapper.java.command on system PATH: java
wrapper  | Resolved the real path of wrapper.java.command from system PATH: /usr/lib/jvm/java-8-jre/jre/bin/java
wrapper  | Magic number for file /usr/lib/jvm/java-8-jre/jre/bin/java: 0x7f454c46
wrapper  | Startup Timeouts: wrapper.startup.timeout=30, wrapper.startup.delay.console=0, wrapper.startup.delay.service=0, wra                                                                                                               pper.restart.delay=5
wrapper  | Ping settings: wrapper.ping.interval=5, wrapper.ping.interval.logged=1, wrapper.ping.timeout=30, wrapper.ping.alert                                                                                                               .threshold=7
wrapper  | Shutdown Timeouts: wrapper.startup.timeout=30, wrapper.shutdown.timeout=15, wrapper.jvm_exit.timeout=10, wrapper.jv                                                                                                               m_cleanup.timeout=10, wrapper.jvm_terminate.timeout=6593248
wrapper  | Launching a JVM...
wrapper  | Java Command Line:
wrapper  |   Command[0] : /usr/lib/jvm/java-8-jre/jre/bin/java
wrapper  |   Command[1] : -Djava.library.path=../lib
wrapper  |   Command[2] : -classpath
wrapper  |   Command[3] : ../lib/wrapper.jar:../tracker-server.jar
wrapper  |   Command[4] : -Dwrapper.key=2xNTqWcoPWExlNqg
wrapper  |   Command[5] : -Dwrapper.port=32000
wrapper  |   Command[6] : -Dwrapper.jvm.port.min=31000
wrapper  |   Command[7] : -Dwrapper.jvm.port.max=31999
wrapper  |   Command[8] : -Dwrapper.debug=TRUE
wrapper  |   Command[9] : -Dwrapper.pid=441
wrapper  |   Command[10] : -Dwrapper.version=3.5.25
wrapper  |   Command[11] : -Dwrapper.native_library=wrapper
wrapper  |   Command[12] : -Dwrapper.arch=x86
wrapper  |   Command[13] : -Dwrapper.cpu.timeout=10
wrapper  |   Command[14] : -Dwrapper.jvmid=1
wrapper  |   Command[15] : org.tanukisoftware.wrapper.WrapperSimpleApp
wrapper  |   Command[16] : org.traccar.Main
wrapper  |   Command[17] : /opt/traccar/conf/traccar.cfg
jvm 1    | WrapperManager Debug: WrapperManager class initialized by thread: main   Using classloader: sun.misc.Launcher$AppCl                                                                                                               assLoader@5c647e05
jvm 1    | WrapperManager: Initializing...
jvm 1    | WrapperManager Debug: JVM #1
jvm 1    | WrapperManager Debug: Running a 64-bit JVM.
jvm 1    | WrapperManager Debug: org.tanukisoftware.wrapper.WrapperManager package information:
jvm 1    | WrapperManager Debug:   Implementation Title: org.tanukisoftware.wrapper
jvm 1    | WrapperManager Debug:   Implementation Vendor: Tanuki Software, Ltd.
jvm 1    | WrapperManager Debug:   Implementation Version: 3.5.25
jvm 1    | WrapperManager Debug:   Is Sealed?: False
jvm 1    | WrapperManager Debug: org.tanukisoftware.wrapper.WrapperManager protection domain:
jvm 1    | WrapperManager Debug:   Location: file:/opt/traccar/lib/wrapper.jar
jvm 1    | WrapperManager Debug:     Size: 121,449
jvm 1    | WrapperManager Debug:     MD5: c2730df4dcbe5a4167baf53b6e939c13
jvm 1    | WrapperManager Debug: Registering shutdown hook
jvm 1    | WrapperManager Debug: Using wrapper
jvm 1    | WrapperManager Debug: Registered MBean with Platform MBean Server: org.tanukisoftware.wrapper:type=WrapperManager
jvm 1    | WrapperManager Debug: Load native library.  There are multiple possible file names and the first to be found will b                                                                                                               e used.  Errors loading non-existing files is normal and is only a problem if they all fail.
jvm 1    | WrapperManager Debug:   Attempt to load native library with name: libwrapper-linux-x86-64.so  Result: no wrapper-li                                                                                                               nux-x86-64 in java.library.path
jvm 1    | WrapperManager Debug:   Attempt to load native library with name: libwrapper.so  Result: Success!
jvm 1    | WrapperManager Debug:   Successfully loaded native library.
jvm 1    | WrapperManager Debug: Loaded localized resources.
jvm 1    | WrapperManager Debug: Calling native initialization method.
jvm 1    | WrapperJNI Debug: Inside native WrapperManager initialization method
jvm 1    | WrapperManager Debug: Java Version   : 1.8.0_31-b13 Java HotSpot(TM) 64-Bit Server VM
jvm 1    | WrapperManager Debug: Java VM Vendor : Oracle Corporation
jvm 1    | WrapperManager Debug: OS Name        : Linux
jvm 1    | WrapperManager Debug: OS Arch        : amd64
jvm 1    | WrapperManager Debug:
jvm 1    | WrapperManager Debug: WrapperManager.start(a org.tanukisoftware.wrapper.WrapperSimpleApp, args[&quot;/opt/traccar/conf/t                                                                                                               raccar.cfg&quot;]) called by thread: main
jvm 1    | WrapperManager Debug: Initial thread: main Priority: 5
jvm 1    | WrapperManager Debug: Control event monitor thread started.
jvm 1    | WrapperManager Debug: Communications runner thread started.
jvm 1    | WrapperManager Debug: Open socket to wrapper...Wrapper-Connection
jvm 1    | WrapperManager Debug: Startup runner thread started.
jvm 1    | WrapperManager Debug: Opened Socket from 31,000 to 32,000
jvm 1    | WrapperManager Debug: Send a packet KEY : 2xNTqWcoPWExlNqg
jvm 1    | WrapperManager Debug: handleBackend()
wrapperp | accepted a socket from 127.0.0.1 on port 31000
wrapperp | closing backend server.
wrapperp | read a packet KEY : 2xNTqWcoPWExlNqg
wrapper  | Got key from JVM: 2xNTqWcoPWExlNqg
wrapperp | send a packet LOW_LOG_LEVEL : 1
wrapperp | send a packet LOGFILE : ../logs/wrapper.log.20150129
wrapperp | send a packet PROPERTIES : (Property Values)
wrapper  | Start Application.
wrapperp | send a packet START : start
jvm 1    | WrapperManager Debug: Received a packet LOW_LOG_LEVEL : 1
jvm 1    | WrapperManager Debug: LowLogLevel from Wrapper is 1
jvm 1    | WrapperManager Debug: Received a packet LOGFILE : ../logs/wrapper.log.20150129
jvm 1    | WrapperManager Debug: Received a packet PROPERTIES : (Property Values)
jvm 1    | WrapperManager Debug: Received a packet START : start
jvm 1    | WrapperManager Debug: Java temporary directory: /tmp
jvm 1    | WrapperManager Debug: calling WrapperListener.start()
jvm 1    | WrapperManager Debug: WrapperListener.start runner thread started.
jvm 1    | WrapperManager Debug: Application start main thread: WrapperListener_start_runner Priority: 5
jvm 1    | WrapperSimpleApp Debug: start(args) Will wait up to 2 seconds for the main method to complete.
jvm 1    | WrapperSimpleApp Debug: invoking main method
jvm 1    | WrapperSimpleApp:
jvm 1    | WrapperSimpleApp Error: Encountered an error running main:
jvm 1    | WrapperSimpleApp Error: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 375;                                                                                                                columnNumber: 14; The content of element type &quot;properties&quot; must match &quot;(comment?,entry*)&quot;.
jvm 1    | WrapperSimpleApp Error:      at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:                                                                                                               80)
jvm 1    | WrapperSimpleApp Error:      at java.util.Properties$XmlSupport.load(Properties.java:1201)
jvm 1    | WrapperSimpleApp Error:      at java.util.Properties.loadFromXML(Properties.java:881)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.ServerManager.init(ServerManager.java:91)
jvm 1    | WrapperSimpleApp Error:      at org.traccar.Main.main(Main.java:27)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jvm 1    | WrapperSimpleApp Error:      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:4                                                                                                               3)
jvm 1    | WrapperSimpleApp Error:      at java.lang.reflect.Method.invoke(Method.java:483)
jvm 1    | WrapperSimpleApp Error:      at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:290)
jvm 1    | WrapperSimpleApp Error:      at java.lang.Thread.run(Thread.java:745)
jvm 1    | WrapperSimpleApp Error: Caused by: org.xml.sax.SAXParseException; lineNumber: 375; columnNumber: 14; The content of                                                                                                                element type &quot;properties&quot; must match &quot;(comment?,entry*)&quot;.
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException                                                                                                               (ErrorHandlerWrapper.java:203)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapp                                                                                                               er.java:134)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReport                                                                                                               er.java:437)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReport                                                                                                               er.java:368)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReport                                                                                                               er.java:325)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.handleEndElement(XMLDTD                                                                                                               Validator.java:1994)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.endElement(XMLDTDValida                                                                                                               tor.java:879)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndEleme                                                                                                               nt(XMLDocumentFragmentScannerImpl.java:1782)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentCont                                                                                                               entDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScan                                                                                                               nerImpl.java:606)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument                                                                                                               (XMLDocumentFragmentScannerImpl.java:510)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configurat                                                                                                               ion.java:848)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configurat                                                                                                               ion.java:777)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
jvm 1    | WrapperSimpleApp Error:      at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderIm                                                                                                               pl.java:348)
jvm 1    | WrapperSimpleApp Error:      at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvi                                                                                                               der.java:106)
jvm 1    | WrapperSimpleApp Error:      at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:                                                                                                               78)
jvm 1    | WrapperSimpleApp Error:      ... 10 more
jvm 1    | WrapperSimpleApp Debug: start(args) end.  Main Completed=true, exitCode=1
jvm 1    | WrapperManager Debug: returned from WrapperListener.start()
jvm 1    | WrapperManager Debug: WrapperListener.start() returned an exit code of 1.
jvm 1    | WrapperManager Debug: WrapperManager.stop(1) called by thread: WrapperListener_start_runner
jvm 1    | WrapperManager Debug: Send a packet STOP : 1
jvm 1    | WrapperManager Debug: Pausing for 1,000ms to allow a clean shutdown...
wrapperp | read a packet STOP : 1
wrapper  | JVM requested a shutdown. (1)
wrapper  | wrapperStopProcess(1, FALSE) called.
wrapper  | Sending stop signal to JVM
wrapperp | send a packet STOP : NULL
jvm 1    | WrapperManager Debug: Received a packet STOP :
jvm 1    | WrapperManager Debug: Stopped checking for control events.
jvm 1    | WrapperManager Debug: Thread, WrapperListener_start_runner, handling the shutdown process.
jvm 1    | WrapperManager Debug: shutdownJVM(1) Thread: WrapperListener_start_runner
jvm 1    | WrapperManager Debug: wait for 0 shutdown locks to be released.
jvm 1    | WrapperManager Debug: Send a packet STOPPED : 1
wrapperp | read a packet STOPPED : 1
wrapper  | JVM signaled that it was stopped.
jvm 1    | WrapperManager Debug: Closing backend connection.
wrapperp | socket read no code (closed?).
wrapperp | Closing backend socket.
jvm 1    | WrapperManager Debug: Closed backend socket (Normal): java.net.SocketException: Socket closed
jvm 1    | WrapperManager Debug: Returned from backend handler.
wrapper  | Signal trapped.  Details:
wrapper  |   signal number=17 (SIGCHLD), source=&quot;unknown&quot;
wrapper  | Received SIGCHLD, checking JVM process status.
wrapper  | JVM process exited with a code of 1, however the wrapper exit code was already 1.
wrapper  | JVM exited normally.
jvm 1    | WrapperManager Debug: calling System.exit(1)
jvm 1    | WrapperManager Debug: WrapperManger stopped due to System Exit
jvm 1    | WrapperManager Debug: Server daemon shut down
wrapper  | &lt;-- Wrapper Stopped</pre>

Что это может быть ? и в какую сторону копать ?
В тоже время на боевом сервер стоит все в точ точ одинаковое за исключением того что там стоит 2.10 версия traccar и чуть старее версия mysql

**Comment by tananaev** [comment]
Похоже что какая-то проблема с конфигурационным файлом:
<pre>Caused by: org.xml.sax.SAXParseException; lineNumber: 375; columnNumber: 14;...</pre>

**Comment by napaster** [comment]
Попробую тогда еще раз просмотреть traccar.cfg. Возможно где то ошибся или удалил лишнее чтото. По результату отпишусь.

**Comment by napaster** [comment]
В общем удалил полностью папку /opt/traccar и проинсталил еще раз. поправил  в cfg только параметры подключения к mysql. теперь вроде как запускается, но при попытке зайти пустая страница в веб браузере.

**Comment by tananaev** [comment]
Смотрите в логах что за ошибка.

**Comment by napaster** [comment]
В лог вообще ничего не падает. Даже в debug режиме wrapera

**Comment by tananaev** [comment]
Тогда смотрите в браузере. Например в Chrome нужно открыть Settings->More tools->JavaScript console.
