### ISSUE TITLE
GT06 MSG_STATUS for Important Information

### ISSUE THREAD

**Issue by bernamaxim** [tananaev/traccar#1055]
Why you do not use MSG_STATUS type, whereas it contains important information such as Status Engine, Gps Tracking, Gps Charge, Gps Active, Engine Cut, Volt Level, Gsm Signal, Alarm Language? You have been using the other types to determine the status Engine (ACC). I see you have used it, but you actually remove at the commit 9b5a19002940d067284a3e3ae7d7cfd24e4d9bff dated February 11, 2013. Thanks.

**Comment by tananaev** [comment]
Currently Traccar does not support messages without GPS info like MSG_STATUS.

**Comment by tananaev** [comment]
Traccar has supported this for a while now.
