### ISSUE TITLE
TK108 

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#1057]
I have bought a tracker called tk108, which looks like this: http://www.android-touchpadtabletpc.com/sale-721360-tk108-waterproof-mini-pet-gps-tracker.html

and I was wondering which protocol it uses. It looks like xexun, but doesn't seem to work with it.
2015-02-02 16:42:41 DEBUG: [5013 <- 188.188.24.231] - HEX: 4c4f473135303230323136323330372c2b33323437353837343134312c4750524d432c3134323330372e3030302c412c353034302e393237332c4e2c30303432332e333439322c452c302e30302c302e30302c3032303231352c2c2c412a36452c462c2c696d65693a3836323130363032353039303632342c313138a0c80d0a
2015-02-02 16:43:09 DEBUG: [5013 <- 188.188.24.231] - HEX: 3135303230323137323335392c2b33323437353837343134312c4750524d432c3135323335392e3030302c412c353034302e393831302c4e2c30303432332e303536322c452c352e35302c3238372e39352c3032303231352c2c2c412a36372c4c2c2c696d65693a3836323130363032353039303632342c3132303c05

**Comment by tananaev** [comment]
It looks like Xexun protocol. Try port 5006.

**Comment by renaudallard** [comment]
As I wrote, I tried xexun, but I didn't see the device. When using xexun protocol, there is no more debug log with hex, but the device is not recognized. I don't have a line log telling I have an unregistered device.

**Comment by tananaev** [comment]
Can I see full logs with 5006 port?

**Comment by renaudallard** [comment]
How do I enable more logs? When it is using port 5006, there is no more HEX log.

**Comment by tananaev** [comment]
If there is no HEX it means there is no data. Maximum logging level is enabled by default in last Traccar version.

**Comment by renaudallard** [comment]
That is quite strange then. Why would the device send data on the 6 or 7 other ports I have tried, but not on 5006 and not on 6006 (I changed the ports in the config just to check).

**Comment by tananaev** [comment]
For example it can be blocked on the firewall.

**Comment by renaudallard** [comment]
There is no firewall blocking that port, at least on the server. I changed the port to 6006 just in case someone on the way would be blocking the packet. I will try again tomorrow.

**Comment by renaudallard** [comment]
There is definitely no log for that device and it's not being blocked on a firewall.
# tcpdump -ttt -n -e -i em0 port 5006                                                                                                                                      
tcpdump: listening on em0, link-type EN10MB
tcpdump: WARNING: compensating for unaligned libpcap packets
Feb 04 14:19:02.252940 bc:16:65:50:49:67 28:92:4a:36:a8:6a 0800 78: 188.188.59.138.29918 > XXXXXXXX.5006: S 82271250:82271250(0) win 10880 <mss 1360,nop,wscale 0,nop,nop,sackOK,nop,nop,timestamp 65817 0> (DF)
Feb 04 14:19:02.252985 28:92:4a:36:a8:6a bc:16:65:50:49:67 0800 54: XXXXXXXX.5006 > 188.188.59.138.29918: R 0:0(0) ack 82271251 win 0 (DF)

**Comment by tananaev** [comment]
I don't know what it means. Is it connection handshake or real data?

**Comment by renaudallard** [comment]
It's the same as on other ports, except there is no log in traccar. Would you like to see the packets of the transmission?

**Comment by tananaev** [comment]
Yes, I would like to see packet capture log (for example from WireShark).

**Comment by renaudallard** [comment]
This is somewhat strange, on all ports except the allegedly right one (5006), there is a good connection. On 5006, or any port I put with xexun protocol, the server sends a RSET directly.

I have not found how to attach a pcap file, so just download the jpg and rename it to pcap for wireshark.

![port5006](https://cloud.githubusercontent.com/assets/478410/6079794/396ecdbe-ae0a-11e4-9f03-4dcc420ed34b.jpg)

**Comment by tananaev** [comment]
Try to change port number in the config file and see if it fixes the problem.

**Comment by renaudallard** [comment]
As said, I already tried to change it to 6006 and it exhibits the same behaviour.

**Comment by tananaev** [comment]
Can you connect to it locally (e.g. through telnet)?

**Comment by renaudallard** [comment]
That's a good one. There is indeed nothing listening on that port...
But it's enabled in the config...
    
    <entry key='xexun2.enable'>true</entry>
    <entry key='xexun2.port'>5006</entry>

It seems this is due to an incompatible change in the config between 2 versions. I have upgraded the config.  But that means it should have worked before on port 5000. I will check later.

**Comment by renaudallard** [comment]
OK, thanks, it all boiled down to a change in the config file between 2 versions.
