### ISSUE TITLE
Address field in traccar database.

### ISSUE THREAD

**Issue by khansquare** [tananaev/traccar#1058]
Hello!!
I have installed this server on ubuntu, It's working perfectly. I want to know about the structure of database. And specially about the address column in position table. This column has NULL only in every record!
What does it mean? Does it store the current address of device or anything else?
Please Specify.

**Comment by tananaev** [comment]
Reverse geocoding is disabled by default. If you enable it in the config then you will get non-null address.

**Comment by khansquare** [comment]
How to enable it sir?

**Comment by tananaev** [comment]
Modify or add to Traccar config file:
<pre>&lt;entry key='geocoder.enable'&gt;true&lt;/entry&gt;</pre>

**Comment by khansquare** [comment]
I have already tried it, But it's not working yet. Any other changes?

**Comment by tananaev** [comment]
It will add address only for new records.

**Comment by khansquare** [comment]
Yes I am talking about new records after enabling the geocoder. The new records in database was as usual.

**Comment by tananaev** [comment]
Maybe there is some problem with default Google geocoder. You can try Nominatim server.

**Comment by khansquare** [comment]
It mean I will have to install nominatim server on my machine!!!!
Is there no another option sir?

**Comment by tananaev** [comment]
You can try their server just to see if it works.

**Comment by khansquare** [comment]
Can you please suggest me to do so..?

**Comment by khansquare** [comment]
Sorry to bother you sir! I didn't restart my machine after geocoder setup. Now It is working good. 
Thanks for your supprt.

**Comment by tananaev** [comment]
You just need to restart service.
