### ISSUE TITLE
Upgrading erases configuration

### ISSUE THREAD

**Issue by ariscop** [tananaev/traccar#1059]
traccar.run unconditionally creates /opt/traccar/conf/traccar.cfg, erasing anyexisting configuration

**Comment by tananaev** [comment]
Well, basically automatic upgrading is not supported. Set of configuration parameters can change and database structure can change between releases, so new version can actually be incompatible with an old one.

**Comment by ariscop** [comment]
That's fair but it still shouldn't silently erase configuration, if you're not supposed to upgrade via traccar.run it could simply error instead of overwriting.

**Comment by tananaev** [comment]
Agree. That's a good idea to check if folder is already there. Need something similar for Windows installer as well.

**Comment by tananaev** [comment]
There is a default config file now, so upgrade process is much easier. There is also upgrade documentation:

https://www.traccar.org/upgrading-traccar/
