### ISSUE TITLE
Use traccar ONLY to insert to database?

### ISSUE THREAD

**Issue by GeeZuZz** [tananaev/traccar#1061]
I don't need the web interface, I only need a reliable and lightweight server that gets the data from the tracker, and inserts into a MySQL DB.

How can I completely disable the webserver, and try to make the server more lightweight? (i only use TK103)

Is there any way to add a prefix to the DB tables? (I'm only allowed one DB)

I would prefer a non-java based server, but it looks like traccar is the best option I got?

What I REALLY  need is a tracker that submits the data via HTTP instead of TCP, but for some strange reason that feature doesn't seem to exist on cheap trackers!

**Comment by vitalidze** [comment]
You can configure MySQL using [official guide](http://www.traccar.org/docs/mysql.jsp). Then to disable HTTP server you should update this configuration entry:

````xml
<entry key='http.enable'>true</entry>
````

to

````xml
<entry key='http.enable'>false</entry>
````

**Comment by vitalidze** [comment]
> How can I completely disable the webserver, and try to make the server more lightweight? (i only use TK103)

You may disable/remove all other protocols in configuration file and just leave the only TK103.

> Is there any way to add a prefix to the DB tables? (I'm only allowed one DB)

You can rename already created tables (or create them yourself) and then update `database.selectDevice`, `database.insertPosition` and `database.updateLatestPosition` queries in configuration file accordingly.
