### ISSUE TITLE
Version number is not provided

### ISSUE THREAD

**Issue by khansquare** [tananaev/traccar#1064]
Hello!
I am building traccar from source files on Ubuntu 12.04 LTS 32Bit.
When I run package.sh file according to step 13 at http://www.traccar.org/docs/build.jsp, I got this message "Version number is not provided".
Please suggest what am I missing?

**Comment by tananaev** [comment]
You need to provide a version number as a command line argument.

**Comment by khansquare** [comment]
Which version number? 
Please give me more details.

**Comment by khansquare** [comment]
I simply put the package with 1.0 version number as a command line argument and the zip files has generated. 
But as I install traccar and start the daemon using following command..
-sudo /opt/traccar/bin/traccar start
-[sudo] password for user: 
-Starting traccar...
-Waiting for traccar..................
-WARNING: traccar may have failed to start.

and can't open localhost:8082

**Comment by tananaev** [comment]
Have you fixed the issue?

**Comment by khansquare** [comment]
It has been fixed automatically by putting a version number after the command.
Or you are asking anything else?

**Comment by tananaev** [comment]
You said you are getting "WARNING: traccar may have failed to start".

**Comment by khansquare** [comment]
Yes sir, I was getting this message during starting the daemon of traccar  (sudo /opt/traccar/bin/traccar start). When I saw in log files, There was a license error. After searching for this type of errors, I found that I have installed a professional version of wrapper-delta-pack by mistake. Then I remove it and installed the community version which is free to use. And I got the solution.
