### ISSUE TITLE
h2 database - remove old positions

### ISSUE THREAD

**Issue by kamilhlavka** [tananaev/traccar#1065]
can be done?

ALTER TABLE POSITIONS SET REFERENTIAL_INTEGRITY FALSE
DELETE FROM POSITIONS WHERE ID BETWEEN 1 AND 100000 // or 150000
COMMIT

Will it work?

Thanks Kamil

**Comment by tananaev** [comment]
For MySQL database I use following commands:
<pre>DELETE FROM positions WHERE time &lt; DATE_ADD(NOW(), INTERVAL -3 MONTH);
UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id NOT IN (SELECT id FROM positions);</pre>

**Comment by kamilhlavka** [comment]
THX super
