### ISSUE TITLE
GWT module 'traccar' may need to be (re)compiled

### ISSUE THREAD

**Issue by m4monster** [tananaev/traccar#1066]
I was getting license error, because I downloaded professional version of wrapper. Then I packaged again with wrapper community version. I got my new packages and server has been started. But as I load localhost:8082 into browser I got this error in my browser.
How to recompile this?

**Comment by tananaev** [comment]
Have you compiled the GWT project?

**Comment by khansquare** [comment]
I just compiled the project at the beginning in eclipse, I didn't compile it again after downloading new wrapper tar.gz file.

**Comment by tananaev** [comment]
How did you compile it in Eclipse? Did you click GWT compile?

**Comment by khansquare** [comment]
No sir! I didn't click on this option.

**Comment by tananaev** [comment]
Well, you have to click on it to compile web interface.
