### ISSUE TITLE
Allow multiple users to see the same device(s)

### ISSUE THREAD

**Issue by mmeimaris** [tananaev/traccar#1067]
I understand that this is not possible at the moment. However, this would be helpful in cases of hierarchical organizations, where both the employee and his manager want to see the employee's device. How would I go about doing that?

**Comment by vitalidze** [comment]
I have implemented this feature in [my fork](http://traccar.litvak.su/). So there are now three different types of accounts: administrator, manager and user. Administrator sees all devices and can 'Share' any device to any user. Manager can create new users and managers, which are linked with manager. Then, manager sees his devices and devices of all underlying users in hierarchy.

**Comment by mmeimaris** [comment]
Thank you very much.

**Comment by snoop168** [comment]
Any update on whether this will work in this repo anytime soon? I see that there is a table setup for users_devices and I did manually add some records for my second user to "read" and "write" and it worked, so it seems that there just needs to be some UI to be able to add these records in without needing to do it manually in the DB.

**Comment by tananaev** [comment]
It's already implemented in the source code, so the feature will be available with the next official release.

**Comment by deednseed** [comment]
Do you have any plan to add a feature wherein a normal user can share the devices link with him, with other normal user(s)?

**Comment by tananaev** [comment]
This is not the right place to ask questions.
