### ISSUE TITLE
Error at Mysql

### ISSUE THREAD

**Issue by farbeed** [tananaev/traccar#1068]
Hi,

I tried to use Mysql server for Traccar, I replaced the below code in the config file

```
<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/fadi?allowMultiQueries=true&amp;autoReconnect=true</entry>
<entry key='database.user'>root</entry> 
<entry key='database.password'>fadi@100</entry>
```

but traccar does not crate any table in the database!
how can I fix it?

**Comment by tananaev** [comment]
Have you tried to open web interface?

**Comment by farbeed** [comment]
It is worked after I opened web interface.


Thanks Anton
