### ISSUE TITLE
resetDelay property issue

### ISSUE THREAD

**Issue by veldjmaxis** [tananaev/traccar#1069]
Hi Anton,
I have a problem with resetDelay property per server. If I set resetDelay on Xexun to 60 secs, and 86400 for GL200, settings from GL200 became to be applyed to Xexun instead of its own property. I need to set that settings per server coz xexun is on short connection mode and GL200 on long connection mode. I made some changes to traccar, like implementing geofence but I dont think that this related to my changes. Something like problem in GlobalTimer where settings are setted for all server instead of setting per server.

**Comment by tananaev** [comment]
I have double checked and `resetDelay` is applied per protocol.

**Comment by tananaev** [comment]
Note that Traccar uses `HashedWheelTimer` for idle detection, so it might not be as precise as default Java `Timer`.

**Comment by veldjmaxis** [comment]
Thans for reply Anton.
So I need to check in my changes where I made a mistake.
Can You tell me, whether changes in these files can make problems with resetDelay?
Coz I made changes in:
- FilterHandler (for geofence handling)
-DataManager
-GL200 protocol (Implemented more events)
-BasePipelineFactory (enabling geofence per protocol)

**Comment by tananaev** [comment]
BasePipelineFactory is where the `IdleStateHandler` is added.

**Comment by veldjmaxis** [comment]
OK Anton, I updated source code to latest and problem fixed itself.
I have another one querstion. Can You provide me some ide how and where implement Heartbeat response for GL200?
Coz in long connection mode device sends Heart beat message and needs response to this message from server to inform that connection is still alive.

**Comment by tananaev** [comment]
You can send response from protocol decoder class.

**Comment by veldjmaxis** [comment]
Thanks Anton. I will try to do this. Thanks again for Your help
