### ISSUE TITLE
How to figure out if a tracker (tk103) is not showing on traccar server?

### ISSUE THREAD

**Issue by mp3banker** [tananaev/traccar#1071]
I'm new to this and I'm having issue figuring out why my tk103 is not showing up on the traccar server:

I don't know if issue comes from traccar server, port forwarding, GPRS network provider, tracker configuration or tracker itself.

How do I test that traccar is listening on port 5002 (tk103)? I could telnet from outside my network and have a chat with server but not sure what command or text to type to get server to respond and confirm that server and port forwarding if working.

Thank you in advance for some pointers. 

I hope this is not a case of RTFM

Eric

**Comment by tananaev** [comment]
If you can connect to the port through telnet it means Traccar is listening on that port.

You can also use some online tools to check ports (for example http://www.yougetsignal.com/tools/open-ports/).

**Comment by mp3banker** [comment]
I have figured out the GPRS end of it and now receiving data from device (tk103) but server (Mac) does not seem to respond with LOAD or ON command, so device keeps sending LOGON request and not position data

Log entry:
2015-02-12 05:07:00 DEBUG: [5002 <- 24.114.85.63] - HEX: 23232c696d65693a3335393731303034363138363931332c413b

When I send a SMS  "load123456" command to device it responds with "load fail, check GPRS" but GPRS seem ok since according to log i'm receiving these LOGON request (with associated IP)

Not sure how to go about it from here...

Thanks

**Comment by tananaev** [comment]
I see two issues here:
1. You need to use port 5001 instead of 5002 for your device
2. Your device doesn't send any location. Probably you need to activate location reporting with some special command.

**Comment by mp3banker** [comment]
Anton,

Thank you. Indeed port 5001 is responding (making progress) by sending LOAD command

But the hand shake stops there and connection is lost see log:

2015-02-13 04:20:35 DEBUG: [5001 <- 24.114.99.92] - HEX: 23232c696d65693a3335393731303034363138363931332c413b
2015-02-13 04:20:35 DEBUG: [5001 -> 24.114.99.92] - HEX: 4c4f4144
2015-02-13 04:20:35  WARN: Connection reset by peer - java.io.IOException (FileDispatcherImpl.java:-2)
2015-02-13 04:20:35  INFO: Closing connection by exception
2015-02-13 04:20:35  INFO: Closing connection by disconnect

RESET by whom?

I'm still digging in the tracker command set to see if there is something I'm doing wrong but once the GPRS hand shake starts
I was expecting it to trigger sending of positions.

This very quick reset is puzzling me. Any suggestion?

Thanks

Eric




On Feb 12, 2015, at 6:05 PM, Anton Tananaev <notifications@github.com<mailto:notifications@github.com>> wrote:


I see two issues here:
1. You need to use port 5001 instead of 5002 for your device
2. Your device doesn't send any location. Probably you need to activate location reporting with some special command.

**Comment by tananaev** [comment]
"Reset by peer" means device disconnected from server.

Maybe following thread will help you with command:
https://github.com/tananaev/traccar/issues/529
