### ISSUE TITLE
Problem with TR02 (Not shown on Web)

### ISSUE THREAD

**Issue by kailinet** [tananaev/traccar#1072]
I just installed TR02 with Traccar. Im using IMEI as unique identifier.
As manual I'm using port 5022.

On log it only show:
2015-02-11 01:48:40 DEBUG: [5022 <- 120.180.95.221] - HEX: 68681c0504035889905270679600261a010d101918180016111216000000000d0a
2015-02-11 01:48:40 DEBUG: [5022 -> 120.180.95.221] - HEX: 54681a0d0a

My other device working properly. Thereis any idea where the problem is?
Thanks.

**Comment by tananaev** [comment]
It is just a heartbeat message. Looks like your device doesn't send location data.

**Comment by kailinet** [comment]
yup its seems so. i just trying to sending message a sms to get a location and it got it. its need to moving? or?

**Comment by tananaev** [comment]
I don't know about this device logic. Maybe it sends data only when moving.

**Comment by kailinet** [comment]
Done. Its send data only when moving :)
Thanks for response :)
