### ISSUE TITLE
GT06 protocol issue

### ISSUE THREAD

**Issue by nitinvermak** [tananaev/traccar#1073]
Hey guys,

I m new to GT06 device. Earlier i have worked on tk103 device.
When i installed the device to send data to server.
first it sends the login message and then the heartbeat only.
Even after sending the heartbeat response there is no message from device regarding location.
Also there is one message coming with this protocol number "0x8B" what does it mean.

And if someone is having detailed manual for Gt06 please share.

**Comment by tananaev** [comment]
Protocol number 0x8B probably means response to some command. Some devices don't send data when they don't have a GPS fix or when they are not moving.

**Comment by lahirutm** [comment]
http://www.iconcox.com/uploads/soft/130627/1-13062F94158.pdf

http://support.sathyainfo.com/kb/a76/gps-vehicle-tracker-gt06n-command-list.aspx
