### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by rino666** [tananaev/traccar#1074]
hello!
can help me to start traccar on windows8.1 system?

this is the tracker-server.log:

<pre>2015-02-11 16:39:11  INFO: Shutting down server...
2015-02-11 16:41:40  INFO: Starting server...
2015-02-11 16:41:40  INFO: Operating System name: Windows 8.1 version: 6.3 architecture: x86
2015-02-11 16:41:40  INFO: Java Runtime name: Java HotSpot(TM) Client VM vendor: Oracle Corporation version: 25.31-b07
2015-02-11 16:41:40  INFO: Memory Limit heap: 247mb non-heap: 0mb
2015-02-11 16:41:40  INFO: Version: 2.11-SNAPSHOT</pre>

this is the wrapper.log:

<pre>INFO   | jvm 1    | 2015/02/11 20:00:37 | 2015-02-11 20:00:37.729:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/02/11 20:00:37 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getLatestPositions()' threw an unexpected exception: java.lang.IllegalStateException
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:389)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:579)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/02/11 20:00:37 | Caused by: 
INFO   | jvm 1    | 2015/02/11 20:00:37 | java.lang.IllegalStateException
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.traccar.web.server.model.DataServiceImpl.getSessionUser(DataServiceImpl.java:113)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.traccar.web.server.model.DataServiceImpl.getLatestPositions(DataServiceImpl.java:403)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:561)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:265)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:305)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/02/11 20:00:37 |   at java.lang.Thread.run(Unknown Source)</pre>

I think that the problem is the jre istallation in automatic i have update java at the last version

excuse for my english

**Comment by tananaev** [comment]
This error means that you are not logged.

**Comment by rino666** [comment]
what?
in browser?
I log with admin admin at address http://localhost:8082/
use a teltonika fm4200, so I set up device FM4200 and imei, at the moment I don't know, 123456789012345
but it not work
the port on the router is open TCP/UDP 5027, as you tell

**Comment by tananaev** [comment]
Does it happen right after login? Or after some time?

**Comment by rino666** [comment]
right after login and again, again, periodically

**Comment by rino666** [comment]
but, I see than if, I do not set up any device in browser periodically if I have a device in browser no.

**Comment by tananaev** [comment]
What browser are you using?

**Comment by rino666** [comment]
the browser that I using is goggle chrome and firefox.
thanks, but maybe I did something stupid. Control today and let you know

**Comment by rino666** [comment]
thanks to all, it's ok
now I need to implement a different client.
I need to collect other data that sends the Teltonika, I begin to see if I can implement them.
In particular, I need to implement canbus
