### ISSUE TITLE
Cellocator Ignition on/off

### ISSUE THREAD

**Issue by gioramies** [tananaev/traccar#1075]
Hi.

I'm trying to send a message to the cellocator modem but don't know how to do it. I have read the *Wireless Communication Protocol* and also the function *sendReply* in *CellocatorProtocolDecoder.java*, which gave me a strong foundation to start, but still unable to create the message for ignition on/off. I think ignition command is on page 91 of the document but not sure and anyway don't know exactly what and how to create the message.
Can someone help me to achieve it please? Thank you.

**Comment by tananaev** [comment]
I think you need to fill "Generic Command Message" format with correct command id and all other fields. `sendReply` is a good place to start implementation.

**Comment by gioramies** [comment]
Thank you. I did it.

**Comment by shernandezp** [comment]
Hello gioramies.

May you share the method that you use for send a Ignition on/off to cellocator device?
I'm working in this topic as well.
Thank you.

**Comment by cristianp431** [comment]
hello  gioramies colud you please tell us how to create a personalized comand for cellocator device? for example IGNITION on/off 

thanks
