### ISSUE TITLE
SMS rather than IP communication?

### ISSUE THREAD

**Issue by SmugWimp** [tananaev/traccar#1077]
I can get SMS only for a much lower price than Cellular Data (IP).

Can Traccar support SMS only communication?

If you do not support SMS only do you plan to?

If you do not plan to support SMS only, can you give me a brief list of requirements for me to do so?

Kind Regards,

-- Smug

**Comment by tananaev** [comment]
Traccar does not support SMS communication and I don't have any plans to support it so far.

**Comment by billwide** [comment]
Hi Tananaev, congratulations buddy for your Traccar project. Today Traccar does not support SMS communication, but if I hire a developer this can be done easily, right? This is something that I am planning to do in a near future. Thanks in advance and hope for your reply. Tks again!

**Comment by tananaev** [comment]
@billwide, I don't think it's that easy. Traccar is built around Netty framework and it would require some effort to integrate SMS communication properly.
