### ISSUE TITLE
Protocol Identification Help

### ISSUE THREAD

**Issue by uppaljs** [tananaev/traccar#1079]
Hi,

I am using a GoSAFE G797W and using the port 5013 - The data format being reported is 

2015-02-13 15:03:56 DEBUG: [5013 <- 185.5.153.215] - HEX: 2a475331362c3335313533353035383730393737352c3130303335363133303231352c2c5359533a473739573b56312e30363b56312e302e322c4750533a413b363b4e32342e3830323730303b4534362e3631363832383b303b303b3638343b312e33352c434f543a36302c4144433a342e33313b302e31302c4454543a32303030303b3b303b303b303b3123

which translates to 

*GS16,351535058709775,100356130215,,SYS:G79W;V1.06;V1.0.2,GPS:A;6;N24.802700;E46.616828;0;0;684;1.35,COT:60,ADC:4.31;0.10,DTT:20000;;0;0;0;1#

but traccar is unable to parse any data.

Can you recommend which port to use ? or do I need to change anything else?

Thanks,

**Comment by uppaljs** [comment]
Okay , looking into the code for H02Decoder - as this seems very close to it

    	    "\\*..," +                          // Manufacturer
            "(\\d+)," +                         // IMEI
            "V\\d," +                           // Version?
            ".*" +
            "(\\d{2})(\\d{2})(\\d{2})," +       // Time (HHMMSS)
            "([AV])," +                         // Validity
            "(\\d+)(\\d{2}.\\d+)," +            // Latitude (DDMM.MMMM)
            "([NS])," +
            "(\\d+)(\\d{2}.\\d+)," +            // Longitude (DDMM.MMMM)
            "([EW])," +
            "(\\d+.?\\d*)," +                   // Speed
            "(\\d+.?\\d*)?," +                  // Course
            "(\\d{2})(\\d{2})(\\d{2})," +       // Date (DDMMYY)
            "(\\p{XDigit}{8})" +                // Status
            ".*");
    
I believe that the difference here is the following

1) the position of the location in the converted ascii
2) the N & E in front of location , the current H02 supports co-ordinates as N,COORDINATE;E,COORDINATE whereas the tracker i have is sending it in N24.802700;E46.616828 format.

Kindly help.

Thanks,

**Comment by tananaev** [comment]
It doesn't match any existing Traccar protocols. It should be a new decoder.

**Comment by uppaljs** [comment]
What is required for a new decoder @tananaev ?

**Comment by tananaev** [comment]
If you want me to implement it I need full protocol documentation.

**Comment by uppaljs** [comment]
Ah , unfortunately , i don't have that , is there any product that you recommend - that is fully supported by traccar ?

**Comment by tananaev** [comment]
I have implemented decoder with limited functionality.

Here a new version to test:
https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

You need to add following lines to the config file:
<pre>    &lt;entry key='gosafe.enable'&gt;true&lt;/entry&gt;
    &lt;entry key='gosafe.port'&gt;5078&lt;/entry&gt;</pre>

I don't know which one of the fields (in bold) is speed and which one is course/heading:
<pre>*GS16,351535058709775,100356130215,,SYS:G79W;V1.06;V1.0.2,GPS:A;6;N24.802700;E46.616828;<strong>0;0;684;1.35</strong>,COT:60,ADC:4.31;0.10,DTT:20000;;0;0;0;1#</pre>

If you can identify those fields by trial I can improve decoder more.

**Comment by uppaljs** [comment]
Oh I can definitely do that. Let me test. And give you the complete field
definition one by one.

Many thanks.

**Comment by uppaljs** [comment]
Hi @tananaev  , 

The version provided by you , now is decoding, many thanks for that , looking forward for the complete field mapping, I have enabled all options on the tracker [ It has option to turn off/on different fields from the configuration software]. Here's the full detail of the packets , I hope this helps with improving the decoder.

Many thanks!

First Message Received After Power on

2a475331362c33353135333530353837303937373523
*GS16,351535058709775#

Field Number | Value | Purpose
------------ | ------------- | -------------
1 | *GS16 | Manufacturer Number
2 | 351535058709775 | IMEI of Device

Message After GPS Lock

2a475331362c3335313533353035383730393737352c3233333732303133303231352c2c5359533a473739573b56312e30363b56312e302e322c4750533a413b343b4e32342e3830323637363b4534362e3631363831323b303b303b3637323b312e38313b342e32332c434f543a36303b2c4144433a342e32343b302e31302c4454543a32303030303b3b303b303b303b3123

*GS16,351535058709775,233720130215,,SYS:G79W;V1.06;V1.0.2,GPS:A;4;N24.802676;E46.616812;0;0;672;1.81;4.23,COT:60;,ADC:4.24;0.10,DTT:20000;;0;0;0;1#

Field Number | Value | Purpose
------------ | ------------- | -------------
1 | *GS16 | Manufacturer Number
2 | 351535058709775 |  IMEI
3 | 232415130215 | date? ( not sure ) 
4 | EMPTY Field | Empty Field - Not Confirmed Yet
5 | SYS:G79W |  Device Name
6 | V1.06 |   Firmware Version
7 | V1.0.2 |  Hardware Version
8 | GPS:A |  GPS Lock Available
9 | 4 |   Number of Satellite 
10 | N24.802676 |  Latitude
11 | E46.616812 | Longitude
12 | 0 | Speed 
13 | 0 | Azimuth 
14 | 672 |  Altitude 
15 | 1.81 | HDOP
16 | 4.23 |  VDOP
17 | COT: |   COT DATA , STATIC FIELD , Engine Data Start Point
18 | 60 |  Mileage [ Every unit starts at 0 and then keeps counting ]
19 | Empty Field  | Engine Running Hours
20 | ADC: |  STATIC FIELD , Analog to Digital Converter Data Start Point
21 | 4.24 |  External Battery Voltage
22 | 0.10 | Internal Backup Battery Voltage
23 | DTT: |  STATIC FIELD , STATUS DATA Start Point
24 | 20000  |   Device Status , Internal 
25 | Empty Field | [IO Status]
26 | 0 |  Geo Fence Status Number 1-120 
27 | 0 | : Geo Fence Status Number 121-156
28 | 0 | Event Status
29 | 1 | [Packet Type Indicator]

**Comment by uppaljs** [comment]
Hi @tananaev ,

Apologies for pinging again , did you get a chance to look at this?

Many thanks,
Junaid

**Comment by tananaev** [comment]
I have added other location info to decoder.

**Comment by uppaljs** [comment]
Hi,

Many thanks , Can you give me a compiled copy? I am also trying to setup a
local build environment , so I can help out on the protocol too.

Thanks,

**Comment by tananaev** [comment]
Here is a new binary:
https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

**Comment by toleabivol** [comment]
@uppaljs where did you get the documentation from ? I would like to read it also for some extra fields like FUL

**Comment by gaurav931** [comment]
@uppaljs pls share GOSafe device protocol document..
