### ISSUE TITLE
Feeding server from an HTTP request

### ISSUE THREAD

**Issue by Ferretdog** [tananaev/traccar#1083]
I'm using the osmand format to push a position update to my traccar server. 

Eg. 
http://server:5055/?id=123&lat=38.0001&lon=145.001&timestamp=1424231173&hdop=1&altitude=1&speed=0

I'm using tasker to generate the url. (Because the android client doesn't have tasker support ... hint hint)

Problem: my lat is negative. Osmand doesn't seem to work with a negative latitude - how do I work with that?

Thanks

**Comment by tananaev** [comment]
Is the issue resolved?
