### ISSUE TITLE
Mobile-friendly Server

### ISSUE THREAD

**Issue by Ferretdog** [tananaev/traccar#1084]
The current server screen it pretty usable, but viewing it on a phone is like trying to rip your eyes out through your kneecaps. 

A phone-friendly presentation would be fantastic.

**Comment by vitalidze** [comment]
[My mod of web UI](http://traccar.litvak.su/) has mobile version. It's automatically switched when you access it from mobile device. You can try [demo](http://d.traccar.litvak.su) on your phone/tablet.

**Comment by Ferretdog** [comment]
I tried yours. It gave me an error on startup and wouldn't load so I had to switch back.

**Comment by vitalidze** [comment]
You may consider creating an issue on [tracker](https://github.com/vitalidze/traccar-web/issues) (with `wrapper.log` file contents) to figure out what went wrong.
