### ISSUE TITLE
Connections remain open

### ISSUE THREAD

**Issue by mhuppertz** [tananaev/traccar#1085]
I have some trackers sending their information to the server on port 5001. Everything works fine. But suddenly I had some problems accessing the web-interface. After some research I found out that there are over 3500 open connections on port 5001. Does somebody else encounter this issue? Is this problem due to the traccar server or do my trackers (I use TK103-2B and TK104) let the connections open and don't close them correctly?

**Comment by mhuppertz** [comment]
Well I think I figured it out myself. I Added the following line to my config file
    
    <entry key='gps103.resetDelay'>60</entry>

**Comment by tananaev** [comment]
Yes, you can use `resetDelay` parameter to clean up stale connections. Value is timeout in seconds.
