### ISSUE TITLE
Calamp

### ISSUE THREAD

**Issue by luiramji** [tananaev/traccar#1086]
Hi,

Calamp brand is not supported by traccar. I have access to their wiki just in case you want my help integrating it. I like the brand because they have very good quality products at very good prices.

**Comment by tananaev** [comment]
I already have CalAmp protocol implementation, but because of NDA I cannot publish it as open source. If you can sort out this issue with manufacturer then I can easily add support for it.

**Comment by barigo** [comment]
hi , 
do you have the sms command to , reduce the intreval of sending position to server .
now i have , 60seconde when ign/on , and 1 hour when ign/off .

can you help us with that.

**Comment by tananaev** [comment]
CalAmp protocol is already available in Traccar, so closing this thread.
