### ISSUE TITLE
xexun2 protocol and the new server.jar

### ISSUE THREAD

**Issue by connectnet** [tananaev/traccar#1087]
Hi!
After changing the server my TK102-2 doesnt works nighter on port 5006 nor on port 5036 only 5000.
Setting to port 5006 I receive no data but at port 5036 I receive data but it doesnt shows a placemark.

With port 5000 I cant see the extended data like IMEI and battary. Whats the right port for my device now?
```
2015-02-18 17:38:23 DEBUG: [5000 <- 00.000.000.0] - HEX: 
313530323138313633373437272B30303132333435363738393030274750524D43273136333734372E303932274127303030302E30303030274E2730303030302E30303030274527302E303027302E303027313830323135272727412A36332746272720696D65693A31323334353637383930313233342730352736362E3627463A332E37385627302731333927323534343827323632273037273737344327333445363F3F
```

**Comment by tananaev** [comment]
It looks kind of like Xexun protocol, but instead of commas there are quote marks. It is not supported by Traccar.
