### ISSUE TITLE
How to install Client

### ISSUE THREAD

**Issue by koonk** [tananaev/traccar#1089]
Hello,

I purchased a device off ebay which is a GPS tracker. Now I have installed TRACCAR on my server and tested with my mobile and it is working great.

My question is, how do I add configuration to this GPS device(with no screen) to send data to the server?

I am a novice and would really appreciate if you could help.

Thanks & Regards

**Comment by tananaev** [comment]
Usually you need to send special commands (typically via SMS messages) to the device to configure server address and port. Ask seller for details.

**Comment by koonk** [comment]
Hello,

Thank you for the prompt reply. The device has a slot for SIM card. It has 3 other slots, one for power, one for speed, one for usb.

I have connected it to USB but it only shows as a pendrive. Do I need to add any config file etc to it?

Would really appreciate your help.

Thanks & Regards

**Comment by tananaev** [comment]
Well, maybe someone here would be able to help you if you specify model of your device, but I think it's better to contact seller or manufacturer.
