### ISSUE TITLE
Tracker LK106

### ISSUE THREAD

**Issue by joepr** [tananaev/traccar#1090]
Hello Everyone 

Hope I can get any help or tips from any expert here. I have various LK106 trackers and I will like to configure them using the USB port instead of sending SMS. I do see inside of the tracker is a USB port does. Anyone have or know of a software that could let me send the commands?

**Comment by tananaev** [comment]
Are you sure it's a data port? Most likely it's just a charging port.

**Comment by joepr** [comment]
![lk106 usb port](https://cloud.githubusercontent.com/assets/10345032/6321876/5302c056-bade-11e4-8197-99ad8972bd29.JPG)

Here's a picture of the tracker board. The manufacturer apparently have a software to send commands to the tracker but so far I haven't made it work. Here is a screeshoot of the software window.

![trackerpc](https://cloud.githubusercontent.com/assets/10345032/6321893/a31a2304-bade-11e4-8f6c-da0228f39d96.JPG)

**Comment by tananaev** [comment]
It looks like software for updating firmware. What is on the "command" page?
