### ISSUE TITLE
Add Request Position When GPS Connected

### ISSUE THREAD

**Issue by azzahrah** [tananaev/traccar#1093]
Hello Anton,

Can you add feature request position when gps connected for GPS teltonika?

Regards
J.P

**Comment by tananaev** [comment]
Do you mean like a button to request position from device? It will require to finish #7 first.

**Comment by jokopitoyo** [comment]
Little difference, i want when gps connected to the server, server force device to give latest position, currently i have problem with Teltonika FM100, some device always send old data... not currently so so i need to force gps to send last position...

TQ

**Comment by tananaev** [comment]
Do you have any documentation on how to send location request to Teltonika devices?
