### ISSUE TITLE
mv1C tracker support ?

### ISSUE THREAD

**Issue by Hemendrajain** [tananaev/traccar#1095]
Does Traccar support the device mv1C. I do not have the protocol details.
If someone has come across this device, please share information

Please find the link below:

http://www.ebay.in/itm/GPS-TRACKER-VEHICLE-MV1C-REAL-TIME-VOICE-MNTRG-IGN-STATS-ENGINE-HRS-2YRWRTY-/111599681171

Technical Parameters:

GSM: 850/900/1800/1900 MHz
Dimensions: 90cm_45cm_13.6cm weight: 50 grams
GPRS: Class12, TCP/IP built-in GSM Module
GPS: Siemens class10- AGPS chip
Frequency: L1,1575.42MHz C/A code
GPS Channels: 24
Tracking sensitivity: - 179dBm
Acquisition sensitivity: - 148dBm
Locating time cost: Hot start: < 1sec(Open Sky)
Warm start:<15 sec
Cold start: < 27 sec(Open Sky)
GPS antenna: Built-in high gain ceramic patch antenna
Working voltage/current: 12-24vDC/30mA@12V 
Three LED indicators: GPS-blue; GSM-green; Power-red
Application environment: Operating temperature:-40 °C to + 85 °C
Operating humidity:5% to 95% RH

http://www.gpstracker.net.in/MV1C.html

**Comment by tananaev** [comment]
I need protocol documentation or at least message examples to verify if it's supported or not.

**Comment by Hemendrajain** [comment]
Sure. Will check and revert back
