### ISSUE TITLE
Installing Traccar Server on AWS Ubuntu 14.04 | Help Required

### ISSUE THREAD

**Issue by learner88** [tananaev/traccar#1101]
First of all about my technical knowledge
"I am not a technical person but technical enough to search on Google with right pointers and carve my way out"

Now Query:
I have got an instance on AWS with Ubuntu 14.04 LTS installed on it. I can see there are two ways to install traccar server:

1) https://www.traccar.org/docs/build.jsp (Road Block: Not able to execute step 3 & 4)
or
2) https://www.traccar.org/docs/linux.jsp (Road Block: Not able to execute "Start daemon" Error message says failed but no traccar logs available for analysis)

Which one of the above I should follow? How to cross the road blocks?
I might need a step-by-step guidance further to above answer.

**Comment by Jeferex** [comment]
You should use way 2. 

You need to have java installed in order to install traccar.

**Comment by learner88** [comment]
@Jeferex Thanks for your reply!

Steps followed by me for Way 2 (Linux Installation):
1) Created an instance on AWS for Ubuntu 14.04 LTS
2) Installed jre-8u31-linux-x64 successfully
3) Executed "Run traccar.run (sudo ./traccar.run)"
4) Got failed message because for next command "Start daemon (sudo /opt/traccar/bin/traccar start)" after waiting for few minutes.

No log file for traccar got generated in opt/traccar
I am stuck here, can you please guide me on how to proceed from here?

**Comment by Jeferex** [comment]
First check that the traccar server is the 64 bits version.

**Comment by learner88** [comment]
@Jeferex 
Yes it's a 64 bit version "traccar-linux-64-2.11" and Ubuntu is also a 64 bit verion

**Comment by tananaev** [comment]
Are you sure there are no log files under `/opt/traccar/logs`?

**Comment by learner88** [comment]
@Anton
Yes, I am also amazed but there was not log file. In fact there was no
folder named logs under traccar.

Path followed by me to fetch logs home/ubuntu/opt/traccar

I know I have done something wrong over here,  but not able to figure
what's that?

**Comment by tananaev** [comment]
Did you install it from root user? Maybe it failed to copy files into `/opt` directory because of permissions.

**Comment by learner88** [comment]
@Anton under root directory

/opt/traccar beyond this I am not able to proceed because of permission
issues.

How can I mitigate this?

**Comment by tananaev** [comment]
If you are using terminal you can switch to root user using `sudo su` command.

**Comment by learner88** [comment]
@tananaev and @Jeferex 
Thanks for your help guys! Now the server is up running with traccar application.

**Comment by anton** [comment]
@learner88 huh?

**Comment by bzanios** [comment]
Hello.
I know that the post is very old but i can't find another place to ask for help. I am trying to make an acount to the traccar forum but without any success. Anyway.
My problem is that i had install traccar on a Debian(server) system. I was able to load the localhost:8082 page but today when i had try, i couldn't. When i started the service i got the message "Service traccar started". What could be the problem?
Can anyone help me step by step removing my old installation and make a clear one from the beginning?
Or can tell me whats going on?

**Comment by tananaev** [comment]
@bzanios, the right place to ask would be forum:

https://www.traccar.org/forums/forum/server/

Please never comment on old closed github threads!
