### ISSUE TITLE
Last and latest position

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#1104]
Because of tracker's weird behavior and some other circumstances last added device position can be not latest. Therefore device position in web client can be wrong. https://github.com/vitalidze/traccar-web/issues/97

It is believed that to get the latest position in the web client scales badly.

It would be nice to implement latest position in device properties. And update it on every position addition.

**Comment by tananaev** [comment]
Good idea. I will implement it at some point.

**Comment by jokopitoyo** [comment]
Websocket mybe good option for this... since version 4.x netty support websocket server...

**Comment by vitalidze** [comment]
Don't get how web sockets may help here. I have spent some time and came with the following SQL query to update positions:

````xml
    <entry key='database.updateLatestPosition'>
        UPDATE devices d SET d.latestPosition_id = IF(d.latestPosition_id IS NULL OR EXISTS(SELECT 1 FROM positions p1, positions p2 WHERE p1.id = d.latestPosition_id AND p2.id = :id AND p1.time &lt; p2.time), :id, d.latestPosition_id) WHERE d.id = :device_id;
    </entry>
````

This works fine on MySQL and should be quite fast without any modifications to java code. To use it replace (or comment out) existing setting in `traccar.cfg` file:

````xml
    <entry key='database.updateLatestPosition'>
        UPDATE devices SET latestPosition_id = :id WHERE id = :device_id;
    </entry>
````

Hope this helps.

**Comment by Abyss777** [comment]
I've tried your query with default H2 db and got:
````
2015-02-28 14:15:05  WARN: Function "IF" not found; SQL statement:

        UPDATE devices d SET d.latestPosition_id = IF(d.latestPosition_id IS NULL OR EXISTS(SELECT 1 FROM positions p1, positions p2 WHERE p1.id = d.latestPosition_id AND p2.id = ? AND p1.time < p2.time), ?, d.latestPosition_id) WHERE d.id = ?;
     [90022-184] - org.h2.jdbc.JdbcSQLException (DbException.java:345)

````

**Comment by tananaev** [comment]
I think `latestPosition` should just point to the latest record by time.

**Comment by vitalidze** [comment]
@Abyss777 I haven't tried it on H2, so looks like it's MySQL specific.

@tananaev that's what I intend to do with such update query. It may be processed in java, but I think it will require additional select to look up latest position for device to make decision whether `latestPosition_id` should be updated or not. Maybe I am missing something.

**Comment by Abyss777** [comment]
Masterkit BM8009GL (protocol Wialon IPS) sends stored points (after period without connection to server) in the reverse order - latest first.
And there is logic here, sometimes it's better to know where is device now than wait until it will send whole track.
In this case it's more important to have latest position than last received.

**Comment by Abyss777** [comment]
As I understand it was implemented long far ago and issue can be closed
