### ISSUE TITLE
Automatic Builds

### ISSUE THREAD

**Issue by uppaljs** [tananaev/traccar#1105]
Hi @tananaev ,

Just wanted to ask a quick question , if you have looked into automated builds? A lot of commits go into the code base specially with the new protocols , it would be really nice to have a nightly build available.

Thanks,

**Comment by tananaev** [comment]
I've been thinking about continuous build integration for a while now, but haven't got time to implement it yet.

**Comment by uppaljs** [comment]
hahaha - i was just added it to travis ci :-)

**Comment by tananaev** [comment]
Yes, I've integrated it with Travis CI and added build status to the GitHub description.

**Comment by uppaljs** [comment]
Can you add push back to github releases as well please ? http://docs.travis-ci.com/user/deployment/releases/

**Comment by tananaev** [comment]
Thanks for the info, I'll think about it.
