### ISSUE TITLE
no data without gps data

### ISSUE THREAD

**Issue by petersusan** [tananaev/traccar#1108]
Dear Tananaev
i am using the traccar with mysql, using gps303 that is forwarded to the port 5001 (gps103protocol)
if the tracker sending the packedge with gps data then everything all right, 

when the tracker have no gps signal, then it still sending the packedges without gps data but it is not recorded by traccar.
without gps data i still have informations in the packedge that i need like oil level.

these are the messages from the gps (by wireshark)
```
imei:359710046982931,tracker,150223202244,,F,122244.000,A,4733.7127,N,01902.4392,E,0.00 ,0 ,,1,1,84.13%, ,;
```
```
imei:359710046982931,tracker,150204093844,,L,, ,ee4 , ,6d4  , , , ,,1,1,84.13%, ,;
```
how can i get info from the tracker without gps data?
Thanks and Regards
peter

**Comment by tananaev** [comment]
Traccar does not support messages without GPS data yet. I plan to fix it in future.

**Comment by petersusan** [comment]
As i can see the regexp part should be changed in the gps103protocol, but
probably the java part too.

I do not know java (yet), so i need someone to do it for me, - i guess for
an experienced java programmer this is just a piece of cake.

 

Can i donate your project to encourage your to fix it in very soon? How much
would it cost?

 

Thanks

peter

 

  _____

**Comment by tananaev** [comment]
You are welcome to donate to the project, but I cannot give you any estimates on when it would be fixed.

**Comment by petersusan** [comment]
So then in other words, how much would it cost to fix it for the
protocol103? - or should i find someone else / or learn java

 

Btw only regexp should be changed or java part too?

 

  _____

**Comment by tananaev** [comment]
Everything should be changed. We need new database tables, new model classes, new regex and modify decoder as well. If you want to see those in web interface you need to change web interface as well.

It's a major change and I don't want to do it before I switch to new web interface.

**Comment by tananaev** [comment]
I believe this has been supported for a while now.
