### ISSUE TITLE
Traccar Sending Email Possibility

### ISSUE THREAD

**Issue by RoyTH** [tananaev/traccar#1109]
Can Traccar send email based on type of alert sent from a tracker? i.e. if you have a TK103 with an SOS button can traccar be configured to send an email to a specified email address upon receipt of an Helpme status? or if the tracker has a shock sensor etc?

**Comment by tananaev** [comment]
Traccar does not support email notifications yet.

**Comment by tananaev** [comment]
This is already supported.
