### ISSUE TITLE
Last time connection

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#1111]
There is a possibility to determine and show if device is offline (and even notify by email) in alternative web client https://github.com/vitalidze/traccar-web

Now it uses last device position in database, but some devices can send "keep alive", "ping packets"  or others (without coordinates) that show device is online. Usually it happends more frequently than sending positions. And disappearing such packets can help more accurate determine that device is offline.

It would be nice to implement `last_time_connection` device property in database and update it on every message received from device.

**Comment by tananaev** [comment]
I have plans to support keep alive messages and I actually want to display TCP connection status as well.

**Comment by Abyss777** [comment]
I'm thinking about implementing this by myself and want to figure out your plans

* The simpliest way is to update timestamp then any message has been received from device.
````XML
<entry key='database.updateConnectionLastTime'>
        UPDATE devices SET connectionlasttime = CURRENT_TIMESTAMP() WHERE id = :device_id;
</entry>
````
and web interface can interpret it as it wants. (calculate status online/offline on one's own)

* The server can trace connection status by it self and web interface just will show it
 * On receiving login message change status to "Logining"
 * On possition message or keep alive/ping message change status to "Online"
 * On ChanelIdle/ChanelDisconnect/Exception change status to "Offline"
But here can be some problem because logicaly connection can exist very long even device is realy offline. There are two solutions: set `resetDelay` for all protocols or implement some subservice to watch connections and reset them to "Idle" or "Offline" after some timeout.

I think that should be implemented at least first part because it will allow to notificate about "Offline" with configurable delay.
What do you think?

**Comment by tananaev** [comment]
I think we need to have three statuses in web interface:
- <b>Green</b> when connection is active and last message from tracker was less than some time X
- <b>Yellow</b> means connection might be active but last message was more than X seconds ago
- <b>Red</b> when there is no TCP connection

I plan to do significant database modifications along with implementation of new web interface, so I don't want to touch old one to avoid implementing same feature twice.

**Comment by Abyss777** [comment]
As I understand it is implemented long far ago and issue can be closed

**Comment by tananaev** [comment]
Correct.
