### ISSUE TITLE
Digital port, Analog Port an DB MySql

### ISSUE THREAD

**Issue by Mikelord2** [tananaev/traccar#1115]
As can add to the "positions" table data as "DI1 (digital port 1)" AN1 Analog port 1, these data are stored in the "other".
I put them in the configuration file, but I see no result.

example.
```
    <entry key = "database.insertPosition '>
         INSERT INTO positions (device_id, time, valid, latitude, longitude, altitude, speed, course, power, address, other, ai1, di1, di2, di3, do1, do2, 1w)
         VALUES (: device_id,: time,: valid,: latitude,: longitude,: altitude,: speed,: course,: power,: address,: extended_info,: ai1,: di1,: di2,: di3,: do1 $
     </ entry>
```
to do this I leave, writing data to BD

**Comment by tananaev** [comment]
Where do you expect to see the result? Extended info is only displayed on the status panel.

**Comment by Mikelord2** [comment]
the idea is to have them sorted in the "positions" table in order to locate them faster and manage alerts and other consultations.

**Comment by tananaev** [comment]
Unfortunately there is no way to display them in the archive for now. I plan to add it in one of the future versions.

**Comment by Mikelord2** [comment]
but it could create rows in the "positions" table, and sort them from outside and inject the table again ordered without affecting traccar?.

You're very kind with your help and feedback, the project is very good and has a lot of potential, Greetings from Santiago of Chile

**Comment by tananaev** [comment]
Data is already in the database, so only web interface changes are required to display all additional data.

**Comment by lahirutm** [comment]
tananaev -> Don't you have any plan to store device status data ?  Because most devices sending status data to keep alert about device online status. But in that data, no any position data. At least if you can update a feild for LastDeviceOnline in the devices table same as LastUpdatedPosition.

**Comment by tananaev** [comment]
Yes, I plan to save data without location info.
