### ISSUE TITLE
TimeZone and Logger level

### ISSUE THREAD

**Issue by prsolucoes** [tananaev/traccar#1117]
Hi,

I think that have some problem with server related to timezone and logger leve.

All logs from wrapper come with current timezone of my server, but all logs of tracker-server is with a +3 on log datetime.

Another thing is the logger level, im setting:

```
<entry key='logger.enable'>true</entry>
    <entry key='logger.level'>error, fatal</entry>
    <entry key='logger.file'>/var/log/tracker/tracker-server.log</entry>
```

But every command the come to tracker-server he is logging as DEBUG:

```
2015-03-12 18:05:17 DEBUG: [5001 <- XXX.227.156.XXX] - HEX: XXX53937313030343635383738353XXX
2015-03-12 18:05:17 DEBUG: [5001 -> XXX.227.156.XXX] - HEX: 4f4e
```

How i can solve this two problems?

**Comment by prsolucoes** [comment]
On my dev machine, it is working, only on prod the timezone is different, but is not a proble, on traccar.

**Comment by tananaev** [comment]
Time in the log is always in server timezone.

As for the second problem, see #529.
