### ISSUE TITLE
Server implementation

### ISSUE THREAD

**Issue by cypherbond** [tananaev/traccar#1118]
Dear Sir,
I have used Traccar for testing a device before. I wanted to develop a web site for tracking Government Vehicles. For this service I have to go through an auction to obtain a contract. I have very little time remaining for this. So I need your guidance in building up things properly. 
1) Initially the requirement is of approx. 300 devices. I'm not changing the code of your software, instead I'm letting it create MySQL database for me, make replica of it and alter the replica database with my own application in Java for displaying tripwise information. Also the device is switched on only when the vehicle starts and switched off when it reaches destination. This particular route is to be plotted on map and retrieve its source and destination address and store it in the database for reporting. For this I had to create a function in the program to distinguish between trips and I used "coarse" number which keeps on changing every time you switch on the device. Is there any other alternative to this? 
2) If want to use 300 devices simultaneously, with update signal of each device is set to 1 minute, will there be any problem that you have faced with Traccar? Can Traccar handle 300 requests simultaneously efficiently? So far have you come across any bug that can cause trouble in reading and writing data in database or Traccar stops to listen on server port?
3) Contract period is of 2 years. So gradually data will keep on growing, What should be the server recommended requirements like cores, RAM and space? 
4) Which Map service will you recommend Google Maps or Bing Or Open street map in terms of request handling, efficacy and economy?

**Comment by cypherbond** [comment]
I will be grateful if you have any suggestions too.

**Comment by tananaev** [comment]
1) You can try to check gap between messages. If it's too big, then it means it's a new route. But your solutions seems fine.

2) People use Traccar with 1000 and more devices, so it should work just fine. There might be some problems on database/web side, so I recommend to clean database periodically (archive old data).

3) Main resource to look at is RAM size, probably 4GB would be enough for 300 units.

4) I would recommend to read terms and conditions of each map provider. For example, Google Maps does not allow to use free API for enterprise or commercial asset tracking and Business version is very expensive. Not sure about Bing conditions. OpenStreetMaps is free for any use as far as I know.

**Comment by lahirutm** [comment]
I am using traccar for long time. Now i have 450 devices. Fortunately google didn't do anything yet. You can have a demo og mine @ gps.globemw.net. Username/Passwd : demo/demo. Also i can help you to develop anything using google API.

**Comment by umeshbichukale** [comment]
@lahirutm i need some help to build this application from scratch.please share me your contact details i need some help.
Best Regards,
Umesh Bichukale.

**Comment by lahirutm** [comment]
lahirutm@gmail.com

On Mar 21, 2015 10:01 AM, "umeshbichukale" <notifications@github.com> wrote:
>
> @lahirutm i need some help to build this application from scratch.please
share me your contact details i need some help.
