### ISSUE TITLE
Auto start on Amazon EC2 simple linux

### ISSUE THREAD

**Issue by peptoni** [tananaev/traccar#1121]
Hi,
Just wanted to share how I managed to start MySQL and Traccar on an Amazon EC2 linux (Traccar install does not setup auto start on this linux).  Sure there must be other (and better) ways:

Edit /etc/rc.local and add the following lines:

service mysqld start
/opt/traccar/bin/traccar start

**Comment by tananaev** [comment]
By Amazon EC2 linux you mean Amazon Linux AMI?

I guess better way is to ask Java Service Wrapper team to add support for it:
https://sourceforge.net/p/wrapper/discussion/122338/

**Comment by peptoni** [comment]
Yes, Amazon Linux AMI. 

Ok. Thanks!
