### ISSUE TITLE
MySQL database purge

### ISSUE THREAD

**Issue by peptoni** [tananaev/traccar#1122]
Is this the correct way to delete (purge) position records on a MySQL database?

Example: Delete records older than 3 months

Update device's latestPosition_id to null if latest position is in the records to be deleted:
* UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id IN (SELECT id FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH));

Delete records older than 3 months:
* DELETE FROM positions WHERE time < DATE_ADD(NOW(), INTERVAL -3 MONTH);

**Comment by tananaev** [comment]
I use following queries for demo server:
<pre>DELETE FROM positions WHERE time &lt; DATE_ADD(NOW(), INTERVAL -3 MONTH);</pre>
<pre>UPDATE devices SET latestPosition_id = NULL WHERE latestPosition_id NOT IN (SELECT id FROM positions);</pre>

**Comment by peptoni** [comment]
Yep, I saw that in another issue.  But that would fail with an error if we tried to delete records on the positions table that are still referenced by the devices table.  It happened to me today while doing some tests.
I think we have to dissociate the latestPosition_Id from devices table first...
Am I missing something...?
Thanks!

**Comment by tananaev** [comment]
Yeah, I think your queries are better. The only problem is if someone adds old record in between two commands, but I guess it's extremely rare case.

**Comment by peptoni** [comment]
One could wrap the two sentences in a transaction, I guess. Anyway, thanks very much!
