### ISSUE TITLE
Teltonika Devices Get Speed in KM instead of Knots.

### ISSUE THREAD

**Issue by anjumsohail** [tananaev/traccar#1124]
I am Running Traccar with SQL Server, with default h2 database, Traccar stores Speed information in database according the value in table "user_settings", but with my SQL server, Traccar is always saving Speed in Knots,
I have seen the code the 
https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/TeltonikaProtocolDecoder.java

the are line 158 : position.setSpeed(buf.readUnsignedShort() * 0.539957);

The device send speed information in KM, which is converted to knots by multiplying it with 0.539957 as you see above.

i could simply recompile the code by modifying above line as 
 position.setSpeed(buf.readUnsignedShort());

but instead i want it to be dynamic according to the value in table user_settings.

How could i do that

Thanks

ANJUM

**Comment by tananaev** [comment]
User affect the displayed speed. Value in the database should always be in knots.
