### ISSUE TITLE
add new protocol to traccar server

### ISSUE THREAD

**Issue by manee1982** [tananaev/traccar#1125]
Hi tananaev.
i need to add new protocol to traccar server to make it identify my new device. Here what i get from my device:
```
-1515-$GPRMC,120017.000,A,1725.6760,N,03355.9001,E,22.67,36.96,160215,,,A*6F,%{000028015180",1DT 
```
where is the 1515 is the id of our new device id we make it by the device configuration software given by manufacturer.

we made all the process required to add new protocol. please give an advice.

**Comment by tananaev** [comment]
It looks very similar to T55 protocol, so you probably just need to slightly modify T55 decoder to handle your format.
