### ISSUE TITLE
Traccar extended information into Opengts?

### ISSUE THREAD

**Issue by fm500** [tananaev/traccar#1128]
Traccar offers mcc, mnc, lac, cellID, index, altitude, etc.

Is there any way to pass some of this data into OpenGTS?  I opened up the OpenGTS DB table and for events like CellID and others, they are blank.  When I run traccar without opengts integration, traccar shows them.

If it's a hassle or difficult -- any easy way to just log this to a file?

I see issue #855 which touches on this somewhat, but honestly I'm not a SQL developer so I do not know how to do this.

Optimally the traccar would file the information appropriately into OpenGTS.

**Comment by satbikkel** [comment]
you need netbeans and basic java.  take a look at DatabaseDataManager.java, Position.java, and your protocol server.

**Comment by fm500** [comment]
I'm completely lost.  It's probably hopeless, but I added the following to traccar.cfg and it didn't help.  It would no longer update the DB.  So I removed it.

The change from the default opengts integration file is the addition of "cellTowerID" and ":cell" into the two lines respectively.

Likely, if I need development knowledge I won't be able to tackle it.

            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, cellTowerID, address)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', UNIX_TIMESTAMP(NOW()), :cell, :address);

**Comment by tananaev** [comment]
Ignore @satbikkel's comment. You need to replace `:cell` with `ExtractValue(:extended_info, '/info/cell')`.

**Comment by fm500** [comment]
Perfect.  I went back and grabbed ALL the goods.  I stuffed the whole extended info mess in rawData  incase I need to later -- I'm not sure why that was being set to null.

Works great.

    <entry key='database.insertPosition'>
        START TRANSACTION;
            UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE imeiNumber = :device_id;
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = :device_id;
            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address, cellTowerID, mobileCountryCode, mobileNetworkCode, locationAreaCode)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, :extended_info, UNIX_TIMESTAMP(NOW()), :address, ExtractValue(:extended_info, '/info/cell'), ExtractValue(:extended_info, '/info/mcc'), ExtractValue(:extended_info, '/info/mnc'), ExtractValue(:extended_info, '/info/lac'));
        COMMIT;
    </entry>

**Comment by tananaev** [comment]
Thanks for feedback and for sharing your config.

**Comment by fm500** [comment]
It works great; but when a device doesn't report one of the required values in its update, it will not update the DB because the data is missing.  This can also happen as you add multiple devices and some server ports provide data elements and others don't.

Is there any way to allow the update to not fail if the required data is not present or the device can not supply the data?

2015-03-23 00:37:27  WARN: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'address, cellTowerID)

**Comment by tananaev** [comment]
You can use `IFNULL` function to provide default value:
<pre>IFNULL(ExtractValue(:extended_info, '/info/cell'), 0)</pre>

**Comment by fm500** [comment]
It didn't like it.  I changed the top to the bottom.  Do you see a syntax error I might be missing?

2015-04-18 20:59:34 DEBUG: [5002 <- 194.88.242.112] - HEX: 283032373034333034373536324252303031353034313841343333342e383931324e31313631392e31363238573030302e31323031393131302e3030303030303030303030304c303030303030303029
2015-04-18 20:59:34  INFO: device: 27043047562, time: Sat Apr 18 20:19:11 UTC 2015, lat: 43.58152, lon: -116.31938
2015-04-18 20:59:35  WARN: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COMMIT' at line 3 - com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException (NativeConstructorAccessorImpl.java:-2)
2015-04-18 20:59:36 DEBUG: [5002 <- 194.88.242.112] - HEX: 283032373034333034373536324250303030303030323730343330343735363248534f29
2015-04-18 20:59:36 DEBUG: [5002 -> 194.88.242.112] - HEX: 283032373034333034373536324150303148534f29


            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, :extended_info, UNIX_TIMESTAMP(NOW()), :address, ExtractValue(:extended_info, '/info/cell'), ExtractValue(:extended_info, '/info/mcc'), ExtractValue(:extended_info, '/info/mnc'), ExtractValue(:extended_info, '/info/lac'))


            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, :extended_info, UNIX_TIMESTAMP(NOW()), :address, IFNULL(ExtractValue(:extended_info, '/info/cell'), 0), IFNULL(ExtractValue(:extended_info, '/info/mcc'), 0), IFNULL(ExtractValue(:extended_info, '/info/mnc'), 0), IFNULL(ExtractValue(:extended_info, '/info/lac'), 0))

**Comment by esteves67** [comment]
it isnt working for me =( what version of traccar are you using? im using 3.6 and can't get extended information to opengts to work =(( it just dont update the db, i already tried the ifnull or nullif dont work either =/

**Comment by esteves67** [comment]
im trying to pass battery data from traccar android through extended info to opengts

**Comment by tananaev** [comment]
New version of Traccar save data in the JSON format. If you want XML, try this config parameter:
```xml
<entry key='database.xml'>true</entry>
```

**Comment by esteves67** [comment]
Thank you so much ! i couldnt get 3.6 to work with extended info, but got 3.1 to work with the database.xml parameter, just one more question im getting values 40% battery = 4000% how to fix it ?

**Comment by tananaev** [comment]
Please create a separate issue to discuss any problems that you have.
