### ISSUE TITLE
traccar refuses to start with "logger.enable true" in opengts integration configuration.

### ISSUE THREAD

**Issue by fm500** [tananaev/traccar#1129]
When:
 
    <entry key='logger.enable'>false</entry>

Is changed to:

 
    <entry key='logger.enable'>true</entry>

When using this configuration file:

https://www.traccar.org/docs/opengts.jsp

Traccar refuses to start:

STATUS | wrapper  | 2015/03/22 22:50:23 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/03/22 22:50:23 | Java Service Wrapper Community Edition 64-bit 3.5.25
STATUS | wrapper  | 2015/03/22 22:50:23 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/03/22 22:50:23 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/03/22 22:50:23 |
STATUS | wrapper  | 2015/03/22 22:50:23 | Launching a JVM...
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp:
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at org.apache.log4j.FileAppender.<init>(FileAppender.java:110)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at org.apache.log4j.DailyRollingFileAppender.<init>(DailyRollingFileAppender.java:203)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at org.traccar.helper.Log.setupLogger(Log.java:46)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at org.traccar.ServerManager.init(ServerManager.java:97)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:27)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:290)
INFO   | jvm 1    | 2015/03/22 22:50:24 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2015/03/22 22:50:26 | <-- Wrapper Stopped

**Comment by tananaev** [comment]
You need to specify a path where you want to put log file:
<pre>&lt;entry key='logger.file'&gt;/full/path/to/tracker-server.log&lt;/entry&gt;</pre>
or:
<pre>&lt;entry key='logger.file'&gt;C:\some\windows\path\tracker-server.log&lt;/entry&gt;</pre>

**Comment by fm500** [comment]
Works great; thanks closed.
