### ISSUE TITLE
What is the port number of Teltonika FM1202 for traccar?

### ISSUE THREAD

**Issue by KrishnaKumar12391** [tananaev/traccar#1132]
i need to configure this device to traccar.. what is the port no of this?

**Comment by tananaev** [comment]
Try port 5027.

**Comment by KrishnaKumar12391** [comment]
this port is also not working.. now also i am not getting the data... any other option for fix this...

**Comment by tananaev** [comment]
Do you see any HEX messages in the log file?

**Comment by KrishnaKumar12391** [comment]
no, i didnt see.......

**Comment by tananaev** [comment]
It means either your device can't connect to the server (possibly firewall or router issue) or it doesn't send any data.

**Comment by KrishnaKumar12391** [comment]
how to check that? device connected or not.?

**Comment by tananaev** [comment]
You can start by checking if port is visible from internet. For example <a href="http://www.tananaev.com/port.html">here</a>.

**Comment by KrishnaKumar12391** [comment]
i had check.. Result -Port is closed, its means connected or not?

**Comment by tananaev** [comment]
Port is closed means that your computer is not visible from internet. Do you have public IP? If yes, then there must be some problem with router or firewall.
