### ISSUE TITLE
Unable to view added device on the webpage

### ISSUE THREAD

**Issue by femiadeyemi** [tananaev/traccar#1133]
Hi,
I successfully installed traccar server and later add a device using the webpage localhost:8082. But unfortunately I couldn't see the device on the webpage and I even try to add it again, and I recieved an error message saying the device is already existing. I check the tracker-server.log and device is sending its location and I can see the lat and lon but is not display on the webpage. Please what can I do to rectify this. Thank you

**Comment by tananaev** [comment]
Looks like you already have a device in the database, but it's not linked to your account. What you can do is to remove database and try again:
1. Stop Traccar service
2. Remove all files from `data` directory
3. Start Traccar service
4. Add device and try again

**Comment by femiadeyemi** [comment]
It works like a charm! Thank you.
