### ISSUE TITLE
arnavi protocol

### ISSUE THREAD

**Issue by vokivit** [tananaev/traccar#1134]
Got troubles with identifying trcker's protocol
device: Arnavi
protocol info here (sorry, couldn't find english version) http://st.kupit-glonass.ru/9/1063/139/protokol-arnavi.pdf
for example
$AV,V2 - Main Message GPSLite V2
//1 2 3 4 5 6 7 8 9 10 11 12 1314 15 16 17 18 19 20 21
$AV,V2,32768,12487,2277, 203, -1, 0,0,193,0, 0,
1,13,200741,5950.6773N,03029.1043E,0.0, 0.0, 121012,*6E
Thanks!
UPD: 
HEX: d10800970000000032c63661f5100300e1
Decoded HEX: Ñ2Æ6aõá

**Comment by tananaev** [comment]
It looks like it's not supported yet. I have added it to by backlog of new protocols.

**Comment by tananaev** [comment]
Protocol is implemented (7ccf052eec0d2d71903c99bd8620c2bbfa45f311).
