### ISSUE TITLE
TK104 over UDP

### ISSUE THREAD

**Issue by ke5stl** [tananaev/traccar#1135]
it appears that the Gps103ProtocolDecoder does not support the use of UDP.

the TK104 that I'm trying to use has the ability to use UDP, which consumes less battery power than TCP, so I'd like to be able to use that instead of TCP.

please can we have GPS103 improved to support UDP too?

best regards,
peter

**Comment by tananaev** [comment]
It does support UDP.

**Comment by ke5stl** [comment]
my bad.  I was looking at an older version of code.  Thank you!
