### ISSUE TITLE
Queclink GV500 support?

### ISSUE THREAD

**Issue by SoapyMan** [tananaev/traccar#1151]
Does Queclink GV500 devices supported? Are they use gl200 protocol?

**Comment by tananaev** [comment]
Unless they changed protocol it should work just fine on GL200 port. Let me know if it works. If it doesn't, let me know as well and I will try to fix it.

**Comment by daipayan-matrix** [comment]
I have a query, I had installed the Driver in my laptop. Added the Server FTP path and allowed the port in the server. But problem is no file is generated in the provided FTP. Am tried to search a lot but no where I find any sort of files with GPS data.

Am using GL50X @Track Air Interface Protocol R3.00

Anyone please guide me!
