### ISSUE TITLE
GT02 ( GT02A !? ) Clone Unknown Protocoll

### ISSUE THREAD

**Issue by somebuddy87** [tananaev/traccar#1152]
I bought the following GPS Tracker and want it to work with traccar.

http://www.amg-haendler.de/GPS-Tracker-AmgoTrack-500-Festeinbau-12-24-V

It looks like this one : http://www.dx.com/p/goome-gt02a-gps-gsm-gps-alarm-car-motorcycle-positioning-tracker-black-12-36v-222881#.VRu4D_msWwU

Working with Port 5000: shows no match.  Only "error" or no match.

There is no protocoll documentation for this tracker available.

LOG:
```
2015-04-01 11:10:49 DEBUG: [5002 <- 80.187.109.173] - HEX: 68681906040358899051834706000b1a010a2123272e1d20222f28100d0a
2015-04-01 11:10:59 DEBUG: [5002 <- 80.187.109.173] - HEX: 68681906040358899051834706000c1a010a1e1c232c1b1a222b290f0d0a
```
I hope someone can help me.
Thank you!

**Comment by tananaev** [comment]
Have you tried gt02 protocol (port 5022)?

**Comment by somebuddy87** [comment]
Thank you ! It works like a charm..
I treid gt02 before without success. Nevermind...
