### ISSUE TITLE
Reverse geocoding for Arabic street names

### ISSUE THREAD

**Issue by farbeed** [tananaev/traccar#1153]
Hi,

I have a problem in the reverse geocoding, I started  Traccar  with Mysql and it is worked , but the data stored at database in the address field have some ????  
Example:
LAT:31.941313 LON:35.9534315
The result look like

Al Yarmouk, ?????, Amman, 009626, ??????

can any one support?

**Comment by tananaev** [comment]
Looks like there is some encoding problem. You can try to set database connection encoding to UTF-8:
<pre>useUnicode=true&amp;characterEncoding=utf8</pre>

You might need to change MySQL server encoding as well.

**Comment by farbeed** [comment]
Hi Anton

where shall I add this code exactly? I tried to do but it did not worked with me

**Comment by tananaev** [comment]
At the end of the `database.url` parameter in the config file.

So it should look something like this:
<pre>&lt;entry key='database.url'&gt;jdbc:mysql://localhost:3306/db?allowMultiQueries=true&amp;amp;useUnicode=true&amp;amp;characterEncoding=utf8&lt;/entry&gt;</pre>

**Comment by farbeed** [comment]
It worked :)

**Comment by vzoltan** [comment]
What version of traccar do you have, and how did you turn on reverse geocoding feature?
thanks

**Comment by tananaev** [comment]
All recent versions support reverse geocoding. As for turning on reverse geocoding, see <a href="https://www.traccar.org/configuration-file/">the config file documentation</a>.

**Comment by vzoltan** [comment]
Thanks, it works ok. (use it with google api now)

However, is it possible to configure this to cut/remove the zip code and the country?

**Comment by tananaev** [comment]
Currently it's not possible. If you really need it please create a separate thread for this feature request.

**Comment by tananaev** [comment]
Address formatting has been available for some time now.
