### ISSUE TITLE
Cannot log into demo

### ISSUE THREAD

**Issue by johnjohndoe** [tananaev/traccar#1159]
The [website](https://www.traccar.org) advertises the [demo instance](http://demo.traccar.org). However it does not tell which **user** name and **password** one could use. When I click on `Register` nothing happens. I could not see any errors in the browser console.

**Comment by tananaev** [comment]
You need to register a new user. Fill out user and password and click Register button.

**Comment by johnjohndoe** [comment]
Okay, now it works. You could possible explicitly tell so on the website. Thank you.
