### ISSUE TITLE
gt02a clone does not send any data

### ISSUE THREAD

**Issue by ekaftan** [tananaev/traccar#1163]
I have two of these: http://www.aliexpress.com/item/Guaranteed-100-4-band-car-GPS-tracker-GT02A-Google-link-real-time-tracking-free-shipping/1257279802.html

I have failed to configure them with traccar. I tried port 5002 and 5022, but the device opens the socket and then never sends any data. Nothing gets logged and tcpdump shows just the connection being open and nothing else.

Is this a workable product or should I just trash them?

Thanks.

**Comment by tananaev** [comment]
As far as I know many people successfully use this or similar devices with Traccar, but it sound like your one has some issue. Possibly firmware bug or just a configuration problem.

**Comment by ekaftan** [comment]
I made it work. It was the SIM I was using... it was a 'multimedia' SIM and goes through some kind of application firewall that breaks everything thats not web based.

Thanks for the fast response.
