### ISSUE TITLE
Using a message queue to improve performance

### ISSUE THREAD

**Issue by jedjones-uk** [tananaev/traccar#1165]
HI Anton,

Traccar is a great and stable piece of software, but I find it can be quickly overwhelmed with devices, especially if the database it is writing to is not the same structure used in your builds. I was thinking about adding the ability to write those messages to a message queue instead of a database. Something like Kafka with persistence would mean traccar only has to deal with receiving and decoding the messages and another micro-service could be used to read from the queue and write it to more permanent storage like a database.

Using the queue would also allow other micro-services to subscribe to the messages and can then do more advanced real-time processing without any delay in the device service.

Is there any reason this idea would not work or should not be done?

Jed

**Comment by tananaev** [comment]
There is a plan to add API to be able to access messages in real time. As for queue, I'm not sure about that. If database can't handle number of devices, then something should be done about the database or insert query.

**Comment by jedjones-uk** [comment]
The issue is that badly designed devices will ddos a server whenever it comes back online after some downtime and cause more downtime and lost messages. The advantage of a queue is that it can receive the messages much quicker than a database can write them, and once in the queue you have a level of persistence so you can take as much time and attempts as necessary to write to the database and other real time processing.

The reason I am interested in this is because we have had to run traccar as a series of micro servers behind HA Proxy to be able to handle just 1250 devices because  the traccar connection pool was reaching its limit. Now we have 14 traccar end points to receive the data and they all write to the same database that a single instances wrote too. This has fixed our issue but is not ideal as it creates a much bigger infrastructure cost.

**Comment by tananaev** [comment]
I know people who use Traccar with more than 10k devices and it works fine with just one instance.

**Comment by jedjones-uk** [comment]
Do you happen to know what kind of server spec they have because we had constant timeouts on a single 16GB instance with just 1250 devices.

**Comment by tananaev** [comment]
Unfortunately I don't, but I'm pretty sure 16GB should be more than enough for 1250 devices. What OS are you using? Maybe you reached the limit on number of open connections?

**Comment by jedjones-uk** [comment]
They are running on CentOS 6, and it appears that its traccars connection limit we were reaching vs an OS limit. This is why I am interested in offloading a connection from traccar ASAP vs waiting for a database write.

**Comment by tananaev** [comment]
I think on Linux by default the limit is around 1000 connections, so you definitely need to change it.

**Comment by jedjones-uk** [comment]
Ok, thanks, I will experiment with that and see how it goes.

**Comment by ahmedaswai** [comment]
I used Redis Publish Subscribe and I achieved great really really short response time even after I added more business logic to the handlers and the filters.

**Comment by m-menon** [comment]
hi, does anyone know how to increase the number of open connections on Ubuntu? I think I may hit a similar problem in time to come. A ulimit -n returns me 1024 ... which indicates that there is a 1024 connection limit by default on Ubuntu 14 LTS. 

Edit etc/sysctl.conf or something - if yes then does any other options needs to be set as well?

Thanks

**Comment by tananaev** [comment]
You can try some suggestions from this thread:

http://stackoverflow.com/questions/21515463/how-to-increase-maximum-file-open-limit-ulimit-in-ubuntu

**Comment by m-menon** [comment]
Great thanks :100:
