### ISSUE TITLE
GSM Base Location T322 not working When GPS Invalid

### ISSUE THREAD

**Issue by bernamaxim** [tananaev/traccar#1169]
When I get GPS Signal Invalid (V), it cannot get location data in LBS.
```
2015-04-16 03:42:34 DEBUG: [5020 <- 114.121.134.153] - HEX: 24247538362c3836323935313032303030363632342c4343432c02013400010000001fd955a2ffe2525f06f1ebc11c0000180000000000000000a9e7050003360200fe010a007a0055000001af8da301ef04000000002a62310d0a
2015-04-16 03:42:34 DEBUG: [5020 -> 114.121.134.153] - HEX: 40407532372c3836323935313032303030363632342c4343432c312a30390d0a
```

What should I do for fix it?

**Comment by bernamaxim** [comment]
I think it about ```MCC|MNC|LAC|CI```
But, i don't have idea for translate it to coordinat locations.

**Comment by tananaev** [comment]
Traccar does not support LBS yet. To add support we need to find a provider first.

**Comment by soulraven** [comment]
is hard to impossibile to find a good provider, opensource solution is openCell but is not complete.
Any ideea will be great to know

**Comment by Abyss777** [comment]
Supporting LBS is greate feature

Maybe something will be usefull:
https://location.services.mozilla.com/api (a bit bigger than openCell ID)
http://unwiredlabs.com/api (cool coverage, has free account)
Secret google API (if it's true) http://www.google.com/glm/mmap?mcc=xxx&mnc=xxx&towerid=xxx (http://stackoverflow.com/questions/1598696/google-maps-cellid-to-location)

**Comment by tananaev** [comment]
LBS locations have been supported for a while now, so closing this.
