### ISSUE TITLE
JI 109

### ISSUE THREAD

**Issue by ajit-bhingarkar** [tananaev/traccar#1170]
Dear Anton and team,

While testing the server for JI 109 protocol while some protocols work for some others I am able to get expected response. Does the latest build fully support JI 109?

Any guidance will really be helpful. Could there be something missing in DB? I am using default, which seems to be h2.

Some of the requests and responses are below:
```
78781F120E040F0A100F10CC027AC7EB0C46584900148F01CC00287D001FB8000380810D0A --- --- GPS, LBS information packet 38 bytes
78 78 05 12 B8 00 56 0A 0D 0A

78780A13000504000003F352940D0A  --- status message (works as expected)
78 78 05 13 03 F3 17 04 0D 0A

787825160B03110A1010CF027AC8450C4657410014000901CC00266A001E236006040001000A34620D0A -- STATUSGPS.LBS.STATUS 
78 78 05 16 00 0A 6E 9F 0D 0A

787825160B051B093523CF027AC8360C4657B30014000901CC00266A001E1740050400020008D7B10D0A
78 78 05 16 00 08 4D 8D 0D 0A

7878241701CC00266A001E233132353230313337393037373430353100000000000001000B1F1A0D0A
78 78 05 17 00 0B 25 CA 0D 0A
```
Thanks in advance,
Ajit

**Comment by tananaev** [comment]
This is GT06 protocol which is supported by Traccar. The problem is that your device doesn't send any GPS data.
