### ISSUE TITLE
How many devices (GPS) can support simultaneous active Traccar Server

### ISSUE THREAD

**Issue by maulunag** [tananaev/traccar#1172]
How many devices (GPS) can support simultaneous active Traccar Server

**Comment by kokram** [comment]
Hi Maulunag,




I connected simultaneously 30000 devices successfully.




Regards.



—
Enviado desde Mailbox

**Comment by Blejzer** [comment]
@kokram
Can you let me know what is your configuration (hardware, software)?
 I could not find any valid way of testing...

Regards,

**Comment by maulunag** [comment]
I have at Amazon Web Services , the basic plan , with Ubuntu 14.04 and working with TK102 and TK103 GPS devices

**Comment by joepr** [comment]
Thanks for the info! I was looking to ask this same question.

**Comment by akmal1999** [comment]
@maulunag when you added the tk102 did you give the full imei or only 12 digit from right side? Mine server does not find the tk102.

**Comment by tananaev** [comment]
@akmal1999, easiest options is to add 2 devices. One with full IMEI and one with 12-digit id.
