### ISSUE TITLE
Is possible to read power (battery level) on protocol h02?

### ISSUE THREAD

**Issue by joepr** [tananaev/traccar#1173]
Greetings Everyone!

I do have a few of GPS trackers that use protocol h02. Everything seems to be working perfectly. However I will like to know if someone here had manage to read the battery level ton this GPS Devices. I do see the option on the traccar web however no data is displayed. Any help will be appreciated.

**Comment by tananaev** [comment]
As far as I understand H02 messages don't include battery info, but the [protocol documentation](https://www.traccar.org/protocols/) is in Chinese, so I'm not too sure.

**Comment by joepr** [comment]
Hello Tannaev

Thanks for the reply. Yes I notice the h02 protocol did not pass the battery level Info. Bad luck for me. I appreciate your time and effort

**Comment by catrucho** [comment]
I have a RF-V8S that is quite similar to RF-16 and uses H02 protocol.
I have managed to read the battery level.
If you are able to send a command to the gps through a GPRS connection like
*XX,YYYYYYYYY,S26,HHMMSS#
where XX is manufactor code (HQ in my case), YYYYYYYY is the gps device ID number, S26 is the command to read the device status, and HHMMSS is the time code like 071500.
The device will answer 

*HQ,7310028651,LINK,073351,100,0,86,0,0,020815,FFFFFFFF#

Where 
HQ-manufacturer
7310028651 Device ID number
Link (¿¿??)
100 (¿¿??)
0 (¿¿??)
86 is the battery level in percentage.
020815 is the time code in HHMMSS
FFFFFF is alarm status ( like low battery level, etc)

**Comment by joepr** [comment]
Hello catrucho

Yes! you are right if you send a SMS command to the GPS tracker 

example: where

It will reply the location as long with additional information like serial number and battery level. This is a good addition however it will not send the battery level to the server or software you are using to read the GPS data. This is a good protocol however is not a perfect one!

Thanks for your reply!

**Comment by catrucho** [comment]
I believe is a question of the server or the software not getting this info, the tracker is passing this info, now the traccar or the protocol have to be modify to get this info and showed and loged, but I am not sure.

**Comment by tananaev** [comment]
The problem is that Traccar doesn't support messages without GPS info yet. I plan to add support for those kind of messages in one of the next versions.

**Comment by catrucho** [comment]
It's not the full document in chinese but It's in english.
Part of the H02 protocol.
https://drive.google.com/open?id=0Bw13bQgIGLTaN3NYdGJIZU0tdWs&authuser=0

**Comment by catrucho** [comment]
I found out that H02 protocol send another kind of packets
The normal one V1 with GPS position, speed, 
'*HQ,123456789012345,V1,121300,A,6000.0000,N,13000.0000,E,0.00,0.00,010112,ffffffff,000000,000000,000000,000000#',
The one with LINK with GSM, GPS and other levels, as stated above.
*HQ,7310028651,LINK,073351,100,0,86,0,0,020815,FFFFFFFF#
And a third one that in my device is something like
*HQ,7310028651,NBR,062045,214,3,255,6,13110,7518,151,13110,39,157,13110,7514,146,13110,72,146,13110,7841,145,13110,12,145,080815,FFFDFFFF#

That is related to the GSM CELL ID (MCC, MNC,LAC,CID) when there is no GPS signal, what is very useful, this can be search in http://opencellid.org/ ( a believe that they have and api to search too) and gps position the cell with gps coordinates that gives a quite accurate position even withouth gps signal.

I am no programmer but I was having a look at the file H02ProtocolDecoder.java and as far as I understand everything that doesn't much the first chain with gps position is discarded, am I right? 

WOuld it be difficult to implement the "link" string to read and add battery level and even in the future the last chain to check position by gsm cell or would it be too difiicult ?

As far as I understand the battery level wouldn't be very difficult but the third one would be more difficult right ?

Thanks.

**Comment by tananaev** [comment]
You are correct that everything that doesn't have GPS info is discarded. As I said before I am aware of this issue and plan to solve it in future.

Using GSM cell information to estimate location is also in plans.

**Comment by jpambulo** [comment]
were you able to solve this problem? I am also using h02 protocol and want to save the battery life info of the device.

**Comment by tananaev** [comment]
@jpambulo, battery info is supported for H02 protocol.

**Comment by jpambulo** [comment]
@tananaev I only get these as attribute values. 

 {"power":5,"ignition":false,"status":4294966271,"ip":"121.54.44.167","distance":0.0,"totalDistance":361.33}

**Comment by tananaev** [comment]
The "power" is the battery value.

**Comment by usr2017** [comment]
Hy
I have an obd2 gps tracker (clone from china)that use h02 protocol and I want to change time zone.
Please tell me how to do this via sms.

**Comment by tananaev** [comment]
Please don't comment on old closed threads.
