### ISSUE TITLE
Eelink GOT10

### ISSUE THREAD

**Issue by piresbruno** [tananaev/traccar#1176]
Anyone here has an Eelink GOT device?
I need to update the firmware to v1.8.5 but i don't find anywhere the firmware package or remote server configuration to do it.

Thanks,
Bruno

**Comment by tananaev** [comment]
Have you tried to ask manufacturer?

**Comment by piresbruno** [comment]
Yes, i seems like they don't want to give access to the info, because the hardware was bought to a third party.
At the time i didn't knew that Eelink was the manufacturer... and the buy i've bought it from is not very responsive, so if i don't find a way to update it, i'm  stuck, because the latest version of the firmware has the feature why i've bought the device...

**Comment by tananaev** [comment]
Try to ask in issue #907.

**Comment by piresbruno** [comment]
Thanks

**Comment by vzoltan** [comment]
18. Remote Upgrade
UPGRADE,upgrade package,
domain name / IP, port #
Example:
UPGRADE,C4_EXT.exf,www.sky200.com,69#


http://www.eelink.com.cn/uploads/datasheet/GPS_TRACKER_OPERATION_COMMANDS(D).pdf
