### ISSUE TITLE
traccar working  for me but...can't show in opengts.

### ISSUE THREAD

**Issue by VanitySoft** [tananaev/traccar#1179]
I am sure I am doing a configuration  wrong somewhere. I currently have  traccar setup  and my device is registered and communicating nicely....I updated the configuration to use my opengts instance.restarted successfully... however data is not being..is there some  steps I missed with the opengts integration?  Thanks.

**Comment by tananaev** [comment]
Do you mean it doesn't work in OpenGTS? What do you see in the log (tracker-server.log)?

**Comment by VanitySoft** [comment]
yes, i mean't OpenGTS.  
looks like the DB may have got corrupt?...

2015-04-23 11:11:35  INFO: device: 357730060585347, time: Thu Apr 23 11:11:23 UTC 2015, lat: 38.905825, lon: -77.006316
2015-04-23 11:11:35  WARN: Duplicate entry 'sysadmin-357730060585347-1429787483-0' for key 'PRIMARY' - com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException (NativeConstructorAccessorImpl.java:-2)

**Comment by tananaev** [comment]
Probably it means that device sends old duplicate data and because of some unique constraints in OpenGTS database it's impossible to add duplicates to the table.

**Comment by VanitySoft** [comment]
ah never-mind, it works :). it was a WARN(just so it wont add dups). i had to refresh the UI.  Thanks for getting back to me quickly!
