### ISSUE TITLE
notification extended

### ISSUE THREAD

**Issue by adipo** [tananaev/traccar#1180]
Hello,

It is possible to extend notification menu with something more flexible like an http request or launch an application?

Thank you

**Comment by tananaev** [comment]
What notification menu are you talking about?

**Comment by adipo** [comment]
Hello Anton,

For notification we have email and Pushbullet as options. For me it would be easy to start applications or to send http commands.

This way I could follow watchman making his guard tour on a CCTV system or I could detect presence of a peron in a dangerous area and switch off some dangerous equipaments. 

With http commans and some dedicated equipaments it is posiible to send sms or make all kind of automations.

Thank you

**Comment by tananaev** [comment]
Traccar doesn't have any notifications yet.

**Comment by tananaev** [comment]
Traccar supports HTTP event forwarding.
