### ISSUE TITLE
Feature Request: Ability to add Custom EventHandler via configuration.

### ISSUE THREAD

**Issue by VanitySoft** [tananaev/traccar#1181]
I need to send events received from connected devices to something other than a database.(JMS, Another web service,etc.) .  I am planning on juts doing this programatically in the code...but i can see other projects wanted this functionality.

**Comment by vitalidze** [comment]
This will be very useful. Vote for it.

**Comment by tananaev** [comment]
There is an HTTP event forwarding available. I believe it should be enough for any custom functionality. Please re-open if it's not.
