### ISSUE TITLE
Device FL2000G Protocol

### ISSUE THREAD

**Issue by ramarize** [tananaev/traccar#1184]
Hello;
Can you please guide me to write new decoder for FL2000G, The device is sending 
this data 5B 80 30313030313030303031 0B 3133353132333435363738 5D
and the server sould response with this : 5B 00 30313030313030303031 0C 33 3133353132333435363738 5D, didnt manage to find any protocol using the same logic as this one, please help
Thank you

**Comment by ramarize** [comment]
Update
for this example I use 13512345678 as imei

**Comment by tananaev** [comment]
Looks like Traccar doesn't support it yet. I need protocol specifications to implement support.

**Comment by ramarize** [comment]
Hello 
You may find the protocols at this link : http://s000.tinyupload.com/index.php?file_id=43585586354232592782
However, I was so far I manage to send login to the device but I am stucked at (Heartbeat packet) which must be as fellow 
device send  5B F0 30313030313030303031 0B 3133353132333435363738 5D
and the response must be as : HEX:5B FF 30313030313030303031 0B 3133353132333435363738 5D
my problem was in FF which is (ÿ) as ASCII or 255  , but when I debug I get (c3bf)as hex and it is Ã¿ as text , after this device is keep sending (Heartbeat packet) every 10 minutes..
Thank you

**Comment by ramarize** [comment]
Update
2015-04-28 01:57:22 DEBUG: [5090 <- 197.252.3.13] - HEX: 5bf0303030303030303030300b31333531323334353637385d
2015-04-28 01:57:22 DEBUG: [5090 -> 197.252.3.13] - HEX: 5bc3bf30303030303030300b31333531323334353637385d

**Comment by ramarize** [comment]
Hello 
after I manage to response to the login requset and the heartbeat requset I create : 2015-04-29 18:30:48  WARN: String index out of range: 12 - java.lang.StringIndexOutOfBoundsException (String.java:1950)...
and this the Hex from the device side 5b9330303030303030303030462849545631353330343741313533342e303830354e30333233332e30383838453030302e30303032393034313530303030303430302657737a2d776c303031264230303030295d
any help?
Thank you

**Comment by tananaev** [comment]
It is TK102 protocol (port 5036). I have fixed one issue with decoder and it should work correctly now.

**Comment by ramarize** [comment]
Yes , it is almost  same as TK102 and the delimiter must edit as well
Thank you another Great answer.
