### ISSUE TITLE
sql server config to traccar config file

### ISSUE THREAD

**Issue by behibehzad** [tananaev/traccar#1185]
Hi i change my config file to this :

```
<entry key='database.driverFile'>C:\Program Files (x86)\Traccar\lib\sqljdbc_4.1\enu\sqljdbc4.jar</entry>
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
<entry key='database.url'>jdbc:sqlserver://185.55.224.88\MSSQLSERVER;user=myradyab.ir_behzad;password=xxxxxxxx;</entry>
<entry key='database.user'>myradyab.ir_behzad</entry>
<entry key='database.password'>xxxxxxxx</entry>
```

but in the my sql server database,i dont have any table,where write data traccar?how can i see data into the sql server?

**Comment by tananaev** [comment]
You need to open web interface to initialize database schema. If you have already tried that it didn't work, please provide logs (wrapper.log).

**Comment by behibehzad** [comment]
I try to open localhost:8082 but when i enter the admin user name and password,no happen event into the web and show me log in page!

**Comment by tananaev** [comment]
If you are using Chrome browser, try to open developer tools and and see if there are any errors on Network or Console tabs.

**Comment by behibehzad** [comment]
thanks,but i use the firefox browser,how can i open developer tools in the firefox browser?

**Comment by tananaev** [comment]
Not sure, but there must be something similar in Firefox browser as well.

**Comment by behibehzad** [comment]
ok,i install the chrome browser,please help me how can i to open developer tools in chrome?

**Comment by tananaev** [comment]
Press Menu button in the top right corner, then More Tools -> Developer Tools.

**Comment by behibehzad** [comment]
i open the developer tools and console tab,in console tab and status column write this:pending

**Comment by behibehzad** [comment]
my server address is :http://46.105.248.69:8082/ please help me ,thanks.

**Comment by tananaev** [comment]
It means server doesn't respond. What are hardware specs of your server? Check `wrapper.log` file to see if there are any errors there.

**Comment by behibehzad** [comment]
my wrapper.log is:STATUS | wrapper  | 2015/04/25 07:00:10 | Pinging the JVM took 8 seconds to respond.

**Comment by tananaev** [comment]
How much memory (RAM) do you have on the server?

**Comment by behibehzad** [comment]
thanks my friend to pay attention to my problem,512M

**Comment by tananaev** [comment]
That might not be enough especially considering that you are running it on Windows which probably uses at least half of that memory for the system processes.

**Comment by behibehzad** [comment]
are the 2GB ram is enough?thanks.

**Comment by behibehzad** [comment]
and my sql server database into the host,and my traccer web on the vps

**Comment by tananaev** [comment]
It depends on the number of devices, but 2GB should be enough for a few hundred or maybe even 1000s.
