### ISSUE TITLE
How can i reset username and password

### ISSUE THREAD

**Issue by behibehzad** [tananaev/traccar#1187]
Hi,i'm forget my user name and password,how can i reset it to admin for username and admin to password.

**Comment by tananaev** [comment]
You need to change it manually in the database. Are you using default H2 database?

**Comment by behibehzad** [comment]
Yes, i use that,how can i change?

**Comment by tananaev** [comment]
You need to open database file using any JDBC viewer (for example H2 console) and change password in the `users` table. Note that you need to stop Traccar service first.

**Comment by emmerossi** [comment]
Hi, similar question...forgot ADMIN password. Trying to use H2 console, opening jdbc:h2:tcp://localhost/Traccar/data/database.mv.db.h2 is this correct ? or should I open jdbc:h2:tcp://localhost/Traccar/data/database.mv ? I've the same result, cannot see user's table

**Comment by tananaev** [comment]
To connect to H2 database you need to stop Traccar first. Then use connection parameters that you can find in Traccar config file (URL, user and password).

Starting from Traccar version 3, the password is hashed. You can use values from the following comment to reset your password: https://github.com/tananaev/traccar/issues/1293#issuecomment-121156068.

**Comment by emmerossi** [comment]
Hi, tried again but cannot see the users. I first stop the service, then use H2 console and using SELECT * FROM INFORMATION_SCHEMA.USERS the only user listed is "sa" while other useres have been created.

**Comment by tananaev** [comment]
What database URL are you using? As for query, to see all users you just need to run:

<pre>SELECT * FROM USERS;</pre>

**Comment by emmerossi** [comment]
Thanks for prompt reply : I'm trying to use  
1) jdbc:h2:tcp://localhost/Traccar/data/database.mv.db.h2 
2) jdbc:h2:tcp://localhost/Traccar/data/database.mv 
3) jdbc:h2:C:\Users\Administrator\Desktop\BCRS demo SW\Traccar\data\database 
DB is H2, same results for 1-2-3

**Comment by tananaev** [comment]
Is the last one from Traccar config file? If yes, then it should work.

**Comment by emmerossi** [comment]
Absolutely, from .xml configuration file
<entry key="database.driver">org.h2.Driver</entry> <entry key="database.url">jdbc:h2:C:\Users\Administrator\Desktop\BCRS demo SW\Traccar\data\database</entry> <entry key="database.user">sa</entry> <entry key="database.password"/> <entry key="database.checkTable">traccar</entry>

**Comment by tananaev** [comment]
If Traccar works correctly with that URL, it means there is data in that database and you should be able to see it.

Make sure you stop Traccar server before accessing it.

**Comment by emmerossi** [comment]
It works, then i stop the service and play with H2. cannot paste the h2 console image in the forum...

**Comment by tananaev** [comment]
You can attach images to GitHub thread if you want.

**Comment by emmerossi** [comment]
![h2console](https://cloud.githubusercontent.com/assets/7482584/10379584/5bdb3994-6e0f-11e5-9974-062e5f3f560e.png)
![h2console](https://cloud.githubusercontent.com/assets/7482584/10379665/c7ac54aa-6e0f-11e5-8e32-7b8a1a30f6ff.png)

**Comment by tananaev** [comment]
I just compared with my local database.

First of all, you shouldn't be using `INFROAMTION_SCHEMA'. It contains H2 system tables and not Traccar ones. There should be a `PUBLIC` schema which should have a `USER` table in it (assuming you have Traccar version 3+). That's what you need.

If you don't have that, it means you are doing something wrong. E.g. connecting to the wrong database.

**Comment by emmerossi** [comment]
thank you for suggestion will investigate.
