### ISSUE TITLE
Proposal: ManyToMany table with key--value

### ISSUE THREAD

**Issue by LimitTech** [tananaev/traccar#1190]
Hello!

I really love traccar server. I'm using it with some Teltonika devices.

Maybe an improvement of the database structure would be adding a table called "others" or similar with three columns: 
position_id (FK to positions)
io (a string. Well, using Teltokina I saw io are labeled as ioXXX, maybe a super-improvement would be creating a table of 'io' and this field FK to it)
value (string? int?)

This table could be seeded by parsing the 'other' column of positions.

Have a nice day!

**Comment by tananaev** [comment]
What are the benefits of doing it this way?

**Comment by LimitTech** [comment]
Well, imagine you want to know how many times an io has values and which ones or maybe "Get the positions where the value of ioX is 1 or more"; using that auxiliary table you can do a very fast query.

**Comment by tananaev** [comment]
It would probably work for exact matches only because we can store only string value which in not useful in most cases.

**Comment by LimitTech** [comment]
Well, I'm to good with Java but I did a PHP script to be executed by cron.

In PHP I do:

    foreach ($xml->children() as $key => $value) {
         if (substr($key, 0, 2) === "io") {
              $io_id = substr($key, 2, 4);
               // push to insert query
           }
    }

The idea is doing something like next pictures:

![ios_table](https://cloud.githubusercontent.com/assets/6768578/7496418/472830f8-f414-11e4-9921-e17e66d80225.PNG)
![io_values_table](https://cloud.githubusercontent.com/assets/6768578/7496419/4a2b1b30-f414-11e4-8d44-d457689b8eb7.PNG)

**Comment by tananaev** [comment]
There is no plan to implement this at the moment.
