### ISSUE TITLE
Eclipse extendedInfo cannot be resolved

### ISSUE THREAD

**Issue by and12345** [tananaev/traccar#1192]
Hi great project here,
Try to add some extended info to traccar to detect fuel on GPS103ProtocolDecode.java

```
    // Additional data
    // ACC
    extendedInfo.set("ACC", parser.group(index++));

    // Door
    extendedInfo.set("Door", parser.group(index++));

    //Fuel
    extendedInfo.set("Fuel", Double.valueOf(parser.group(index++)));

    // Extended info
    position.setExtendedInfo(extendedInfo.toString());
```

But i got error on my Eclipse saying that extendedInfo cannot be resolved, please bear me cause i'm new on programming.

**Comment by tananaev** [comment]
I have re-factored some code and there is no `extendedInfo` any more. Add extra data is store directly in position object.

**Comment by and12345** [comment]
Hi Anton,

Could you please help me how to add the fuel ACC and Door into the code please.

**Comment by tananaev** [comment]
Where is the fuel and door info in this message?

**Comment by and12345** [comment]
Hi Anton,

From 0,0,45.16% : 
0/1 - engine status
0/1 door open/close
45.16% is the fuel level

**Comment by tananaev** [comment]
Traccar already parses all those values as "ioX" (where X start from 1).

**Comment by and12345** [comment]
wow, my bad dont check the git first, i think i still use the old version. 
Will try it tonight at my time, thanks a lot Anton :+1:

**Comment by and12345** [comment]
Hi Anton, just want to update that the fuel (other values) is work just wondering whether this feature is also working when integrated with opengts or is the wiki need to be update also 

<entry key='database.insertPosition'>
        INSERT INTO positions (device_id, time, valid, latitude, longitude, altitude, speed, course, power, address, other)
        VALUES (:device_id, :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :power, :address, :extended_info);
    </entry>

i see there's still extended_info there

**Comment by tananaev** [comment]
You need to add it to the query if you want to save fuel data.
