### ISSUE TITLE
How to show ignition FM4200 and GT06N

### ISSUE THREAD

**Issue by adhasyuhada** [tananaev/traccar#1195]
Hi Anton,
I'm looking for a way show ignition on/off/stop to database OpenGTS on "EventData", how must am i doing ?

**Comment by tananaev** [comment]
For GT06 there is an ACC value which I think means ignition, but the problem is that it is sent in messages without coordinates which is not supported by Traccar yet and therefore ignored. I plan to fix it in near future.

As for Teltonika, it sends bunch of IO fields and one of them is probably ignition, but you need to know id mapping.

**Comment by adhasyuhada** [comment]
What's mean id mapping ? and how to show IO for teltonika ?

**Comment by tananaev** [comment]
Teltonika devices have ids for all extra data. It is basically an integer number, but I don't know which one is ignition.

**Comment by Ndevadiga** [comment]
I have added 1 GT06N in traccar but the ACC is showing as false.. How the ACC(ignition) will be shown as true or ON. 
On which byte ACC data will be coming.. Pls help me

**Comment by tananaev** [comment]
The problem with GT06 protocol is that most of the time ACC info comes in a separate status messages without GPS data, so Traccar ignores those.

**Comment by Ndevadiga** [comment]
Then how we can get the ignition data, how we can show the acc status in
traccar application for gt06n.

Request you to help us on the same.

Thanks,

**Comment by tananaev** [comment]
Support for messages without location info is in plans.

As for now, you need to configure your device to send combined GPS+status messages, but I'm not sure if it's possible to force device to send those types of messages.

**Comment by Ndevadiga** [comment]
Could anyone help me with the GT06N ignition packet pls for the below data

78781f120f0603003618cc01658a12085213e010555c01942d3b9e00666500d9a9130d0a
78781f120f0603003706c901657e180852155017549401942d3b9e00666400dbe5390d0a
78781f120f0603003711cb01657b640852187014546f01942d3b9e00666400dcbd380d0a
78781f120f060300371bcc01657b1a08521c8016545101942d3b9e00666500dda6da0d0a
78781f120f060300382dcc01657e9a0852235018543201942d3b9e00666500de68260d0a
78781f120f060300390fcc0165897a085229b00c541a01942d3b9e001da900dfc0da0d0a
78781f120f0603003a0fcb01658e7408522c700c541c01942d3b9e001da800e0b5b80d0a
78781f120f0603003a38cb016590b208522d9000541b01942d3b9e001da900e24fed0d0a

**Comment by tananaev** [comment]
Those messages are of type 0x12 (GPS + LBS), so they don't have ignition information.

**Comment by xizoaziz** [comment]
@adhasyuhada  i'm facing this problem to  , did you found solution for it ?

**Comment by adhasyuhada** [comment]
@xizoaziz i have no solution for IO

**Comment by SudhakarDatt** [comment]
I also need help in GT06 protocol, how to identify Ignition status

**Comment by saulo1212** [comment]
I also need help in GT06 protocol, how to identify Ignition status

<Buffer 78 78 1f 12 15 04 11 0e 2e 06 c9 01 d9 66 a4 05 07 04 8c 00 18 00 02 d4 02 51 02 00 ad 9f 01 45 02 d1 0d 0a>
