### ISSUE TITLE
Listener only

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1196]
hi,

Firstly thanks a ton for a wonderful piece of Software. I am a little new to java but I have created something to nicely display vehicles / trackers - and the location data is picked up from a database currently. 

I was thinking is it possible for me to separate out just the listener part (I just need it to work with 2-3 protocols) and use that for receiving the incoming data from the trackers? It would be great if you could help me with any quick steps that will help me in achieving this. My experience with java is too little. Any help from your side will be of great help.

Thanks once again,
M&M

**Comment by tananaev** [comment]
Yes, it's very easy. You don't even need to change the code.

What you need to do following change in the config file:
1. Disable web interface (set `http.enable` to `false`)
2. Disable protocols that you don't need (set `<protocol>.enable` to `false`)
3. Configure database connection parameters and `database.selectDevice` and `database.insertPosition` queries

**Comment by m-menon** [comment]
hi Anton,

Wow, that's really cool :-) But just curious about one thing - if the numbers of vehicles / trackers grow, will I need to run multiple instances of the listener? Are you aware of any (optimal / max)numbers that a single listener may be able to handle? 

I need to anticipate the future scaling at some point because I am thinking of making something available to the general public where they can simply add trackers and view it online. As it will be a free service I think many will use it for tracking.

Thanks once again for your time. I really appreciate it.

Cheers,
M&M

**Comment by tananaev** [comment]
I know some people use it with 10k+ devices, so I don't think number of devices would be an issue. There are no limits in the application, so it all depends on your hardware.

**Comment by m-menon** [comment]
hi Anton,

That's cool. Thanks a lot for your help

Cheers,
M&M

**Comment by m-menon** [comment]
hi,

In one of your above replies you said "3. Configure database connection parameters and **database.selectDevice** and **database.insertPosition** queries"

Can I know what exactly that means?

Thanks,
M&M

**Comment by tananaev** [comment]
Have you looked at the config file? You need to adjust mentioned parameters to work with your database.

**Comment by m-menon** [comment]
hi,

yes I did. I got a little confused cos you mentioned only 2 queries. And I am java and mongodb is still new territory to me :-) I saw that some JDBC MongoDB driver can completely tranform SQL to MongoDB type queries. I should be trying one of those today. Thanks a ton for the help and the great work. Shall donate as soon as the project is over :-)

**Comment by m-menon** [comment]
I have signed up for a free sandbox mongodb at mongolabs so that I can test it with MongoDB.

It specifies 2 ways to connect to the DB:

```
To connect using the mongo shell:
 mongo ds023483.mlab.com:23483/gpsdata -u <dbuser> -p <dbpassword>

To connect using a driver via the standard MongoDB URI (what's this?):
 mongodb://<dbuser>:<dbpassword>@ds023483.mlab.com:23483/gpsdata
```

I believe I have to use the 2nd option. Now that brings me to be how should i be passing the other parameters...the username/password etc. Do I still need those other entry keys database.user, database.password etc?

I have tried a few different combinations but traccar fails to start when I switch to mongolabs MongoDB. It works perfectly fine with MySQL that I set up. Thanks a ton

**Comment by tananaev** [comment]
MongoDB is a NoSQL database, so I'm not sure if it's compatible with Traccar. It has a JDBC driver, so it might work, but I've never tried.

**Comment by m-menon** [comment]
oh the UnityJDBC driver says

> The JDBC driver for MongoDB runs SQL queries against MongoDB for any Java application that supports JDBC. SQL support includes functions, expressions, aggregation, and joins including for collections with nested objects and arrays

So I think it should work except that I can't seem to get the connection right

**Comment by tananaev** [comment]
Maybe this would help:

http://stackoverflow.com/a/27598312/2548565

**Comment by m-menon** [comment]
Thanks for the link. Was looking at the logs...and here's what I see

### 

> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: java.lang.ClassNotFoundException: mongodb.jdbc.MongoDriver
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at java.lang.Class.forName0(Native Method)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at java.lang.Class.forName(Class.java:264)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.initDatabase(DataManager.java:94)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at org.traccar.database.DataManager.<init>(DataManager.java:64)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:121)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:498)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
> INFO   | jvm 1    | 2016/03/06 05:50:55 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
> STATUS | wrapper  | 2016/03/06 05:50:57 | <-- Wrapper Stopped

The UnityJDBC installation itself went very smoothly. I hope it is not some path variable or something

**Comment by tananaev** [comment]
You need to add path to the config file:
```
<entry key='database.driverFile'>...</entry>
```

**Comment by m-menon** [comment]
Ok thanks Anton. Lemme fiddle with it for a while. If this can work on MongoDB it could be helpful to others too. Shall post if I succeed :-) Thanks once again for the pointers :+1:
