### ISSUE TITLE
can not get address field from tk-06 device.

### ISSUE THREAD

**Issue by behibehzad** [tananaev/traccar#1198]
Hi,why can't get address field from my tk-06 device?,show to me null value in address field.

**Comment by tananaev** [comment]
If you want to get address info you need to enable reverse geocoder. See <a href="https://www.traccar.org/configuration-file/">config documentation</a> for more details.

**Comment by behibehzad** [comment]
i change the my config file to the this:

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'>http://nominatim.openstreetmap.org/reverse</entry>
but no show to me address!

**Comment by tananaev** [comment]
Please do not use OSM hosted Nominatim server (see http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy).
