### ISSUE TITLE
Delete position table every 24 hourse?

### ISSUE THREAD

**Issue by behibehzad** [tananaev/traccar#1199]
are the delete position table every 24 hourse?thanks anton

**Comment by tananaev** [comment]
You can use MySQL database and then have a system task to clear positions every 24 hours.

**Comment by behibehzad** [comment]
my friend ,in my sql server database i think clear my position table data every 24 hourse,thats true?

**Comment by tananaev** [comment]
Traccar does not clear any data from database.

**Comment by wahisoufiane** [comment]
Don't you think that a system task to clear positions, won't be blocked by a 'locked_table' when the table 'position' is used by traccar?

**Comment by tananaev** [comment]
Most database engines are designed to handle multiple simultaneous connections, so locks shouldn't be a problem.

**Comment by TecSeguridad** [comment]
Sorry I have been trying several ways listed here to clean up the database and I have not managed to get it, it all gives me a syntax error or similar.
Anton could you help me with the right command to clean up pisces and events at the base? For version 3.10 Thanks in advance.

**Comment by tananaev** [comment]
If you get an error, you should probably tell us the error.
