### ISSUE TITLE
GPS 103 check if its online 

### ISSUE THREAD

**Issue by venusdharan** [tananaev/traccar#1200]
Hello first let me thank you for this powerful software, this helped me a lot , Im running traccar as back-end and my custom web ui for display. anyway my question is ist possible check weather the device is online or not, i think it can be found from others but, im not sure which field value to be read to determine that. please help.

**Comment by tananaev** [comment]
Currently it is not possible, but I am working on new API which will include such functionality.

**Comment by tananaev** [comment]
Traccar already offers connection status through API and web app.
