### ISSUE TITLE
Project Error

### ISSUE THREAD

**Issue by robertoalmeida** [tananaev/traccar#1201]
Downloaded now the project and compile the following error appears:

Running org.traccar.model.MiscFormatterTest
Tests run: 1, Failures: 1 Errors: 0, Skipped: 0, Time elapsed: 0.021 sec <<< FAILURE!

Tests run: 1, Failures: 1 Errors: 0, Skipped: 0, Time elapsed: 0.021 sec <<< FAILURE!
testToString (org.traccar.model.MiscFormatterTest) Time elapsed: 00:02 sec <<< FAILURE!
org.junit.ComparisonFailure: expected: <... <a> 3 </a> <b> 2 </ b> <c> 3 [,] 56 </ c> </ info >> but was: <. .. <a> 3 </a> <b> 2 </ b> <c> 3 [.] 56 </ c> </ info >>
at org.junit.Assert.assertEquals (Assert.java:115)
at org.junit.Assert.assertEquals (Assert.java:144)
at org.traccar.model.MiscFormatterTest.testToString (MiscFormatterTest.java:17)
............

What's the problem?

**Comment by tananaev** [comment]
The problem was that decimal format can be different in different locales. I have removed this case from tests and everything should work now.

**Comment by robertoalmeida** [comment]
Thanks.
