### ISSUE TITLE
OBD T361

### ISSUE THREAD

**Issue by farbeed** [tananaev/traccar#1203]
Hi,

Im using T361 OBD device, the device should send car info, but when the traccar decode the messages , I see the positions only, there is no important data in the Other Filed, the data look like this
<info><protocol>ulbotech</protocol><hdop>343</hdop></info>

Alos I received 471 positions in one minute, while the configuration it should send One position per minute.

**Comment by farbeed** [comment]
Hi,

also I get this in the log file.

WARN: Readable byte limit exceeded: 1 - java.lang.IndexOutOfBoundsException (AbstractChannelBuffer.java:236)
2015-05-11 13:01:24  INFO: Closing connection by exception

**Comment by tananaev** [comment]
Please provide HEX data from logs.

**Comment by farbeed** [comment]
here it is

HEX: f8010108653280262660481cdacf830209ffffffffffffffff780304000300000404000000030506017418a021f99697f8f801010865328026266048fffeae800209ffffffffffffffff7803040000000004040000000005060174178b21747e31f8f801010865328026266048fffeae800209ffffffffffffffff7803040200000004040000000005060375175421f3060800000000000000009c28f8f801010865328026266048fffeae800209ffffffffffffffff780304020200000404000000000506036a175c21f20608000000000000000074aff8f8010108653280262660481ce26065020901a000030a8c368b780304020200000404000000000506036e179421fb06080000000000000000dc38f8f8010108653280262660481ce260a3020901a000030a8c368b450304020200000404000000000506036f17cf21ff06080000000000000000b9ecf8f8010108653280262660489ce260b4010e01e757bd022340d7002b010d01570304020200000404000000260506036a17d42200060800000000000000000a0101ab9ff8f8010108653280262660489ce260b5010e01e757b10223406e0029010801570304020200000404000000330506036917d82200060800000000000000000a0108205af8f8010108653280262660489ce260df010e01e756f30223384a0003010a02a80304020200000404000001280506036217fe22010608000000000000000005aaf8f8010108653280262660489ce260f6010e01e75899022338c2001b015c00640304020200000404000001800506036b18072201060800000000000000000a0140aaebf8f8010108653280262660489ce260f700010e01e758db022338b2001a015c00820304020200000404000001880506036c180b2201060800000000000000000a01401f45f8f8010108653280262660489ce2611b010e01e768be02233875002300140073030402020000040400000369050603611818220106080000000000000000cbdcf8f8010108653280262660489ce26123010e01e769ee022337630019010200730304020200000404000003a605060370181c2201060800000000000000000a01045a03f8f8010108653280262660489ce26124010e01e769dd0223371f001900fb00730304020200000404000003ae0506036e181c2201060800000000000000000a0104073bf8f8010108653280262660489ce26127010e01e769b4022336670014010000730304020200000404000003c30506036e181c2201060800000000000000000a01440891f8f8010108653280262660489ce26128010e01e769ac022336290014010300730304020200000404000003c905060371181c2201060800000000000000000a0140e471f8f8010108653280262660489ce26143010e01e7687f02232b00

**Comment by farbeed** [comment]
I also found this warning

WARN: java.lang.NullPointerException (ReverseGeocoderHandler.java:45)

**Comment by tananaev** [comment]
Are you using the latest version of Traccar? I have tried HEX messages and it's decoded correctly. If you are using the latest release and it's still happening, I need full log file to investigate the problem deeper.

**Comment by farbeed** [comment]
Hi Anton.

Im using the last version of traccar 2.12. attached is the log.

Note that I use traccar as a service to decode messages only.  it worked
fine for many devices such as TK104 ,fm1200,ECO4,TCO3

For Traccar web application there is error called r remote procedure call
error, see the attached.

Thanks

**Comment by tananaev** [comment]
You cannot attach files to GitHub emails. If you want you can send it to me directly (email address in profile).
