### ISSUE TITLE
iPhone application

### ISSUE THREAD

**Issue by wolfbgn** [tananaev/traccar#1204]
I have installed Traccar client for iOS on iPhone 5 - v8.3. It connects with the server, I can see it, reports positions correcrly every 60s. Every thing looks good.
But: Traccar client is being switched off by unknown ( to me ) reason. This happens when the phone has been switched off - Traccar client does not switches on automaticly with the phone.
Also Traccar client switches off by itself after several hours without network coverage.
Can this be fixed, because I use for my children.

**Comment by tananaev** [comment]
Are you sure that phone settings allow Traccar Client to work in background? If yes, then I guess nothing else can be done. Apple is very strict on what apps can do in the background and it can kill the app in various cases.

**Comment by wolfbgn** [comment]
Settings are OK, I think. 
Traccar client stays ON but does not send data to server, the log on phone is empty Server shows offline status.

**Comment by tananaev** [comment]
The only option I can think of is to get console logs from iPhone and see what's happening.

Try following application (I haven't tried it because I don't have an iPhone at the moment):
http://lemonjar.com/iosconsole/
