### ISSUE TITLE
geocoder problem !!

### ISSUE THREAD

**Issue by juanma2413** [tananaev/traccar#1207]
Anton, I enable the geolocation

<pre>    &lt;entry key='geocoder.enable'&gt;true&lt;/entry&gt;
    &lt;entry key='geocoder.type'&gt;nominatim&lt;/entry&gt;
    &lt;entry key='geocoder.url'&gt;http://nominatim.openstreetmap.org/reverse&lt;/entry&gt;</pre>

This worked about 7 hours and stopped working.

There may be some overload problem?
You can correct this somehow?

You can orient the matter

Thank you so much,

JM

**Comment by juanma2413** [comment]
I see you enter new rows in the table position . They are random and are spaced 10 to 25 minutes between them.
1) It can happen that the insert is very fast and the location is not resolved ?
2) It may be that there is a restriction by the server?

Your comment will be very useful to solve my problem ,

Thanks and best regards from Argentina

**Comment by tananaev** [comment]
I think this should answer your question:
http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy

Basically, if you want to use Nominatim, you need to host your own instance.

Alternatively you can try to use Google API, but it has it's own limitations as well.

**Comment by juanma2413** [comment]
Anton ,
Can you tell me if you had any experiance or comment hosting a nominatin.openstrettmap .
I really appreciate your help

**Comment by tananaev** [comment]
I don't know if there are any providers, but you can try to install your own instance following instructions from here:
http://wiki.openstreetmap.org/wiki/Nominatim/Installation
