### ISSUE TITLE
Supporting this software

### ISSUE THREAD

**Issue by behibehzad** [tananaev/traccar#1211]
The program will support up to Kay? task after the server support from this program what is it?thanks

**Comment by tananaev** [comment]
What is Kay? I don't quite understand the question.

**Comment by behibehzad** [comment]
So when the software will be supported?

**Comment by behibehzad** [comment]
When you close your site, what happens to the server we will?

**Comment by tananaev** [comment]
What software are you talking about? What do you mean what happens to the server?

**Comment by behibehzad** [comment]
traccar server software,it mean when your support or site is down,in my server have a customer GPS data,what happen on my server?

**Comment by tananaev** [comment]
Traccar is a fully self-hosted solution. All data is store on your own server and there is no communication with any of my servers.

**Comment by behibehzad** [comment]
thanks my friend to help my problems.Excuese me for ask this question.
