### ISSUE TITLE
Data insert in to multiple tables

### ISSUE THREAD

**Issue by seshutpt** [tananaev/traccar#1213]
Dear Tananaev
Thank you for your support.
In my application i am storing each device data in to individual tables  with the  table names of Imei number.
I want to modify the given insert statement, data should be stored device corresponding table. 
Can you please help me how to change the insert statemet( Insted of table Positions  )
```xml
<entry key='database.insertPosition'>
        INSERT INTO positions (device_id, time, valid, latitude, longitude, altitude, speed, course, power, address, other)
        VALUES (:device_id, :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :power, :address, :extended_info);
    </entry>
```
thanks in advance

**Comment by tananaev** [comment]
If you are using MySQL database, you can use dynamic query to insert data into different tables. Something like this:
<pre>set @sql = concat('insert into gs_tracker_data_', :device_id, ' (dt_server, dt_tracker, lat, lng, altitude, angle, speed, params) values (?, ?, ?, ?, ?, ?, ?, &quot;&quot;)');
prepare stmt from @sql;
set @time = :time; set @lat = :latitude; set @lon = :longitude; set @alt = :altitude; set @course = :course; set @speed = :speed;
execute stmt using @time, @time, @lat, @lon, @alt, @course, @speed;
deallocate prepare stmt;</pre>

**Comment by seshutpt** [comment]
Haii

I am using MS Sql server. How can i do this. i created each device has a different table with imei name.
Instead of Positions table  i need to insert the data in to corresponding tables.
please help me

**Comment by tananaev** [comment]
MS SQL Server has dynamic queries as well:

https://msdn.microsoft.com/en-nz/library/ms188001.aspx

**Comment by seshutpt** [comment]
Haii ,

please check the below procedure to insert data in to  different tables. I am unable to use this procedure in datamanager class. Please help me how to use this procedure and insert data in to multiple tables.

ALTER procedure [dbo].[imeinumber]
@DeviceId int,
@DateTime time,
@Valid bit,
@Latitude float,
@Longitude float,
@Altitude float,
@Speed float,
@Course float,
@imei nvarchar(50),
@strsql nvarchar(1000)

as  
begin
set @strsql='insert into '''+@imei+'''(device_id, imei, time, valid, latitude, longitude, altitude, speed, course)values(@DeviceId,@imei,@DateTime,@Valid,@Latitude,@Longitude,@Altitude,@Speed,@Course)'
exec @strsql

 
In databamanager class  you are passing the query as string and assigning the variables to that query. If i use this procedure how can do that. Please help me.

**Comment by tananaev** [comment]
You need to pass all those parameters as arguments to the stored procedure. How are you trying to use it?

**Comment by seshutpt** [comment]
I called like this. 
 PreparedStatement stmt=dataSource.getConnection().prepareStatement("{call imeinumber (?,?,?,?,?,?,?,?,?,?,?,?)}");
       stmt.setLong(1, device_id);
       stmt.setString(2, imei);
       stmt.setDate(3, (java.sql.Date) time);
       stmt.setBoolean(4, valid);
      stmt.setDouble(5, latitude);
       stmt.setDouble(6, longitude);
       stmt.setDouble(7, speed);
      stmt.setDouble(8, course);
       ResultSet rs = stmt.executeQuery();

**Comment by tananaev** [comment]
I think you don't need those curly braces. So, what is the error message you get?

**Comment by seshutpt** [comment]
I will send you the both functions now
query="INSERT INTO :imei (device_id,imei,time,valid,latitude,longitude,altitude,speed,course,power,strLatitude,strLongitude ) VALUES (:device_id,:imei,:time,:valid,:latitude,:longitude,:altitude,:speed,:course,:power,:strLatitude,:strLongitude)";

 if (query != null) {
            queryAddPosition = new NamedParameterStatement(query, dataSource, Statement.RETURN_GENERATED_KEYS);
        }

how can i pass the stored procedure to queryAddPosition as query.

**Comment by tananaev** [comment]
Why are you changing the code? You only need to change a query in the config file.

It should look something like this:
<pre>EXEC dbo.imeinumber @DeviceId = :device_id, @DateTime = :time, ...</pre>

**Comment by seshutpt** [comment]
Hai 
I am getting the following error when i use the above query.

Query: EXEC dbo.imeino(@imei=:imei,@deviceid=:device_id,@time=:time,@latitude=:latitude,@longitude=:longitude,@altitude=:altitude,@speed=:speed,@course=:course,@power=:power);

Error: in log file
78781f120f051d0d352bc601de620f08698fe90034190194310015009d09002a90e00d0a
2015-05-29 13:53:41 DEBUG: [5023 -> 106.220.226.127] - HEX: 78780512002a2cfc0d0a
2015-05-29 13:53:41  INFO: device: 1, time: Fri May 29 13:53:43 IST 2015, lat: 17.417395, lon: 78.408805
2015-05-29 13:53:41  WARN: Incorrect syntax near '@imei'. - com.microsoft.sqlserver.jdbc.SQLServerException (SQLServerException.java:216)

**Comment by tananaev** [comment]
Why did you put parenthesis there? Also, there is no `:imei` parameter.

**Comment by seshutpt** [comment]
thank you for your support
actually we created the table name as based on imei number, thats why i am giving one more parameter is imei, this parameter i added in  position and every where. You can see my strored procedure  in my 3rd reply.

Now i am getting this error:
2015-05-29 18:26:30  INFO: device: 1, time: Fri May 29 18:26:32 IST 2015, lat: 17.417221666666666, lon: 78.4086711111111
2015-05-29 18:26:30  WARN: A result set was generated for update. - com.microsoft.sqlserver.jdbc.SQLServerException (SQLServerException.java:190)

Query is:
EXEC dbo.imeino @imei=:imei,@DeviceId=:device_id,@DateTime=:time,@Valid=:valid,@Latitude=:latitude,@Longitude=:longitude,@Altitude=:altitude,@Speed=:speed,@Course=:course,@power=:power;

**Comment by seshutpt** [comment]
Thank you very much, data inserting

Thank you
