### ISSUE TITLE
Connect to multiple databases

### ISSUE THREAD

**Issue by Starsiss** [tananaev/traccar#1215]
Hello,
I am trying to show markers for another kind of devices that i have stored in another database, but i get a 500 traccar/dataService error when trying to recover the data from that database. is there a way to create multiple entries in the conf file to connect to different databases? or I can connect to those DB whenever the user and password supplied in the conf file are correct for that other DB?( althoug the url db name does not match)

thanks,

**Comment by tananaev** [comment]
No, current version of Traccar does not support working with multiple databases.

**Comment by Starsiss** [comment]
I know that SQL server can make selects from another database if it is explicity defined in the FROM clause DB_NAME.dbo.TABLE_NAME and if the user and pwd provided have rights over that DB. I suppose there is nothing more to do than copy the table to traccar db.

thanks,

**Comment by tananaev** [comment]
If it's the same instance of the database engine, then yes, you can probably specify database directly in the SQL statement.

Another option is to set up database replication.

**Comment by Starsiss** [comment]
In the end, I copied the table to the Traccar Database, and worked from there, but what i tought it was a problem od FB connectivity is turning out a little more complex. I set my Class as entity, and I have declared it in the DataService class, interface and Impl. just as any other class, like devices or positions, but every time i get the 500 server error when trying to access to the data through Application.getDataService().METHOD_IMPLEMENTED()

This is the method in DataServiceImpl:
@Transactional    
@Override
    public List<Ascensor> getTodosAscensores()
    {
        EntityManager entitymanager = getSessionEntityManager();        
        List<Ascensor> ascensores = new LinkedList<Ascensor>();     
             String queryString = "SELECT a FROM Ascensor a";    
        TypedQuery<Ascensor> query = entitymanager.createQuery(queryString,Ascensor.class); ascensores = query.setMaxResults(100).getResultList();
             return ascensores;
    }

And my class Ascensor like this
@Entity
@Table(name = "Ascensor", indexes = { @Index(name = "PK_Ascensor", columnList = "Empresa,Codigo") })       

public class Ascensor implements Serializable {    
    private static final long serialVersionUID = 1;
// <editor-fold desc="ATTRIBUTES">
    @Id
    @Column(name = "Codigo", nullable = false, updatable = false, unique = true)
    private String Codigo;

I am totally at loss as I have revised all the code, but unable to find any discordances with other entities.

**Comment by tananaev** [comment]
What is the actual error/exception on the server side?

**Comment by Starsiss** [comment]
after much trying to setup correctly the debug for the project I was able to access to a more detailed infor of the error. this is what I get:

Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getAscensores()' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute query

Anyway, I can seem to get to the full Stacktrace of the error.

**Comment by tananaev** [comment]
Looks like there is something wrong with query. Take a look at the real SQL query by adding following parameter to persistence config:

<pre>&lt;property name=&quot;show_sql&quot;&gt;true&lt;/property&gt;</pre>

**Comment by Starsiss** [comment]
I was able to find the error. it seems like one of the parameters for a column was of a primitive type and was getting a null from the database, and so, the query failed. I changed the type to a wrapper type and all worked fine.

thanks for your help!
