### ISSUE TITLE
Диспетчер

### ISSUE THREAD

**Issue by borozenetsvv** [tananaev/traccar#1216]
Хотелось бы специального пользователя, который видел бы весь транспорт на карте, но не мог редактировать. Что-то вроде диспетчера.

**Comment by tananaev** [comment]
Со временем планируется реализовать права доступа для пользователей, но думаю что это случится не очень скоро.

**Comment by vitalidze** [comment]
В [моей модификации](http://traccar.litvak.su) есть возможность назначить пользователю права [только на чтение](http://traccar.litvak.su/features/read-only-users.html), что подходит под термин "Диспетчер".

**Comment by borozenetsvv** [comment]
К сожалению, мой трекер не поддерживается. Отсюда теряется весь смысл задумки. Жаль...

**Comment by tananaev** [comment]
Различные права доступа уже поддерживаются в официальной версии.
