### ISSUE TITLE
What is the Course field in database?and is the speed per mile or kilometer?

### ISSUE THREAD

**Issue by behibehzad** [tananaev/traccar#1220]
What is the Course field in database?and is the speed per mile or kilometer?

**Comment by vitalidze** [comment]
Course represents direction of vehicle/tracker, i.e. angle where it is moving right now. Speed is in knots (additional info here http://en.wikipedia.org/wiki/Knot_(unit)).

**Comment by behibehzad** [comment]
How can i change speed unit to KM/H?

**Comment by vitalidze** [comment]
In web UI you can change how to display it in 'Settings' >> 'Preferences' menu. You cannot change the way traccar stores it in database.

**Comment by tananaev** [comment]
Official web app also supports various speed units.
