### ISSUE TITLE
Dependencies for Traccar server

### ISSUE THREAD

**Issue by mpele** [tananaev/traccar#1226]
Hi, 
Thank you for your magnificent work !!! 
Could you shortly explain why are wine in the list of dependencies for Linux:
- wine
- innoextract
- makeself

I am preparing to build traccar server locally but I do not understand what for are mentioned dependencies.

**Comment by tananaev** [comment]
Those are dependencies to create installers. To create installer for Windows I use Inno Setup, so I need innoextract and wine to build it. For Linux I use makeself to create self-extracting archive.

To build server itself you don't need either of those.

**Comment by mpele** [comment]
Thank you for clarification.
