### ISSUE TITLE
I updated config file but when i visit it again it shows me old entry. Why?

### ISSUE THREAD

**Issue by surendrakumar1992** [tananaev/traccar#1230]
Hello,
I am new with traccar. I updated config file according my requirement but when i visit it again. It show me old entry. Where is my updated file?

**Comment by tananaev** [comment]
Can you be more specific. What did you update? Have you restarted the service after changing config?

**Comment by surendrakumar1992** [comment]
Thanks for the quick reply.
I updated config file for mysql like database name, password. I turn off other protocol port which i not used. then i restart the traccar but it show me old entry which i alredy updated.
Note that it works fine. but i confused when i visit it again becuase no change reflect in file.

**Comment by tananaev** [comment]
Well, there must be something in the database if everything else works correctly.

**Comment by surendrakumar1992** [comment]
Hey man, thanks for the fast  response.
First time i updated config file, only minor change for mysql and it's works fine.
Now i want to turn on gecoder for the address but config file look like default not my changes be there .
Thanks

**Comment by tananaev** [comment]
Traccar doesn't write anything to the config file, so there must be some other explanation.

**Comment by surendrakumar1992** [comment]
Thanks,
Now i turn off the gecoder settings and it's works charm on ui but config file still show geocoder false.

**Comment by tananaev** [comment]
I suspect you are doing something wrong or looking in the wrong place because geocoder won't work if it's disabled in the config file.
