### ISSUE TITLE
In which case traccar store the data in database?

### ISSUE THREAD

**Issue by surendrakumar1992** [tananaev/traccar#1232]
Hello,
This is new query.
I found last entry of my device is 30-05-2015 in database. But on ui it show latest position with address.
It display address on ui but not store in database why?
Thanks

**Comment by tananaev** [comment]
Web interface takes data only from database, so you must be looking in the wrong place.

**Comment by surendrakumar1992** [comment]
Hello,
Thanks for response.
@tananaev  i really get this issue. On web ui i getting address but when i fetched data againest latesPositionId of devices it give address as null.
Any idea why this happened in my case only?

**Comment by tananaev** [comment]
Can I see a screenshot and what you see in the database?

**Comment by surendrakumar1992** [comment]
![traccor1](https://cloud.githubusercontent.com/assets/12594740/7934890/5e5da8c6-0949-11e5-9d10-93dbc670a155.png)
![traccor2](https://cloud.githubusercontent.com/assets/12594740/7934893/623a9364-0949-11e5-821b-3f2807b3501e.png)

**Comment by surendrakumar1992** [comment]
Thanks for response..
hope this image helpful.
One more thing
From last two days I use select query on 'Position' table and it's gives 900 all time. I not able to see new entry in database.

**Comment by surendrakumar1992** [comment]
Hey @tananaev .. Got the issue.
My database reset mysql to default. 
Is config file reset when we restart the traccar?

**Comment by tananaev** [comment]
Traccar doesn't (re-)write the config file, so there must be some other explanation.

**Comment by surendrakumar1992** [comment]
Thanks man..  @tananaev
