### ISSUE TITLE
New in Traccar a Simple Consult

### ISSUE THREAD

**Issue by cgarbero** [tananaev/traccar#1259]
![1](https://cloud.githubusercontent.com/assets/12959087/8245048/3e5a73f2-15ff-11e5-9a49-c7b8f1d292e7.jpg)
hi, i am new using traccar and i am testing this wonderfull soft with my cellphone cause i dont have a gps. I download the app client traccar in my cellphone a make the connection and start to track but the answers are
1- is there any way that if the cell is inactive or the speed is equal to 0 don mark on the map?
2. Why the position on the map is incorrect (if you see it marks two diferrents ways), there will be some problem with the GPS on my phone?

thanks a lot and sorry for my english. I am from Argentina. 

Hugs.

**Comment by tananaev** [comment]
1. No, currently there is no way.

2. What location provider did you use on the phone?

**Comment by cgarbero** [comment]
the provider name is claro from argentina

**Comment by tananaev** [comment]
No, I mean are you using GPS or network location provider? Are you using iPhone or Android app?

**Comment by cgarbero** [comment]
ohhh, it is android the app is client traccar, i am using gps, i connect the cell with 3g and i am using the GPS on.

**Comment by tananaev** [comment]
What location provider is selected in the app?
