### ISSUE TITLE
PT502 fuel indicators

### ISSUE THREAD

**Issue by and12345** [tananaev/traccar#1263]
Hi Anton, 

Some question, is the PT502 fuel meter supported as the device have fuel/oil indicators.

**Comment by tananaev** [comment]
Current implementation of PT502 protocol supports only basic GPS info. If you want full support, I need protocol specifications.

**Comment by and12345** [comment]
Hi Anton, i'm still new to GPS Protocol. Is this what you mean ?

Hex :
24504f532c31313032333435362c3033333733312e3030302c412c303333352e323631372c4e2c30393834312e313538372c452c302e30302c38382e31322c3231303631352c2c2c412f303030302c302f3166382f3338383930302f2f6633332f2f0d0a

Decode : 
$POS,11023456,033731.000,A,0335.2617,N,09841.1587,E,0.00,88.12,210615,,,A/0000,0/1f8/388900//f33//

GPRS Position Data format:
$[cmd],[id],[hhmmss.mss],[fix_flag],[Latitude],[N/S],[Longitude],[E/W],[Speed],[Orientation],[ddMMyy],,,[fix_data]/[input],[output]/[ad]/[Odometer]/[driver_id]/gsb/[spec_ver,spec_data]/\r\n

This is from Bofan documentation page 3 & 4 https://www.dropbox.com/s/vyw1z65lcmrn0xb/Protocol%20and%20command%20list(V1.2).pdf?dl=0

**Comment by tananaev** [comment]
I have added support for additional info. Let me know if you want me to provide a new build for you to try.
