### ISSUE TITLE
GPS Lantrix Protocol TAIP

### ISSUE THREAD

**Issue by cgarbero** [tananaev/traccar#1265]
Hello i am testing a GPS Lantrix T1800 this GPS use protocol TAIP, i configure the IP in the soft of the GPS (i dont have static ip so i use no-ip ddns) with the port of the protocol (5057) i open in my router the ports 8082 (for traccar) and i open the port 5057 for the protocol of the GPS and i do a portforward to my computer i can se in the tracker server log this: 

2015-06-22 22:49:46 DEBUG: [E72E5DB0: 5057 <- 201.251.179.211] - HEX: 3e5247503233303631353031303234382d323638323532332d30363532333638323030303030303330303746343130313b49443d303030353b23303030323b2a32413c0d0a

but in the map i dont see anything. i give the ID of the GPS 0005 and in traccar too but i can see anything 

what could happend? Programation of the GPS ? 

thanks

**Comment by tananaev** [comment]
It looks like an extension to standard TAIP protocol. The problem is that date/time format is different from original TAIP. Do you have protocol specifications for your device?

**Comment by cgarbero** [comment]
no where i can find ?

**Comment by cgarbero** [comment]
i found this but this is for opengts

http://www.movve.net/site/OpenGTS_2.4.7/src/org/opengts/servers/lantrix/TrackClientPacketHandler.java

**Comment by cgarbero** [comment]
why do you say that is a problem of date/time ?

**Comment by cgarbero** [comment]
yes it is true in the soft i can see that the time is wrong, how can i fix that ?

**Comment by cgarbero** [comment]
![datetimewrong](https://cloud.githubusercontent.com/assets/12959087/8297985/2528ac90-1939-11e5-925f-437cac3b7f7e.jpg)
if you see the date and the time (1st and 2nd field are wrong) how can i fix this, i have to go out with the gps so it can take positition and date and hour ?

**Comment by cgarbero** [comment]
can u explain to me what does it mean this string ? 

2015-06-22 22:49:46 DEBUG: [E72E5DB0: 5057 <- 201.251.179.211] - HEX: 3e5247503233303631353031303234382d323638323532332d30363532333638323030303030303330303746343130313b49443d303030353b23303030323b2a32413c0d0a

**Comment by tananaev** [comment]
If you convert it to text you will get (date and time is in bold):
<pre>&gt;RGP<b>230615010248</b>-2682523-065236820000003007F4101;ID=0005;#0002;*2A&lt;</pre>

According to TAIP protocol documentation that I have the date/time format should be:
`BBBBCCDDDDD` where
`BBBB` - GPS Week
`CC` - Day of Week
`DDDDD` - GPS Time of Day

But your device sends in different format. Looks like it sends:
`DDMMYYHHMMSS` where
`DD` - Day
`MM` - Month
`YY` - Year
`HH` - Hours
`MM` - Minutes
`SS` - Seconds

If you can confirm that, I can try to support both formats on the server side. The question is how to distinguish between two.

**Comment by cgarbero** [comment]
![wireshark](https://cloud.githubusercontent.com/assets/12959087/8299024/4b4ef5f0-1948-11e5-85ac-c54db64fe997.jpg)

this is what i capture with wireshark. I dont know this protocol, i will try tomorrow with a different equiptment.

thanks a lot

**Comment by cgarbero** [comment]
hi i have the protocol of comunicattion from the GPS lantrix T1800, is there a posibility that u add to the list of protocol ? how can i pass the document?

**Comment by cgarbero** [comment]
1.1 Reporte de Posición
El equipo descargará los eventos con el siguiente formato:
>RGP190805211932-3457215-058493640000000FFBF0300;ID=8251;#2122;*54< CR LF
Donde:
> Encabezado de todos los paquetes
RGP Nombre de la sentencia
190805 Día (DDMMAA)
211932 Hora GMT (HHMMSS)
-3457215 Latitud (Formato DD.DDDDD)
-05849364 Longitud (Formato DDD.DDDDD)
000 Velocidad en KPH (0 ..999).
000 Dirección (0 ..359)
0 3 = Posición 3D, 2 = Posición 2D ;0= No válida
FF Edad del dato en Hexadecimal
BF Estado de las entradas digitales. Ver Nota 3
0x80 Ignición.
0x40 Materia Principal.
0x20 Batería Interna
0x10 Entrada Digital 4
0x08 Entrada Digital 3.
0x04 Entrada Digital 2.
0x02 Entrada Digital 1.
0x01 Entrada Digital 0.
03 Número de Evento que generó el reporte (decimal).
00 Precisión Horizontal HDOP (0..50)
; Separador
ID=8251 Número de ID del equipo
; Separador
#2122 Número de la sentencia (las generadas por el móvil van
desde #0000 a #7FFF y las generadas por la Base van de
#8000 a #FFFF)
; Separador
*54 Checksum. Se calcula haciendo OR exclusivo Desde el >
(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
4
A cada paquete recibido la base le deberá contestar:
>ACK;ID=8251;#2122;*26<CR LF
Donde:
> Encabezado de todos los paquetes
ACK Aviso de Comando recibido
; Separador
ID=8251 Número de ID del equipo
; Separador
#2122 Número de la sentencia (el mismo Número usado en
el RGP)
; Separador
*26 Checksum. Se calcula haciendo OR exclusivo Desde
el >(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
1.2 Solicitud de Posición
Cuando la Base desee obtener la Posición del móvil lo deberá interrogar con el
siguiente Comando:
>QPF;ID=8251;#8000;*29<CR LF
Donde:
> Encabezado de todos los paquetes
QPF Pedido de Posición
; Separador
ID=8251 Número de ID del equipo
; Separador
#8000 Número de la sentencia (el equipo deberá contestar
con este mismo Número)
; Separador
*29 Checksum. Se calcula haciendo OR exclusivo Desde
el >(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
Respuesta:
>RPF050505122440-3460494-058625150000003FF7E0001;ID=8251;#8000;*21< CR LF
Donde:
> Encabezado de todos los paquetes
RPF respuesta a un QPF
050505 Día (DDMMAA)
122440 Hora GMT (HHMMSS)
-3460494 Latitud
-05862515 Longitud
5
000 Velocidad en KPH (0 ..999).
000 Dirección (0 ..359)
3 3 = Posición 3D, 2 = Posición 2D ;0= No válida
FF Edad del dato en Hexadecimal
7E Estado de las entradas digitales. Ver Nota 3
0x80 Ignición.
0x40 Batería Principal.
0x20 Batería Interna
0x10 Entrada Digital 4
0x08 Entrada Digital 3.
0x04 Entrada Digital 2.
0x02 Entrada Digital 1.
0x01 Entrada Digital 0.
00 Número de Evento que generó el reporte (decimal).
01 Precisión Horizontal HDOP (0..50)
; Separador
ID=8251 Número de ID del equipo
; Separador
#8000 Número de la sentencia (Observese que es el
mismo número usado en la interrogación)
; Separador
*21 Checksum. Se calcula haciendo OR exclusivo Desde
el >(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
1.3 Comando de Detención de Motor
Para detener el motor se enviará el siguiente Comando:
>SSG01;ID=8251;#8001;*26<CR LF
Donde:
> Encabezado de todos los paquetes
SSG01 Pedido de detención del motor
; Separador
ID=8251 Número de ID del equipo
; Separador
#8001 Número de la sentencia (el equipo deberá contestar
con este mismo Número)
; Separador
*26 Checksum. Se calcula haciendo OR exclusivo Desde
el >(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
Respuesta:
>RSG;ID=8251;#8001;*53< CR LF
6
Donde:
> Encabezado de todos los paquetes
RSG Respuesta al Comando SSG
; Separador
ID=8251 número de ID del equipo
; Separador
#8001 Número de la sentencia
; Separador
*53 Checksum. Se calcula haciendo OR exclusivo incluyendo el
signo > hasta el signo * sin incluirlo.
< Final de todos los paquetes
CR LF Fin de línea y avance de carro
1.4 Comando de arranque del Motor
Para permitir el arranque del vehículo se deberá enviar el siguiente Comando:
>SSG00;ID=8251;#8002;*26<CR LF
Donde:
> Encabezado de todos los paquetes
SSG00 Pedido de detención del motor
; Separador
ID=8251 Número de ID del equipo
; Separador
#8002 Número de la sentencia (el equipo deberá contestar
con este mismo Número)
; Separador
*26 Checksum. Se calcula haciendo OR exclusivo Desde
el >(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
Respuesta: >RSG;ID=8251;#8001;*53<
Donde:
> Encabezado de todos los paquetes
RSG Respuesta al Comando SSG
; Separador
ID=8251 número de ID del equipo
; Separador
#8001 Número de la sentencia
; Separador
*53 Checksum. Se calcula haciendo OR exclusivo
incluyendo el signo > hasta el signo * sin incluirlo.
< Final de todos los paquetes
CR LF Fin de línea y avance de carro
7
1.5 Solicitud de Histórico
Para solicitar una bajada de los eventos guardados en la memoria de históricos, se
deberá enviar al equipo el siguiente Comando:
>QDLT040505122440050505180000;ID=8251;#8003;*26<CR LF
Donde:
> Encabezado de todos los paquetes
QDLT Comando de Solicitud de Histórico
040505 Día de Inicio (ddmmaa)
122440 Hora de Inicio (hhmmss)
050505 Día final (ddmmaa)
180000 Hora final (hhmmss)
; Separador
ID=8251 Número de ID del equipo
; Separador
#8003 Número de la sentencia (el equipo deberá contestar
con este mismo Número)
; Separador
*26 Checksum. Se calcula haciendo OR exclusivo Desde
el >(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
Respuesta:
>RDL;ID=8251;#8003;*26<CR LF
Donde:
> Encabezado de todos los paquetes
RDL Respuesta al QDLT
; Separador
ID=8251 Número de ID del equipo
; Separador
#8003 Número de la sentencia (Número usado en el QDLT)
; Separador
*26 Checksum. Se calcula haciendo OR exclusivo Desde
el > inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
Al recibir este comando el T 1800 empezará a descargar todos los eventos que
correspondan a dicho período en el formato RGP. Los eventos serán descargados
en forma masiva (Alrededor de 50 por segundo).
8
1.6 Solicitud de Posición Extendida
Es posible pedir al equipo un reporte de Posición Extendida donde además de los datos
del RGP nos informará del estado de ambas baterías, la navegación, el nivel de la
señal GSM, el estado de las entradas digitales y analógicas y de las salidas.
El Comando para pedir Posición extendida es:
>QTT;ID=0003;#0000;*44< CR LF
Donde:
> Encabezado de todos los paquetes
QTT Pedido de Posición extendida
; Separador
ID=8251 Número de ID del equipo
; Separador
#8004 Número de la sentencia (el equipo deberá
contestar con este mismo Número)
; Separador
*29 Checksum. Se calcula haciendo OR exclusivo
Desde el >(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
Respuesta:
>RTT190805211932-3457215-058493640000000FFBF0300 04050610
010 00010002000312901230;ID=8251;#8004;*29<CR LF
Donde:
> Encabezado de todos los paquetes
RTT Respuesta al QTT
190805 Día (DDMMAA)
211932 Hora GMT(HHMMSS)
-3457215 Latitud
-05849364 Longitud
000 Velocidad en KPH (0 ..999).
000 Dirección (0 ..359)
0 3 = Posición 3D, 2 = Posición 2D ;0= No válida
FF Edad del dato en Hexadecimal
BF Estado de las entradas digitales. Ver nota 3
0x80 Ignición
0x40 Batería Principal.
0x20 Batería Interna
0x10 Entrada Digital 4
0x08 Entrada Digital 3.
0x04 Entrada Digital 2.
0x02 Entrada Digital 1.
0x01 Entrada Digital 0. Ver Nota 3
9
03 Número de Evento que generó el reporte (decimal).
00 Presicion Horizontal HDOP (0..50)
[espacio]
0 Status de antena (0 = Normal, 1 = Cortocircuito,
2 = Desconectado).
4 Modo de Navegación.
0 Sin navegación
1 1 solo satélite sin Posición
2 2 satélites sin Posición
3 3 satélites Posición 2D
4 4 o mas satélites Posición 3D
05 Cantidad de satélites usados (00..12).
06 Cantidad de satélites vistos (00..12).
10 Cantidad de satélites en cielo abierto (00..12).
[espacio]
0 Salida 0 (0..1).
1 Salida 1 (0..1).
0 Salida 2 (0..1).
[espacio]
0001 Conversor AD0 (0000..3000).
0002 Conversor AD1 (0000..3000).
0003 Nivel de señal GSM (0000..3000).
1290 Nivel de batería Principal (volts)(0000..3000).
1230 Nivel de batería Auxiliar (volts)(0000..3000).
; Separador
ID=8251 Número de ID del equipo
; Separador
#8004 Número de la sentencia (el equipo deberá contestar
con este mismo Número)
; Separador
*29 Checksum. Se calcula haciendo OR exclusivo Desde
el >(inclusive) hasta el * (sin incluirlo)
< Final de todos los paquetes
CR LF Fin de linea y avance de carro
Comandos de Configuración . 2
El equipo usa para su configuración un juego de Comandos para definir
Timers, Reglas, IPs, Teléfonos, APN, etc.
Para el envío de esos Comandos vía GPRS o SMS debe agregarse al
inicio del paquete los caracteres > y al final del paquete el ID, el
Número de sentencia, el checksum y el <.
2.1 Grabación de Timers Estables
Comando: STD153600
Donde:
STD Nombre del Comando
15 Número de Timer
3600 Cantidad de segundos
Respuesta: RTD Respuesta al Comando STD
2.2 Bloqueo y Habilitación de Reglas
Comando: SED43U
Donde:
SED Nombre del Comando
43 Número de Regla
U U= Bloquea; H= Habilita
Respuesta: RED Respuesta al Comando SED
2.3 Grabación de Dirección IP/Teléfono
Comando: !L0021010200.80.196.58,4097,4096 Grabación de IP 0
Donde:
!L0021 nombre del Comando
0 Número de memoria (0 a 5)
10 cantidad de reintentos de marcado (1 a 25)
200.80.196.58 dirección IP o teléfono de destino
, separador
4097 puerto de Transmisión UDP del equipo (1 a
65536)
, separador
4096 puerto de Recepción UDP del equipo (1 a
65536)
Respuesta: !K0021
12
2.4 Grabación de APN 1, Usuario y Password
Comando: !L0053internet.unifon:wap,wap
Donde:
!L0053 Nombre del Comando
internet.unifon Nombre del APN
: Separador
wap Usuario
, Separador
wap Password
Respuesta: !K0053
2.5 Grabación de APN 2, Usuario y Password
Ejemplo: !L0015internet.ctimovil.com.ar:wap,wap
Donde:
!L0015 Nombre del Comando
ctimovil.com.ar Nombre del APN
: Separador
wap Usuario
, Separador
wap Password
Respuesta: !K0015
2.6 Grabación de Exceso de Velocidad
Comando: !L0039100020030040020
Donde:
!L0039 Nombre del Comando
100 Velocidad 0 (kmh)
020 Velocidad 1 (kmh)
030 Velocidad 2 (kmh)
040 Velocidad 4 (kmh)
020 HDOP (020 a 255) Recomendado 020 a 030
(calidad mínima de la señal para tomar como
dato válido la velocidad detectada por el GPS)
Respuesta: !K0039
2.7 Grabación de Reintentos de ACK
Comando: !L003106
Donde
!L0031 Nombre del Comando
06 Cantidad de reintentos (01 a 25)
Respuesta: !K0031
2.8 Grabación de Umbrales de Contador
Comando: !L0046100200
Donde:
!L0046 Nombre del Comando
100 Valor del Contador 0 (0 a 255)
200 Valor del Contador 0 (0 a 255)
Respuesta: !K0046
2.9 Grabación de ID
Comando: !L001000031111
Donde:
!L0010 Nombre del Comando
0003 Nombre de la ID existente
1111 Nombre de la ID nueva
Respuesta: !K0010
Nota: En la respuesta el equipo contestara con su nuevo ID
2.10 Grabación de Ahorros de Energía
Comando: !L003706000180060001800600060011111
Donde:
!L0037 Nombre del Comando
0600 Tiempo de GPS Apagado (Segundos)
0180 Tiempo de GPS Encendido (Segundos)
(Este tiempo no debe ser menor a 120
segundos)
0600 Tiempo de Módem Apagado (Segundos)
0180 Tiempo de Módem Encendido (Segundos)
(Este tiempo no debe ser menor a 120
13
segundos)
1 Ahorro de GPS Habilitado
(1= Habilitado 0= Deshabilitado)
1 Ahorro de Módem Habilitado
(1= Habilitado 0= Deshabilitado)
1 Ahorro de Máximo GSM Habilitado
(1= Habilitado 0= Deshabilitado)
Respuesta: !K0037
2.11 Grabación de Marcas Horarias
Comando: !L00482160021601216022160321604
Donde:
!L0048 Nombre del Comando
21600 Cantidad de segundos/2 desde la cero hora
GMT. (12:00:00)
21601 Cantidad de segundos/2 desde la cero hora
GMT. (12:00:02)
21602 Cantidad de segundos/2 desde la cero hora
GMT. (12:00:04)
21603 Cantidad de segundos/2 desde la cero hora
GMT. (12:00:06)
21604 Cantidad de segundos/2 desde la cero hora.
GMT. (12:00:08)
Respuesta: !K0048
2.12 Grabación de Umbrales de Batería
Comando: !L0041070210
Donde:
!L0041 Nombre del Comando
070 Umbral de Tensión: Mínima (cada unidad =
0,142Volts) En el ejemplo 10Volts
210 Umbral de Tensión: Máxima (cada unidad =
0,142 Volts) En el ejemplo 30Volts
Respuesta: !K0041
2.13 Grabación de Debounce
Comando: !L0022100
Donde:
!L0022 Nombre del Comando
100 Tiempo en mSeg. (0-255)
14
Respuesta: !K0022
2.14 Grabación de Timers
Comando: !L000201100000070
Donde:
!L0002 Nombre del Comando
01 Número de Timer
1 Tipo de Timer (1=Estable 0=No Estable)
00000070 Cantidad de segundos (0-7776000)
Respuesta: !K0002
2.15 Grabación De Mensajes Predefinidos
Comando: !L0068001Hola
Donde:
!L0068 Nombre del Comando
001 Número de mensaje
Hola Texto del mensaje
Respuesta: !K0068
2.16 Grabación de Direcciones DNS
Comando: !L0075 10.10.10.10 , 10.10.1.10
Donde:
!L0075 Nombre del Comando
10.10.0.10 DNS 1
, Separador
10.10.0.11 DNS2
Respuesta: !K0075
2.17 Grabación de Umbrales de los Conversores A/D
Comando: !L007703A2060E
Donde:
!L0077 Nombre del comando
03A2 Valor en Hexadecimal para el conversor A/D 1.
060E Valor en Hexadecimal para el conversor A/D 2.
Nota: Para obtener el valor en mV, convertir el valor Hexa a decimal y dividirlo por 3,1.
Para obtener el valor en Hexadecimal hay que Multiplicar el umbral en mV por 3,1 y
luego convertir a Hexadecimal.
Respuesta: !K0077
15
2.19 Grabación de Valores de Distancia
Comando: !L0079 00100 00080 00050 00020 00
Donde:
!L0079 Nombre del comando
00100 Valor de velocidad para la posición 0
0080 Valor de velocidad para la posición 1.
0050 Valor de velocidad para la posición 2.
0020 Valor de velocidad para la posición 3.
00 Estado de los indicadores de giro.
00= ningún indicador habilitado
01= indicador 0 habilitado
02= indicador 1 habilitado
03= indicadores 0 y 1 habilitados
04= indicador 2 habilitados
05= indicadores 0 y 2 habilitados
06= indicadores 2 y 3 habilitados
08= indicador 3 habilitado
09= indicadores 0 y 3 habilitados
10= indicadores 1 y 3 habilitados
11= indicadores 0-1 y 3 habilitados
12= indicadores 2 y 3 habilitados
13= indicadores 0-2 y 3 habilitados
14= indicadores 1-2 y 3 habilitados
15= Todos los indicadores habilitados

Comandos de Interrogación . 3
3.1 Pedido de Número de Serie
Comando: !L0095
Respuesta: !00095A1234
Donde:
!00095 Respuesta al Comando !L0095
A1234 Número de serie
3.2 Pedido de Versión de Firmware
Comando: !L0099
Respuesta:
!0009909/05/14 1.0
Donde:
!00099 Respuesta al Comando !L0099
09/05/14 1.0 Nombre de la Versión
3.3 Pedido de IP/ Teléfonos
Comando: !L00510
Donde:
!L0051 Nombre del Comando
0 Número de memoria (0-5)
Respuesta: !0005110200.80.196.58,8097,8096
Donde:
!00051 Respuesta al Comando !L00510
10 Cantidad de reintentos
200.80.196.58,8097,8096 IP y puertos
3.4 Pedido de Conversores AD y señal GSM
Comando: !L0018
Respuesta: !00018000100001300147209151
Donde:
!00018 Respuesta al Comando !L0018
0001 Conversor AD0
0000 Conversor AD1
1300 Nivel de señal GSM
1472 Tensión de BAT. EXTERNA
0915 Tensión de BAT INTERNA
1 Estado de registración GSM
17
(1=registrado; 0=no registrado)
3.5 Pedido de Velocidades
Comando: !L0040
Respuesta: !00040100020030040020
Donde:
!00040 Respuesta al Comando !L0040
100 Velocidad 0 (kmh)
020 Velocidad 1 (kmh)
030 Velocidad 2 (kmh)
040 Velocidad 4 (kmh)
020 HDOP (020 a 255) Recomendado 020 a 030
(calidad mínima de la señal para tomar como
dato válido la velocidad detectada por el GPS)
3.6 Pedido de Ahorros de Energía
Comando: !L0038
Respuesta: !0003806000180060001800600060011111
Donde:
!00038 Respuesta al Comando !L0038
0600 Tiempo de GPS Apagado (Segundos)
0180 Tiempo de GPS Encendido (Segundos)
(Este tiempo no debe ser menor a 120
segundos)
0600 Tiempo de Módem Apagado(Seg.)
0180 Tiempo de Módem Encendido (Seg.)
(Este tiempo no debe ser menor a 120
segundos)
(Este tiempo no debe ser menor a 120
segundos)
1 Ahorro de GPS Habilitado
(1= Habilitado 0= Deshabilitado)
1 Ahorro de Módem Habilitado
(1= Habilitado 0= Deshabilitado)
1 Ahorro de Máximo GSM Habilitado
(1= Habilitado 0= Deshabilitado)
3.7 Pedido de Umbrales de Batería
Comando: !L0042
Respuesta: !00042070210
Donde:
!00042 Respuesta al Comando !L0042
070 Umbral de Tensión: Mínima (cada unidad = 0,142Volts) En el ejemplo 10Volts
210 Umbral de Tensión: Máxima (cada unidad = 0,142 Volts) En el ejemplo 30Volts
18
3.8 Pedido de Estado de los Contadores
Comandos: !L0047
Respuesta: !00047100200000000
Donde:
!00047 Respuesta al Comando !L0047
100 Contador 0
200 Contador 1
000 Estado actual del contador 0
000 Estado actual del contador 1
3.9 Pedido de Marcas Horarias
Comando: !L00490
Donde:
!L0049 Nombre del Comando:
0 Número de Marca Horaria
Respuesta: !0004943199
Donde:
!00049 Respuesta al Comando !L00490
43199 Cantidad de segundos / 2 desde la cero hora
GMT. (23:59:59)
3.10 Pedido de Reintentos de ACK
Comando: !L0032
Respuesta: !0003206
Donde:
!00032 Respuesta al Comando !L0032
06 cantidad de reintentos
3.11 Pedido de Debounce
Comando: !L0024
Respuesta: !00024100
Donde:
!00024 Respuesta al Comando !L0024
100 Cantidad de mSeg. de retardo
19 20
3.12 Pedido de Timers
Comando: !L005015
Donde:
!L0050 Nombre del Comando:
15 Número de Timer
Respuesta: !0005015100003600
Donde:
!00050 Respuesta al Comando:
15 Número de timer
1 Tipo de timer (0=no estable; 1=estable)
00003600 Cantidad de Seg.
3.13 Pedido de Escucha Telefónica
Comando: !L0017110123456789
Donde:
!L0017 Nombre del Comando
1 Llamada Saliente (1= Saliente 0= Entrante)
10 Cantidad de segundos x 10 de espera hasta
Cancelar la escucha (Si la llamada esta en curso
no cancela la llamada)
123456789 Número de teléfono al que debe llamar (En caso
de llamada entrante omitir)
Respuesta: !K0017
3.14 Pedido de Activación de Salidas
Comando: !L0S341
Donde:
!L0S34 Nombre del Comando
1 Número de Salida (0-2) (0= Motor,1= Buzzer, 2=
Sal. Auxiliar)
Respuesta: !K0034
3.15 Pedido de Desactivación de Salidas
Comando: !L0N341
Donde:
!L0N34 Nombre del Comando
1 Número de Salida (0-2) (0= Motor,1= Buzzer, 2=
Sal. Auxiliar)
Respuesta: !K0034
3.16 Pedido de Posición GPS
Comando: !L0013
Respuesta:
!0001326/05/09,18:25:13,-3457.22,-05849.37,B,3,V,000,000,000,010,13
Donde:
!00013 Respuesta al Comando !L0013
26/05/09 Fecha
18:25:13 Hora GMT
-3457.22 Latitud (grados por 100) -34,5722
-05849.37 Longitud (grados por 100) -058,4937
B Cantidad de satélites en hexa (11)
3 Posición 3=3D; 2=2D; 0=No válida
V V=válida A=no válida
000 Velocidad kmh
000 Rumbo
000 Reservado
010 HDOP
13 Reservado
Nota: Se recomienda utilizar el Comando: QPF o QTT para pedir Posición
3.17 Pedido de Umbrales de Conversores A/D
Comando: !L0076
Respuesta: !0007603A2060E
Donde:
!L0076 Nombre del comando
03A2 Valor en Hexadecimal del conversor A/D 1.
060E Valor en Hexadecimal del conversor A/D 2.
Nota: Para obtener el valor en mV, convertir el valor Hexa a decimal y dividirlo por 3,1.
3.18 Pedido de Distancias y giros
Comando: !L0078
Respuesta: !000780010000080000500002015
Donde:
!L0078 Nombre del comando
00100 Valor de velocidad para la posición 0
0080 Valor de velocidad para la posición 1.
0050 Valor de velocidad para la posición 2.
0020 Valor de velocidad para la posición 3.
00 Estado de los indicadores de giro.
21
00= ningún indicador habilitado
01= indicador 0 habilitado
02= indicador 1 habilitado
03= indicadores 0 y 1 habilitados
04= indicador 2 habilitados
05= indicadores 0 y 2 habilitados
06= indicadores 2 y 3 habilitados
08= indicador 3 habilitado
09= indicadores 0 y 3 habilitados
10= indicadores 1 y 3 habilitados
11= indicadores 0-1 y 3 habilitados
12= indicadores 2 y 3 habilitados
13= indicadores 0-2 y 3 habilitados
14= indicadores 1-2 y 3 habilitados
15= Todos los indicadores habilitados
22
Comandos de Restauración . 4
4.1 Pedido de Reset
Comando: !L00162
Respuesta: !K0016
Nota: Este comando reinicia el equipo sin modificar ningún parámetro.
4.2 Pedido de Default
Comando: !L0098
Respuesta: !K0048
Nota: ¡Cuidado! Este comando retorna al equipo a los valores de fábrica.
4.3 Pedido de Borrar Default
Comando: !L0097
Respuesta: !K0097
Nota: ¡Cuidado! Este comando borra todos los valores de los Timers y todas las
Reglas, dejando al equipo sin reportar.
4.4 Pedido de Borrar Eventos Pendientes
Comando: !L0064
Respuesta: !K0064
Nota: ¡Cuidado! Este comando borra todos los eventos pendientes de envío.
4.5 Pedido de Borrar Eventos Históricos
Comando: !L0011
Respuesta: !K0011
Nota: ¡Cuidado! Este comando borra todos los eventos grabados en la memoria
EEPROM.
23
Notas
Nota 1: Generales
El checksum que aparece en los ejemplos no esta calculado. Son solo a título
informativo.
Cuando el equipo tiene eventos pendientes que descargar enviará un paquete cada 3
segundos.
Nota 2:
Cálculo de Checksum en Visual Basic
Public Function Check_Cmd(ByVal str1 As String)
Dim x, y As Integer
Dim chk As String
y = 0
For x = 1 To Len(str1) - 1
y = y Xor (Val(Asc(Mid(str1, x, 1))) And &H7F)
Next
chk = Hex(y)
If Len(chk) = 1 Then chk = "0" + chk
Check_Cmd = chk
End Function
Cálculo del checksum en C
/* get chksum */
int r;
unsigned char chksum;
chksum = 0;
for (r = 0; r < strlen(modem.rxbuff); r++)
{ if (
modem.rxbuff[r] == '*')
break;
else
chksum = chksum ^ modem.rxbuff[r];
}
Ejemplos de Checksum correctos
>RGP060905122440-3460494-058625150000003FF7E0601;ID=1001;#0000;*2E<CR
LF
>RGP040507122440-3460494-058625150000003FF7E0601;ID=9999;#0000;*22<CR
LF
24
Nota 3:
Decodificación de los Estados de las Entradas
>RGP190805211932-3457215-058493640000000FF9 F 0300;ID=8251;#2122;*54< CR LF
La información del estado de las entradas se presenta, codificada en hexadecimal,
en el byte resaltado. Para decodificarla hay que convertir el valor en hexa a binario.
Ej: 9F = 10011111 =>
1=Entrada Ignición (1=0 volt; 0=6-30 volt)
0=Entrada batería interna conectada (0=6-9volt; 1= menos de 6 volt)
0=Entrada batería externa conectada (0=6-30 volt; 1=menos de 6 volt)
1=Entrada 4 (cable verde) al aire
1=Entrada 3 (cable gris) al aire
1=Entrada 2 (cable naranja) al aire
1=Entrada 1 (cable rojo) al aire
1=Entrada 0 (cable marrón) al aire
Nota 4:
Comunicacion por puerto local
Para comunicarse con la unidad por puerto local, vía cable de programación,
es necesario reemplazar el primer caracter (!) por (#) y agregar (*) checksum
al final.
Ejemplo de Comando !L0095 (Número de serie) enviado por puerto local:
#L0095*63 El checksum se calcula haciendo OR exclusivo
Desde el #
(inclusive) hasta el * (sin incluirlo)
Respuesta: #00095A1234
Por puerto local no estan implementados los Comandos:
QPF, QTT, STD, SED, SSG y QDLT

**Comment by cgarbero** [comment]
can you help me to add this protocol is TAIP protocol

**Comment by cgarbero** [comment]
https://drive.google.com/file/d/0B5W1GhBiE_lMLWhOUGViODlMRTQ/view

**Comment by cgarbero** [comment]
help!!!!!!!!!! i

**Comment by tananaev** [comment]
I will provide a new build for you a bit later.

**Comment by tananaev** [comment]
Here is a new version to test:
https://www.dropbox.com/s/myt68q5u7fiz49r/tracker-server-jar-with-dependencies.jar?dl=0

As there were quite a few changes since last release, you need to modify the config file:

1. Rename all `http.*` parameters to `web.*`
2. Rename `database.selectDevice` to `database.selectDevicesAll`
3. Change `database.selectDevicesAll` return column name from `imei` to `uniqueId` which in case of default config mean just removing `as imei`

**Comment by cgarbero** [comment]
all this change i have to do in the traccar.cfg ?

**Comment by cgarbero** [comment]
what does it mean " Rename all http.* parameters to web.*"

**Comment by fabover** [comment]
Todas esas modificaciones son en traccar.cfg si.
debe quedar asi: 
donde antes decia: http. debes poner web.

<entry key='database.selectDeviceAll'>
        SELECT id, uniqueId
        FROM devices;
    </entry>

 
    <entry key='web.enable'>true</entry>
    
    <entry key='web.port'>8082</entry>
    <entry key='web.application'>C:\Program Files\Traccar\traccar-web.war</entry>

**Comment by fabover** [comment]
<entry key='web.enable'>true</entry>
    
    <entry key='web.port'>8082</entry>
    <entry key='web.application'>C:\Program Files\Traccar\traccar-web.war</entry>

**Comment by fabover** [comment]
<entry key='web.enable'>true</entry>

**Comment by tananaev** [comment]
Looks correct. Does it work?

**Comment by cgarbero** [comment]
i am trying the port is 5037 ?

**Comment by fabover** [comment]
deberia ser 5057

**Comment by fabover** [comment]
si no te funciona prueba cambiar: database.selectDeviceAll por database.selectDevicesAll

**Comment by tananaev** [comment]
Please write in English. Port is the same.
