### ISSUE TITLE
Java version update

### ISSUE THREAD

**Issue by vitalidze** [tananaev/traccar#1273]
I am seeing significant changes to the code of project. From my point of view the time has come to update the minimal java version for the project, even java 7 [reached end of support](https://www.java.com/en/download/faq/java_7.xml). Some statistics ([1](https://plumbr.eu/blog/java/java-version-statistics-2015-edition) [2](http://mcstats.org/global/)) say that java 7 already dominates on many of tested servers. I think it would be great to move to java 8 as it is a mature release now and considered to be the most significant one since java 5 (with generics support).

**Comment by tananaev** [comment]
First of all, I would love to move to Java 7 or even Java 8.

Minecraft servers statistics looks good, but the statistics from Plumbr is worrying. It basically shows that  20% (1 out of 5) of users still have Java 6.

**Comment by vitalidze** [comment]
I believe nowadays everyone can just upgrade java. Why can't you just force them to do so? Maybe you can even create some poll on your web site about a version of java people are using.

**Comment by tananaev** [comment]
I guess I can check for the version in the installer. OK, I will update soon, but I want to release another version before the update as it's almost ready.

Speaking of new version, I am implementing JavaScript version of web interface. I will keep support for your MOD UI, but there are quite a few changes in the config and there likely be some more changes. Just heads up that you would probably need to update your documentation.

**Comment by vitalidze** [comment]
Thank you. It would be great to jump to java 8, which is the mainstream now. For your consideration. Also GWT does not support java 8 yet, so my web UI mod will probably stick with java 7, but it will support it some day for sure.

Actually I am keeping my eye on your changes, so I am aware of it. I can see that another major update with function for sending commands is coming, which is implemented as a separate servlet. I am very interested in it as well, since many users of my web mod also requesting. But this is out of scope of this issue. Anyway, thank you very much for keeping some small thought on me.

**Comment by tananaev** [comment]
I will switch to Java 7 first.

As for commands support, it won't be included in this release either, but right after.

**Comment by Jeferex** [comment]
@tananaev the next release is going to bundle new javascript web version?

**Comment by tananaev** [comment]
@Jeferex, yes, it will include new JavaScript web interface by default.

**Comment by guilhermesouza** [comment]
@tananaev, you already ready web interface to power you see? Some screen
shot

Em qua, 24 de jun de 2015 às 17:59, Anton Tananaev <notifications@github.com>
escreveu:

**Comment by tananaev** [comment]
@guilhermesouza, no screenshots, but it looks very similar to the old one for the first version.

**Comment by guilhermesouza** [comment]
@tananaev <https://github.com/tananaev>, The new version of traccar already
have support for sending commands by GPRS? in a recent post that a
developer made this implementation, you want to include this in the next
versions?

Em qua, 24 de jun de 2015 às 19:07, Anton Tananaev <notifications@github.com>
escreveu:

**Comment by tananaev** [comment]
@guilhermesouza, no it doesn't. Sending command support will not be included in the new version just yet.

**Comment by guilhermesouza** [comment]
@tananaev <https://github.com/tananaev>, GPRS command sending is very
complicated at what level?You need to change a lot in traccar the code to
make it work or only the structure of the protocols?

Em qua, 24 de jun de 2015 às 19:27, Anton Tananaev <notifications@github.com>
escreveu:

**Comment by guilhermesouza** [comment]
@tananaev <https://github.com/tananaev>, The change would have to be in the
core or each protocol traccar?

Em qua, 24 de jun de 2015 às 19:33, Guilherme Souza <souzaux@gmail.com>
escreveu:

**Comment by tananaev** [comment]
@guilhermesouza, if you want to discuss it in more details, please discuss it on a relevant topic. This issue is about updating Java version.

**Comment by guilhermesouza** [comment]
OK.

Em qua, 24 de jun de 2015 às 19:35, Anton Tananaev <notifications@github.com>
escreveu:
