### ISSUE TITLE
error starting traccar v3

### ISSUE THREAD

**Issue by and12345** [tananaev/traccar#1275]
Hi Anton,

Been following traccar project, today after upgrade i got an error while starting traccar : 

2015-06-27 17:41:01  WARN: Table 'traccar.user' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder.java:287 < DataManager.java:225 < PermissionsManager.java:50 < ...)

traccar doesn't create the required tables.

**Comment by tananaev** [comment]
Are you sure you have all required queries in the config?

**Comment by and12345** [comment]
Hi Anton,

I'm following code from https://www.traccar.org/mysql/ last time in v2 it works.

**Comment by tananaev** [comment]
Please post your config file.

**Comment by and12345** [comment]
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    


	<entry key='database.driver'>com.mysql.jdbc.Driver</entry>
	<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&amp;autoReconnect=true</entry>
	<entry key='database.user'>test</entry>
	<entry key='database.password'>testtraccar</entry>


    <entry key='database.createSchema'>
        CREATE TABLE user (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(1024) NOT NULL,
        email VARCHAR(256) NOT NULL UNIQUE,
        hashedPassword VARCHAR(1024) NOT NULL,
        salt VARCHAR(1024) DEFAULT '' NOT NULL,
        readonly BOOLEAN DEFAULT false NOT NULL,
        admin BOOLEAN DEFAULT false NOT NULL,
        map VARCHAR(1024) DEFAULT 'osm' NOT NULL,
        language VARCHAR(1024) DEFAULT 'en' NOT NULL,
        distanceUnit VARCHAR(1024) DEFAULT 'km' NOT NULL,
        speedUnit VARCHAR(1024) DEFAULT 'kmh' NOT NULL,
        latitude DOUBLE DEFAULT 0 NOT NULL,
        longitude DOUBLE DEFAULT 0 NOT NULL,
        zoom INT DEFAULT 0 NOT NULL);

        CREATE TABLE device (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(1024) NOT NULL,
        uniqueId VARCHAR(256) NOT NULL UNIQUE,
        status VARCHAR(1024),
        lastUpdate TIMESTAMP,
        positionId INT,
        dataId INT);

        CREATE TABLE user_device (
        userId INT NOT NULL,
        deviceId INT NOT NULL,
        `read` BOOLEAN DEFAULT true NOT NULL,
        `write` BOOLEAN DEFAULT true NOT NULL,
        FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE,
        FOREIGN KEY (deviceId) REFERENCES device(id) ON DELETE CASCADE);

        CREATE INDEX user_device_user_id ON user_device(userId);

        CREATE TABLE position (
        id INT PRIMARY KEY AUTO_INCREMENT,
        protocol VARCHAR(1024),
        deviceId INT NOT NULL,
        serverTime TIMESTAMP NOT NULL,
        deviceTime TIMESTAMP NOT NULL,
        fixTime TIMESTAMP NOT NULL,
        valid BOOLEAN NOT NULL,
        latitude DOUBLE NOT NULL,
        longitude DOUBLE NOT NULL,
        altitude DOUBLE NOT NULL,
        speed DOUBLE NOT NULL,
        course DOUBLE NOT NULL,
        address VARCHAR(1024),
        other VARCHAR(8192) NOT NULL,
        FOREIGN KEY (deviceId) REFERENCES device(id) ON DELETE CASCADE);

        CREATE TABLE data (
        id INT PRIMARY KEY AUTO_INCREMENT,
        protocol VARCHAR(1024),
        deviceId INT NOT NULL,
        serverTime TIMESTAMP NOT NULL,
        deviceTime TIMESTAMP NOT NULL,
        other VARCHAR(8192) NOT NULL,
        FOREIGN KEY (deviceId) REFERENCES device(id));

        ALTER TABLE device ADD
        FOREIGN KEY (positionId) REFERENCES `position`(id);

        ALTER TABLE device ADD
        FOREIGN KEY (dataId) REFERENCES data(id);

        CREATE TABLE server (
        id INT PRIMARY KEY AUTO_INCREMENT,
        registration BOOLEAN NOT NULL,
        latitude DOUBLE NOT NULL,
        longitude DOUBLE NOT NULL,
        zoom INT NOT NULL);

        CREATE TABLE traccar (
        id INT PRIMARY KEY AUTO_INCREMENT);
    </entry>
....
all others are default

**Comment by tananaev** [comment]
Following line is missing:
<pre>&lt;entry key='database.checkTable'&gt;traccar&lt;/entry&gt;</pre>

**Comment by and12345** [comment]
I've tried to add that line, but still traccar complain table doesn't exist. I'm sure with mysql username password is right.
Is there any changes from v2 to v3 in order to use mysql database ?

**Comment by tananaev** [comment]
So, you installed clean version 3.0 and changed 4 lines in the config, correct? That's what I did on the demo server and it works.

**Comment by and12345** [comment]
yes, but i'm using a new database (i create one empty dtabase)

**Comment by tananaev** [comment]
I created an empty database for the demo server. Exactly the same setup as you.

**Comment by and12345** [comment]
I'm running Java(TM) SE Runtime Environment (build 1.7.0_80-b15) with Ubuntu 14.04 64bit, is this Java version supported ?

**Comment by tananaev** [comment]
Yes, you can use Java 6 and higher. Can I take a look at your setup (SSH)?

**Comment by and12345** [comment]
yes, could you please send your public key to and12345.88 at gmail com

**Comment by and12345** [comment]
Hi Anton, i've add your key. feel free to look, it's not a production server.

**Comment by tananaev** [comment]
I have fixed the problem. It was actually a tricky one.

The error message was
<pre>Specified key was too long; max key length is 767 bytes</pre>

All keys are 256 characters UTF8, but because MySQL assumes the worst case for UTF8 (3 bytes), we get 256 * 3 = 768 (>767 for InnoDB).

It worked for me on the demo server because (I guess) I'm using MyISAM which has 1000 bytes limit.

I will update the queries to satisfy both engines.

**Comment by and12345** [comment]
great !! Thanks a lot Anton :dancers:

**Comment by qbraksa** [comment]
Hi, just curious .... was this merged into 3.0 ?

Because I'm kinda having the same issues, and the default config file generated still contains the old valuse that cause the previous error : 

```
Specified key was too long; max key length is 767 bytes
```

(I downloaded `traccar-macosx-64-3.0.zip` from `traccar.org/download`)

**Comment by tananaev** [comment]
Version 3.0 is already released, so I can't merge anything into it. This fix will be included in the 3.1 release. For now you can just take changes and apply them to your current config file.
