### ISSUE TITLE
problems with the new Traccar web 3.0:

### ISSUE THREAD

**Issue by guilhermesouza** [tananaev/traccar#1277]
problems with the new Traccar web 3.0:

- With each update it duplicates values in the state field.
- When a device is turned off it still continues displaying the online status (green)

**Comment by tananaev** [comment]
I have fixed state fields duplication. Replace this file in your Traccar web directory:
https://github.com/tananaev/traccar/blob/ea0a523ef676310526055b1ae381387868afd738/web/app/view/state/StateController.js

As for green status, it's only color. It doesn't mean that it's online.

**Comment by guilhermesouza** [comment]
Thanks! @Anton

Em sáb, 27 de jun de 2015 às 18:15, Anton Tananaev <notifications@github.com>
escreveu:

**Comment by anton** [comment]
@guilhermesouza thanks for what? are you confusing me with someone else?

**Comment by tananaev** [comment]
My name is Anton as well.
