### ISSUE TITLE
the server error occurs when you start the new version 3.0

### ISSUE THREAD

**Issue by guilhermesouza** [tananaev/traccar#1283]
After compiling the new version 3.0 traccar and send to the server error occurs when you start:

STATUS | wrapper  | 2015/06/29 23:55:24 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/06/29 23:55:24 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/06/29 23:55:24 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/06/29 23:55:24 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/06/29 23:55:24 | 
STATUS | wrapper  | 2015/06/29 23:55:24 | Launching a JVM...
INFO   | jvm 1    | 2015/06/29 23:55:24 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp: 
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at java.io.BufferedReader.fill(BufferedReader.java:161)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at java.io.BufferedReader.readLine(BufferedReader.java:324)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at java.io.BufferedReader.readLine(BufferedReader.java:389)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at org.traccar.ServerManager.init(ServerManager.java:39)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:117)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:26)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:483)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2015/06/29 23:55:27 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2015/06/29 23:55:29 | <-- Wrapper Stopped

**Comment by tananaev** [comment]
Fixed the problem. Please try again.
