### ISSUE TITLE
New columns 

### ISSUE THREAD

**Issue by mpele** [tananaev/traccar#1284]
Is it possible to some data (odometer, power etc.) be saved in separated columns in table positions through changing traccar.cfg (of course, with manual table adaptation) or the changes have to be done through modification of code?

**Comment by tananaev** [comment]
Depends on the database engine you are using. For example, in MySQL you can use `ExtractValue` function to get values from XML field.

**Comment by mpele** [comment]
Thank you for your prompt reply.
