### ISSUE TITLE
Restarting Traccar fails when using MySQL

### ISSUE THREAD

**Issue by sonar98** [tananaev/traccar#1288]
In the wrapper log following lines:
WrapperSimpleApp Error: Encountered an error running main:
01 09:29:39 | WrapperSimpleApp Error: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'user' already exists
01 09:29:39 | WrapperSimpleApp Error: <---->at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
01 09:29:39 | WrapperSimpleApp Error: <---->at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccesso
01 09:29:39 | WrapperSimpleApp Error: <---->at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructo
01 09:29:39 | WrapperSimpleApp Error: <---->at java.lang.reflect.Constructor.newInstance(Constructor.java:534)
01 09:29:39 | WrapperSimpleApp Error: <---->at com.mysql.jdbc.Util.handleNewInstance(Util.java:389)
01 09:29:39 | WrapperSimpleApp Error: <---->at com.mysql.jdbc.Util.getInstance(Util.java:372)

traccar.xml:
`<entry key='database.driver'>com.mysql.jdbc.Driver</entry>`
`<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/vru_gps?allowMultiQueries=true&amp;autoReconnect=true</entry>`
`<entry key='database.user'>vru_gps</entry>`
`<entry key='database.password'>**********</entry>`

**Comment by tananaev** [comment]
It looks like you removed required configuration parameter:

<pre>&lt;entry key='database.checkTable'&gt;traccar&lt;/entry&gt;</pre>

**Comment by sonar98** [comment]
You are right.. that was it.
