### ISSUE TITLE
Update from 2.x to 3.0 migrate all data

### ISSUE THREAD

**Issue by 1sthandy** [tananaev/traccar#1293]
Hi anton,

i need for all synology users a migrating script. there is a mysql database running, so i think its simple to create a commandline

thanks

Greetings Gordon

**Comment by tananaev** [comment]
It's not that easy. The main problem is that user passwords are now stored as hashes instead of plain text like in the old version.

**Comment by 1sthandy** [comment]
you can read out the old table "users" with the passwords, crypt the passwords and insert these in the new table. maybe a normal php script can be used. or can you use the loginname and crypt them for the first login? like the admin

**Comment by tananaev** [comment]
One option I can think of is to reset password for all users to some pre-defined password.

**Comment by 1sthandy** [comment]
that sounds good

**Comment by tananaev** [comment]
I have generated a hash for password "password":

`ef38a22ac8e75f7f3a6212dbfe05273365333ef53e34c14c` (hash)
`000000000000000000000000000000000000000000000000` (salt)

Can you help with SQL scripts for migration?

**Comment by 1sthandy** [comment]
How can i help?
is it better to work with two databases traccar(version2) and traccar3(version3)
are any tables the same in both versions?

**Comment by tananaev** [comment]
I changed names of all tables on purpose, to avoid errors and keep old data safe.

For example, users are now in `user` table instead of `users`, device in `device` table instead of `devices` etc. There are not too many changes to the actual structure, so it should be possible to copy data with a simple script.

**Comment by gmoscalu** [comment]
Hi guys,

Sorry to barge in, but depending on how authentication takes place, you could easily use for the migration the builit-in tools: https://dev.mysql.com/doc/refman/5.5/en/encryption-functions.html I suggest using the PASSWORD command - if it's secure enough for enterprises to secure DB access, I think it should be secure enough to secure our accesses as well.

This, of course if the app would then use the same encryption scheme when authorizing user acess or doing something like this in the app: SELECT IF(PASSWORD(gui_password)=db_stored_password,'OK','NOK') FROM db_table_holding_credentials WHERE login_name='gui_username';

IMHO, if I see dozens of duplicated tables in my DB, I will probably decide to drop them at some time and possibly break functionality.

**Comment by tananaev** [comment]
@gmoscalu, I don't want Traccar to depend on particular database engine implementation of encryption functions as it's not part of the SQL standard and some engines might not have it.

**Comment by tananaev** [comment]
I have created a script to copy data from old database schema to the new one:

https://www.traccar.org/update-from-2-x-to-3-0/

**Comment by 1sthandy** [comment]
thanks, can i use it for migration from 2-x-to-3-1 also?
or must i use that:
https://www.traccar.org/update-from-3-0-to-3-1/ ?

**Comment by tananaev** [comment]
I think you can, but I haven't tested migration directly from 2.x to 3.1.

**Comment by nikenikw** [comment]
Hi 1sthandy,

sorry to bothering you,
I am a Synology user, and very thanks for you effort on  traccar for Synology,
just want to ask, will we have traccar 3.1 for Synology?

Thank you!

**Comment by 1sthandy** [comment]
@tananaev i have tested the migration, it works fine. thanks for your help
