### ISSUE TITLE
which is TK103 port?

### ISSUE THREAD

**Issue by lucasViniciusNunes** [tananaev/traccar#1294]
Hello,

I need to send a command to GPS device, I have IP address but I don' t have the port. Can you help me?

Thank you.

**Comment by tananaev** [comment]
Usually you can find correct port for devices here:
https://www.traccar.org/devices/

But in your particular case you need to try all ports from the following web page:
https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by lucasViniciusNunes** [comment]
Hi,

Thank you for your answer.

I tried to use all that ports but anything works. I wrote the following code, but I can not communicate. 
How did you do to find those ports?

	for (int i = 5000; i<5100; i++) {
		// getPositionsFromMicroSD method call
	}

	public void getPositionsFromMicroSD(String iP, int port, List<Date> dates, int pwd) {
		Socket client;
		try {
			client = new Socket(iP, port);
			PrintStream exit = new PrintStream(client.getOutputStream());
			
			SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
			for (Date date : dates) 
				exit.println("load" + pwd + " " + sdf.format(date));
			
			exit.close();
		} catch (UnknownHostException e) {
			e.printStackTrace();
		} catch (IOException e) {
			System.out.println("Error to send informations to: " + "IP: " + iP + " port: " + port);
			//e.printStackTrace(); //TODO Create erros log.
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

**Comment by lucasViniciusNunes** [comment]
I have another doubt, which is velocity measurement unit? is It mile? I am problem to convert it.

**Comment by Jeferex** [comment]
Speed Units is always Knots in Traccar.

**Comment by tananaev** [comment]
@lucasViniciusNunes, can you please explain in more details of what you are trying to do. Your code doesn't make sense to me. Are you trying to connect to the device? Device should be the client.

**Comment by lucasViniciusNunes** [comment]
Yes, I am trying to connect to device and client is the device. I need to send commands on random moments, for example, I need to send command "get positions in microSD card" (load+pwd date), but I only can send commands when the device communicate with me. Code I posted is a attempt to discover the input port.

**Comment by tananaev** [comment]
You can't connect directly to the device. You need to wait for device to connect to your server.

**Comment by lucasViniciusNunes** [comment]
I need get positions in Micro SD, when device communicate with me I send the command **,imei:999999999999999,Q,YYYYMMDD and it works, but I need get which is IMEI device that is communicating and it is very slow. I can't wait long time because I need to release the connection to another devices send positions. 
Do you have any idea how I can resolve it?

**Comment by tananaev** [comment]
There is no way to resolve it. It's impossible to connect to the device directly because it's not a server. You have to wait for the connection.

**Comment by lucasViniciusNunes** [comment]
Is It problem happens only with TK103 or with all devices?

**Comment by tananaev** [comment]
It's not a problem. It's the way all devices work. You cannot connect directly to devices because they are not servers.

**Comment by lucasViniciusNunes** [comment]
Ok. Thank you for your time.
