### ISSUE TITLE
Position entries does not showup on web

### ISSUE THREAD

**Issue by PerBuus** [tananaev/traccar#1296]
Hi,

Just installed the newest version and setup my TK106 device.

Log shows:

2015-07-10 13:03:18 DEBUG: [40C71CD4: 5001 <- xxx.xxx.xxx.xxx] - HEX: 2a48512c343130363031333633392c56312c3131303331382c412c353730302e333932302c4e2c30303935352e383136362c452c3030302e33302c3030302c3130303731352c46464646464246462c3233382c30312c302c302c3623

which seems to be correct (ident as exspected = "4106013639").

But entries does not show up, when I register a device for this ident?

"position" table is emty.

Any idea?

Thanks!

Per Buus Sorensen

**Comment by tananaev** [comment]
Your device uses H02 protocol. Port 5013 in Traccar.

**Comment by PerBuus** [comment]
Thanks!

It works.

Per


Fra: Anton Tananaev [mailto:notifications@github.com]
Sendt: 11. juli 2015 02:27
Til: tananaev/traccar
Cc: Per Buus Sørensen
Emne: Re: [traccar] Position entries does not showup on web (#1296)


Your device uses H02 protocol. Port 5013 in Traccar.
