### ISSUE TITLE
Address encoding problem in 3.0

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#1298]
Examples:
<pre>
nominatim/reverse.php?format=json&lat=-20.2453300&lon=-70.0942000&zoom=18&addressdetails=1
nominatim/reverse.php?format=json&lat=49.607605&lon=8.517553&zoom=18&addressdetails=1
</pre>

**Comment by MRokas** [comment]
It happens with all 3 reverse lookups. They return everything correct, so I would guess error is in the code (would help, but I don't trust my java knowledge, which is barely above 0)

**Comment by tananaev** [comment]
I guess the problem is when the data is written into the database. What database are you using?

**Comment by MRokas** [comment]
Tried default and MySQL. Utf8_general_ci on MySQL

**Comment by tananaev** [comment]
Make sure you have following parameters in your `database.url` parameter:

<pre>useUnicode=yes
characterEncoding=UTF-8</pre>

**Comment by MRokas** [comment]
I've both of them, and even tried refreshing page.
Not really sure what the issue could be :/

**Comment by tananaev** [comment]
Is the encoding incorrect in the web interface or in the database as well?

**Comment by MRokas** [comment]
Both of them.

**Comment by tananaev** [comment]
Try to use `utf8mb4` encoding in MySQL instead of simply `utf8`.
