### ISSUE TITLE
3g support - Query

### ISSUE THREAD

**Issue by alltimeashu** [tananaev/traccar#1300]
Hi,

Is traccar support GPS tracking devices running on 3g or 4g instead of GPRS protocol? Like Meitrack T333 using 3g.

**Comment by tananaev** [comment]
From the server point of view there is no difference between those, so Meitrack T333 should work as long as it uses same message format as other Meitrack devices.

**Comment by alltimeashu** [comment]
Thanks for confirmation.👍
