### ISSUE TITLE
Traccar on windows

### ISSUE THREAD

**Issue by emmerossi** [tananaev/traccar#1305]
Hi, tried to install in windows environment, several errors running traccar batch file that invoke wrappermanager. Where find detailed instructions for windows environment ? thanks

**Comment by tananaev** [comment]
You are not supposed to touch any batch files. Traccar is a windows service and it's started automatically after restart or you can start it manually from Services.

**Comment by emmerossi** [comment]
I'm sure I miss something in the installation process. Seems too simple to work, executing the install file and reboot and expect everithing works as windows services. Where to find detailed intallation/configuration instructions ? Thank you

**Comment by tananaev** [comment]
That's all you need to do. Just run the installer and restart the system.

Try to open following link in browser:
<a href="http://localhost:8082/">http://localhost:8082/</a>

**Comment by tananaev** [comment]
You can find some more details here:

https://www.traccar.org/quick-start/

**Comment by emmerossi** [comment]
Magic! it really works, thanks. Now moving to configuration details I do not see the traccar.cfg and the only way to change configuration seems to edit traccar.xml file, nevertheless restarting service does not take that changes. Thank you again.

**Comment by tananaev** [comment]
Starting from version 3.0 I renamed the file from `traccar.cfg` to `traccar.xml`.

**Comment by emmerossi** [comment]
Ok. but changing manually the xml file and restarting the service it stops its execution. Is this the right way to start/stop the server ? Bye

**Comment by tananaev** [comment]
Are there any better options?

**Comment by emmerossi** [comment]
Well there are, but this is not the problem. The problem I'm facing is that any modification to .xml file does not seems to have any effect on configuration, restarting traccar service from windows control panel or even rebooting the system. In other words my impression is that traccar server works perfectly if you use the standard configuration, but no parameter can be altered  at all.

**Comment by tananaev** [comment]
You must be doing something wrong. What parameters did you try to change?

**Comment by emmerossi** [comment]
First I'd like to change the http port from 8082 to something different, then try to use mySql and last the listening ports from trakers. Any help is appreciated, thanks.

**Comment by tananaev** [comment]
That's a lot of changes. Check `wrapper.log` for the actual error message, but most likely there is some problem with MySQL.

**Comment by emmerossi** [comment]
Hi, I've made some progress : Now it works fine on any specific ip port. I'm using a Tk103-2 tracker and use all port number as suggested, not visualizing on map. Same configuration do not work neither on my server nor on demo.traccar.org with the same result. Debugging hex code I receive ##,imei:359710046174166,A; thats'all no position at all. Calling the tracker directly it shows lat, long, and speed, so presume it works but do not sent this info to server. Thank you

**Comment by tananaev** [comment]
You should use port 5001 for your device. As for logging GPS data, read point 1 on the following page:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by emmerossi** [comment]
Anton, thank you very much for support and patience. I've read all information and debug the log, tried all ports in range, but guess the TK103-2 is a bit unstable. Now it works perfectly, great work, will try to use also MySQL as well. Thank you again, Ciao.
