### ISSUE TITLE
CRX1 (TR06) CONCOX PROTOCOL

### ISSUE THREAD

**Issue by SRIKAAA** [tananaev/traccar#1308]
I have configured traccar successfully in my server with MS SQL Database. We are receiving data from 2 devices configured to server. Model Number (TR06) of concox. The protocol is similar to GT06 (crx1) model, but TR06 with firmware(TR06_22_60DM2_B25E_V29_L_WM) has internal distance calculation option. Please suggest how to approach to store internal mileage parameter in the database.

![protocol_flow](https://cloud.githubusercontent.com/assets/13375578/8740713/db5b66de-2c6b-11e5-84cb-3a05718f55ed.png)
![protocolwithdistance](https://cloud.githubusercontent.com/assets/13375578/8740712/db3c11ee-2c6b-11e5-8751-1f1b5a81dff0.jpg)

**Comment by tananaev** [comment]
Can you please provide full documentation.

**Comment by SRIKAAA** [comment]
I have sent full document PDF to your Email ID (anton.tananaev@gmail.com) from srikanth.gundla@pragatipadh.com

**Comment by tananaev** [comment]
I have implemented the extension. It would be nice if you could provide me with some HEX message samples with mileage information for testing.

**Comment by SRIKAAA** [comment]
Can i have complete setup file with above implementation. Highly appreciate if you can provide the same.

**Comment by tananaev** [comment]
Here is a binary file:
https://www.dropbox.com/s/myt68q5u7fiz49r/tracker-server-jar-with-dependencies.jar?dl=0

You need to install latest official release and replace `tracker-server.jar` with the above file.

**Comment by SRIKAAA** [comment]
Hi

Hope you are fine. I have installed latest setup file. For above protocol, Do i need to modify any scripts in MS SQL Databases to capture the event_Key_Odometer Value.

**Comment by tananaev** [comment]
No, you don't need to modify anything.

**Comment by SRIKAAA** [comment]
OK
After observing the data, we found that only when the Ignition is ON, the position data is being inserted in the database. I would share the Log of position table. WHen vehicle is stopped/Ignition is OFF. The device would send "GPS_STATUS" message. Is there a possibilty to pass latitude=0,longitude=0 to the database with current time stamp.

Problem: In my application, i am showing the datetime from position table and if vehicle stops for 5 hours. Customer is asking why there is no latest time.

**Comment by tananaev** [comment]
Traccar does not support messages without GPS info yet. The plan is to add support for it in the next release.

**Comment by SRIKAAA** [comment]
I am not getting  " event_Key_Odometer " value in position table. Log "{"sat":7,"acc":true,"mcc":404,"mnc":4,"lac":130,"cell":737280,"index":1837,"ip":"106.67.79.242"}"

I have installed latest set up file. But the mileage parameter is not saved. Give me IP and port address i will configure one device to your server for you to test. (Or i will share Log message packets from device)

**Comment by tananaev** [comment]
If it's not there, it means that your device doesn't send it. Please provide HEX message from the server log to confirm that.

**Comment by SRIKAAA** [comment]
787823120f081b121d37cb01c8e2cc08afd3c020d50201940701d600a1190041ee100576d1470d0a787823120f081b121e05cb01c8e1b608afcdd022d50201940701d600a11a0041ee6c0577250e0d0a787823120f081b121e0fcb01c8e08408afc80020d50301940701d600a11a0041eec605780daf0d0a787823120f081b121e19cb01c8df5c08afc24020d50201940701d600a11a0041ef1f0579f2810d0a787823120f081b121e23cb01c8de1a08afbc4021d50301940701d600a11a0041ef7b057a13d60d0a




The above Log Explaination is sent in Mail.
Below is the split:
78  -->start
78  --> Start
23	--> Length
12 --> Protocol
0f	08 1b 12 1d 37  --> Datetime

cb	--> Satellites


01c8e2cc	--> Latitude
08afd3c0	--> Longitude
20		--> Speed
d502		--> Course, Status

0194		--> MCC
07	--> MNC
01d6	--> LAC
00a119	--> Cell Id
0041ee10 --> Mileage
0576	--> Serial No
d147	--> Checksum
0d0a	--> End Bits

**Comment by tananaev** [comment]
Here is a new build:

https://www.dropbox.com/s/myt68q5u7fiz49r/tracker-server-jar-with-dependencies.jar?dl=0

**Comment by SRIKAAA** [comment]
For the above fix, can you please share the setup file for windows 64-bit OS. I am unable to update the above build in server which has got 3.1 version. Your help is highly required in this regard.

**Comment by tananaev** [comment]
Sorry, but I can't provide installer for this test build. You need to install latest release, replace `tracker-server.jar` file with the one provided above and restart service.

**Comment by SRIKAAA** [comment]
ok..I got it thanks for the information. I m able to receive the mileage parameter now.

Can u share any sample code for storing the Battery status , GSM Strength which would be sent by device in heart beat package. I want to pass Lat, Long=0 along with these parameters to server in NON GPS packet information.

**Comment by tananaev** [comment]
Status parsing code is already there in the decoder:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gt06ProtocolDecoder.java

**Comment by SRIKAAA** [comment]
As per the log shared through mail and below attachement. The NON GPS package info is not getting stored in the database.

Kindly share a sample code to resolve the issue.

**Comment by tananaev** [comment]
Look at the GT06 decoder lines from 207 to 218.

**Comment by SRIKAAA** [comment]
Thank you for reply. 

Kindly note that the Log i have shared is for MSG_STATUS=13

The parameter is declared but not used any where in the code.

private static final int MSG_STATUS = 0x13;  (Line Number 62)

When the vehicle is in parking mode , it is sending only MSG_STATUS packet. It is a NON-GPS Packet.
I have sent the Log in mail yesterday. kindly suggest the sample code. This help would be of great use to me.

**Comment by tananaev** [comment]
I plan to implement support for GT06 status messages soon.

**Comment by Enritux** [comment]
Could we support with some doubts regarding the concox BL10?

**Comment by Enritux** [comment]
Could we support with some doubts regarding the concox BL10? I don't know where to start, the documentation is very poor. I need to understand how the information travels between the terminal and the server.

**Comment by Roshan75** [comment]
Hi. I have GT06n GPS tracker. Can anybody tell me how to create sql database for the GPS tracker. Thank you :)

**Comment by aliz701** [comment]
Currently, I am doing GPS CONCOX settings with SMS
Is there a software to set IP?
