### ISSUE TITLE
Popup dialog box notifying about device state update  

### ISSUE THREAD

**Issue by tebsa** [tananaev/traccar#1309]
Hi Anton,

Is it possible to have a dialog box popup (on the web interface) when the device state changes notifying me that the state of the device has changed?   

Thanks,
Teboho

**Comment by tananaev** [comment]
What do you mean by state changes?

**Comment by tebsa** [comment]
When I get a message from the gps device. I want to get a notification on the web interface that the location has changed.

**Comment by tananaev** [comment]
Most devices send messages every minute or more often, so it doesn't make much sense to show popup every time GPS location is updated. Also, what if you have 10s or even 100s of devices?

**Comment by tebsa** [comment]
I know it does not make sense. But is it possible to do it? I need it for a project I am doing at school. I am making an accident notification system. So my device will only send the message when an accident has occurred. My java is not that good. So I needed guidance on how to go about getting it to give me a popup when a message has been received from the device.

**Comment by tananaev** [comment]
You can implement it in the web interface if you want. Web interface is written in JavaScript.

**Comment by tebsa** [comment]
Thanks I will give it a try.
