### ISSUE TITLE
Tk103-2 via demo server?

### ISSUE THREAD

**Issue by Alex037** [tananaev/traccar#1310]
Hello, I am trying to connect one Xexun's TK 103-2 to traccar's demo server just to see how it works (before I move to setting up own server). However, I am not seeing anything in my traccar account. I have followed the device/port list (5006 for TK103-2), but nothing happened. IMEI number is 013226007839836. Any idea what am I doing wrong here? I am using 104.43.219.242 as demo.traccar.org IP address, right?

**Comment by tananaev** [comment]
Address is correct, but I don't see any messages from your device on the server side.

**Comment by Alex037** [comment]
It is killing me all day. I had previously TK102-2 and was able to set it up in 5 min (some time last year). Now I am trying to hook this one up, but obviously something is going wrong. I have verified the device on xexun website, just to confirm that is not a clone. SMS part is working OK.

**Comment by tananaev** [comment]
I can see your device is sending to the port 5036. You should configure it to use port 5006.

**Comment by Alex037** [comment]
Yes, I have switched SIM card and in desperation tried all ports from link that you posted for TK devices.
https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/
I will try to correct that and see what will happen.
