### ISSUE TITLE
Sevrer Settings not getting saved 

### ISSUE THREAD

**Issue by tebsa** [tananaev/traccar#1312]
Hi Anton,

When I change the server settings and save them. The map layer, latitude, longitude and Zoom values do not get saved. When I logout and log back in these server settings values are empty. This does not seem to work properly. 

![traccar_serever_settings](https://cloud.githubusercontent.com/assets/13431415/8827728/9f325808-308e-11e5-9901-ca62c71ed5e1.png)

Kind Regards,

Teboho Phalatse

**Comment by tananaev** [comment]
This is work in progress. I haven't finished the implementation yet.

**Comment by tebsa** [comment]
Thanks.
