### ISSUE TITLE
Trying to send a command to device with external web

### ISSUE THREAD

**Issue by al3x1s** [tananaev/traccar#1316]
Hey Anton, I'm trying to send a command to device with my webpage and I have been reviewing your JS code

this is how I'm trying to send a command, there is something wrong with this?

```javascript
jQuery.ajax({
    type: "POST",
    url: "http://url:8082/api/command/send",
    dataType: "json",
    data: {
        deviceId: 12,
        type: "positionStop",
        other: ""
    },
    success: function (res) {
    	console.log("done");
    	console.log(res);    
    }
});
```

I got this output from console.log

```
[Log] 
{
  "success": false,
  "error": "Unexpected char 100 at (line no=1, column no=1, offset=0)"
}
```

reference: 
[Traccar commit](https://github.com/tananaev/traccar/commit/8063c5e93514475daba2caf6538e261f27681bc3)

**Comment by tananaev** [comment]
It looks correct, but try to remove `other` field and see if it works.

If it doesn't, please check actual request and response in the browser developer console.

**Comment by al3x1s** [comment]
It works if I build manually JSON Object instead use **req.getReader()** adding these lines to **send(HttpServletRequest req, HttpServletResponse resp)** function in **CommandServlet.java**

``` java
    private void send(HttpServletRequest req, HttpServletResponse resp) throws Exception {
        //---- BEGIN
        Log.debug("REQ device | " + req.getParameter("deviceId"));
        Log.debug("REQ type | " + req.getParameter("type"));
        
        JsonObject jo = Json.createObjectBuilder()
            .add("deviceId", req.getParameter("deviceId"))
            .add("type", req.getParameter("type"))
            .build();
        // ------- END

        Command command = JsonConverter.objectFromJson((jo), new Command());
        
        getActiveDevice(command.getDeviceId()).write(command);
        sendResponse(resp.getWriter(), true);
    }
```

**Traccar log output:**
```
2015-07-27 16:56:32 DEBUG: REQ device | 12
2015-07-27 16:56:32 DEBUG: REQ type | positionStop
```


**Explorer Output:**
``` javascript
{
  "success": false,
  "error": "The device is not registered on the server"
}
```

**Comment by al3x1s** [comment]
I can go ahead with this solution in my own project, adding some validations, but don't know if these changes going to crash your own webpage because your webpage works without these lines

**Comment by tananaev** [comment]
I see the problem now. API call expects JSON object as payload, not POST parameters.

**Comment by al3x1s** [comment]
Yup, that was
now it works with this code


``` javascript
jQuery.ajax({
    type: "POST",
    url: "http://url:8082/api/command/send",
    dataType: "text",
    data: JSON.stringify({
        deviceId: 2,
        type: "imei"
    }),
    success: function (res) {
    	console.log("done");
    	console.log(res);    
    }
});
```

**but i got this warn output:** (this is not the error before, because I already checked that I have the correct data, deviceId and type)

```
2015-07-27 18:49:13 DEBUG: [70728777: 5007 > 66.201.160.70]
2015-07-27 18:49:13  WARN: unsupported message type: class java.lang.String - IllegalArgumentException (...)
2015-07-27 18:49:13  WARN: [70728777] error - unsupported message type: class java.lang.String - IllegalArgumentException (...)
2015-07-27 18:49:13  INFO: [70728777] disconnected
```

**Comment by tananaev** [comment]
What protocol do you have on port 5007? I am in the process of testing command, so there might be some issues.

**Comment by al3x1s** [comment]
Totem Protocol, but I already added the respective commands like gps103 commands

**Comment by tananaev** [comment]
I guess there is some problem with the code you've added. I have tested GPS103 and it doesn't give this error.

**Comment by al3x1s** [comment]
This is what I did

https://github.com/al3x1s/traccar/commit/526ec985c8d48d588511bddff22eaee53f4bdfc1

**Comment by al3x1s** [comment]
I added a test file and doesn't give an error

```
Running org.traccar.protocol.TotemProtocolEncoderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
```

and I have been putting Logs and the error appears after this return, I have printed **encodeCommand((Command) msg)** and it returned what I want ("*000000,801#")

**BaseProtocolEncoder.java**
``` java
 @Override
    protected Object encode(ChannelHandlerContext ctx, Channel channel, Object msg) throws Exception {
        
        if (msg instanceof Command) {
            //Error got after this return
            return encodeCommand((Command) msg);
        }
        
        return msg;
    }
```

**Comment by tananaev** [comment]
You haven't added `StringEncoder` to the pipeline.

**Comment by al3x1s** [comment]
you answer is totally and absolutely right haha 
it works like a charm

but is only one-way communication?

I mean, I sent a command to get the device imei, but it just send the command line

**Comment by tananaev** [comment]
Please send a pull request when you finish to integrate it into the main Traccar branch. Thanks

**Comment by al3x1s** [comment]
Done!, thanks Anton
