### ISSUE TITLE
traccar server is not starting

### ISSUE THREAD

**Issue by lingareddyg** [tananaev/traccar#1318]
Traccar server is not starting..showing error like below in linux

<pre>STATUS | wrapper  | 2015/07/29 06:18:56 | --&gt; Wrapper Started as Daemon
STATUS | wrapper  | 2015/07/29 06:18:56 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/07/29 06:18:56 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/07/29 06:18:56 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/07/29 06:18:56 | 
STATUS | wrapper  | 2015/07/29 06:18:57 | Launching a JVM...
INFO   | jvm 1    | 2015/07/29 06:18:57 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/07/29 06:18:58 | WrapperSimpleApp: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/07/29 06:18:58 | java.lang.NoClassDefFoundError: org.slf4j.ILoggerFactoryWrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.verifyImpl(Native Method)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.verify(J9VMInternals.java:72)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initialize(J9VMInternals.java:134)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.Class.forNameImpl(Native Method)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.Class.forName(Class.java:141)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at com.mchange.v2.log.MLog.findByClassnames(MLog.java:143)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at com.mchange.v2.log.MLog.refreshConfig(MLog.java:73)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at com.mchange.v2.log.MLog.&lt;clinit&gt;(MLog.java:51)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initializeImpl(Native Method)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at com.mchange.v2.naming.JavaBeanReferenceMaker.&lt;clinit&gt;(JavaBeanReferenceMaker.java:51)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initializeImpl(Native Method)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at com.mchange.v2.c3p0.impl.PoolBackedDataSourceBase.&lt;clinit&gt;(PoolBackedDataSourceBase.java:263)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initializeImpl(Native Method)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initialize(J9VMInternals.java:200)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initialize(J9VMInternals.java:167)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initialize(J9VMInternals.java:167)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.J9VMInternals.initialize(J9VMInternals.java:167)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at org.traccar.database.DataManager.initDatabase(DataManager.java:103)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at org.traccar.database.DataManager.&lt;init&gt;(DataManager.java:61)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at org.traccar.Context.init(Context.java:92)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at org.traccar.Main.main(Main.java:26)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.reflect.Method.invoke(Method.java:611)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.Thread.run(Thread.java:738)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | Caused by: java.lang.ClassNotFoundException: org.slf4j.ILoggerFactoryWrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:434)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:660)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:358)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:626)WrapperSimpleApp Error: 
INFO   | jvm 1    | 2015/07/29 06:18:58 | 	... 29 moreWrapperSimpleApp Error: 
STATUS | wrapper  | 2015/07/29 06:19:00 | &lt;-- Wrapper Stopped
</pre>

**Comment by tananaev** [comment]
Are you using official Traccar release? Looks like you are missing some libraries.

**Comment by lingareddyg** [comment]
Hi,
It is working in windows system.

**Comment by tananaev** [comment]
You still haven't answered my question. What version are you using? If you install official release, all libraries are included. If you compile from source code, libraries are downloaded automatically as a part of build process and should be under `lib` folder in the output.

**Comment by lingareddyg** [comment]
i downloaded from www.traccar.org site. version is 3.0

**Comment by tananaev** [comment]
OK, if you downloaded an official release it should work. What version of Java are you using? You can check using following command:

<pre>java -version</pre>

**Comment by tananaev** [comment]
Version 6 should be enough. Note that starting from next release, the minimum version would be 7.

Are you using default web interface as well? No modification at all?

**Comment by lingareddyg** [comment]
no modifications are done, using default web interface only.

**Comment by tananaev** [comment]
I suspect the problem is that you have `slf4j` library installed somewhere on in your system (maybe old version or some components are missing) and Traccar is picking that up from standard classpath and failing to start.

**Comment by tananaev** [comment]
I guess you need to provide `slf4j-nop.jar` or `slf4j-simple.jar` somehow.

**Comment by tananaev** [comment]
Try to use following JAR file (it include all the dependencies):

https://www.dropbox.com/s/myt68q5u7fiz49r/tracker-server-jar-with-dependencies.jar?dl=0

**Comment by lingareddyg** [comment]
where should include this jar file..

**Comment by tananaev** [comment]
In the default Traccar installation path:
<pre>/opt/traccar/</pre>

**Comment by lingareddyg** [comment]
Now i am getting below error...

STATUS | wrapper  | 2015/07/29 07:29:07 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/07/29 07:29:07 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/07/29 07:29:07 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/07/29 07:29:07 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/07/29 07:29:07 | 
STATUS | wrapper  | 2015/07/29 07:29:07 | Launching a JVM...
INFO   | jvm 1    | 2015/07/29 07:29:07 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/07/29 07:29:08 | WrapperSimpleApp Error: Class org.traccar.Main found but could not be initialized: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/traccar/Main, offset=6
STATUS | wrapper  | 2015/07/29 07:29:10 | <-- Wrapper Stopped

**Comment by tananaev** [comment]
OK, now the problem is that I gave you developer build of next version which requires Java version 7.

**Comment by lingareddyg** [comment]
Its working..Thanks a Lot...
can know the distance of particular date with this traccar.

**Comment by tananaev** [comment]
Currently there is no option to calculate a distance in Traccar. This feature is in plans for one of the future versions.

**Comment by lingareddyg** [comment]
Hi,
In database, device time is not in Indian time, how can set to IST.
but in web interface it is showing IST time only.

**Comment by tananaev** [comment]
In the database the timestamp should be stored in UTC format. If you need local time, you can convert it in the SQL query (see Traccar config file).

**Comment by eduardocorar** [comment]
I´m using Windows 8.1  64 bits. I did download the proper traccar server version. The installation was OK.
After restarting, the program did not start.
Can I run it manually? How?

**Comment by tananaev** [comment]
@eduardocorar, you don't need to run it manually. I have tested Traccar on Windows 8.1 64 bits and it worked perfectly. Please check `wrapper.log` for error messages.

**Comment by eduardocorar** [comment]
Wrapper.log shows:
STATUS | wrapperm | 2015/08/11 19:05:12 | Traccar service installed.
STATUS | wrapper  | 2015/08/11 19:06:28 | --> Wrapper Started as Service
STATUS | wrapper  | 2015/08/11 19:06:28 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/08/11 19:06:28 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/08/11 19:06:28 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/08/11 19:06:28 | 
STATUS | wrapper  | 2015/08/11 19:06:29 | Launching a JVM...
INFO   | jvm 1    | 2015/08/11 19:06:35 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/08/11 19:06:40 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/08/11 19:06:45 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/08/11 19:06:48 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hgeby99b8jnvtd1tlcm4s|2f12d5d0, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hgeby99b8jnvtd1tlcm4s|2f12d5d0, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:C:\Program Files (x86)\Traccar\data\database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2015/08/11 19:06:52 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @21833ms
INFO   | jvm 1    | 2015/08/11 19:06:53 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.13.v20150730
INFO   | jvm 1    | 2015/08/11 19:06:54 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@4b2b5228{/api,null,AVAILABLE}
INFO   | jvm 1    | 2015/08/11 19:06:54 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@446b9a1a{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2015/08/11 19:06:54 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @23130ms

**Comment by tananaev** [comment]
Looks like it's running.

**Comment by eduardocorar** [comment]
Yes, it´s running. I can see the device using demo mode (port 5005). I cannot see it at localhost:8082.
Which port number I need to configure at device? I tried both 5005 and 8082 with no success.

**Comment by tananaev** [comment]
For the device (assuming Traccar Client) you need to use port 5005. Are you sure ports are visible from internet? Try to check it here: http://www.tananaev.com/port.html.

**Comment by eduardocorar** [comment]
The port is closed...

**Comment by tananaev** [comment]
Are you sure you have a public IP address? If yes, there must be some problem with firewall or router.

**Comment by eduardocorar** [comment]
The problem was on the Firewall. Thanks.
But, now, the device is recognized just in DEMO (demo.traccar.org)
No communication when using localhost:8082

**Comment by tananaev** [comment]
What address and port did you put into the app?

**Comment by eduardocorar** [comment]
adress localhost:8082
porrt 5050

**Comment by eduardocorar** [comment]
address

**Comment by tananaev** [comment]
It is incorrect. You should use your public IP address as address. Remove 8082 from address string as well as it's a port number.

Port should be 5005 (not 5050).

**Comment by eduardocorar** [comment]
Thanks. Now it's working fine
Em 12/08/2015 23:54, "Anton Tananaev" <notifications@github.com> escreveu:

**Comment by sureshandimenu** [comment]
hell sir i installed traccar new version but its not working from out side, i tried to check required ports status from outside ports are opened but not working but locally its opening traccar app but when i try to add my ios device which has traccar client. its not recognizing device please ...pls help me on it.

**Comment by tananaev** [comment]
@sureshandimenu, please create a separate issue.

**Comment by naveenreddy531** [comment]
I am working with your traccar web ui source code in netbeans guided from the website http://traccar.litvak.su/installation.html and every thing is working fine after the process of ATTACH DEBUGGER from DEBUG menu and i am getting traccar web ui in my default browser with url " http://127.0.0.1:8888/traccar.html " and i have added an android client with which is working fine with your demo.traccar.org but when i want to see my device in this web ui it is not visible . In my mobile client LOCATION UPDATE is coming and after few seconds it is visible SENT FAILED with mobile client app ip address of my local ip and server as 5055 and preferred ALL THREE PROVIDERS one by one and my traccar web ui log is showing" Log is not available. Looked at D:\NetBeansProjects\traccar-web\logs\tracker-server.log, " . In the downloaded source code i have not seen any traccar-server.log f ile . So can you please help me how to execute this with my device

**Comment by vinaydd** [comment]
How to check device status weather my device work to send location or not ?

**Comment by tananaev** [comment]
@vinaydd, please don't comment on old closed threads. Also, for general questions you should use forum. And before posting anything you should check troubleshooting guide.
