### ISSUE TITLE
NullPointerException on Web Interface

### ISSUE THREAD

**Issue by bernamaxim** [tananaev/traccar#1324]
I found this problem.

![untitled](https://cloud.githubusercontent.com/assets/2969479/8980829/ad9c6b0e-36dd-11e5-8ee2-5ef41ad6e61a.png)

I found this error before null pointer when inspected element the following:

![untitled2](https://cloud.githubusercontent.com/assets/2969479/8981096/d5ead7f6-36df-11e5-8b60-bbba7f435701.png)

When I deleted cookies and site data and refresh, it can display login page. When show history, I cannot find speed, course and address. And I cannot pointing location of unit with double click on unit.

![untitled3](https://cloud.githubusercontent.com/assets/2969479/8982114/2a39f014-36e8-11e5-99f0-79f6b99d1108.png)

Thanks for advance

**Comment by tananaev** [comment]
What server version are you using?

**Comment by bernamaxim** [comment]
The latest commit, build from source.

**Comment by tananaev** [comment]
Are you sure you updated both back-end and web interface?

**Comment by bernamaxim** [comment]
of course. It's updated.

**Comment by tananaev** [comment]
Looks like you have incorrect speed unit value in either `server` or `user` table.

**Comment by higomatos** [comment]
Correction for this bug is here
https://github.com/tananaev/traccar/pull/1339

2015-08-07 1:49 GMT-03:00 Anton Tananaev <notifications@github.com>:

> Looks like you have incorrect speed unit value in either server or user
> table.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1324#issuecomment-128595029>.
>



-- 
Higo Soares Matos
86-9934-3237 - TIM
86-8882-3796 - OI

**Comment by bernamaxim** [comment]
thanks @higomatos
