### ISSUE TITLE
Megastek GVT-800 error decode

### ISSUE THREAD

**Issue by sanayaCorp** [tananaev/traccar#1334]
I tried to connect my gps device is Megastek GVT-800 with servers located in vps, but why always provide information that String index out of range: -19 – StringIndexOutOfBoundsException (… <MegastekProtocolDecoder.java:166 <ExtendedObjectDecoder.java:39 <…)

This is for the information of traccar server error log

<pre>2015-08-04 18:02:55 INFO: [9084C848] disconnected
2015-08-04 18:03:29 INFO: [0722E24E] connected
2015-08-04 18:03:31 DEBUG: [0722E24E: 5024 < 223.255.230.34] HEX: 244d47563030322c3031333737373030373533363433342c2c522c3031303131342c3030303035372c562c303030302e303030302c4e2c30303030302e303030302c452c30302c30302c30302c39392e392c302e3030302c302e30302c302e302c38302e3236332c3531302c38392c323334322c303330422c2c303030302c303030302c3230302c39362c302c202c202c2c2c2c54696d65723b210d0a
2015-08-04 18:03:31 WARN: String index out of range: -19 – StringIndexOutOfBoundsException (… < MegastekProtocolDecoder.java:166 < ExtendedObjectDecoder.java:39 < …)
2015-08-04 18:03:31 WARN: [0722E24E] error – String index out of range: -19 – StringIndexOutOfBoundsException (… < MegastekProtocolDecoder.java:166 < ExtendedObjectDecoder.java:39 < …)
2015-08-04 18:03:31 INFO: [0722E24E] disconnected</pre>

while for the format uploading gprs from documentation megastek gvt-800 is

<pre>&lt;data head&gt;&lt;protocol version&gt;,&lt;device IMEI&gt;,&lt;device name&gt;,&lt;GPRS real-time/stored data flag&gt;,&lt;date&gt;,&lt;time&gt;,&lt;GPS fixed flag&gt;,&lt;latitude&gt;,&lt;N/S&gt;,&lt;longitude&gt;,&lt;W/E&gt;,&lt;used satellite number of BDS&gt;,&lt;used satellite number of GPS&gt;,&lt;used satellite number of GLONASS&gt;,&lt;HDOP&gt;,&lt;speed&gt;,&lt;course&gt;,&lt;altitude&gt;,&lt;mileage&gt;,&lt;MCC&gt;,&lt;MNC&gt;,&lt;LAC&gt;,&lt;Cell ID&gt;,&lt;GSM signal strength&gt;,&lt;digital input&gt;,&lt;digital output&gt;,&lt;analog input 1&gt;,&lt;analog input 2&gt;,&lt;analog input 3&gt;,&lt;temperature sensor 1&gt;,&lt;temperature sensor 2&gt;,&lt;RFID&gt;,&lt;external accessories status&gt;,&lt;battery level&gt;,&lt;alert event type&gt;;&lt;checksum&gt;&lt;data tail&gt;</pre>
If anyone can help solve my problem ?? Thanks before

**Comment by tananaev** [comment]
Looks like they changed message format. Can you please provide full documentation.

**Comment by sanayaCorp** [comment]
thanks for replay for my problem, this is the format for the documentation of the device gvt uploading gprs-800 Megastek
https://www.dropbox.com/s/q7aownb3n9d3ui9/GPRS%20Uploading%20Data.pdf?dl=0
and if needed a format command list
https://www.dropbox.com/s/foul2cciwfa1ken/Command%20List.pdf?dl=0

**Comment by tananaev** [comment]
It looks somewhat similar to current Megastek implementation, but some things are different. I have added it to my backlog of new protocols.

**Comment by sanayaCorp** [comment]
Yeah right tool gvt gps-800 is the latest series of Megastek, in fact I've made an attempt to create a new protocol, but it is still one of my current build. Maybe mr tananaev can help me provide a solution? GVT800ProtocolDecoder.java following listing:
public class GVT800ProtocolDecoder extends BaseProtocolDecoder {

    public GVT800ProtocolDecoder(GVT800Protocol protocol) {
        super(protocol);
    }
     
    private static final Pattern patternGPRMC = Pattern.compile(
            "\\$MGV002," +
            "(\\d{2})(\\d{2})(\\d{2})" +   // Date (DDMMYY)
            "(\\d{2})(\\d{2})(\\d{2})\\.\\d+," + // Time (HHMMSS.SSS)
            "[FL]," +                      // Flag GPS Fix Flags       
            "(\\d+)(\\d{2}\\.\\d+)," +     // Latitude (DDMM.MMMM)
            "([NS])," +                    // Flag Nort/South Indicator 
            "(\\d+)(\\d{2}\\.\\d+)," +     // Longitude (DDDMM.MMMM)
            "([WE])," +                    // Flag East/West Indicator
            "(\\d+\\.\\d+)?," +            // Speed
            "(\\d+\\.\\d+)?," +            // Course
            "[^\\*]+\\*[0-9a-fA-F]{2}");   // Checksum
    

    private static final Pattern patternSimple = Pattern.compile(
            "[FL]," +                      // Flag
            "([^,]*)," +                   // Alarm
            "imei:(\\d+)," +               // IMEI
            "(\\d+/?\\d*)?," +             // Satellites
            "(\\d+\\.\\d+)?," +            // Altitude
            "Battery=(\\d+)%,," +          // Battery
            "(\\d)?," +                    // Charger
            "(\\d+)?," +                   // MCC
            "(\\d+)?," +                   // MNC
            "(\\p{XDigit}{4},\\p{XDigit}{4});" + // Location code
            ".+");                         // Checksum

    private static final Pattern patternAlternative = Pattern.compile(
            "(\\d+)," +                    // MCC
            "(\\d+)," +                    // MNC
            "(\\p{XDigit}{4},\\p{XDigit}{4})," + // Location code
            "(\\d+)," +                    // GSM signal
            "(\\d+)," +                    // Battery
            "(\\d+)," +                    // Flags
            "(\\d+)," +                    // Inputs
            "(?:(\\d+),)?" +               // Outputs
            "(\\d\\.?\\d*)," +             // ADC 1
            "(?:(\\d\\.\\d{2})," +         // ADC 2
            "(\\d\\.\\d{2}),)?" +          // ADC 3
            "([^;]+);" +                   // Alarm
            ".*");                         // Checksum

    private boolean parseGPRMC(String gprmc, Position position) {
        
        // Parse message
        Matcher parser = patternGPRMC.matcher(gprmc);
        if (!parser.matches()) {
            return false;
        }

        int index = 1;

        // Date
        Calendar time = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
        time.clear();
        time.set(Calendar.DAY_OF_MONTH, Integer.valueOf(parser.group(index++)));
        time.set(Calendar.MONTH, Integer.valueOf(parser.group(index++)) - 1);
        time.set(Calendar.YEAR, 2000 + Integer.valueOf(parser.group(index++)));
        position.setTime(time.getTime()); 
        
        // Time
        time.set(Calendar.HOUR_OF_DAY, Integer.valueOf(parser.group(index++)));
        time.set(Calendar.MINUTE, Integer.valueOf(parser.group(index++)));
        time.set(Calendar.SECOND, Integer.valueOf(parser.group(index++)));

        // Validity
        position.setValid(parser.group(index++).compareTo("A") == 0);

        // Latitude
        Double latitude = Double.valueOf(parser.group(index++));
        latitude += Double.valueOf(parser.group(index++)) / 60;
        if (parser.group(index++).compareTo("S") == 0) latitude = -latitude;
        position.setLatitude(latitude);

        // Longitude
        Double longitude = Double.valueOf(parser.group(index++));
        longitude += Double.valueOf(parser.group(index++)) / 60;
        if (parser.group(index++).compareTo("W") == 0) longitude = -longitude;
        position.setLongitude(longitude);

        // Speed
        String speed = parser.group(index++);
        if (speed != null) {
            position.setSpeed(Double.valueOf(speed));
        }

        // Course
        String course = parser.group(index++);
        if (course != null) {
            position.setCourse(Double.valueOf(course));
        }              

        return true;
    }
    
    @Override
    protected Object decode(
            Channel channel, SocketAddress remoteAddress, Object msg)
            throws Exception {

        String sentence = (String) msg;

        // Detect type
        boolean simple = (sentence.charAt(3) == 'V');

        // Split message
        String id;
        String gprmc;
        String status;
        if (simple) {
            int beginIndex = sentence.indexOf(',') + 16;
            int endIndex = sentence.indexOf(',', beginIndex);
            id = sentence.substring(beginIndex, endIndex);
            
            beginIndex = 0;
            endIndex = sentence.indexOf(',', beginIndex);
            gprmc = sentence.substring(beginIndex, endIndex);
            
            beginIndex = endIndex + 1;
            endIndex = sentence.indexOf('E', beginIndex);
            status = sentence.substring(beginIndex, endIndex);
        } else {    
            int beginIndex = 24;
            int endIndex = sentence.indexOf(',', beginIndex);
            id = sentence.substring(beginIndex, endIndex).trim();
              
            beginIndex = 0;
            endIndex = sentence.indexOf(',', beginIndex);
            gprmc = sentence.substring(beginIndex, endIndex);
              
            beginIndex = endIndex + 1; 
            endIndex = sentence.indexOf('E', beginIndex);
            status = sentence.substring(beginIndex, endIndex);
        }
        // Create new position
        Position position = new Position();
        position.setProtocol(getProtocolName());

        // Parse location data
        if (!parseGPRMC(gprmc, position)) {
            return null;
        }
        
        if (simple) {

            // Parse status
            Matcher parser = patternSimple.matcher(status);
            if (!parser.matches()) {
                return null;
            }
            
            int index = 1;

            // Alarm
            position.set(Event.KEY_ALARM, parser.group(index++));

            // IMEI
            if (!identify(parser.group(index++), channel, null, false)) {
                if (!identify(id, channel)) {
                    return null;
                }
            }
            position.setDeviceId(getDeviceId());

            // Satellites
            position.set(Event.KEY_SATELLITES, parser.group(index++));

            // Altitude
            String altitude = parser.group(index++);
            if (altitude != null) {
                position.setAltitude(Double.valueOf(altitude));
            }

            // Battery
            position.set(Event.KEY_POWER, Double.valueOf(parser.group(index++)));

            // Charger
            String charger = parser.group(index++);
            if (charger != null) {
                position.set(Event.KEY_CHARGE, Integer.valueOf(charger) == 1);
            }

            position.set(Event.KEY_MCC, parser.group(index++));
            position.set(Event.KEY_MNC, parser.group(index++));
            position.set(Event.KEY_LAC, parser.group(index++));
            
        } else {

            // Parse status
            Matcher parser = patternAlternative.matcher(status);
            if (!parser.matches()) {
                return null;
            }
            
            int index = 1;

            if (!identify(id, channel)) {
                return null;
            }
            position.setDeviceId(getDeviceId());

            position.set(Event.KEY_MCC, parser.group(index++));
            position.set(Event.KEY_MNC, parser.group(index++));
            position.set(Event.KEY_LAC, parser.group(index++));
            position.set(Event.KEY_GSM, parser.group(index++));

            // Battery
            position.set(Event.KEY_BATTERY, Double.valueOf(parser.group(index++)));
            
            position.set(Event.KEY_FLAGS, parser.group(index++));
            position.set(Event.KEY_INPUT, parser.group(index++));
            position.set(Event.KEY_OUTPUT, parser.group(index++));
            position.set(Event.PREFIX_ADC + 1, parser.group(index++));
            position.set(Event.PREFIX_ADC + 2, parser.group(index++));
            position.set(Event.PREFIX_ADC + 3, parser.group(index++));
            position.set(Event.KEY_ALARM, parser.group(index++));
            
        }
        return position;
    }

}

and for the following GVT800ProtocolDecoderTest

public class GVT800ProtocolDecoderTest extends ProtocolDecoderTest {

    @Test
    public void testDecode() throws Exception {

        GVT800ProtocolDecoder decoder = new GVT800ProtocolDecoder(new GVT800Protocol());

        verify(decoder.decode(null, null,
                "$MGV002,013777007537283,,R,050815,134208,A,0609.7667,S,10650.3277,E,00,08,08,1.06,0.000,306.40,42.3,90.260,510,89,23FA,0061,11,0000,0000,216,100,0,23.50,24.00,,,87,Timer;!"));        
                
    }

}

and the following error

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec <<< FAILURE!
testDecode(org.traccar.protocol.GVT800ProtocolDecoderTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at org.traccar.helper.DecoderVerifier.verify(DecoderVerifier.java:47)
	at org.traccar.protocol.GVT800ProtocolDecoderTest.testDecode(GVT800ProtocolDecoderTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)

please tell me the solution, thanks in advance mr tananaev

**Comment by tananaev** [comment]
What does `simple` flag mean in your case? I think you need to take some simpler protocol as a base.

**Comment by sanayaCorp** [comment]
So if referring to the decode hex to ascii:
$MGV002,013777007537283,,R,050815,134208,A,0609.7667,S,10650.3277,E,00,08,08,1.06,0.000,306.40,42.3,90.260,510,89,23FA,0061,11,0000,0000,216,100,0,23.50,24.00,,,87,Timer;!
If I take the example of the implementation Megastek protocol decoder, then I should be able determines the device id, gprmc, and messages from the devices, but I am currently cutting a message to the difficulty is in accordance with the implementation of Megastek protocol decoder, could master any suggestion that more simple again

**Comment by tananaev** [comment]
I have implemented the protocol.

**Comment by sanayaCorp** [comment]
this sample decode hex to ascii from two device GVT-800 and thanks for answer with my problem.
https://www.dropbox.com/s/cdzd5gaqzyuzghi/documents-export-2015-08-05.zip?dl=0

**Comment by sm2x** [comment]
may I know what port should be set for Megastek GVT-800, my device is sending this
$MGV002,861508030357594,,R,080419,123015,A,1437.1384,N,12103.4945,E,00,10,09,0.66,0.000,95.05,84.3,161.352,515,02,4F0B,0C2B,18,00000000,0,,,,,,,,1-0,94,,Timer;!

**Comment by tananaev** [comment]
For Megastek you should use Megastek port. In future please don't comment on old closed threads. Also, for questions we have forum.

**Comment by sm2x** [comment]
I thought my post is related to this thread sorry, I am now posting my question on the forum
