### ISSUE TITLE
new send command

### ISSUE THREAD

**Issue by and12345** [tananaev/traccar#1344]
Hi Anton,

Just see your work today and been upgrade to 3.1.
I see there's a new send command on traccar, could you inform us what device command already supported here ? 
And what we can do to help send command for another device, is there any documentation to add new send command for another device ?

**Comment by maxicabanillas78** [comment]
gps103 port 5001 , gt06 port 5023

**Comment by tananaev** [comment]
You can find all the information about 3.1 release here (including list of supported commands and protocols):

https://www.traccar.org/blog/traccar-3-1/

There is no documentation on how to add commands, but it's pretty straight forward. Just look at the code and follow the same pattern.

**Comment by and12345** [comment]
Hi Anton,

Could you please point us what files need to be update, and also could you please support send command for PT502.

Thank you

**Comment by tananaev** [comment]
To implement commands you need to update `XxxProtocol.java` file and add `XxxProtocolEncoder.java` to encode commands (where `Xxx` is your protocol name).

**Comment by marcuscarvalho6** [comment]
Anton , you have forecast when will the command to Suntech devices?

**Comment by tananaev** [comment]
@marcuscarvalho6, Traccar already support commands for Suntech protocol.

**Comment by marcuscarvalho6** [comment]
If he seems to be misconfigured , or at least for some versions . When firing the command to the device by the system nothing happens , and the command summarizes engine be returning the following message: "Command engineResume is not supported in protocol suntech " .

The commands provided on the provider website are as follows:

Enable output 1
SA200CMD ; XXXX ; 02 ; Enable1
Disable Output 1
SA200CMD ; XXXX ; 02 ; Disable1

Where XXXX should be replaced by device IMEI .

**Comment by marcuscarvalho6** [comment]
In the configuration file is set as follows:

"CMD ; { % s } ; 02 ; Enable1 \ r "
"CMD ; { % s } ; 02 ; Disable1 \ n"

**Comment by tananaev** [comment]
@marcuscarvalho6, so command format is specific to device type?

**Comment by marcuscarvalho6** [comment]
Not according to the manufacturer's own website , these are the correct commands for all devices .

There are also other commands , such as the order position.

SA200CMD;XXXXX,02;StatusReq

But this specifically command only works in versions :

207B = ST215 E / I
208B = ST215LC
249 = ST215W
212 = ST240

http://www.stdobrasil.com.br/site/suporte/

**Comment by tananaev** [comment]
I have changed the format.

**Comment by marcuscarvalho6** [comment]
When will the version with the modifications to download the .run ?

2015-08-14 0:05 GMT-03:00 Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
I can provide a new `jar` file if you want, but I don't plan to release a new version for at least a month.

**Comment by marcuscarvalho6** [comment]
I've been seeing on the site on how to run the traccar patir the
source code, but I think it is desatializado .
I built the project with dependencies , the case remains the same?

java -jar traccar -server- with- dependences.jar "config.xml "

When you could provide a tutorial updated to version 3.x ?


2015-08-15 5:09 GMT-03:00 Anton Tananaev <notifications@github.com>:

**Comment by marcuscarvalho6** [comment]
I've been seeing on the site on how to run the traccar patir the
source code, but I think it is out of date .
I built the project with dependencies , the case remains the same?

java -jar traccar -server- with- dependences.jar "config.xml "

When you could provide a tutorial updated to version 3.x ?


2015-08-15 11:01 GMT-03:00 Vinícius Carvalho <marcuscarvalho6@gmail.com>:

**Comment by tananaev** [comment]
It hasn't changed. You can run the server manually using the command you mentioned.
