### ISSUE TITLE
Stop engine command GPS103 doesn't work

### ISSUE THREAD

**Issue by Jeferex** [tananaev/traccar#1345]
Anton,

I've been testing some GPS103 devices in http://dev.traccar.org and the stop/resume engine doesn't work. I have the manufacturer app installed in my computer and I sniffed the commands it sends. When I send STOP command, it sends in HEX:

2a:2a:2c:69:6d:65:69:3a:33:35:39:37:31:30:30:34:38:37:33:30:33:33:38:2c:4a

And when I send RESUME command, it sends this:

2a:2a:2c:69:6d:65:69:3a:33:35:39:37:31:30:30:34:38:37:33:30:33:33:38:2c:4b

I see there is no semicolon at the end like in your code, maybe that's why it doesn't work.

Thanks.

**Comment by tananaev** [comment]
Can you please provide network packets log (pcap?).

**Comment by tananaev** [comment]
I have updated http://dev.traccar.org/. Please try now and see if it works.

**Comment by Jeferex** [comment]
Anton, I just tested sending commands some minutes ago. I guess now it works. Can you check your logs? The IMEI is 359710047648192.

I can send you the manufacturer app pcap file if you need it.

Thanks

**Comment by tananaev** [comment]
Well, I have already checked that it sends commands without semi-colon, but does it work with a real device? Does device accept the command this way?

As for pcap, it would be great if you could provide the file. You can send to my email (address is in profile). Thanks.

**Comment by Jeferex** [comment]
Anton, I just tried sending commands in DEV Traccar but engineStop command doesn't work. However, resume command does work and Fix positions command works too. It is weird.

**Comment by Jeferex** [comment]
Now. I know. The ENGINE STOP COMMAND has a semicolon at the end while the others don't.

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gps103ProtocolEncoder.java

Check it out!

**Comment by tananaev** [comment]
Fixed now.

**Comment by Jeferex** [comment]
Now, everything works as expected. Thanks Anton. Great work.

**Comment by tananaev** [comment]
Thanks for feedback.
