### ISSUE TITLE
How i can save google location(exact location of device) in position address field?

### ISSUE THREAD

**Issue by surendrakumar1992** [tananaev/traccar#1368]
Hello @tananaev 
Currently i am using traccar and it's working fine. I have issue regarding address of device which is not exact location of google map. There is any way to save google location in position table(address coloum). 
Thanks in advance :)

**Comment by tananaev** [comment]
There are several options available for address resolution:

https://www.traccar.org/reverse-geocoding/

**Comment by surendrakumar1992** [comment]
@tananaev 
Thank you so much buddy... :+1:
