### ISSUE TITLE
traccar new web interface builds

### ISSUE THREAD

**Issue by ginei11** [tananaev/traccar#1371]
how can i do build de new traccar web interface in netbeans?
https://github.com/tananaev/traccar-web

**Comment by vitalidze** [comment]
If you are talking about my web UI mod then official instructions for netbeans are located here: http://traccar.litvak.su/ide/netbeans.html

**Comment by ginei11** [comment]
I want the ui version 3.0
this web ui:
http://demo.traccar.org/

**Comment by vitalidze** [comment]
Then looks like these are the only instructions available for now: https://github.com/tananaev/traccar#netbeans-recommended I guess any instructions for importing maven project should work.

**Comment by ginei11** [comment]
thanks,
now i download traccar web ui of: http://traccar.litvak.su/
and I am getting the following error:
"Remote procedure call error"
I think it's the connection to the database
How do I connect my database in mysql?

**Comment by vitalidze** [comment]
First of all please do not post questions related to my web UI mod in this tracker. It has it's own issue tracker here: https://github.com/vitalidze/traccar-web/issues

Sounds like a database connection issue. You should edit 'debug' section in `persistence.xml` file https://github.com/vitalidze/traccar-web/blob/aeb3f770775c530d38be8272d8c3bd6396eebd1d/src/main/resources/META-INF/persistence.xml

Also you need to check out log for error messages.

**Comment by tananaev** [comment]
If you want to use Traccar version 3.0 web interface, you don't need to compile it. It's written in pure JavaScript, so no compilation required unless you want to minimize it.

**Comment by Kasimir61** [comment]
Vitaly, is there a new Update to download – my last Version has some Errors and i dont know, if there is another Update ??

 

Regards Sven

 

Sven Krzizek
Birkenwerder Str. 5
16562 Bergfelde

 

 

fon:  +49 03303 5392885-0

fax :  +49 03303 5392885-9


funk:  +49 (0)157 851 155 77

email:  <mailto:info@service61.de> info@service61.de

 

Von: Vitaly Litvak [mailto:notifications@github.com] 
Gesendet: Montag, 24. August 2015 18:50
An: tananaev/traccar <traccar@noreply.github.com>
Betreff: Re: [traccar] traccar new web interface builds (#1371)

 

First of all please do not post questions related to my web UI mod in this tracker. It has it's own issue tracker here: https://github.com/vitalidze/traccar-web/issues

Sounds like a database connection issue. You should edit 'debug' section in persistence.xml file https://github.com/vitalidze/traccar-web/blob/aeb3f770775c530d38be8272d8c3bd6396eebd1d/src/main/resources/META-INF/persistence.xml

Also you need to check out log for error messages.
