### ISSUE TITLE
port error

### ISSUE THREAD

**Issue by vzoltan** [tananaev/traccar#1373]
hi, just installed v31 into a new empy db and i get this error:

<pre>STATUS | wrapper  | 2015/08/25 21:40:54 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/08/25 21:40:54 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/08/25 21:40:54 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/08/25 21:40:54 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/08/25 21:40:54 | 
STATUS | wrapper  | 2015/08/25 21:40:55 | Launching a JVM...
INFO   | jvm 1    | 2015/08/25 21:40:55 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/08/25 21:40:56 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/08/25 21:40:56 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/08/25 21:40:56 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9bsemebdrrsdc7|7d12855, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kfsx9bsemebdrrsdc7|7d12855, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2015/08/25 21:40:57 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @2351ms
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp: 
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:5050
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.traccar.TrackerServer.start(TrackerServer.java:131)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.traccar.ServerManager.start(ServerManager.java:75)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: Caused by: java.net.BindException: Address already in use
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at sun.nio.ch.Net.bind0(Native Method)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at sun.nio.ch.Net.bind(Net.java:445)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at sun.nio.ch.Net.bind(Net.java:437)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2015/08/25 21:40:58 | WrapperSimpleApp Error: 	... 1 more
STATUS | wrapper  | 2015/08/25 21:41:01 | <-- Wrapper Stopped</pre>

why is it trying to use port 5050? (that is used by my couchpotato server)
where can i change it?

thank you.

**Comment by vzoltan** [comment]
i put CP to other port, then it tried to used that "new" port.

**Comment by tananaev** [comment]
You can change ports in the config file:

https://www.traccar.org/configuration-file/

**Comment by vzoltan** [comment]
Thanks, but i dnt know what port should i change, because if i change cp's 5050 port to a "random" port, then i got the same erro in the wrapper log, only with that "random" port that cp is using.

Az iPademről küldve

2015. aug. 25. dátummal, 23:13 időpontban Anton Tananaev <notifications@github.com> írta:

**Comment by tananaev** [comment]
What was the random port? By default Traccar uses port 8082 and ports 50xx.

**Comment by vzoltan** [comment]
thanks,
i just removed the unused protocols from the config files (incl. 5050) now it starts.
sorry :) and thanks
