### ISSUE TITLE
Blank web page (no login prompt)

### ISSUE THREAD

**Issue by brianharriscollins** [tananaev/traccar#1374]
Successfully installed TRACCAR Windows 64 (startup logs attached), when I go to localhost:8082, I get this JS error. Did I miss something on install?

![image](https://cloud.githubusercontent.com/assets/9937429/9480401/0c85cb08-4b40-11e5-90c2-12893d2d19d9.png)

LOG
<pre>STATUS | wrapperm | 2015/08/25 21:10:01 | Traccar service installed.
STATUS | wrapper  | 2015/08/25 21:11:27 | --> Wrapper Started as Service
STATUS | wrapper  | 2015/08/25 21:11:27 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/08/25 21:11:27 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/08/25 21:11:27 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/08/25 21:11:27 | 
STATUS | wrapper  | 2015/08/25 21:11:27 | Launching a JVM...
INFO   | jvm 1    | 2015/08/25 21:11:29 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/08/25 21:11:31 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/08/25 21:11:34 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/08/25 21:11:35 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 31o1bi9bshuvwe1yqxl4g|78e112dd, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 31o1bi9bshuvwe1yqxl4g|78e112dd, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:C:\Program Files\Traccar\data\database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2015/08/25 21:11:39 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @12124ms
INFO   | jvm 1    | 2015/08/25 21:11:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.13.v20150730
INFO   | jvm 1    | 2015/08/25 21:11:42 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@34be3631{/api,null,AVAILABLE}
INFO   | jvm 1    | 2015/08/25 21:11:42 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@147d2d14{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2015/08/25 21:11:42 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @14488ms</pre>

**Comment by tananaev** [comment]
it looks like ExtJS library is missing. Possibly Internet access issue?

**Comment by brianharriscollins** [comment]
should the library be local or is the code going out and bringing it in (which may be a setting for IE/browser?)

**Comment by tananaev** [comment]
It is retrieved from CDN (cdnjs.cloudflare.com).

**Comment by brianharriscollins** [comment]
security settings in IE - all solved, thnks!


On Tue, Aug 25, 2015 at 3:59 PM, Anton Tananaev <notifications@github.com>
wrote:

> It is retrieved from CDN (cdnjs.cloudflare.com).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1374#issuecomment-134754266>.
>



-- 
Brian Collins
Chief Operating Officer, int*terra*
brian.collins@intterragroup.com
http://youtu.be/DVPOYjhkBEo
*719-310-6041*
*www.intterragroup.com* <http://www.intterragroup.com/>
