### ISSUE TITLE
Speed unit should be rounded to 2 decimals only

### ISSUE THREAD

**Issue by Jeferex** [tananaev/traccar#1375]
When converting speed to km/h, it shows a lot of decimals. It should be 2 decimails only.

**Comment by tananaev** [comment]
It is already fixed in the source code. Fix will be available with the next release.

**Comment by Jeferex** [comment]
I am using dev.traccar.org. Is it fixed there?

**Comment by tananaev** [comment]
I would not rely on this. I update `dev` server only when I need to test something. It doesn't necessarily run a build from latest source code. In fact, it can be somtimes older than the main `demo` server.

**Comment by Jeferex** [comment]
Ok. I thought It was updated with the latest source code. It is good to know that.

Thanks.
