### ISSUE TITLE
Какой web сервер использовать?

### ISSUE THREAD

**Issue by edgiru** [tananaev/traccar#1378]
Добрый день Антон. Подскажите нужен ли для traccar web сервер? или он уже содержит в себе его?
читал Вашу статью на хабре почему то в песочнице она. У Вас написано что вы используете ExtJS и Jetty или вы уже перешли на Google Web Toolkit с библиотекой Smart GWT как и планировали?

**Comment by tananaev** [comment]
Нет, traccar-web не нужен. Новый веб интерфейс и сервер теперь в одном репозитории.

Вы читали очень старую статью. Изначально использовал ExtJS для очень простого веб интерфейса. Потом перешел на GWT и написал более продвинутый интерфейс. Потом (недавно) перешел обратно на ExtJS (и переписал всю функциональность что была на GWT).
