### ISSUE TITLE
Export tracks as gpx

### ISSUE THREAD

**Issue by korjavin** [tananaev/traccar#1382]
Hello,
I have to work on my tracks, calculate distance and other values.
I can do it with other services, but how can I get gpx track?

**Comment by tananaev** [comment]
Currently Traccar doesn't supported exporting. It's in plans.

For now I guess you can manually extract data from the database.

**Comment by vitalidze** [comment]
FYI, my [web UI mod](http://traccar.litvak.su/features/) has a function to export [archive to GPX](http://traccar.litvak.su/features/archive-export.html) as well as the distance calculation implemented as a column in archive with total distance at the bottom.

**Comment by korjavin** [comment]
wow, nice, i'll take a look
