### ISSUE TITLE
Raw posted data from supported devices required

### ISSUE THREAD

**Issue by openqubit** [tananaev/traccar#1384]
Hello. I am trying to create a web page embeddedable realtime map for my portable device connected to traccar and i can't seem to find any format for raw data posted from any of the supported devices. Does the GPRMC push from the device contain ip address of the device? 

A generic gpsobject for TK102  can be see here https://github.com/fvdm/nodejs-tk102#events

**Comment by tananaev** [comment]
What GPRMC push are you talking about? Please provide more details on what you are trying to do and what you need.

**Comment by openqubit** [comment]
I am trying to setup a node js server to process posted data from the server.  I am trying to find out whether the posted data contains the ip address of the device as well.

**Comment by tananaev** [comment]
You can forward data from Traccar to your server using `WebDataHandler` class. Currently it doesn't support device IP address reporting, but it should be easy to include it (device IP address is already available in the `Position` object).

**Comment by openqubit** [comment]
Thanks @tananaev
