### ISSUE TITLE
Error create server

### ISSUE THREAD

**Issue by douglaspedro** [tananaev/traccar#1387]
Hello guys. I'm creating a new server with 10 devices. I do with h2 or sql ? This is the error log for SQL. Thanks.

<pre>STATUS | wrapper  | 2015/08/31 18:03:58 | --> Wrapper Started as Service
STATUS | wrapper  | 2015/08/31 18:03:58 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/08/31 18:03:58 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/08/31 18:03:58 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/08/31 18:03:58 | 
STATUS | wrapper  | 2015/08/31 18:03:59 | Launching a JVM...
INFO   | jvm 1    | 2015/08/31 18:03:59 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/08/31 18:04:01 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/08/31 18:04:01 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/08/31 18:04:02 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1b60os89b1128clczsb3gf|33506783, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.microsoft.sqlserver.jdbc.SQLServerDriver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1b60os89b1128clczsb3gf|33506783, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:sqlserver://172.16.1.18;instanceName=SQLEXPRESS;databaseName=traccar;, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2015/08/31 18:04:02 | [C3P0PooledConnectionPoolManager[identityToken->1b60os89b1128clczsb3gf|33506783]-HelperThread-#2] WARN com.mchange.v2.c3p0.DriverManagerDataSource - Could not load driverClass com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2015/08/31 18:04:02 | java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.net.URLClassLoader.findClass(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.lang.Class.forName0(Native Method)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.lang.Class.forName(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.DriverManagerDataSource.ensureDriverLoaded(DriverManagerDataSource.java:143)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:173)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
INFO   | jvm 1    | 2015/08/31 18:04:02 | [C3P0PooledConnectionPoolManager[identityToken->1b60os89b1128clczsb3gf|33506783]-HelperThread-#0] WARN com.mchange.v2.c3p0.DriverManagerDataSource - Could not load driverClass com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2015/08/31 18:04:02 | java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.net.URLClassLoader.findClass(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.lang.ClassLoader.loadClass(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.lang.Class.forName0(Native Method)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at java.lang.Class.forName(Unknown Source)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.DriverManagerDataSource.ensureDriverLoaded(DriverManagerDataSource.java:143)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:173)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
INFO   | jvm 1    | 2015/08/31 18:04:02 | 	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)</pre>

**Comment by tananaev** [comment]
Looks like you are trying to use MS SQL server, but you are missing JDBC driver.

Details on how to integrate Traccar with MS SQL can be found here:
https://www.traccar.org/ms-sql/

Also, please don't post huge log files like that. Either put only one fragment (it makes sense in this case as you get same error over and over) or upload log file somewhere (e.g. DropBox) if you really want to show whole file.

**Comment by douglaspedro** [comment]
Sorry.
I see, how create JDBC driver?
Thanks.

Date: Mon, 31 Aug 2015 14:28:08 -0700

**Comment by tananaev** [comment]
You need to download it from the database vendor website.

**Comment by douglaspedro** [comment]
Thanks Anton.
You are the man!

Date: Tue, 1 Sep 2015 14:47:25 -0700
