### ISSUE TITLE
Installation doesn't work on linux 64 Centos

### ISSUE THREAD

**Issue by fperroud** [tananaev/traccar#1389]
I tried to install Traccar server on linux 64 Centox, i have downloaded ZIP and unzip in directory /opt/traccar, i connect to server as ROOT, when i want to start install by typing : sudo ./traccar.run, i have this error :

root@server [/opt/traccar]# sudo ./traccar.run
Verifying archive integrity... All good.
Uncompressing traccar  100%  
./traccar.run: line 488: ./setup.sh: Permission non accordée

What is it ?

Thanks

**Comment by tananaev** [comment]
You shouldn't create `/opt/traccar` yourself. It is created by the installer, and because you did it yourself I guess there are some conflicts.

I suggest to remove it, unzip downloaded file to some other directory and run installer (`traccar.run`) after that.

**Comment by fperroud** [comment]
no it doesn't work, same error when i launch traccar.run in another directory after remove opt/traccar

**Comment by tananaev** [comment]
I guess `setup.sh` is not executable for some reason. Try to extract files from the installer manually:
<pre>./traccar.run --noexec</pre>

Then add executable flag to the file:
<pre>chmod +x setup.sh</pre>

And then run it manually.

**Comment by fperroud** [comment]
where is files extracted ? when i launch :
./traccar.run --noexec
i don't see the files

**Comment by tananaev** [comment]
Try following command (it will extract it into the current directory):
<pre>./traccar.run --current --noexec</pre>

**Comment by fperroud** [comment]
Unrecognized flag : --current

**Comment by tananaev** [comment]
Try `--notemp` flag instead of `--current`.

**Comment by fperroud** [comment]
I have resolved the problem by using the option : ./traccar.run --target /opt/traccar --noexec
Thank you for your help and reactivity.

The server is launched and works well with the default base H2, but we want to use a MySQL Database, we have modified the configuration file traccar.xml, the server starts well, but when i launch the url to login, we have at screen a popup with error : NullPointer

Can you help me concernng this problem ?

Thanks

**Comment by tananaev** [comment]
I suspect there is something missing in the config file. Can you show me what you `traccar.xml` file looks like?

**Comment by fperroud** [comment]
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key='web.enable'>true</entry>
    
    <entry key='web.port'>8082</entry>
    
    <entry key='web.path'>web</entry>
    <entry key='web.debug'>true</entry>

    <entry key='geocoder.enable'>false</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'>http://nominatim.openstreetmap.org/reverse</entry>

    <entry key='distance.enable'>true</entry>

    

    

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>target/tracker-server.log</entry>

    

    

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://gextrasoft.com:3306/gsoft_TRACCAR?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
    <entry key='database.user'>gsoft_GENY</entry>
    <entry key='database.password'>gextrasoft2014!</entry>
    
    <entry key='database.checkTable'>traccar</entry>

    <entry key='database.selectSchemaVersion'>
        SELECT * FROM traccar;
    </entry>

    <entry key='database.createSchema'>
        CREATE TABLE "user" (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(128) NOT NULL,
        email VARCHAR(128) NOT NULL UNIQUE,
        hashedPassword VARCHAR(128) NOT NULL,
        salt VARCHAR(128) DEFAULT '' NOT NULL,
        readonly BIT DEFAULT 0 NOT NULL,
        admin BIT DEFAULT 0 NOT NULL,
        map VARCHAR(128),
        language VARCHAR(128),
        distanceUnit VARCHAR(128),
        speedUnit VARCHAR(128),
        latitude FLOAT DEFAULT 0 NOT NULL,
        longitude FLOAT DEFAULT 0 NOT NULL,
        zoom INT DEFAULT 0 NOT NULL);

        CREATE TABLE device (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(128) NOT NULL,
        uniqueId VARCHAR(128) NOT NULL UNIQUE,
        status VARCHAR(128),
        lastUpdate TIMESTAMP,
        positionId INT,
        dataId INT);

        CREATE TABLE user_device (
        userId INT NOT NULL,
        deviceId INT NOT NULL,
        "read" BIT DEFAULT 1 NOT NULL,
        "write" BIT DEFAULT 1 NOT NULL,
        FOREIGN KEY (userId) REFERENCES "user" (id) ON DELETE CASCADE,
        FOREIGN KEY (deviceId) REFERENCES device (id) ON DELETE CASCADE);

        CREATE INDEX user_device_userId ON user_device(userId);

        CREATE TABLE position (
        id INT PRIMARY KEY AUTO_INCREMENT,
        protocol VARCHAR(128),
        deviceId INT NOT NULL,
        serverTime TIMESTAMP NOT NULL,
        deviceTime TIMESTAMP NOT NULL,
        fixTime TIMESTAMP NOT NULL,
        valid BIT NOT NULL,
        latitude FLOAT NOT NULL,
        longitude FLOAT NOT NULL,
        altitude FLOAT NOT NULL,
        speed FLOAT NOT NULL,
        course FLOAT NOT NULL,
        address VARCHAR(512),
        other VARCHAR(4096) NOT NULL,
        FOREIGN KEY (deviceId) REFERENCES device (id) ON DELETE CASCADE);
        
        CREATE INDEX position_deviceId_fixTime ON position (deviceId, fixTime);

        CREATE TABLE data (
        id INT PRIMARY KEY AUTO_INCREMENT,
        protocol VARCHAR(128),
        deviceId INT NOT NULL,
        serverTime TIMESTAMP NOT NULL,
        deviceTime TIMESTAMP NOT NULL,
        other VARCHAR(4096) NOT NULL,
        FOREIGN KEY (deviceId) REFERENCES device (id) ON DELETE CASCADE);

        ALTER TABLE device ADD
        FOREIGN KEY (positionId) REFERENCES position (id) ON DELETE CASCADE;

        ALTER TABLE device ADD
        FOREIGN KEY (dataId) REFERENCES data (id) ON DELETE CASCADE;

        CREATE TABLE server (
        id INT PRIMARY KEY AUTO_INCREMENT,
        registration BIT NOT NULL,
        map VARCHAR(128),
        bingKey VARCHAR(128),
        mapUrl VARCHAR(128),
        language VARCHAR(128),
        distanceUnit VARCHAR(128),
        speedUnit VARCHAR(128),
        latitude FLOAT DEFAULT 0 NOT NULL,
        longitude FLOAT DEFAULT 0 NOT NULL,
        zoom INT DEFAULT 0 NOT NULL);

        CREATE TABLE traccar (
        version INT DEFAULT 0 NOT NULL);

        INSERT INTO traccar (version) VALUES (301);
    </entry>

    <entry key='database.selectServers'>
        SELECT * FROM server;
    </entry>

    <entry key='database.insertServer'>
        INSERT INTO server (registration, latitude, longitude, zoom)
        VALUES (:registration, :latitude, :longitude, :zoom);
    </entry>

    <entry key='database.updateServer'>
        UPDATE server SET
        registration = :registration,
        map = :map,
        bingKey = :bingKey,
        mapUrl = :mapUrl,
        language = :language,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom
        WHERE id = :id;
    </entry>

    <entry key='database.loginUser'>
        SELECT * FROM "user"
        WHERE email = :email;
    </entry>

    <entry key='database.selectUser'>
        SELECT * FROM "user"
        WHERE id = :id;
    </entry>

    <entry key='database.selectUsersAll'>
        SELECT * FROM "user";
    </entry>

    <entry key='database.insertUser'>
        INSERT INTO "user" (name, email, hashedPassword, salt, admin)
        VALUES (:name, :email, :hashedPassword, :salt, :admin);
    </entry>

    <entry key='database.updateUser'>
        UPDATE "user" SET
        name = :name,
        email = :email,
        admin = :admin,
        map = :map,
        language = :language,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom
        WHERE id = :id;
    </entry>

    <entry key='database.updateUserPassword'>
        UPDATE "user" SET hashedPassword = :hashedPassword, salt = :salt WHERE id = :id;
    </entry>
    
    <entry key='database.deleteUser'>
        DELETE FROM "user" WHERE id = :id;
    </entry>

    <entry key='database.getPermissionsAll'>
        SELECT userId, deviceId FROM user_device;
    </entry>
    
    <entry key='database.selectDevicesAll'>
        SELECT * FROM device;
    </entry>
    
    <entry key='database.selectDevices'>
        SELECT * FROM device d INNER JOIN user_device ud ON d.id = ud.deviceId WHERE ud.userId = :userId;
    </entry>
    
    <entry key='database.insertDevice'>
        INSERT INTO device (name, uniqueId) VALUES (:name, :uniqueId);
    </entry>
    
    <entry key='database.updateDevice'>
        UPDATE device SET name = :name, uniqueId = :uniqueId WHERE id = :id;
    </entry>
    
    <entry key='database.deleteDevice'>
        DELETE FROM device WHERE id = :id;
    </entry>
    
    <entry key='database.linkDevice'>
        INSERT INTO user_device (userId, deviceId) VALUES (:userId, :deviceId);
    </entry>

    <entry key='database.selectPositions'>
        SELECT * FROM position WHERE deviceId = :deviceId AND fixTime BETWEEN :from AND :to ORDER BY fixTime;    
    </entry>

    <entry key='database.insertPosition'>
        INSERT INTO position (deviceId, protocol, serverTime, deviceTime, fixTime, valid, latitude, longitude, altitude, speed, course, address, other)
        VALUES (:deviceId, :protocol, CURRENT_TIMESTAMP(), :time, :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :other);
    </entry>

    <entry key='database.selectLatestPositions'>
        SELECT * FROM position WHERE id IN (SELECT positionId FROM device);
    </entry>

    <entry key='database.updateLatestPosition'>
        UPDATE device SET positionId = :id WHERE id = :deviceId;
    </entry>

    

    
    <entry key='gps103.port'>5001</entry>
    <entry key='tk103.port'>5002</entry>
    <entry key='gl100.port'>5003</entry>
    <entry key='gl200.port'>5004</entry>
    <entry key='t55.port'>5005</entry>
    <entry key='xexun.port'>5006</entry>
    <entry key='xexun.extended'>false</entry>
    <entry key='totem.port'>5007</entry>
    <entry key='enfora.port'>5008</entry>
    <entry key='meiligao.port'>5009</entry>
    <entry key='maxon.port'>5010</entry>
    <entry key='suntech.port'>5011</entry>
    <entry key='progress.port'>5012</entry>
    <entry key='h02.port'>5013</entry>
    <entry key='jt600.port'>5014</entry>
    <entry key='ev603.port'>5015</entry>
    <entry key='v680.port'>5016</entry>
    <entry key='pt502.port'>5017</entry>
    <entry key='tr20.port'>5018</entry>
    <entry key='navis.port'>5019</entry>
    <entry key='meitrack.port'>5020</entry>
    <entry key='skypatrol.port'>5021</entry>
    <entry key='gt02.port'>5022</entry>
    <entry key='gt06.port'>5023</entry>
    <entry key='megastek.port'>5024</entry>
    <entry key='navigil.port'>5025</entry>
    <entry key='gpsgate.port'>5026</entry>
    <entry key='teltonika.port'>5027</entry>
    <entry key='mta6.port'>5028</entry>
    <entry key='tzone.port'>5029</entry>
    <entry key='tlt2h.port'>5030</entry>
    <entry key='taip.port'>5031</entry>
    <entry key='wondex.port'>5032</entry>
    <entry key='cellocator.port'>5033</entry>
    <entry key='galileo.port'>5034</entry>
    <entry key='ywt.port'>5035</entry>
    <entry key='tk102.port'>5036</entry>
    <entry key='intellitrac.port'>5037</entry>
    <entry key='xt7.port'>5038</entry>
    <entry key='wialon.port'>5039</entry>
    <entry key='carscop.port'>5040</entry>
    <entry key='apel.port'>5041</entry>
    <entry key='manpower.port'>5042</entry>
    <entry key='globalsat.port'>5043</entry>
    <entry key='atrack.port'>5044</entry>
    <entry key='pt3000.port'>5045</entry>
    <entry key='ruptela.port'>5046</entry>
    <entry key='topflytech.port'>5047</entry>
    <entry key='laipac.port'>5048</entry>
    <entry key='aplicom.port'>5049</entry>
    <entry key='gotop.port'>5050</entry>
    <entry key='sanav.port'>5051</entry>
    <entry key='gator.port'>5052</entry>
    <entry key='noran.port'>5053</entry>
    <entry key='m2m.port'>5054</entry>
    <entry key='osmand.port'>5055</entry>
    <entry key='easytrack.port'>5056</entry>
    <entry key='gpsmarker.port'>5057</entry>
    <entry key='khd.port'>5058</entry>
    <entry key='piligrim.port'>5059</entry>
    <entry key='stl060.port'>5060</entry>
    <entry key='cartrack.port'>5061</entry>
    <entry key='minifinder.port'>5062</entry>
    <entry key='haicom.port'>5063</entry>
    <entry key='eelink.port'>5064</entry>
    <entry key='box.port'>5065</entry>
    <entry key='freedom.port'>5066</entry>
    <entry key='telik.port'>5067</entry>
    <entry key='trackbox.port'>5068</entry>
    <entry key='visiontek.port'>5069</entry>
    <entry key='orion.port'>5070</entry>
    <entry key='riti.port'>5071</entry>
    <entry key='ulbotech.port'>5072</entry>
    <entry key='tramigo.port'>5073</entry>
    <entry key='tr900.port'>5074</entry>
    <entry key='ardi01.port'>5075</entry>
    <entry key='xt013.port'>5076</entry>
    <entry key='autofon.port'>5077</entry>
    <entry key='gosafe.port'>5078</entry>
    <entry key='autofon45.port'>5079</entry>
    <entry key='bce.port'>5080</entry>
    <entry key='xirgo.port'>5081</entry>
    <entry key='calamp.port'>5082</entry>
    <entry key='mtx.port'>5083</entry>
    <entry key='tytan.port'>5084</entry>
    <entry key='avl301.port'>5085</entry>
    <entry key='castel.port'>5086</entry>
    <entry key='mxt.port'>5087</entry>
    <entry key='cityeasy.port'>5088</entry>

</properties>

**Comment by fperroud** [comment]
By comparing with database H2 that works well, i have found that the table 'server' is empty with MySQL while in H2 it is initialized with a record while 'true' in column registration.
By forcing a record in this table in MySQL, it works well now.

For replace columns of type BIT in H2, i used TINYINT field in Mysql, is this correct ? Perhaps it's the cause of the problem ?

**Comment by tananaev** [comment]
Server table should be created automatically on the first start. Not sure why it failed to do so.

As for data type, as far as I know MySQL supports `BIT` type, so there is no need to change anything.

**Comment by fperroud** [comment]
Ok, thank you. It works well now, but i have of to change the script in traccar.xml to work, the quotation marks by special quote in MySQL (backtick) : " ` " and it works well

**Comment by tananaev** [comment]
Double quotes should work because of this:
<pre>sessionVariables=sql_Mode=ANSI_QUOTES</pre>

**Comment by tananaev** [comment]
Maybe it should be lower case M:
<pre>sessionVariables=sql_mode=ANSI_QUOTES</pre>

**Comment by fperroud** [comment]
but we have other databases and we can't aply this to others, is it possible to have this specially for one database MySQL ?

**Comment by tananaev** [comment]
This would apply for the Traccar session only if you specify it in the database connection URL, but as far as I can see you already have it there.

**Comment by fperroud** [comment]
Ok than you for your big help and reactivity, it's work very well.

**Comment by tananaev** [comment]
What version of CentOS do you have? I am trying to investigate the installation issue. I tried on version 6.4 and it doesn't happen.

**Comment by tananaev** [comment]
I have tested installer on CentOS versions 6.5 and 7.1 as well and it works fine.

**Comment by m-menon** [comment]
I have (almost) the same issue too. I have tried both Centos 6.5 and Centos 7. The error during install. This is on Centos 6.5 and 7 also exactly the same error

```
[root@li394-53 home]# unzip traccar-linux-64-3.4.zip
Archive:  traccar-linux-64-3.4.zip
  inflating: traccar.run
  inflating: README.txt
[root@li394-53 home]# sudo ./traccar.run
Verifying archive integrity... All good.
Uncompressing traccar  100%
./setup.sh: line 5: [: -lt: unary operator expected
Detected RHEL or Fedora:
Installing the traccar daemon..
[root@li394-53 home]#
```

Anything I could be doing wrong? Both are fresh installs of CentOS

Thanks

**Comment by tananaev** [comment]
What's the default shell on your platform?

**Comment by m-menon** [comment]
Oh you mean 

```
[root@li394-53 home]# ps -p $$
  PID TTY          TIME CMD
 2618 pts/0    00:00:00 bash
[root@li394-53 home]# echo $SHELL
/bin/bash
```

Java I thought I'd install after the traccar install...before starting up traccar...Like I did earlier on Ubuntu 14.04 LTS and it worked fine

**Comment by tananaev** [comment]
You have to install Java first.

**Comment by m-menon** [comment]
It worked..thanks! But one strange thing to note is that when I installed it on Ubuntu 14.04, the installation went smoothly even without java. When I tried to start it, at that time is showed the error and then I installed java and it started....whereas in the case of centos the installation doesn't go through unless java is installed :-)

**Comment by tananaev** [comment]
Maybe it was on some older version. Traccar now checks for Java in the installer.

**Comment by m-menon** [comment]
cool, thank you so much. Just for information it is the same version (traccar-linux-64-3.4.zip) that I tried on Ubuntu 14.04 LTS Trusty Tahr also. Thanks once again

**Comment by alidiaby** [comment]
Hi I am seting up traccar on a VPS server (bluehost) and the linux versionis 64 x86 version,  I have been able to uncompress but installation is not starting. Where i have to copy the file on the server, knowing that I already have a couple of website on the same server. I created a trackar subdomain.
