### ISSUE TITLE
Hexadecimal speed conversion to Double

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#1404]
Hi anton, as I told you before I'm creating a slightly different protocol using GT06 protocol decoder but I need to convert speed from Hex to Double, how can I do that?
in GT06 I have this:
position.setSpeed(buf.readUnsignedByte() * 1.00);
(forget about the 1.00)
The device is sending speed in hex but is not sending 0x10 but only the integer part 10.
How can I convert that to Double ??
Thanks

**Comment by tananaev** [comment]
Can you please provide example of the data you get and what you are highlight the part you are trying to convert.

**Comment by hackerunet** [comment]
I'm trying to change this from Gt06 protocol decoder:
// Speed
position.setSpeed(buf.readUnsignedByte() * 0.539957);

This is a speed conversion from knots to kms, but my device send speed as hexadecimal value not an integer, so I need a procedure to change hexadecimal to double and store the speed.

This is the speed spec in the documentation:

5.2.1.8.	Speed
One byte is consumed, defining the running Speed of GPS. The value ranges from 0x00 to 0xFF indicating a range from 0 to 225km/h.
e.g.   	0x00 represents 0 km/h.
   		0x10 represents 16km/h.
	  		0xFF represents 255 km/h.

**Comment by tananaev** [comment]
You can provide sample in HEX format like the one you get in the log.

**Comment by hackerunet** [comment]
Ok
First received: 
787805120060c1a20d0a
78781f120f090b071308c90115565a074e36df003d2e02de041b6e008d1f000bf78d0d0a

**Comment by tananaev** [comment]
So, where is the HEX data that is not an integer?

**Comment by hackerunet** [comment]
not a clue, I'm not able to see the incomming data I just want to store the correct speed, the gt06 protocol is reading the information, multiplying x 0.539957, I need to replace that and convert the buf.readUnsignedByte() which returns a short number with the hexadecimal equivalence explained here:

5.2.1.8. Speed
One byte is consumed, defining the running Speed of GPS. The value ranges from 0x00 to 0xFF indicating a range from 0 to 225km/h.
e.g. 0x00 represents 0 km/h.
0x10 represents 16km/h.
0xFF represents 255 km/h.

How can I do that?

**Comment by hackerunet** [comment]
can I do this?

double speed = (double) buf.readUnsignedByte();
position.setSpeed(speed);

**Comment by tananaev** [comment]
Yes, you should be able to do that.

**Comment by hackerunet** [comment]
But the result is going to be... maybe the same right?

**Comment by hackerunet** [comment]
Please maybe this do the job:

##FUNCTION TO CONVERT TO HEX##
public static long parseUnsignedHex(String text) {
        if (text.length() == 16) {
            return (parseUnsignedHex(text.substring(0, 1)) << 60)
                    | parseUnsignedHex(text.substring(1));
        }
        return Long.parseLong(text, 16);
    }

// Speed
String hex = String.valueOf(buf.readUnsignedByte());
long longHex = parseUnsignedHex(hex);
double d = Double.longBitsToDouble(longHex);
position.setSpeed(d);

**Comment by hackerunet** [comment]
Maybe this is it:
// Speed
String hex = String.valueOf(buf.readUnsignedByte());
double d = Integer.parseInt(hex, 16);
position.setSpeed(d);

**Comment by tananaev** [comment]
No, just `readUnsignedByte` should work.

**Comment by hackerunet** [comment]
Anton, this is not working, the final string is not the sent by the device and for that the resulted speed is higher than real.

String hex = String.valueOf(buf.readUnsignedByte());
double d = Integer.parseInt(hex, 16);
position.setSpeed(d);

And this does not work, I received a incompatible types error (short cannot be converted to a string):
double d = Integer.parseInt(buf.readUnsignedByte(), 16);

**Comment by tananaev** [comment]
What units does your device send speed value in?

**Comment by maxicabanillas78** [comment]
![capturar](https://cloud.githubusercontent.com/assets/3855804/9829110/4e23ff84-58cf-11e5-8033-9627f5148557.PNG)
78781f120f090b071308c90115565a074e36df003d2e02de041b6e008d1f000bf78d0d0a
this is what you sent luis
so you can see what the sends

**Comment by hackerunet** [comment]
the protocol specification says is sending speed as hexadecimal unit in Kilometers per hour.

**Comment by tananaev** [comment]
Can you please send me protocol documentation to check? If you don't want to share it publicly, you can send it to me by email (address in profile).

**Comment by tananaev** [comment]
It's looks like a standard GT06 protocol. Where does it say that the Speed is in HEX? Speed value is just a byte, so as I said before `readUnsignedByte` should work.

**Comment by hackerunet** [comment]
jum, ok ok, so basically it doesn't need anything special at all? I'm sorry
about my ignorance about this...

**Comment by tananaev** [comment]
Correct, it's a standard byte value in binary format.

**Comment by hackerunet** [comment]
Anton you are right the GPS device is not sending an accurate speed due to
factory failures.
Thanks a lot, the sad part is that we are returning 1000 Devices!!

**Comment by tananaev** [comment]
That's a lot of devices. Are you sure it sends completely incorrect value or just using different speed units?

**Comment by hackerunet** [comment]
I did a test with a vehicle and it sends the speed correctly, apparently
this issue is present in a group of devices only, so we are testing
everything again. thanks for the support i think this can be closed now.
