### ISSUE TITLE
Wrapper License Issue

### ISSUE THREAD

**Issue by ankurraiyani** [tananaev/traccar#1411]
Hi,

I have downloaded server source code and made necessary changes.
Then i followed the steps to create .run file, now when i execute run file then it creates project under /opt
When i try to start the traccar it doesn't generate tracer-server.log and give wrapper license error as below
>
ERROR  | wrapper  | 2015/09/17 07:21:11 | License Error:
ERROR  | wrapper  | 2015/09/17 07:21:11 | A valid license was not found in the Wrapper configuration file.
ERROR  | wrapper  | 2015/09/17 07:21:11 | 
ERROR  | wrapper  | 2015/09/17 07:21:11 | The Java Service Wrapper requires a License Key to activate the
ERROR  | wrapper  | 2015/09/17 07:21:11 | software.  License Keys can be purchased on the Java Service Wrapper
ERROR  | wrapper  | 2015/09/17 07:21:11 | web site:
ERROR  | wrapper  | 2015/09/17 07:21:11 |   http://wrapper.tanukisoftware.com/purchase
ERROR  | wrapper  | 2015/09/17 07:21:11 | 
ERROR  | wrapper  | 2015/09/17 07:21:11 | You can also immediately obtain a one-month Free trial license:
ERROR  | wrapper  | 2015/09/17 07:21:11 |   http://wrapper.tanukisoftware.com/trial
ERROR  | wrapper  | 2015/09/17 07:21:11 | 
ERROR  | wrapper  | 2015/09/17 07:21:11 | License Keys can be generated for any of the following HostIds.
ERROR  | wrapper  | 2015/09/17 07:21:11 |   HostId(s):
ERROR  | wrapper  | 2015/09/17 07:21:11 |     7c4a33c8 (hostid)

I have linux 23 bit machine and i am new to traccar.

Please guide how can i resolve this error.

Thanks,
Ankur

**Comment by tananaev** [comment]
You need to use community (free) edition of the Java Service Wrapper.

**Comment by ankurraiyani** [comment]
How can i use it and what are the steps to do that ?

**Comment by tananaev** [comment]
You need to follow the same steps to create an installer; just download different version of the wrapper.

**Comment by ankurraiyani** [comment]
I followed the same steps to create run file and downloaded the required lib as well.
Still getting same error.

Do i need to create certificate and use it?

**Comment by tananaev** [comment]
Which version of Java Service Wrapper did you download?

**Comment by ankurraiyani** [comment]
I had downloaded Standard version earlier and now i have downloaded community version and it's working now !
Thanks a lot.
