### ISSUE TITLE
Using Traccar with MongoDB

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1418]
was wondering if there is any documentation on adapting / using traccar with mongodb? I see a huge amount of tracking data going in to my database eventually and was thinking if using mongodb would be a good idea.

and importantly - thanks a ton for the wonderful work. It's amazing

**Comment by tananaev** [comment]
I know that there is an experimental JDBC driver for MongoDB. I haven't tried it, but it might work with Traccar.

**Comment by m-menon** [comment]
thank you so much. I will give it a try and update if I succeed.
