### ISSUE TITLE
I can not see the data from this device - Accurate GT06

### ISSUE THREAD

**Issue by lucaspoo** [tananaev/traccar#1419]
Hello.
I bought this new device ACCURATE GT06 . After setting it up, I can not see the data from the same web interface. The Log is showing the following:

<pre>2015-09-22 18:25:32  INFO: [3BA601CF] connected
2015-09-22 18:25:34 DEBUG: [3BA601CF: 5023 < 179.16.220.13] HEX: 78780d0103554880201670490005f36e0d0a
2015-09-22 18:25:34 DEBUG: [3BA601CF: 5023 > 179.16.220.13] HEX: 7878050100059ff80d0a</pre>

But I can not convert this hexadecimal.
I'm using port 5023 ( already tried in 5013 and is the same).
I believe I'm using the wrong door . What might be happening?

Thanks!

**Comment by tananaev** [comment]
Port 5023 is the correct one. It seems like your device doesn't send any GPS data (possibly no GPS signal).

**Comment by lucaspoo** [comment]
Okay, I'll see what can be happening with that device .

Thank you!
