### ISSUE TITLE
My device is not shown in the demo

### ISSUE THREAD

**Issue by melwet** [tananaev/traccar#1420]
I wanted  to test my GPS tracker. It's a Meitrack T322X. When I send the data to the demo server, the locations of the device are not shown in demo.traccar.org

Username: melvin.wetzel@gmail.com

**Comment by tananaev** [comment]
The port (5020) was closed on the server. Please try again now.

**Comment by melwet** [comment]
Nothing yet. I use this 41.226.27.211
Is this correct?

**Comment by tananaev** [comment]
No, it's the old address. New one is 104.43.219.242.

**Comment by melwet** [comment]
Thanks! Now it works. 

Another question. Is it possible to use this protocol and store the data in my own mysql database? When I install the traccar server on my VPS.

**Comment by tananaev** [comment]
Yes, that is definitely possible. All SQL queries are in the config file, so you can configure Traccar to write data directly into your own database.

**Comment by melwet** [comment]
I will try this. Maybe I need your help later;)

Thanks for your help so far!!
