### ISSUE TITLE
add Accumulators to Calamp protocol 

### ISSUE THREAD

**Issue by HusseinYounis** [tananaev/traccar#1430]
hello anton, 

dont forget to add accumulators to calamp protocol .

this is your code : 

<pre> // Accumulators
            int accCount = buf.readUnsignedByte();
            int accType = accCount >> 6;
            accCount &= 0x3f;

            if (accType == 1) {
                buf.readUnsignedInt(); // threshold
                buf.readUnsignedInt(); // mask
            }

            for (int i = 0; i < accCount; i++) {
                extendedInfo.set("acc" + i, buf.readUnsignedInt());
            }</pre>

because Accumulators missing in  traccar 3

**Comment by tananaev** [comment]
What do you mean by missing? The code is there.

**Comment by HusseinYounis** [comment]
I am using traccar with calamp 2600 and 700 ... but in extra info there is
no accumulators value ..just input and event

**Comment by tananaev** [comment]
Please provide some HEX message samples from log (tracker-server.log).

**Comment by HusseinYounis** [comment]
see attachment

**Comment by tananaev** [comment]
I don't see any attachments. I don't think GitHub allows attachments in emails.

**Comment by HusseinYounis** [comment]
2015-09-28 07:41:31 DEBUG: [AE6B6181: 20500 < 46.230.54.31] HEX:
830543321494860101010a0c215608b6680ead5ada1bed88d300000049801f000500000300003cf33200000000000000008b0ce101
2015-09-28 07:41:31 DEBUG: [AE6B6181: 20500 > 46.230.54.31] HEX:
02010c210a0000000000
2015-09-28 07:41:31  INFO: [AE6B6181] id: 1, time: Mon Sep 28 06:39:20 AST
2015, lat: 24.624201, lon: 46.8551891, speed: 0.0, course: 0.0
2015-09-28 07:41:32 DEBUG: [AE6B6181: 20500 < 46.230.54.31] HEX:
830543321494860101010a0c225608b6870ead5c751bed8a80000000070f1e010500000300003cf33200000000000000008b0ce101
2015-09-28 07:41:32 DEBUG: [AE6B6181: 20500 > 46.230.54.31] HEX:
02010c220a0000000000
2015-09-28 07:41:32  INFO: [AE6B6181] id: 1, time: Mon Sep 28 06:39:51 AST
2015, lat: 24.6242421, lon: 46.855232, speed: 0.0, course: 0.0
2015-09-28 07:41:32 DEBUG: [AE6B6181: 20500 < 46.230.54.31] HEX:
830543321494860101010a0c235608b7020ead5bf71bed89e3000000080f1f000500000300003cf33200000000000000008b0ce101
2015-09-28 07:41:32 DEBUG: [AE6B6181: 20500 > 46.230.54.31] HEX:
02010c230a0000000000
2015-09-28 07:41:32  INFO: [AE6B6181] id: 1, time: Mon Sep 28 06:41:54 AST
2015, lat: 24.6242295, lon: 46.855216299999995, speed: 0.0, course: 0.0
2015-09-28 07:41:33 DEBUG: [AE6B6181: 20500 < 46.230.54.31] HEX:
830543321494860101010a0c245608b73d0ead5b081bed88fb000000090f1f330500000300003cf33200000000000000008b0ce101
2015-09-28 07:41:33 DEBUG: [AE6B6181: 20500 > 46.230.54.31] HEX:
02010c240a0000000000
2015-09-28 07:41:33  INFO: [AE6B6181] id: 1, time: Mon Sep 28 06:42:53 AST
2015, lat: 24.6242056, lon: 46.8551931, speed: 0.0, course: 0.0
2015-09-28 07:41:33 DEBUG: [AE6B6181: 20500 < 46.230.54.31] HEX:
830543321494860101010a0c255608b7790ead5b441bed88fa000000080f1f330500000300003cf33200000000000000008b0ce101
2015-09-28 07:41:33 DEBUG: [AE6B6181: 20500 > 46.230.54.31] HEX:
02010c250a0000000000
2015-09-28 07:41:34  INFO: [AE6B6181] id: 1, time: Mon Sep 28 06:43:53 AST
2015, lat: 24.6242116, lon: 46.855193, speed: 0.0, course: 0.0
2015-09-28 07:41:34 DEBUG: [AE6B6181: 20500 < 46.230.54.31] HEX:
830543321494860101010a0c265608b7b50ead5af81bed88dc000000090f1f330500000300003cf33200000000000000008b0ce101
2015-09-28 07:41:34 DEBUG: [AE6B6181: 20500 > 46.230.54.31] HEX:
02010c260a0000000000

**Comment by tananaev** [comment]
I have double checked the messages from your log. There are no accumulators there. Accumulator count is 0.

**Comment by HusseinYounis** [comment]
I decode the hex also using calamp tools its give me accumulators values ...

**Comment by tananaev** [comment]
Which one of the messages you checked and what values do you see in the tool?

**Comment by HusseinYounis** [comment]
OptionsByteMobileID,MobileIDType8310000011131MobileIDLength 5 bytes05
000001015MobileID43321494754332149475100001100110010000101001001010001110101
288603018357MobileIDLen1 byte01000000011MobileIDTypeESN01000000011Service
TypeAck'd Request010000000011Message Type10: MiniEvent0A00000000101010
Sequence#190013000000001001119UpdateTime2014-12-18 07:02:54 AM54927C1E
010101001001001001111100000111101418886174Latitude24.77908480EC4FD00
00001110110001001111110100000000247790848Longitude46.7286851BDA3B42
00011011110110100011101101000010467286850Speed 0 mph000000000000000000
HeadingEast ( 86 degrees)005600000000101011086Satellites 404000001004
FixStatus*Good*00000000000CommStateAvail,Network,Data,Connected0F0000111115
InputsIgnitionOn,Input1,Input2,Input3,Input41F0001111131UnitStatus**Good**00
000000000EventCode51330011001151Accum Count505000001015Accum  000000300
0000030000000000000000000000001100000000768Accum  10000007600000076
00000000000000000000000001110110118Accum  20000000000000000
000000000000000000000000000000000Accum  30000000000000000
000000000000000000000000000000000Accum  40000000000000000
000000000000000000000000000000000

**Comment by tananaev** [comment]
Sorry, but I cannot read this. You need to either properly format it or attach a screenshot.

**Comment by HusseinYounis** [comment]
using CalAmp_LMDecoder_2014.12.08
url : https://puls.calamp.com/w/images/e/e9/CalAmp_LMDecoder_2014.12.08.zip

**Comment by HusseinYounis** [comment]
![sadsadsa](https://cloud.githubusercontent.com/assets/14852408/10185327/a29953e6-674f-11e5-9445-88989ad84695.PNG)

**Comment by tananaev** [comment]
Which HEX message from the log are you decoding? I can't find any matching one.

**Comment by HusseinYounis** [comment]
2015-09-29 08:36:08 DEBUG: [AAACBDD2: 20500 < 37.217.51.99] HEX: 830543321494860101010a0cf7560972730eab61bd1bee4f8e00983b0c0f1f330500000301003f2e3300000000000000009195e140
2015-09-29 08:36:08 DEBUG: [AAACBDD2: 20500 > 37.217.51.99] HEX: 02010cf70a0000000000

**Comment by tananaev** [comment]
Sorry, but HEX on the screenshot doesn't match the HEX from the log. There must be some mistake.

**Comment by HusseinYounis** [comment]
hex: 830543321494860101010a0080560b5a5e0eadd0291becf3c500f005090f1f3305000003010040c0a600000000000000008b12a102

screenshot : 
![ssssssssssssss](https://cloud.githubusercontent.com/assets/14852408/10185911/5304f0aa-6755-11e5-8190-598ca0485d3b.PNG)

**Comment by tananaev** [comment]
I have fixed the issue. Thanks for feedback.

Here is a new build for testing:

https://www.dropbox.com/s/myt68q5u7fiz49r/tracker-server-jar-with-dependencies.jar?dl=0

**Comment by maxicabanillas78** [comment]
good day friend
Poderia you inform me if the ignition is showing traccar
![capturar](https://cloud.githubusercontent.com/assets/3855804/10194498/6d18875e-675f-11e5-80ec-7c5cd4efe47b.PNG)

**Comment by maxicabanillas78** [comment]
leave working as Event.KEY_IGNITION

**Comment by beabel** [comment]
> using CalAmp_LMDecoder_2014.12.08 url : https://puls.calamp.com/w/images/e/e9/CalAmp_LMDecoder_2014.12.08.zip

@HusseinYounis  the link from lmDecoder is broken, can you share a new link please.
