### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin

### ISSUE THREAD

**Issue by reviloera** [tananaev/traccar#1434]
Am trying to consume the REST API endpoint and am getting that error. Where do I set the CORS

**Comment by reviloera** [comment]
I have recomplled and now this is the error 
  <code>
Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
</code>

**Comment by tananaev** [comment]
Added more CORS headers.

**Comment by vladamirk** [comment]
Hi @reviloera ,
I have faced an issue when I need to login to Traccar from different app, but I can't get cookies for it, I hope you can give me some advice. Thank you in advance for any help.

**Comment by reviloera** [comment]
Ensure credentials is enabled in your request e.g if you are using jquery

$.ajaxSetup({
    type: "POST",
    data: {},
    dataType: 'json',
    xhrFields: {
       withCredentials: true
    },
    crossDomain: true});

then your CORS on the server credetials must be enabled


On Fri, Nov 13, 2015 at 2:53 AM, Volodymyr <notifications@github.com> wrote:

> Hi @reviloera <https://github.com/reviloera> ,
> I have faced an issue when I need to login to Traccar from different app,
> but I can't get cookies for it, I hope you can give me some advice. Thank
> you in advance for any help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1434#issuecomment-156274249>.
>



-- 
an eye for design and a mind for code [revilo]

**Comment by vladamirk** [comment]
Thank you for response, but it's not helping in my case. 
https://github.com/tananaev/traccar/issues/1526#issuecomment-156485377
