### ISSUE TITLE
Capturing GT06 protocol information

### ISSUE THREAD

**Issue by younus93** [tananaev/traccar#1445]
Hi Anton. Thank you so much for making this project open source. I used the service on your domain and its splendid. 
As a part of an academic project, is it possible to capture the data sent by a GT06 protocol device? 
I created a nodejs endpoint on my server and it is able to catch and send over the data your Traccar Client sends to it. But, when I configure the device to send data to my server, I'm not able to capture any packets. 
How do you get these http requests? I have a Rest endpoint listening on '/' on my server at the port 8000. 
This endpoint is successfully able to listen to the packets Traccar client sends. 

My question is how to capture the login and heartbeat packets sent by the device?

**Comment by tananaev** [comment]
GT06 is not a HTTP-based protocol. It works on top of raw TCP connection.

One thing you can do is to use Traccar to forward GT06 or any other GPS data to your web service. Let me know if you are interested and I'll provide more details on how to do it.

**Comment by younus93** [comment]
Hello, 
Thanks for the information. Yes, I would love to learn how to implement the method you mentioned above. 
And, the GT06 tracker with imei number 358911020149049 is not showing any status. I can see it on the map, but when I ask for a range of data in the below panel, I am not seeing anything. Can you please tell me whats wrong?

**Comment by tananaev** [comment]
Are you using demo server or your own one? Make sure you selected correct time interval. Does data show up in the state panel when you select the device?

As for forwarding data, you can add lines from the following comment to the config: https://github.com/tananaev/traccar/issues/1131#issuecomment-121150718.

**Comment by younus93** [comment]
Thanks for the help.

**Comment by amitsharma957** [comment]
Hello,

I want to gt06 protocol with full  description. device sent to server non readable symbol.
so plz help me.........

**Comment by tananaev** [comment]
@amitsharma957, you can find protocol documentation here:

https://www.traccar.org/protocols/

There are no readable symbols because GT06 is a binary protocol.

**Comment by amitsharma957** [comment]
@tananaev , thanks 

i read protocol but not clear .........data received but data is in chines symbol........

if u have any doc. and file plz send  private msg amitsharma957@gmail.com

Thanks..in advance

**Comment by tananaev** [comment]
I already gave you the link to the protocol documentation. I have to repeat again that the data is in binary format, so it won't be readable text.

**Comment by rbniranjan** [comment]
@tananaev , Thanks for providing such help.

I am creating own GPS Tracker server in PHP and using GT06 protocol based device. I am able to get the data on my server. But problem is I always get login data from the device. Even I successfully send the data to device from my server.

This is the hexa formate that I got from server : 78780d010358899054620946001570f70d0a
I respond following data to device from my server : 787805010014d9dc0d0a

As per protocol suggestion. I am doing same but device always send me login data on my server.

Can you please help me.

Thanks.

**Comment by sachiner** [comment]
@tananaev can you please give me a small example how can i get a data from the module using the node.js server

**Comment by tananaev** [comment]
I am not a Node.js developer. How would I give you an example? I would recommend searching on forum and GitHub. There might be some examples.

**Comment by ShubhamKadam141994** [comment]
@tananaev I have purchased Wetrack2 device and I want to store data of GPS device at the server. So how I can make the connection between GPS device and server. and what technology that device used to communicate with the server ?

**Comment by tananaev** [comment]
@ShubhamKadam141994, how is your question related to this issue? If it's not, please find the right place to ask it.

**Comment by vkumarOST** [comment]
Hi tananev

Am Building a GPS tracking application. am new to socket programming. am able to connect with my gps its GT06 but not able to read data can you send me the sample code. so that i will understand how to read data so that i will code to by myself for my customise requirement. all i need is to recive data to my application and how to convert

**Comment by anilmcmt** [comment]
Hi,
I have BW08 GPS Vehicle Tracker device and send data to own server and port
But unable to read data i got like some thing
DATA 223.225.51.14: xx
��

Please help i travel 10 days

**Comment by tananaev** [comment]
@anilmcmt, please don't ask questions on an ancient closed thread. Also, if you ask something it has to be related to Traccar and you need to provide proper log fragment.

**Comment by basilstr** [comment]
Hi guys.
I receive data from the tracker, but I did not find a suitable description in the protocol description
78 78 22 22 14 0a 11 15 15 25 cb 05 4d 6f a6 02 e4 f0 3a 00 14 00 00 ff 06 34 bf 00 20 05 00 00 00 01 d6 1b d8 0d 0a
What does protocol 22 mean?

**Comment by notesMafia** [comment]
> Hi guys. I receive data from the tracker, but I did not find a suitable description in the protocol description 78 78 22 22 14 0a 11 15 15 25 cb 05 4d 6f a6 02 e4 f0 3a 00 14 00 00 ff 06 34 bf 00 20 05 00 00 00 01 d6 1b d8 0d 0a What does protocol 22
i think this is your lat long here   05 4d 6f a6 02 e4 f0 3a
49.42274111111111, Longitude: 26.976743333333335  show location of ukrine

**Comment by sajjatdev** [comment]
login response error
