### ISSUE TITLE
Gt06 protocol check.

### ISSUE THREAD

**Issue by warlockopy** [tananaev/traccar#1452]
Hello, I am checking the gt06 protocol, because one device that I am getting from china seems to have that protocol, even checking on google seems similar, but not according to the protocol document on traccar website.

Related cases #971 #526 #483 #326 

Some other reference.
Just Share about GT003.  now my gps works nicely on xxxxxxxxxx

THIS IS THE HISTORY

1. Purchased GT003 from ebay, OK by SMS but need something better, no information on GPS manual book about how if you want to web tracking, then found wonderful website Orange-trace.com.

2. FIRS PROBLEM COME, based on manual book GT003 and seller website on ebay, to change server/IP  by type this format via sms : SERVER,1/0,domain/ip,port#.                  BUT, GPS always replied FORMAT WRONG !!.  no matter how i change the format by SMS, GPS replied FORMAT WRONG! (by sms command : PARAM,1# you'll see the original IP only from manufacturer)

3. THEN, I found this from forum http://forum.gpstrace.ru/viewtopic.php?pid=16739  (Thanks  a lot guys for share there)-- after tanslate from rusian to english, here it is: "my version GT003 - V06, and server command is entered differently than earlier versions and instructions that was included, namely SERVER, code, domain / IP, port # where the code is 8520.   
So, I Got the newest version of GT003 with the new sms command syntax, and this is NOT CLEARLY informed on manual book/different.
This is the right format sms command: SERVER, code, domain / IP, port #.   I don't know where it come from the number: 8520, but USE it and works!.
HOW did we know the GT003 is V06 or not, simple.... by open your GPS and you'll see the sticker with V06 printed on gps chipset modul.

4. FINALLY
    IN orange-gps tracker, GT003 is the same  protocol with GT06, so in this case :
    4.1  IP and port will be used for GT003/GT06 configuration is  193.193.165.166/port 20281
    4.2  I change the IP server on GPS by sms command :  SERVER, 8520,193.193.165.166,20281 #
          GPS replied : SET IP OK ! IP:193.193.165.166,20281 #
          YESSSS!!!

5. Make sure your SIMCARD setting for APN/Internet is OK and, make any proper configuration on orange-gps trace.com, and you'll see soon, your GPS is HERE.

May this useful for who got problem as me. big_smile

Regards

Added after    4 minuts  23 seconds:
This is GT003 looks like http://www.ebay.com/itm/130904718893?ss … 1497.l2649
if admin need to update the picture about device supported on this lovely web site. 

I cannot attach will try on email.

**Comment by tananaev** [comment]
The protocol documentation that you sent me called TK103 in Traccar and it works on port 5002.

**Comment by Wtracking** [comment]
good Afternoon.

I have 4 gt003 devices and I could not configure them for a year and a half and today with your help I managed to get two to work but I continue with two that keep the "Format wrong" response to the command. I noticed that those who did not accept the command are from version 12. Would you have any idea or knowledge about which command to use for this case?

**Comment by acvardar** [comment]
Dear Wtracking, 

It is because the field "8520" is a password. In my devices user manual it is written by hand 
"83466207". 
I entered command  SERVER, 83466207,109.235.68.205,6023#
![img_2629](https://cloud.githubusercontent.com/assets/27638009/25073200/1d18232a-22ea-11e7-927c-638e1860463c.JPG)

Hope you still have the user manual...

**Comment by Wtracking** [comment]
Dear ACvardar,

Thanks for your help. that code 8520 help us to point two of our devices GT02B to wialon server but just work on two and we still need help with other two that us version 12.

**Comment by Malouda** [comment]
Hello,i am new to the gprs trackers,i want to buy gps tracker GT06 GSM GPRS GPS for out customers,the main aim is to set up a server so as to monitor our customers motorcycles!Any advice?

**Comment by Wtracking** [comment]
Dear Atraccar,

Did you know witch syntax must be used to set ip on GT003 track device
version 12?

**Comment by Wtracking** [comment]
Hi guys,

I have just test the code write on the manual by pen and its works for GT003 devices with version 12. if you have one of use that code SERVER, 83466207,109.235.68.205,6023# and you will get write answer from device like i get.

Enjoy

**Comment by quique4x4** [comment]
Thank you very much Wtracking. This work for me: SERVER, 83466207,109.235.68.205,5023#
Regards.
