### ISSUE TITLE
got stuck at ipkg bootstrap verification at packageinstallation on synology

### ISSUE THREAD

**Issue by delta-wave81** [tananaev/traccar#1453]
Hi there,

I have tried installing traccar using your guide from https://www.traccar.org/synology/ but i got stuck at the installationprocess of the package.
 
Ipkg bootstrap, java 7 and mysqlserver have been installed by gui.
Coreutils, textutils and gettext have been installed by ipkggui. And verified by ssh by ipkg.
 
My problem is, when I try to install the Cummunity Package after configuring the ports and mysql password... I get the message the IPKG Bootstrap is not installed. Whitch it is.

My DS is a DS1813+ with DSM 5.2-5592 Update 4.
 
What can I do to make this work?

**Comment by tananaev** [comment]
@1sthandy might be able to help you.

**Comment by 1sthandy** [comment]
Hi, today you can test the Betapackage http://www.synology-forum.de/showthread.html?41824-Beta-Traccar-GPS-Trackingserver&p=580995&viewfull=1#post580995

**Comment by delta-wave81** [comment]
Hi,
found the solution to my problem here:
http://www.synology-forum.de/showthread.html?68335-EBI-Easy-Bootstrap-Installer
at  entry 23.08.2015, 20:00.
Hope this helps others with the same problem as well.

**Comment by 1sthandy** [comment]
@delta-wave81 thanks, this will be fixed in next Version
