### ISSUE TITLE
Open street map

### ISSUE THREAD

**Issue by ethankz** [tananaev/traccar#1454]
Please help me. Open street map is not displaying anymore, but others maps are working.

**Comment by ethankz** [comment]
Please i don't know what happen with this map. Can someone help me?

**Comment by tananaev** [comment]
Did it stop working after some changes?

**Comment by ethankz** [comment]
I recently installed LAMP on my server. I faced some problems during mysql installation. That's all.

**Comment by tananaev** [comment]
I guess you need to look at browser console to see why it doesn't load open street maps.

**Comment by ethankz** [comment]
But you know others maps are working well.

**Comment by tananaev** [comment]
I have no idea why it might be happening. The only way to know is to check browser console to see if there are any error messages there. Also, try to add "debug.html" to the URL and see if it helps.

**Comment by ethankz** [comment]
Please take a look: http://23.236.144.233:8082/

**Comment by tananaev** [comment]
It works for me. Try to clear your browser cache.

**Comment by ethankz** [comment]
Thank you very much.
