### ISSUE TITLE
Change traccar 3 default map to Google Maps

### ISSUE THREAD

**Issue by and12345** [tananaev/traccar#1456]
Hi Anton,

Is it possible for me to change the default maps to google maps ? Which code i've to edit ?

Thank you

**Comment by tananaev** [comment]
There is a work-around to get Google Maps layers:

https://www.traccar.org/map-layers/

Note that you need a permission/license from Google to use their tile server.

**Comment by lilicsubatman** [comment]
if i have api keys on google... what can i  use google maps is a default layer in my traccar...?

**Comment by tananaev** [comment]
If you have premium business Google Maps license, then ask their support if you are allowed to use tile server directly. That's the only option at the moment.

If you don't have premium license, you are not allowed to use Google Maps for GPS tracking.
