### ISSUE TITLE
Date and time issue

### ISSUE THREAD

**Issue by addonravi** [tananaev/traccar#1459]
Hi tananaev
Below code is my tracker-server.log file code..
It's display time is null but in my database position table all date are perfectly added. 

<pre>2015-10-17 00:01:48 DEBUG: [ABEC8028: 5090 < 1.39.15.73] HEX: 454f3b313b3836343930363032303933343838343b52473b342b3135313031363138333134362b32332e30333333372b37322e35313133302b302e32302b302b343135392b310d0a
2015-10-17 00:01:48  WARN: NullPointerException (DefaultDataHandler:29 < BaseDataHandler:29 < ... < ExtendedObjectDecoder:41 < ...)
2015-10-17 00:01:48  INFO: [ABEC8028] id: 7, time: null, lat: 23.03337, lon: 72.5113, speed: 0.2, course: 0.0</pre>

**Comment by tananaev** [comment]
What version of Traccar are you using?

**Comment by addonravi** [comment]
3.1

**Comment by tananaev** [comment]
Traccar version 3.1 doesn't use port 5090.

**Comment by addonravi** [comment]
why??

**Comment by tananaev** [comment]
Because it didn't support Flextrack protocol (port 5090). What protocol are you using?

**Comment by addonravi** [comment]
I using eskyes620 protocol and port is 5090.
I created 2 file eskyes620ProtocolDecoder.java and eskyes620Protocol.java
and 1 test file eskyes620ProtocolDecoderTest.java

**Comment by tananaev** [comment]
It means that you are not using version 3.1 of Traccar. You are using your custom build and looks like you haven't provided time value.

**Comment by addonravi** [comment]
yes .. I think same to you but i am not sure for that.. I check update ..
If i find any problem then contact to you.
Thanks for fast replay..

**Comment by addonravi** [comment]
Thanks Solve this problem 
I close this issue.
