### ISSUE TITLE
getDeviceid() method return 0 value

### ISSUE THREAD

**Issue by addonravi** [tananaev/traccar#1460]
<pre>position.setDeviceId(getDeviceId());</pre>

Not set Device id because getDeviceId() method return 0 and deviceid 0 not available in Device table ..
so it's provide reference exception.
currently i set static device id.

Below is error show in tracker-server.log file

<pre>WARN: Cannot add or update a child row: a foreign key constraint fails ("mahesh"."position", CONSTRAINT "position_ibfk_1" FOREIGN KEY ("deviceId") REFERENCES "device" ("id") ON DELETE CASCADE) - MySQLIntegrityConstraintViolationException (... < QueryBuilder:412 < DataManager:336 < DefaultDataHandler:27 < ...)
2015-10-17 12:26:49  INFO: [A3771226] id: 0, time: null, lat: 23.03374, lon: 72.51159, speed: 0.27, course: 0.0</pre>

**Comment by tananaev** [comment]
What protocol are you using?

**Comment by addonravi** [comment]
I create new protocol...
my device is::eskyes620

**Comment by tananaev** [comment]
I guess you didn't call `identify` method then.

**Comment by addonravi** [comment]
yes ... you are right....

**Comment by addonravi** [comment]
Thanks ..Solve problem 
now I close this communication..
