### ISSUE TITLE
Traccar & OpenGTS further integration

### ISSUE THREAD

**Issue by rafikhamid** [tananaev/traccar#1464]
Hello there!
Thanks for making this great project open source.
I am about to start a custom GPS tracking application so I was looking around and decided to use Traccar with OpenGTS, because Traccar can receive data from a lot of devices with different protocols already and OpenGTS is not, but OpenGTS has many functionnalities that are not yet present in Traccar.

Do you have any ideas how I can make OpenGTS uses the different protocol and decodere classes ?

**Comment by tananaev** [comment]
You can find info about integrating Traccar with OpenGTS here:

https://www.traccar.org/opengts/

There is also an alternative way to integrate by forwarding location data via HTTP requests.

**Comment by rafikhamid** [comment]
thanks for the link but I have already seen that page, and it contains only how to make Traccar use OpenGTS database, it does not say how can we have OpenGTS functionnalities in Traccar, like (playing an itinerary, reports, auto update data..etc).

If this is not possible, should I implements all those functionnalities from scratch using Traccar ?

**Comment by tananaev** [comment]
This is the quote from the page:
> You will be able to use most features from OpenGTS system with advantage of support for all Traccar communication protocols

That's exactly what you asked in the original question. You get all OpenGTS features with all Traccar protocol.

**Comment by rafikhamid** [comment]
Sorry did not read that part, because I take a quick look at the code snippet in that page and it seems that it changes only database driver & query.

So how can I get almost features from OpenGTS ? 
How can I see the map and administration pages if the Traccar web interface will be disabled ?

Thanks in advance.

**Comment by tananaev** [comment]
You would have to use OpenGTS web interface. Traccar works only as a back-end to write data from devices directly into OpenGTS database.

**Comment by rafikhamid** [comment]
Thanks a lot, I will try that.
Thanks again for the great project
