### ISSUE TITLE
identified protocol

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1465]
how i can know this protocol which device name  could be ?  

my client comes witht this protocol but i can  know like this device is gt02 or al900or something ? 

attached  http://omlinux.com/proto/Communication%20Protocol-1-1.doc

here attached protocol

**Comment by tananaev** [comment]
It looks like GT06 protocol. Port 5023 in Traccar.

**Comment by perfectwebtech** [comment]
ok thanks yes working :)
