### ISSUE TITLE
Visiontek 87VTU Device Integration

### ISSUE THREAD

**Issue by rangacharyulu** [tananaev/traccar#1475]
Hi, 
Found 86 VT ,84 VT and used the same port 5069 for this device also , Receiving log in HEX format , but cant see that in database, Configured for MySQL database, I am able to save data into that from Android client but data from GPS device not stored in Database

![vtek87](https://cloud.githubusercontent.com/assets/15318574/10721972/4f599d9e-7bd1-11e5-9de7-f217c84e392f.png)

The Log file contains data like this : 

<pre>HEX:24312c564d432c3335383037323034343237313833382c32362c31302c31352c31302c34332c32302c31372e3036363431384e2c3038302e333935363637452c3030302e302c3238352c30302e382c303037342c363339302c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e372c342e302c32342c31302c303030303030303030303030302c412c302324312c564d432c3335383037323034343237313833382c32352c31302c31352c30392c31392c34302c30302e303030303030302c3030302e303030303030302c3030302e302c3030302c30302e302c303030302c363037302c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e352c342e302c39392c30302c303030303030303030303030302c562c302324312c564d432c3335383037323034343237313833382c32352c31302c31352c30392c31392c34352c30302e303030303030302c3030302e303030303030302c3030302e302c3030302c30302e302c303030302c363037302c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e362c342e312c39392c30302c303030303030303030303030302c562c302324312c564d432c3335383037323034343237313833382c32352c31302c31352c30392c31392c35302c30302e303030303030302c3030302e303030303030302c3030302e302c3030302c30302e302c303030302c363037302c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e362c342e312c39392c30302c303030303030303030303030302c562c302324312c564d432c3335383037323034343237313833382c32352c31302c31352c30392c31392c35352c30302e303030303030302c3030302e303030303030302c3030302e302c3030302c30302e302c303030302c363037302c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e362c342e322c39392c30302c303030303030303030303030302c562c302324312c564d432c3335383037323034343237313833382c32352c31302c31352c30392c32302c30302c30302e303030303030302c3030302e303030303030302c3030302e302c3030302c30302e302c303030302c363037302c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e362c342e302c39392c30302c303030303030303030303030302c562c3023</pre>

**Comment by tananaev** [comment]
I have extended support for Visiontek protocol to include this format.

**Comment by rangacharyulu** [comment]
Thank you

**Comment by rangacharyulu** [comment]
Thanks for the Update , One issue i have observed is the time from device is coming as per IST , but the decoder is adding +5.30 to the time so in database the time is saving incorrectly , Please resolve this issue

Please go through the log below: 


 HEX: 24312c564d432c3335383037323034343237313833382c32382c31302c31352c31312c30372c34302c31372e3430323035354e2c3037382e343538393237452c3030302e302c3038362c30312e322c303534322c363638362c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31332e312c342e312c32302c30372c303030303030303030303030302c412c302324312c564d432c3335383037323034343237313833382c32372c31302c31352c32322c35302c31352c31372e3435373530374e2c3037382e343736373133452c3030302e302c3333332c30312e332c303531372c363637362c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e362c342e322c39392c30372c303030303030303030303030302c412c302324312c564d432c3335383037323034343237313833382c32372c31302c31352c32322c35302c32302c31372e3435373530374e2c3037382e343736373133452c3030302e302c3035352c30312e372c303531352c363637362c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e372c342e322c39392c30362c303030303030303030303030302c412c302324312c564d432c3335383037323034343237313833382c32372c31302c31352c32322c35302c32352c31372e3435373530374e2c3037382e343736373133452c3030302e302c3036312c30312e372c303531352c363637362c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e372c342e322c39392c30362c303030303030303030303030302c412c302324312c564d432c3335383037323034343237313833382c32372c31302c31352c32322c35302c33302c31372e3435373530374e2c3037382e343736373133452c3030302e302c3036322c30312e372c303531342c363637362c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e362c342e302c39392c30362c303030303030303030303030302c412c302324312c564d432c3335383037323034343237313833382c32372c31302c31352c32322c35302c33352c31372e3435373530374e2c3037382e343736373133452c3030302e302c3033362c30312e372c303531342c363637362c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e362c342e322c39392c30362c303030303030303030303030302c412c302324312c564d432c3335383037323034343237313833382c32372c31302c31352c32322c35302c34302c31372e3435373530374e2c3037382e343736373133452c3030302e302c3331302c30312e372c303531352c363637362c302c302c302c302c302c302c302c302c30302e30302c30302e30302c30302c30302c303030302c31322e372c342e322c39392c30362c303030303030303030303030302c412c3023
2015-10-28 11:07:49  INFO: [C1511B4E] disconnected
2015-10-28 11:07:49  INFO: [C1511B4E] id: 3, time: Wed Oct 28 16:37:40 IST 2015, lat: 17.402055, lon: 78.458927, speed: 0.0, course: 86.0
2015-10-28 11:07:49  INFO: [C1511B4E] id: 3, time: Wed Oct 28 04:20:20 IST 2015, lat: 17.457507, lon: 78.476713, speed: 0.0, course: 55.0
2015-10-28 11:07:49  INFO: [C1511B4E] id: 3, time: Wed Oct 28 04:20:15 IST 2015, lat: 17.457507, lon: 78.476713, speed: 0.0, course: 333.0
2015-10-28 11:07:49  INFO: [C1511B4E] id: 3, time: Wed Oct 28 04:20:30 IST 2015, lat: 17.457507, lon: 78.476713, speed: 0.0, course: 62.0
2015-10-28 11:07:49  INFO: [C1511B4E] id: 3, time: Wed Oct 28 04:20:25 IST 2015, lat: 17.457507, lon: 78.476713, speed: 0.0, course: 61.0
2015-10-28 11:07:49  INFO: [C1511B4E] id: 3, time: Wed Oct 28 04:20:35 IST 2015, lat: 17.457507, lon: 78.476713, speed: 0.0, course: 36.0
2015-10-28 11:07:49  INFO: [C1511B4E] id: 3, time: Wed Oct 28 04:20:40 IST 2015, lat: 17.457507, lon: 78.476713, speed: 0.0, course: 310.0

**Comment by tananaev** [comment]
Traccar usually expects UTC time from devices. Is it possible to set up timezone on your device?

**Comment by rangacharyulu** [comment]
Thanks , Will change that and inform you the status
