### ISSUE TITLE
Traccar api

### ISSUE THREAD

**Issue by ethankz** [tananaev/traccar#1481]
Hi Anton, i'm now trying to use the api on my traccar server. For testing purposes, i'm using poster, a firefox extension, to login in my traccar api using my account parameters. But i always obtainthe same result : {"success":false}.
I also tried with this php script:
<pre>$url='http://ipaddress/api/login';
$data=array("email"=>"admin","password"=>"admin");

//send request
$curl=curl_init($url);

//save in separate variable instead of printing in browser
curl_setopt($curl, CURLOPT_RETURNTRANSFER,true);
curl_setopt($curl, CURLOPT_POST,true);
curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
//get response in a variable to decode json
$response=curl_exec($curl);

if ($response === false) {
    $info = curl_getinfo($curl);
    curl_close($curl);
    die('error occured during curl exec. Additioanl info: ' . var_export($info));
}
curl_close($curl);

$decoded = json_decode($response);
if (isset($decoded->response->status) && $decoded->response->status == 'ERROR') {
    die('error occured: ' . $decoded->response->errormessage);
}
var_dump($decoded);</pre>

Can you help me please

**Comment by tananaev** [comment]
Try to compare the request sent by Traccar web interface and your script and see the difference. There must be something that we're missing.
