### ISSUE TITLE
без задержки

### ISSUE THREAD

**Issue by edgiru** [tananaev/traccar#1487]
Антон поскажите где настроить что бы машина двигалась по дороге без задержки. Т.е. что бы ехала в режиме реального времени, а не прыгала через 5-10 сантиметров. треккер стоит galileosky v2.3 с тех поддержкой связался они сказали что настроить что бы треккер постоянно без перерывно отсылал на сервер пакеты. примерно раз в секунду или две.

**Comment by tananaev** [comment]
Правильно они посоветовали. Надо настроить трекер чтобы отправлял данные более часто. К сожалению пока что сервер не поддерживает отправку команд на galileosky, так что вам вручную надо сменить частоту отпавки.

**Comment by edgiru** [comment]
а настроки сервера оптимальны? трекер то я настрою это не проблема. Просто подумал может в сервере есть задержка.

**Comment by tananaev** [comment]
Никаких задержек не должно быть на сервере.

**Comment by edgiru** [comment]
спасибо!
