### ISSUE TITLE
Skypatrol in release 2.12 not connecting to server

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#1488]
Hello anton, I have installed in my server the traccar version 2.12 and I'm trying to connect a skypatrol TT870+ (plus) gps device but if I see the logger (tracker-server.log) file I cannot see anything coming  to the configured port which in my case is 5023
I was wondering if maybe there is a bug in the skypatrol protocol that is not accepting the data from the device, I have also enabled the bit27 to send the mask, this is another listener data example received:

```
GPGGA,174204.00,1059.66828,N,06349.46838,W,1,08,0.95,35.3,M,-31.8,M,,*5A
GPRMC,174204.00,A,1059.66828,N,06349.46838,W,0.000,0.0,291015,,,A*40 009F
```

**Comment by tananaev** [comment]
SkyPatrol is using UDP protocol, but port 5023 is a TCP port (in default Traccar config).

**Comment by hackerunet** [comment]
I configured skypatrol device to use TCP protocol how do you know is sending in UDP?

**Comment by tananaev** [comment]
Traccar supports only UDP for SkyPatrol protocol, so you need to configure it to use UDP.

**Comment by hackerunet** [comment]
ohhhhh ok ok ok.... how do I configure traccar for udp then? which port should I use?

**Comment by tananaev** [comment]
Default port for SkyPatrol is 5021.

**Comment by hackerunet** [comment]
and how do I enable udp for that port in config.cfg ??? using the old configuration file

**Comment by tananaev** [comment]
Depends on how old. This is what you need to add if you are using version 3.0 or higher:

<pre>&lt;entry key='skypatrol.port'&gt;5021&lt;/entry&gt;</pre>

**Comment by hackerunet** [comment]
I'm using version 2.12

**Comment by tananaev** [comment]
Then you should have following lines:
<pre>    &lt;entry key='skypatrol.enable'&gt;true&lt;/entry&gt;
    &lt;entry key='skypatrol.port'&gt;5021&lt;/entry&gt;</pre>

**Comment by hackerunet** [comment]
Anton, I received this already but no position is stored:

```
392e34373038322c572c312c30372c312e31362c32332e382c4d2c2d33312e382c4d2c2c2a3532204750524d432c3231313532392e30302c392c313035392e36363832362c4e2c30363334392e34353234332c572c302e3030302c302e302c3239313031352c2c2c412a34332030313333
```

**Comment by tananaev** [comment]
This format is not supported by SkyPatrol decoder, but you can try Enfora protocol. Port 5008 and it's using TCP, so you need to switch device back to TCP.

**Comment by hackerunet** [comment]
ok, let's check, one question, is the last skypatrol decoder compatible with the format sent by the device?

**Comment by tananaev** [comment]
No, SkyPatrol supports only binary format, but it should work with Enfora decoder.

**Comment by hackerunet** [comment]
yes anton, it worked! regards and thanks
