### ISSUE TITLE
traccar <-> OpenGTS device management

### ISSUE THREAD

**Issue by santosharjun** [tananaev/traccar#1495]
Hi,

After integrating traccar and OpenGTS, there is no web UI for traccar. can someone point me to documentation on how to manage devices and users through command line?

**Comment by tananaev** [comment]
You should manage devices through OpenGTS tools after integration.

**Comment by santosharjun** [comment]
Cool, so you meant adding devices to OpenGTS is enough? but how does traccar accept/reject data from devices? because someone can spam my server with data from non-registered devices?

**Comment by tananaev** [comment]
Traccar takes list of devices from OpenGTS database. There is no protection from spam at the moment.

**Comment by santosharjun** [comment]
Thanks for your comments
