### ISSUE TITLE
tk 206 obd 2 configeration issue

### ISSUE THREAD

**Issue by aborass** [tananaev/traccar#1503]
hi im not unexpert with computers or trackers so please be slow an patient with me :)
i have a tk 206 obd 2 tracker not sure if its original or not , it costed 35 us dollars dont know if thats cheap,,, any ways ill tel you what i did step by step and please tell me what i got wrong:
1- i configured my tracker  to demo server 104.43.219.242 by sending 803#104.43.219.242#5006# to my device then it replied (set server ok)
2- i registered to the demo server and loged in to the map main page (demo.traccar.org)
3- i added the device using the my lmei number 352887071819324
but i didnt get any results or location in the map
4- i tried changing the ports to 5036   -   5023     -   5013   -  5001 - 5002  but  none of them worked
5-tried to shorten my lmei to o887071819324   that didnt work as well
im using a new sim card with full credit and 3g - 4g service>>>>> the reseption in my area is good using my mobile but im not sure about my tracker <<< is it the location of the obd plug maybe the problem ,
i also dont get speed alerts even after setting my speed alert properly ssa#speed#1#>>
 im really confused i feel desperate after trying every thing,,, please help me

**Comment by tananaev** [comment]
Your device is using TK103 protocol. Port 5002 is the correct one.

Device unique identifier that you should be using is 087071819324.

**Comment by aborass** [comment]
thanks a lot just changed the iemi to 087071819324  and the port to 5002 and every thing worked fine
