### ISSUE TITLE
Unable to Install Traccar on Mac OS X Yosemite

### ISSUE THREAD

**Issue by Java-god** [tananaev/traccar#1505]
I'm having difficulty in Installing Traccar on my Mac. I followed the setup instructions on https://www.traccar.org/mac-os/ but I keep getting the message "command not found".

When I double click on the file, it directs me to the App store.

Please assist.

Regards,
Emezie.

**Comment by tananaev** [comment]
Which instruction gives you the error?

**Comment by Java-god** [comment]
They all did. 
sudo chmod +x traccar.run: "No such file or directory"

sudo ./traccar.run: "command not found"

sudo /opt/traccar/bin/traccar start: "command not found"

**Comment by tananaev** [comment]
Looks like you are running it from the wrong directory. You need to download Traccar and unzip the file first, and then run those commands from the place where you unzipped the archive.

**Comment by Java-god** [comment]
I had already downloaded and unzipped the file before running. Please could you explain how I can run those commands from the place where I unzipped the archive?

I dragged the traccar.run file into the terminal and when I run, I got the following:

    EmezMac:~ user$ /Users/user/Desktop/traccar-macosx-64-3.1/traccar.run 
    Verifying archive integrity... All good.
    Uncompressing traccar  100%  
    mkdir: /opt: No such file or directory
    usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
    chmod: /opt/traccar: No such file or directory
    ./setup.sh: line 12: /opt/traccar/bin/traccar: No such file or directory
    rm: /opt/traccar/setup.sh: No such file or directory
    EmezMac:~ user$

**Comment by tananaev** [comment]
Looks like `/opt` folder is missing, so you need to create it first.

After that run the file with root privileges:
<pre>sudo /Users/user/Desktop/traccar-macosx-64-3.1/traccar.run</pre>

**Comment by Java-god** [comment]
I'm sorry if my questions sound stupid, do you mean I should create a folder, name it "opt", place the Traccar folder inside before I run?

**Comment by tananaev** [comment]
No, just run following command in the terminal:
<pre>sudo mkdir /opt</pre>

**Comment by Java-god** [comment]
Thank you so much. It's installed and running. I got this;
Starting traccar. Detected Mac OSX and installed launchd daemon.
    Waiting for traccar...
    .
    .
    .
    .
    running: PID:3270
How do I proceed with the server? Is everything run from the terminal? Is there no sort of UI?

**Comment by Java-god** [comment]
Thank you so much. It's installed and running. I got this:


    Starting traccar. Detected Mac OSX and installed launchd daemon.
    running: PID:3270

How do I proceed with the server? Is everything run from the terminal or is there some sort of UI?

**Comment by tananaev** [comment]
There is a web interface: <a href="http://localhost:8082">http://localhost:8082</a>

**Comment by Java-god** [comment]
Thanks a lot.
