### ISSUE TITLE
update query

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1507]
hello

is there way can do query in  traccar.xml file ?

like if devices come without gps then update last time stamp or something ?

update timestamp in devicetable or in eventdata  i use opengts db with traccar and my own interface

or guide me which java file i can edit and update query for time only ? 

to show my client online and offline i am very in trouble so :) 

help very appriciate :)

**Comment by tananaev** [comment]
I plan to implement device status (online/offline), but it's not implemented yet.

**Comment by perfectwebtech** [comment]
1) oh can u help me or give hint which file i can make like this work in java ? 

or when u can make it done i need it  urgent on my gt06n with opengts database and

my own interface 


2) how i can get or call all values like battery level, gps signal, to my opengts database using traccar any hint something ?

**Comment by tananaev** [comment]
1) If you need it urgently, you can add some code to the decoder to handle those messages:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gt06ProtocolDecoder.java

2) You can access all extra data in the query via `:other` parameter.
