### ISSUE TITLE
help update

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1511]
hello

1) is it database.updateposition 

comes values from datamanage.java ?

regarding heartbit i can capture time with this query ? for update time query ?

<pre>&lt;entry key='database.updateLatestPosition'&gt;
UPDATE device SET lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE deviceID = RIGHT(CONCAT('000000000000000', :deviceId), 15);
&lt;/entry&gt; </pre>

?  is it correct ? as from datamanage.java comes like values during heartbit i can capture time as in updatepossition query right ? or help me 

2)  here below config u can help me or guide me regarding what values i can capture for gps signal, battery info and other few data from gt06n :) can u give me hint just as name of value like there is

gpssignal i can capture value or which java file i can see values to pass in xml with query ? as well above question 1 time also and other values cell info satelite , battery level  etc etc ? 

<pre>    &lt;entry key='web.enable'&gt;false&lt;/entry&gt;
    &lt;entry key='web.port'&gt;8082&lt;/entry&gt;
    &lt;entry key='web.path'&gt;/opt/traccar/web&lt;/entry&gt;

    &lt;entry key='geocoder.enable'&gt;true&lt;/entry&gt;
    &lt;entry key='geocoder.type'&gt;google&lt;/entry&gt;

    &lt;entry key='logger.enable'&gt;true&lt;/entry&gt;
    &lt;entry key='logger.level'&gt;all&lt;/entry&gt;
    &lt;entry key='logger.file'&gt;/opt/traccar/logs/tracker-server.log&lt;/entry&gt;

    &lt;!-- DATABASE CONFIG --&gt;

    &lt;entry key='database.driver'&gt;com.mysql.jdbc.Driver&lt;/entry&gt;
    &lt;entry key='database.url'&gt;jdbc:mysql://localhost:3306/iat?allowMultiQueries=true&lt;/entry&gt;
    &lt;entry key='database.user'&gt;keval&lt;/entry&gt;
    &lt;entry key='database.password'&gt;Keval0987&lt;/entry&gt;

    &lt;entry key='database.selectDevicesAll'&gt;
        SELECT deviceID AS id, deviceID AS uniqueId FROM device WHERE deviceID REGEXP '^[0-9]+$';
    &lt;/entry&gt;

    &lt;entry key='database.insertPosition'&gt;
        START TRANSACTION;
           SELECT @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM FROM device WHERE imeiNumber = :device_id;
        SELECT @lastSpeed := speedKPH FROM eventdata WHERE accountID = @accountID AND deviceID = @deviceID ORDER BY timestamp DESC LIMIT 1;
        SELECT @distance := (ACOS(SIN(@lastLatitude * PI() / 180) * SIN(:latitude * PI() / 180) + COS(@lastLatitude * PI() / 180) * COS(:latitude * PI() / 180) * COS((:longitude * PI()/180)-(@lastLongitude*PI()/180)))*6371000);
	        
	UPDATE device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastOdometerKM = @odometer + @distance, lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE deviceID = RIGHT(CONCAT('000000000000000', :deviceId), 15);

        SELECT @accountID := accountID, @deviceID := deviceID FROM device WHERE imeiNumber = :device_id;

SELECT @fakeStatus := CASE
		WHEN (:speed &gt; 1) AND (@distance = 0) THEN 61713
		WHEN (:speed &gt; 1) AND (@distance &gt; 0) THEN 61714
		WHEN (:speed &amp;lt; 1) AND (@distance &gt; 0) THEN 61715
		ELSE 61716
	END;        

	
	INSERT INTO eventdata (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, creationTime, address)
        VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), @fakeStatus, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', @distance, @odometer + @distance, UNIX_TIMESTAMP(NOW()), :address);
        COMMIT;
    &lt;/entry&gt;

    &lt;entry key='database.updateLatestPosition'&gt;
UPDATE device SET lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE deviceID = RIGHT(CONCAT('000000000000000', :deviceId), 15);
    &lt;/entry&gt;</pre>

**Comment by tananaev** [comment]
1) Heartbeat messages are not recorder in the database in the current version.

2) All additional data is stored in `:other` parameter in XML or JSON format. You can extract it if you want using standard MySQL functions (in case of XML). Set of attributes depends on the protocol you are using and on the type of messages your device sends.

**Comment by perfectwebtech** [comment]
1) but which file i can make changes in funtion java u can help me like pipe files or datamanager.java ? :) 

2) is it example there something little example ? so i can follow ?

**Comment by tananaev** [comment]
1) You need to change protocol decoder class if you want to decode heartbeat messages.

2) For example you can use following function call to get number of satellites (assuming that you are using XML format):

<pre>ExtractValue(:other, '/info/sat')</pre>
