### ISSUE TITLE
command hint

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1513]
hello,

u can give me command hint like with opengts used traccar and my interface is used php so 

how i should play with opengts database and gt06n commands how i can fire with java directly communication or something could be ? easy way or some ideas, guidance plz

**Comment by tananaev** [comment]
There is an API you can use from your code:

https://www.traccar.org/traccar-api/

**Comment by perfectwebtech** [comment]
ok thanks here any command can work ? 


and traccar-api i should change query according to opengts database ? 

and there is reply back to database where will be save example any command can work like i want to set ip adddress port as wel so any command will work ? 

and where is in api  i can change sql structure according to opengts and data will save in eventdata or else ? by api when device give reply of command ?

**Comment by tananaev** [comment]
> ok thanks here any command can work ?

Only some commands are implemented for some protocol, but it's possible to extend support.

> and traccar-api i should change query according to opengts database ?

You would probably need to change/add some queries...

> and there is reply back to database where will be save example any command can work like i want to set ip adddress port as wel so any command will work ?

The API is just for sending commands. Replies are handled by protocol decoders like any other data.

> and where is in api i can change sql structure according to opengts and data will save in eventdata or else ?

The API doesn't depend on the database structure, but queries are required for authentication and permissions check.

> by api when device give reply of command ?

See my answer for the third question.
