### ISSUE TITLE
To call heartbeat class

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1514]
For getting heartbeat record i had develop one function on gt06decoder

then as follow 

i want to call defaultDataHandeler.java's handleUpdatePosition function from

StandardLoggingHandler from BasePipelineFactory.java

DefaultDataHandler.java

<pre> @Override
    protected Position handleUpdatePosition(Position positionUpdate) 
    {
            try {
        //Context.getDataManager().addPosition(position);
        //Position lastPosition = Context.getConnectionManager().getLastPosition(position.getDeviceId());
        //if (lastPosition == null || position.getFixTime().compareTo(lastPosition.getFixTime()) > 0) {
            Context.getDataManager().updateLatestPosition(positionUpdate);
        //}
        } catch (Exception error) {
            Log.warning(error);
        }

    return positionUpdate;
    }</pre>

**Comment by tananaev** [comment]
Why do you want to call `DefaultDataHandler` from `StandardLoggingHandler` directly? They are already in the same pipeline, so if you decode everything correctly, the message will get to the logging handler first and then to the data handler.

**Comment by perfectwebtech** [comment]
ok
so please guide me how can i call from standardLoggingHandler on BasePipelineFactory.java

another function like handlePosition

protected Position handleUpdatePosition(Position positionUpdate) 

because i want to update time of device at heartbeat record


i had make one object on gt06protocoldecoder.java

protected Object decodeUpdater(
            Channel channel, SocketAddress remoteAddress, Object msg)
            throws Exception {

        ChannelBuffer buf = (ChannelBuffer) msg;

        if (buf.readByte() != 0x78 || buf.readByte() != 0x78) {
            return null;
        }

        int length = buf.readUnsignedByte(); // size
        int dataLength = length - 5;

        int type = buf.readUnsignedByte();

        if (type == MSG_STATUS) 
        {
            Position position = new Position();
                position.setDeviceId(getDeviceId());
                position.setProtocol(getProtocolName());

                DateBuilder dateBuilder = new DateBuilder(timeZone)
                        .setDate(buf.readUnsignedByte(), buf.readUnsignedByte(), buf.readUnsignedByte())
                        .setTime(buf.readUnsignedByte(), buf.readUnsignedByte(), buf.readUnsignedByte());
                position.setTime(dateBuilder.getDate());
                
                if (MESSAGES_STATUS.contains(type)) {
                        position.set(Event.KEY_ALARM, true);

                        int flags = buf.readUnsignedByte();

                        position.set(Event.KEY_IGNITION, (flags & 0x2) != 0);
                        // TODO parse other flags

                        // Voltage
                        position.set(Event.KEY_POWER, buf.readUnsignedByte());

                        // GSM signal
                        position.set(Event.KEY_GSM, buf.readUnsignedByte());
                    }
                
                // Index
                if (buf.readableBytes() > 6) {
                    buf.skipBytes(buf.readableBytes() - 6);
                }
                int index = buf.readUnsignedShort();
                position.set(Event.KEY_INDEX, index);
                sendResponse(channel, type, index);
                return position;
        }

        return null;
    }

for this one function on basedatahandler.java

protected final Object decodeUpdater(ChannelHandlerContext ctx, Channel channel, Object msg) throws Exception {
                    
        if (msg instanceof Position) {
            return handleUpdatePosition((Position) msg);
        }
        
        StringBuilder s = new StringBuilder();
        s.append("decodeUpdater: ");
        Log.info(s.toString());
        
        return msg;
    }
    
    protected abstract Position handleUpdatePosition(Position position);

and for this Defaultdatahandler.java one method

 @Override
    protected Position handleUpdatePosition(Position positionUpdate) 
    {
            try {
        //Context.getDataManager().addPosition(position);
        //Position lastPosition = Context.getConnectionManager().getLastPosition(position.getDeviceId());
        //if (lastPosition == null || position.getFixTime().compareTo(lastPosition.getFixTime()) > 0) {
            Context.getDataManager().updateLatestPosition(positionUpdate);
        //}
        } catch (Exception error) {
            Log.warning(error);
        }

    return positionUpdate;
    }

thanks for your help

waiting for your reply
