### ISSUE TITLE
power and course

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1515]
1) i can pass power and course in query value ? 

2) i am getting like erorr what could be problem ? 
when i try to update query in xml file  with power and course variable then happen like this error 

<pre>21:14:48  WARN: No value specified for parameter 20 - SQLException (... < QueryBuilder:428 < DataManager:345 < DefaultDataHandler:27 < ...) 2015-11-08 21:14:48  INFO: [7CFDF4C7] id: 862304021265866, time: Thu Jan 01 05:30:00 IST 1970, lat: 0.0, lon: 0.0, speed: 0.0, course: 0.0
</pre>

**Comment by tananaev** [comment]
Can I see the query?

**Comment by perfectwebtech** [comment]
1)  is there way i can call query for hex data of only heartbit data no gps during in databasemanager.java or query build like what we call clases of database.insertposition like

i can create database.updateheartbit directly and call update query and case deviceId i can get and update during heartbit ? 




2) 
yes here is query 


<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    

    <entry key='web.enable'>false</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>




    


   <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/iat?allowMultiQueries=                                                                                                                     true</entry>
    <entry key='database.user'>root</entry>
    <entry key='database.password'>Keval@0987</entry>

 <entry key='database.selectDevicesAll'>
        SELECT deviceID AS id, deviceID AS uniqueId FROM device WHERE deviceID R                                                                                                                     EGEXP '^[0-9]+$';
</entry>

<entry key='database.linkDevice'>
     UPDATE device SET lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTime                                                                                                                      = UNIX_TIMESTAMP(NOW()) WHERE deviceID = RIGHT(CONCAT('000000000000000', :device                                                                                                                     Id), 15);
    </entry>

    <entry key='database.insertPosition'>
        START TRANSACTION;
           SELECT @lastLatitude := lastValidLatitude, @lastLongitude := lastVali                                                                                                                     dLongitude, @odometer := lastOdometerKM FROM device WHERE imeiNumber = :deviceId                                                                                                                     ;
        SELECT @lastSpeed := speedKPH FROM eventdata WHERE accountID = @accountI                                                                                                                     D AND deviceID = @deviceID ORDER BY timestamp DESC LIMIT 1;
        SELECT @distance := (ACOS(SIN(@lastLatitude * PI() / 180) * SIN(:latitud                                                                                                                     e * PI() / 180) + COS(@lastLatitude * PI() / 180) * COS(:latitude * PI() / 180)                                                                                                                      * COS((:longitude * PI()/180)-(@lastLongitude*PI()/180)))*6371000);

        UPDATE device SET lastValidLatitude = :latitude, lastValidLongitude = :l                                                                                                                     ongitude, lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastOdometerKM = @odometer +                                                                                                                      @distance, lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE deviceID = RIGHT(CONCAT                                                                                                                     ('000000000000000', :deviceId), 15);

        SELECT @accountID := accountID, @deviceID := deviceID FROM device WHERE                                                                                                                      imeiNumber = :deviceId;

SELECT @fakeStatus := CASE
                WHEN (:speed > 1) AND (@distance = 0) THEN 61713
                WHEN (:speed > 1) AND (@distance > 0) THEN 61714
                WHEN (:speed &lt; 1) AND (@distance > 0) THEN 61715
                ELSE 61716
        END;


        INSERT INTO eventdata (accountID, deviceID, timestamp, statusCode, latit                                                                                                                     ude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, cr                                                                                                                     eationTime, address, other, power, course, extended_info)
        VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), @fakeStatus, :lati                                                                                                                     tude, :longitude, :speed * 1.852, :course, :altitude, '', @distance, @odometer +                                                                                                                      @distance, UNIX_TIMESTAMP(NOW()), :address, :allinfo, :allpower, :allcourse, :e                                                                                                                     xtended_info);
        COMMIT;
    </entry>

        <entry key='database.updateLatestPosition'>
       UPDATE device SET lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTim                                                                                                                     e = UNIX_TIMESTAMP(NOW()) WHERE DeviceId = RIGHT(CONCAT('000000000000000', :devi                                                                                                                     ceId), 15);
    </entry>

    <entry key='database.updateDevice'>
  UPDATE device SET lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTime = U                                                                                                                     NIX_TIMESTAMP(NOW()) WHERE DeviceId = RIGHT(CONCAT('000000000000000', :deviceId)                                                                                                                     , 15);
</entry>

<!--

<entry key='database.driver'>org.h2.Driver</entry>
    <entry key='database.url'>jdbc:h2:/opt/traccar/data/database</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'></entry>

    <entry key='database.checkTable'>traccar</entry>

    <entry key='database.selectSchemaVersion'>
        SELECT * FROM traccar;
    </entry>

    <entry key='database.createSchema'>
        CREATE TABLE "user" (
        id INT PRIMARY KEY AUTO_INCREMENT,
        name VARCHAR(128) NOT NULL,
        email VARCHAR(128) NOT NULL UNIQUE,
        hashedPassword VARCHAR(128) NOT NULL,
        salt VARCHAR(128) DEFAULT '' NOT NULL,
        readonly BIT DEFAULT 0 NOT NULL,
        admin BIT DEFAULT 0 NOT NULL,
        map VARCHAR(128),
        language VARCHAR(128),
        distanceUnit VARCHAR(128),

**Comment by tananaev** [comment]
1) I have added some changes to detect device online status. You can use some of that code.

2) I guess the problem is with your CASE statement. Maybe it should end with `END CASE`.

**Comment by perfectwebtech** [comment]
where is your code ? or file where i can download from github ?  traccar.xml or else ?

**Comment by perfectwebtech** [comment]
src/org/traccar/BaseProtocolDecoder.java


is it here in test or in traccar ? i see 4 hours edited files so is it ?
