### ISSUE TITLE
command with opengts

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1516]
i can call command which file i can fire like query  and class call ? 

like in opengts db used there is one command  devicecommand

so which file better option i should put class calle verytime and check table if apear data of commands and then class will call to device and send command and will get reply in any one of table ? 

any guidance or help like which files i can call better my class for commands of gt06n

**Comment by tananaev** [comment]
As I said before, you can use API to send commands. If you still want to do it via database, you have two options:

1. Have a timer to check if new commands are available in the database table.
2. Check for new commands in some existing event. For example when you receive message from device.
