### ISSUE TITLE
for heartbeat updateLatestPosition call

### ISSUE THREAD

**Issue by perfectwebtech** [tananaev/traccar#1517]
how can i call

Context.getDataManager().updateLatestPosition(position);

from Basepipelinefactory.java file

because i want to update device timings for heartbeat device is active or not

on traccar.xml file i  had setup

<entry key='database.updateLatestPosition'>
       UPDATE device SET lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE DeviceId = RIGHT(CONCAT('000000000000000', :deviceId), 15);
    </entry>

please guide me which file i have to change for call database.updateLatestPosition

i got the concept of hax but how to call this functions 

guide me

thanks

waiting for your reply

**Comment by tananaev** [comment]
Look. In last 4 days you created 9 issues basically asking the same questions. Please study the code first and then ask specific questions if you have any. Also, please keep one issue for one question.

**Comment by perfectwebtech** [comment]
hello sorry 

acctually we are working here 4 to 5 person in same project it's big so 

asking more question sorry :) 

but almost understand about online thing as u did i think will work seems getting status there so 

can customization query but thanks for your help very appreciate really 

case end of project i will donation for you :) 

thanks for your help :)

**Comment by tananaev** [comment]
It would make sense for every developer to have their own GitHub account. If you have any specific questions feel free to ask, but keep same questions in a single GitHub thread.

If you have any customizations, it's better to contact me via email (address is in profile).

**Comment by perfectwebtech** [comment]
yes thanks for your reply and support anton

is it gt06n support battery , gps signal gsm signal ? 

i can get from extended_info or something i should implement ?

**Comment by perfectwebtech** [comment]
oh sorry anton i got it sometime comes and sometime not comes so may be

during heartbit will not come extended_info :) 

ok got it thanks all comes in other and extended info
