### ISSUE TITLE
Traccar version 2.12 storing Localtime instead UTC time

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#1522]
Hi anton, I want to remove from traccar from all protocols the capacity of storing the gps time in Localtime
I found this in the protocol gps103 and I want to know how to change this to completely remove localtime and store utctime only.
```
private static final Pattern pattern = Pattern.compile(
            "imei:" +
            "(\\d+)," +                         // IMEI
            "([^,]+)," +                        // Alarm
            "(\\d{2})/?(\\d{2})/?(\\d{2})\\s?" + // Local Date
            //"(\\d{2}):?(\\d{2})(?:\\d{2})?," +  // Local Time ->>>>>>>>> REMOVE THIS
            "[^,]*," +
            "[FL]," +                           // F - full / L - low
            "(?:(\\d{2})(\\d{2})(\\d{2})\\.(\\d+)|" + // Time UTC (HHMMSS.SSS)
            "(?:\\d{1,5}\\.\\d+))," +
            "([AV])," +                         // Validity
            "(\\d+)(\\d{2}\\.\\d+)," +          // Latitude (DDMM.MMMM)
            "([NS])," +
            "(\\d+)(\\d{2}\\.\\d+)," +          // Longitude (DDDMM.MMMM)
            "([EW])?," +
            "(\\d+\\.?\\d*)?,?" +               // Speed
            "(\\d+\\.?\\d*)?,?" +               // Course
            "(\\d+\\.?\\d*)?,?" +               // Altitude
            "([^,]+)?,?" +
            "([^,]+)?,?" +
            "([^,]+)?,?" +
            "([^,]+)?,?" +
            ".*");

```

```
// Timezone calculation
        if (utcHours != null && utcMinutes != null) {
            int deltaMinutes = (localHours - Integer.valueOf(utcHours)) * 60;
            deltaMinutes += localMinutes - Integer.valueOf(utcMinutes);
            if (deltaMinutes <= -12 * 60) {
                deltaMinutes += 24 * 60;
            } else if (deltaMinutes > 12 * 60) {
                deltaMinutes -= 24 * 60;
            }
            time.add(Calendar.MINUTE, -deltaMinutes);
        }
        position.setTime(time.getTime());

```

**Comment by tananaev** [comment]
Traccar always stores UTC time.

The problem with GPS103 protocol is that it doesn't send full UTC date and time, so I need to calculate it from exiting data.

**Comment by hackerunet** [comment]
I always have the same trouble if I change something in my server I start receiving wrong time values.

**Comment by tananaev** [comment]
Please provide HEX message samples and more info about the problem.

**Comment by hackerunet** [comment]
Look anton: the Hexadecimal data
696d65693a3335393731303034363836303730372c747261636b65722c3135313131313036343634332c2c462c3232343634322e3030302c412c313030342e313334342c4e2c30363931362e333433382c572c302e30302c303b

The ascii:
imei:359710046860707,tracker,151111064643,,F,224642.000,A,1004.1344,N,06916.3438,W,0.00,0;

The tracking table is storing this:
| 359710046860707 | 2015-11-10 18:26:41 |

So, traccar is storing the data in localtime not UTC the system date is:
mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2015-11-10 22:58:52 |
+---------------------+
1 row in set (0.00 sec)

My os date:
[root@server1 ~]# date
mar nov 10 22:59:03 UTC 2015
[root@server1 ~]#

**Comment by tananaev** [comment]
Are you sure you provided matching record from your MySQL database. I doubt that because even minutes and seconds don't match the original message. What is the local timezone?

**Comment by hackerunet** [comment]
is the same gps, is impossible for me to give the same exact record it has seconds or minutes of difference the important thing is to get the last received message from the same gps because I get the database last value but if I check tracker-server.log I already have 2 more values for example so I'm seeing the live data being received between over 10 K records received each minute

**Comment by tananaev** [comment]
Can you then provide the log output. Traccar should print the decoded location info including time.

**Comment by hackerunet** [comment]
this is the last received:
[root@server1 ~]# tail -f /opt/traccar/logs/tracker-server.log | grep 359710046860707
2015-11-10 18:37:47  INFO: device: 359710046860707, time: Tue Nov 10 18:37:47 VET 2015, lat: 10.068891666666667, lon: -69.27254166666667

**Comment by hackerunet** [comment]
What I see there is that traccar has a VET local timezone instead of UTC, can you see it?

**Comment by tananaev** [comment]
I think I know what the problem is. You manually changed your server timezone to UTC, but for some reason Java doesn't respect that setting.

The solution is to force timezone for Java in the `wrapper.conf` file:
<pre>wrapper.java.additional.1=-Duser.timezone=UTC</pre>

**Comment by hackerunet** [comment]
Yeah it was exactly that, everything is solved now so finally we found the problem, I have opened this same case before with different traccar versions, make sure to save this is the problems vault... Regards and thanks anton.

**Comment by wekaz** [comment]
where to put wrapper.conf?
