### ISSUE TITLE
authorization

### ISSUE THREAD

**Issue by vladamirk** [tananaev/traccar#1526]
Hi Anton,
We stacked with next problem, when we trying to do authorization with angular service thru standard API we get response "success:true" but cookies not saved on client side as you can see from screenshots, also we tried to do device/get and obviously "success:false". You can see console.log info on screenshots below. Thank you in advance for any help.
```javascript
$http({
                method: 'POST',
                url: 'http://gps.cheetah.pro/api/login',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded'
                },
                transformRequest: function(obj) {
                    var str = [];
                    for(var p in obj)
                        str.push(encodeURIComponent(p) + "=" + encodeURIComponent(obj[p]));
                    return str.join("&");
                },
                data: {
                    email: 'admin',
                    password: 'admin'
                }
            }).success(function(res, status, headers){
                console.log(headers('Set-Cookie'));
                console.log(headers());
                console.log($cookies.getAll());
                //if(!res.data.success) {
                //    console.error("Invalid email or password");
                //    return false;
                //}

                //$timeout(function () {
                //    console.log(res, headers('JSESSIONID'));
                //    console.log($window.sessionStorage);
                //});

                $http.get('http://gps.cheetah.pro/api/device/get').then(function(data){
                    console.log(data);
                });
```

![dff8f43a9e3d0039701c8c6f1695a7a8a1e480cfa0462fb740 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/8604419/11133852/65cff170-894d-11e5-8b5c-f47135d77357.jpg)

![7608fb10bf0c331f8d8c956960dcabd494a01f0b7e9e336be0 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/8604419/11133805/169fca26-894d-11e5-8427-c3cf7d70b67c.jpg)
![7ccdafa26b55319205b30b51f6e564303d7bd110ae22f68ba3 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/8604419/11133810/1eafb7e4-894d-11e5-9aea-76a9a5d677ef.jpg)

**Comment by tananaev** [comment]
I think the problem is that you app and Traccar API are running on different hosts, so cookie doesn't work for this CORS request. Not sure why though.

**Comment by vladamirk** [comment]
Thank you for fast response, yes you right, we hosted our app and Traccar on different hosts, but shouldn't it be able to get logged in? I mean I thought that's the purpose of login API so you can use it with other services.

**Comment by tananaev** [comment]
It should definitely be possible, but I haven't tried it myself, so there might be some issues. You can try to ask in #1434 if it works for @reviloera.

**Comment by vladamirk** [comment]
Okay, thank you.

**Comment by vladamirk** [comment]
Hello Anthon,
I think we need some kind of authorization with token, that sends as a parameter, cause cookies not working, browser not saving them. That's my code on plunker, maybe you can test it and give me some ideas please.
http://plnkr.co/edit/6SPmUWOWDZl2blVe4WP1

**Comment by reviloera** [comment]
BTW am using angularjs and its working perfectly well. 

Am using restangular for my API calls. I can share with you my code if you are intrested

**Comment by vladamirk** [comment]
It would be great, also I shared my plunker, maybe you can show me there?

**Comment by reviloera** [comment]
``` javascript
angular.module('your-app', ['restangular'])
.constant('API_URL', 'http://xx.xxx.11.103:8082/')
.config(function(RestangularProvider){
RestangularProvider.setDefaultHttpFields({
      withCredentials: true   // this will handle cookie sessions for you
    });
});

// on your controller file you will have something like this
angular.module('your-app').controller('MainCtrl', function($scope, Restangular,API_URL,$q) {
  Restangular.setBaseUrl(API_URL); // set your api base url
 //asume we want to login
var login_url = Restangular.all('api/login');

var data = {
email : 'v@v.com',
password : 'pass'
};

var data_encoded = $.param(data);    // ensure you have jquery loaded on your application

login_url.customPOST(data_encoded,
          undefined,
          undefined,
          {'Content-Type': "application/x-www-form-urlencoded; charset=UTF-8"})
          .then(function(response){

// TODO   login success
})

// if you want to sync data
var devices_url = Restangular.all('api/');
       
devices_url.customGET('async').then(function (response) {
          var syncData = response.plain();
        });

});
```

**Comment by vladamirk** [comment]
Thank you, but I tried to use "withCredentials: true" and its give me error 
```
XMLHttpRequest cannot load http://gps.cheetah.pro/api/login. Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://example.com:5000' is therefore not allowed access.
```

**Comment by reviloera** [comment]
I think the issue is with the CORS am sending you my configuration of this file then you recompile `src/org/traccar/web/BaseServlet.java`

**Comment by vladamirk** [comment]
Can you reattach it?

**Comment by reviloera** [comment]
ok am sending

**Comment by vladamirk** [comment]
@reviloera , I'm still waiting 
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by reviloera** [comment]
sent sorry my network is veeeery sloooow

**Comment by reviloera** [comment]
I have sent check mail

**Comment by vladamirk** [comment]
Nothing in mail.

2015-11-13 12:12 GMT-08:00 reviloera <notifications@github.com>:

**Comment by vladamirk** [comment]
Just copy paste it in here, it will work.

**Comment by reviloera** [comment]
http://codeshare.io/qmdPp

**Comment by vladamirk** [comment]
Thank you, it must work, but is it open XSS attack possibilities?

**Comment by reviloera** [comment]
yea its kind of unsecure , but it works if you have a better solutin share

**Comment by vladamirk** [comment]
Yes, I already asked if Anton will add token authorization.
https://github.com/tananaev/traccar/issues/1526#issuecomment-156485377

**Comment by reviloera** [comment]
great that will  be owesome

**Comment by vladamirk** [comment]
Thank you for help.

**Comment by reviloera** [comment]
welcome and sorry for my slow internet

**Comment by tananaev** [comment]
I have merged #1510.

**Comment by vladamirk** [comment]
Basic Authorization is unsecured (as well as the solution given by @reviloera). Enabling Access-Control-Allow-Credentials is insecure. Therefore I'm coming up with the next possible ways to solve the problem:
1. Create a Origin white list in config file, which is reloaded upon every Traccar service restart.
2. Create a token-based auth (token (i.e. JSESSIONID or whatever) is sent after the successful authorization and can be used in further requests.

**Comment by tananaev** [comment]
Can you provide some links explaining why Basic Authorization and Access-Control-Allow-Credentials are both insecure.

**Comment by tananaev** [comment]
I did some research and I guess you are talking about "cross-site request forgery" issue. I think it makes sense to make Origin configurable.

**Comment by vladamirk** [comment]
Thank you.

**Comment by tananaev** [comment]
Added new config parameter to specify `Access-Control-Allow-Origin`. Example of usage:
<pre>&lt;entry key='web.origin'&gt;http://mozilla.com&lt;/entry&gt;</pre>

**Comment by vladamirk** [comment]
Sorry if I'm being annoying, just trying to use amazing service, and implement some features that would be useful, but I don't know java and can't do it by my self. With current update i can apply it for 1 domain, can you create something like list of ALLOWED_ORIGIN which separate all origins with comma

**Comment by tananaev** [comment]
Added support for multiple domains.

**Comment by vladamirk** [comment]
Thank you, it worked.

**Comment by vipien** [comment]
Hello, I need your help. I added this line in traccar.xml

 `    <entry key='web.origin'>http://localhost:1080</entry>`

but the problem persist. The error is 

https://cloud.githubusercontent.com/assets/8376694/12899074/e7375572-ce81-11e5-9556-aca64e96131e.png

Please help me!

**Comment by vladamirk** [comment]
Check your port, on screenshot it's different

On Monday, 8 February 2016, vipien <notifications@github.com> wrote:

> Hello, I need your help. I added this line in traccar.xml
>
> <entry key='web.origin'>http://localhost:1080</entry>
>
> but the problem persist. The error is
>
>
> https://cloud.githubusercontent.com/assets/8376694/12899074/e7375572-ce81-11e5-9556-aca64e96131e.png
>
> Please help me!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/1526#issuecomment-181568048>.
>


-- 
Sent from Gmail Mobile

**Comment by vipien** [comment]
@vladamirk The port in web.origin is the origin url port? Please check my screenshoot again. Thanks
