### ISSUE TITLE
Question about front end

### ISSUE THREAD

**Issue by sosoxuc** [tananaev/traccar#1543]
Hi there
Great work, really great

One question. Would not it be better to migrate on Bootstrap. I see bigger advantages. Licencing, Speed, Mobile device compatibility and so on.

And another one. Can I participate in your project ? I can help on front end for example.

Thanks and best wishes

**Comment by tananaev** [comment]
Licensing shouldn't be a problem. GPLv3 is compatible with Apache 2.0.

How can you compare Bootstrap (basically a CSS framework) to ExtJS (a JavaScript framework)? Bootstrap doesn't have any functionality except layout and even its layout is not very suitable for SPA style required for GPS tracking platform.

Of course you welcome to participate. Any ideas what you want to work on?

**Comment by sosoxuc** [comment]
Ideas are very very many :)
I will try to send you them to mail

**Comment by sosoxuc** [comment]
I will rebuild fork on Bootstrap and show you as a first stap :smile:
