### ISSUE TITLE
Automated Migrations [New feature request]

### ISSUE THREAD

**Issue by 4nonym0us** [tananaev/traccar#1544]
Hello,
It would be great if you could implement Automated migrations.
Check this out: http://flywaydb.org/getstarted/firststeps/maven.html. Such a tool can help you to get rid of all these custom migrations scripts you have to write every time you release a new traccar version (i.e. https://www.traccar.org/update-from-3-1-to-3-2/). There is also Java API support present:
```
Flyway flyway = new Flyway();
flyway.setDataSource(url, user, password);
flyway.migrate();
```
In my opinion, It's really useful for a contributors – everybody should be able to update their own databases just by executing single command (in a case if you consider using maven) or just by running the executable (in a case if you consider using Java API).

**Comment by tananaev** [comment]
Can you please explain how it solves the problem of writing scripts manually?

**Comment by 4nonym0us** [comment]
I should've said that **you (as a main developer and the only person who make changes to the database) will need to write the initial** SQL statement anyway in thiscase, but **contributors and users won't be forced to make a manual migrations** (for example, I'm running traccar on a VPS and I needed to download DB viewer for H2 to execute the migration statements by myself. All this is pretty annoying and can be automated).
If you need really automatic migrations (when you don't need to write SQL statements by yourself), you should use any ORM technology (i.e. http://javalite.io/database_migrations) as a Data Access layer in your app (to be honest, It's really 'dirty' to write pure SQL statements and save them in config file to be fetched from the application lately).
I'm not Java developer (I mostly use C#/.NET when I need to set up a back-end), therefore I can't advice you any good solution based on my personal experience, but I advice you to make a research on these libraries:
* Flyway
* Liquibase
* c5-db-migration
* dbdeploy
* mybatis
* MIGRATEdb
* migrate4j
* dbmaintain
* AutoPatch
Some of them (at least **migrate4j**) don't use pure SQL – you write Java code for the migration, but I'm not sure if there is H2 support.
You should consider using automatic migrations altogether with ORM technology if you really want to forget about SQL forever, but if it's fine for you to write SQL statements for migrations, you should take a look on tools like **Flyway**.
I think that you made a great solution for GPS tracking and I really appreciate this. If you still have any questions, fell free to ask them. I'd be glad to provide you any help.

**Comment by vitalidze** [comment]
I totally agree with @4nonym0us The migrations in current implementation is the pain for the end user. If you use `Liquibase` you can write your migrations in DSL without writing any SQL queries. Then the library will run proper SQL statements according to the specific of underlying database. The liquidbase supports a large variety of databases (including oracle, mysql, h2, postgresql, MS SQL), the number is way greater then for flyway. I recommend to choose the liquidbase if you will want to switch.

**Comment by tananaev** [comment]
Liquibase sounds like a good option. I will take a look at this option.

**Comment by tananaev** [comment]
I have implemented Liquibase support. Now I need to test migration scripts at least for H2 and MySQL.

**Comment by vitalidze** [comment]
The implementation looks very good and readable. Thank you for spending time on that! I hope it will work fine for all supported versions at least as of 3.x. I think I will need to either disable or rewrite these migrations to support them in my traccar web UI mod. Looks like `database.changelog` configuration option may be of help, right?

**Comment by tananaev** [comment]
Yes, the idea is that if you provide "database.changelog" configuration parameter, Traccar will use it.

**Comment by vitalidze** [comment]
Cool, thanks. And if there are no such parameter then it won't do anything related with DB migration?

**Comment by tananaev** [comment]
Correct.

**Comment by 4nonym0us** [comment]
@tananaev, thanks a lot!
