### ISSUE TITLE
"Geofence" [New feature request]

### ISSUE THREAD

**Issue by sosoxuc** [tananaev/traccar#1547]
Alert is sent to user when:
- [ ] Device leaves specified area (prior defined by user)
- [ ] Speed is higher then restricted
- [ ] Some other cases

alert is sent to:
- [ ] eMail
- [ ] Web hook - good for SMS services
- [ ] Something else

**Comment by tananaev** [comment]
This feature is on the roadmap.

**Comment by guilhermesouza** [comment]
+1 very good.

Em seg, 23 de nov de 2015 às 20:44, Anton Tananaev <notifications@github.com>
escreveu:

**Comment by fabriziomazzoni** [comment]
It would be interesting to have a field in the Database or an event that defines wether the device is in a geofence defined by user or not. It could be used in management applications which use route steps and not mapping. The application could warn the user to do some action by checking in the device geofence status.

Example:

I define a route in my application such as "New York -> Philadelphia -> Toronto"

I define these 3 geofences (New York, Philadelphia, Toronto) in traccar. When a device enters one of them the status gets changed to "In New York/Philadelphia/Toronto". From my application I check whether the route step matches the geofence status and from there I can remind my user to do something. It could be interesting as sometimes we could have hundreds if not thousands of devices in traccar and keeping track of them visually would be quite difficult. Having an event triggering makes life so much simpler.

**Comment by tananaev** [comment]
Thanks for feedback. I still haven't decided how geofencing feature should work, but it's definitely on the roadmap for Traccar project.

**Comment by glbatistabh** [comment]
+1 very good.

**Comment by Abyss777** [comment]
Looks like all implemented.
