### ISSUE TITLE
Как добавить googl или яндекс карты на сервер? 

### ISSUE THREAD

**Issue by StormFront33** [tananaev/traccar#1549]
Здравствуйте, установил сервер, в bing зарегистрировал ключ, всё работает, всё нравится, только карт мало. Подскажите пожалуйста как установить googl или yandex карты на сервер?

**Comment by tananaev** [comment]
Посмотрите вот эту страницу:

https://www.traccar.org/map-layers/

К сожалению Yandex карты пока не поддерживаются из-за нестандартной проекции.

**Comment by StormFront33** [comment]
Спасибо, а что значат x,y,z  в указателях ??? Например http://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga

**Comment by tananaev** [comment]
Координаты тайлов и зум. Ссылки нужно конфигурировать без каких-либо модификаций или подстановок.

**Comment by StormFront33** [comment]
Круто, я разобрался, спасибо. На сайте, только карты спутник, и растровая, если ли возможность добавить гугл - гибрит карту?

**Comment by tananaev** [comment]
Думаю что пока что нет. Гибрид состоит из двух слоев на сколько я знаю. На данный момент только один слой поддерживается.

**Comment by StormFront33** [comment]
Печаль для меня лично. Но всё равно спасибо, это лучше чем нечего.

**Comment by tananaev** [comment]
Вы можете код подправить если очень нужно.

**Comment by StormFront33** [comment]
Я не могу, к сожалению я больше продвинутый пользователь, а не программист. А так бы добавил карты гугл с ссылкой на соглашение(https://www.google.com/intl/ru-RU_US/help/terms_maps.html). Далее чтобы не плодить темы, подскажите с теркерами на двух симкартах, будет ли работать сервер? Например вот с таким как TK103A +, TK103A, TK103-2, GPS105A, TK103B?

Ссылка на китайский магазин: http://ru.aliexpress.com/af/gps-%25D1%2582%25D1%2580%25D0%25B5%25D0%25BA%25D0%25B5%25D1%2580-dual-sim.html?ltype=wholesale&spm=2114.031020208.8.4.enzcVP&SearchText=gps+трекер+dual+sim&d=y&origin=n&productId=518313550&initiative_id=QRW_20151127033516&isViewCP=y

Подскажите какой взять?

**Comment by tananaev** [comment]
К слову о соглашении, Google не разрешает использовать бесплатные карты для GPS трекинга. Нужно платить за лицензию (примерно $10000 в год).

Что касается устройств, похоже что по ссылке это в основном одни и теже модели. Скорее всего они все поддерживаются в Traccar.
