### ISSUE TITLE
[Help wanted] Definition of valid position

### ISSUE THREAD

**Issue by gsiotas** [tananaev/traccar#1551]
Hi guys!
Does anyone know how a valid position is being defined as valid? What are the requirements that traccar categorized a position as invalid? 

Thank you in advance for your answer.

**Comment by tananaev** [comment]
Validity flag is set by GPS module in the device. Usually "invalid" data means either old coordinates (because GPS signal is lost), or the location is inaccurate because of number of satellites in the fix or poor signal.

**Comment by gsiotas** [comment]
Ok thank you for your prompt answer.
