### ISSUE TITLE
Unknown message format tk103

### ISSUE THREAD

**Issue by vladamirk** [tananaev/traccar#1569]
Hello, I tried to connect another type of tracer tk-103b with t-mobile carrier, data only package. When I set up my tracker for the server it sends me some invalid messages on all ports 5001,5006...

Hex decoder give this results:

@Åî
: xx !Ì·Ï
ÓB[<y6¡aY: xx !&ÌªÄ
ˆf<b6¡aYFm
?
 xx "Ê¥W
&Ð[<s6¡adpå

![img_04122015_092157](https://cloud.githubusercontent.com/assets/8604419/11584489/2ca3f964-9a19-11e5-8487-a02a38af4b1f.png)

**Comment by tananaev** [comment]
Correct port for your device is 5023.

**Comment by vladamirk** [comment]
Also there is query not provided error, that appear to be there after last update.

**Comment by vladamirk** [comment]
It helped, port 5023 work, it`s just still comes in some unreadable format in logs, in traccar everything great, thank you

**Comment by tananaev** [comment]
As for query, you must be missing something in the config file.

**Comment by vladamirk** [comment]
it`s there https://github.com/tananaev/traccar/search?utf8=%E2%9C%93&q=database.updateDeviceStatus
but not in your config, same in mine

**Comment by tananaev** [comment]
It is in my config:

https://github.com/tananaev/traccar/blob/master/debug.xml#L218

Note that config files in `setup` directory are updated only during official release.
