### ISSUE TITLE
Device Parameters / Properties

### ISSUE THREAD

**Issue by ivanfmartinez** [tananaev/traccar#1591]
Hi Anton,

I have been looking at traccar code, and implementing some tests.
Now I have a need that I found should be used at other places too.

I have to get some properties for each device .
ex. email where alarm messages should be sent 
mqtt topic also to publish messages for device.

Also looking at the LBS service I have found that in my case I'm testing two devices with different operators, and the MNC should be different for each device, but the device does not send this field. In this case the global parameter location.mnc cannot be used.

Do you have in your plans any idea of the best way to implement this kind of device parameters ?

Thanks

**Comment by tananaev** [comment]
I've been thinking about it, but don't have any plans for it at the moment. It definitely makes sense to have some device-specific properties.

**Comment by Abyss777** [comment]
Looks like device attributes connected with this issue.

**Comment by tananaev** [comment]
Yes, attributes are available for devices now. Closing.
