### ISSUE TITLE
SMS command (SOS): automatic tracking

### ISSUE THREAD

**Issue by rhani00** [tananaev/traccar#1594]
Hi everybody
I just bought a tracker (IEMI: 355488 xxxxxx / it seems GPS103B)  and i want to activate the automatic tracking option to add my GPS to a "Traccar" server. 

All famous FIX tracking commands fails : "fix060s***n123456", "t060s***n123456".
Finally, my tracker accepted the command : "fix123456 060 **n" (return FIX,CONFIG OK)
The tracking command indicated by the poor user guide is "ITV 030 500" (030: period in static state / 500: period in motion state). The tracker return "ITV, CONFIG OK". 

Unfortunately, all these commands were no effect on my traccar in both mode (SMS & GPRS).
Only one tracking message can be successfully configured by "smslink123456" command or a simple call to tracker.

Could you help me please.
Best regards

**Comment by tananaev** [comment]
Have you tried to contact seller or manufacturer?

**Comment by rhani00** [comment]
Unfortunately i didn't receive any answer from manufacter (they looks only
for big orders) and seller has only basic notions regarding the
configuration of tracker.
I look for someone that have the same issue using this tracker (IMEI:
35548xx)

**Comment by rhani00** [comment]
Hi
Finally, tracking problem is resolved.
After connecting ACC wire, "ITV 030 500" command activate successfully auto tracking in GPRS mode.
I share with users of similar tracker the protocol "h02" and traccar port "5013".

**Comment by Tractms** [comment]
HI rhani00. I have same GPS with IEMI. 355488020xxx
I note the GPS is going into sleep mode.
Did you find out how to turn this off ?
+
ITV 030 500" command responds with a CONFIG OK message
fix123456 060***n"  command responds with a CONFIG OK message   AND
fix123456 060s***n"  command responds with a CONFIG OK message
Stranged how both commands work.

Did you find out how to turn the sleep mode off ?
This appears to be the cause of the tracker going off line.

**Comment by Fleetracking** [comment]
Hi
Follow steps below to configure your tracker:

begin123456 (default factory parameters)
password123456 xxxxx (to change password)
admin123456 0666xxxx (to setup admin phone number)
centernum123456 0666xxxx
timezone123456 0 (TZ = GMT+0)
ITV123456 60 300 ( freq = 5min in motion state / freq = 1min else)
APN123456  www.iamgprs1.ma (morrocan ISP APN)
adminip123456 52.X.X.X 5013 (@IP of server / 5013: appropriate port)
GPRS123456 1 (activate GPRS mode)

BR
