### ISSUE TITLE
CastelProtocolDecoder

### ISSUE THREAD

**Issue by dettrick** [tananaev/traccar#1599]
Hi,

I noticed in the latest version of Traccar that my Castel device no longer communicates with the server. After inspecting the log file i found that the GPS tracker sends the initial login message and the server then sends a response but after the server sends the response the communication stops.

Looking through the code I found that it is likely caused by the server sending a inccorect login response message. When you streamlined the CastelProtocolDecoder.java with a generic response method call, you forgot to write the "content" to the response channel buffer object. This should occur after line 101 but it's missing. 

As a result the GPS tracking receives an incorrect response and stops communicating with the server until the unit is externally reset. The tracker wont establish permanent communication until the server side is fixed.

I will try and update the code and rebuild. Will let you know what the result is. I have attached the log file for your reference.
[tracker-server.txt](https://github.com/tananaev/traccar/files/64043/tracker-server.txt)

**Comment by tananaev** [comment]
Fixed the problem. It was a silly mistake when I changed the decoder.
