### ISSUE TITLE
On the problem of Huabao protocol?

### ISSUE THREAD

**Issue by gpsim** [tananaev/traccar#1610]
hi tananaev!
When I use the Huabao protocol, the log is always prompt the unknown equipment and equipment, is actually a garbled form, please help look. Thank you~

<pre>2015-12-21 16:11:41 DEBUG: [47E8ADAC: 5015 < 117.136.20.88] HEX: 7e0100002d0141305678720024002c012f373031313142534a2d41362d424400000000000000000000003035363738373201d4c14238383838386d7e
2015-12-21 16:11:41  WARN: Unknown device - A0Vxr (117.136.20.88)</pre>

**Comment by tananaev** [comment]
Fixed the problem with identifier.

**Comment by addonravi** [comment]
Hi Sir,

I got this below type of data in log,  i  seen huabao protocol but decoding is not there , i think blind data report 

7e
0704
012f
014530480708
00d2
0005
01
003a0000000000000003015f750c045270b0000000000119170803210509010400000f2ceb16000c00b28991241909150101172400060089ffffffff
003a0000000000000003015f750c045270b0000000000119170803210514010400000f2ceb16000c00b28991241909150101172400060089ffffffff
003a0000000000000003015f750c045270b0000000000119170803210519010400000f2ceb16000c00b28991241909150101172400060089ffffffff
003a0000000000000003015f750c045270b0000000000119170803210524010400000f2ceb16000c00b28991241909150101172400060089ffffffff
003a0000000000000003015f750c045270b0000000000119170803210529010400000f2ceb16000c00b28991241909150101172400060089ffffffff
897e

**Comment by tananaev** [comment]
Please don't comment on old closed threads. As for your message, I need to see original message from Traccar logs.
