### ISSUE TITLE
Oko navi protocol needed

### ISSUE THREAD

**Issue by tomastovt** [tananaev/traccar#1612]
We have several trackers Ukrainian production - "OKO Navi". Interested in whether there is a possibility to add a protocol to your Traccar?.

**Comment by tananaev** [comment]
Do you have protocol documentation? You can send it by email (address is in profile) if you don't want to publish it here.

**Comment by tomastovt** [comment]
Here massages from it

**Comment by tomastovt** [comment]
After establishing the device TCP-server connection to the specified address and port of the first premise is first transmitted to the IMEI of the device, the GPS-receiver data and additional information from the device. The package begins with "{" and ends with "}" field separator "," (comma), for example:
{123456789098765,132810.000, A, 4926.424, N, 03203.683, E, 8.4,83.5,131010,07,7.85, F7,14.2,1,82,3N5}
Description fields:
123456789098765 - IMEI device (GSM-module)
132810.000 - Greenwich Mean Time (13 hours, 28 minutes, 10 seconds)
And - a sign of the reliability of the coordinates (V - coordinates are not reliable)
4926.4243, N - latitude (49 degrees 26.4243 minutes N - north latitude, S - south)
03203.6831, E - longitude (32 degrees 03.6831 minutes E - east, W - west)
8.4 - speed in knots / hr
83.5 - azimuth movement,
131011 - Date GMT (October 13, 2011)
07 - the number of the received GPS-receiver satellites to calculate the coordinates in decimal format,
7.85 - voltage on the analog input (white wire) device 7.85V in decimal format, for example, the voltage of the analog fuel level sensor in the tank. The range of values ​​from 0.00 to 9.99, step 0.01V.
F7 - message code from the device in hexadecimal. This event code in the device, due to which he gave the data to the server. The range of values ​​from 00 to FF.
00 - periodic data when the vehicle is moving,
01 - violation of input,
02 - off "ignition"
05 - restoration of input,
06 - inclusion of "ignition"
EF - GPG-module restart with no coordinates in 10 minutes,
F0 - off GSM / GPS-module with the "loss" of the external power supply,
F3 - registration in the GSM network after the loss
F7 - change of the azimuth of the vehicle,
F8 - stop the car,
F9 - periodic data when the vehicle is stationary,
FC - the server was unavailable for 1 hour,
FE - data transmission request,
FD - transition to the "invisible"
FF - inclusion (or restart) device.
14.2 - 14.2V voltage device in decimal format, step 0.1V.
1 - a sign of efficiency of internal memory (0 - faulty memory, 2 - in the internal memory has no data sent to the server)
82 - the current state of the I / O device, gradation level GSM-signal in hexadecimal format. Description of the assignment of bits in the binary representation of the field (in this example, 10000010): the least significant bit (extreme right) - a state of input 1 "white lead" (1 - high level, 0 - low), the next bit - state vhoda- 2 "green wire" (1 - high level, 0 - low), the next bit - output state 1 "white wire - lock relay" (1 on, 0 - off), 7 and 6 bits indicate the level of GSM-signal: 11 - high, 10 - average (as in the example), 01 - low, 00 - no registration
3N5 - version of the device
ATTENTION!!! If the device is set to the port 31200 server receiving data, the format of the next packet previously established connection is similar to how and when the first parcel at establishing a new connection (see. Above). If the reception port of the server is not equal to 31200, the following previously established connection only contain information GPS-receiver and the state of the device (without field IMEI), such as:
{132810.000, A, 4926.4243, N, 03203.6831, E, 25.0,183,131011,07,5.69,05,14.1,1,82,3N5}

**Comment by tomastovt** [comment]
And Here some live data:

7b3836313030313030313031363431352c3131353033312e3030302c412c343830342e3130313138302c4e2c30323235352e3232373030322c452c342e3132312c3131312e302c3231313231352c362c302e30302c46372c31332e362c312c30307d
{861001001016415,115031.000,A,4804.101180,N,02255.227002,E,4.121,111.0,211215,6,0.00,F7,13.6,1,00}

7b3131353033342e3030302c412c343830342e3039383934342c4e2c30323235352e3233333433362c452c372e3835382c3132302e392c3231313231352c372c302e30302c46372c31332e372c312c30307d
{115034.000,A,4804.098944,N,02255.233436,E,7.858,120.9,211215,7,0.00,F7,13.7,1,00}

7b3131353033382e3030302c412c343830342e3039313232372c4e2c30323235352e3235303231332c452c31372e3632312c3132382e312c3231313231352c382c302e30302c30302c31332e372c322c30307d
{115038.000,A,4804.091227,N,02255.250213,E,17.621,128.1,211215,8,0.00,00,13.7,2,00}

**Comment by tananaev** [comment]
I have added this protocol to my backlog of new protocols.

**Comment by tomastovt** [comment]
great thanks, when we can use it?

**Comment by tananaev** [comment]
I have more than 40 other protocols in the backlog, so it will take a while. If you need it urgently, please send me an email and we can discuss options.

**Comment by vinwareznic** [comment]
Hi and when we can use the protocol for GPS OKO-NAVI?
Thank you.

**Comment by tananaev** [comment]
@vinwareznic, if you need it urgently, please send me an email. Address is in profile.

**Comment by tsmgeek** [comment]
@vinwareznic 

Your live data samples above do not have device version number, is this a mistake or within spec or optional?

Does your version number indicate a protocol version or need any specific decoding?
>3N5

Does this need to be logged?
>1 - a sign of efficiency of internal memory (0 - faulty memory, 2 - in the internal memory has no data sent to the server)

GPIO, you example has 82 as 10000010 but it should be 01010010, are you starting with LSB or MSB as bit 0?
>bit 0 - input 1 "white lead" (1 - high, 0 - low)
bit 1 - input 2 "green wire" (1 - high, 0 - low), 
bit 3 - output 1 "white wire - lock relay" (1 on, 0 off), 
bit 4 - NA
bit 5 - NA
bit 7,6 - GSM-signal: 11 - high, 10 - average , 01 - low, 00 - no registration

**Comment by tananaev** [comment]
Protocol is implemented.
