### ISSUE TITLE
v 3.3 address is null

### ISSUE THREAD

**Issue by xizoaziz** [tananaev/traccar#1625]
why address is null in v 3.3 . but when try old version 3.2 it working .?

**Comment by tananaev** [comment]
What reverse geocoder provider are you using?

**Comment by xizoaziz** [comment]
the default  one i didn't change any thing 

  <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>

**Comment by tananaev** [comment]
There is a limit on free Google geocoding API. Are you sure you haven't reached it?

**Comment by xizoaziz** [comment]
yes i m sure . and why it is working when move to old one ?

**Comment by tananaev** [comment]
Try to set `geocode.processInvalidPositions` to `true` in the config file.

**Comment by xizoaziz** [comment]
working fine now . thanks for your help quick  replay.

**Comment by superservidor** [comment]
Hi Antov,

I am sending GPS updates from the Traccar Client for Android, and now I am getting a null address after upgrade to v3.3 from v3.2.

Below is my geocoder config at /opt/traccar/conf/traccar.xml :

    

    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>
    <entry key='geocoder.processInvalidPositions'>true</entry>
    <entry key='geocode.processInvalidPositions'>true</entry>
    
    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

What is wrong? Could you help me?

Thanks

**Comment by tananaev** [comment]
You can try this build which includes the fix:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0
