### ISSUE TITLE
Netbeans Configuration for working on the Javascript in traccar/web

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#1628]
How does one work on the Javascript for the web interface in NetBeans?

Currently, the Maven project only "exposes" the traccar server files which are all Java.  When the web interface was in a separate repository, this was easy to setup as a separate project.  Is there a different type of project that I should use now that the server and web interface are in the same repository?

**Comment by tananaev** [comment]
There is no project for JavaScript. I use IntelliJ and it shows all the files including Java and JavaScript. Not sure about NetBeans.
