### ISSUE TITLE
On startup, column "positionid" does not exit

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#1630]
I built traccar v3.3 and used the JAR with dependencies.  I am using PostgreSQL and I am not using the web client.  I created an empty database (traccar_db) and ran traccar.jar which created the schema using LiquidBase.  Subsequent starts of the server give me the same warning/error message:

> 2015-12-30 04:25:54  INFO: Operating system name: Linux version: 3.13.0-74-generic architecture: amd64
> 2015-12-30 04:25:54  INFO: Java runtime name: Java HotSpot(TM) 64-Bit Server VM vendor: Oracle Corporation version: 25.66-b17
> 2015-12-30 04:25:54  INFO: Memory limit heap: 241mb non-heap: 0mb
> 2015-12-30 04:25:54  INFO: Character encoding: UTF-8 charset: UTF-8
> 2015-12-30 04:25:54  INFO: Version: null
> 2015-12-30 04:25:58  WARN: ERROR: column "positionid" does not exist
>   Position: 45 - PSQLException (... < QueryBuilder:376 < DataManager:324 < ConnectionManager:55 < ...)
> 2015-12-30 04:25:58  INFO: Starting server...

Is there an error in the **database/*.xml** files?

Off-topic question: I noticed that there was not an entry for **database.createSchema** in **traccar.xml**.  Is this entry no longer necessary with LiquidBase?

- jss

**Comment by tananaev** [comment]
Correct, `database.createSchema` is no longer required because Liquibase handles database creation.

As for the problem, it looks like it fails on `database.selectServers` query. What config file are you using?

**Comment by jon-stumpf** [comment]
I am using the *vanilla* **traccar/unix/setup/traccar.xml** with lines 22-25 changed to point to my PostgreSQL server.  Nothing else was changed.

Potentially related, I have configured my phone, using the Android Traccar Client, to point to my traccar v3.3 server.  I am attempting to insert my phone into the devices table.  I get the following error:

> traccar_db=> insert into devices (name, uniqueId) values ('jss-s6', '375199');
> ERROR:  column "uniqueid" of relation "devices" does not exist
> LINE 1: insert into devices (name, uniqueId) values ('jss-s6', '3751...

Yet, displaying the columns of the table gives me the expected output.

> traccar_db=> \dS devices
>                                      Table "public.devices"

Column  | Type             |                      Modifiers                      
----------- | ---------------------------- | ----------------------------------------------------
id         | integer                     | not null default nextval('device_id_seq'::regclass)
name       | character varying(128)      | not null
uniqueId   | character varying(128)      | not null
status     | character varying(128)      | 
lastUpdate | timestamp without time zone | 
positionId | integer                     | 

> Indexes:
>     "pk_device" PRIMARY KEY, btree (id)
>     "device_uniqueId_key" UNIQUE CONSTRAINT, btree ("uniqueId")
> Referenced by:
>     TABLE "positions" CONSTRAINT "fk_position_deviceId" FOREIGN KEY ("deviceId") REFERENCES devices(id) ON DELETE CASCADE
>     TABLE "user_device" CONSTRAINT "fk_user_device_deviceId" FOREIGN KEY ("deviceId") REFERENCES devices(id) ON DELETE CASCADE

Further checking, I see that I cannot reference any column with a capital letter in it.

> traccar_db=> select uniqueId from devices;
> ERROR:  column "uniqueid" does not exist
> LINE 1: select uniqueId from devices;
>  -------------------^
> traccar_db=> select lastUpdate from devices;
> ERROR:  column "lastupdate" does not exist
> LINE 1: select lastUpdate from devices;
>  -------------------^
> traccar_db=> select positionId from devices;
> ERROR:  column "positionid" does not exist
> LINE 1: select positionId from devices;
> -------------------^
> traccar_db=> select id, name, status from devices;

id | name | status 
---- | ------ | --------
 | |

> (0 rows)

I am perplexed.

**Comment by jon-stumpf** [comment]
Further investigating using pgadmin, I see that I must double-quote these fields, using the letters capitalized as described in the table definition, in order to use them.

**Comment by jon-stumpf** [comment]
In the *vanilla* **traccar/setup/unix/traccar.xml**, I double-quoted all references to column names that contained capital letters - for example:

>     <entry key='database.insertPosition'>
>         INSERT INTO positions ("deviceId", protocol, "serverTime", "deviceTime", "fixTime", valid, latitude, longitude, altitude, speed, course, address, attributes)
>         VALUES (:deviceId, :protocol, :now, :time, :time, :valid, :latitude, :longitude, :altitude, :speed, > :course, :address, :attributes);
>     </entry>

This addressed the original error I reported and also subsequent errors (e.g., inserting positions).

Thank you for your prompt response.

**Comment by tananaev** [comment]
Maybe there is some option to ignore letter case for column names. Most databases ignore it by default.

**Comment by jannier** [comment]
Any solution?

**Comment by jannier** [comment]
sorry! what solution?

**Comment by jannier** [comment]
I found excuses
