### ISSUE TITLE
Remove DEBUG info from logs?

### ISSUE THREAD

**Issue by Hoekynl** [tananaev/traccar#1637]
Hello,

I have searched the forum and this issues on github for this but I can not find an answer to my question.

I want to remove the DEBUG info from my logs. I can edit "logger.level" in the config, but I do not know the good value for it.
There are no values given at the documentation. https://www.traccar.org/configuration-file/
Can you please give me the correct value to remove DEBUG info, but keep the device info?

Thanks!

**Comment by tananaev** [comment]
You can find available options here:

http://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/Level.html

Try `info` or `warn`.

**Comment by Hoekynl** [comment]
info was the correct value :) Thanks!
:+1:
