### ISSUE TITLE
Username and password are sent in clear

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#1648]
Hello,

I was checking my reverse proxy logs, and I saw that all usernames and passwords were logged in cleartext. It seems the client sends the password in a completely clear way though a GET request.
```
91.183.56.64 - - [08/Jan/2016:08:23:46 +0100] "GET /blank.html?language=English&email=renaud%40allard.it&password=mypassword HTTP/1.1" 200 0
```

**Comment by tananaev** [comment]
Good finding. I definitely need to fix it.
