### ISSUE TITLE
Watch Protocol

### ISSUE THREAD

**Issue by PTDreamer** [tananaev/traccar#1654]
Bought a W5 Q50 kids watch for one of my kids. None of the online servers worked so I had to get my hands dirty.
Current traccar code was not parsing the data properly. Opening this since don't know if it is just this device or a general issue.
The data looks like:
```
[3G*2256002206*0079*UD2,100116,153723,A,38.000000,N,-9.000000,W,0.44,299.3,0.0,7,100,86,0,0,00000008,2,0,268,3,3010,51042,146,3010,51043,132]
```
The parsing fails on the longitude because of the "-". After fixing the parsing one additional fix had to be done because the signal was getting inverted due to the "W".
The question is, should I create a PR? If yes changing the current protocol implementation or creating a new one?
Also does anyone have any more info regarding this protocol, especially the server -> watch bit?

**Comment by tananaev** [comment]
I have fixed the problem. Funny thing is that protocol includes both hemisphere data and coordinate sign which seems redundant and just silly.

**Comment by albertusgeyser** [comment]
What port should I use?

**Comment by tananaev** [comment]
You can check port number in the default configuration file.
