### ISSUE TITLE
Traccar 3.3 (fresh install)  reverse geocode

### ISSUE THREAD

**Issue by vzoltan** [tananaev/traccar#1660]
Hi, i decided to install a fresh install of traccar 3.3, till now i was using 2.2 and nominatim was just fine for me, but now with 3.3 i get NULL in address field.

traccar.xml ::

...
    <   !--entry key='geocoder.enable'   >true<   /entry   >
    <   entry key='geocoder.type'   >google<   /entry--   >

   <    entry key='logger.enable'    >true<    /entry    >
    <    entry key='logger.level'    >all<    /entry    >
    <    entry key='logger.file'    >/opt/traccar/logs/tracker-server.log<    /entry    >

 <    entry key='geocoder.enable'    >true<    /entry    >
    <    entry key='geocoder.type'    >nominatim<    /entry    >
    <    entry key='geocoder.url'    >http://nominatim.openstreetmap.org/reverse<    /entry    > 

i did try with default GOOGLE but same result, "NULL"

please give me an advice what to change, tweak.

thank you

**Comment by tananaev** [comment]
Please try this build:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

**Comment by vzoltan** [comment]
well, now it works, but there is something wrong.
i did try it now with iphone app, and after 1 location update, the status list just stopped updating,sending data.

**Comment by tananaev** [comment]
The address field format is now configurable using `geocoder.format` configuration parameter.

You can find more info about format here:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/geocode/AddressFormat.java

I think it includes house number by default, so maybe Nominatim just didn't return it.

**Comment by vzoltan** [comment]
Ok thanks for the cinfig info

But with ver 2.x nominatim guves back numbers too .


Any idea about the nee issue with your new server jar?
Iphone app stops semding data

**Comment by tananaev** [comment]
Traccar Client issue has nothing to do with server. There must be some problem on the phone side.

As for house numbers, I need logs to investigate the issue.

**Comment by vzoltan** [comment]
Just before the new jar
Ios app was working fine.

I will try it later and send you logs

Thank you!

**Comment by vzoltan** [comment]
@tananaev thanks, after testing it in the morning, it is ok now.
thank you.
