### ISSUE TITLE
Error connecting to MySQL

### ISSUE THREAD

**Issue by webmst** [tananaev/traccar#1663]
Hi Anton,
I've just spotted a runtime error, probably due to the MySQL database connection, after having tried an upgrade from 3.1 to 3.3 (so my setup was surely working before), that I'm unable to eliminate even if now I'm installing traccar from scratch with a new database.

I think that the issue is MySQL-related because - performing some step-by-step attempts - it shows up as soon as I modify the traccar.xml file in order to set traccar to use MySQL instead of the default H2 database.

Here are my lines in traccar.xml:

```
...

   <!-- DATABASE CONFIG -->
   
<entry key='database.driver'>com.mysql.jdbc.Driver</entry>
<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccarallowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>

<entry key='database.user'>traccar</entry>
<entry key='database.password'>traccar</entry>

<entry key='database.changelog'>/usr/local/traccar/data/db.changelog-master.xml</entry>

...

```

Please note that I set the 'database.changelog' value to 'db.changelog-master.xml', having found no official documentation about this new feature on your website (please confirm this is correct).

This is the runtime error:
<pre>
root@freenas:/usr/local/traccar # java -jar tracker-server.jar conf/traccar.xml
Exception in thread "main" java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 81; The reference to entity "a" must end with the ';' delimiter.
        at java.util.XMLUtils.load(XMLUtils.java:76)
        at java.util.Properties.loadFromXML(Properties.java:868)
        at org.traccar.Config.load(Config.java:29)
        at org.traccar.Context.init(Context.java:112)
        at org.traccar.Main.main(Main.java:29)
...
</pre>
Could you please point me to the right direction?

Best regards,
Alberto

**Comment by tananaev** [comment]
Error indicates that there is some problem with XML format in the config file.

**Comment by webmst** [comment]
Thanks Anton, I solved the issue modifying the traccar.xml file manually.

The problem had been created by a truncated copy/paste from notepad to the 'vi' editor; the 'database.url' entry was very long and had been split in several lines, even if I didn't seem.

Best regards,
Alberto
