### ISSUE TITLE
GPS giving wrong longitude

### ISSUE THREAD

**Issue by netomx** [tananaev/traccar#1669]
Hi, I received some faulty GPS modules giving positive longitude, but I'm on America and I need it negative. On an old version of traccar, modifing traccar.conf: 

<entry key='database.insertPosition'>

with 

ABS(:longitude)*(-1)

Worked, but now it is not. Only the first one is modified, and the rest are positive. Any help? Thanks

**Comment by tananaev** [comment]
It should be possible to do the same thing with the new version. Can I see your query?

**Comment by netomx** [comment]
Yes:

[CODE]
<entry key='database.insertPosition'>
        INSERT INTO positions (deviceId, protocol, serverTime, deviceTime, fixTime, valid, latitude, longitude, altitude, speed, course, address, attributes)
        VALUES (:deviceId, :protocol, :now, :time, :time, :valid, :latitude, ABS(:longitude)*(-1), :altitude, :speed, :course, :address, :attributes);
    </entry>
[/CODE]

**Comment by tananaev** [comment]
Looks fine to me. I don't see any reason why it would write positive values.

**Comment by netomx** [comment]
I'll make another test and tell you if got a problem.

That query works for every position insert? or is it another?

**Comment by tananaev** [comment]
For every position. There are no other queries for writing data into this table.

Note that if you are using default web interface or Traccar API, you will still get positive values because data is served directly from memory without going through database.

**Comment by netomx** [comment]
default web interface

Damn. How do I force it to read from database? Or how does it get its from memory? From the variable? I don't know Java, but can I modify the variable from the traccar.xml ?

Thanks

**Comment by tananaev** [comment]
I have added new config options to force hemisphere. Here is a new build:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

Use following line in the config:
```
<entry key='location.longitudeHemisphere'>W</entry>
```

**Comment by netomx** [comment]
At a first glance, appears it is fixed. Thank pal :)

Btw, this GPS uses the gt06 protocol, I don't think there's a poblem with the parsing, right? Or it can be?

**Comment by tananaev** [comment]
There was a problem at some point, but it should be fixed by now.

**Comment by netomx** [comment]
I remember now, from 5 GPS, just 1 sent the correct one, so I don't think it is the parser.

Thanks!
