### ISSUE TITLE
Cant see device latitude ,longitude, valid, time, altitude , speed and address 

### ISSUE THREAD

**Issue by varunsingh2324** [tananaev/traccar#1677]
Hi Tananaev,

Greetings, I have just installed the server and client of Traccar. I am using demo.traccar.org. but facing alot of problems related to following:
1) i am unable to find the 12 digit IMEI number
2) In the client my Device identifier for Samsung GT-S7562 is 5004 
3) Server port for client is 5055
4) In demo.traccar.org periodic reporting , stop reporting , engine stop and engine resume when clicked is showing -> NullPointer Exception: Command Resource37> " Could not understand this"
5) User tracking is disabled

please , initiate a solution to these problems also, attaching the screen
![image](https://cloud.githubusercontent.com/assets/16815946/12480419/32d0f48e-c068-11e5-8fb2-d5cc974fa5fe.png)

Regards,

**Comment by tananaev** [comment]
IMEI number is always 15 digits.

Are you trying to send commands to Traccar Client? That's not supported.

What do you see on the status screen in the app?

**Comment by varunsingh2324** [comment]
Hi tananaev,

When i press show tab in the bottom to find the track i see nothing..After reading your documentation i filled the identifier as " 123456789012345" for my device GT-S7562
By now my configuration for Traccar client is:
Server port :5055
 i could not track 
 what can be the issue ?

**Comment by varunsingh2324** [comment]
Also my device is GT-S7562 port is not available in your document

**Comment by tananaev** [comment]
If you are using Traccar Client, the port is always 5055. Does your identifier have a space in it?

**Comment by varunsingh2324** [comment]
Thanks for the reply. 
No my identifier is not having space.

**Comment by varunsingh2324** [comment]
Should i use demo.traccar.org ?
as for now i was using my ip address

**Comment by varunsingh2324** [comment]
Ok Anton now currently i have redid everything...i am using demo.traccar.org and my identifier of the device is accepted. I can see the Last update as well but when i want to see the location update of my device it is not showing in the Show tab bottom. Server is up and running. Please guide.

**Comment by tananaev** [comment]
Your comment is confusing. Are you using your own server or demo server?

**Comment by varunsingh2324** [comment]
Sorry for that anton . I am using demo server. i will define everything about what i did so far. 
1. I opened demo.traccar.org.
2.On service in windows  i started the traccar server in backgorund.
3.I added the device and the unique identifier in my case : NAME : Varun 
                                                                                             IDENITIFIER:822356
4.I used the server address as demo.traccar.org
5.Started the client in android mobile
6. I see now in my computer browser my Name coming written with last update

this is it . only i cant see location update

**Comment by tananaev** [comment]
Wait. Why do you need Traccar server on Windows if you are using demo server?

**Comment by varunsingh2324** [comment]
sorry for this again anton. I am not clear about this .. what is traccar server...i am using demo.traccar.org so i believe i am using demo server

**Comment by tananaev** [comment]
You can either use your own server or you can use demo server. If you use demo server, you don't need to install Traccar on your own computer.

**Comment by tananaev** [comment]
As for the problem, what do you see on the status screen in the app?

**Comment by varunsingh2324** [comment]
Ok. I see service created and connectivity change messages popping. nothing else

**Comment by tananaev** [comment]
If you don't see "location update" there, it means app doesn't get the location. If you are using GPS, make sure you have a good signal. Note that GPS doesn't work indoors.

**Comment by varunsingh2324** [comment]
I have tried using personal wifi for GPS but the "location update" is not showing. Also, in your youtube video this->https://www.youtube.com/watch?v=B8rrqRfvOj4  " you also might be using your home wifi i preassumed.However, i followed your video correctly still no location update

**Comment by tananaev** [comment]
What location provider are you using?

**Comment by varunsingh2324** [comment]
my personal wifi

**Comment by tananaev** [comment]
There is "location provider" option in the app.

**Comment by varunsingh2324** [comment]
yes.GPS satellites . i am using wireless network to connect GPS

**Comment by tananaev** [comment]
Looks like your device doesn't have a GPS signal. Note that GPS doesn't work indoors.

**Comment by varunsingh2324** [comment]
Anton is Traccar client version 3.5 working perfectly...i have the old client for android

**Comment by tananaev** [comment]
Are you implying that there is a bug in the new version?

**Comment by varunsingh2324** [comment]
See , i am using Traccar client 3.5. In that there is a very long device identifier which is by default "123456701234 ". i tried using that for my device but the " local host:8082" did not accept
but as compare to your new version the device identifier number is easily accepted by "local host:8082" also , i wanted to know if i am using "demo.traccar.org" in server address will it be fine or i will to use my own ip address

**Comment by tananaev** [comment]
1. Why are you using old version of Traccar Client? New version always have some bug fixes. There is no point in using the old one.

2. What do you mean by device was not accepted by localhost? Did you get any errors?

3. Do you want to use your own server or free demo server?

**Comment by varunsingh2324** [comment]
I understand what you said, so now i have downloaded  Traccar client 3.8 in which device identifier for my Samsung GT-7562 is "350026". it is like now i am doing everything from the scratch. now
1.How to use free demo server ?
2.What will be the server address in the "Traccar client " ?
please guide, and thanks for reverting back instantly

**Comment by tananaev** [comment]
1. Traccar Client is configured by default to report location to the demo server. All you need to do is register account and add your device with unique id there. That's it.

2. If you want to use demo server, everything is already configured there. You don't need to change address or port. Just use default settings.

**Comment by varunsingh2324** [comment]
ok Anton. I will try what ever you have stated

**Comment by varunsingh2324** [comment]
accha what is the difference between " demo.traccar.org " and "local host:8082" they both open the same window ?
![image](https://cloud.githubusercontent.com/assets/16815946/13074812/eb80e070-d4cc-11e5-9751-34fec3b6719b.png)
![image](https://cloud.githubusercontent.com/assets/16815946/13074816/ef78a96a-d4cc-11e5-8792-4f8982105485.png)

**Comment by tananaev** [comment]
demo - is my server
localhost - is your local server

Of course they look the same because they run exactly the same software.

**Comment by varunsingh2324** [comment]
Hello Anton,
After following everything correctly, i have established two location updates in my traccar client . Now "demo.traccar.org" is showing my name of the device "trac" and "last update" respectively. The only issue is can not get "State" in which "Attribute" and "value" is not showing. Also, in the bottom screen, when i select "Device" i can't see "show" tab working in which longitude, latitude,speed and address is shown. Please, guide. i am sending a screen shot
![image](https://cloud.githubusercontent.com/assets/16815946/13106530/ba7710fe-d58e-11e5-8f98-ce0eae26296d.png)

**Comment by tananaev** [comment]
What do you see on the status screen in the app?

**Comment by varunsingh2324** [comment]
Status screen is working as desired. Everything is working fine.this is my screen
![image](https://cloud.githubusercontent.com/assets/16815946/13108151/6b331f8e-d597-11e5-9123-352bb9bde76b.png)

now anton, can you please tell me how will i know the path i travelled. There is " Follow" button . Does this "Follow" will show me the path i travelled ?

**Comment by tananaev** [comment]
In your report you have only 2 points which are basically in the same location. There is no "path" as far as I can see. Maybe you need to select longer time interval.

**Comment by varunsingh2324** [comment]
Hi Anton. You are rite, that is why i have travelled a bit of distance. Here is something i want to show you:

![image](https://cloud.githubusercontent.com/assets/16815946/13133917/6f80ff54-d626-11e5-8c99-9704d03a96bb.png)

**Comment by tananaev** [comment]
Is there anything wrong with this screenshot?

**Comment by varunsingh2324** [comment]
Anton there is nothing wrong. Now it is working fine. Thanks!

**Comment by varunsingh2324** [comment]
Hi Anton, There is new set of issues i am facing now while working on local server. 
1. I started the service" Traccar" from my windows
2. I made a new registration on the "Traccar server" with a unique device id
3. In the " Traccar client " inserted the "IP address"
4. My device was registered on PC
5. I started my "Traccar " client service and recieved a " Location update"
 The problem is when i want to track this Location update on my local server i dont see anything
this is the attached screen where i am unable to see any "Last Update" beside my "Name"
![traccar screenshot2](https://cloud.githubusercontent.com/assets/16815946/13254313/d5edfb9a-da66-11e5-9282-59e4d511db30.png)

**Comment by tananaev** [comment]
Check server logs (specifically `tracker-server.log`) to see if there are HEX messages from your device there.

**Comment by varunsingh2324** [comment]
I don't see HEX message of my device ?

**Comment by tananaev** [comment]
It means server doesn't receive any data from your device. Possibly device configuration issue or some network issue.

**Comment by ratanakpek** [comment]
Hi, @tananaev! I wonder why you need to store position object into sqlite db and then select it by compare like this:

 if (result.getDeviceId().equals(preferences.getString(MainActivity.KEY_DEVICE, null))) {
                     send(result);
   } else {
                     delete(result);
   }
 1. why need to store in sqlite?

**Comment by ratanakpek** [comment]
databaseHelper.selectPositionAsync(new DatabaseHelper.DatabaseHandler<Position>() {
            @Override
            public void onComplete(boolean success, Position result) {

}}

2. after the result parameter is null, it is not send send the latitude and longtiude? This is the reason I dont see it active in web

**Comment by tananaev** [comment]
@ratanakpek, why are you asking it here? Please create a new thread in the client repository.
