### ISSUE TITLE
Server v3.3 on Raspberry Pi -> Synology MySQL not working

### ISSUE THREAD

**Issue by stevebeer** [tananaev/traccar#1686]
Started with clean installation of Raspian on Raspberry Pi. 
Default H2 database is running nice and smooth but,

Trying to use External MySQL server on Synology DS214 NAS.
Database and user are created with all possible rights.
What is going wrong??

Traccar server version 3.3 on a Raspberry Pi.

Only database tables were created:
- DATABASECHANGELOG
- DATABASECHANGELOGLOCK

After starting server, it stops immediately.

Configuration parameters changed in XML-file according to https://www.traccar.org/mysql/
Also added the mentioned check.table option.

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
    <entry key='database.url'>jdbc:mysql://192.168.0.19:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
    <entry key='database.user'>traccar</entry> 
    <entry key='database.password'>***************</entry>
    <entry key='database.checkTable'>traccar</entry>

**Comment by stevebeer** [comment]
Server v3.2 works great with same configuration!

**Comment by tananaev** [comment]
You need to check `wrapper.log` file for error messages. There must be some problems with creating database schema.

**Comment by stevebeer** [comment]
Problem solved!
Changing 'utf-8' to 'latin1' in the .xml configuration file did the trick.

Issue can be closed.
My step-by-step guide is usefull for people who want to install Traccar on a Raspberry Pi.
All credits to Tananev offcourse ;-)
http://vdeweb.com/wiki/doku.php?id=linux:ubuntu:traccar_raspberry

**Comment by tananaev** [comment]
Thanks for sharing the information.
