### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#1688]
Hello Anton,

This is not really about an issue, but more of an enhancement and improvement in bug tracking. Would it be possible for you to issue snapshots of traccar every X days (or other schedule)? I know it's not extremely hard to compile, but that are quite some dependencies if you want to produce a full snapshot including the "compressed" web interface. Also, I am almost sure you have them already after each change anyway :). There is no need to have a zip for every architecture, just the traccar-server.jar, its libs and the web interface as this is not something every user should use anyway.

**Comment by tananaev** [comment]
The problem would be stability of those builds. I don't want to deal with all the issues raised against something that is not completely finished and tested. I am trying to make release cycles shorter. Ideally I want to release a new version every 1-2 months.

**Comment by renaudallard** [comment]
It is mainly meant for builds with fixes in them. Also, there shouldn't be an installer of any kind to avoid random people using those versions without knowing.

**Comment by tananaev** [comment]
Usually when I fix some issue I create a build of tracker-server.jar. You can always find latest here:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

For web interface I would recommend to just get files from GitHub and use "debug.html" version.

**Comment by renaudallard** [comment]
For the web interface, it's hard to ask for people to use debug.html. Or maybe there could be a switch in the config file to use debug.html by default.

**Comment by tananaev** [comment]
There is a switch:
```
    <entry key='web.debug'>true</entry>
```

**Comment by renaudallard** [comment]
ah, OK, that's an undocumented one :)
Thanks Anton, so in final, I see you are in fact already doing what I asked.

**Comment by tananaev** [comment]
I'm using this flag during development process because I don't want to minify web interface all the time.
