### ISSUE TITLE
:attribute

### ISSUE THREAD

**Issue by atiliocd** [tananaev/traccar#1693]
I use the Traccar Integrated with OpenGTS, is there Any Way to put the parameter ":attributes" in Table EventData of OpenGTS ?

Grateful!

**Comment by tananaev** [comment]
There is no point in putting attributes in original format into the OpenGTS table, but you can extract individual fields from attributes and store them in EventData.

**Comment by atiliocd** [comment]
Thanks!

**Comment by himsashu** [comment]
Hi Tananaev
Can you guide me how to extract individual value from attributes and store in EventData of OpenGTS?

**Comment by tananaev** [comment]
Please don't comment on closed thread. Create a new one.

**Comment by himsashu** [comment]
Sorry
