### ISSUE TITLE
Skypatrol mask

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#1694]
Hello there, I have a skypatrol TT8750+ GPS device and I really want to get this device in my platform but seems to be very very difficult. Can you please help me out on this? How can I configure this device? what mask uses skypatrol to be able to stay attached to traccar server? what mask supports the skypatrol protocol?
regards.

**Comment by tananaev** [comment]
You need to make sure that device sends mask itself to the server. Otherwise any mask with GPS information should work.

**Comment by hackerunet** [comment]
anton, can you tell me if the skypatrol protocol is UDP or TCP please?
thanks

**Comment by tananaev** [comment]
It's UDP.

**Comment by hackerunet** [comment]
I have tested so many differents masks on this protocol using a skypatrol TT8750+ device and no matter if I have the mask generator file and I enable mask bit it never ever gets connected to traccar server.
I have the bit "add position report mask" 4 bytes in binary format stablished in 1 which is enabled, also I have "add sequence number message" 2 bytes in binary format in 1 and everything is sent is binary format using udp protocol, the UDP port 5021 is opened and nothing works. I think this protocol needs a revision, I'll send the PDF documentation with the mask generator to see if is possible to get this up and running and normalized with the documentation.

**Comment by hackerunet** [comment]
I think the problem is beyond the mask, something is not quite well in this protocol but I really have no idea about what should be failing.
regards

**Comment by tananaev** [comment]
I guess I need protocol documentation and some of your message samples. SkyPatrol and Enfora have always been problematic.

**Comment by hackerunet** [comment]
I already sent to your email also a mask calculator so that way you can see exactly how it has to be done

**Comment by hackerunet** [comment]
Thank you anton this seems to be solved, if you think is already solved please close the case.
regards

**Comment by tananaev** [comment]
Closing the issue. Thanks for the documentation and message samples.

**Comment by guifer01** [comment]
Good Morning, I was testing this skypatrol TT8750+ GPS and i have the same problem, could you share how you solve the problem, thanks, 

I receave the same problem

2017-08-16 07:47:57 DEBUG: [2D6E54B0: 5021 < 190.113.210.54] HEX: 0005020000000000012020202020202020202020545438373530506c757320

thanks

**Comment by ardonjl** [comment]
Hello, sorry por answer so too late but your problems is the configuration TT8750+ GPS change "HEX" by "ASCII"
