### ISSUE TITLE
OsmAnd Protocol UTC-time

### ISSUE THREAD

**Issue by mluepkes** [tananaev/traccar#1700]
Would it be possible to add a UTC-enabled time field (e.g. 1994-11-05T13:15:30Z) to the OsmAnd Protocol? This would enable the use of other tracker Apps like [mendhak/gpslogger](https://github.com/mendhak/gpslogger/).

I have no clue about Java, so bear with me, but something along these lines should/could work:

```java
                case "timestampUTC":
                    try {
                        long timestamp = Long.parseLong(value);
                        if (timestamp < Integer.MAX_VALUE) {
                            timestamp *= 1000;
                        }
                        position.setTime(new Date(timestamp));
                    } catch (NumberFormatException error) {
                        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
                        position.setTime(dateFormat.parse(value));
                    }
                    break;
```

**Comment by tananaev** [comment]
You can use unix timestamp value in UTC. What formats does the other app support?

**Comment by mluepkes** [comment]
It is a UTC time string. The URL parsed from my log hex looks like this:

`/?id=[...]&lat=[...]&lon=[...]&timestamp=2016-01-27T18:55:47Z&hdop=30.0&altitude=0.0&speed=0.0`

Omissions [...] added by me. The transmitted URL results in the following error.

`error - Unparseable date: "2016-01-27T18:55:47Z" - ParseException (... < OsmAndProtocolDecoder:78 < ExtendedObjectDecoder:39 < ...)`

**Comment by tananaev** [comment]
I have added support for ISO-formatted time values.

**Comment by mluepkes** [comment]
Thanks alot!
