### ISSUE TITLE
How to send raw message

### ISSUE THREAD

**Issue by hanselsen** [tananaev/traccar#1703]
I have a minifinder device and I want to push a command to it (let's say LEDs ON)
The protocol documentation says it should be 123456LED1 where 123456 is your pin.
How would I send this message using the "write(Object message)" method in ActiveDevice?

 I created this method for testing 
```
public void sendCommand(Command command) {
        getChannel().write(command.getType(), remoteAddress);
        //protocol.sendCommand(this, command);
    }
```
And then used the API to push a command with this json: `{"deviceId": 1, "type": "W1,05S"}`

No results are visible, except that the device becomes "offline" and then reconnects after about 10s.

Somebody any insights?

**Comment by tananaev** [comment]
Do you see the message being sent in the log file (tracker-server.log)?

**Comment by hanselsen** [comment]
Ah, good point. I haven't watched that file yet.
I now see that it's giving me the following:
```
2016-02-07 09:06:18 DEBUG: [4F538F96: 5062 > 91.241.29.10]
2016-02-07 09:06:18  WARN: [4F538F96] error - unsupported message type: class java.lang.String - IllegalArgumentException (...)
2016-02-07 09:06:18  INFO: [4F538F96] disconnected
2016-02-07 09:06:46  INFO: [E05FBFFA] connected
```
What could I do to inject a string or hash?

**Comment by tananaev** [comment]
What protocol are you using?

**Comment by hanselsen** [comment]
Minifinder

**Comment by tananaev** [comment]
You need to add `StringEncoder` to the channel pipeline.

**Comment by hanselsen** [comment]
Ok great! No errors anymore thanks.
Maybe you want to help just a little bit more. I have send 'G' which should be a status request.
In the log is this: 
`2016-02-07 09:44:09 DEBUG: [3DA6C22E: 5062 > 91.241.29.10] HEX: 47`
So thats the correct hex value for 'G'. 
Any idea what communication I am missing for the device to respond?

**Comment by tananaev** [comment]
Are you sure you just need to send one letter without any delimiters?

**Comment by hanselsen** [comment]
[MiniFinder_Pico_Protocol.pdf](https://github.com/tananaev/traccar/files/120636/MiniFinder_Pico_Protocol.pdf)

Yes. I have PIN lock off, so I won't need to send the PIN as a prefix. (But let me try for sure)

**Comment by tananaev** [comment]
Try to add beginning (`!`) and delimiter (`;`) in various combinations.

**Comment by hanselsen** [comment]
Sadly. No response either. Good thinking though.

**Comment by tananaev** [comment]
I guess there is some problem on the device side then. Maybe there is something missing in the documentation.

**Comment by hanselsen** [comment]
Oh I see this issue is still open. I found the solution. For the minifinder, you need to add 123456 before every command... Weird, but true
