### ISSUE TITLE
Unstable connections in traccar version 3.3

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#1711]
Hi anton, I've been facing serious problems with traccar version 3.3, connections are not stable, devices are always disconnected and I was forced to migrate back to 2.12, any suggestions?
Now, that I have my server with old version I'm receiving this error:
2016-02-08 21:17:39  WARN: netty warning: Failed to accept a connection.

Is something very weird because I honnestly don't know why netty is not able to handle connections, the server where netty is giving us so many troubles is used by 1000 devices only.
Version 3.3 is not stable we are facing problems permanently because all devices are always disconnected, they start working for minutes and then everything starts operating abnormally.
regards

**Comment by hackerunet** [comment]
now, traccar 2.12 has serious issues, don't know why, everything is down and nothing works..
16-02-08 21:34:33 DEBUG: [B82F65D0: 5001 -> 186.167.244.220] - HEX: 4c4f4144
2016-02-08 21:34:33 DEBUG: [74DDCB01: 5001 <- 186.167.245.173] - HEX: 696d65693a3335333435313034383131393239392c747261636b65722c313630323038313733312c2c462c3231333130312e3030302c412c303933312e323238312c4e2c30363931332e393536382c572c302e30302c2c3b23232c696d65693a3335333435313034383131393239392c413b696d65693a3335333435313034383131393239392c747261636b65722c313630323038313733312c2c462c3231333130382e3030302c412c303933312e323238312c4e2c30363931332e393536382c572c302e30302c2c3b23232c696d65693a3335333435313034383131393239392c413b23232c696d65693a3335333435313034383131393239392c413b23232c696d65693a3335333435313034383131393239392c413b
2016-02-08 21:34:33  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:34  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:35  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:36  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:37  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:38  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:39  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:40  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:41  WARN: netty warning: Failed to accept a connection.
2016-02-08 21:34:42  WARN: netty warning: Failed to accept a connection.

**Comment by hackerunet** [comment]
More issues, downgraded java to 1.6, same issues, upgraded to 1.7 again and now:
2016-02-08 21:47:41 DEBUG: [F096B50A: 5001 <- 186.185.238.236] - HEX: 696d65693a3335393731303034373836323631312c747261636b65722c3136303230383137333131352c2c462c3231343631362e3030302c412c303933322e323235312c4e2c30363931332e383431322c572c342e31342c3232352e31383b696d65693a3335393731303034373836323631312c747261636b65722c3136303230383137333135302c2c462c3231343635312e3030302c412c303933322e313034332c4e2c30363931332e393634392c572c31302e36312c39382e35323b3335393731303034373836323631313b
2016-02-08 21:47:41  WARN: Broken pipe - java.io.IOException (FileDispatcherImpl.java:-2)
2016-02-08 21:47:41  INFO: Closing connection by exception
2016-02-08 21:47:41  INFO: Closing connection by disconnect
2016-02-08 21:47:41 DEBUG: [750E7CB1: 5001 -> 186.167.250.226] - HEX: 4c4f4144
2016-02-08 21:47:41  WARN: java.nio.channels.ClosedChannelException (AbstractNioWorker.java:433)
2016-02-08 21:47:41  INFO: Closing connection by exception
2016-02-08 21:47:41 DEBUG: [750E7CB1: 5001 -> 186.167.250.226] - HEX: 4c4f4144
2016-02-08 21:47:41  WARN: java.nio.channels.ClosedChannelException (AbstractNioWorker.java:433)
2016-02-08 21:47:41  INFO: Closing connection by exception
2016-02-08 21:47:41 DEBUG: [87E52701: 5001 <- 186.185.201.144] - HEX: 696d65693a3435393731303034303339353631392c747261636b65722c3136303230383137333131332c2c462c3231343631352e3030302c412c313030382e313933342c4e2c30363830302e303234322c572c322e38392c37342e31363b3435393731303034303339353631393b

**Comment by tananaev** [comment]
It has nothing to do with version of Traccar ot Java. There are limits on number of connections in the operating system. By default on Linux it's around 1000.

**Comment by hackerunet** [comment]
both servers limits are in unlimit

**Comment by hackerunet** [comment]
that exception is messing up the entire system, I keep receiving netty failed to accept a connection and very few devices are connected. what should I do now?

**Comment by tananaev** [comment]
Make sure the limits are increased for the correct user. There is nothing else you can do. I think that's the only reason it can be happening.

**Comment by hackerunet** [comment]
what user handle traccar connections? root?

**Comment by tananaev** [comment]
Yes, it should be `root` by default.

**Comment by hackerunet** [comment]
OK anton, yes, again file descriptors were the problem the thing is if I restart the service I loose the limits configuration so I had to set ulimit -Hn manually to 1000000 and i receive no errors but devices still not connected

**Comment by hackerunet** [comment]
Anton, it's very weird, seems to be opened when I restart the service but in few minutes everything get backs to closed sockets or connections.
very weird,  I cannot find the problem...

**Comment by tananaev** [comment]
It sounds like it still reaches some limit. Not sure why. If you find an explanation, please let me know.

**Comment by hackerunet** [comment]
limits are not reached, yesterday I restart the database and seems to be related to it, all devices start connecting again but after 5 hours everything starts failing once again:
2016-02-09 15:39:40 DEBUG: [CC5C604D: 5001 -> 186.167.251.248] - HEX: 4c4f4144
2016-02-09 15:39:40  WARN: java.nio.channels.ClosedChannelException (AbstractNioWorker.java:433)
2016-02-09 15:39:40  INFO: Closing connection by exception

**Comment by hackerunet** [comment]
Anton this is something I have always said to you, the linux kernel is not able to release file descriptors and the TCP stack get's soon without sockets resources, so, for small servers and few devices traccar is nice, but when you have 7000 vehicles issues begins to show up.
For example, why if I have 7000 vehicles but active vehicles are like 2000 why this is the output of netstat?
```
[root@host ec2-user]# netstat -ant | awk '{print $6}' | sort | uniq -c | sort -n
      1 established)
      1 FIN_WAIT1
      1 Foreign
     57 LISTEN
     62 SYN_RECV
    141 TIME_WAIT
    976 LAST_ACK
  10246 CLOSE_WAIT
  16425 ESTABLISHED
[root@host ec2-user]#
```

I see 16 425 connections stablished but when I list everything you will notice that real connections are not more than 1000, so the kernel let's opened lots of socket connections and resources are never released.

```
      1 66.249.88.200
      1 Address
      1 servers)
      2 186.14.5.241
      2 186.167.244.169
      2 186.167.245.214
      2 186.185.143.40
      2 186.185.199.130
      2 186.91.221.183
      2 186.93.202.121
      2 186.94.102.190
      2 190.153.56.62
      2 190.206.242.253
      2 190.79.74.16
      2 200.82.157.133
      2 200.84.172.113
      2 200.84.218.155
      2 37.210.249.70
      2 66.249.88.195
      3 190.199.195.1
      5 190.198.252.133
      5 200.109.191.227
      6 186.185.65.203
      7 186.185.222.139
     14 54.218.82.65
    177 172.31.30.15
  44977
[root@ip-172-31-31-220 ec2-user]#
```
You can also see 44977 opened connections without any ip addresses at all, which means file descriptors are still opened, java never release connections and now we are facing internal sockets phantom connections and a bottle neck of traffic inside the machine.. so, that's what I've found so far.

**Comment by hackerunet** [comment]
After less than an hour I get this:
```
[root@ip-172-31-31-220 ec2-user]# netstat -ant | awk '{print $6}' | sort | uniq -c | sort -n
      1 established)
      1 Foreign
      4 SYN_SENT
      5 FIN_WAIT1
     57 LISTEN
     65 SYN_RECV
    175 TIME_WAIT
   1012 LAST_ACK
  19478 ESTABLISHED
  21954 CLOSE_WAIT
```

**Comment by tananaev** [comment]
Do you have `resetDelay` set for the used protocols?

**Comment by hackerunet** [comment]
I have a global resetDelay, is it needed per protocol? I'm using 2.12 but, I'm thinking about getting 3.1 installed right away.

**Comment by tananaev** [comment]
What is global resetDelay? Is it your custom thing? As far as I remember in original Traccar there is no such thing.

**Comment by hackerunet** [comment]
holly crap... let me show you configuration file, maybe that was something let behind due to several changes.

```
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <!-- Global confiduration -->
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.dataSource'>com.mysql.jdbc.jdbc2.optional.MysqlDataSource</entry>
    <entry key="database.url">jdbc:mysql://axiomagps-mysql.chegeo77rzo5.us-west-2.rds.amazonaws.com:3306/axiomagps_db?allowMultiQueries=true&amp;allowReconnect=true</entry>
    <entry key="database.user">axiomaadmin</entry>
    <entry key="database.password">k4m1k4z32013</entry>

    <!-- Database refresh delay in seconds -->
    <entry key='database.refreshDelay'>300</entry>

    <!-->
        id - Long
        imei - String
    <-->
    <entry key='database.selectDevice'>
        SELECT imei as id,imei as imei
        FROM axioma_vehiculos;
    </entry>

    <!-->
        device_id - String
        time - Date
        valid - Boolean
        latitude - Double
        longitude - Double
        speed - Double
        course - Double
        power - Double (NULL for some protocols)
        extended_info - String (XML)
    <-->
<entry key='database.insertPosition'>
        START TRANSACTION;
        INSERT INTO `axiomagps_db`.`axioma_tracking`(`course`,`device_id`,`latitude`,`longitude`,`power`,`speed`,`time`,`valid`,`command`)
                VALUES (:course,:device_id,:latitude,:longitude,:power,:speed,:time,1,:extended_info);
        CALL insert_tracking(:device_id,:time,1,:latitude,:longitude,:speed,:course,:power,:extended_info);
        COMMIT;
    </entry>

    <!-- Web interface port -->
    <entry key='http.enable'>false</entry>
    <entry key='http.port'>8082</entry>
    <entry key='http.application'>/opt/traccar/traccar-web.war</entry>

    <!-- Logging options -->
    <entry key='logger.enable'>false</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    <!-- Gps103 server configuration -->
    <entry key="gps103.enable">true</entry>
    <entry key="gps103.port">5001</entry>

    <!-- EV603 server configuration -->
    <entry key="ev603.enable">true</entry>
    <entry key="ev603.port">5002</entry>

    <!-- PT502 server configuration -->
    <entry key="pt502.enable">true</entry>
    <entry key="pt502.port">5003</entry>

    <!-- Meiligao server configuration -->
    <entry key="meiligao.enable">true</entry>
    <entry key="meiligao.port">5004</entry>

     <!-- Android server configuration -->
    <entry key='t55.enable'>true</entry>
    <entry key='t55.port'>5005</entry>

    <!-- tk103 server configuration -->
    <entry key="tk103.enable">true</entry>
    <entry key="tk103.port">5008</entry>
</properties>
```

**Comment by hackerunet** [comment]
I'm testing connection also with the android traccar client to see communication but I'm getting error sending data.
So, I need to think what is wrong with my traccar, if is a database end problem maybe I get an error in the logs, but nothing is returned, I'm only getting netty issues like netty was not able to accept a connection, so, that part was already fixed.
If I don't get a database error why the server is refusing connections? nothing is configured in iptables, my firewall is down and accepting connections, so, why is not working? I'm analyzing the OSI layers model to see what the heck is going on.
I'll begin creating a new server with necessary stuff to serve traccar and I'll connect it to the database using my current database and also a small temporary database hosted in the server, that way I get a clue, maybe locked tables are not letting traccar operate correctly, but if that's the case traccar should be able to accept a connection no matter if the database is available, so, after getting a new connection it tries to store into the database if that's not possible an error should be diplayed in logs.
Question, if the issue is something not known like a transactions lock for example, can traccar handle that unkown exception? or it just handles a small errors list ??

**Comment by hackerunet** [comment]
There is a conception issue in traccar anton, the problem is that database engines like mysql needs lots of resources to handle high levels of records. So what I did in my server is to create a tracking table for each vehicle in the system so that way instead of having to query for a single vehicle historical position between millions of records of all vehicles I just have to query in the tracking_imei table, so that way my database engine won't have memory issues.
the problem of implementing that concept is:
1) Maintenance   
2) Table names are variable and mysql engine does not allow use table names as a variable in a query.
my concept worked over 4 years almost but now, after this serious of issues I'm asking myself how to find a solution to get closer to the traccar standard and maybe remove stored procedures or triggers that would be causing issues in my environment.

**Comment by tananaev** [comment]
I see a lot of issues. Let's solve everything one by one. First of all, I don't see any `resetDelay` parameters in your config. That's the reason you accumulate stale connection.

**Comment by hackerunet** [comment]
I just have this one:

    <entry key='database.refreshDelay'>300</entry>

is it different? where do you want me to place the resetDelay?

**Comment by tananaev** [comment]
You need to set it for each protocol like this:
```
<entry key="gps103.resetDelay">60</entry>
```

Value is in seconds. It basically means that if there were no messages for X seconds from device, close the connection.

I wonder how you managed before without it. For any significant number of devices it's a must-have config parameter.

**Comment by tananaev** [comment]
Also, you don't need `[protocol].enable` parameters any more. If you have a port for protocol, it's enabled automatically.

**Comment by hackerunet** [comment]
ok, is all that valid for traccar V2.12 or 3.+ only?

**Comment by hackerunet** [comment]
is it possible to use a variable here and try to use table names depending on the imei received?
This will allow me to remove 3 functions I have to use to achieve storing positions in each vehicle table

**Comment by tananaev** [comment]
It's valid for all version. Can we please solve problems one by one. If you want to discuss multiple issues at the same time, please create a separate thread.

**Comment by hackerunet** [comment]
Yeah, sure, I'm very sorry anton, you are the boss. go on. I'm changing the configuration file to fit your observations.

**Comment by hackerunet** [comment]
now I got this:
```
[root@ip-172-31-31-220 ec2-user]# service traccar console
Running traccar...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.26
wrapper  |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | log4j:WARN No appenders could be found for logger (com.mchange.v2.log.MLog).
jvm 1    | log4j:WARN Please initialize the log4j system properly.
jvm 1    | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
wrapper  | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
I don't know if console option is supported. Please run it as a service.

**Comment by hackerunet** [comment]
[root@ip-172-31-31-220 ec2-user]# service traccar start
Starting traccar...
Waiting for traccar......
WARNING: traccar may have failed to start.
[root@ip-172-31-31-220 ec2-user]# java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (amzn-2.6.1.3.61.amzn1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
[root@ip-172-31-31-220 ec2-user]#

**Comment by tananaev** [comment]
Check `wrapper.log` file. Is it the same error? Are you using original Traccar version?

**Comment by hackerunet** [comment]
nothing is there, Is the configuration file, this doesn't work at all in 2.12 version, yes I'm using traccar official versions.

```
`<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <!-- Global confiduration -->
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
    <entry key='database.dataSource'>com.mysql.jdbc.jdbc2.optional.MysqlDataSource</entry>
    <entry key="database.url">jdbc:mysql://localhost:3306/axiomagps_db?allowMultiQueries=true&amp;allowReconnect=true</entry>
    <entry key="database.user">user</entry>
    <entry key="database.password">pass</entry>

    <!-- Database refresh delay in seconds -->
    <entry key='database.refreshDelay'>300</entry>

    <!-->
        id - Long
        imei - String
    <-->
    <entry key='database.selectDevice'>
        SELECT imei as id,imei as imei
        FROM axioma_vehiculos;
    </entry>

    <!-->
        device_id - String
        time - Date
        valid - Boolean
        latitude - Double
        longitude - Double
        speed - Double
        course - Double
        power - Double (NULL for some protocols)
        extended_info - String (XML)
    <-->

    <entry key='database.insertPosition'>
	START TRANSACTION;         
	INSERT INTO `axiomagps_db`.`axioma_tracking`(`course`,`device_id`,`latitude`,`longitude`,`power`,`speed`,`time`,`valid`,`command`)         
		VALUES (:course,:device_id,:latitude,:longitude,:power,:speed,:time,1,:extended_info);
	CALL insert_tracking(:device_id,:time,1,:latitude,:longitude,:speed,:course,:power,:extended_info);         
	COMMIT;
    </entry>

    <!-- Web interface port -->
    <entry key='http.enable'>false</entry>
    <entry key='http.port'>8082</entry>
    <entry key='http.application'>/opt/traccar/traccar-web.war</entry>

    <!-- Logging options -->
    <entry key='logger.enable'>true</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    <!-- Gps103 server configuration -->
    <entry key="gps103.enable">true</entry>
    <entry key="gps103.port">5001</entry>
    <entry key="gps103.resetDelay">300</entry>

    <!-- EV603 server configuration -->
    <entry key="ev603.enable">true</entry>
    <entry key="ev603.port">5002</entry>
    <entry key="ev603.resetDelay">300</entry>

    <!-- PT502 server configuration -->
    <entry key="pt502.enable">true</entry>
    <entry key="pt502.port">5003</entry>
    <entry key="pt502.resetDelay">300</entry>

    <!-- Meiligao server configuration -->
    <entry key="meiligao.port">5004</entry>
    <entry key="meiligao.resetDelay">300</entry>

     <!-- Android server configuration -->
    <entry key='t55.port'>5005</entry>
    <entry key="t55.resetDelay">300</entry>

    <!-- tk103 server configuration -->
    <entry key="tk103.port">5008</entry>
    <entry key="tk103.resetDelay">300</entry>

    <!-- intellitrac server configuration -->
    <entry key='intellitrac.port'>5009</entry>
    <entry key="intellitrac.resetDelay">300</entry>

    <!-- teltonika server configuration -->
    <entry key='teltonika.port'>5010</entry>
    <entry key='teltonika.resetDelay'>300</entry>

    <!-- h02 server configuration -->
    <entry key='h02.port'>5011</entry>
    <entry key='h02.resetDelay'>300</entry>

    <!-- Meitrack server configuration -->
    <entry key='meitrack.port'>5012</entry>
    <entry key='meitrack.resetDelay'>300</entry>

    <!-- Xexun server configuration -->
    <entry key='xexun.port'>5013</entry>
    
    <!-- AVL-08 server configuration -->
    <entry key='avl08.port'>5014</entry>
    
    <!-- Enfora server configuration -->
    <entry key='enfora.port'>5015</entry>
    
    <!-- Maxon server configuration -->
    <entry key='maxon.port'>5016</entry>
    
    <!-- Suntech server configuration -->
    <entry key='suntech.port'>5017</entry>
    
    <!-- Progress server configuration -->
    <entry key='progress.port'>5018</entry>
    
    <!-- JT600 server configuration -->
    <entry key='jt600.port'>5019</entry>
    
    <!-- V680 server configuration -->
    <entry key='v680.port'>5020</entry>
    
    <!-- TR20 server configuration -->
    <entry key='skypatrol.port'>5021</entry>
    <entry key="skypatrol.resetDelay">300</entry>
    
    <!-- Navis server configuration -->
    <entry key='navis.port'>5022</entry>
    
    <!-- Skypatrol server configuration -->
    <entry key='tr20.port'>5023</entry>
    
    <!-- GT02 server configuration -->
    <entry key='gt02.port'>5024</entry>
    
    <!-- GT06 server configuration -->
    <entry key='gt06.enable'>true</entry>
    <entry key='gt06.port'>5025</entry>
    <entry key="gt06.resetDelay">300</entry>
    
    <!-- Megastek server configuration -->
    <entry key='megastek.port'>5026</entry>
    
    <!-- Navigil server configuration -->
    <entry key='navigil.port'>5027</entry>
    
    <!-- GpsGate server configuration -->
    <entry key='gpsgate.port'>5028</entry>
    
    <!-- MTA6 server configuration -->
    <entry key='mta6.port'>5029</entry>
    
    <!-- MTA6CAN server configuration -->
    <entry key='mta6can.port'>5030</entry>
    
    <!-- TLT-2H server configuration -->
    <entry key='tlt2h.port'>5031</entry>
    
    <!-- Syrus server configuration -->
    <entry key='syrus.port'>5032</entry>
    
    <!-- Wondex server configuration -->
    <entry key='wondex.port'>5033</entry>
    
    <!-- Cellocator server configuration -->
    <entry key='cellocator.port'>5034</entry>
    
    <!-- Galileo server configuration -->
    <entry key='galileo.port'>5035</entry>
    
    <!-- YWT server configuration -->
    <entry key='ywt.port'>5036</entry>
    
    <!-- TK102 server configuration -->
    <entry key='tk102.port'>5037</entry>
    
    <!-- XT7 server configuration -->
    <entry key='xt7.port'>5038</entry>
    
    <!-- Wialon server configuration -->
    <entry key='wialon.port'>5039</entry>

    <!-- Carscop server configuration -->
    <entry key='carscop.port'>5040</entry>

    <!-- Apel server configuration -->
    <entry key='apel.port'>5041</entry>

    <!-- Man Power server configuration -->
    <entry key='manpower.port'>5042</entry>

    <!-- GlobalSat server configuration -->
    <entry key='globalsat.port'>5043</entry>
    
    <!-- Atrack server configuration -->
    <entry key='atrack.port'>5044</entry>
    
    <!-- PT3000 server configuration -->
    <entry key='pt3000.port'>5045</entry>
    
    <!-- Ruptela server configuration -->
    <entry key='ruptela.port'>5046</entry>

    <!-- Topflytech server configuration -->
    <entry key='topflytech.port'>5047</entry>

    <!-- Laipac server configuration -->
    <entry key='laipac.port'>5048</entry>

    <!-- Aplicom server configuration -->
    <entry key='aplicom.port'>5049</entry>

    <!-- Gotop server configuration -->
    <entry key='gotop.port'>5050</entry>

    <!-- Totem server configuration -->
    <entry key='totem.port'>5051</entry>

    <!-- Gator server configuration -->
    <entry key='gator.port'>5052</entry>

    <!-- Noran and UniGuard server configuration -->
    <entry key='noran.port'>5053</entry>

    <!-- M2M mini server configuration -->
    <entry key='m2m.port'>5054</entry>

    <!-- OsmAnd server configuration -->
    <entry key='osmand.enable'>true</entry>
    <entry key='osmand.port'>5055</entry>
    <entry key='osmand.resetDelay'>300</entry>

    <!-- EasyTrack server configuration -->
    <entry key='easytrack.port'>5056</entry>

</properties>

```

**Comment by hackerunet** [comment]
Anton I just test again and without the protocol.enable entry key traccar version 2.12 doesn't work.

**Comment by hackerunet** [comment]
Added suggested params and now is working, everything is up and running I need to let this running for half an hour to see how it behaves.. thanks anton...

**Comment by hackerunet** [comment]
Anton, I think the absence of resetDelay param was the issue, after 30 minutes this are the netstat stats:
```
[root@ip-localhost ec2-user]# netstat -ant | awk '{print $6}' | sort | uniq -c | sort -n
      1 established)
      1 Foreign
      7 SYN_SENT
      9 LAST_ACK
     12 LISTEN
     23 SYN_RECV
    112 TIME_WAIT
    266 FIN_WAIT1
   1693 CLOSE_WAIT
   6813 ESTABLISHED
[root@ip-localhost ec2-user]#
```

**Comment by hackerunet** [comment]
is official, regarding connections, the issue was absence of resetDelay params, somehow It was used before but removed some days ago accidentaly that got all devices down caused by resources massive consumption.
Thanks anton.

**Comment by tananaev** [comment]
As for `[protocol].enable` parameters, I guess they were removed in version 3.3.
