### ISSUE TITLE
Debian installation fails

### ISSUE THREAD

**Issue by Hoekynl** [tananaev/traccar#1714]
Hello Traccar users,

I want to install traccar to my Pi at home. I downloaded the 3.3 zip and want to run traccar.run as sudo.
This error rolls out :
`pi@pi:~ $ sudo ./traccar.run
Verifying archive integrity... All good.
Uncompressing traccar  100%
./setup.sh: 5: [: -lt: unexpected operator
Detected Ubuntu or Debian:
Installing the traccar daemon using init.d..
`

How am I able to solve this? Traccar won't start.

**Comment by tananaev** [comment]
Try to change default shell to bash if it's not.

**Comment by Hoekynl** [comment]
Tried to change, dont know if it's correct.
`pi@pi:~ $ cat /etc/shells
# /etc/shells: valid login shells
/bin/sh
/bin/dash
/bin/bash
/bin/rbash
pi@pi:~ $ echo $SHELL
/bin/bash
pi@pi:~ $ chsh
Password:
Changing the login shell for pi
Enter the new value, or press ENTER for the default
        Login Shell [/bin/bash]: /bin/bash
pi@pi:~ $ sudo ./traccar.run
Verifying archive integrity... All good.
Uncompressing traccar  100%
./setup.sh: 5: [: -lt: unexpected operator
Detected Ubuntu or Debian:
Installing the traccar daemon using init.d..
`

**Comment by tananaev** [comment]
I guess you need to change default shell for root user because you run the script as a root (`sudo`).

**Comment by Hoekynl** [comment]
Unfortunatly the error still occurs after changing the shell

`
pi@pi:~ $ sudo echo $SHELL
/bin/bash
pi@pi:~ $ sudo chsh
Changing the login shell for root
Enter the new value, or press ENTER for the default
        Login Shell [/bin/bash]: /bin/bash
pi@pi:~ $ sudo ./traccar.run
Verifying archive integrity... All good.
Uncompressing traccar  100%
./setup.sh: 5: [: -lt: unexpected operator
Detected Ubuntu or Debian:
Installing the traccar daemon using init.d..
`

**Comment by tananaev** [comment]
OK, as a workaround you can extract files manually and install Traccar manually.

For info on how to extract files check help:

```
./traccar.run --help
```

When you extract everything check `setup.sh` file to see what it does to install service. It basically copies files to `/opt/traccar` and then registers service.

**Comment by Hoekynl** [comment]
I extracted the files to /home/pi/traccar.
The setup.sh script contains :
`#!/bin/sh

UNIX_PATH="/opt/traccar"

if [ $(java -version 2>&1 | grep -i version | sed 's/.*version "\(.*\)\.\(.*\)\..*"/\1\2/; 1q') -lt 17 ]
then
  echo "Please install Java version 7 or higher"
else
  mkdir -p $UNIX_PATH
  cp -rf * $UNIX_PATH
  chmod -R go+rX $UNIX_PATH
  $UNIX_PATH/bin/traccar install
  rm $UNIX_PATH/setup.sh
fi
`

I have installed the latest java, so I could remove line 5,6,7, and 8 ? That is where the error is from.
Do I just execute `sudo ./setup.sh` now?

**Comment by tananaev** [comment]
You need Java version 7 or higher. If you already have latest, you can just ignore all the if statements.

**Comment by Hoekynl** [comment]
My setup.sh
`#!/bin/sh

UNIX_PATH="/opt/traccar"

#if [ $(java -version 2>&1 | grep -i version | sed 's/.*version "\(.*\)\.\(.*\)$
#then
#  echo "Please install Java version 7 or higher"
#else
  mkdir -p $UNIX_PATH
  cp -rf * $UNIX_PATH
  chmod -R go+rX $UNIX_PATH
  $UNIX_PATH/bin/traccar install
  rm $UNIX_PATH/setup.sh
#fi
`
Installer gives error :
`pi@pi:~/traccar $ sudo ./setup.sh
Detected Ubuntu or Debian:
Installing the traccar daemon using init.d..
pi@pi:~/traccar $ sudo /opt/traccar/bin/traccar start
Starting traccar...
/opt/traccar/bin/./wrapper: 1: /opt/traccar/bin/./wrapper: Syntax error: word unexpected (expecting ")")
Waiting for traccar..................
WARNING: traccar may have failed to start.
`

**Comment by tananaev** [comment]
Looks like there is some problem with Java Service Wrapper now. I think the problem is still with default shell. I would recommend to find out a way to set shell to bash for root user.

**Comment by Hoekynl** [comment]
But isn't the root shell already bash?
```
pi@pi:~/traccar $ sudo echo $SHELL
/bin/bash
```

**Comment by tananaev** [comment]
Check the first line in the `wrapper` file. If it's not bash, change it to bash.

**Comment by Hoekynl** [comment]
Uhm.. `sudo nano /opt/traccar/bin/wrapper` returns
```
^?ELF^B^A^A^@^@^@^@^@^@^@^@^@^B^@>^@^A^@^@^@�U@^@^@^@^@^@@^@^@^@^@^@^@^@��^D^@^$
^@^@^@�^@^@^@^@^@^@^@^@^@^@^@^S^@^@^@^M^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^T^@^@^@^@$
^@^@^@@^Q!�^PyO"^B(^@ aC^@^A^B^@^A^B^@^@^A"y^D^E4^@^C �^@�^L ނ^Q�$^A
#P�h^D^Q^B2^B^AH^H �^H�^@^@@^H^@ ^Q^X^A^D"^Up4^@A^@D�^@A^A%^D8�^P@^@�^L�0^B^D�^$
^KId�^@[�?�(�8�V^Mi�2��^Xt�^Y"s�o�K��Ͱ Eīë֫^Y^C]!u��1ѫ^G��k5^S�d�ګ=3�ޫ%�A�۫^X�v@�^$
�$^?�^Yn=#mu�G�zm�I�J�t�݆�چ"�L��-ۆ9��q�?ʆ^M�g�3�ӆt       5�CAF   =)�cB�ˆ^O'o�fu�$
[@A
�v�1x)^NXe���ԝ�^W^?zݝѝp)?�ޝ^C�n^O@̝S�^Ul��"ʜ�Y�eE���Q��Ԝ^]^N��^D���^A�ߜ^R2��t!��$
^D^@^@^Q^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@M^A^@^@^R^@^@^@^@^@^@^@^@^@^@^@^@$
^@^@^Q^@^Y^@^@�d^@^@^@^@^@^H^@^@^@^@^@^@^@Q^F^@^@^Q^@^Z^@�ee^@^@^@^@^@^H^@^@^@^$
^@^@^Q^@^Z^@��d^@^@^@^@^@^D^@^@^@^@^@^@^@�      ^@^@^Q^@^Z^@@�d^@^@^@^@^@^D^@^@$
^E^@^@^Q^@^Z^@�4e^@^@^@^@^@^H^@^@^@^@^@^@^@�^H^@^@^Q^@^Y^@^P�d^@^@^@^@^@^H^@^@^$
^@^@^Q^@^Z^@P�d^@^@^@^@^@^D^@^@^@^@^@^@^@M      ^@^@^Q^@^Z^@`�d^@^@^@^@^@^D^@^@$
^@^@^Q^@^Y^@��d^@^@^@^@^@^D^@^@^@^@^@^@^@?^H^@^@^R^@^N^@ �A^@^@^@^@^@%^@^@^@^@^$
^@^@^Q^@^Z^@P�d^@^@^@^@^@^D^@^@^@^@^@^@^@Q^G^@^@^Q^@^Y^@��d^@^@^@^@^@^D^@^@^@^@$
^@^@^Q^@^Z^@��d^@^@^@^@^@^D^@^@^@^@^@^@^@�
^@^@^Q^@^Z^@0Di^@^@^@^@^@^D^@^@^@^@^@^@^@�^G^@^@^Q^@^Y^@(�d^@^@^@^@^@^H^@^@^@^@$
^@^@^Q^@^Z^@��d^@^@^@^@^@^H^@^@^@^@^@^@^@�^E^@^@^Q^@^Y^@^H�d^@^@^@^@^@^H^@^@^@^$
^@^@^Q^@^Z^@�Ci^@^@^@^@^@^H^@^@^@^@^@^@^@�

```

**Comment by tananaev** [comment]
Looks like it's a binary file. Not sure what can be done at this point. I guess there is some compatibility issue between Java Service Wrapper and Debian.

You can try to run Traccar manually:

https://www.traccar.org/manual-installation/

**Comment by Hoekynl** [comment]
Manual installation doesn't work either. I tested it on a different installation.

The ARM installation package does install, but also doesn't start.
This time the error is :
```
Starting traccar...
Segmentation fault
Waiting for traccar..................
WARNING: traccar may have failed to start.
```

**Comment by tananaev** [comment]
Wait, what is the architecture of your system?

**Comment by Hoekynl** [comment]
The raspberry pi is ARMv6

**Comment by tananaev** [comment]
Java Service Wrapper doesn't work on Raspbery Pi. You need to run Traccar manually:
```
java -jar /opt/traccar/tracker-server.jar /opt/traccar/conf/traccar.xml
```

**Comment by Hoekynl** [comment]
Seems to work with that command!
Got it to boot at startup aswell with screen. Thanks!!

**Comment by dennisonm** [comment]
Is there any update for CentOS? 

I'm still facing this issue:
`sudo: /opt/traccar/bin/traccar: command not found`

It will run using `java -jar /opt/traccar/tracker-server.jar /opt/traccar/conf/traccar.xml`, but I can't figure out how to make it run automatically at startup. Java newbie.
