### ISSUE TITLE
Invalid Location Jumps for vehicles

### ISSUE THREAD

**Issue by nitinzambani** [tananaev/traccar#1720]
seems like many of the devices are showing invalid position jumps,
vehicle is showing at one place and then another place which is at  10 to 30 miles distance and then back to original place...!

i have added the snap of map, here vehicle is going from A to B and its jumping in between to location c many times. this is just 15 min travel
![map](https://cloud.githubusercontent.com/assets/16347581/12999029/9d452740-d170-11e5-8ffa-535adc036119.JPG)

device used : name is GT02a, and its protocol is TK103

 attached an txt file with data of position table for single device
the last column is what i have added to calculate distance from last location 
you wiill see for few locations its showing distance as 23136 meters...!

[mp.txt](https://github.com/tananaev/traccar/files/127508/mp.txt)

also attached log files for the same day 

[tracker-server.log.20160210_1.txt](https://github.com/tananaev/traccar/files/127518/tracker-server.log.20160210_1.txt)

**Comment by nitinzambani** [comment]
HI tananaev
by the time we get resolution for this, i was thinking of an workaround , I am checking the distance between current location update with previous location , id the distance is greater than lets say 1000 meter then i will mark it as valid = false

below is the mysql 
    <entry key='database.insertPosition'>
		
		-- Map the java variables to sql variables.
		SET @deviceId = :deviceId;
		SET @latitude = :latitude;
		SET @longitude = :longitude;
		SET @Valid = :valid;

		-- Let select the last position latitude and longitude for this device.
		SELECT latitude, longitude 
			INTO  @last_latitude, @last_longitude 
			FROM positions WHERE device_id = @deviceId ORDER BY serverTime DESC LIMIT 1;


		-- Let calculate the Geo Distance between the to position.
		SET @distance =	ROUND( DEGREES(ACOS(COS(RADIANS(@last_latitude)) * COS(RADIANS(@latitude)) *
					COS(RADIANS(@last_longitude) - RADIANS(@longitude)) +
					SIN(RADIANS(@last_latitude)) * SIN(RADIANS(@latitude)))) * 111.045 * 1000 );

	IF(@distance > 1000) THEN SET @Valid = false;
	END IF;
	

	INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other, distance)
	VALUES (:deviceId, :protocol, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), @Valid, :latitude, :longitude, :altitude, :speed, :course, :address, :other, 
@distance);

but its not allowing IF statement in the script 

any idea ?

**Comment by tananaev** [comment]
I can see that in the log file there is a lot of filtering and unknown devices. Can that be a problem?

**Comment by nitinzambani** [comment]
well filtering has been working for more than 6 months now so that shd not be a problem
regarding the unknown device its only one device which is not registered and all the logging is for that device only  , i had removed this unknown  device later for a while but this did not solve problem. 
has anybody else has reported this kind of problem ?

**Comment by tananaev** [comment]
Can you please point out specific lines in the log file where the problem happens.

**Comment by nitinzambani** [comment]
yes, i have highlighted problem at two instances one at  2016-02-10 04:39:34 and another at 2016-02-10 04:29:39
both can be seen in mp.txt file as well.
for first issue i.e at 2016-02-10 04:39:34 i have attached log from 2016-02-10 04:39:30 to 2016-02-10 04:39:40 in file named "log for 1.txt" as i do not know which log line corresponds to the issue  

similarly "log for 2.txt" for second time
[log for 1.txt](https://github.com/tananaev/traccar/files/127933/log.for.1.txt)
[Log for 2.txt](https://github.com/tananaev/traccar/files/127934/Log.for.2.txt)

**Comment by tananaev** [comment]
Please provide logs including decoded data. I don't see any problems in the attached files.

**Comment by nitinzambani** [comment]
By decoded data u mean
Wrapper log ?
I have given  the complete log other than there is no log

**Comment by tananaev** [comment]
In the logs you gave me I can see only a couple of location reports and all of them are from different vehicles. I don't see any "jumping" there.

**Comment by nitinzambani** [comment]
i m not getting what u are trying to find in the logs 
for checking jumping u will have to get the locations for same device and compare its location updates 

in position table it seen with two locations of same device with distance more than 20 km and time difference in seconds

**Comment by nitinzambani** [comment]
![jumping](https://cloud.githubusercontent.com/assets/16347581/13027859/b5c7d3de-d284-11e5-989d-fb9719345488.JPG)
![jumping zoom](https://cloud.githubusercontent.com/assets/16347581/13027858/b5c40808-d284-11e5-8c08-6221f8a1a05e.JPG)

this is one more example of how it is looking due to multiple jumps

**Comment by tananaev** [comment]
Log stores all the messages and original data from devices. I want to find two messages where the jump happens.

The picture reminds me of a problem where there were two devices with the same device identifier. Can it be the case here?

**Comment by nitinzambani** [comment]
Two devices with same identifier not possible
As this problem is not fir one or two devices but  almost all of my devices
are giving this problem

For jumping log , how can I identify which log line is for which of the
record in db position table ?
So that I can find the corresponding log for jumped location and send you
that

**Comment by tananaev** [comment]
I think the easiest way for you to identify log records is by reported time in the `INFO` messages.

**Comment by nitinzambani** [comment]
Ok great
Let me check

**Comment by nitinzambani** [comment]
Hi Tananaev

i have identified the logs for jumps, 
i have attached a log file with location updates of device id 6

i have also attached the archive panel and map images for the same time frame to show how it is looking into map.

please check , you can see there are multiple jumps in just 5 min of time
check the last location it shows 34 KM away from the previous location
[devicelog.txt](https://github.com/tananaev/traccar/files/130910/devicelog.txt)
![device archive panel](https://cloud.githubusercontent.com/assets/16347581/13051501/86b820e8-d41f-11e5-935a-148c23385432.png)
![device map](https://cloud.githubusercontent.com/assets/16347581/13051505/8ba40d92-d41f-11e5-9261-bb2797a0e42e.JPG)
![device map 2](https://cloud.githubusercontent.com/assets/16347581/13051507/90273f2e-d41f-11e5-95ae-e81d77111068.JPG)
![device map 3](https://cloud.githubusercontent.com/assets/16347581/13051519/95db22dc-d41f-11e5-9ab0-c42e552f6377.JPG)

**Comment by nitinzambani** [comment]
HI,
found the problem the device was sending right locations but not in order of path,
and i was not saving the device time instead i was saving serverTime only 
so when the route was showing on map , it was looking weird

thanks tananaev for your help 
and sry for the trouble

**Comment by nitinzambani** [comment]
i am changing the config to save device time now, 
will close the issue, if the issue is actually resolved after monitoring for 1 or 2 days

**Comment by tananaev** [comment]
Good to hear that it works now.
