### ISSUE TITLE
SNAPSHOT: 3.3

### ISSUE THREAD

**Issue by franiis** [tananaev/traccar#1722]
Hi, 
I have very simple question.
Today I installed the Traccar 3.3 from website (Linux 64). Earlier I removed older version. Now I have in logs something like this:

`2016-02-12 10:39:35  INFO: Version: 3.2-SNAPSHOT`

Is that mean that I have some uninstalled files/wrong version?
Or maybe the version on website has wrong number (commit with new version was commited on 23.12 - day of new version - but pushed to master 2 days later - if I'm not mistaken)?

Greetings,
Piotr

**Comment by tananaev** [comment]
It's a known issue. I forgot to update package version when released version 3.3. If you downloaded it from the official website, it should be the latest.

**Comment by franiis** [comment]
OK, sorry for trouble (I tried, but I did'n find any info in issue tracker).
Thank you very much :)
