### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by theMastablasta** [tananaev/traccar#1726]
Not able to get any connection. Using an android emulator and a Samsung S6. Both do a position update but transmitting error occurs right after that. Using my public ip and tried local ip also as the S6 is inside the same network. Firwall on/off makes no difference. 
Log:
```
2016-02-15 13:40:05  INFO: Starting server...
2016-02-15 13:42:21  INFO: [84C556C1] connected
2016-02-15 13:42:21 DEBUG: [84C556C1: 5037 < 127.0.0.1] HEX: 30303063686f73743a76657273696f6e
2016-02-15 13:42:21  INFO: [287DFD7F] connected
2016-02-15 13:42:21 DEBUG: [287DFD7F: 5037 < 127.0.0.1] HEX: 30303231686f73743a636f6e6e6563743a3139322e3136382e3139322e3132383a35353535
2016-02-15 13:42:21  INFO: [287DFD7F] disconnected
2016-02-15 13:43:21  INFO: [CE3F1B9C] connected
```

**Comment by tananaev** [comment]
There is nothing in the log from Traccar Client. It means server doesn't receive any data from device. There must be some network issue.

**Comment by theMastablasta** [comment]
"port 5055 is closed", so that's my problem. Opened the port at the windows firewall but it's still closed. Sure it's my router. Tried to open that port on the router but fails. Looks like a problem with this W724 router in general (to open ports). I will try again today.

**Comment by tananaev** [comment]
Are you sure your ISP provides you with public IP address?

**Comment by theMastablasta** [comment]
I tried this for example: https://www.whatismyip.com/what-is-my-public-ip-address/
And here it shows the ip

**Comment by tananaev** [comment]
Some internet provider use NAT. If that's the case, you won't be able to access it.

**Comment by theMastablasta** [comment]
Looks like Telekom Germany is using NAT. Even if the NAT type is set to open?

**Comment by tananaev** [comment]
I would recommend to contact your ISP and clarify it. If you are behind NAT, you won't be able to use Traccar on your local computer. You would have to get a VPS server.

**Comment by theMastablasta** [comment]
The router supports DDNS. Would this help?

**Comment by tananaev** [comment]
It would help if your internet provider gives you dynamic public IP address. But it won't help in case of NAT.

**Comment by theMastablasta** [comment]
Which means the only solution for me would be a VPS server.

**Comment by theMastablasta** [comment]
Are there any specifics I must note before I get a VPS server? I would like to get one but as there are costs involved I want to be sure to do the right choice. And thanks a lot for your help @tananaev!

**Comment by tananaev** [comment]
I would recommend to get at least 1GB of RAM for VPS.

**Comment by theMastablasta** [comment]
Thanks, I will try tomorrow.

**Comment by theMastablasta** [comment]
Could this VPS do the job?
https://contabo.com/?show=configurator&vserver_id=145

**Comment by tananaev** [comment]
Yes, it should be fine.

**Comment by theMastablasta** [comment]
Got it worky without a VPS. Set router NAT Type to open and opened port 5055. Works with local network (IPv4) and also with the public IP.  Thanks again!
