### ISSUE TITLE
telic picotracker protocol improvement

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#1735]
Hi,

I installed Traccar server and i think it is one of best open source servers avaiable, so thank you for that!

Since i am using Telic Picotracer i would also like to see ADC values under "State" section on server. ADC1 gives values between 0.255 and it shows battery voltage, that is why it is important for me and probably to all others users who are using Picotracker.

I found that Picotracker data string is something like that and i can probably found out where is the ADC value in that string, but how to add that feature to server?

'telik' : '182012345699,010100001301,0,270613041652,166653,475341,3,0,355,6,2,1,231,8112432,23201,01,00,217,0,0,0,0,7\0',

**Comment by tananaev** [comment]
I need protocol documentation to implement ADC and other additional data decoding.

**Comment by argokask** [comment]
I do not have the proper documentation for that protocol  but i investigated that data string little bit and i have found out what these numbers means.

I decoded original HEX message to ASCII, that is the ouput:

**c**0720970613**99**,**190216110707**,0,**190216110706**,**123456**,**123456**,3,2,179,4,,,46,4394522,,0010,00,**112**,0,0,0108

c - ASCII equivalent of the lenght of GPRS data string
99 - message type (99 is time periodical message)
190216110707 - data time stamp of the message
190216110706 - data time stamp of GPS position
123456 - longitude
123456 - latitude
112 - battery voltage 3,81V (8bit ADC output: values from 0 to 255 meas range 3,50V - 4,30V )

ADC value vs voltage:

4,33V = 250
3,47V = 0

To calculate those values equation would be something like that.

**(adc value / 10) * 0,03 + 3,47 = voltage**

I hope that helps. I would be very thankful when you can help me out with that tihing.

**Comment by tananaev** [comment]
Can you please provide original HEX message.

**Comment by argokask** [comment]
Original HEX message:

650000003033323039373036313339392c3231303231363131323830302c302c3231303231363131323735392c3234363931322c3539343037362c332c34372c3239312c31302c2c2c34362c343431393239302c2c303031302c30302c3130302c302c302c3031303800

Decoded message:

**e**0320**xxxxxx****99**,**210216112800**,0,**210216112759**,**123456**,**123456**,3,47,291,10,,,46,4419290,,0010,00,**100**,0,0,0108

*at this point ADC value = 100  (3,77V)
*xxxxxx is IMEI last 6 digits


When connection starts between tracker and server first message includes adittional information about carrier and tracker identification.



303032363937303631337c3234387c30317c30303430303630313100640000003030333039373036313332352c3231303231363131323633302c302c3231303231363030313430352c3234363938352c3539343037382c332c302c3238332c31322c2c2c32332c343431383636392c2c303031302c30302c3131372c302c302c3031303800


0026**xxxxxx**|**248**|**01**|004006011d0030**xxxxxx**25,**210216112630**,0,**210216001405**,**123456**,**123456**,3,0,283,12,,,23,4418669,,0010,00,**117**,0,0,0108


*xxxxxx is tracker IMEI last 6 digits
*248 is carrier country code (248 = Estonia)
*01 is carrier company code (01  = Estonian Telia)
*210216112630  timestamp
*210216001405  timestamp
*123456 longitude
*123456 latitude
*117 batt voltage

**Comment by tananaev** [comment]
I have implemented battery values decoding for Telic protocol.

**Comment by argokask** [comment]
Hi Anton, 

Thank you for protocol fix.

Can you please give me brief overview how to add that fixed protocol to my existing gps server? I am using Win7 operation system.

If i open traccar-server jar file with 7z then i see folder "protocol" (tracker-server.jar\org\traccar\protocol\) and under that i see three Telik class files. Whad should i do with those files and how to correctly add new implemented fix to there?

**Comment by tananaev** [comment]
First of all, you need to make sure have latest release installed. After that replace `tracker-server.jar` file with this one:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

Finally restart the service and you should see battery level values.

**Comment by argokask** [comment]
Ok, thank you Anton.

Do i need also new traccar.xml file (there is protocol named "telik" but new protocol name is "telic"). Under the "web" folder, do i have to update someting there also?

**Comment by tananaev** [comment]
You need to rename protocol in the config, but no other changes are required.

**Comment by argokask** [comment]
Hi Anton,

Yes, now i see the battery line. Thank you for helping me. 

Is it possible to add also the forumla to calculate ADC 8bit value to battery voltage.

(adc_value / 10) * 0,03 + 3,47 = voltage

It is not very important for me but if you will find the time for that and if it is not very complicated to add i would be happy about that.

Best regards.

**Comment by tananaev** [comment]
Are you sure the formula is the same for all devices that use Telic protocol?

**Comment by argokask** [comment]
Hi Anton,

not sure about that because i have tested only Picotrackers. 

**http://www.telic.de/en/products/asset-tracking**

There are second type of trackers from Telic and those i dont know.

**http://www.telic.de/en/products/professional-vehicles/sbc-avl**

**Comment by tananaev** [comment]
I am happy to implement the formula, but only if it would work for all devices. You can try to confirm with the manufacturer if it's the case.

**Comment by argokask** [comment]
Hi Anton, 

I have now better knowledge about both Telic devices (Picotracker and SBC-AVL).

They both have exactly the same protocol, but now i have the corrected formula for internal battery. I found out that telic protocol includes also external battery values and formula.  Below there are two examples, one for Picotracker and another for SBC-AVL. Is it possible that you add both values with formulas to the server? I would be very grateful. 

The only difference is at the startup when tracker starts establishing connection to the server, Picotracker sends one long message (imei, country code, carrier id) with GPS data but SBC-AVL sends first message for connection startup (imei, country code, carrier id) and then sends next message with GPS data. I hope there is no problem because of that.


**HEX message from Picotracker at startup:**

303032363937303631337c3234387c30317c30303430303630313100640000003030333039373036313332352c3231303231363131323633302c302c3231303231363030313430352c3234363938352c3539343037382c332c302c3238332c31322c2c2c32332c343431383636392c2c303031302c30302c3131372c302c302c3031303800

**Decoded GPS message from Picotracker:**

**0026xxxxxx|248|01|004006011**d0030xxxxxx25,210216112630,0,210216001405,123456,123456,3,0,283,12,,,23,4418669,,0010,00,117,0,188,0108

*the first part of the message is deliverd only when establishing connection with server:(0026xxxxxx|248|01|004006011)

*xxxxxx is tracker IMEI last 6 digits
*248 is carrier country code (248 = Estonia)
*01 is carrier company code (01 = Estonian Telia)
*210216112630 timestamp
*210216001405 timestamp
*123456 longitude
*123456 latitude
*117 batt voltage                     ==> INTERNAL battery voltage formula: U = 3.4 + (ADC_val * 0,00345)
*188 external supply voltage   ==> EXTERNAL supply voltage formula U = 6 + (ADC_val / 8 )



**Message from SBC-AVL at startup:**

SBC-AVL sends first message to server for establishing connection:

303032363232323232327c3234387c30317c30303230303430303100

0026**xxxxxx**|248|01|002004001    //imei last 6 digit, country code, carrier id

**HEX GPS data message from SBC-AVL:**

Then sends GPS data:

5c0000003539323037383232323232322c3031303130303033303230302c302c3234303531363133333530302c3232323232322c3232323232322c332c302c302c352c2c2c33372c3332342c2c313031302c30302c34382c302c302c3034303600

**Decoded GPS data message from SBC-AVL:**

\592078xxxxxx,010100030200,0,240516133500,123456,123456,3,0,0,5,,,37,324,,1010,00,117,0,**188**,0406

*xxxxxx is tracker IMEI last 6 digits
*210216112630 timestamp
*210216001405 timestamp
*123456 longitude
*123456 latitude
*117 batt voltage                     ==> INTERNAL battery voltage formula: U = 3.4 + (ADC_val * 0,00345)
*188 external supply voltage   ==> EXTERNAL supply voltage formula U = 6 + (ADC_val / 8 )


Best regards,
Argo

**Comment by tananaev** [comment]
I will take a look in a couple of days.

**Comment by tananaev** [comment]
I've implemented battery and external power info decoding.

**Comment by argokask** [comment]
Big thanks to you!

Can you please support me with dropox download link like last time. 

Last time you gave me dropox link where was new "tracker-server.jar" file with that fix included. Then i can just copy and replace it.

Thanks again !

Best regards,
Argo

**Comment by tananaev** [comment]
Try this version:

https://www.dropbox.com/s/myt68q5u7fiz49r/tracker-server-jar-with-dependencies.jar?dl=0

**Comment by argokask** [comment]
Hi Anton,

I downloaded the file and replaced old file with that one (i changed file name to "tracker-server.jar"). When i started the service then all my old added trackers was gone. Then tried to add them again but error popup occurs with no text inside. At the moment seems like it is not working for some reason.

Best regards,
Argo

**Comment by tananaev** [comment]
There have been some changes, so it's totally possible that there is some compatibility issue.

**Comment by argokask** [comment]
Ok, can i do something about it ?

**Comment by tananaev** [comment]
Check browser console for errors.

**Comment by argokask** [comment]
Hi Anton,

I reinstalled server and now i can add users and devices. 

Can you check that protocol again because the value "Power" equals 6 all the time ? When i looked incoming messages for example there is dec value 51 which should equal something like 12.3. 

Value "Battery" is works well.

**Comment by tananaev** [comment]
Please provide message samples where the power value is incorrect, and provide correct value as well.

**Comment by argokask** [comment]
Hi Anton,

**hex message from SBC-AVL unit:**

64000000303332303738xxxxxxxxxxxx2c3232303631363034343230302c302c3232303631363034343230302c3234373136392c3539333931312c332c34382c3234382c382c2c2c35302c313032343834362c2c313131312c30302c34382c302c**3531**2c3034303600

**xxxxxxxxxxxx  is my gps device ID

**converted hex to ascii:**

d032078xxxxxx,220616044200,0,220616044200,247169,593911,3,48,248,8,,,50,1024846,,1111,00,48,0,**51**,0406

**xxxxxx is my gps device ID

Power value in hex = 3531 
Power value in ascii = 51
Calculated power = 6 + (power_value / 8)  = 12.375

**Comment by tananaev** [comment]
Fixed the problem. I would recommend to wait till next official release because there were a lot of changes in the server code, so I'm not sure if it's compatible with previous release.

**Comment by argokask** [comment]
Hi Anton,

Thank you for helping me out ! I will be waiting next official release.
