### ISSUE TITLE
Distance Calculation Issue

### ISSUE THREAD

**Issue by nefertiti007** [tananaev/traccar#1738]
Dear Anton,

Many chinese devices, when powered on for the first time sends 1 or 2 position updates with location of china.

In such cases, distance results then turn out to be wrong.

I feel a solution to (calibrate distance value should be a good idea)

**Comment by tananaev** [comment]
Are those initial positions marked as `valid`?

**Comment by nefertiti007** [comment]
Yes, in GT06n I have noticed this in.  attaching screenshot.
![yes](https://cloud.githubusercontent.com/assets/1138485/13167420/f26b0004-d6f8-11e5-9220-b1d91f8da3b5.jpg)

**Comment by tananaev** [comment]
I have added check for position validity to include only correct locations in distance calculation. Here is a new build to try:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

**Comment by nefertiti007** [comment]
Dear Anton,

I will check it in the next few days, as I will need to test it with a new device. Shall update on here .
