### ISSUE TITLE
Hidden app during Running Crash

### ISSUE THREAD

**Issue by amet123** [tananaev/traccar#1739]
Hi

Hidden app during Running Crash and unable to open after dial (8722227)

Thanks

**Comment by tananaev** [comment]
Which version are you using?

**Comment by amet123** [comment]
Just download from taccar website

**Comment by tananaev** [comment]
Yes, but when did you download it? Today?

**Comment by amet123** [comment]
Yesterday

**Comment by tananaev** [comment]
What phone are you using? What is Android version?

**Comment by amet123** [comment]
Motorola

**Comment by amet123** [comment]
5.0

**Comment by tananaev** [comment]
Please try this version:

https://github.com/tananaev/traccar-client-android/releases/download/v3.9/app-hidden-release.apk
