### ISSUE TITLE
Unable to see my TK102 in demo.traccar.org

### ISSUE THREAD

**Issue by jslmiatb** [tananaev/traccar#1740]
Good afternoon.

I would like to test my new TK102 in demo.traccar.org (bought here http://www.amazon.com/gp/product/B01535CSCE/ref=pd_lpo_sbs_dp_ss_1?pf_rd_p=1944687622&pf_rd_s=lpo-top-stripe-1&pf_rd_t=201&pf_rd_i=B013FV8EB2&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=1BAEJN6Y43Q73FH5SPMH)

The sim car inside is an nigerian Etisalat car. So I set : "apn+password etisalat" following the instructions and details here http://etisalat.com.ng/easyblaze-data-services/internet-settings/

I ran this command "t030s***n+password" to activate auto track. Then I declared my device in demo.traccar.org using the IMEI of the GPS Tracker.

By the end I set "adminip+password 40.122.161.243 XXXX" with all the ports proposed here https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/. But I never see the coordinates in the web interface when I refresh the interface.

Which is my mistake ?
Thanks in advance.

**Comment by maxicabanillas78** [comment]
Port 5001

**Comment by jslmiatb** [comment]
I tried twice but it didn't work at all. When I send a "check+password" I have GPRS OK.

**Comment by tananaev** [comment]
What's the device id?

**Comment by jslmiatb** [comment]
Do you mean the imei of device I entered in the console ?

**Comment by tananaev** [comment]
Yes.

**Comment by jslmiatb** [comment]
I wouldn't like publish the imei on internet. Everybody could play whit that on internet... It's not safe, no ?

**Comment by tananaev** [comment]
It's just a number, but if you want you can just send it to me by email (address is in profile).

**Comment by jslmiatb** [comment]
Here is the imei 352887072059573. Thank you

**Comment by tananaev** [comment]
Your device is using TK103 protocol. Try port 5002. Also, you should use 087072059573 as unique id.

**Comment by jslmiatb** [comment]
Ok. Thanks. I tried with "adminip+password 40.122.161.243 5002" and created a new device with this unique id like this 087072059573. Still not working my GPRS status show OK.

**Comment by tananaev** [comment]
I can see it's working. Please wait a little or refresh the page.

**Comment by jslmiatb** [comment]
You are right !!! It's true ! Thank you so much. Does the web page do an auto-refresh ???

**Comment by tananaev** [comment]
It should update data live.

**Comment by jslmiatb** [comment]
Last question. If I would install Traccar server does it provide web page to show result or is it possible to create our own resultw website ?

**Comment by jslmiatb** [comment]
You do a great job ! By the end, I think my problem is solved. Thank you.

**Comment by tananaev** [comment]
If you install Traccar, you'll get the same functionality as you see on the demo server. Of course you can customize it if you want because source code is available.

**Comment by jslmiatb** [comment]
Ok Thank you. It's "only" avalaible in Java, that's it ? Not in python ?

**Comment by tananaev** [comment]
Yes, back-end is Java only. Web interface is in JavaScript.

**Comment by jslmiatb** [comment]
Ok. THank you so much. Bye.
