### ISSUE TITLE
Google reverse geocoder

### ISSUE THREAD

**Issue by theMastablasta** [tananaev/traccar#1742]
Address field using WebUI is blank. MySQL db table showing _null_.
Config file:
```
    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>
```
What am I doing wrong?

**Comment by tananaev** [comment]
I've just tested it on default Traccar version and it works just fine. Maybe you are reaching Google API limit or there is some networks issue?

**Comment by theMastablasta** [comment]
Can't be the limit as it never worked so far. Network? Good question...

**Comment by theMastablasta** [comment]
<entry key='geocoder.processInvalidPositions'>true</entry>
was the solution! All worky now
