### ISSUE TITLE
xexun TK102-2 battery voltage

### ISSUE THREAD

**Issue by M230** [tananaev/traccar#1754]
Hello, I was wondering if it's possible to implement battery voltage for the xexun protocol? My TK102-2 sends this information however it is not displayed.

**Comment by tananaev** [comment]
Are you using your own server?

**Comment by M230** [comment]
Yes, running on Debian.

**Comment by tananaev** [comment]
You can try following config parameter:
```
<entry key='xexun.extended'>false</entry>
```

**Comment by M230** [comment]
That did the trick, Thanks!

**Comment by carlosjs** [comment]
Hello. I've tried to apply that trick to show the voltage with no luck. Should this line added to config.xml or to default.xml ? Any specific section ?
Anyway, I've tried with both and no results came after restarting the server. Any hint?
Thanks !

**Comment by tananaev** [comment]
@carlosjs, I would recommend to create a new issue and provide HEX samples.
