### ISSUE TITLE
Change nautic miles to kmh

### ISSUE THREAD

**Issue by thogo1977** [tananaev/traccar#1761]
Hello,
thanks or great work.

Is it possible to change the incoming data for speed of my tracker to km/h? I use the tk103 protokoll. The tracker delivers speed in nautic miles and i whant to see it in km/h.

Thanks for helping.

ThoGo

**Comment by tananaev** [comment]
You can change units in the web interface. Check account or server settings.

**Comment by thogo1977** [comment]
thanks, that is right in /preferences/speed unit. 

Of wikepedia https://en.wikipedia.org/wiki/Knot_%28unit%29

1 international knot =
    1 nautical mile per hour (by definition),
    1.852 kilometres per hour (exactly),[3]
    0.514 metres per second (approximately),
    1.151 miles per hour (approximately),
    20.254 inches per second (approximately). 

So my traccer transmited 0.2699785 nmh or knot than traccar has to show 0,5 km/h 0,26knots and 0,31mph. But traccar shows only 0,4 km/h, 0,22 knots and 0,25 mph.

How can i change the factor or do i make a mistake.

Thanks

ThoGo

**Comment by tananaev** [comment]
Here is the code:

https://github.com/tananaev/traccar/blob/master/web/app/store/SpeedUnits.js

Values are correct as you can see. Are you sure you are looking at the same position instance in the web interface and database?

**Comment by thogo1977** [comment]
thanks, sorry for late answer. I think it is my tracker. I use the tk20 (vjoy or kingneed) with protokoll tk103. This thing transmit something like 0.05399570000000001 this. And when i export it of mysql, it is ugly in excel. And why not for trackar too. I think i wait for protokoll update. Thanks a lot ThoGo

**Comment by tananaev** [comment]
Traccar converts all data into knots, that's why you see so many decimal digits. You should probably round them if you want to export data into excel.

**Comment by undee123** [comment]
I'm with the latest traccar server version, but I cannot find any configuration for changing miles to km/h.
Accuracy and distance are in km, only speed is in mph.

**Comment by tananaev** [comment]
You can configure it in user or server attributes.

**Comment by undee123** [comment]
I'm sorry, but I just can find these values to change in the configurations:

User:
- Phone
- Map Layer
- Latitude
- Longitude
- Zoom
- 12-hour-format
- Coordinates format

Server:
- Map Layer
- Bing Maps Key
- Custom Map
- Latitude
- Longitude
- Zoom
- 12-hour-format
- force settings
- Coordinates format

**Comment by tananaev** [comment]
Have you clicked on the "attributes" button?

**Comment by undee123** [comment]
No, but now I have, was a bit tricky to find. Thank you very much!
