### ISSUE TITLE
Update from 3.3 to 3.4 - db.changelog-master.xml not found

### ISSUE THREAD

**Issue by TwizzyDizzy** [tananaev/traccar#1764]
Hi Anton,

I just tried to upgrade from 3.3 to 3.4 server (Linux, amd64).

The wrapper complains, when trying migrate the database, that there is no ```/opt/traccar/data/db.changelog-master.xml```

    STATUS | wrapper  | 2016/03/04 12:05:01 | Launching a JVM...
    INFO   | jvm 1    | 2016/03/04 12:05:01 | WrapperManager: Initializing...
    INFO   | jvm 1    | 2016/03/04 12:05:02 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
    INFO   | jvm 1    | 2016/03/04 12:05:02 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
    INFO   | jvm 1    | 2016/03/04 12:05:02 | INFO 3/4/16 12:05 PM: liquibase: Clearing database change log checksums
    INFO   | jvm 1    | 2016/03/04 12:05:02 | INFO 3/4/16 12:05 PM: liquibase: Successfully acquired change log lock
    INFO   | jvm 1    | 2016/03/04 12:05:02 | INFO 3/4/16 12:05 PM: liquibase: Successfully released change log lock
    INFO   | jvm 1    | 2016/03/04 12:05:02 | INFO 3/4/16 12:05 PM: liquibase: Successfully acquired change log lock
    INFO   | jvm 1    | 2016/03/04 12:05:02 | INFO 3/4/16 12:05 PM: liquibase: Successfully released change log lock
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp: 
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error: Encountered an error running main:
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error: liquibase.exception.ChangeLogParseException: /opt/traccar/data/db.changelog-master.xml does not exist
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:100)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:17)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:227)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:202)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:192)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at liquibase.Liquibase.update(Liquibase.java:188)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:168)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.<init>(DataManager.java:65)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:121)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:29)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:606)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
    INFO   | jvm 1    | 2016/03/04 12:05:02 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
    STATUS | wrapper  | 2016/03/04 12:05:05 | <-- Wrapper Stopped

Searching for the file yields the following:

    root@hostname:/opt/traccar# find /opt/traccar -iname "*changelog*"
    /opt/traccar/data/changelog-master.xml
    /opt/traccar/data/changelog-3.3.xml

Renaming the file seems, for now, to do the trick:

    cd /opt/traccar/data
    mv changelog-master.xml db.changelog-master.xml

What is the correct name of the file in the future?

Cheers
Thomas

**Comment by tananaev** [comment]
Correct file name is `changelog-master.xml`. I guess you used old config after upgrade.

**Comment by TwizzyDizzy** [comment]
Indeed. Close - sorry for the fuzz. ```<entry key='database.changelog'>``` is the setting in traccar.xml
