### ISSUE TITLE
RethinkDB compatibility and integrity possibilities.

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#1769]
Hi anton, I've been working over a project that uses rethinkdb as database engine and I'm wondering if you maybe have a general point of view or appreciation about using this NoSQL kind databases to be used with traccar.
Do you think is reliable? do you think it can be used with traccar?
thanks

**Comment by tananaev** [comment]
I'm sure some NoSQL databases can be used, but it would require some code modifications.

**Comment by hackerunet** [comment]
ok, I can see there is a full database module or clases that handles SQL queries like, a query builder and a parser that retrieves connection details and make a connection with the engine, so is that where I have to recode??

**Comment by tananaev** [comment]
Yes, I guess the main place where you would have to make changes is `DataManager`.

**Comment by hackerunet** [comment]
Amazing .. thanks, I'll proceed and then maybe we can post the code.

**Comment by apaleja** [comment]
@hackerunet are you still working on it ? I am also interested in using NoSQL with traccar. I'd love to contribute.

**Comment by hackerunet** [comment]
Yeah but, not with rethinkdb, only mongodb which offers more stability.
I'll post a release candidate in few days.

**Comment by apaleja** [comment]
Thanks for reply. I will look forward for the release.
