### ISSUE TITLE
Monitoring client for Linux

### ISSUE THREAD

**Issue by hanselsen** [tananaev/traccar#1772]
Is there an easy way to have a mocking client installed on Linux?
I would like to use this client as a monitoring "device" that reports every problem when connecting to the Traccar server.
Using the Minitracker or OSMAnd protocol would be great.

**Comment by tananaev** [comment]
There is this Python script that generates fake locations:

https://github.com/tananaev/traccar/blob/master/tools/test-generator.py

**Comment by hanselsen** [comment]
Thanks I'll give that a go
