### ISSUE TITLE
Problem in Laipac Protocol

### ISSUE THREAD

**Issue by addonravi** [tananaev/traccar#1774]
HI Tananaev,
I am using Traccar Laipac Protocol.
I get the below data:
(1)     $AVRMC,80006030,173350,**p**,2302.0125,N,07230.6828,E,0.00,0.00,090316,0,3997,702,1,0,0*34
Q:      Whai is meaning of p in data data.
(2)  $AVRMC,80006030,080121,a,2301.9411,N,07232.0437,E,26.71,40.00,090316,6,3794,690,1,0,0*25
Q:     Whai is meaning of 6 (Type) in data.
Please help me.
Thanks

**Comment by tananaev** [comment]
You can find protocol documentation here:

https://www.traccar.org/protocols/

**Comment by addonravi** [comment]
I have alreday this document. but not define in document.

and your code not send responce when Type is 6. If type is 0 then only send responce.
Why??

**Comment by tananaev** [comment]
That's all the documentation that I have.

**Comment by addonravi** [comment]
Thanks for fast responce.

**Comment by tananaev** [comment]
The problem with "p" type is fixed. See #2423 for more details.

**Comment by vassyakin** [comment]
Thanks, I will test today

**Comment by vassyakin** [comment]
Anton, it works with Traccar 3.7, thanks! New tracker-server.jar is only for version 3.7?

В течение часа тестировал локально на ноутбуке на версии 3.7, все работает, спасибо! Будет ли https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0 работать на предыдущих версиях Траккар? Мы пока до сих пор на 3.2...

**Comment by tananaev** [comment]
Yes, it's only for 3.7.

**Comment by okjokj2** [comment]
I have liapac StarFinderLite
I configured it to send TCP data to port 5048 but the device doesn't appear as Online.

I captured the received data 
Here the received (80 byte) data packet
String:
$AVRMC,99999999,002553,A,1520.8990,N,04411.6959,E,0.00,,120617,0,,41,1,628,*18

Hex stream:
244156524d432c39393939393939392c3030323535332c412c313532302e383939302c4e2c30343431312e363935392c452c302e30302c2c3132303631372c302c2c34312c312c3632382c2a31380d0a



Here another received (61 byte)  data packet
String :
$AVRMC,99999999,003849,V,,N,,E,0.00,,120617,0,,41,1,186,*36

Hex stream:
244156524d432c39393939393939392c3030333834392c562c2c4e2c2c452c302e30302c2c3132303631372c302c2c34312c312c3138362c2a33360d0a

Please guide me what to do .

Best regards.

**Comment by tananaev** [comment]
@okjokj2, you should create a new issue instead of commenting on and old closed thread. Also, please provide protocol documentation for your device.

**Comment by addonravi** [comment]
This blow string says no GPS data you need to ignore otherwise get 
filled values


the blank value is in ",," has no value because of device has not 
getting proper gps signals thats y the reason that type of packets are comes

Here another received (61 byte) data packet
String :
$AVRMC,99999999,003849,V,,N,,E,0.00,,120617,0,,41,1,186,*36

-Ravi

**Comment by tananaev** [comment]
It might be a valid case and not a device issue, so it might need fixing on the server side.
