### ISSUE TITLE
device_id is always 0

### ISSUE THREAD

**Issue by ManishKaushik** [tananaev/traccar#1779]
Hi,
 I am integrating traccar with Opengts with MS SQL Server.
I am facing a problem that "device_id" variable is not correctly returning the unique id/IMSI. Due to this SQL query to insert event gets failed. I have tried with two different device types and result is same.

Please help on what I am missing here...

tracker-server log:
```
2016-03-13 19:36:41 DEBUG: [7E3150D4: 5001 < 106.201.110.91] HEX: 2424463133312c3836313037343032333038393634352c4141412c33352c32382e3530383139382c37372e3033313032382c3136303331333134303633372c562c302c33312c302c302c302c302c313130362c32333739322c3430347c31307c303036367c323132442c303030302c303030307c303030307c7c303235397c303030302c2a31410d0a
2016-03-13 19:36:41  WARN: Cannot insert the value NULL into column 'accountID', table 'gts.dbo.MSEventData'; column does not allow nulls. INSERT fails. - SQLServerException (... < QueryBuilder:433 < DataManager:306 < DefaultDataHandler:27 < ...)
2016-03-13 19:36:41  INFO: [7E3150D4] id: 0, time: 2016-03-13 19:36:37, lat: 28.50820, lon: 77.03103, speed: 0.0, course: 0.0
```

traccar.xml:
```
	<entry key='database.insertPosition'>

	DECLARE @accountID varchar(32) 
	DECLARE @deviceID varchar(32) 
	DECLARE @tijd bigint
	DECLARE @nu bigint

	
	set @tijd = (select dbo.unix_timestamp(CONVERT(VARCHAR(19),:time,120)));
	set @nu = (select dbo.unix_timestamp(CONVERT(VARCHAR(19),getdate(),120)));
	
	UPDATE MSDevice SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = @tijd, lastUpdateTime = @nu WHERE imeiNumber = :device_id;         
	SELECT @accountID = accountID,@deviceID=deviceID  FROM MSDevice WHERE imeiNumber = :device_id;
	INSERT INTO MSEventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address)
		VALUES (@accountID, @deviceID, @tijd, 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', @nu, :address);

	</entry>
```

**Comment by tananaev** [comment]
I guess there is some problem with `database.selectDevicesAll` query.

**Comment by ManishKaushik** [comment]
Thanks a ton. It was that.
I corrected that and all worked well.

Here is the configuration for Opengts MS SQL server integration:
SQL function:
----------------
CREATE FUNCTION [dbo].[UNIX_TIMESTAMP] (
 @ctimestamp DATETIME
 )
 RETURNS INT
 AS
 BEGIN
 DECLARE @return INT

SET @ctimestamp = DATEADD(HH,DATEDIFF(hh, GETDATE(),GETUTCDATE()),@ctimestamp);

SELECT @return = DATEDIFF(SECOND,{d '1970-01-01'}, @ctimestamp)

RETURN @return
 END
GO

traccar.xml
---------------
    
    <entry key='database.refreshDelay'>300</entry>

    
	<entry key='database.selectDevicesAll'>
        SELECT imeiNumber AS id, imeiNumber AS uniqueId FROM MSDevice WHERE imeiNumber &lt;&gt; '';
	</entry>
		
    <entry key='database.selectDevice'>
        SELECT imeiNumber AS id, imeiNumber AS imei from MSDevice;
    </entry>

    
	<entry key='database.insertPosition'>

		
	DECLARE @accountID varchar(32) 
	DECLARE @deviceID varchar(32) 
	DECLARE @tijd bigint
	DECLARE @nu bigint

	
	set @tijd = (select dbo.unix_timestamp(CONVERT(VARCHAR(19),:time,120)));
	set @nu = (select dbo.unix_timestamp(CONVERT(VARCHAR(19),getdate(),120)));
	
	UPDATE MSDevice SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = @tijd, lastUpdateTime = @nu WHERE imeiNumber = :device_id;         
	SELECT @accountID = accountID,@deviceID=deviceID  FROM MSDevice WHERE imeiNumber = :device_id;
	INSERT INTO MSEventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address)
		VALUES (@accountID, @deviceID, @tijd, 0, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', @nu, :address);
	
	</entry>
