### ISSUE TITLE
Some positions have NULL address

### ISSUE THREAD

**Issue by 4nonym0us** [tananaev/traccar#1781]
I'm running traccar server and I have only 2 devices, connected to it.

I've discovered that some of the positions don't have **Address** field.
After making a research I found out that there is approx. 41.63% positions (which equals 142 436 records in the DB) without an address.

I saw that you use Google Reverse Geocoder and It seems to work great and has a good reputation.
I tried geocoding the positions manually (I used following url: http://maps.googleapis.com/maps/api/geocode/json?latlng=%LAT%,%LNG%) and all of the positions, which I tried to manually test, were successfully handled by the API gateway.

I know that there is a request/day limit on Google services, but I'm running only 2 devices and It's impossible that I could reach that limit.

What's your opinion on this problem?

**Comment by tananaev** [comment]
What's the location report frequency on your devices?

There can be some network issue. Or maybe Google just limiting number of requests for some reason.

Traccar got banned by other reverse geocoding providers (e.g. Nominatim), so I won't be surprised if Google limiting the number of requests as well.

**Comment by 4nonym0us** [comment]
Here are the device settings:
1st device: 120*sec*+20*deg* *turns*
2nd device: 30*sec*+20*deg* *turns*
Here is the request with the frequency of locations for the last 25 days:

> ![image](https://cloud.githubusercontent.com/assets/2701409/13737134/99673b98-e9c3-11e5-948a-287e4fd130a0.png)

Here is the request without *WHERE [address] IS NULL* condition:

> ![image](https://cloud.githubusercontent.com/assets/2701409/13737152/be1370d8-e9c3-11e5-95fa-b08a920456c2.png)

It looks like Google is really limiting the API requests when ~2.3k req/day is reached?
If so, you should consider adding the **geocoder.key** param to the **GoogleReverseGeocoder.java** so everybody can set up their own key (in a case they need id).

**Comment by tananaev** [comment]
Key parameter would be useful only for premium plan users. Are you planning to use it? It should be fairly simple to implement.

Limiting number of requests per second would be more complicated.

**Comment by 4nonym0us** [comment]
Key parameter can be used by everybody who wants to use **pay-as-you-go billing** – It allows use up to 100k requests per day (and each 1k requests will cost $0.50). However, It's still a standard API Plan.
Premium plan allows to raise limit to 250k requests pay day (and concurrency limit to 50 requests per second).
According to this, **KEY** param is helpful not only to premium users and It would be really great of you could implement it.

I agree that implementing the handling of the concurrency limit scenario is quite hard. I think that the best way to do that is to create a background worker, that will have a fixed thread pool, which is used to execute reverse geocoding procedure. It's an important thing, which is needed for the positions integrity.

**Comment by tananaev** [comment]
I've added support for API key.

**Comment by 4nonym0us** [comment]
Thanks a lot!
