### ISSUE TITLE
how does traccar server identify device type / protocol

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1785]
just a simple question - how does traccar server identify the device protocol? Cos I have seen that for adding new devices, only the name and IMEI needs to be specified. How does it automatically take care of things which might be device / protocol specific in some cases?

**Comment by tananaev** [comment]
It doesn't. Each communication protocol uses different port:

https://www.traccar.org/devices/

**Comment by m-menon** [comment]
ok, i think i need to rephrase my question a bit...what I actually wanted to ask was this: when you add a new device, all you do is to prompt for name and IMEI number, and that's it. I was wondering that there might be protocols requiring extra fields or some other params. Just curious and also wanted to know your thoughts on that, if any

**Comment by tananaev** [comment]
Add devices send basic GPS information (coordinates, time, speed etc). If device sends some extra data, it's stored in `attributes` database column in JSON format.

**Comment by m-menon** [comment]
Thanks a lot for the clarifcation
