### ISSUE TITLE
Issues with DeviceTime and GT06 protocol

### ISSUE THREAD

**Issue by samm-git** [tananaev/traccar#1786]
I am using latest Traccar with GT06-based tracker. It works fine, but i found that when car is not moving device time is also not changing and reflect date in the past. When i was debugging communication i found that this is because of GT06 protocol: if car is not moving tracker sends only status packet (0x13) which does not contain time or location information. So parser is using `getLastLocation(position, null);` call to obtain data from the last location (0x12) packet. Device time also taken from it.
I think that it is more correct to fill device time with server time for such packets. Also i think that speed for such packets should be set to 0, because location is an old one. 

Please let me know if you think that i am correct, i can try to create the patch if needed.

**Comment by tananaev** [comment]
Device time is filled with current server time. See `getLastLocation` implementation.

As for speed, I don't agree. It would be misleading to include old location with wrong speed value.

**Comment by samm-git** [comment]
Thank you for reply. I am agree about speed, but device time is not filled correctly. See this dump from the live system:

```
surikat:~/h2/bin# java -cp /opt/traccar/lib/h2-1.4.191.jar org.h2.tools.Shell -url 'jdbc:h2:/opt/traccar/data/database;AUTO_SERVER=TRUE' -user sa -sql 'select id,devicetime,servertime from POSITIONS order by id desc limit 10;'
ID   | DEVICETIME            | SERVERTIME
1077 | 2016-03-15 08:45:10.0 | 2016-03-15 09:26:59.405
1076 | 2016-03-15 08:45:10.0 | 2016-03-15 09:24:03.281
1075 | 2016-03-15 08:45:10.0 | 2016-03-15 09:21:07.172
1074 | 2016-03-15 08:45:10.0 | 2016-03-15 09:18:11.154
1073 | 2016-03-15 08:45:10.0 | 2016-03-15 09:15:14.951
1072 | 2016-03-15 08:45:10.0 | 2016-03-15 09:12:18.789
1071 | 2016-03-15 08:45:10.0 | 2016-03-15 09:09:22.813
```

Please let me know if you need any other information.

**Comment by samm-git** [comment]
Btw, i found that in the traccar.xml

```xml
    <entry key='database.insertPosition'>
        INSERT INTO positions (deviceId, protocol, serverTime, deviceTime, fixTime, valid, latitude, longitude, altitude, speed, course, address, attributes)
        VALUES (:deviceId, :protocol, :now, :time, :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :attributes);
    </entry>
It seems that we are inserting `time` 2 times and in fact completely ignoring devicetime. Am i right?
```

**Comment by tananaev** [comment]
Good catch. Fixed the problem.

**Comment by samm-git** [comment]
Confirmed, thank you! 
```
ID   | DEVICETIME              | SERVERTIME              | FIXTIME
1105 | 2016-03-15 10:57:57.862 | 2016-03-15 10:57:57.943 | 2016-03-15 08:45:10.0
1104 | 2016-03-15 10:55:01.761 | 2016-03-15 10:55:02.027 | 2016-03-15 08:45:10.0
```

P.S. i will donate 15$ for the great software. Before i was using self-written perl daemon (for different tracker) and now, after tracker upgrade, found traccar and i really like it )
