### ISSUE TITLE
A simple example of api call

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1789]
I have just started experimenting with the API functionality. I managed to get some of them working but it would be fantastic if there were some simple examples on the following api calls. Just basic examples if possible would be of great help, Thanks for the wonderful work

API for 

1) Logging in / authentication
2) Check if a user exists
3) Add a user account
4) Check if a device exists
5) Add / attach a device to the user account
5) Get the device count of a particular user
7) Get a count of all devices
8) Get position information about a particular device, with start / end date range
9) Delete a device belonging to a user
10) Delete a user account

**Comment by tananaev** [comment]
The easiest way you can get some examples is use standard web interface and look at the requests in browser developer console.

**Comment by m-menon** [comment]
cool. Thanks :+1:
