### ISSUE TITLE
SSL Certificate generation - Server type

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1790]
Wanted to run the API on https and about to send in a request for certificate generation. But I have seen a dropdown box that asks for the web server type - Apache-ModSSL, Apache-SSL,, nginx, Tomcat etc. Which one do I choose? Traccar runs its own web server i guess

**Comment by tananaev** [comment]
Please carefully read all the information on the page:

https://www.traccar.org/secure-connection/

**Comment by m-menon** [comment]
lol...thanks a lot. I asked the question before I read the answer to my previous question
