### ISSUE TITLE
Ubunto https/proxy/ssl config to Centos 6.5

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1791]
Can someone help me adapt the below for use on Centos 6.5? As these are configuration related stuff, I am a little wary of experimenting as I have other stuff on the machine
This [page](https://www.traccar.org/secure-connection/) speaks of running [traccar on SSL](https://www.traccar.org/secure-connection/). I need to config for centos 6.5

Basically how would this look for use on Centos 6.5? I guess some modules will need to be installed differently or may not be needed at all?

```
sudo apt-get install apache2
sudo a2enmod ssl
sudo a2enmod proxy_http
sudo a2enmod proxy_wstunnel
sudo service apache2 restart
```

And then the vhost config - how to adapt this to Centos 6.5?

```
<IfModule mod_ssl.c>
        <VirtualHost _default_:443>

                ServerName demo.traccar.org
                ServerAdmin webmaster@localhost

                DocumentRoot /var/www/html

                ProxyPass /api/socket ws://localhost:8082/api/socket
                ProxyPassReverse /api/socket ws://localhost:8082/api/socket

                ProxyPass / http://localhost:8082/
                ProxyPassReverse / http://localhost:8082/

                SSLEngine on
                SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
                SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

        </VirtualHost>
</IfModule>
```

And then this bit

```
sudo a2ensite traccar
sudo service apache2 restart
```

Thanks a ton

**Comment by tananaev** [comment]
On CentOS instead of `apt-get` you should be using `yum` package manager.

You need to adjust server name and certificate files in the config. Also, I'm not sure if Let’s Encrypt works well on CentOS.

**Comment by m-menon** [comment]
I did this to install Apache on Centos 6.5

```
sudo yum update
sudo yum install httpd
yum install mod_ssl openssl
```

But for 
```
proxy_http
proxy_wstunnel
```

For the Let's Encrypt thats ok cos I have a paid ssl certificate that I can use...probably just need to drop in the pem file and the cert itself in the correct directories

Thanks a lot. You've been very helpful

**Comment by tananaev** [comment]
Both `proxy_http` and `proxy_wstunnel` are standard Apache modules. I don't think you need to install them separately.

**Comment by m-menon** [comment]
So basically I just need to find the Centos commands for enabling the following modules I guess?

```
sudo a2enmod ssl
sudo a2enmod proxy_http
sudo a2enmod proxy_wstunnel
```

**Comment by tananaev** [comment]
Yes, it should be fine.

**Comment by m-menon** [comment]
Thanks a lot. I think for now I will test using Ubuntu and at a later stage will think of CentOS
