### ISSUE TITLE
My app consume 800mb data in 1 month

### ISSUE THREAD

**Issue by amet123** [tananaev/traccar#1798]
Hi

I integrated traccar in my android app with 1 min update location
My qurstion : is it possible to consume data due to location update  data in my app

**Comment by m-menon** [comment]
Perhaps Tananaev could answer this better with some numbers but I don't think at 1 minute intervals it wouldn't consume so much of data / bandwidth. For example I have couple of TK103 GPS trackers (which of course send more information than the stock traccar android app) set at 30 seconds and the data transfer is so minimal. You can perhaps do this - clear up the data usage for the apps in the android settings. Then monitor for an hour, or even a day and see at what rate the data is being transferred by the app. It should help you to zero / optimize the settings for the app. Perhaps you could install some sniffer or something, on the phone itself, or even on your LAN if you are on WiFi...it could give you a good idea of the data transfer behind the scenes. If you could channel it through a proxy, then I guess you can easily monitor what's going on too. Just my few thoughts and ideas

**Comment by tananaev** [comment]
Do you mean you integrated Traccar Client code?

If everything works correctly, it shouldn't consume more than 50MB per month with 1 minute interval.

The problem could be if your server doesn't accept messages, then Traccar Client logic is to retry, so potentially it could use a lot of traffic for re-tries.

**Comment by amet123** [comment]
Thanks for quick reply , i integrated with odoo-mobile  framwork

**Comment by tananaev** [comment]
What did you integrate from Traccar project?

**Comment by amet123** [comment]
Realtime Location only

**Comment by tananaev** [comment]
Which part of which project have you integrated?
