### ISSUE TITLE
No Server set for org.traccar.web.WebServer

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1800]
Just curious of the line I saw in the log file
```
[WrapperSimpleAppMain] WARN org.eclipse.jetty.server.handler.AbstractHandler - No Server set for org.traccar.web.WebServer$1@2eb2ce92
```

Java version I am using:
```
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```

Btw which version of java would you think is best to use with Traccar on Ubuntu LTS 14.04? 7 / 8 / 9?

Thank you so much,
M&M

**Comment by tananaev** [comment]
I've fixed it, but there is no need to update. You can safely ignore the warning.

**Comment by m-menon** [comment]
cool thanks :+1:
