### ISSUE TITLE
DB optimizations

### ISSUE THREAD

**Issue by 4nonym0us** [tananaev/traccar#1804]
Hello @tananaev,
To start with, I'd like to say thanks for sharing traccar to the community and supporting it all the time. It'd great to see that project is under continuing development and is constantly improving.
<hr>
As far as I can see, the DB isn't properly optimized and this may cause troubles in a huge data sets (every table have only simple PK 'Id' and that's all).
I'm not a DBA (as well as you, I guess) so I think that It might be a good idea to create an issue when everyone can share their thoughts and suggest DB-related improvements.

### Table: dbo.Positions.

Let's research the common operation: we usually want to get a set of **Positions**, filtered by date and deviceId (It's pretty common request, isn't it?):
```
SELECT *     -- or even  'SELECT TOP @pageCount *
  FROM [positions]
  WHERE [fixTime] >= @p0
    AND [fixTime] <= @p1
    AND [deviceId] = @p2
  ORDER BY [fixTime]
```
According to this usual request, we might need to use **fixTime** (and probably the **deviceId** as well) at least as a **non-clustered index**. The clustered index relates to the way data is physically sorted on disk, which means it's a good all-round choice for most situations, so should we should consider using **fixTime** even as as a **clustered index** (as the benefits are simple: the request won't require the dbms to scan the full table and the 'ORDER BY operation' will be instant as data will be physically stored as a page, sorted by **fixTime**.
However, there is a cons: making clustered index requires a column to be unique and we cannot ever be 100% sure that the **all positions** will have unique **fixTime** so It looks like that using **non-clustered** index is a s better idea so far.
<hr>
What's your opinion on the DB optimization overall and on the my proposal?

**Comment by tananaev** [comment]
I appreciate feedback, but your main point about having no indexes is incorrect. There is an index on `positions` table. It includes two fields (`deviceId` and `fixTime`), so it's exactly for the query that you provided as an example.

As for the making it clustered, it's not possible because `fixTime` is not unique.

I am for DB optimizations, so if you have any other optimization ideas feel free to share.

**Comment by 4nonym0us** [comment]
It's quite odd because I have only one index key on PK_POSITIONS index.
Here is the request: `EXEC sys.sp_helpindex @objname = N'positions'`
and the response:
```
index_name		index_description					index_keys
PK_POSITIONS	clustered, unique, primary key		id
```
By the way, I'm using SQL Server, hosted on Azure. Might it be the root of the issue?

**Comment by tananaev** [comment]
Thanks for feedback.
