### ISSUE TITLE
OSMAND Data not showing valid from iOS or Android.  Reverse Geocoding not working.

### ISSUE THREAD

**Issue by netsound** [tananaev/traccar#1805]
Hello I have been trying to trouble shoot why my TK103 and gpsgate client's have been getting geocoding without issue and my iOS and Android clients do not have geocode information.   Looking at the mysql data getting stored for the osmand clients (iOS/Android)  Valid = 0 were as for the gpsgate or tk103 clients valid = 1.  Am I correct in thinking that geocodes will only be added to the database if the server has a valid = 1 result for data received?   And if so why isn't the packet getting flagged as valid from ios/android clients.

**Comment by tananaev** [comment]
What version of the server are you using?

**Comment by netsound** [comment]
Looks like 3.3 December 2015's release..... I see you released 3.4 here 17 days ago.. Let me upgrade to that...

**Comment by tananaev** [comment]
There was an issue in old version. Should be fixed in 3.4.

**Comment by netsound** [comment]
Is there an upgrade process or is it just remove old.. install new?

**Comment by tananaev** [comment]
Remove old one and install new one. Make sure to backup database if you have any valuable data there.

**Comment by netsound** [comment]
Well that was it...  3.4 showing valid for the ios/androids and putting geolocation address's in the database...  Reading the rest of the commits done on 3.3 to 3.4 now..  Thanks.. 
https://github.com/tananaev/traccar/compare/v3.4...master

Looks like my scripts that run against the mysql are working too.. so thanks again for all the time you put into this..
