### ISSUE TITLE
gt06 timezone to utc error

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1806]
hi,

Is this configuration setting still relevant to latest 3.4 version?

`<entry key=’gt06.timezone’>0</entry>`

Because I wanted to get the gt06 device to use UTC offset +00:00

But once I added `<entry key=’gt06.timezone’>0</entry>` to the config file traccar refuses to start. I see the following error in the log

```
INFO   | jvm 1    | 2016/03/20 07:07:24 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/03/20 07:07:24 | WrapperSimpleApp Error: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
```

Any pointers?

Thanks
M&M

**Comment by tananaev** [comment]
It is still relevant, but you are using wrong quoting symbol. It should be regular single quote `'` instead of the one you are using `’`.

**Comment by m-menon** [comment]
oh strange cos I copied it from one of the discussions on this topic :-) Thanks

**Comment by tananaev** [comment]
Your text editor might be messing with quoting symbols. Very common problem.

**Comment by m-menon** [comment]
okay thanks :-)
