### ISSUE TITLE
DataManager thread safety

### ISSUE THREAD

**Issue by sura2k** [tananaev/traccar#1808]
When I was altering the code I found that `DataManager `is getting accessed as a singleton object via `Context `class. But however `DataManager `has few shared fields such as `devicesByUniqueId `. By looking at the `DataManager:getDeviceByUniqueId` for example, it might lead to some issues. 
For example if one thread doing the `devicesByUniqueId.clear();`, other thread might throw a _device not found_ exception.

Appreciate if you can clarify this.

**Comment by tananaev** [comment]
I have added read and write locks for devices and groups.

**Comment by sura2k** [comment]
In case if you move to Java 8 permanently, take a look at [StampedLock](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/locks/StampedLock.html). 
It fits **where** `read count >>>>>> write count`.

**Comment by tananaev** [comment]
Thanks for suggestion. I plan to migrate to Java 8 eventually. It will make sense to use `StampedLock` then.
