### ISSUE TITLE
protocol enable

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1809]
Does this configuration / key have to do with older version of traccar cos in the latest version I just see the port numbers and there is no seperate key to enable / disable. So i think if there is an entry for port, that is automatically considered enabled and if there is no port entry then that protocol is disabled? Thanks

**Comment by tananaev** [comment]
Correct, if there is a `xxx.port` parameter, it means `xxx` protocol is enabled.

**Comment by m-menon** [comment]
Thank you so much for the wonderful work and such fast response to the questions & queries :+1:
