### ISSUE TITLE
Map not displayed after refreshing page

### ISSUE THREAD

**Issue by mannouman** [tananaev/traccar#1815]
Hi, 

First of all, thanks a lot for this app !!!

I have an issue (in local(debian) and in your demo website : when i refresh page, the map is not displayed anymore (i try to deconnect-reconnect, clean cache...)

Thanks

**Comment by mannouman** [comment]
It was because i set map to BingMap, it seems it does not work ?

**Comment by tananaev** [comment]
You need to set API key to be able to use Bing Maps.

**Comment by tananaev** [comment]
I missed your first comment. If you are using demo server, only OSM is available.

**Comment by mannouman** [comment]
Ok, thanks dude !

**Comment by joelmanx** [comment]
already have a API key of bing, in wich file add this key?

**Comment by tananaev** [comment]
You add it in server settings, not file.

**Comment by joelmanx** [comment]
thanks,I did it and worked successfully
