### ISSUE TITLE
Traccar Log 

### ISSUE THREAD

**Issue by leontino** [tananaev/traccar#1820]
second time it happens, and stop traccar and increases the memory and CPU.

http://imgur.com/iZKxTH0

**Comment by tananaev** [comment]
Most likely it means that you have reached open connection limit for Traccar process.

There are two things you might want to do:

1. Increase the limit for the process (not that it's OS limit, not Traccar)

2. Set `resetDelay` parameter for protocol(s) that you use

**Comment by leontino** [comment]
How I do it ?

**Comment by tananaev** [comment]
1. For Linux connection limit see following page (or just Google for it):

http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

2. Reset delay can be set in Traccar config:

https://www.traccar.org/configuration-file/

**Comment by leontino** [comment]
Do you can show-me a example for put configuration-file ?

**Comment by tananaev** [comment]
Here is an example:
```
<entry key="xexun.resetDelay">100</entry>
```
