### ISSUE TITLE
multiple web interfaces

### ISSUE THREAD

**Issue by sickmind** [tananaev/traccar#1821]
Hi,
Can I somehow run multiple web interfaces, for example one running on the server where traccar is installed and another one on a different machine (and network) but still using the same database?

Cheers.

**Comment by tananaev** [comment]
I guess it's possible with some modifications to the web code. You would need to use Traccar API though, not database directly.

**Comment by sickmind** [comment]
Hi Anton,
What is causing this limitation (not not being able to use the DB directly), mysql shouldn't have problems with multiple connections. 
Cheers.

**Comment by tananaev** [comment]
Some data is cached in memory. There would be problem with synchronizing that data.

Live location and status updates won't work at all.

**Comment by sickmind** [comment]
I see, thanks!
What about having multiple servers writing in the same DB but only one with enabled web interface, does it implies similar limitation? Not that I need such design, just curious about the possibilities :)

**Comment by tananaev** [comment]
In that case the problem will be with live location updates. What is the reason for multiple servers?

**Comment by sickmind** [comment]
Both scalability and high availability. For example putting HAproxy or nginx in front of few traccar instances. DB scalability and high availability is pretty easy nowadays (maria db in gallera cluster for exmaple).

**Comment by tananaev** [comment]
Yeah, but you need a reason for all that first. Traccar can handle hundreds of thousands of devices. Do you need more than that?

**Comment by sickmind** [comment]
That's correct for scalability - it is unlikely that someone will need to scale up that much. But for high availability reasons it's always better to be able to run on multiple severs, so there will be no downtime during single server maintenance or failure. It is not that important for the web interface to stay up all the time, but for the server part it is always better to have some high availability solution.
Of course it can be configured to run in a cluster so the downtime will be limited to minutes (if not less), but configuring and maintaining a cluster is a far more complicated than running multiple instances behind a load balancer. The applications are getting more and more advanced in the recent years, if you look back 5 or 10 years ago the only high availability solution in 99% of the cases was a cluster. But nowadays more and more application support scalability solving a lot of issues. Take mariadb for example, now we have Gallera with active-active replication, back in the mysql days the only option was active-standby. The same with many other (especially web) applications.

In my case I use traccar for personal use with less than 5 devices, so I don't really need neither of both. I was just wondering how far traccar can go or can it run in a cloud environment :)

**Comment by tananaev** [comment]
Back-end that communicates with devices is pretty flexible. You can run it on any number of servers in parallel and write to the same database.

The code that serves API would be the issue because that's where the caching is.

**Comment by sickmind** [comment]
Thanks for the explanation.
