### ISSUE TITLE
Identifier validation

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1831]
hi,

Say I were to be using the Traccar API to add a device, I guess the only validation that I'd perhaps need to do on the Identifier is that it is either an IMEI number or atleast a number with 12 digits? Am i right in assuming that? Thanks

**Comment by m-menon** [comment]
wow then perhaps the best I can do is to keep the minimum length to a few characters? say 3-5. Thanks

**Comment by tananaev** [comment]
Technically nothing stops user from having ids less than 3 characters. Is there any reason you want to implement this validation?

**Comment by m-menon** [comment]
the primary reason is prevention of junk / useless / orphan data in the tables :-)

**Comment by tananaev** [comment]
Maybe you can filter punctuation and special characters, but again technically for some protocols those would be valid ids.
