### ISSUE TITLE
Traccar demo server configuration

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1837]
hi,

Is it possible to get some idea of the hardware configuration of the [demo servers](https://www.traccar.org/demo-server/) used by traccar at the moment with an approximate idea of the number of devices/user accounts currently on the server? This will greatly help in choosing hardware for bigger deployments. Thanks

**Comment by tananaev** [comment]
### Main demo server

4 Cores, 7 GB memory

- 15k registered users
- 9.5k registered devices

### Second demo server

2 Cores, 4 GB memory

- 1.5k registered users
- 1k registered devices

Number of active users and device is unknown.

**Comment by m-menon** [comment]
Fantastic. Thanks :+1:
