### ISSUE TITLE
User deletion - devices table

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1840]
hi,

When I delete a user, is there another query to delete the users devices from the device table? This is because I didn't see any 'on delete cascade' or other constraint at db level. I am using MySQL. Sorry I couldn't test that out because I am trying my hands at getting this to work with MongoDB

I can see these 3 queries in the config file

```
    <entry key='database.unlinkDevice'>
        DELETE FROM user_device WHERE userId = :userId AND deviceId = :deviceId;
    </entry>

    <entry key='database.deleteDevice'>
        DELETE FROM devices WHERE id = :id;
    </entry>

    <entry key='database.deleteUser'>
        DELETE FROM users WHERE id = :id;
    </entry>
```

Prorbably this is executed in some order. But also one more thing - there doesn't seem to be anything to remove the data from the postions data. I think it could be optimal to remove the positions data too because once the device / user is deleted, the data for that device cannot be accessed anyway from the interface.

Thanks M.M

**Comment by m-menon** [comment]
I think I can probably write a trigger or something - to delete all those records in positions table for which there is no record found in `user_device` - or do you think there could be a better way? Thanks for the super quick responses so far :+1:

**Comment by tananaev** [comment]
There is `ON DELETE CASCADE` in `user_device` table. Which means only links between devices and user are removed, not devices themselves. It's because devices can be shared or later re-assigned to another user.

**Comment by m-menon** [comment]
Alright. Does that mean that once a user is deleted, the server will still continue to accept the data from the tracker? Thanks

**Comment by tananaev** [comment]
Yes.

**Comment by m-menon** [comment]
alright, I'll probably write a trigger to remove the device from the table as well as from the positions table because I don't really have a need to re-assign a device to a different user. Thanks once again

**Comment by m-menon** [comment]
hi,

Do you think that the mysql table "positions" has the on delete cascade option set? If yes then would it not show up in the table description

```
mysql> describe user_device;
+----------+---------+------+-----+---------+-------+
| Field    | Type    | Null | Key | Default | Extra |
+----------+---------+------+-----+---------+-------+
| userid   | int(11) | NO   | MUL | NULL    |       |
| deviceid | int(11) | NO   | MUL | NULL    |       |
+----------+---------+------+-----+---------+-------+
2 rows in set (0.00 sec)
```

Thanks,
M.M

**Comment by m-menon** [comment]
Sorry false alarm, I used the wrong query. I can see the on delete cascade here

```
| user_device | CREATE TABLE "user_device" (
  "userid" int(11) NOT NULL,
  "deviceid" int(11) NOT NULL,
  KEY "fk_user_device_deviceid" ("deviceid"),
  KEY "user_device_user_id" ("userid"),
  CONSTRAINT "fk_user_device_deviceid" FOREIGN KEY ("deviceid") REFERENCES "devices" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_user_device_userid" FOREIGN KEY ("userid") REFERENCES "users" ("id") ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
```

**Comment by tyepez** [comment]
Hi, please help me, I dont have CONSTRAINT in my tables, How can I get all "alter table with CONSTRAINTS" for apply to my tables?

**Comment by tananaev** [comment]
@tyepez, please don't comment on closed or unrelated threads. If you have a question create a topic on forum and explain your issue.
