### ISSUE TITLE
Traccar server does not start in windows.

### ISSUE THREAD

**Issue by zizango123** [tananaev/traccar#1845]
tracar server doesnt start  it just paused after successfully release of change log lock.. no further processing is either done or is not visible on the log file.
The server is not started when checked.

**Comment by tananaev** [comment]
Can I see the logs?

**Comment by zizango123** [comment]
STATUS | wrapper  | 2016/04/02 12:31:04 | --> Wrapper Started as Service
STATUS | wrapper  | 2016/04/02 12:31:04 | Java Service Wrapper Community Edition 64-bit 3.5.27
STATUS | wrapper  | 2016/04/02 12:31:04 |   Copyright (C) 1999-2015 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/04/02 12:31:04 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/04/02 12:31:04 | 
STATUS | wrapper  | 2016/04/02 12:31:05 | Launching a JVM...
INFO   | jvm 1    | 2016/04/02 12:31:19 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/04/02 12:31:37 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/04/02 12:31:39 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/04/02 12:31:45 | INFO 4/2/16 12:31 PM: liquibase: Successfully acquired change log lock
INFO   | jvm 1    | 2016/04/02 12:31:50 | INFO 4/2/16 12:31 PM: liquibase: Reading from gps.DATABASECHANGELOG
INFO   | jvm 1    | 2016/04/02 12:31:50 | INFO 4/2/16 12:31 PM: liquibase: Successfully released change log lock

**Comment by tananaev** [comment]
What version of Traccar are you using?

**Comment by zizango123** [comment]
3.3

**Comment by tananaev** [comment]
Please update to the latest version and see if it still happens.

**Comment by zizango123** [comment]
ok will do

**Comment by zizango123** [comment]
Updated to the latest version and traccar now starts but no data is received from the devices. It used to receive earlier before the problem starts to occur.

**Comment by tananaev** [comment]
Please follow steps here:

https://www.traccar.org/troubleshooting/
