### ISSUE TITLE
Timestamp in GPRMC vs {fixTime} in forward.url

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1847]
hi,

I see the following gprmc statement in the forward.url
$GPRMC,052714.000,A,0119.7256,N,10352.6082,E,0.00,0.00,030416

but then I also pass the {fixTime} in the forward url then the value received for the same sentence is
fixTime=1459661234000 (actually the fixTime value seems strange)

Shouldn't the fixTime be the same as that received in the GPRMC? Or does it convert that time into Server time zone?

Cheers,
M.M

**Comment by tananaev** [comment]
It should be. Why do you think it's different? Please provide actual URL with both parameters at the same time.

**Comment by m-menon** [comment]
The values above are actual values taken from a single/same url. Anyway here's another complete forward url - as seen on the receiving end

`/insertposdata?id=359710034734114&code=0x0000&gprmc=$GPRMC,064614.000,A,0119.7256,N,10352.6082,E,0.00,0.00,030416,,*04&address=11+Tannery+Rd%2C+Singapore%2C+SG&latitude=1.32876&longitude=103.87680333333333&fixTime=1459665974000&statusCode=0xF841`

Thanks,
M.M

**Comment by tananaev** [comment]
Everything works as intended. Note that `fixTime` is in unix timestamp format.

**Comment by m-menon** [comment]
oic...thanks :+1:
