### ISSUE TITLE
Synology DS415play installation guide request

### ISSUE THREAD

**Issue by yeekhoon** [tananaev/traccar#1856]
Hi 1sthandy.
Good day. I need some your guidance and steps how to install the traccar into synology. there is limited resource I can find on how traccar can be installed into synology. Despite several attempts make and without much success.

Here is what i had gone through the steps to install ipkg with all these files coreutils, textutils, and gettext 

On the ipkg installation here are the steps i have gone through

Step 1 – to confirm what type of processor it has
my DS415play return :
Model : 54
model name : Intel (R) Atom(TM) CPU CE5335 @1.60GHz
Model : 54
model name : Intel (R) Atom(TM) CPU CE5335 @1.60GHz
Model : 54
model name : Intel (R) Atom(TM) CPU CE5335 @1.60GHz
Model : 54
model name : Intel (R) Atom(TM) CPU CE5335 @1.60GHz

Step 2- get the ipkg install
wget http://ipkg.nslu2-linux.org/feeds/optware/syno-i686/cross/unstable/syno-i686-bootstrap_1.2-7_i686.xsh

step 3 – make it executable
chmod +x syno-i686-bootstrap_1.2-7_i686.xsh

step 4 – Run the script
sh syno-i686-bootstrap_1.2-7_i686.xsh

step 5 – remove script
rm syno-i686-bootstrap_1.2-7_i686.xsh

Step 6 – Update the package list
ipkg update

step 7 – add repo: https://www.cphub.net/ into package center
packager center > setting > package source

step 8 – install mariDB

Step 9 – install traccar

encounter error during installation. Here is the error message :

Fail to install “traccar”. gettext is not installed. Please install gettext via CLI or if available, via package center.

can you guide me along… or do you have any installation guide on how to install the all these files coreutils, textutils, and gettext  into synology DS415play 

thank you.
best regards
YK

**Comment by tananaev** [comment]
@1sthandy

**Comment by 1sthandy** [comment]
you also have to install the packages:
ipkg install gettext
ipkg install coreutils
ipkg install textutils

do you have a symlink to /opt ?

the installer look for /opt/bin/gettext

You can install with the cphub repo also the “Easy Bootstrap Installer” this creates a symlink to /opt

if you dont want to use ssh for install, you can also install the "iPKGui" than you can install coreutils, textutils, and gettext

If you are on DSM 6.0 you have to use [this file](https://sourceforge.net/projects/traccar-synology/files/traccar3.4-006-noarch.spk/download)

Greetings 1stHandy

**Comment by yeekhoon** [comment]
thank you for responding to my thread, 1stHandy. 
I have successfully installed traccar.. while i click to start the traccar, i hit by another issue, here is the error message "This site can’t be reached, 101.127.117.55 took too long to respond. ERR_CONNECTION_TIMED_OUT"

i checked the url and it is show as http://101.127.117.55:55000/

so, i have no clue of what is going on despite i read up from https://www.traccar.org/synology/

could you give me some pointer...

thank you for your help.

**Comment by 1sthandy** [comment]
i need your Logfiles from: /volumeX/@appstore/traccar/logs/

X = maybe 1 or 2

**Comment by yeekhoon** [comment]
Hi 1sthandy,
thank you for response. I don't know why not i couldn't use putty to ssh NAS despite i have enabled the ssh service in terminal & snmp>terminal . The error message i got "Network error : connection time out"

prior to the installation ipkgui, I can access via ssh, but now, after the installation of ipkgui, i couldn't do it.... i have been look out for solution from the online resource, it seem that most of the solution provided with is to enable the ssh in NAS.

can you help me 1sthandy before i can take out the logs file from the volumeX
or any otherway that i can get it...

thanks you and have a great day ahead.
best regards
YK

**Comment by yeekhoon** [comment]
Hi 1sthandy,
strangely, I could access by using username "admin", once I login, I couldn't access any hidden files or directory... if I use "root", the message I received is "access denied". 

how shall I configure my user right so that I can access under root username...

thank you.

**Comment by yeekhoon** [comment]
Hi 1sthandy,
I have no idea of what I have done, as a result, I able to access the root directory
here is the logfiles

/volume1/@appstore/traccar/logs/tracker-server.log

2016-04-10 22:01:13  INFO: Operating system name: Linux version: 3.2.40 architecture: i386
2016-04-10 22:01:13  INFO: Java runtime name: Java HotSpot(TM) Client VM vendor: Oracle Corporation version: 24.79-b02
2016-04-10 22:01:13  INFO: Memory limit heap: 170mb non-heap: 96mb
2016-04-10 22:01:13  INFO: Character encoding: UTF-8 charset: UTF-8
2016-04-10 22:01:13  INFO: Version: 3.4-SNAPSHOT
2016-04-10 22:01:25  INFO: Starting server...


/volume1/@appstore/traccar/logs/wrapper.log.20160410

INFO   | jvm 1    | 2016/04/10 22:01:23 | INFO 4/10/16 10:01 PM: liquibase: /volume1/@appstore/traccar/data/changelog-mast                                   er.xml: /volume1/@appstore/traccar/data/changelog-3.3.xml::changelog-3.3::author: New row inserted into users
INFO   | jvm 1    | 2016/04/10 22:01:23 | INFO 4/10/16 10:01 PM: liquibase: /volume1/@appstore/traccar/data/changelog-mast                                   er.xml: /volume1/@appstore/traccar/data/changelog-3.3.xml::changelog-3.3::author: ChangeSet /volume1/@appstore/traccar/dat                                   a/changelog-3.3.xml::changelog-3.3::author ran successfully in 329ms
INFO   | jvm 1    | 2016/04/10 22:01:23 | INFO 4/10/16 10:01 PM: liquibase: Successfully released change log lock
INFO   | jvm 1    | 2016/04/10 22:01:23 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSourc                                   e - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 3                                   0, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, c                                   heckoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultC                                   onnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge0ys9g4rbhx129o1y|11c239c, debugUnreturnedConnec                                   tionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocatio                                   n -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> fals                                   e, identityToken -> 1hge0ys9g4rbhx129o1y|11c239c, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:m                                   ysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=latin1&sessionVar                                   iables=sql_mode=ANSI_QUOTES, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessCon                                   nections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads                                    -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, property                                   Cycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false                                   , unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2016/04/10 22:01:24 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @12                                   602ms
INFO   | jvm 1    | 2016/04/10 22:01:25 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.15.v2016                                   0210
INFO   | jvm 1    | 2016/04/10 22:01:29 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - St                                   arted o.e.j.s.ServletContextHandler@84b81a{/api,null,AVAILABLE}
INFO   | jvm 1    | 2016/04/10 22:01:29 | [WrapperSimpleAppMain] WARN org.eclipse.jetty.server.handler.AbstractHandler - N                                   o Server set for org.traccar.web.WebServer$1@152e370
INFO   | jvm 1    | 2016/04/10 22:01:29 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started S                                   erverConnector@12a78f6{HTTP/1.1}{0.0.0.0:55000}
INFO   | jvm 1    | 2016/04/10 22:01:29 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @17954ms

**Comment by yeekhoon** [comment]
Hi 1sthandy,
I manage to get the traccar log files out finally and zipped it as attached...... whooshh....

[traccar-logs.zip](https://github.com/tananaev/traccar/files/213402/traccar-logs.zip)

thank you and have a great day ahead..

**Comment by 1sthandy** [comment]
@yeekhoon it looks like all is fine `INFO   | jvm 1    | 2016/04/10 22:01:29 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@12a78f6{HTTP/1.1}{0.0.0.0:55000}
INFO   | jvm 1    | 2016/04/10 22:01:29 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @17954ms`

can you access by internal IP?
You have to check the access from internet to synology.

**Comment by yeekhoon** [comment]
Thank you for your pointer 1sthandy, I manage to resolve the access from external by doing port forwarding from my router to synology.
here is the port forwarding configuration
external : 101.127.117.55       public port 8888
internal : 192.168.0.101          private port 55000

I have installed Traccar Client (IOS) and try to simulate the gps location, however, it does not work.. I did a port check from https://www.traccar.org/port-check/ , it shown port is open.. pls see attached picture

![port-check](https://cloud.githubusercontent.com/assets/18328964/14496173/e5ebcc4a-01c4-11e6-8aeb-c64df43b3640.JPG)


here is the setting I have set in the Traccar Client

Traccar Client (IOS)
Device identifier : 642999
server address : 101.127.117.55
Server Port : 8888
Frequency:60
----------------------------------------------
Traccar Client (IOS) status : 
21:18 - Location Update
21:18 - Send failed
21:24 - Location Update
21:29 - Location Update
21:30 - Send failed
21:31 - Send failed
---------------------------------------------

Traccar server, I have added the device..  see attached picture

![traccar](https://cloud.githubusercontent.com/assets/18328964/14495812/9d9a3720-01c3-11e6-8624-f5429e47e465.jpg)


What have I still not done right to get these work.. thanks

thank you 1stHandy..

**Comment by 1sthandy** [comment]
the port 55000 is only the web ui

for android or iphone client you have to forward 55055 also to the diskstation and you have the use this port in your client config.

other Devices are:
[Device and Portlist](https://www.traccar.org/devices/)

Greetings 1stHandy

**Comment by yeekhoon** [comment]
Thank you 1stHandy... finally i manage to get it work.. it work like a charm.. thank you....
i see that there are lot of improvement or new feature could be added into traccar, hence, i wish to contribute more in coding, i have been pretty long time never touch on java coding.. and willing to use my spare time to my hand dirty again... could you give me some pointers on which tool you are using to do coding? eclipse?

**Comment by tananaev** [comment]
I would recommend IntelliJ IDEA or NetBeans:

https://www.traccar.org/build/

**Comment by yeekhoon** [comment]
thank you 1sthandy and tananaev, and have a great day ahead...
