### ISSUE TITLE
Server side use for Nautical application

### ISSUE THREAD

**Issue by Hatchorder** [tananaev/traccar#1857]
Hi,

We use this app to track a phone on a ship at Sea. Is it possible to have a number of new options on the server side:

1) Ability to select speed in Knots as well as KMH and MPH (I have been informed that the default is knots if you do not select MPH or KMH)

2) Ability to see Lat and Long in Degrees Minutes and seconds (At moment it is displayed in Decimal Degrees (DD) maybe have an option to display in Degrees Decimal Minutes (DDM), and Degrees Minutes and Seconds (DMS)

3) Ability to display distance in Nautical Miles as well as Miles and Kilometers.

Thank you.

Ian

**Comment by tananaev** [comment]
All 3 options are implemented.
