### ISSUE TITLE
Using traccar as a backend.

### ISSUE THREAD

**Issue by zizango123** [tananaev/traccar#1863]
I intend to use traccar as a backend for gathering the datas sent by the devices and using my own applications to display the datas.But whenever i change web.enable to false the server doesnt start. Also i need to insert the datas into a custom table not provided by traccar as default. It worked fine with previous versions but after update it no longer works even after reverting to old versions.

**Comment by tananaev** [comment]
It should continue working as before. What is the error? Check logs.

**Comment by zizango123** [comment]
It works now.
