### ISSUE TITLE
/fake-login 404 (Not found)

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1869]
hi,

Any pointers as to what could be causing this error that I see in the console every time I login?

![fake-login](https://cloud.githubusercontent.com/assets/10776430/14517224/b157f8fe-023d-11e6-82da-2ee25a8b974d.jpg)

Thanks,
M&M

**Comment by tananaev** [comment]
It's not an error. It's required to allow browsers to save username and password.

**Comment by m-menon** [comment]
cool thanks. So if I were to be using a rest client to do a login I would be basically doing a HTTP POST to /api/session with the following parameters (I have just posted what I think are some important parameters/settings)

```
CURLOPT_URL => "https://mygpstrackerdomain.com/api/session",
CURLOPT_CUSTOMREQUEST => "POST",
CURLOPT_POSTFIELDS => "email=example75%40gmail.com&password=1234&=",
CURLOPT_HTTPHEADER => array(
	"cache-control: no-cache",
	"content-type: application/x-www-form-urlencoded",
)

```

So this would return me a session token that I would use in subsequent calls? Sori if this sound too much of a newbie question but I haven't dealt with REST APIs before. Thanks a ton

Cheers,
M&M

**Comment by tananaev** [comment]
REST API actually shouldn't have sessions, but Traccar does, so it's not fully REST.

Anyway, the call doesn't return you a session. It just authenticates current HTTP session. After that, you can do other calls with the same cookie header.

**Comment by m-menon** [comment]
Great thanks. Wonderful support as ever. Now the system is only experimental but once it goes live I'd me more than glad to donate to the project :+1:

**Comment by m-menon** [comment]
hi, you mentioned "same cookie header". I can see these headers after execution

```
Access-Control-Allow-Credentials →true
Access-Control-Allow-Headers →origin, content-type, accept, authorization
Access-Control-Allow-Methods →GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin →*
Connection →Keep-Alive
Content-Length →208
Content-Type →application/json
Date →Thu, 14 Apr 2016 06:25:27 GMT
Keep-Alive →timeout=5, max=100
Server →Jetty(9.2.15.v20160210)
Strict-Transport-Security →max-age=31536000; includeSubDomains
```

So I guess as long as I keep sending subsequent request without closing the browser, it should be authenticated and return the results?

Thanks,
M&M

**Comment by tananaev** [comment]
I don't see any cookie in your response. What Traccar version are you using?

**Comment by m-menon** [comment]
It's this one
Linux 64 bit	[traccar-linux-64-3.4.zip](https://github.com/tananaev/traccar/releases/download/v3.4/traccar-linux-64-3.4.zip)	04-Mar-2016

Thanks,
M.M

**Comment by tananaev** [comment]
You probably already have cookie set up for the session.

**Comment by m-menon** [comment]
alright thanks... :+1:
