### ISSUE TITLE
Country Code instead of Street name

### ISSUE THREAD

**Issue by zizango123** [tananaev/traccar#1871]
Hi,
I have successfully integrated traccar with gisgraphy as a geocoder in my private server but while reverse geocoding, only the country code is being retrieved instead of the whole address or the street name. I know for a fact that while reverse geocoding my gisgraphy server returns all the relevant informations as given below although it is in json format
```
{"numFound":1,"QTime":16,"result":[{"lng":93.96277599615655,"lat":24.82406963531293,"streetName":"NH202","city":"Imphal","state":"Imphal East","countryCode":"IN","geocodingLevel":"STREET","distance":835.5903652266896}]}
```
But only the country code i.e IN is being retrieved and inserted into the database by traccar.

**Comment by tananaev** [comment]
This is the result I get:
```
{"numFound":1,"QTime":35,"result":[{"name":"NH202","distance":3.66640648541338,"gid":145829197,"openstreetmapId":258107994,"streetType":"TRUNK","oneWay":false,"countryCode":"IN","length":3572.97670498365,"lat":24.824120188522553,"lng":93.96278092022945,"isIn":"Imphal","isInAdm":"State of Manipur"}]}
```

**Comment by tananaev** [comment]
What server are you using?

**Comment by zizango123** [comment]
I am using gisgraphy server version 4 and the above posted result is the result from http request. I dont know how to post the result from traccar request.

**Comment by zizango123** [comment]
can't i get the street name from the result.

**Comment by tananaev** [comment]
What is the URL that you used?

**Comment by zizango123** [comment]
i used private server as http://192.168.1.5:8080/reversegeocoding/ .
It is not accessible from the outside network just from within the same network.
Also if u want an example of how it works in the private server it is the same as in this URL although it uses http method instead of being called by Traccar. The URL is  http://services.gisgraphy.com/reversegeocoding/search?format=json&lat=24.81317333333333&lng=93.96510222222223

**Comment by tananaev** [comment]
In Traccar I use "http://services.gisgraphy.com/street/streetsearch", not the one you provided. I guess result format is different.

**Comment by zizango123** [comment]
Anyway to use the one that i provided. The result is more accurate and detailed in the one that i provided for use in reverse geocoding.

**Comment by zizango123** [comment]
can you help me to use the url that i provided instead of the streetsearch.

**Comment by zizango123** [comment]
streetsearch is not at all accurate so it is a better if we use reverse geocoding as i have provided in the url. It gives much better and accurate results.

**Comment by tananaev** [comment]
Done. I have changed the format.

**Comment by zizango123** [comment]
So i have to compile the traccar server from source code using the commit provided??

**Comment by tananaev** [comment]
You can either wait for new release or build a version from source code if you want.

**Comment by zizango123** [comment]
Thanks i will try to build from source for now until a new release is available.
