### ISSUE TITLE
Unable to plot movement path after upgrading from 3.4 to 3.5

### ISSUE THREAD

**Issue by strasharo** [tananaev/traccar#1881]
Not sure if I did something wrong, but after the upgrade from 3.4 to 3.5 today traccar is unable to plot the path for any movement of the device. Was working fine in 3.4. When I search in the reports for a specific timeframe I get a lot of results, but nothing is plotted on the map. I only see a blue circle in the last reported position:
http://prntscr.com/ateden

**Comment by tananaev** [comment]
What browser are you using? Try Chrome.

**Comment by strasharo** [comment]
Tried both Chrome and FF. The specific shot was taken in Chrome.

**Comment by tananaev** [comment]
Are you sure you are using default version without any modifications? Please try clearing browser cache.

If nothing helps, check browser developer console to see if there are any errors or warnings there.

**Comment by renaudallard** [comment]
I am having the exact same issue.
And also, following a device doesn't work anymore either. There is no more arrow with the direction, just a blue circle like you and when you clock on the target icon, the device moves but not the map.

**Comment by renaudallard** [comment]
The browser console shows errors:
TypeError: h.getStyle(...) is null
.updateLatest()
 app.min.js:83
.fire()
 ext-all.js:22
.dispatch()
 ext-all.js:22
.monitor/a.doFireEvent()
 ext-all.js:22
.fireEventArgs()
 ext-all.js:22
.fireEvent()
 ext-all.js:22
.onCollectionItemChange()
 ext-all.js:22
.notify()
 ext-all.js:22
.itemChanged()
 ext-all.js:22
.afterChange()
 ext-all.js:22
.afterEdit()
 ext-all.js:22
.privates.callJoined()
 ext-all.js:22
.set()
 ext-all.js:22
.asyncUpdate/a.onmessage()
 app.min.js:98
xmlService()
 sm.base.min.js:1
tpzService()
 sm.base.min.js:1
tpzRefresh()
 sm.base.min.js:1
<anonymous>

**Comment by renaudallard** [comment]
What is interesting is that when I use debug.html, I see the arrows instead of the blue circles and everything is working fine.

**Comment by tananaev** [comment]
Please download installer again. I have fixed the issue.

**Comment by renaudallard** [comment]
-<script src="//cdnjs.cloudflare.com/ajax/libs/ol3/3.15.1/ol.js"></script>
+<script src="//cdnjs.cloudflare.com/ajax/libs/ol3/3.15.1/ol-debug.js"></script>

You have enabled some debugging in release?

**Comment by tananaev** [comment]
Yes, it always used to be debug version of the library.

**Comment by zonavip** [comment]
donde encuentro las mejoras de la version 3.5? gracias

**Comment by strasharo** [comment]
Re-downloaded the installer for 3.5, fixed the issue for me.
Thanks a lot again, Anton. :)
