### ISSUE TITLE
About upgrading traccar.

### ISSUE THREAD

**Issue by zizango123** [tananaev/traccar#1883]
I have a previous installation of traccar that is working perfectly but i want to upgrade to the latest version. My installation is in windows. What i want to know is whether i can just copy the jar file from another installation of the latest version to the previous installation and restart for it to work. Its very inconvenient to uninstall it all again and then reinstall it.

**Comment by tananaev** [comment]
Do you have custom configuration?

**Comment by zizango123** [comment]
yes is do.

**Comment by tananaev** [comment]
Then you need to apply your changes again. I don't see any other way.

**Comment by zizango123** [comment]
So i have to reinstall again.

**Comment by tananaev** [comment]
Well, you don't have to. I think it's just easier.

Alternatively you can manually update jar file, libraries, web files, config file and changelog files.

**Comment by zizango123** [comment]
ok thanks.
