### ISSUE TITLE
Parameter Error

### ISSUE THREAD

**Issue by zizango123** [tananaev/traccar#1886]
The `:time` parameter is no longer giving any value. It just gives  warning of sqlexception no value specified for parameter

**Comment by tananaev** [comment]
You should use either `:fixTime` or `:deviceTime` now.

**Comment by zizango123** [comment]
Are these in unix timestamp or do i need to convert them.

**Comment by tananaev** [comment]
Those are date type in Java. Same as before.

**Comment by zizango123** [comment]
Thanks. :fixTime Works fine.
