### ISSUE TITLE
arrowstyle.js:1 Uncaught ReferenceError: goog is not defined

### ISSUE THREAD

**Issue by gaborgsomogyi** [tananaev/traccar#1887]
When I'm trying to load the release.html file from chrome browser (Version 49.0.2623.112 m) then the following error comes all the time:

arrowstyle.js:1 Uncaught ReferenceError: goog is not defined

The interesting part is that debug.html works flawlessly.
Because of this issue the arrow can't be seen on the map.

**Comment by tananaev** [comment]
There was an issue with original release. Please re-download installer.

**Comment by gaborgsomogyi** [comment]
Cool. I've just seen the commit :)
