### ISSUE TITLE
New Tracker

### ISSUE THREAD

**Issue by leontino** [tananaev/traccar#1888]
Hello, I have a TK305 I don't know what's the port to him.

##,imei:359710048******,A;

when I decoded the hex code, show me this! I have put on port 5023!

Help-me please!

**Comment by tananaev** [comment]
Correct port for your device is 5001. Also, please read following page:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by leontino** [comment]
Thank you dear!
