### ISSUE TITLE
Relying on cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#1892]
Hi Anton,

Is there a specific reason why you take js and css stuff out of cdnjs.cloudflare.com instead of pulling them directly from the web folder of traccar?
This has some kind of implications, like it could potentially make you vulnerable if scripts hosted at cloudflare become targetted by crackers. Also, if you are accessing your traccar server from some networks, cloudflare might block you.

**Comment by tananaev** [comment]
There are many benefits including caching, faster downloading, reducing load on the server, reducing download size. Also it makes it easier for me to develop and distribute Traccar server.

There is always a chance that CloudFlare might get hacked, but I think it's pretty low.

I didn't quite get the last point. Why would CloudFlare block you?

**Comment by renaudallard** [comment]
I agree that the chance of cloudflare being hacked is quite low.
Cloudflare is known to block some networks or IP ranges. In general, this is not a big issue as you have a captcha, but, here, the captcha just won't work.

**Comment by tananaev** [comment]
Do you have any proof links of blocked resources by CloudFlare? I guess they might block access to some websites to prevent DDoS, but not JavaScript CND scripts.

**Comment by renaudallard** [comment]
I tried from a blocked IP and indeed js and css CDN are not blocked.
That might still be an issue behind a corporate firewall which doesn't allow internet access tough.

**Comment by tananaev** [comment]
If there is no internet access, you won't be able to get map tiles. But I see your point. Anyway, if someone really needs it, he can just copy all the libraries into the web folder and update links. It's really easy.

**Comment by FX7** [comment]
Hi,

i tried to copy all the ressources from cloudeflare. But its not that easy as you think. There are many many other files (eg pictures) which also have to be downloaded.

And while I'm writing this, i can't access my traccar server because some of the cloudflare resources seems to be down.

So if you can tell me an easy way to download everythink please tell me ...

**Comment by tananaev** [comment]
You can download libraries from their official websites.

**Comment by 2SI3NX** [comment]
@tananaev  Is it possible to include all the scripts thats needed without relying on Cloudflare? How difficult would that be? Some detailed instructions would be appreciated.   
traccar is supposed to be open source isnt it?  Cloudflare is far from being open source. The whole traccar project pertaining to privacy really has no point if you mix it with services that expose you or that you are vulnerable to attack, in this case you might as well include google and facebook.

**Comment by tananaev** [comment]
You can always copy all the files to Traccar web folder and serve locally. The only change you need to do after that is in load.js file.

**Comment by renaudallard** [comment]
There seem to be 2 other files:
```
web/simple/index.html:<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.20.1/ol.css" type="text/css">
web/simple/index.html:<script src="https://cdnjs.cloudflare.com/ajax/libs/ol3/3.20.1/ol.js" type="text/javascript"></script>

```

**Comment by tananaev** [comment]
That's only for simple version of the web app.

**Comment by 2SI3NX** [comment]
@tananaev Can you post which files we need exactly to get this fully working without cloudflare please?  A link from cloudflare?

**Comment by tananaev** [comment]
In the load.js file you can find a list of libraries they you need to download. Then you search on the internet for those libraries.

**Comment by renaudallard** [comment]
The tricky one is the one which depends on the language:
    addScriptFile('//cdnjs.cloudflare.com/ajax/libs/extjs/' + extjsVersion + '/classic/locale/locale-' + locale.languages[locale.language].code + '.js');

**Comment by tananaev** [comment]
You should probably just get the whole extjs library.
