### ISSUE TITLE
Group for a group?

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1897]
![image](https://cloud.githubusercontent.com/assets/10776430/14746862/4407e2ac-08e4-11e6-84a8-949f19125942.png)

Was trying to create a group and then I see a dropdown box asking for a group, for a group. I didn't quite get that. Probably a group name and description would do?

Cheers,
M&M

**Comment by tananaev** [comment]
It's an optional parameter. You can have an hierarchy of groups.

**Comment by m-menon** [comment]
cool thanks
