### ISSUE TITLE
GT03A traccar server 3.4 not saving power/battery status

### ISSUE THREAD

**Issue by neerajbw1** [tananaev/traccar#1904]
I am using traccar 3.4 server and having concox device GT03A protocol GT06, in position table attributes field battery/power status is not stored, any help on this would be very helpfull.

**Comment by tananaev** [comment]
Please don't duplicate your question. I answered on the forum:

https://www.traccar.org/forums/topic/gt03a-battery-power-details-is-not-stored-in-attributes-traccar-version-3-4/
