### ISSUE TITLE
Question on KEYs in Event.java

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#1918]
Is there a document that defines the purpose for each of the KEYS in Event.java?  I am writing a new protocol decoder and want to match data to the correct keys.  I believe these are the correct mappings:

  1) KEY_BATTERY = voltage of the vehicle battery
  2) KEY_POWER = voltage of the tracker device battery
  3) KEY_ALARM = flag for an SOS button or similar manual alert mechanism

Thanks.

- jss

**Comment by tananaev** [comment]
There is no document, but I think most keys are pretty obvious.

1) KEY_BATTERY - device battery
2) KEY_POWER - external power supply for the device (usually car battery)
3) Correct

**Comment by jon-stumpf** [comment]
What are the units of measurement for KEY_BATTERY and KEY_POWER?  Are they both Volts?

- jss

**Comment by tananaev** [comment]
There is no standard for that because most protocol documentation don't specify units. So for now I just store original value.

**Comment by jon-stumpf** [comment]
So, all external attributes/info are "raw" values and the units will vary protocol to protocol.

Are the position fields all normalized - specifically:

- times in UTC,
- speed in knots, 
- altitude in feet,
- course in degrees

- jss

**Comment by tananaev** [comment]
Yes, most attributes are raw values.

Time, speed and course are normalized. Altitude is not, but I think in most cases it's meters.
