### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1926]
hi,

Just wanted to know how traccar handles this: From what I observe the GPS Position data will not be posted to the positions table unless the device is added prior to receiving the data from the gps tracker. So my question is - upon receiving data from a GPS tracker, does traccar do a look up each and every time to see if the device exists in the device table? Or does it use some kinda caching or something? 
But then that brings up another question - when I add a new device I don't need to restart traccar service. How does traccar then keep track of newly added devices? 

Thanks,
M.M

**Comment by tananaev** [comment]
There is a cache, but if device is missing from there, Traccar syncs the cache with tha database table.

**Comment by m-menon** [comment]
okay. But if I add a new device using the API, the record is just getting posted to the database. So how does traccar server application know that a new device has been added and that it should query the Db to refresh the data? Sorry just curious how it's done

**Comment by tananaev** [comment]
Your statement is incorrect. If you add a device via API, Traccar updates the cache.

**Comment by m-menon** [comment]
oic....thanks
