### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by dschense** [tananaev/traccar#1940]
I have a little question:

I am running two machines --> Server A and Server B both behind Fritzbox router.
Server A: Nginx with Domain example.com and open Port 443 (192.168.178.201)
Server B: Traccar with Webinterface on Port 8082 (192.168.178.202)

Server A is connected to Internet.
Server B is on the same network as Server B but ports are not open over Fritzbox

Now when i call example.com i get redirected to https://example.com:443
Nginx with example.com is used as reverse proxy and links https://example.com to Ip of Server B with Port 8082 --> 192.168.178.202

With this I get the webinterface of traccar with https:// running without problems.

Now my problem is:

I want to use Android device to sent GPS data to the Server A and the Date gets redirected to Server B to be written to MySQL Database also running on Server B.
Android Device is connecting over Port 5055.

My Problem is: How to do such a Port forwarding or redirection over IpTables or something else to get the GPS data to the Traccar Server.

**Comment by tananaev** [comment]
I think you should be able to do port forwarding on the router.

**Comment by dschense** [comment]
yes, this would be possible. but i want the traffic to port 5055 running on Server A with the configured Domain and then pass this through the local network to Server B running traccar and Database.

**Comment by tananaev** [comment]
I'm not an expert in iptables, but I'm sure it's possible to achieve what you want.

**Comment by dschense** [comment]
This is what i have tryed. 192.168.178.1 is my router 192.168.178.202 is the server Traccar is running on and the iptables are configuered on the nginx Server with ip 192.168.178.201

```
iptables -t nat -A PREROUTING -p tcp -d 192.168.178.1 --dport 5055 -j DNAT --to 192.168.178.202:5055
iptables -t nat -A POSTROUTING -p tcp -d 192.168.178.202 --dport 5055 -j SNAT --to-source 192.168.178.1
```

**Comment by tananaev** [comment]
I guess it's better to ask about iptables on some Linux forum.

**Comment by wolfbgn** [comment]
Open on Fritzbox port 5055 - 5055 and point to 192.168.178.202.
Unless you have some firewall on server do not mess with iptables.
