### ISSUE TITLE
I have a problem with SQL SERVER 2014 and Trigger in positions

### ISSUE THREAD

**Issue by vipien** [tananaev/traccar#1946]
Hello, first of all thank you very much for everything.

I'm having a problem when I enable a trigger that believes in the positions table, the trigger simply inserted into another table the event that sends a tk103, but I see an error in the server log file

The trigger is so.
 ```
USE [traccar]
GO
/****** Object:  Trigger [dbo].[AddEvent]   Script Date: 14/05/2016 17:23:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER TRIGGER  [dbo].[AddEvent]  ON [dbo].[positions] 
FOR   INSERT
AS

DECLARE @atributos NVARCHAR(max)
DECLARE @evento NVARCHAR(128)

SELECT	@atributos = Inserted.attributes
FROM INSERTED

SELECT @evento = StringValue FROM parseJSON(@atributos) WHERE name = 'alarm'

INSERT INTO listevents (eventnew) VALUES (@evento)

```

The error the next.

```
2016-05-14 20:49:57 DEBUG: [2B0AB039: 5001 < 186.167.249.239] HEX: 696d65693a3335333435313034313932363731362c747261636b65722c313630353134323034392c30343132363537393432352c462c3030343934382e3030302c412c303833372e303335312c4e2c30373031352e343331362c572c302e30352c3b
2016-05-14 20:49:57  WARN: The statement must be executed before any results can be obtained. - SQLServerException (... < QueryBuilder:433 < DataManager:457 < DefaultDataHandler:27 < ...)
2016-05-14 20:49:57  INFO: [2B0AB039] id: 353451041926716, time: 2016-05-14 20:49:48, lat: 8.61725, lon: -70.25719, speed: 0.1, course: 0.0

```

In any case the position is inserted in both tables but would like to know because it happens and avoid it

I'm sure the problem is to insert that modify the trigger to select another table and print to debug and no exception occurs.

**Comment by tananaev** [comment]
You don't need a trigger. You can just modify the query in the config.

**Comment by vipien** [comment]
I just do not want to stop inserting positions in the table, and use a SQL function to extract the trigger event that was json parameters. What would be the recommendation to keep doing the same thing but without the error?

Thanks again.

**Comment by tananaev** [comment]
I suspect the error is about returning generated position id, but I'm not sure why it's happening.

**Comment by vipien** [comment]
I did it through a store procedure and the result is the same, still throwing error.

It happens because there is an insert, without this related.

**Comment by tananaev** [comment]
It's because Traccar expects to get generated position id, but because you have several inserts it gets confused.

**Comment by vipien** [comment]
Thank you for responding effectively it seems, add a new query to config and change the code to insert into both tables. I have another question but I will create a new thread because it has nothing to do with this and I have not gotten any answer in another topic here.

Thanks.
