### ISSUE TITLE
Teltonika FM1125 – CODEC_12 - Send Commands from Traccar

### ISSUE THREAD

**Issue by javisan** [tananaev/traccar#1948]
Is it possible to send commands back to device using codec_12 with Traccar web page Command function?

The response message structure is nearly the same:

<pre>
| 0x00000000 | Data Size |  0x0C  | Command quantity |  0x05  | Command size | Command | Command quantity |   CRC   |
|   4 Bytes  |  4 Bytes  | 1 Byte |       1 Byte     | 1 Byte |   4 Bytes    | X Bytes |      1 Byte      | 4 Bytes |
</pre>
It can be considered as an arbitrary text.
It is a command that the serial device connected to Teltonika FM1125 can understand.

**Comment by tananaev** [comment]
Teltonika commands are implemented.

**Comment by javisan** [comment]
Dear Anton,
First of all, thanks for your hard work as always.

I've compiled the new code and I've updated test server but I'm still don't see the option to send custom commands in the web page. What I'm doing wrong?

**Comment by tananaev** [comment]
Is device connected? Does it show as green?

**Comment by javisan** [comment]
Yes, it is connected and shown as green in the web page with position updated.

**Comment by tananaev** [comment]
Is 5th button in the toolbar enabled? That's the one to send commands.

**Comment by javisan** [comment]
That's the problem. I only see Add, Edit, Remove and Command buttons on the left. Follow and Settings on the right toolbar. I'm using the last GIThub version "...NetBeansProjects\traccar\web"

**Comment by javisan** [comment]
app.min.js was the problem. Now I can see the new buttons!
I've make a new installation of Traccar_3.6 and I have used this file. How can we generate the app.min.js in every rebuild at NetBeans?

**Comment by tananaev** [comment]
I would recommend to use debug version:
```
<entry key='web.debug'>true</entry>
```

It uses original JavaScript file, so you don't need to generate anything.

**Comment by javisan** [comment]
Everything perfect, working like a charm!
Thanks you very much for your help.
