### ISSUE TITLE
Handle results of command execution (Wondex)

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#1949]
Hello

Devices with Wondex protocol reply on command not in a similar way.
They start from "$OK:..." or "$ERR:.." and there is no GPS coordinates.
It's not a big deal to extend protocol decoder to store such answers in (for examle) KEY_STATUS or KEY_EVENT (or even add something like "command-result") and traccar adds last position and store such answer like position.

It is OK if device is not moving and not sending a lot of points. But most likely I'll miss the answer in a flow of positions.

Is it only way to catch such answers via SQL and extend web-interface to monitor them?

That is better: use KEY_STATUS, KEY_EVENT or invent new one like KEY_COMMANDRESULT = "command-result" ?

Or may be I thing in a wrong way?

**Comment by tananaev** [comment]
That's the only way to handle it at the moment. I guess you can use "result" key to store the data.

I'm actually trying to think of a way to better handle result as a part of the command request, but can't think of any good universal solution at the moment.

**Comment by Abyss777** [comment]
On the one hand "handle result as a part of the command request" is conveniently, but on the other hand it is asynchronous. My devices answer after 20-30 seconds on some commands. 

Frankly, I don't like an idea to store such things in positions.

May be now is good point to start implementing new abstraction like "Device event"
It will prepare base to future development of notifications (We will notify about what? About events)

Visually it can be like panel with device event history (updating every N seconds) and Push notifications to browser and even push to mobile "Traccar manager"

There can be events like: command results, alarms, overspeed, start/stop moving, enter/exit geofence and others.

On logical way it can be like event handler "onPositionWrite" that analyzes position according device settings (if speed is more than speed limit it generate event etc.)
The second part is notification process, that pull not sent events from database and send it via email, push etc.

**Comment by Abyss777** [comment]
I thought about it more and decided that store the result of the command in the "position" is not such a bad idea. Anyway, most of the "events of devices" will be connected with the "position", and why not store the result of the command is there not to do an extra field in the database for a single case.

**Comment by tananaev** [comment]
That's what I thought to do for now as well. I made some comments on your pull request.

**Comment by Abyss777** [comment]
Resolved long ago
