### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1958]
hi,

Just wanted to check if there is a timeout interval for the session. I am logging in using the API and just wondering how long before it times out so that I can post the credentials again. Or does the session stay till the browser is closed? Cheers . M.M

**Comment by tananaev** [comment]
Traccar uses Jetty library for HTTP server including session management. I'm not sure what's the default behaviour. I assume that there is some reasonable finite timeout value.

**Comment by m-menon** [comment]
Alright thanks :+1:
