### ISSUE TITLE
GT06 decodeStatus function

### ISSUE THREAD

**Issue by gbvaz** [tananaev/traccar#1962]
Hi!

I've been working on some of the status values such as ignition and power. The ignition seems to be working fine, I do get different values, which tells me if it is on or off. But when it comes to the power information, I always get full battery, no matter what the real status of the battery is. I've tested unplugging the battery from the car and leaving it off for hours, and no sign of change. 

So, I've starting digging up the code. More specifically, the decodeStatus function from the Gt06ProtocolDecoder class. There, on line 162 (master), I've noticed that the param for the KEY_POWER is "buf.readUnsignedByte()", which is the same as KEY_GSM and KEY_STATUS, the latter being the flags variable which has the same value at end.

My question is: is this correct? Shouldn't it be passing a value like on line 161 BitUtil.check(flags, 1), changing the param "flags" in each case with different values?

What can you tell me about all that? I'm sorry if I misinterpreted something here, I'm just trying to understand if it's something wrong with the code or with my devices.

Thanks!

**Comment by tananaev** [comment]
I don't quite understand the question. Ignition is a flag (1 bit). Power is a numerical value that is stored as full byte. Everything looks correct to me.

**Comment by gbvaz** [comment]
Let me try explaining this another way.

For example, I've decoded the hex code: 

`78781f1210051310340dc702233e7204b760d40438ee02d4170083002add002210970d0a`

This is code I got from my Traccar log, and it was send by one of my devices.

The Status info starts at the byte 32 and ends at the byte 34, as follows: 

`221097`

22 is the device information content, and we need to convert to binary, as follows:

`00100010`

Breaking it down, from right to left:

```
0 // 0 not fortified / 1 fortified 
1 // 0 low ACC / 1 high ACC
0 // 0 not charged / 1 charged ??????????
0 // 000 normal / 001 vibration alarm / 011 low-power alarm / 100 sos
0
1
0 // 0 gps has not located / 1 gps has located
0 // 0 petrol/electricity on / 1 petrol/electricity off
```

As you can se the charging flag bit is set to 0, as it should, since I've detached the battery from the car. But this information is being ignored on traccar, as it is always is set to full on the database:

`"power":6`

What am I missing here? Is this really the bit traccar checks?

Can you explain me what's is going on this method, and how do you get different values from the same method buf.readUnsignedByte()?

```
    private void decodeStatus(Position position, ChannelBuffer buf) {

        position.set(Event.KEY_ALARM, true);

        int flags = buf.readUnsignedByte();

        position.set(Event.KEY_IGNITION, BitUtil.check(flags, 1));
        position.set(Event.KEY_STATUS, flags);
        position.set(Event.KEY_POWER, buf.readUnsignedByte());
        position.set(Event.KEY_GSM, buf.readUnsignedByte());
    }
```

Hope this helps!
Thanks!

**Comment by tananaev** [comment]
Second byte in status block is voltage. That's what you get in the "power" field. It has nothing to do with device information bitmask.
