### ISSUE TITLE
Use API key with google geocoder

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1966]
Is it possible to use an API key with Google Geocoder at the moment? Thanks

**Comment by tananaev** [comment]
Yes, it is possible.

**Comment by m-menon** [comment]
okay thanks. How do I pass the API key? Thanks

**Comment by tananaev** [comment]
Through `geocoder.key` config parameter.

**Comment by m-menon** [comment]
okie thanks :+1:

**Comment by m-menon** [comment]
I tried creating a server key in Google API console and tried a few different combinations, traccar doesn't get the address. I have added the geocoder.key in traccar config file. Also just to be sure that I have enabled the correct API, here's the list of APIs that I see in Google API manager. Some such stuff from Google is pretty crazy and their UI really sucks bigtime :)

will you be able to suggest where I could be wrong? For now I have enabled the geolocation, geocoding and javascript map APIs from Google. The key I have already put in the config file

```
Google Maps APIs

Google Maps Android API
Google Maps SDK for iOS
Google Maps JavaScript API
Google Places API for Android
Google Places API for iOS
Google Maps Roads API
Google Static Maps API
Google Street View Image API
Google Maps Embed API
Google Places API Web Service
Google Maps Geocoding API
Google Maps Directions API
Google Maps Distance Matrix API
Google Maps Geolocation API
Google Maps Elevation API
Google Maps Time Zone API
```

Thanks a ton. M.M

**Comment by tananaev** [comment]
Wait, what version of Traccar are you using? It's only available in the latest one.

**Comment by m-menon** [comment]
hi, I am using v 3.5 ... release date 17 Apr 2016

**Comment by tananaev** [comment]
Try to build a JAR file from the latest source code. It might fix the problem.

**Comment by m-menon** [comment]
oops my experience with java is almost nil. Is there anything else that I could check to narrow in on the cause? Thanks. M.M

**Comment by tananaev** [comment]
Here is a new build to try:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

**Comment by m-menon** [comment]
Amazing, that works!!! :100:  So kind of you to sort this out so fast. Cheers - M.M

**Comment by shubhamalive** [comment]
Hello, i am new to this.
I can see google maps on my local machine but on accessing my server from external IP, google maps vanished.
After reading i find out its because i have to enter google maps key, i have generated API code, but cant understand where to enter and how to? can you guide me wit the same ? 
I also found a .jar file shared above, but cant understand how to use it ? 
![screenshot_4](https://cloud.githubusercontent.com/assets/20866586/17451310/6df097b6-5b83-11e6-8aaf-ecd821f5f02d.png)

**Comment by tananaev** [comment]
@shubhamalive, are you talking about actual maps or reverse geocoder?

**Comment by shubhamalive** [comment]
@tananaev I am using actual maps. Geocoder i saw from some above posts.

**Comment by tananaev** [comment]
How are you using Google Maps with Traccar? It doesn't support it.

**Comment by shubhamalive** [comment]
@tananaev i Have used this > http://traccar.litvak.su/installation.html to change traccar Web UI, i got google maps and many more feature with it. Features list > http://traccar.litvak.su/features/

**Comment by tananaev** [comment]
That's not an official Traccar project. You should ask the author.
