### ISSUE TITLE
Button Panic

### ISSUE THREAD

**Issue by andrecordeiro** [tananaev/traccar#1968]
Hy guys,

I would like to leave the Service Running Off, and when you press the POWER button for 3 consecutive times, even with SREEN_OFF , the service is running on. It would be a panic button. It's possible?

Best Regards.

**Comment by tananaev** [comment]
Are you talking about Traccar Client app?

**Comment by andrecordeiro** [comment]
exactly , the client application is android or ios . it is possible? Best regards

Date: Sun, 22 May 2016 22:50:00 -0700

**Comment by tananaev** [comment]
Here is the issue tracker for Traccar Client for Android:

https://github.com/tananaev/traccar-client-android/issues

**Comment by andrecordeiro** [comment]
Tks!!!
