### ISSUE TITLE
Linux Installition

### ISSUE THREAD

**Issue by kedarnathjimage** [tananaev/traccar#1971]
how to install traccar on godaddy Virtual private server.
 Any input on this will be highly appreciated. Thanks

**Comment by tananaev** [comment]
Like on any other server. Download installer and check readme for instructions.

**Comment by joerango** [comment]
The readme file refers to the website but the documentation page is currently down. Is it anywhere on github?

**Comment by tananaev** [comment]
@joerango, website should be working now.
