### ISSUE TITLE
DS008 Shenzhen Defenstar Technology

### ISSUE THREAD

**Issue by marchantm** [tananaev/traccar#1982]
Hi, someone can help me finding the port for this device?

Thanks & Regards

**Comment by tananaev** [comment]
Please read following two pages:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/
https://www.traccar.org/identify-protocol/

**Comment by marchantm** [comment]
Thanks, i found the protocol V680 but not working :(

**Comment by tananaev** [comment]
Can I see server logs?

**Comment by marchantm** [comment]
Hi, the server log is blank nothing added. When is said that to the vendor they answer me all the time "if you don't added our protocol to your server you never be able to read the device".

Thanks for keep helping us.

**Comment by m-menon** [comment]
@marchantm, First set up the device to send the data to your server. This is usually done by sending an SMS command (device-specific, pls refer to the device manual for that). Once this is done, check the log files in the log folder. You will be able to see data coming from the device information, in hex. Use the links above to identify the protocol. Add the device identifier in traccar through device add menu option, and then you will be able to see the data in your traccar web UI. There are 2 log files, one of which logs all the data that is being sent from the gps trackers. The other log file is mainly for use by traccar itself - like server messages, status, errors etc.

**Comment by marchantm** [comment]
Yes i tried all of that. I sent you a email. Can you check? 

thanks again

**Comment by tananaev** [comment]
You can send me an email. Address is in profile.

**Comment by marchantm** [comment]
The tracker use UDP port. The V680 Protocol accept UDP?

**Comment by tananaev** [comment]
Are you absolutely sure that it's not possible to use TCP for this device?

**Comment by marchantm** [comment]
Yes, i asked to the vendor :(

2016-06-14 17:44 GMT-04:00 Anton Tananaev <notifications@github.com>:

> Are you absolutely sure that it's not possible to use TCP for this device?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/1982#issuecomment-226025537>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF5Qb-tTUM20QAuYuUYMqSK_lnbVYUVYks5qLyC1gaJpZM4IpMgC>
> .
>



-- 

*MAURICIO MARCHANT*
------------------------------

Considera el medioambiente y ‘Piensa *antes* de imprimir’

**Comment by tananaev** [comment]
I have added UDP support.

**Comment by RendaniN** [comment]
HI Anton,  i have a device using v680 tracking is working perfectly, im having problems getting events/alarms SOS to be specific any help to point me in the right direction would be appreciated

**Comment by RendaniN** [comment]
Sorry
