### ISSUE TITLE
showing 0 in lat, lang and speed

### ISSUE THREAD

**Issue by SiddiqueAhmad** [tananaev/traccar#1984]
server logs showing 0 in all params, also time is wrong

`HEX: 78781f120d0b0b000000c00000000000000000002000019a041e7f00bd4f0043a4010d0a78780a1305006400010044a6830d0a78780d0103554880201803160045667e0d0a78781f120d0b0b000000c00000000000000000002000019a041e7f00bd4f0045c1370d0a78781f120d0b0b000000c00000000000000000002000019a041e7f00bd4f0046f3ac0d0a78781f120d0b0b000000c00000000000000000002000019a041e7f00bd4f0047e2250d0a`
`id: 1, time: 2013-11-11 05:00:00, lat: -0.00000, lon: 0.00000, speed: 0.0, course: 0.0`

using 5023 as port (GT06), however it was decoded on other GpsGateServer as GT02 device too, but in case of GT02 it give unknow device

**Comment by SiddiqueAhmad** [comment]
done, after setting the device offset all okay now, thanks for such a great application open source

**Comment by ijrad** [comment]
Hi Siddique, do you mean that the issue was resolved when you set the time zone of your device?, got the same issue with a tk102 tracker, please how you fixed this issue? Thanks

**Comment by SiddiqueAhmad** [comment]
sorry i forgot how it was fixed, and i also missed your message
