### ISSUE TITLE
Delete all things related to user when I delete the user

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#1986]
hi,

I want to be able to delete all things related to a user when the user is deleted. For example I delete a user, I want to delete the devices he has, the groups he has created, the position data for those devices he owns etc. Is this possible? If yes can you please guide me on that? Probably need to add some on cascade option to few more tables or something? Thanks

My system design is such that one device will only belong to a single user. When the user gets deleted, I no longer need to keep the devices, groups etc, that belong to that user.

**Comment by tananaev** [comment]
You can try to add cascade delete option for group and device tables.

**Comment by m-menon** [comment]
alright thanks :+1:
