### ISSUE TITLE
GT06 protocol based device always sent Login packet to server

### ISSUE THREAD

**Issue by rbniranjan** [tananaev/traccar#1988]
Hi,

I am using my own TCP based tracker server it is written in PHP. My problem is , Device is always send login packet to my server.

Can any one suggest me what I am doing wrong. 

Thanks.

**Comment by tananaev** [comment]
Please don't spam everywhere with your question.

**Comment by rbniranjan** [comment]
Ok, I will not put same question everywhere.

Can you please provide me any suggestion regarding my question.

**Comment by tananaev** [comment]
I would recommend to compare your reply with Traccar server reply and see if there's any difference there.

**Comment by rbniranjan** [comment]
Ok, Thanks Tananaev,

I got the solution.
