### ISSUE TITLE
tracer won't start on mac os

### ISSUE THREAD

**Issue by satgurumss** [tananaev/traccar#1994]
I'm trying to install traccar server on mac OS. i have installed JDK and tried running the commands mentioned on the site.
the first one runs successfully, but the second one gives a prompt that java is not installed.
```
Abids-MacBook-Air:traccar-macosx-64-3.5 Satguru$ sudo ./traccar.run
Verifying archive integrity... All good.
Uncompressing traccar  100%  
./setup.sh: line 7: [: -lt: unary operator expected
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
Detected Mac OSX:
The traccar daemon is already installed.
Abids-MacBook-Air:traccar-macosx-64-3.5 Satguru$ 
```

**Comment by tananaev** [comment]
Looks like you don't have Java installed. What's the output of the following command:
```
java -version
```

**Comment by satgurumss** [comment]
Thanks. I had the wrong version of java installed. It works now. Thank you for your help.
