### ISSUE TITLE
Data not send to Synology Server

### ISSUE THREAD

**Issue by Bassieven** [tananaev/traccar#2014]
Hi,

I've got a  working version of the Traccar Synology server, and installed the iOS client on my iphone. My iphone sends fine, but Synology doesn't recieve data.

**My settings iPhone**
external IP
port 55005 (wich is open)
Unique ID
Service status on
No errors on log

**My Synology Settings**
external IP:55000
added unique ID

Result, no recent updates.

Please help me out!

**Comment by tananaev** [comment]
In regular version of Traccar port for Traccar Client is 5055, so I'm guessing on Synology you should be using 55055 instead of 55005.

**Comment by Bassieven** [comment]
IT's port 55055, maybe good idea to document it on the installation page.

**Comment by tananaev** [comment]
It is documented here:

https://www.traccar.org/devices/

Then for Synology you just need to add 5 at the beginning.

Where did you get 55005 from?

**Comment by Bassieven** [comment]
No, it's 55055, the one you shouted earlier 2 replies above. So indeed it's another 5 in front, but it's a good thing to post on https://www.traccar.org/synology/

**Comment by tananaev** [comment]
Updated the page.

**Comment by Bassieven** [comment]
Great man! Superb support
