### ISSUE TITLE
Does any one recognise this tracker and can assist me with the correct port to use 

### ISSUE THREAD

**Issue by goddies** [tananaev/traccar#2019]
Good Day 

I am trying to get this tracker to work on http://demo.traccar.org/  

It has a generic name of OBD80
I tried a whole range of port numbers eventually 
I got a response from IP 40.122.161.24 5023 
But alas no tracking info 
It has an id that is 10 digit 
That looks like this 8160******
The original website is 
http://3.tkstargps.net/

But there is no fun in that, I enjoy using .traccar app and website I would really like to get the tracker to work here. I used to use a TK206 and it worked brilliantly. 

I would appreciate any help as I foxed by this device. 

![big_2](https://cloud.githubusercontent.com/assets/19916518/16021936/a702fda2-31b5-11e6-8c60-accbb16aa11b.jpg)
![big_3](https://cloud.githubusercontent.com/assets/19916518/16021937/a70865da-31b5-11e6-9f60-88d3bd402aa1.jpg)
![big_1](https://cloud.githubusercontent.com/assets/19916518/16021935/a6e4b450-31b5-11e6-8371-bc43a1102cb1.jpg)

This tracker is definitely in the cheap Chinese range 

Here is an extract from the manual 

4.12 fortification disarm SMS settings
SMS fortification: SF Re: SF OK
SMS disarm: CF Re: CF OK
4.14 GPS restart  SMS: CQGPS
4.15 Restore factory settings 
SMS command: FORMAT
4.16 Device reboots  SMS: CQ
4.17  Device Check:  SMS query device information: CXZT
4.18 APN settings 
APN Instruction format: apn123456 cmnet Re: apn ok

If it will help I can attach a copy of the manual. 

Your help and kind assistance would be much appreciated. 

Regards 

Goddies

**Comment by goddies** [comment]
I meant to add that I thought it was a GT06 the manuals look very similar and the sms commands look almost exactly the same.

**Comment by tananaev** [comment]
One of the ports from the following page should work:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by goddies** [comment]
Dear tananaev 

I have tried all those ports as suggested.

This tracker uses an id number rather than an imei number 

The id is 8160531234 (I changed the last few numbers for this web posting)

Do I enter the number as 8160531234 or do I add a zero in front of the number as with some other trackers. Like this 08160531234

I have tried all the ports twice and no joy the only one I can get a reaction out of i some of the port numbers and that is one time and date update after adding a zero or removing a zero from the end.

I tried the id number in this format 8160531234, 08160531234 and 008160531234 in all my testing but alas no joy.

I would welcome any and all suggestions, 

Thank you again for your time and trouble and any assistance you might be able to provide. 

Regards

**Comment by tananaev** [comment]
How do you know that it doesn't use IMEI? What's the IMEI number?

**Comment by novistudionl** [comment]
Its using the H02 protocol, so you need to use port 5013 and use this as the identifier: 8160531234

**Comment by goddies** [comment]
Thank you novistudionl thank you so much it works very happy Thank you again so so much!!!

Thank you  tananaev  for trying to help me I am very appreciative of your help !!!

**Comment by Phup** [comment]
Hello.
Any idea how to set continuous monitoring on this GPS tracker?
Thanks.

**Comment by goddies** [comment]
Hello Do you have the manual for this device if not I can email you pm me your email address. Regards Godfey

**Comment by Phup** [comment]
Hello Godfey,
Would appreciate that if possible. 
Please use this temporary forward email: phup@forward.cat
Thanks,

**Comment by FuntPND** [comment]
Good day.
Could you please send me a user manual to this tracker.
Just send me a short message with this form http://flei.ho.ua/contact.html, I will answer.

**Comment by goddies** [comment]
Drop me a email and I will send you the manual there seems to be a problem with your server.

The project "Ordinary Hosting" successfully operating since August 2005,
Internal Server Error (500)

When the page request http://flei.ho.ua/cgi-bin/email.cgi An internal error occurred on the server. Please contact the administrator at flei-admin@s2.ho.ua

**Comment by FuntPND** [comment]
Thank you for the answer. I received your message and sent you my e-mail.
I know about that error, but I actually receive messages from that form :)

**Comment by Gar-za** [comment]
So is there a manual for this device?  If so I would like it too.

**Comment by goddies** [comment]
What is your email I can send it to you.

**Comment by Gar-za** [comment]
alwaysworking2hard@gmail.com

thanks

**Comment by FuntPND** [comment]
You can also request documentation by manufacturer: lcbtech.cn

**Comment by johanhje** [comment]
Could you please send me the manual to?

johan@hjelmberg.se

Best regards, Johan

**Comment by MerlinCZ** [comment]
Please, can anyone tell me what is the default IP adress and Port for 3.tkstargps.net for this device ? 
i changed it and forgot :( thank you very much.

**Comment by goddies** [comment]
Hello 

Send the FORMAT  command via sms to the tracker that will reset it to its factory defaults and could possibly solve your problem.

Regards 

Goddies

**Comment by MerlinCZ** [comment]
Unfortunately, after a factory reset will restore all values, but set the IP address and the port remains. I've already tried.

**Comment by goddies** [comment]
Hello 

I have two numbers from my notes I am not sure which is which 

What is the problem do you need a tracking server to monitor your tracker. 

If you need a tracking server to monitor your tracker I have one Hosted in Cape Town South Africa you welcome to use its on the house, you will need to send me a email and password.  If you need a European one try traccar.org. If need access to a server let me know can do the setup via email or pm.

In the mean time this is the out put from my notes 
XM_GT08B_SW_3.0 2016/03/22 19:30 ID:8160813069 IP:120.076.079.192 8185 BAT:6 APN:CMNET GPS:A-11-09 GSM:25

Or try IP 106.3.230.234 8185 

I not sure which is what or if those ip's will even work.

Regards

**Comment by MerlinCZ** [comment]
Thank you very much, the first IP address works.
traccar server I'll install on your server, but I wanted to test the function of tkstargps - function values of cars loaded from OBD2

thanks a lot.

**Comment by goddies** [comment]
Cool I dont use all those features. I dont trust the makers and am afraid I will mess my car up. 

Send an email with your email address and password to  godfrey_@_compudoc_._co_._za just remove the underscores for the correct address to email. 

I will create one for you. No problem.

Regards

**Comment by arpadf** [comment]
Dear Everybody,
I have this type of GPS tracker but unfortunately I forgot the tracker password. I tried to do the FROMAT but nothing changes. Could anybody help me, please? How can I reset the tracker password?
Thank you!

**Comment by tananaev** [comment]
@arpadf, I guess it's better to contact device vendor.

**Comment by goddies** [comment]
@arpadf I had a look at my notes on this tracker, have you changed the admin number, ie trying to send commands to the tracker from a cell number different to the admin number,  because the majority of commands don't need a password even format to work. Its just a thought for you to consider.

**Comment by arpadf** [comment]
@goddies Thank you but I have tried it! I have tried to change the APN settings from a different number but I always got password error message when I used the defaul (123456) password. I unable to setup APN settings because I always get password error message.

**Comment by assid2** [comment]
Hi,
Did you get this working ? 
Can someone please post a howto ? I have the same device and would love to try traccar.

**Comment by goddies** [comment]
> 
> 
> Hi,
> Did you get this working ?
> Can someone please post a howto ? I have the same device and would love to try traccar.
Hi  assid2

I use this tracker and have it working. It is very reliable. 

Send me an email to godfrey@compudoc._co._za remove the _ and will try to help you. 

Regards 
Godfrey
