### ISSUE TITLE
on login screen

### ISSUE THREAD

**Issue by warlockopy** [tananaev/traccar#2024]
Is it possible to disable the register option in the login screen. In order that only and administrator can add users

**Comment by tananaev** [comment]
Yes, you can disable it in server settings.

**Comment by warlockopy** [comment]
Wich entry key, I am not finding anything related to that?



    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>

**Comment by tananaev** [comment]
No, you can disable it from web console as an admin user.

**Comment by warlockopy** [comment]
Found it thanks
