### ISSUE TITLE
Not processing h02 protocol

### ISSUE THREAD

**Issue by jeancaffou** [tananaev/traccar#2035]
Tracker bought from here:
http://www.yulongdatechnology.com/#!products/cp0e

Protocol was found to be h02 by using Hex decoder.

Tracker is programmed to send data to port 5013. Server is receiving data. In the log I have:

`2a48512c3335333530353232303837333036372c56312c2c562c343630352e37353733322c4e2c30313433302e37333836332c452c302e30302c302c2c46464646464645462c3132352c3139342c202036342c643323200d0a`

Which decodes to

`*HQ,353505220873067,V1,,V,4605.75732,N,01430.73863,E,0.00,0,,FFFFFFEF,125,194,  64,d3# 
`

No other log other than this DEBUG. Troubleshooting link says:
https://www.traccar.org/troubleshooting/

> **If there are HEX messages in the log, and they are not followed by any other log records, it can mean one of two things:**
> Your device doesn’t send GPS location. One of the reasons might be that it doesn’t have a GPS fix. Note that GPS doesn’t work indoors and it can take up to 15 or more minutes for device to get a first fix. Be patient.
> 
> You are using wrong port. If you are using Chinese device, you must read about ports for Chinese GPS trackers. For all other devices, please read protocol identification guide.

Port is not wrong according to this link:
https://raw.githubusercontent.com/tananaev/traccar/master/tools/test-integration.py

I think there is a slight deviation from the h02 protocol that the device sends and it is not processed correctly.

**Comment by tananaev** [comment]
It looks like your device doesn't report time and date. I would recommend to contact vendor and clarify why it can be happening. Possibly device firmware issue.

**Comment by jeancaffou** [comment]
Yes, this must be the issue. I wouldn't count on any support from the Chinese vendor. 
Would it be possible to default to the current date and time in these cases, rather than ignore the AVL?

**Comment by tananaev** [comment]
Fixed the problem by using server time as a fallback.
