### ISSUE TITLE
Traccar Server Starts but webpage is blank

### ISSUE THREAD

**Issue by nags66** [tananaev/traccar#2040]
Hi 

I have built the traccar server source code with H2 DB instance as well. When I start the server it starts with no errors or exception, but the webpage is blank with a title and a spinning circle in middle. What might be wrong? 

-Nags

**Comment by tananaev** [comment]
I guess you are missing something. Check browser developer console.

**Comment by nags66** [comment]
Where is that console? I have configured a port 7548 and the console am accessing is http://localhost:7548

What would be the developer console url?

**Comment by tananaev** [comment]
There is no URL. It's part of browser tools. What browser are you using?

**Comment by nags66** [comment]
ok. am getting a 404 for http://localhost:7548/app.min.js?_dc=1466651596114 Failed to load resource: the server responded with a

**Comment by tananaev** [comment]
Open `Settings > More Tools > Developer Tools`.

**Comment by tananaev** [comment]
Well, looks like you haven't compiled JavaScript files.

**Comment by nags66** [comment]
doesnt the build take care of it?

**Comment by tananaev** [comment]
No, it doesn't. You can try following option in the config:
```
<entry key='web.debug'>true</entry>
```

**Comment by nags66** [comment]
How do I compile the JS?

**Comment by tananaev** [comment]
This script takes care of compiling JS:

https://github.com/tananaev/traccar/blob/master/tools/minify.sh

**Comment by nags66** [comment]
Should I execute minify.sh outside of the IDE, it looks like a shell script. am on windows.

**Comment by tananaev** [comment]
It probably won't work on Windows. Have you tried the option from my comment above?

**Comment by nags66** [comment]
Which comment? the minify.sh? or the web entry?

**Comment by tananaev** [comment]
About `web.debug`.

**Comment by nags66** [comment]
yes, i added, but havent tested yet. I have to figure out how to compile the js. else it will throw the same error. Has anyone done this on Windows? 
Or should I migrate to ubuntu

**Comment by tananaev** [comment]
You don't need to compile JS if you use that flag in the config.

**Comment by nags66** [comment]
oh ok.

**Comment by tananaev** [comment]
OK, let me explain in a bit more details. In general, JavaScript doesn't require any compilation.

What `minify` does is combining all JS files into one big file and minifies it by removing spaces etc. In debug mode (`web.debug`), your browser will download each file separately. Basically, everything will work, but it will be slightly slower than minified version that I use for release.

**Comment by nags66** [comment]
Ok, am able to view the console, added a device and device is sending data. But still am getting this error.

ext-all-debug.js:24866 GET http://localhost:7548/api/session?_dc=1466654374172 404 (Not Found)

**Comment by tananaev** [comment]
That's not an error. You can safely ignore that message.

**Comment by nags66** [comment]
device is not being tracked... it shows the device is online, but no co-ordinates are there

**Comment by tananaev** [comment]
Check logs. Usually it means that device is connected, but it doesn't send any GPS data.

**Comment by nags66** [comment]
Which log? i dont see tracker-server.log anywhere. The same device sends data to the demo.traccar.org server, I can see the co-ordinates. But not on my server.

**Comment by tananaev** [comment]
What config file are you using? Log file location is configured that file.

**Comment by nags66** [comment]
I checked that log file, nothing in that.

**Comment by tananaev** [comment]
There are no HEX messages? It means that your device doesn't send anything.

**Comment by nags66** [comment]
it has. 
474554202f3f69643d3431363934332674696d657374616d703d31343636363131363038266c61743d31322e3931333136323731266c6f6e3d37372e35393833363332372673706565643d302e302662656172696e673d302e3026616c7469747564653d3830302e3026626174743d33342e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f312e362e3020284c696e75783b20553b20416e64726f696420342e342e343b20484d204e4f544520314c5445204d4955492f56372e332e312e302e4b48494d494444290d0a486f73743a203139322e3136382e312e31373a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a

**Comment by nags66** [comment]
Looks like there is a error
UPDATE devices SET status = ?, lastUpdate = ?, motion = ? WHERE id = ?; [42122-191] - JdbcSQLException (... < QueryBuilder:62 < *:132 < DataManager:365 < ConnectionManager:123 < ...)
2016-06-23 10:02:10  WARN: [5F68B472] error - NullPointerException (MotionEventHandler:39 < BaseEventHandler:26 < BaseDataHandler:29 < ...)

**Comment by tananaev** [comment]
I guess something is missing in your config. @Abyss777 might be able to help with this one.

**Comment by nags66** [comment]
Am getting the coordinates, but it shows an old information, why not current?

**Comment by tananaev** [comment]
You are not providing any details. How do you expect me to answer your question?

**Comment by Abyss777** [comment]
> Looks like there is a error
Do you use last git code?

**Comment by nags66** [comment]
Yes, i downloaded it from ur website. 

I dont see any errors now in the log file. 
But the device coordinates seems to be dated and not current.

**Comment by tananaev** [comment]
Maybe your device just sends old data?

**Comment by nags66** [comment]
:) lets see. thanks for the support guys...!!
