### ISSUE TITLE
tracker-server LOG in chinese

### ISSUE THREAD

**Issue by elyfran** [tananaev/traccar#2041]
Yesterday the log was in English and today is in Chinese and stopped track . Anyone know why ?

following example:
`〲㘱〭ⴶ㌲〠㨰㘳㐺‱䤠䙎㩏传数慲楴杮猠獹整⁭慮敭›楗摮睯⁳敓癲牥㈠㄰′㉒瘠牥楳湯›⸶″牡档瑩捥畴敲›浡㙤ഴ㈊㄰ⴶ㘰㈭″〰㌺㨶ㄴ†义但›慊慶爠湵楴敭渠浡㩥䨠癡⁡潈却潰⡴䵔 㐶䈭瑩匠牥敶⁲䵖瘠湥潤㩲传慲汣⁥潃灲牯瑡潩⁮敶獲潩㩮㈠⸵㈹戭㐱਍〲㘱〭ⴶ㌲〠㨰㘳㐺‱䤠䙎㩏䴠浥牯⁹楬業⁴敨灡›㤴洴⁢潮⵮敨灡›洰ൢ㈊㄰ⴶ㘰㈭″〰㌺㨶ㄴ†`

**Comment by tananaev** [comment]
What are opening log file with? Notepad? Try some other editor.

**Comment by elyfran** [comment]
Notepad++ or Notepad, but the error disappeared after reinstalled traccar .

thank you for your availability.
