### ISSUE TITLE
Can't Run Traccar Web Interface

### ISSUE THREAD

**Issue by saintfalcon** [tananaev/traccar#2046]
Hi,

I can't seem to be able to run traccar web interface
Inspect element on Chrome kept saying 

```
GET http://87.117.231.154/api/server?_dc=1466691317112 404 (Not Found)
[E] Ext.JSON.decode(): You're trying to decode an invalid JSON String: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/server was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at 87.117.231.154 Port 80</address>
</body></html>

Object
console.trace()
Uncaught Error: You're trying to decode an invalid JSON String: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/server was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at 87.117.231.154 Port 80</address>
</body></html>
```
My server's url is http://87.117.231.154/debug.html

**Comment by saintfalcon** [comment]
Restarted VPS
Restarted Traccar

now presented with

<img src='http://i.imgur.com/7MtVa8N.gif' />

**Comment by tananaev** [comment]
Are you using Apache server as a proxy?

**Comment by saintfalcon** [comment]
I don't think I set apache server as proxy.
just finished install lamp as in digital ocean's article

OS : ubuntu 12.04 64bit

**Comment by tananaev** [comment]
How did you install Traccar?

**Comment by saintfalcon** [comment]
as the traccar documentation suggest.

copy the traccar.run and run sudo ./traccar.run
run sudo /opt/traccar/bin/traccar start

said that traccar is already running

**Comment by tananaev** [comment]
Have you changed web port in the config file?

**Comment by saintfalcon** [comment]
yes, I changed it to port 80 instead of 8082

**Comment by tananaev** [comment]
Well, I can see that you have Apache server running on port 80, and it's not possible for two processes to listen on the same port. So, you must be missing something.

**Comment by saintfalcon** [comment]
works well after changed back to port 8082.

so I just have to keep it running at port 8082?

**Comment by tananaev** [comment]
You can change it to 80, but then you need to either change port in Apache or stop Apache.

**Comment by saintfalcon** [comment]
ah.....
ic, so that's where i went wrong.
thanks for the enlightenment

**Comment by tananaev** [comment]
Traccar has its own embedded web server, so you don't need Apache.
