### ISSUE TITLE
Chrome Browser - Devices not Displayed on map

### ISSUE THREAD

**Issue by neilromig** [tananaev/traccar#2051]
My Traccar installation works perfectly on Linux & Windows desktop browsers both Firefox and Chrome, but on my mobile (Nexus6 / Marshmallow / Chrome) the devices are not displayed on the map. The Devices pane shows them OK but nothing on the map. Also the Reports pane is not shown but perhaps this due to the smaller screen size?
Does this relate to issue #2045?

**Comment by tananaev** [comment]
Reports panel is disabled for small screens.

As for the other problem, I'm not sure how to debug the issue. Can you connect from developer tools (desktop Chrome) to your phone and check if there are any errors or warnings there?

I don't think your issue is any way related to #2045.

**Comment by neilromig** [comment]
Correction - looks like it is a Chrome issue failing to display devices on startup.

**Comment by janci007** [comment]
This is not Chrome specific, it is a race condition.
is LatestPositions store is populated before Devices store is loaded, map does not display the markers.
WebSocket connection must be created **after** Devices store loads

in Root.js controller change the loadApp function

```
loadApp: function () {
        var self = this;
        Ext.getStore('Groups').load();
        Ext.getStore('Devices').load({
            callback: function(){
                // call the asyncUpdate after Devices store loads
                self.asyncUpdate(true);
            }
        });
        Ext.get('attribution').remove();
        if (this.isPhone) {
            Ext.create('widget.mainMobile');
        } else {
            Ext.create('widget.main');
        }
        // remove the immediate asyncUpdate function call
        //this.asyncUpdate(true);
    },
```

**Comment by tananaev** [comment]
Latest version already includes this fix.
