### ISSUE TITLE
Feature Request : Event : Ignition

### ISSUE THREAD

**Issue by nefertiti007** [tananaev/traccar#2059]
Dear All,

I am a non programmer else I would have done it myself.,

But anyone who can, from the contributors who are working on events.

It would be nice to add Ignition event as well on/off/notdetected

**Comment by tananaev** [comment]
I want to release new version as soon as possible, but after that we can definitely add new event types.

**Comment by Abyss777** [comment]
@nefertiti007 it is implemented in https://github.com/tananaev/traccar/commit/5d3b7cbe5924d4a4552035626a83e26b1e756255
Thanks for feedback

**Comment by nefertiti007** [comment]
Perfect, eagerly waiting :) for the next version...  to test.

Great Work @Abyss777 and @tananaev

**Comment by Abyss777** [comment]
It was released in 3.7 and I think can be closed.
