### ISSUE TITLE
Meitrack Temperature sensors values

### ISSUE THREAD

**Issue by slachtar** [tananaev/traccar#2065]
Hello,
seems in meitrack parsing, there's a missing, yet important, field which is temperature sensors values,
the field is the last one and it appears in HEX like this:
000B51 //which should be converted to 11.81°C 
well, first byte 00 is number of sensors (so we need a for loop later from 0 to 0 in this cas)
for each loop step, we read first byte 0B which converts to 11 decimal (integer part of the temp)
and the 2nd byte 51 which converts to 81 decimal (decimal part of the temp).
so temperature for sensor0 is 11.81°C

if we have more sensors, we loop reading two bytes (1 for integer part and 1 for decimal part).

Regards

**Comment by tananaev** [comment]
I need HEX message samples and protocol documentation.

**Comment by slachtar** [comment]
Hello,
message in raw format:

$$K157,866771027160687,AAA,3,37.040231,10.042391,160412151656,A,10,11,0,48,0.8,21,1035518,774980,605|2|0010|307B,0400,0000|0000|0000|0A47|03E3,,,1,0000,001206*2C

You can see 001206 in the end (before the checksum which is temperature for
one sensor).

Protocol documentation is attached, page 8.

Regards,


On Fri, Jul 1, 2016 at 11:12 PM, Anton Tananaev <notifications@github.com>
wrote:

> I need HEX message samples and protocol documentation.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/2065#issuecomment-230058653>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACaj6rUypBrNaBPWTcgvJe79o33Ze5IDks5qRZDbgaJpZM4JDLzO>
> .
>



-- 
Slah Lachtar
Tel. (+216) 98 221 575

**Comment by slachtar** [comment]
Link is here:

http://www.meitrack.com/meitrack-support/protocol/MEITRACK_GPRS_Protocol_V1.8.pdf

**Comment by slachtar** [comment]
Incredibely fast, good work, will report test results.
