### ISSUE TITLE
 Recovering ignition and distance

### ISSUE THREAD

**Issue by cadastro2005** [tananaev/traccar#2068]
Hi,

How can I recover ignition and distance from the property attributes to be able to persist in the table positions?

thx

**Comment by tananaev** [comment]
By default it's stored in JSON format in `attributes`. If you database can extract values from JSON, you can do it. For example, as of MySQL 5.7.8, MySQL supports a native JSON data type.

**Comment by cadastro2005** [comment]
thx...
