### ISSUE TITLE
Issues with geofences

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#2071]
@Abyss777,

I just fixed a crash in geofences:
```
Exception in thread "main" java.lang.NullPointerException
	at org.traccar.database.GeofenceManager.refresh(GeofenceManager.java:154)
	at org.traccar.database.GeofenceManager.<init>(GeofenceManager.java:56)
	at org.traccar.Context.init(Context.java:204)
	at org.traccar.Main.main(Main.java:30)
```

Basically if device didn't have a geozone or group, it used to crash every time on startup.

I noticed another odd thing. Why do we have `deviceGeofences` and `deviceGeofencesWithGroups`? Can't we just use one? Actually, `deviceGeofences` doesn't seem to be used at all. Can you please take a look and fix it if second one is not needed. Thanks

**Comment by tananaev** [comment]
Another issue with saving. OpenLayers library returns following format for Polygon:
```
POLYGON((-320424.02257145883 6912353.341885058,-259274.39994331787 6782716.1419134,-158989.01883316657 6887893.4928338025,-320424.02257145883 6912353.341885058))
```
Your parser crashes on it. Maybe we should use some existing library after all? Please fix this issue as well if you have time.

**Comment by tananaev** [comment]
Web interface code is committed, so you can try it yourself.

**Comment by Abyss777** [comment]
Thanks for the fix, i will investigate how it happen.
deviceGeofences used here https://github.com/tananaev/traccar/blob/master/src/org/traccar/api/resource/GeofenceResource.java#L70

About Polygon, I can explain my thoughts.
Our realization of area is not compatible with standard, it just uses an idea. There is no Circle in standard, and algorithm is not supported holes in Polygon. The double brackets used to describe one big polygon and subtracted others from it.  Like ((big) (hole) (hole)). Because of that I did not add to parser double brackets. I thought we will use own realization of parsers and double brackets will be just unnecessary.
I will add second brackets.

**Comment by Abyss777** [comment]
> Web interface code is committed, so you can try it yourself.

Coordinates need conversion I think.

Broom street is piece of test device path I draw manually and it looks far away from the beginning of test path. (path is from  test-generator.py)

````
2:{id: 4, attributes: {}, name: "The Beginning", description: "",…}
area:"CIRCLE (40.722412 -74.006288, 250)"
attributes:{}
description:""
id:4
name:"The Beginning"
3:{id: 5, attributes: {}, name: "Broom street", description: "",…}
area:"POLYGON((-8237945.784320789 4971657.8008957105,-8237597.040379238 4971442.821753658,-8237651.979493319 4971352.05278257,-8237993.557463468 4971581.363867425,-8237945.784320789 4971657.8008957105))"
attributes:{}
description:""
id:5
name:"Broom street"
````

**Comment by Abyss777** [comment]
> I just fixed a crash in geofences
> Thanks for the fix, i will investigate how it happen.
Sorry, it' s my fault. I have groups or geofences in my test environments, and just missed it.

**Comment by Abyss777** [comment]
I want to notice that wrong order of coordinates is hardcoded to openlayers. It uses longtitude on the first place and latitude on second.
What will we do? Store as openlayers do or parse it and store as other world?

**Comment by tananaev** [comment]
Looks like coordinated need some conversion, so let me investigate it a bit further.

OpenLayers doesn't have WKT encoder/decoder for Circle, so we need to add it. I'll try to do it over the week. I want to release a new version next weekend, so need to finalize everything.

**Comment by Abyss777** [comment]
Here is tested on OSM coder/decoder for Circle.
````javascript
function wktToCircle(map, ps) {
	if (ps.startsWith("CIRCLE")) {
        m = ps.match(/\([^\(\)]+\)/);
        if (m !== null) {
            tmp = m[0].match(/-?\d+\.?\d*/g);
            if (tmp !== null) {
              		var center = ol.proj.fromLonLat([Number(tmp[1]), Number(tmp[0])]);
            			var view = map.getView();
  								var projection = view.getProjection();
 									var resolutionAtEquator = view.getResolution();
  								var pointResolution =      projection.getPointResolution(resolutionAtEquator, center);
  								var resolutionFactor = resolutionAtEquator/pointResolution;
  								var radius = (Number(tmp[2]) / ol.proj.METERS_PER_UNIT.m) * resolutionFactor;
                	geometry = new ol.geom.Circle(center, radius);
            }
        }
    }
  return geometry;
}

function circleToWkt(circle) {
  var result, center;
	if (circle instanceof ol.geom.Circle) {
    var center = geometry.getCenter()
		var radius = geometry.getRadius()
		var edgeCoordinate = [center[0] + radius, center[1]];
		var wgs84Sphere = new ol.Sphere(6378137);
		var groundRadius = wgs84Sphere.haversineDistance(
	    ol.proj.transform(center, 'EPSG:3857', 'EPSG:4326'), 
  	  ol.proj.transform(edgeCoordinate, 'EPSG:3857', 'EPSG:4326')
		);
    center = ol.proj.transform(circle.getCenter(),'EPSG:3857', 'EPSG:4326');
    result = "CIRCLE (";
		result += center[1] + " " +center[0] + ", ";
    result += groundRadius + ")";
	}
  return result;
}
````

**Comment by Abyss777** [comment]
And here is Polygon coder/encoder.
I will tidy it up, combine and will make a pull request.
````javascript
function wktToPolygon(map, ps) {
	var points = [];
    var m, i, lat, lon, tmp, tmpArr;
    if (ps.startsWith("POLYGON")) {
        m = ps.match(/\([^\(\)]+\)/);
        if (m !== null) {
            tmp = m[0].match(/-?\d+\.?\d*/g);
            if (tmp !== null) {
                for (i = 0, tmpArr = []; i < tmp.length; i+=2) {
                    lat = Number(tmp[i]);
                    lon = Number(tmp[i + 1]);
                    points.push(ol.proj.fromLonLat([lon, lat]));
                }
                return new ol.geom.Polygon([points]);
            }
        }
    }
}

function polygonToWkt(polygon) {
	if (polygon instanceof ol.geom.Polygon) {
    polygon.transform('EPSG:3857', 'EPSG:4326');
  	var points = polygon.getCoordinates();
    var result = "POLYGON(("
    for (var i = 0; i < points[0].length; i+=1) {
      	result += points[0][i][1] + " " + points[0][i][0] + ", "
    }
    return result.substring(0, result.length - 2) + "))"
  }
}
````

**Comment by tananaev** [comment]
I guess everything is sorted in this issue. Can we close it?

**Comment by Abyss777** [comment]
Sure.
