### ISSUE TITLE
TK103 decoding problem

### ISSUE THREAD

**Issue by vladamirk** [tananaev/traccar#2075]
HI Anton, I tried already few trackers with your traccar, now I'm testing tk103 and it's connected thru ODB2 port, so I was expecting it to send more data then just coordinates, below you can see decoded data, I tried to break it apart, it seems like it sending at least 5 useful events? In UI it just showing location, time, speed, and status code changing from 00000000 to 00000001, is there any other information that can be extracted from data that's coming, and what's status code change mean?
Also I attached txt with HEX data.
[tk103 HEX info.txt](https://github.com/tananaev/traccar/files/345801/tk103.HEX.info.txt)
Thank you in advance.
Hope to hear from you soon.
```
(016023234823
BR00160701
A4725.4862
N12213.9120
W000.023580000
0.0000000000
L00000000)

(016023234823
BR00160701
A4725.4785
N12213.9349
W000.005354433
3.9900000001
L00000000)
```

**Comment by tananaev** [comment]
I don't think it's possible to extract any more info.

As for the status, here a quote from documentation:
> The 8 bits of IO The first bit representative of the main power switch, "0" means the main power-on, "1", means the main power-off.   The second bit on behalf of the ACC (ignition), "0" means    ACC off, "1" means ACC on.   Other reservations

**Comment by vladamirk** [comment]
About 8 bits of IO in our case only last "0" cganging to 1, maybe it's
ignition indicator?

On Monday, 4 July 2016, Anton Tananaev <notifications@github.com> wrote:

> I don't think it's possible to extract any more info.
>
> As for the status, here a quote from documentation:
>
> The 8 bits of IO The first bit representative of the main power switch,
> "0" means the main power-on, "1", means the main power-off. The second bit
> on behalf of the ACC (ignition), "0" means ACC off, "1" means ACC on. Other
> reservations
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tananaev/traccar/issues/2075#issuecomment-230250991>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AINLAx1lyMciN61G3SUdt-FLSQ1q3Y1Dks5qSNbYgaJpZM4JEIE7>
> .
>


-- 
Sent from Gmail Mobile

**Comment by tananaev** [comment]
It says that "the first bit representative of the main power switch".

**Comment by vladamirk** [comment]
Thank you for your help, have great week.
