### ISSUE TITLE
AWS API Gateway reports errors in Swaggar file

### ISSUE THREAD

**Issue by sgornick** [tananaev/traccar#2079]
In attempting to create an API where I import from Swaggar, I get the following warning:

```
Your API was not imported due to errors in the Swagger file.
Parameter type formData for parameter email not supported. Ignoring.
Parameter type formData for parameter password not supported. Ignoring.
```

I am using the latest from master:
https://raw.githubusercontent.com/tananaev/traccar/master/swagger.json

To replicate:
1.) Download Traccar Swaggar file:
$ wget https://raw.githubusercontent.com/tananaev/traccar/master/swagger.json
2.) In AWS API Gateway service 
http://console.aws.amazon.com/apigateway/home
3.) Click Create API button
4.) Select the Import from Swagger option.
5.) Click on the Select Swaggar File button.
Open the Swaggar.json file downloaded in step 1.
6.) Click the Import button.

The error shown above will be displaed.

**Comment by tananaev** [comment]
It sounds like a problem with AWS API Gateway. I guess it doesn't support `formData` parameters.

**Comment by sgornick** [comment]
> I guess it doesn't support formData parameters.

Looks like it.

"We don't support the 'formData' parameter type in Swagger.": https://forums.aws.amazon.com/message.jspa?messageID=723682

"You can still import the definition successfully but it will not import that parameter specifically."

So I'll close this ticket.
