### ISSUE TITLE
 GT06 : Stopping based on a vehicle speed.

### ISSUE THREAD

**Issue by cadastro2005** [tananaev/traccar#2080]
Hi,
For safety there is some additional parameter for sending stop at a certain speed command based on GT06 ?

**Comment by tananaev** [comment]
There are no additional parameters as far as I know.

**Comment by nefertiti007** [comment]
Stop command, works on GT06 only if the vehicle is below 20 Kmph, and In-case you Initiate a stop command, the device will accept the command and wait for the vehicle speed to reduce below 20kmph and then activate the command.

**Comment by cadastro2005** [comment]
thx @nefertiti007 and @tananaev 

Thank you for the explanation.

**Comment by asifalisheikh** [comment]
is there any other command to stop fuel when vehicle is running above the 20kmph speed
