### ISSUE TITLE
Does traccar support UPD connection from AVL05?

### ISSUE THREAD

**Issue by teerak13** [tananaev/traccar#2112]
Hi Tananaev,

The AVL05 supported UPD connection and I would likd to reduce a cost of data usage by using it. 
So I would like to ask you that, does traccar server support UPD connection from AVL05?  

Thanks,

**Comment by tananaev** [comment]
What protocol does AVL05 use?

**Comment by teerak13** [comment]
I'm not sure. May be totem v1.0 protocol.

**Comment by tananaev** [comment]
Totem protocol doesn't support UDP yet, but if you don't know which protocol your device uses, I would recommend to find it out first.

**Comment by teerak13** [comment]
Thank you so much for your prompt reply.
