### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by poobaisle** [tananaev/traccar#2124]
Hello,
Is there a step by step manual to install traccar on Ubuntu Server 16.04 LTS please ? From the official website, I understand it doesn't take more than the following 2 lines: 
- Run traccar.run (sudo ./traccar.run)
- Start daemon (sudo /opt/traccar/bin/traccar start)
However, I would like to know which environment is required (apache2 ?) ? Should I also install mysql-server ? Any version of JDK will go ? V8 is okay ?
Or does it only needs to run traccar.ru + start daemon ?
Thank you for your feed-back
Poobaisle

**Comment by tananaev** [comment]
Java version 7 or higher is required. If you don't have it, installer will tell you. No other dependencies, so you don't need Apache or anything else.

By default Traccar uses embedded database. If you want to use it with MySQL, you need to read following instruction (after installing Traccar):

https://www.traccar.org/mysql/

**Comment by poobaisle** [comment]
Thank you ! What are the advantages of using it with MySQL ? Does it give more flexibility ? Afterward, I want to add the web interface from Traccar Web UI because I need to generate the kind of reports I could find on his demo server. I guess, it means I need to shift to MySQL isn't it ?

**Comment by tananaev** [comment]
MySQL is recommended for any production server. Default embedded database is not designed to handle large amounts of data. If by Traccar Web UI you mean the project from Vitaly Litvak, it can work on any database as far as I know.

**Comment by poobaisle** [comment]
Yes, I meant the project from Vitaly Litvak. Then, I will try first with the embeded database. What is considered to be large amounts of data please ? A fleet of 50 vehicle would fit into the embedded database ? thank you

**Comment by tananaev** [comment]
For anything more than a couple of devices, I would not recommend to use embedded database.

**Comment by poobaisle** [comment]
Thx. I'll follow your recommendation then.
