### ISSUE TITLE
Traccar Installation problem

### ISSUE THREAD

**Issue by poobaisle** [tananaev/traccar#2125]
Hello,
I am facing problem to install traccar. I downloaded first the latest version through wget then unzipped the file. When I sudo ./traccar.run I get these lines:
./setup.sh: 7: [: -lt: unexpected operator
Detected Ubuntu or Debian
Then when I try to start traccar with sudo /opt/traccar/bin/traccar start
I get the message WARNING: traccar may have failed to start
And finally, when I use a browser to access traccar, it doesn't work.
Any ideas what I did wrong ?

Oupsss, I think I forgot to install JDK !

**Comment by tananaev** [comment]
What was the issue?
