### ISSUE TITLE
Info on Web API

### ISSUE THREAD

**Issue by sunhoww** [tananaev/traccar#2135]
I am trying to build a _ReactJS_ front-end app with **traccar** as the api backend. I had intended to port the app on mobiles with _React Native_ as well.

I noticed `demo.traccar.org` uses a few endpoints (like _xhr_:`geofences` and _ws_:`socket`) not specified in `swagger.json`. Could you direct me to where I could get the full set of endpoints.

**Comment by tananaev** [comment]
@Abyss777, do you have time update swagger file with new API calls for geozones?

**Comment by Abyss777** [comment]
@tananaev Yes, I'll do that. Is there any tools to automate it? or only manually?

**Comment by tananaev** [comment]
I used some tool before. Don't remember the name, but it was something to automatically generate swagger from JAX-RS code. Note that generated code might require some cleanup to remove duplications or some other stuff.

**Comment by Abyss777** [comment]
OK. I'll try and share results.

**Comment by sunhoww** [comment]
@tananaev and @Abyss777 Thanks a lot. I'm closing the issue.
