### ISSUE TITLE
Watch Protocol

### ISSUE THREAD

**Issue by fcontrerasz** [tananaev/traccar#2139]
Hi !

I try to setup a watch in port 5093.. traccar recognizes the string but this switch to possitive lat and Lon...

This is the string:
```
[3G*6105117105*008D*UD2,210716,231601,V,-33.480366,N,-70.7630692,E,0.00,0.0,0.0,0,100,34,0,0,00000000,3,255,730,2,29731,54315,167,29731,54316,162,29731,54317,145]
```
And this is the traccar log (possitive):

id: 6105117105, time: 2016-07-21 20:16:01, lat: 33.48037, lon: 70.76307, speed: 0.0, course: 0.0

![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/6060664/17042315/95c98b72-4f7a-11e6-8583-24b315e7ffc1.PNG)

**Comment by tananaev** [comment]
I have added a workaround, but the message is invalid. It shows negative latitude, but says that it's in North hemisphere. Same with longitude.
