### ISSUE TITLE
Notifications list is empty

### ISSUE THREAD

**Issue by ninioe** [tananaev/traccar#2150]
Hi Anton,
After I uploaded the new version to my server I noticed that the notifications list is empty.
On my development environment it works fine.
 
GET Request:
/api/users/notifications?_dc=1469427477354&userId=1&page=1&start=0&limit=25

Response:
{"details":"NullPointerException (NotificationResource:49 < ...)","message":null}

**Comment by Abyss777** [comment]
Hello
Have you enabled events subsytem in config file?
````
<entry key='event.enable'>true</entry>
````

**Comment by ninioe** [comment]
Thanks a lot.
That solved it.,
