### ISSUE TITLE
resetDelay/timeout variable default value

### ISSUE THREAD

**Issue by bpali** [tananaev/traccar#2160]
I want to set the resetDelay variable BUT before setting it I would like to know what is its default value or at least how can I find it.

I've looked around but didn't find anything. I also am aware of the fact that the resetDelay variable is a per protocol setting.

Waiting forn an aswer.

Thanks

**Comment by tananaev** [comment]
Default value is 0, which means no timeout. By the way, it's better to use `timeout` instead of `resetDelay` (old name for the same thing).

**Comment by bpali** [comment]
Thanks for you answer.

When you have time please update the documentation for the configuration file https://www.traccar.org/configuration-file/  and mention the **[protocol].timeout** variable. Also write there that, by default, there's no timeout.

I'm running traccar 3.3 so for me which of the below will work
```<entry key='ruptela.timeout'>60</entry>```
or 
```<entry key='ruptela.resetDelay'>60</entry>```
for setting 60 seconds timeout for ruptela devices ?

**Comment by tananaev** [comment]
I have update the key on the page. No timeout value means no timeout. This part seems pretty obvious. There is no meaningful default value.

I don't remember when I changed it. You might need to use old key name.

**Comment by bpali** [comment]
OK, thanks for you support
