### ISSUE TITLE
How to send commands to devices from web ? 

### ISSUE THREAD

**Issue by sulfy** [tananaev/traccar#2164]
Please help me on how to send commands such as turn off circuit , turn on circuit from web interface ?
Please Help

**Comment by tananaev** [comment]
There is a button to send commands in the web interface. What protocol are you using?

**Comment by sulfy** [comment]
I am using H02 protocol

**Comment by tananaev** [comment]
H02 supports engine stop/resume commands. You should be able to send them from the web interface.

**Comment by sulfy** [comment]
Should i type the same sms command in the web also?

**Comment by tananaev** [comment]
Where do you want to type it? There should be a dropdown box where you need to select the command.

**Comment by sulfy** [comment]
For me , the dropdown is blank / empty

**Comment by tananaev** [comment]
What version of Traccar are you using? Are you sure device is connected?

**Comment by sulfy** [comment]
It was an error with the device, Thanks

**Comment by owaresabd** [comment]
c

> H02 supports engine stop/resume commands. You should be able to send them from the web interface.

Can you provide me sample code for this?
