### ISSUE TITLE
Bulk Add of Devices Into Traccar

### ISSUE THREAD

**Issue by scmachines** [tananaev/traccar#2167]
Is there any way to add a large number of GPS devices/identfiers into the Traccar system at one time, or is it necessary to enter these one by one via the web interface? I have a Traccar server that listens to Calamp devices, and I changed from the H2 database to a mysql database. Everything works/tracks like it should for the devices I've entered manually. However, for the devices I've tried to add by simply pasting them into the device table of the mysql database, they do not show up or collect the GPS data at all. Any help or information one way or the other would be appreciated.

**Comment by tananaev** [comment]
There are two options:

1. Directly add devices to the database. Note that you need to link them to your user to be able to see devices in the web console.
2. Use web API to add devices.

**Comment by scmachines** [comment]
Thank You, this worked great. Have a great day!
