### ISSUE TITLE
Queclink GV300 not working

### ISSUE THREAD

**Issue by abitmedia** [tananaev/traccar#2170]
Hello, my English is not good, Congratulations on the excellent work of Traccar.

I configure the device gv300 with the ip and port 5004, the log displays me:
```
2016-07-29 19:50:42 DEBUG: [A83EDCCE: 5004 < 200.7.236.9] HEX: 2b41434b3a47545352492c3235303730342c3836383738393032303430393733352c2c303036382c32303136303732393139353033312c3034344524
```
With the hexadecimal tool to check if the respective IMEI, but in the monitoring panel appears to me as not connected.

The port 5004 is not closed on my server

The report mode is UDP

please help.

Thanks

![whatsapp-image-20160729 1](https://cloud.githubusercontent.com/assets/748127/17264922/15d2a110-55b0-11e6-94b1-cb37e910a33b.jpeg)

**Comment by tananaev** [comment]
Your device doesn't send any GPS data.

**Comment by abitmedia** [comment]
I found the problem, the GPS device is not covered, the vehicle start to move around the city began to arrive to the information

thank you very much
