### ISSUE TITLE
teltonika protocol display with property input 

### ISSUE THREAD

**Issue by onethings** [tananaev/traccar#2171]
Hi,
      I have FM1100( i think FM11XX will also work ) and want to display io with data property name. Below are the property name i have test my self with one by one to get property name. Hope some one can replace io number in traccar teltonika protocol or some things.
![io](https://cloud.githubusercontent.com/assets/18694038/17272752/d0c3ba44-56c4-11e6-9e1c-774b9e71ed2d.png)

i upload to google sheet. any one can use. Here are the link https://docs.google.com/spreadsheets/d/1PmDXKo51zZY3qIrQwJBRIk4V1TkfT_7Ibb57-rMmZ1s/edit?usp=sharing
![image](https://cloud.githubusercontent.com/assets/18694038/17272734/5201cef8-56c4-11e6-843a-858976be150e.png) 

configuration with one by one.
![2](https://cloud.githubusercontent.com/assets/18694038/17272757/eddc9d3a-56c4-11e6-90e7-c66145941177.png)
![1](https://cloud.githubusercontent.com/assets/18694038/17272758/f228280a-56c4-11e6-88ce-71de6470f705.png)

**Comment by tananaev** [comment]
I can only do it if mapping is the same for all Teltonika devices.

**Comment by onethings** [comment]
I think FM series will work. May be you can update it first.
I hvae download Teltonika Protocol v2.10 https://drive.google.com/file/d/0B4uZiASMO-o4WjFIdUlDcEI5NEU/view?usp=sharing   and can update with your v2.7 https://www.traccar.org/protocols/ teltonika	FMXXXX Protocols v2_7.pdf

**Comment by tananaev** [comment]
I haven't got time to look at it yet, but I'll check it as soon as I have some free time.

**Comment by onethings** [comment]
Thank you very much. :)

**Comment by tananaev** [comment]
I have added decoding of a few parameters, but there is too many to add all of them. I guess we can add them one by one as needed.

**Comment by onethings** [comment]
Thanks Tananaev. :+1:

**Comment by xizoaziz** [comment]
hi @onethings could you please explain  the different between Power and key_ignition ?
