### ISSUE TITLE
fuel monitoring

### ISSUE THREAD

**Issue by onethings** [tananaev/traccar#2174]
Hi, 
     Can you add fuel monitoring function in traccar, i have bought 3 model of teltonika device FM1100, FM1120, FM1125 (don't know why fm1125 gsm led not light will contact with the teltonika vendor). FM1100 and FM1120 are work. I connect with dyp ds1309 ultrasonic fuel sensor. i can support fuel level data as you want. fuel monitoring are display with a distance from A to B. Or display a day fuel usage in litres or a week, or a month, can custom report with date and time like gps history report.

Best regards,
Onethings

**Comment by onethings** [comment]
also can monitor a group fuel usage etc...

**Comment by tananaev** [comment]
Implementing reports is in plans.

**Comment by onethings** [comment]
thank you very much.
