### ISSUE TITLE
GET to /api/session -> 404

### ISSUE THREAD

**Issue by sunhoww** [tananaev/traccar#2181]
Hi

I don't know whether this is the intended behaviour but...

Whenever I make a `GET` request with basic HTTP auth, the server responds with a status of `404` and a `{}` as the body.

However, I am able to make a `POST` request with the user credentials and have the proper _session_ json responded just fine.

**Comment by tananaev** [comment]
It's a REST API. If you don't have existing session, `GET` would return error 404 (resource not found).

When you do a `POST`, it creates a new session.

**Comment by sunhoww** [comment]
But, isn't that what REST is all about? To not have to maintain a session server-side.

Although, I don't know how the HTTP auth would work out then, when I do try to use websockets.

I'd been using _/api/_session_ to retrieve user info. Evidently that's not how I was supposed to get the info, but `GET` and other methods to _/api/users_ seem to require admin rights.

**Comment by tananaev** [comment]
Yes, sessions are not really REST. You can either use basic auth or you can use session. For websocket though you can only use session at the moment.

To access users, you have to be an admin. It makes sense because with users you get some sensitive information like emails.

**Comment by sunhoww** [comment]
I'll be using websocket, so I should probably be better off using session over http auth. I was concerned about sessions on native mobile apps. Anyways, I'll cross that bridge...

Thanks a lot. It's a great thing your're doing here.

**Comment by tananaev** [comment]
You can take a look at official Traccar Manager apps. Both Android and iOS versions are available and they use sessions and web sockets.

**Comment by sunhoww** [comment]
Yes, I'll do that. Thanks again.
