### ISSUE TITLE
Upgrade from 3.5 to 3.6

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2186]
hi,

Is there anything specific to be done when upgrading from 3.5 to 3.6? Can I just make a backup of the conf file, remove the existing installation by following the below 2 steps

```
Remove traccar from init (sudo /opt/traccar/bin/traccar remove)
Remove traccar directory (sudo rm -R /opt/traccar)
```

And install the new version and update the conf file?

Thanks,
M.M

**Comment by tananaev** [comment]
Yes, that's assuming that you are using external database like MySQL.

**Comment by m-menon** [comment]
cool thanks
