### ISSUE TITLE
WebSocket schema

### ISSUE THREAD

**Issue by sunhoww** [tananaev/traccar#2193]
Hi again.

I can see _/api/socket_ dispatches `positions` and `devices` properties. Referring to the _**AsyncSocket.java**_ src, I see `events` also being dispatched. (java not being a strong suit of mine, I'm not exactly sure how it's being implemented tho.)

- Is it safe to assume that only these three properties are being emitted from this endpoint?
- Also could this be used to send device commands?

**Comment by tananaev** [comment]
Yes, there are up to 3 properties (positions, devices and events). WebSockets are only used for live updated. For commands there is [REST API](https://www.traccar.org/traccar-api/).

**Comment by sunhoww** [comment]
OK. Thanks.
