### ISSUE TITLE
Geofence notifications

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2194]
Hi,

I am trying to use geofence functionality with notifications but no luck so far.  Server version is 3.6.

I added new user with real e-mail (google mail) aadress, then i created couple of geofences and activated notifications (via Mail) like "device has exited geofence" and "device has entered geofence"  So far i have not receive any e-mails to my google mail account mailbox.

Do i misunderstand that functionality or is there some issue with that? 

Another problem is that even if i am logged in as admin i can not uncheck devices under Settings => Users => Devices. At the moment all users sees all devices registred to the server and i can not change it.

**Comment by tananaev** [comment]
Have you configured your SMTP server?

**Comment by tananaev** [comment]
If not, please read following thread:

https://www.traccar.org/forums/topic/smtp-config-for-notifications/

**Comment by argokask** [comment]
Hi,

Thank you for that link, i did not found that before. In "wrapper.conf" i made some changes, is that correct? So far i have not receive eny notifications. 

My purpose is to get some notifications about entering and exiting geofences and also when unit is online and when offline.

# Common Event Email settings.
#wrapper.event.default.email.debug=TRUE
#wrapper.event.default.email.smtp.host=<**smtp.gmail.com**>
#wrapper.event.default.email.smtp.port=25
#wrapper.event.default.email.subject=[%WRAPPER_HOSTNAME%:%WRAPPER_NAME%:%WRAPPER_EVENT_NAME%] Event Notification
#wrapper.event.default.email.sender=<**noreplay@example.com**>
#wrapper.event.default.email.recipient=<**example@gmail.com**>

**Comment by Abyss777** [comment]
Hello, 
You need to make changes in `traccar.xml` config, NOT in `wrapper.conf`

**Comment by argokask** [comment]
Ok, thank you, now it is working.

Is there any solutions for problem i mentioned before?

> 
Another problem is that even if i am logged in as admin i can not uncheck devices under Settings => Users => Devices. At the moment all users sees all devices registred to the server and i can not change it.

**Comment by Abyss777** [comment]
How it is look like? Checkboxes don't work or they appear again after reload? Do you see any errors in browser console?

**Comment by argokask** [comment]
Hi,

I reinstalled server before i read your post, now everything is working fine. Thank you for your time!

**Comment by argokask** [comment]
Unfortunally problem is back again. I opend console but there are no errors. 

Problem discription is following:

Loged in as admin user, i go to "Settings" => "Users" and choose some random no admin rights user to manage what devices that user must see or not see. I see all added devices there and all of them are checked, if i uncheck them and press "x" button and open that "Devices" window again then all of them are checked again. So at the moment all users sees all devices added to the server. Funny is that when i install server then at the beginning there is no such problem but after some time it reoccurs.

Maybe there should be some "Save" button? It seems that server does not acquire new settings in "Devices" window.

I do not remember that problem with older version of Traccar. At the moment i have installed version 3.6.

**Comment by tananaev** [comment]
Check API request in the console when you check or uncheck a device. Specifically check response code and content.

**Comment by argokask** [comment]
I went to the console window and opened "Network" => "XHR". Under that section is assume that i see requests and resopnses.

If i go to "Resopnses" then i see note "This request has no resopnse data available", so i copyd only request header and response header to here.

**Request header:**

DELETE /api/permissions/devices HTTP/1.1
Host: 192.168.1.3:8082
Connection: keep-alive
Content-Length: 25
Origin: http://192.168.1.3:8082
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Content-Type: application/json
Accept: */*
DNT: 1
Referer: http://192.168.1.3:8082/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: et-EE,et;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: JSESSIONID=ycato88dawz81a65sezbubb1f

**Response header**

HTTP/1.1 204 No Content
Date: Thu, 11 Aug 2016 05:18:30 GMT
Access-Control-Allow-Headers: origin, content-type, accept, authorization
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: http://192.168.1.3:8082
Server: Jetty(9.2.17.v20160517)

**Comment by tananaev** [comment]
This looks like a request for unlinking devices. "No Content" response means that the request was successful.

**Comment by argokask** [comment]
Yes, that should be request for unlinking, but again, if i close that window and reopen that then all checkboxes are filled again. Is there someting i can try to fix that problem? Could it be caused by my browser, mayby i should try another browser?

This is request for linking devices.

**Request header**

POST /api/permissions/devices HTTP/1.1
Host: 192.168.1.3:8082
Connection: keep-alive
Content-Length: 25
Origin: http://192.168.1.3:8082
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Content-Type: application/json
Accept: */*
DNT: 1
Referer: http://192.168.1.3:8082/
Accept-Encoding: gzip, deflate
Accept-Language: et-EE,et;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: JSESSIONID=1adam6py3fvnd1ivfytgswgpm2

**Response header**

HTTP/1.1 200 OK
Date: Thu, 11 Aug 2016 06:42:49 GMT
Content-Type: application/json
Access-Control-Allow-Headers: origin, content-type, accept, authorization
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: http://192.168.1.3:8082
Content-Length: 25
Server: Jetty(9.2.17.v20160517)

**Response**

{"userId":2,"deviceId":1}

**Comment by tananaev** [comment]
Does your device have a group? Maybe group is linked to the user?

**Comment by argokask** [comment]
Yes, i am using groups. Now i removed users from group then unchecking works. I did not realise that i can not manage devices inside group.

Thank you for your time.

**Comment by tananaev** [comment]
If user has access to a group, then he has access to all devices in that group.
