### ISSUE TITLE
positions Rest API not working.

### ISSUE THREAD

**Issue by rbniranjan** [tananaev/traccar#2195]
Hi @tananaev,

Thanks for providing the rest API. 

I am developing android manager app using your demo. Every thing is working fine. But When I try to call positions api. I got `protocol=http/1.1, code=400, message=Bad Request` error. We are using retrofit library for sending the request. This is my url that I got from retrofit library.
`api/positions?deviceId=1&from=2016-08-02T10%253A02%253A46.000Z&to=2016-08-05T10%253A32%253A46.000Z`

We are using session based authentication. All other api is working fine.

Looking forward your reply.

**Comment by al3x1s** [comment]
if you unescape that url the result is:  

```
positions?deviceId=1&from=2016-08-02T10%3A02%3A46.000Z&to=2016-08-05T10%3A32%3A46.000Z
```

and you should have an url like this one
```
positions?deviceId=12&from=2016-08-08T15:22:22.000Z&to=2016-08-08T15:52:22.000Z&page=1&start=0&limit=25
```

**Comment by tananaev** [comment]
@al3x1s is right. You are double-escaping URL parameters.

**Comment by rbniranjan** [comment]
Thanks @al3x1s , I successfully implemented positions API.
