### ISSUE TITLE
Log latest heartbeat

### ISSUE THREAD

**Issue by ptrlv** [tananaev/traccar#220]
This is a feature request. I'm using gps103/5001 and the device sends it's IMEI periodically without location info. The traccar server replies with 'ON'. eg.
FINE: [5001 <- 82.132.226.7] - (HEX: 3335393731303034303034343731383b)
FINE: [5001 -> 82.132.226.7] - (HEX: 4f4e)

Can the server please log this 'latest heartbeat' in the devices table?

**Comment by tananaev** [comment]
Connection status is implemented. It's also saved in the devices table.
