### ISSUE TITLE
[FAQ] Why need OpenGTS when we have Traccar ?

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2203]
I have following questions to clarify.

What features makes OpenGTS to integrate with Traccar ?

Why they are not supported in Traccar ?

What new features are in pipeline ?

Any pointer to understand both projects differences and common features in detail ?

Please help me to understand and know traccar better.

Thanks.

**Comment by tananaev** [comment]
> What features makes OpenGTS to integrate with Traccar ?

OpenGTS has some reports that Traccar doesn't at the moment.

> Why they are not supported in Traccar ?

Because we haven't implemented it yet, but we are working on reports.

> What new features are in pipeline ?

Reports is the highest priority.

> Any pointer to understand both projects differences and common features in detail ?

I would recommend to check official websites and demos for both project if you want to compare.
