### ISSUE TITLE
How can a Geofence be linked to a device?

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2205]
hi,

Just had a glance at the Geofence feature. Was wondering how the Geofence is linked to a device or a group of devices? Thanks

**Comment by Abyss777** [comment]
Hello
Geofences can be linked to both devices and groups.

You can see the button above devices list
![image](https://cloud.githubusercontent.com/assets/5688080/17579539/1cf2521a-5fb0-11e6-9575-aa78de40ebb2.png)

The same button is in groups dialog.

**Comment by m-menon** [comment]
Perfect .... thanks :+1:
