### ISSUE TITLE
traccar as backend for leaflet-realtime

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2207]
Hi,

We are using Leaflet in our application, we want to use leaflet-realtime(https://github.com/perliedman/leaflet-realtime) for which we thought traccar as backend to provide location details.

Has anyone done this kind of integration "traccar as backend"?

Please guide me how to do it?

Thanks.

**Comment by tananaev** [comment]
It seems like the library expects GeoJSON. Traccar doesn't return it, but I guess it's possible with some API modifications.

**Comment by kirantpatil** [comment]
Thanks a lot Sir. Please let me know the plan to modify API, what needs to be modified and how?

**Comment by tananaev** [comment]
There is no plan. Source code has to be modified. Please be more specific with your question. I'm not going to write code for you.

**Comment by kirantpatil** [comment]
Yes Sir, what I am asking is pointer to the code where I can try to modify code. But I know it is not straight forward and that is where I need your guidance on how to approach. I am not asking you to write code.

**Comment by tananaev** [comment]
Traccar API code is here:

https://github.com/tananaev/traccar/tree/master/src/org/traccar/api

**Comment by kirantpatil** [comment]
Thanks a lot Sir. I will have a look at it.

**Comment by kirantpatil** [comment]
closing this issue since we will not use leaflet realtime but will use traccar as backend using its default API.
