### ISSUE TITLE
Possible Issue Feedback (Distance in Attributes)

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2208]
Dear All,

The distance option of traccar, which calculates distance between current and past location and updates the distance value in attributes,. Has the following points as per me,.
1. Sometimes when a new device is purchased/activated the location (1st or few updates) might be of a location, of a different country/region/city/area.

Thus when the actual updates start coming from the device, the total distance calculated value in attributes would never be right, and there is no way to fix or make adjustments to it.

I have seen this issue with a lot of devices/brands.

I  can see lot of work and effort being put into development of reports lately on traccar, So I wanted to share this thing I have been noticing/facing.

It might be a good idea, to probably have a way to  get rid of such data/distance value,.

**Comment by tananaev** [comment]
Reports will give you relative distance, so it should be a problem.

I can't think of any good way to solve this problem except for adding a button or something to reset the value.

**Comment by nefertiti007** [comment]
Your point seems good, the ability to reset, This way user can probably from the reset point calculate etc or add their own start value for distance etc.

One way of addressing this in reports,. Could be to calculate per trip (start to stop moving) distance separately? 

How I do it now is,. I take the data between the fixtime required, and calculate distance between each point to the next. and display to the user.

**Comment by tananaev** [comment]
As I said, reports will calculate distance between time interval.

As for the issue, one workaround I can think of, is to remove and device after it gets correct GPS fix.

**Comment by Abyss777** [comment]
I have another idea.
Store distance in device attribute. Logically it is better place. It will be like device odometer and it easy to adjust.

**Comment by tananaev** [comment]
The problem would be to calculate distance for reports then.

**Comment by Abyss777** [comment]
Reports do not rely on DistanceHandler, they recalculate distance.

**Comment by tananaev** [comment]
I didn't know. I think it should rely on it.

**Comment by Abyss777** [comment]
If it is rely on distance handler, then I think after release 3.7 will be a hundred questions:
- Why report shows 0.0 km?
- You have to enable distance handler
- It is OK now for new data, but how to get it for the month ago?
- No way

On the other hand, we have to iterate through all selected positions any way in report, I don't think it is so slow math to throw out.

**Comment by tananaev** [comment]
Well, we can enable it by default (event without config setting). Ideally we also need to use "odometer" value if it's available.

**Comment by jaimzj** [comment]
Resolved in new versions.
