### ISSUE TITLE
Some positions in the database are WAY off

### ISSUE THREAD

**Issue by TwizzyDizzy** [tananaev/traccar#2209]
Hi folks,

I've been meaning to report this for quite some time but only got around to it now. Sometimes, when looking at the map with the positions of the last weeks / months I recognize some positions that can't be real, because I've never been there.

![off](https://cloud.githubusercontent.com/assets/179595/17605745/392c14d6-601c-11e6-81e6-f64d6e3b7e11.jpg)

As you can see, the two positions in the lower left are definately not real.

I am not really sure how to debug this issue because this could be

* the Android GPS provider giving wrong data to the app (GPS provider on the phone - or something low level on the phone - is to blame)
* the app messing up the data and sending it to the server (meaning you know the data from the GPS provider and thereby have the value that came into the app and the value that was going out of the app towards the server) - if the former is different from the latter, the app is to blame
* the server messing up the data after having received the correct data (meaning you know the data that went out of the app and the value that is written into the database) - if the former is different from the latter, the server software is to blame

To debug this in a decent fashion one would have to trace an invalid data point from the GPS provider to the app to the server.

Any ideas how to achieve that?

Not sure, but #1762 could be related to this.

Cheers
Thomas

**Comment by tananaev** [comment]
What provider are you using in the app? GPS only?

**Comment by TwizzyDizzy** [comment]
Yep, GPS only.

**Comment by tananaev** [comment]
Then it must be actual location reported by GPS chip. Have you checked timestamp?

**Comment by TwizzyDizzy** [comment]
What do you mean by that?

**Comment by tananaev** [comment]
Each position has a timestamp value. You can check the time when phone "was" there.

**Comment by TwizzyDizzy** [comment]
Ah yes, the position has a timestamp assigned to it. I mean... it should have, should it not? The issue is not, that I have been at that location earlier or later than what is displayed, but rather, that I have **never** been there.

**Comment by tananaev** [comment]
It must be some phone issue then. Traccar doesn't modify coordinates. It reports whatever your phone returns.

**Comment by TwizzyDizzy** [comment]
Damn it... I feared this to be a GPS chip / OS issue... thanks anyway for your time :+1: !
