### ISSUE TITLE
 Event Overspeed (Configuration per device instead of global)

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2213]
Dear All,

I believe if am not wrong overspeed limit value is to be set in config file which is common /applicable to all devices right?

However, What if in the case, where per device someone needs to set the overspeed limit
use case
1. Different vehicle types,. With different engine/speed capabilites and limitations.

**Comment by Abyss777** [comment]
Hello, @nefertiti007 

You are right.
You have yet another reason to wait next release, because it is already implemented :)

Speed limit moved from config file to objects attributes, that means that you can set speed limit for device/group/server and set it via web-interface.

**Comment by jaimzj** [comment]
Implemented.
