### ISSUE TITLE
Alarms organization

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#2217]
Here is rest protocols list to organize alarms

- [x] Idpl - alarm is SOS 
- [x] Xexun - documentation exist, but do not have alarms explanation
- [x] Tytan - no documentation
- [x] Tzone - have documentation
- [x] T800x - no documentation
- [x] Megastek - has 3 subprotocols, but documentation only for 2
- [x] Kenji - no documentation
- [x] Huabao - have documentation
- [x] Eelink - have documentation

@tananaev if you don't mind I'll use this issue to trace progress and ask you something.

**Comment by tananaev** [comment]
Sure, it's better than email.

**Comment by al3x1s** [comment]
for tzone, is this what you need?

[TZ-AVL19 user guide 1.0.9.en.pdf](https://github.com/tananaev/traccar/files/418244/TZ-AVL19.user.guide.1.0.9.en.pdf)

**Comment by Abyss777** [comment]
@al3x1s thanks, original manual is more credible then excel file.

**Comment by nefertiti007** [comment]
[Concox GT06F communication protocol (1).pdf](https://github.com/tananaev/traccar/files/419684/Concox.GT06F.communication.protocol.1.pdf)

[Wetrack2_GPS Tracker Communication Protocol_v1.8.6.pdf](https://github.com/tananaev/traccar/files/419683/Wetrack2_GPS.Tracker.Communication.Protocol_v1.8.6.pdf)

Attaching Two GT06 Protocols, GT06f is the latest with fuel/voltage
and Wetrack2 (GT06) Basic protocol

Hope this helps? for GT06 Protocls Alarm

**Comment by Abyss777** [comment]
thanks @nefertiti007 
I'll try to implement Alarm messages for GT06

**Comment by tananaev** [comment]
Added T800x, new Megastek format and Kenji documents:

https://www.traccar.org/protocols/

**Comment by Abyss777** [comment]
Looks like organization is finished.

**Comment by nefertiti007** [comment]
@Abyss777 & @tananaev 

In GT06 Protocol document available on traccar site, page 19, there is a alarm value for cut off, can this also be added in?

`0x02: Power Cut Alarm`
