### ISSUE TITLE
Fuel units in protocols

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#2218]
Here is list

- Gl200 - no information about units
- Meitrack - % of tank
- Fox - no documentation
- Stl600 - no information about units
- Noran - no information, but looks like %
- Jt600 - no information, two-bytes value
- Tytan - liters or %
- T55 - no information
- Mta6 - stores in liters
- Intellitrac - no information about units, some number
- Galileo - % of tank
- Atrack - no documentation, may be %
- Aquile - no documentation

Bad situation, I have no idea how to get "spent fuel" for reports from this data.

**Comment by tananaev** [comment]
For start I think we can handle protocols that report percentage. Ignore others for now. We'll add more with time.

For GPS103 please change key to something else. Consumption is different thing and I think we already have a key for it somewhere.

**Comment by Abyss777** [comment]
What will be units of "spent fuel"? We need to know volume of device tank to convert % to liters/gallons?

**Comment by tananaev** [comment]
We can just show percentage.
