### ISSUE TITLE
device is not acting against command sent via api

### ISSUE THREAD

**Issue by mrameezraja** [tananaev/traccar#2229]
I am using below method to send command to device via traccar api which return `OK` response same as input , but the device is not responding against command. If i send the same command via sms it works like a charm.
<pre>
    var username = "admin";
    var password = "admin";
    $.ajax({
        url: "http://[URL]:8082/api/commands",
        dataType: "json",
        contentType: "application/json",
        type: "POST",
        data: JSON.stringify({
            deviceId: 3,
            type: "custom",
            attributes: {
                data: "led123456 on"
            }
        }),
        beforeSend: function (xhr) {
            xhr.setRequestHeader ("Authorization", "Basic " + btoa(username + ":" + password));
        },
        success: function(res){
            console.log(res);
           // res => { deviceId: 3, type: "custom", attributes: { data: "led123456 on" } }
        }
    });
</pre>

**Comment by tananaev** [comment]
Often commands are different for SMS and GPRS.

**Comment by al3x1s** [comment]
could You check in the traccar log if the device send feedback,

I have sent commands to totem protocol and the device's feedback only shows in the traccar log, but the device receive the command properly

**Comment by mrameezraja** [comment]
Here is the log when i send the command:

2016-08-22 08:21:04 DEBUG: [D0FB7008: 5093 > 202.69.12.131] HEX: 4c6564313233343536206f6e 

[Hex to String: Led123456 on]

**Comment by tananaev** [comment]
Have you read my comment above? There is a good chance that format should be different.

**Comment by mrameezraja** [comment]
@tananaev yes. Format is same for both GPRS/SMS.

**Comment by tananaev** [comment]
If you are sure, then it should work. HEX in the log means that command has been sent to the device. How are the command separated from each other? TCP is a stream protocol. How would device know when a command ends?

**Comment by mrameezraja** [comment]
@tananaev  You were right. After many queries i got response from vendor. GPRS command is different i.e `[SG*<IMEI>*0008*LEDSET,1]`. Issue resolved. Thank you :)
