### ISSUE TITLE
Lat Lng capture issue from Mobile network

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2236]
Hi,

I enabled the tracking myself from my Home and it updated 4 different lat lng to the server.

The error range of lat lng captured is in from 500 m to 3 km. 

I am using TATA DOCOMO network provider service in India .

May I know how to minimize this error rate of lat lng ?

What are the steps do I need to take to get  accurate Lat Lng of the position ?

Please find the attached screenshot.

Thanks.

![latlng issue_screenshot from 2016-08-22 18 00 53](https://cloud.githubusercontent.com/assets/1178055/17854951/6c5282da-6893-11e6-8b56-246bcc50270b.png)

**Comment by tananaev** [comment]
What device are you using?

**Comment by kirantpatil** [comment]
I am using Samsung DUOS (Model GT-S7562) Android(Version 4.0.4) mobile with Traccar Client 3.11

**Comment by tananaev** [comment]
I guess that you are using network location provider. To get accurate location, you need to use GPS.

**Comment by kirantpatil** [comment]
Yes, I was using Network provider as Location provider. I will try using GPS.

**Comment by kirantpatil** [comment]
Sir. Yes, Now it is showing accurate Lat lng with GPS enabled. Thank you.
![latlng -screenshot from 2016-08-23 05 03 06](https://cloud.githubusercontent.com/assets/1178055/17875355/2bcfdfa8-68ef-11e6-8391-f3afd13ddd9c.png)
