### ISSUE TITLE
KEY "position_deviceid_fixtime" ("deviceid","fixtime")

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2244]
hi, was looking at the positions table and saw this in positions table `KEY "position_deviceid_fixtime" ("deviceid","fixtime")`. Just curious - is the above key to prevent trackers from inserting duplicate records? thnks

**Comment by tananaev** [comment]
It's for searching, and it's not unique, so you should be able to insert records with same timestamp.

**Comment by m-menon** [comment]
Alright, thanks a lot
