### ISSUE TITLE
Trip detector algorithm

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#2251]
I tested a bit on other device and reach a deadlock, can't decide.

Here is exaggerated example of speed graph:
![image](https://cloud.githubusercontent.com/assets/5688080/17957330/47fb9d54-6aaa-11e6-8531-7e26b903134d.png)

What is this?
1. Parking period with two too small trips that should be filtered (4 minutes duration)
2. 3 minutes trip with small stop in the middle

1. Can cause cut real trip at the beginning and at the end
2. Can cause false trips.

My first version was 2 and now it is 1.  But I want come back to 2 again.

@tananaev what do you think?

**Comment by Abyss777** [comment]
Or just made it configurable? "Greedy parking" vs. "greedy trips"

**Comment by Abyss777** [comment]
One more example
![image](https://cloud.githubusercontent.com/assets/5688080/17960117/9094a5a2-6abd-11e6-8e19-961aa30a6405.png)
**Note:** C-D is more than minimal parking duration
A-B and E-F less than minimal trip duration

1. Variant says it is two trips **B-C** and **D-E**
2. Variant says it is one trip **A-F**

**Comment by tananaev** [comment]
I think it's a good idea to make it configurable.
