### ISSUE TITLE
Show all Reports Options in demo site

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2259]
Hi,

Right now I could see only below columns for Reports in view.
Valid, Time, Latitude, Longitude, Altitude, Speed and Address

Can you please enable all fields of Reports, so that I can select and check all options reading ?

Thanks.

**Comment by tananaev** [comment]
What "all" options are you talking about?

**Comment by kirantpatil** [comment]
Sir, things like Distance travelled and I don't what other parameters available to display.

**Comment by tananaev** [comment]
There can be 50 or more parameters. Where do you want to show all of them?

**Comment by kirantpatil** [comment]
Can it be categorize them something like Distance related, Trip related options and push them to select in some sort side bar like how right now Reports is shown.

**Comment by tananaev** [comment]
They show up in state table.

**Comment by kirantpatil** [comment]
Right now I could see 11 attributes shown. I believe we can expose rest of the attributes there.

**Comment by tananaev** [comment]
Have you actually read my comment? All attributes are displayed in the "State" table.

**Comment by kirantpatil** [comment]
Yes Sir. What I mean was as shown in attached screenshot, regarding State view.

![screenshot from 2016-08-27 11 04 26](https://cloud.githubusercontent.com/assets/1178055/18025436/c498e96e-6c46-11e6-9258-70b0596a91d5.png)

**Comment by tananaev** [comment]
It means that your device doesn't send more attributes.

**Comment by kirantpatil** [comment]
I am using Android mobile. 
Do I need to enable/configure any advanced setting in mobile so that it sends other details ?

**Comment by tananaev** [comment]
Do you mean Traccar Client? It can send only basic information. If you run your own Traccar server, you can configure it to calculate distance on the server side which will also show in attributes.

**Comment by kirantpatil** [comment]
Ok, I will create new server and check it.

Thank you.
