### ISSUE TITLE
Help port GPS device

### ISSUE THREAD

**Issue by condeitokako** [tananaev/traccar#2260]
I might indicate that port can occupy this gps or is currently supported traccar.

http://gpsgate.com/devices/careu_u1

**Comment by condeitokako** [comment]
traccar try to connect to the server and log that throws me is this 08/26/2016 11:39:55 DEBUG : [ 0FEDB0B3 : 5037 < 187 210 189 240 ] HEX: 0007000200014153502d15ec00ab000610273310081a

**Comment by condeitokako** [comment]
try several ports and any changes the message hex

**Comment by condeitokako** [comment]
here is the protocol sheet of the https://nomadicsolutions.biz/wp-content/uploads/dlm_uploads/2014/12/UX-Protocole.pdf

**Comment by condeitokako** [comment]
As currently 10 of these had them saved and I would like to engage them in traccar

**Comment by tananaev** [comment]
ASCII version of the protocol is supported by Traccar. It's called Wondex and works on port 5032.

**Comment by condeitokako** [comment]
I worked very well , commands a question engine stop and reset are not yet supported for this protocol?

**Comment by tananaev** [comment]
No, not yet.

**Comment by condeitokako** [comment]
Thank you very much for the help of settings and I can fill slope will be, for commands , Greetings
