### ISSUE TITLE
How to update to lastest traccar

### ISSUE THREAD

**Issue by onethings** [tananaev/traccar#2261]
Hi,
    I have download https://github.com/tananaev/traccar/archive/master.zip and generate tracker-server.jar . Also replace with /opt/traccar/tracker-server.jar and replace with web folder from master.zip to /opt/traccar/web  .  Run (sudo /opt/traccar/bin/traccar start )  Traccar is running, but in browser not display  anything.  What i have missing in configuration.

Thank you very much!

**Comment by tananaev** [comment]
You need a lot of things. Web interface files (you need to compile those or use debug mode), database schema and new config.

**Comment by onethings** [comment]
Ok, Thanks.
