### ISSUE TITLE
get last position of a device

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2268]
Hi,

I am using below code to get position of device but it has not returned last position.

May I know what API to be used to get last position of Device ?

```
<!DOCTYPE

 html>
<html>
  <head>
    <meta charset="utf-8">
    <title>try traccar api</title>
  </head>
  <body>
    <script src="js/jquery-2.2.2.min.js" charset="utf-8"></script>
    <script type="text/javascript">
      var name = "kiran";
      var uid = "355355059774397";
      $.ajax({
        type: 'get',
        url: 'http://demo.traccar.org/api/positions/',
        headers: {
            "Authorization": "Basic " + btoa("username" + ":" + "password")
        },
        contentType:"application/json",
        data:JSON.stringify({
          name:name,
          uniqueId:uid
        }),
        success: function (response) {
            console.log(response);
        }
      });
    </script>
  </body>

 </html>
```
Returned lat lng details as shown in below screenshot, 
latitude:13.09821752
longitude:77.56231934
![screenshot from 2016-08-29 15 00 45](https://cloud.githubusercontent.com/assets/1178055/18047237/7069ca48-6df9-11e6-800c-c292ca7ac3db.png)

Last Lat lng details at demo server as shown in below screenshot:
latitude: 13.098218
longitude: 77.562319
![screenshot from 2016-08-29 14 57 12](https://cloud.githubusercontent.com/assets/1178055/18047238/71e4b004-6df9-11e6-9ac4-3f34de3fcfb7.png)

**Comment by tananaev** [comment]
Why do you have "data" in your request? Are you sure you are looking at the same device at the exact same moment in time?

**Comment by kirantpatil** [comment]
Yes Sir, I have only one device configured in that account. 

I removed the "data" and sent request and result is still same.

**Comment by kirantpatil** [comment]
I have only one device and its id is deviceId:28970

**Comment by tananaev** [comment]
OK, can you give me connection details so I can check it myself?

**Comment by kirantpatil** [comment]
Sir, Please find the username and password as below.
USERNAME: kirantpatil1@gmail.com
PASSEWORD: kiran123

**Comment by tananaev** [comment]
This is the results I see:

In the web interface: 2016-08-29 20:06:18 (this is local time UTC+12)
Directly via API call: 2016-08-29 08:06:18 (this is UTC time)

Everything is correct as far as I can tell.

**Comment by kirantpatil** [comment]
But why it is showing different latlng while accessed from API.

**Comment by tananaev** [comment]
For me it returns exactly the same data.

**Comment by kirantpatil** [comment]
Not an issue so closing this issue.
