### ISSUE TITLE
User Devices

### ISSUE THREAD

**Issue by ninioe** [tananaev/traccar#2278]
The user devices display wrong devices
![image](https://cloud.githubusercontent.com/assets/8347415/18162688/1bca6bde-7040-11e6-9fbc-e3b840229be3.png)

in BasePermissionsController.js line 39 the store find return the wrong index:
![image](https://cloud.githubusercontent.com/assets/8347415/18162989/6ebe37fc-7041-11e6-84cf-fe8c82415f51.png)

Also, a primary index is missing on "user_device" table (on fields: userid, deviceid)

**Comment by tananaev** [comment]
> The user devices display wrong devices

Are you sure you haven't changed the checkboxes? It doesn't update devices automatically. You need to refresh the page.

> in BasePermissionsController.js line 39 the store find return the wrong index

I need more details (service call responses).

> Also, a primary index is missing on "user_device" table

It's a small table with only two fields. It doesn't need index.

**Comment by Abyss777** [comment]
Seems I know where is the problem, I'll prepare pull request.

**Comment by Abyss777** [comment]
@ninioe please test #2279

**Comment by ninioe** [comment]
Thanks @Abyss777 now it woks OK
