### ISSUE TITLE
Coban GPS105-A  

### ISSUE THREAD

**Issue by thaihaha** [tananaev/traccar#2280]
I bought a Coban GPS105A
The product work with the GPS Server Tracker Home by the provider, but i want to use Traccar.

I try on port 5001 & 5002 but no have result .

pls help me.

my experience , before I use GT06 is ok in database show all record.

but now I test Coban GPS105A no have any record.

**Comment by tananaev** [comment]
Please don't spam everywhere with your question. You already asked on forum. There is no need to duplicate it here.

**Comment by thaihaha** [comment]
I am sorry
