### ISSUE TITLE
"watch" protocol device not responding to all commands

### ISSUE THREAD

**Issue by marko89kv** [tananaev/traccar#2285]
Hi, I have this device - http://www.3g-elec.com/uploadfiles/image/201603/163.jpg (G69), and after getting some documentation from a re-seller, I've figured out it runs on "watch" protocol. The problem is - it doesn't respond to all of the commands. Rebooting, shutting down, "sending flowers", sending texts works fine, but more advanced stuff like - setting up the SOS numbers, turning on/off the alerts for taking the bracelet off or SOS alert do not work. For the commands that are working, the watch responds with appropriate codes (I can see in the tracker-server.log), but for the other commands, it doesn't respond at all, I see my command sent, and the watch doesn't return anything.
Could this be an issue with an upgraded protocol/not getting the correct documentation, or something else?

Thank you.

**Comment by tananaev** [comment]
Have you tried to compare what you see in the logs to what the documentation says?

**Comment by marko89kv** [comment]
Yes, and for an example - sending [SG*_deviceid_*0010*SOS1,_phonenum_] returns the same string, instead of [SG*_deviceid_*0010*SOS1]
My protocol document is very similar to what you have on traccar website.
Here it is:
[CommunicationProtocol.pdf](https://github.com/tananaev/traccar/files/453856/CommunicationProtocol.pdf)

Thank you for responding in such a short notice.

**Comment by tananaev** [comment]
So, what do you see in the logs?

**Comment by marko89kv** [comment]
This is an example of the shutdown command and watch answer, which works:

```
2016-09-04 14:36:46 DEBUG: [DED569EE: 5093 > 109.166.128.51] HEX: 5b53472a363130353137383337342a303030352a52455345545d
2016-09-04 14:36:48 DEBUG: [DED569EE: 5093 < 109.166.128.51] HEX: 5b33472a363130353137383337342a303030352a52455345545d
```

After the watch rebooted, normal communication continues:

```
2016-09-04 14:36:46 DEBUG: [DED569EE: 5093 > 109.166.128.51] HEX: 5b53472a363130353137383337342a303030352a52455345545d
2016-09-04 14:36:48 DEBUG: [DED569EE: 5093 < 109.166.128.51] HEX: 5b33472a363130353137383337342a303030352a52455345545d
2016-09-04 14:37:07  INFO: [6D263CA3] connected
```

But, if you send this, for example:

`2016-09-04 14:39:34 DEBUG: [6D263CA3: 5093 > 109.166.129.122] HEX: 5b53472a363130353137383337342a303031302a534f53312c303734313232393138395d`

there is no response from the watch whatsoever, I'm looking at the log with tail -f, there is no response from the watch.

**Comment by tananaev** [comment]
The command format looks fine. I guess there is something with the device.

**Comment by marko89kv** [comment]
Thank you, I'll close the issue and wait for an answer from the resseler.

**Comment by tananaev** [comment]
OK, please post any updates if you get an answer from the reseller.

**Comment by marko89kv** [comment]
Hi, figured it out, my fault, I didn't pay attention to the length parameter in commands... For every message, you have to acquire it's length and convert it to hex:

Example:
`[CS*YYYYYYYYYY*LEN*UPLOAD, time interval]`
`[SG*8800000015*0009*UPLOAD,10]`

"Upload,10" is 9 characters long, so, convert to hex - 9, or 0009.

If it was UPLOAD,300, LEN would be 0010.

**Comment by tananaev** [comment]
Thanks for sharing the info.
