### ISSUE TITLE
Processing DEBUG message / response from devices

### ISSUE THREAD

**Issue by marko89kv** [tananaev/traccar#2291]
Hello,

is there a way in which we can process DEBUG message, interpret them and save them somewhere in the DB? For an example, my device has the function for checking pulse:

I would send this to it: 
`[CS*YYYYYYYYYY*LEN*PULSE]`,
and the device would respond with the following, which I see in the logs:
`[CS*YYYYYYYYYY*LEN*PULSE,72]`

Thank you.

**Comment by tananaev** [comment]
Any messages that have valuable information in them, should be decoded into `Position` model.

**Comment by marko89kv** [comment]
I understand. I was asking because the device that I'm using, with "watch" protocol doesn't record SOS events in the database. Probably I should get the source code and add missing things from WatchProtocolDecoder and WatchProtocolEncoder?

**Comment by tananaev** [comment]
Decoding should be in `WatchProtocolDecoder`. Please send a pull request if you manage to add it.

**Comment by marko89kv** [comment]
Thank you. I'm looking at it right know, but I have one more quick question:

Inside `WatchProtocolDecoder`, on line 112, where you have implemented the processing of AL (alarm) command, it only has the response to the command `sendResponse(channel, manufacturer, id, "AL");`
Could you point me in the direction of some other protocol in the source code where you have implemented events into responding? So the alarm can be saved under 'events' in the DB. If I manage to implement it locally, I'll send a pull request so it can be added.

Thank you.

**Comment by tananaev** [comment]
You can take a look at `decodeAlarm` method in `Gps103ProtocolDecoder` for an example.

**Comment by marko89kv** [comment]
Thank you, I will update you with my progress.

**Comment by marko89kv** [comment]
I took a look at your example. So when `position.set(Position.KEY_ALARM, decodeAlarm(alarm));` is called, it just adds the alarm as an additional attribute to the position row data, it's not saved in events?

**Comment by tananaev** [comment]
Yes, but it will generate event later in the chain.

**Comment by marko89kv** [comment]
Ok, perfect.

**Comment by Abyss777** [comment]
https://github.com/Abyss777/traccar/commit/b4185cbf84bdff2927f7d9a8b0cde9f4ea889353

Just stores pulse as "pulse" attribute, If you need event, it can be treated as command result (it is really looks like command result).
I can make a pull request, what is better "pulse" or "result?

**Comment by tananaev** [comment]
Can we make it both? A command result with "pulse" attribute.

**Comment by atulbothe** [comment]
Hello,

Sorry commenting on a old thread, some manufacturer use "heart" instead of "Pulse" [as below], do you think it is possible to add a check for "heart" or "pulse" so that traccar handles both?

[3G*YYYYYYYYYY*LEN*heart,72]

Thanks,
Atul

**Comment by tananaev** [comment]
Please create a separate thread for it. We would need an official documentation for it as well.

**Comment by atulbothe** [comment]
Thanks. I have created a new issue and attached the documentation from manufacturer to the issue.

https://github.com/tananaev/traccar/issues/3171

Thanks,
Atul
