### ISSUE TITLE
 Null Address in v3.5

### ISSUE THREAD

**Issue by cadastro2005** [tananaev/traccar#2292]
positions a day ago were filled with the address, but this morning all addresses are being persisted null, anyone know why ?

**Comment by nefertiti007** [comment]
Please check which reverse-geocoder service provider you have configured.
You might have exhausted your daily query limits (Set by the reverse-geocode provider).

**Comment by cadastro2005** [comment]
@nefertiti007 

the settings below ?
 
<entry key='geocoder.enable'>true</entry>
 <entry key='geocoder.type'>google</entry>
 <entry key='geocoder.key'>********************</entry>
 <entry key='geocoder.processInvalidPositions'>true</entry>

**Comment by nefertiti007** [comment]
When you queried, the above URL/web-service of Google, The reason it worked could be you directly queried it using a browser to test,. So the source is different from that as your Traccar Server.

**Comment by cadastro2005** [comment]
@nefertiti007  
what can I do now to activate the service with the key?

**Comment by nefertiti007** [comment]
Even with a key, you will hit the same limitations.

1. You can either enable billing, which might not be the very best/cost effective solution.

Alternatively,. 

You could use open source reverse geocode providers, such as nominatim, gis graphy etc, setup your own instance of nominatim and query that particular server.

*Using nominatims own web-services would still have query limitations.

**Comment by cadastro2005** [comment]
@nefertiti007

**Comment by tananaev** [comment]
If you get null result from Google, it usually means that you hit the limit or you have been blocked for some other reason. If you have a business license, you should contact Google for support.

**Comment by cadastro2005** [comment]
@tananaev  @nefertiti007 

I changed to other geocoder and continues with null address . ( Https://www.traccar.org/reverse-geocoding/ )

Very strange.

**Comment by tananaev** [comment]
Which other geocoder are you using?

**Comment by cadastro2005** [comment]
@tananaev 

I changed to "Nominatim".

**Comment by tananaev** [comment]
What Nominatim server are you using? I hope not their free one? It won't work.

**Comment by cadastro2005** [comment]
@tananaev 
I'm using this url in settings : http://nominatim.openstreetmap.org/reverse.  And even changed geocoder settings, remains null address. What would you recommend ?

I have key only pay on google and the google still does not work .

**Comment by tananaev** [comment]
That Nominatim server won't work because they already blocked Traccar because people overused it. You either need to host your own instance or use one of the paid ones.

If you are using paid Google account, you should be able to get support from them to solve the issue.

**Comment by cadastro2005** [comment]
@tananaev 

You recommend some other geocoder only to test ?

**Comment by tananaev** [comment]
You can try Gisgraphy.

**Comment by cadastro2005** [comment]
@tananaev 

I changed to Gisgraphy and restarted the service and still continues with null address . Very strange.

**Comment by tananaev** [comment]
You can try other options. I have provided you the page with full information.

**Comment by tananaev** [comment]
Are you sure you device reports "valid" location?

**Comment by cadastro2005** [comment]
@tananaev 
Yes. all positions are valid .

**Comment by cadastro2005** [comment]
@tananaev 

the problem continues even changing to any other service provider. =(

**Comment by tananaev** [comment]
If it's null, it can only mean one of two things:

1. It's an invalid position, so it's ignored
2. Your provider doesn't return address

**Comment by cadastro2005** [comment]
I made another approach , only using geocode when it is really necessary, but thank you very much for your attention.
