### ISSUE TITLE
Command without result.

### ISSUE THREAD

**Issue by cadastro2005** [tananaev/traccar#2293]
The latest version of traccar am sending stop command to the CRX1 (gt06) tracker and the command is sent successfully , but the vehicle does not stop. I noted in the log that there is no error and there is no log record of the command sent . In version 3.5 and 3.6 every command sent was entered in the log. Does anyone have any idea why is not blocked and is not showing up in log and still sends the command successfully ?

**Comment by tananaev** [comment]
Are you sure device was connected and you got "commands successfully sent" message in the web interface? I'm assuming that you are using default web interface to send commands, right?

**Comment by tananaev** [comment]
Are you sure device was connected and you got "commands successfully sent" message in the web interface? I'm assuming that you are using default web interface to send commands, right?

**Comment by tananaev** [comment]
Are you sure device was connected and you got "commands successfully sent" message in the web interface? I'm assuming that you are using default web interface to send commands, right?

**Comment by tananaev** [comment]
Are you sure device was connected and you got "commands successfully sent" message in the web interface? I'm assuming that you are using default web interface to send commands, right?

**Comment by cadastro2005** [comment]
@tananaev 

I'm using an alternative interface, but the process of sending the command to API is successful, being the same type that was doing in versions 3.5 and 3.6 .

**Comment by tananaev** [comment]
What's the response from API?
