### ISSUE TITLE
Astra Protocol

### ISSUE THREAD

**Issue by karls4** [tananaev/traccar#2300]
Hi, Im using the Astra AT210 with the system. If I check the database it doesnt record the address and valid is set to false. If I connect my mobile phone to the app it get the address just fine and valid is set to true.

Is there anything I can do to check whats going wrong? There doesnt seem to be any errors in the log.

**Comment by tananaev** [comment]
Astra messages were never marked as valid before. Fixed the problem now.

**Comment by karls4** [comment]
Is there anyway for me to get the addresses to show?

**Comment by tananaev** [comment]
Wait for next release. It's going to happen very soon and it will include the fix.
