### ISSUE TITLE
In ReportController move columns outside of method

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#2301]
@Abyss777,

Not a critical issue, but I think it's better to move `routeColumns`, `eventsColumns`, `summaryColumns` and `tripsColumns` into the class instead of creating new arrays/objects every time `onTypeChange` method is called.

**Comment by Abyss777** [comment]
Sure, where is better place to store these classes?

**Comment by tananaev** [comment]
Let's discuss it a bit later. I need to finish with release first. Just adding ideas to github so we don't forget it.

**Comment by tananaev** [comment]
I think we can just keep them as member variables outside of the method.
