### ISSUE TITLE
Idea for attributes improvement

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#2302]
@Abyss777, this is for the next release.

I think it would be nice to allow users to make aliases for position attributes. It would solve problem with translating all attributes. It will also solve problem of having meaningful names for sensors.

**Comment by Abyss777** [comment]
For future discussion:
How will we connect aliases? To device, protocol or to user? All options have their pros and cons.
Will it be just aliases to show attributes, or rules to replace attributes names before store to DB?

**Comment by tananaev** [comment]
I think just aliases to display data in the web interface. I guess the easiest option is to set it per device. Not sure if we should store them in the device attributes or maybe it's better to create a separate table. What's your thoughts?

**Comment by Abyss777** [comment]
If the aim is just translate and meaningful names, I suggest separate table with something like:
`deviceId` - `oldName` - `newName`. or may be `deviceId` - `substitutions` where substitutions is json like attributes. And make substitutions on web side.

But I think about killing two birds with one stone. There is some protocol/devices with configurable output/inputs or different models with the same protocol but have different meaning of inputs.
For example device1.in1 is ignition, device2.in1 is vibration sensor. If we just translate it we can not handle them as ignition or alarm event, but if we substitute/add them before store to DB we can handle it like ordinary events. Or is it another task and we should not mix them?

**Comment by tananaev** [comment]
I think it's two different problems. In this issue I was thinking only about what we display in the web interface.

**Comment by Abyss777** [comment]
OK.
I have difficulty with naming.
table name: `device_translation`
fields:
- long: `deviceId`
- string(json) : `translation`
It will be OK?

**Comment by tananaev** [comment]
I'm thinking `device_aliases` or something like that with 3 columns:
- deviceId
- key
- alias

**Comment by Abyss777** [comment]
Aliases is better.
I need to start coding to figure out what is easier to access: plane list (key-alias) or objects list (aliases)
On the first sight `aliasStore.getById(deviceId).get('key')` is easier, but I'm not sure.

**Comment by Abyss777** [comment]
`Key` is reserved word for MySQL. I'll use `attribute`. OK?

**Comment by tananaev** [comment]
Sounds good to me.

**Comment by Abyss777** [comment]
Where will we place button to edit aliases and how we will name it? "Attributes Aliases" or just "Aliases"?

![image](https://cloud.githubusercontent.com/assets/5688080/18738662/315c5566-80b7-11e6-8557-060b1538ef95.png)

**Comment by tananaev** [comment]
Maybe just additional button in the settings menu? Then have a dialog with device combo box, attribute name and alias. This would be the simplest option I guess.

**Comment by Abyss777** [comment]
Will we do lookup attribute to replace with alias as it is in position or after capitalizing?
https://github.com/tananaev/traccar-web/blob/master/web/app/view/StateController.js#L104
Or may be case insensitive?

**Comment by tananaev** [comment]
Good question. I think we should use case-sensitive original lower-camel-case format. As soon as we release this feature, we can remove the code that capitalises first letter because users would have an option to assign alias.

By the way, I just got an idea. We can put a button to add alias somewhere in the State panel.

**Comment by Abyss777** [comment]
Agree.

Nice idea. I'll keep it in mind while implementing.

**Comment by Abyss777** [comment]
Looks like it inherits blue color from something (like zoom buttons) ... is it OK?

![image](https://cloud.githubusercontent.com/assets/5688080/18776400/7c3247d2-8182-11e6-84f5-44c43b77f864.png)

**Comment by tananaev** [comment]
I think it's OK. I'm actually thinking of moving "settings" button into the map top bar, so it's going to have same color.

**Comment by Abyss777** [comment]
I think it can be closed by https://github.com/tananaev/traccar/pull/2354 and https://github.com/tananaev/traccar-web/pull/287
