### ISSUE TITLE
H2 Database managing tools

### ISSUE THREAD

**Issue by akamomer** [tananaev/traccar#2306]
Dear, I downloaded database.mv.db file and then I tried to use some clients to read the file, but none of them read it, only shows 2 databases (public and information schema).

Is there any special command to use for this file?
<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/21143005/18414757/e2cfe5d8-77de-11e6-9dba-f6c999f995f8.png">

**Comment by tananaev** [comment]
I guess it means that your database is empty.

**Comment by akamomer** [comment]
no its not empty, the database contains data (I also viewed it in notedpad++) but it can't be read using client.
Any way, can I change H2 database to MySQL now? or I need to fresh install?

Thanks for your help

**Comment by akamomer** [comment]
I also got this error while changing to mysql:

STATUS | wrapper  | 2016/09/11 21:44:59 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2016/09/11 21:44:59 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2016/09/11 21:44:59 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2016/09/11 21:44:59 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2016/09/11 21:44:59 | 
STATUS | wrapper  | 2016/09/11 21:44:59 | Launching a JVM...
INFO   | jvm 1    | 2016/09/11 21:44:59 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 30; columnNumber: 101; The reference to entity "autoReconnect" must end with the ';' delimiter.
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at java.util.XMLUtils.load(XMLUtils.java:76)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at java.util.Properties.loadFromXML(Properties.java:868)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at org.traccar.Config.load(Config.java:29)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at org.traccar.Context.init(Context.java:127)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:30)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: Caused by: org.xml.sax.SAXParseException; lineNumber: 30; columnNumber: 101; The reference to entity "autoReconnect" must end with the ';' delimiter.
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(XMLDocumentFragmentScannerImpl.java:1844)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3058)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:338)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at java.util.XMLUtils.getLoadingDoc(XMLUtils.java:102)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	at java.util.XMLUtils.load(XMLUtils.java:74)
INFO   | jvm 1    | 2016/09/11 21:45:00 | WrapperSimpleApp Error: 	... 10 more
STATUS | wrapper  | 2016/09/11 21:45:02 | <-- Wrapper Stopped

**Comment by cetabio** [comment]
Im not an expert but I would say some grammar error in your configuration changes. 

`The reference to entity "autoReconnect" must end with the ';' delimiter.`

**Comment by tananaev** [comment]
For H2 database make sure you are using same driver version as Traccar.

As for MySQL, as @cetabio says, there is an issue with your config file.

**Comment by akamomer** [comment]
I solved, I used &amp; instead of & thanks for your help.
