### ISSUE TITLE
Draw route of trip on click

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#2309]
Feature request is to draw route of trip on map when you select a trip in report table.

**Comment by tananaev** [comment]
Agree, this would be a nice addition.

**Comment by Abyss777** [comment]
Implemented in https://github.com/tananaev/traccar-web/pull/292

**Comment by Prabhasuji** [comment]
how to create  trip in traccar. and  need ah table details.

**Comment by tananaev** [comment]
You don't create a trip. It's automatically calculated from location history.
