### ISSUE TITLE
Traccar web platform - Adding attributes doesn't work

### ISSUE THREAD

**Issue by marko89kv** [tananaev/traccar#2315]
When going to "Settings" => "Account" => "Attributes" and adding something as an attribute to the user, and saving - after logging out and logging in, the attributes list is empty.

**Comment by tananaev** [comment]
Are you sure you are using correct config file?

**Comment by marko89kv** [comment]
In traccar.xml only the part for mysql connection instead of the default H2 was changed, nothing else.

**Comment by tananaev** [comment]
OK, can I see `database.updateUser` query from your config?

**Comment by marko89kv** [comment]
Sure:

```
<entry key='database.updateUser'>
        UPDATE users SET
        name = :name,
        email = :email,
        admin = :admin,
        map = :map,
        distanceUnit = :distanceUnit,
        speedUnit = :speedUnit,
        latitude = :latitude,
        longitude = :longitude,
        zoom = :zoom,
        twelveHourFormat = :twelveHourFormat
        WHERE id = :id;
    </entry>

```
Should I add `attributes = :attributes` ?

**Comment by tananaev** [comment]
That's not correct query. Why did you say that it's correct? Yes, you need to add attributes there.

It seems like you are using old config. When you update Traccar, you need to update config as well. You can't just keep using old one.

**Comment by marko89kv** [comment]
Ok, I will update. I'm using version 3.7.

**Comment by tananaev** [comment]
If you are using version 3.7, you should use config from version 3.7 as well.
