### ISSUE TITLE
Feature Request : Device Management Info

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2316]
Dear All,

A small addition in device table I am listing as a feature request, as this will allow users with 100's of devices to better manage their inventory of devices on traccar.

In device table, two additional columns can be added to identify the following.

device->msisdn  (The sim card number/mobile number of sim card inside the device)
device->model/protocol - drop down list  (Helps identify the device model / protocol for sending commands etc)

**Comment by tananaev** [comment]
I agree with protocol, but phone number/sim card is a device specific thing. Some devices don't use SIM cards at all.

**Comment by nefertiti007** [comment]
Dear Anton,

correct me if am wrong,. I was under the impression, most of the commercial GPS Tracking devices worked on SIM Card and very few satellite based devices (expensive) ones do exist.

-Also the idea here is, if a user has lets say GT06 or TK103 (100's or 1000's of them), many a times the user would like to simply store the phone number of the device sim card as well, for easy retrieval while tracking, Otherwise end up having to maintain a separate record to cross refer. where lets say I want to send a command to a device (however the device does not support command from platform). If I can view the sim card number as a user, it makes the user/admins life easier.

- Similarly, With protocol/model number, what commands to send also can be easier to plan, for users who use multiple models of devices.

**Comment by tananaev** [comment]
I guess most of devices do have SIM card. And it might be useful for SMS commands in future, so I guess it makes sense to add it as well.

**Comment by Abyss777** [comment]
Hello
Are you talking about device attributes? They are already. Or something else?

**Comment by tananaev** [comment]
Yes, but attributes are harder to access. I think it make sense to add some attributes directly to the device model.

**Comment by khfrabbi** [comment]
I think you also can add drivers(vehicle user) mobile no to contact them or you can add a new table for drivers information and map driver to a device.

**Comment by tananaev** [comment]
@khfrabbi, I think that would out of scope for Traccar. Traccar is used not only for vehicle tracking, but also for personal, animals, cargo tracking and other cases. Drivers would only make sense for vehicles.

**Comment by khfrabbi** [comment]
@tananaev , actually I didn't meant drivers, it should be contact/responsible person's for that device whether it is personal, animals, cargo tracking or other cases. 

anyway thanks for your great job.

**Comment by jaimzj** [comment]
@tananaev , @Abyss777 

I was thinking, maybe how about implementing a module based feature facility.? 

Where relational data, such as what @khfrabbi  said driver information, or what I said about Device SIM and relevant data, can be managed via a seperate module/add on.

These addons will not interfere in the functioning of traccar, rather just link the records created by the addon to its relevant devices or position or event table etc.

**Comment by tananaev** [comment]
There is already a way to store any additional data in the attributes.

**Comment by Abyss777** [comment]
Lets assume new columns/fields names for device model:

- **simCard** (String) -  mobile number or msisdn number of SIM-card installed in device
- **protocol** (String) - protocol name of device, is it will be filled manually or automatically by last position?
- **contact** (String) - driver/responsible person name or other contact information
- **type** (String) - type of device i.e. "car", "track", "yacht", "plane", "man", "woman", "cow" etc. (also use it for device images in future)

any other major columns?

**Comment by tananaev** [comment]
Sounds enough to me. I would just name it "phone" instead of "simCard" because SIM card can mean different things, so it might be confusing.

**Comment by Abyss777** [comment]
OK. What about way of filling `protocol`? Automatically or manual?

**Comment by tananaev** [comment]
Just thought about it a bit more. I think it shouldn't be "protocol". It should be "model" to enter device model. Configured by the user manually.

**Comment by jaimzj** [comment]
@Abyss777 @tananaev I think yes, Model would be a better option than protocol. This helps users identify which device has gone where,. and also send Commands accordingly.
