### ISSUE TITLE
Upgrade process

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2322]
hi,

Is there any documentation on the upgrade process? Even it's just for upgrading from one version earlier, it would be good. For example when 3.7 is released, it would be good to have some instructions on upgrading from 3.6 to 3.7. Thanks

**Comment by tananaev** [comment]
Upgrade instructions (for versions 3.3+):

1. Remove old version
2. Install new one

If you are using H2 database, don't forget to copy the database file over to the new version.

**Comment by m-menon** [comment]
thanks. And then traccar automatically makes the changes to the tables, constraints as necessary (including creating new tables)? Cheers

**Comment by tananaev** [comment]
Yes, Traccar does database schema migration automatically.

**Comment by m-menon** [comment]
great thanks :)
