### ISSUE TITLE
Tramigo T23 IMEI issues

### ISSUE THREAD

**Issue by gpproton** [tananaev/traccar#2324]
Hi Anton

I’ve been testing Tramigo T23 tracking device on traccar server but there are some issues with the integration.

Firstly my device imei is 355457051296302 but it was not still communicating and this usually works with Tramigo enterprise server, after going through Traccar server logs i discovered that traccar was identifying it as 783814147 and it currently reporting, but what i can’t understand is how this ID-783814147 came about.

Lastly the altitude, power status, direction and other parameters were not displaying.

**Comment by tananaev** [comment]
Can I see logs?

**Comment by gpproton** [comment]
Hi Anton

I read through the protocol document for Tramigo T23 and the IMEI field byte order is big endian but my issue is have been searching through the internet and i don't know how to convert it to big endian.

**Comment by tananaev** [comment]
Can I see a message sample from your device?

**Comment by gpproton** [comment]
Tramigo T23 uses Big Endian for it legacy protocol, so it IMEI needs to be converted to big Endian, like 5XXXXXXX to XXXXXXXXXX, well thanks @tananaev
