### ISSUE TITLE
Feature Request : Position : Sticky Informations (Key Values)

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2325]
Dear All,

For few of the protocols I have tested lately, I have been noticing a situation. this includes GT06, meiligao, 	gps103 and such. I will take the example of GT06 in this case,.

In Gt06, KEY_POWER value is sent at set intervals, and new Messages from device supersede the said updates,.

Same for Ignition value as well (However, I do know Ignition can be now found in events) .

Whats your thought on this, Can a solution be found for this? where certain parameters / key values can be kept available for live mapping purposes.

- Specially for users who use traccar as a back-end.

**Comment by tananaev** [comment]
One option I can think of is to preserve some attributes from previous position if they are missing in current one. The problem with this approach is that some attributes can become (very) outdated.

**Comment by nefertiti007** [comment]
Yes, you are right it can get very outdated, 

Otherwise is it possible to (reference the positionid) of the previous post with certain attributes,. in the current or latest position record,. 

This way the user gets to query and display data, and even check time-stamp. And as matter we need not preserve the last attribute value in the new entry, rather just a reference to the position id, that contains these values?

**Comment by tananaev** [comment]
I guess we can implement this feature with configurable set of attributes and expiration time.

I don't think it's a good idea to reference old position. It will quickly turn become very complicated.

**Comment by nefertiti007** [comment]
Thank You @tananaev I have referenced this in feature request list :)

**Comment by Abyss777** [comment]
@tananaev 

Suggesting to configure list of sticky attributes like this:
````
<entry key='copyAttributes'>power;ignition;battery;</entry>
````
But not sure how to implement expiration, may be add attribute to position `attributesCopyTime` store `serverTime` to it and copy it too until expired?

**Comment by tananaev** [comment]
I think it's better to just separate parameters with spaces, but I like the idea.

As a first version we can implement it without expiration.

**Comment by jaimzj** [comment]
@tananaev  & @Abyss777 what are the chances of this feature being implemented? in the coming release?
