### ISSUE TITLE
Feature Request: Allow custom bind to specific interface (instead of 0.0.0.0)

### ISSUE THREAD

**Issue by wico** [tananaev/traccar#2333]
Right now, via the config (traccar.xml) one can set the listening-port for the web-ui:
`<entry key='web.port'>_port_</entry>`

But: I'ts not possible to set the IP it should bind to. Thus, it binds to 0.0.0.0 (all interfaces).

In case one wants to put traccar behind a reverse-proxy (e.g. nginx), it would be nice to bind traccar to e.g. 127.0.0.1:<port> and let nginx to route and control the traffic to it.

**Comment by tananaev** [comment]
What made you think it's not possible? It is possible:
```
<entry key='web.address'>127.0.0.1</entry>
```

**Comment by tananaev** [comment]
It's also possible to configure network interface for each protocol port if someone needs it.

**Comment by wico** [comment]
Ouch, then I have overseen that. Sorry.
