### ISSUE TITLE
Compilation problem with Maven

### ISSUE THREAD

**Issue by marlomgirardi** [tananaev/traccar#2334]
Hi guys!

I'm trying to build the project but Maven is returning the following error:

**[WARNING] Error injecting: org.codehaus.plexus.archiver.jar.JarArchiver**
http://pastebin.com/9hMJTBFG

**Comment by tananaev** [comment]
Can I see full output from the beginning?

**Comment by marlomgirardi** [comment]
http://pastebin.com/pKz3JDvZ

**Comment by tananaev** [comment]
What version of JDK do you have? If 9, you should downgrade to 7 or 8.

**Comment by marlomgirardi** [comment]
It is currently 8

**Comment by tananaev** [comment]
Are you absolutely sure about it? Because it seems to be an error with JDK 9.

**Comment by marlomgirardi** [comment]
I have both, but the 8 is currently active.

track2you@vend2you:/usr/share/java$ java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by tananaev** [comment]
Maven must be using JDK 9. Try following command:
```
echo $JAVA_HOME
```

**Comment by marlomgirardi** [comment]
Sorry, I had not checked the java environment variables. Probably I was giving problem.

Anyway thanks, it helped me solve the problem.
