### ISSUE TITLE
resetDelay option

### ISSUE THREAD

**Issue by smhhadima** [tananaev/traccar#2338]
Hi,

I don't see "resetDelay" option at your documentation page
 https://www.traccar.org/configuration-file/

does it mean it is no longer valid option?

**Comment by tananaev** [comment]
You should use "timeout" instead. Legacy "resetDelay" parameter is still valid, but it will be removed at some point.

**Comment by smhhadima** [comment]
What is the default "timeout" value?

**Comment by tananaev** [comment]
There is no default value. By default there is no connection timeout.

**Comment by smhhadima** [comment]
thank you
