### ISSUE TITLE
could not reponse login data for topflytech 

### ISSUE THREAD

**Issue by touy** [tananaev/traccar#2340]
Hi
recent my team was trying make listener for T8803pro , which that would need a response from the server , and they use traccar server as a data collector , any way , it seems the GPRS data consumed a lot (data gone within 3 days ) , then  
I have tried to convert code to python, and  I found a problem us I could not pass the login , I response to the tracker but it still sending login data , I am not sure if the problem is my code , I am confusing what the thing is going one here . or I misunderstood something ? 

so the issue still exist on traccar server  ? or the problem is the protocol or tracker ?  I download traccer server to install on my linux server to test but it would need sometime , which if you know the reall issue please let me know 

and here what I try sending but no good results 
```python
    dt=str(datetime.now())

    s="232301001500010880316890233088"
    sent=clientsocket.send(s)
    print dt+"sent pure 1:"+str(s)    
    
    dt=str(datetime.now())
    myb=bytearray(s)
    sent=clientsocket.send(s)
    print dt+"sent pure 1 array:"+str(myb)

    dt=str(datetime.now())
    s=binascii.b2a_hex(s)
    sent=clientsocket.send(s)
    print dt+"sent b2a:"+str(s)

    dt=str(datetime.now())
    
    
    dt=str(datetime.now())
    myb=bytearray(s)
    sent=clientsocket.send(s)
    print dt+"sent b2a array:"+str(myb)
    
    dt=str(datetime.now())
    s=binascii.a2b_hex(s)
    sent=clientsocket.send(s)
    print dt+"sent convert a2b"+str(s)
    

    dt=str(datetime.now())
    myb=bytearray(s)
    sent=clientsocket.send(s)
    print dt+"a2b array"+str(s)

    dt=str(datetime.now())
    s="232301000F00010880316890233088"
    sent=clientsocket.send(s)
    print dt+"sent pure:"+str(s)    
    
    dt=str(datetime.now())
    myb=bytearray(s)
    sent=clientsocket.send(s)
    print dt+"sent pure arrat:"+str(myb)

    dt=str(datetime.now())
    s=binascii.b2a_hex(s)
    sent=clientsocket.send(s)
    print dt+"sent b2a:"+str(myb)
    
    dt=str(datetime.now())
    myb=bytearray(s)
    sent=clientsocket.send(s)
    print dt+"sent b2a array:"+str(myb)
    
    dt=str(datetime.now())
    s=binascii.a2b_hex(s)
    sent=clientsocket.send(s)
    print dt+"sent convert a2b"+str(myb)
    
    dt=str(datetime.now())
    myb=bytearray(s)
    sent=clientsocket.send(s)
    print dt+"a2b array"+str(myb)
```

here is some code
```python
import socket
import string,sys
import thread
import struct
from datetime import datetime
#from protocol_handler import Protocol_Handler
import urllib2
import logging
import time 
import sys
import binascii
Port=6661
_null_trans = string.maketrans("", "")
def start_server(argv):
#url=argv[0]
try:
Port=int(argv[0])
except ValueError:
print "Try again both value must be given!"
return
log_file=time.strftime("%Y-%m-%d.log")
logging.basicConfig(filename=log_file, level=logging.INFO)
sock=socket.socket(socket.AF_INET,socket.SOCK_STREAM)
sock.bind(('0.0.0.0',Port))
sock.listen(5)
print 'started on %s' % str(Port)
while (True):
newsock,address=sock.accept()
thread.start_new_thread(handler, (newsock, address))
def handler(clientsocket, clientaddr):
data = clientsocket.recv(1024)
print data
d=binascii.b2a_hex(data)
#binascii.hexlify(data)
print d
print binascii.a2b_hex(d)
myb=bytearray()
s="232301000F00010880316890233088".decode("hex")
#myb.append(s)
myb=bytearray(s)
sent=clientsocket.send(myb)
print "sent"+str(sent)
while(sent==0):
print "send again"
time.sleep(1)
sent =clientsocket.send(myb)
if(sent==0):
print "socket broken"
#binascii.a2b_hex(hexstr)
#binascii.unhexlify(hexstr)
close_connection(clientsocket,clientaddr)

def close_connection(sock,clientaddr):
print "close connection to ip %s" % str(clientaddr)
sock.shutdown(socket.SHUT_WR)
sock.close()
def istext(s):
if "\0" in s:
return "it contains binary"
if not s: # Empty files are considered text"
return "empty string"

# Get the non-text characters (maps a character to itself then
# use the 'remove' option to get rid of the text characters.)
t = s.translate(_null_trans, s)

# If more than 30% non-text characters, then
# this is considered a binary file
threshold=0.3
if float(len(t)) > threshold*float(len(s)):
    return str((float(len(t)/float(len(s)))*100))+" is binary"
return str((float(len(t)/float(len(s)))*100))+" is text"
if name=='main':
start_server(sys.argv[1:])
```

**Comment by tananaev** [comment]
Traccar doesn't send any data to the device except some acknowledgement messages, so if your device used up the data, it must be device.

Not sure why you want to reimplement, but if you want someone to read it, you need to format it properly.

**Comment by touy** [comment]
Hi I have found that the string that I prepared have some hidden characters which caused me trouble for 3 days
'##\x01\x00\x0f\x00\x01\t\x901h\x90#0\x99'
which I have to use regular express to purify the string before send or do any encoding
here is my full code, which I am confusing that what method I have to send the that string , Hex string , or something ? 
[server_listener.zip](https://github.com/tananaev/traccar/files/479155/server_listener.zip)

**Comment by tananaev** [comment]
It's a binary protocol. I don't understand why you are trying to operate with strings.

**Comment by touy** [comment]
base on my code , I prepared the hex string and convert the string to binary data and send it 
but the tracker still keep sending login data to the server 

s="232301000F00010880316890233088" # data that I prepared
#data from tracker 232301001501850880316890233088140209625020
                ps = filter(lambda x: x in string.printable, resp) # filter the string 
                sb="\x23\x23\x01\x00\x0F\x00\x01\x09\x90\x31\x68\x90\x23\x30\x99"
                d=binascii.a2b_hex(ps)                # convert hex string to binary data
                sent=clientsocket.send(d) #send binaray data to the tracker 
                time.sleep(1)

**Comment by tananaev** [comment]
I would recommend to compare what you send with what Traccar sends. Use something like Wireshark to capture and compare network packets.

**Comment by touy** [comment]
so you meant what I have done is correct for sending binary data to tracker, except that if the sent data is correct or not right , I am setting a sniffing program to test it

**Comment by tananaev** [comment]
I haven't checked your code. I'm just suggesting what you can do to check if it's correct.

**Comment by touy** [comment]
hi
I found in log and it seems it's very the same as I did for hex string 
I convert that hex string to binary data
receive :  b'##\x01\x00\x15\x001\x03W6p1\x10\x84\x02\x14\x02\tbP '
what I sent: 232301000f00010880316890233088

resp=binascii.a2b_hex(resp) # use this method to encode
# ==> b'##\x01\x00\x0f\x00\x01\x08\x801h\x90#0\x88'
sent=clientsocket.send(resp) #a2b_hex

(I use python 2.6.6 seems very strange and unclear result, now I use python 3.5) 
but I still could not get the new data from tracker except login data , which I did it before on windows  platform which now I don't have Windows any more 

the main question here what I have done wrong ? or I missed something here or because or Linux or ? 
your traccar is cool , but I don't want to throw my pieces and time , 
 
2016-09-19 02:46:35 DEBUG: [5E274B8A: 5094 < 202.137.156.206] HEX: 232301001500120880316890233088140209625020
2016-09-19 02:46:35 DEBUG: [5E274B8A: 5094 > 202.137.156.206] HEX: 232301000f00010880316890233088
2016-09-19 02:46:36 DEBUG: [5E274B8A: 5094 < 202.137.156.206] HEX: 232303000f00000880316890233088
2016-09-19 02:46:36 DEBUG: [5E274B8A: 5094 > 202.137.156.206] HEX: 232303000f00010880316890233088

**Comment by tananaev** [comment]
Can you provide Wireshark logs?

**Comment by touy** [comment]
here is some wireshark logs 
for 5094 and 6666 ( my server) 
it's very funny that my server there is no data that I sent , ... but when I test with chat server client, it's working fine then... so now it's beyond my mind now
[6666.zip](https://github.com/tananaev/traccar/files/484610/6666.zip)

**Comment by touy** [comment]
sorry the 666 file was wrong one, here is the right one 
[6666__.zip](https://github.com/tananaev/traccar/files/484736/6666__.zip)

**Comment by tananaev** [comment]
I have checked port 6666 and it looks fine to me. You've got a response for your command.

**Comment by touy** [comment]
yes, I just found the same thing so the problem is I could not see the second command from trackers 
the process
- accept
- waiting for data 
- get data 
- process
- response 
- close connection 
why from my console I could not see the second data , there is only one possible 
- I check the seconds and next data always alive with first connection 
- tracker would leave the current connect after some seconds only 
- I have to keep current connection alive for some seconds
if so this protocol would consume much server's energy 
if so I have to settimeout for it , which how many seconds  , is it right ?

**Comment by tananaev** [comment]
You need to keep connection open to communicate with device.

**Comment by touy** [comment]
here we call "a small piece blind your eyes" 
BIG THANKS 
you help my days  , I give you some beers , CHEER!
