### ISSUE TITLE
AR-2G from Oigo Telematics

### ISSUE THREAD

**Issue by inghoward** [tananaev/traccar#2357]
Hi, 
I got an Oigo AR-2G device. I sends this
```
7e002e000000146310002523830400001bfb000369150f310c0591594d062ac0c0141508011303cd63101604fd00000000.
```
Can`t find a matching protocol cause HEX decoder gives some unreadable characters. Anyone knows about this protocol?

**Comment by inghoward** [comment]
I found this decodification manual

[AR_Decodification_Manual.PDF](https://github.com/tananaev/traccar/files/485773/AR_Decodification_Manual.PDF)

**Comment by tananaev** [comment]
Good timing. I've just implemented it 5 days ago.

You can try this build:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0

You need to add following line to the config:
```
<entry key='oigo.port'>5121</entry>
```

**Comment by inghoward** [comment]
Thanks Tananaev!

**Comment by eliudiaz** [comment]
hi Tananaev, could you please check the next oig mg-2g request, when traccar decoder gave me a wrong gps coordinate: 
Req: 303138333533373832303636323232333631303730343032303330343933303632313030303030303030303030303030303030303030303030303030303030303030303037413443303031313030313338303030303030303030

gps decoded:
2017-08-18 23:28:50  INFO: [FE4153ED] id: 138333533373832, time: 2013-02-19 01:48:48, lat: 8756.23013, lon: 8588.61855, speed: 42.6, course: 13874.0

thanks

**Comment by tananaev** [comment]
@eliudiaz, your device is using different protocol. Please create a new issue if you want to discuss it. I would also need protocol documentation for your device.
