### ISSUE TITLE
"watch" protocol - frame length exceeds 1024

### ISSUE THREAD

**Issue by marko89kv** [tananaev/traccar#2369]
This occurs when watch tries to send audio messages - I've noticed that some other protocols have separate frame decoder classes. Where can this be changed for the "watch" protocol?

**Comment by tananaev** [comment]
In [WatchProtocol class](https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/WatchProtocol.java#L51).

**Comment by marko89kv** [comment]
Quick and on point as always, thank you.
