### ISSUE TITLE
ubuntu mysql positions not working 

### ISSUE THREAD

**Issue by shenol** [tananaev/traccar#2373]
```
mysql> select * from positions;
Empty set (0.00 sec
```
log:
```
5005 < 188.57.49.224] HEX: 474554202f3f69643d313930352674696d657374616d703d31343734393137323232266c61743d33382e323936343730266c6f6e3d32372e3138333735302673706565643d302662656172696e673d3026616c7469747564653d3132352e31333426626174743d3020485454502f312e310d0a486f73743a20747261636361722e706174726f6e67656c64696d692e636f6d3a353030350d0a4163636570743a202a2f2a0d0a4163636570742d4c616e67756167653a2074722d74720d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174650d0a557365722d4167656e743a2054726163636172436c69656e742f332e302043464e6574776f726b2f3830382e302e322044617277696e2f31362e302e300d0a0d0a
2016-09-26 20:04:03  INFO: [51EA91A5] disconnected
```

**Comment by tananaev** [comment]
Why are you using port 5005? Correct port for Traccar Client is 5055.

**Comment by shenol** [comment]
Thanks.

**Comment by shenol** [comment]
'\xC4\xB0zmir...' for column 'address' at row 1 - SQLException (... < QueryBuilder:443 < DataManager:292 < DefaultDataHandler:27 < ...)

Turkish char problem.

**Comment by tananaev** [comment]
Try solutions from here:

https://www.traccar.org/forums/topic/mysql-error-change/

**Comment by shenol** [comment]
different applications and system clock ticking. How can I fix

**@zeus:/opt/traccar/conf# date
Tue Sep 27 16:11:27 EEST 2016


2016-09-27 13:02:56 DEBUG: [80DF117B: 5055 > 188.57.49.73] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2016-09-27 13:02:56  INFO: [80DF117B] id: 677928, time: 2016-09-27 13:02:56, lat: 38.39663, lon: 27.09496, speed: 0.0, course: 242.9
**2016-09-27 13:02:58**  INFO: [80DF117B] disconnected

**Comment by tananaev** [comment]
If it's a different problem, please create another thread for it and provide more details.

**Comment by shenol** [comment]
Ok, Thanks.
