### ISSUE TITLE
No direction detected on Tramigo T23 IMEI

### ISSUE THREAD

**Issue by gpproton** [tananaev/traccar#2377]
Hi Anton

I'm currently testing a Tramigo T23 on Traccar, but unlike other device that send angle information to server it's not displaying the moving direction on traccar , but when i check the log i see the direction is actually shown but written as N W  SW etc. I I'll be really glad if the direction detection can be implemented, below is a sample log from the device.
```
80009e08b00086000101bc1803778a59c58dea57546573742054323320547261636b65723a204d6f76696e672c20312e3639206b6d204e57206f66205574656b6f6e2c2045646f2c204e472c20362e34363137302c20352e36313938322c20452077697468207370656564203333206b6d2f682c2031363a3138205365702032372020454f46
```

**Comment by tananaev** [comment]
Done. I've implemented direction decoding.
