### ISSUE TITLE
Different Chinese Tracker

### ISSUE THREAD

**Issue by DamienFlynn** [tananaev/traccar#2380]
Hi I have set up an account on demo2 server, email damofly@yahoo.com. I have added a tracker and tried different ports suggested but no luck. The IMEI No is 353419038264102 can you see it in the log files. It was originally set up for a website called cootrack on port 8820.
version gt02a_30_7s-m_v47_wm

Thank you

**Comment by tananaev** [comment]
Looks like your device is using GT02 protocol, port 5022.

**Comment by DamienFlynn** [comment]
Brilliant.
Thanks Anton
