### ISSUE TITLE
Remove unused method

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#2386]
I've noticed that we don't use `getGeofence`. @Abyss777, do you think we can remove it?

**Comment by Abyss777** [comment]
Do you mean `DataManager.getGeofence` ?

**Comment by tananaev** [comment]
Yes, that one.

**Comment by Abyss777** [comment]
You are right, we should remove it. And also need to check and remove `Datamanager.getX` of all cached objects.

**Comment by tananaev** [comment]
Done, removed `getUser` as well.

**Comment by Abyss777** [comment]
Good. Thanks.
