### ISSUE TITLE
Motion status and /api/reports

### ISSUE THREAD

**Issue by sunhoww** [tananaev/traccar#2389]
Hi

Since the **motion** property has been removed from _/api/devices_ post v3.7, I began using **speed** > 0 from _**positions**_ to determine whether the device was moving. I probably shouldn't be doing this. I was using this to set the color of markers on the map depending on its status (status here being: one of [ _'offline'_, _'moving'_, _'stopped'_ ] ). This worked fine without relying on the events system. ...Until I started seeing stationary devices as _'moving'_.

This happened because I had configured the server with `filter.distance`, to filter out position reporting when devices are stationary. A few times, it just so happens that the last position before the filtering starts has **speed** > 0. It was this position record that _/api/socket_ emits as **positionId** for the _**devices**_ continuously.
- Is there a workaround I'm not seeing?
- Should I be using the events system after all? 
- Is this what's already been discussed at #2325 ?

One other thing. I am using _/api/positions_ to generate some sort of a history. Since now we have _/api/reports/route_, and both endpoints seem to emit the same data. I was wondering...
- Should I use _/api/reports/route_ over _/api/positions_?
- Do the two endpoints indeed emit the same data apart from **address** and **type**?
- Unrelated, but what are **type** and **valid** in positions?

And on a side note, I am also using _/api/positions_ to render some line charts. And because of `filter.distance`, I tend to get rather weird charts (what with all the filtered out data points and all). Now with _/api/reports/trips_, I think I could get prettier, more useful charts.

Amazing job you're doing here.

Thanks.

**Comment by Abyss777** [comment]
Hello

There is another way to avoid jumping coordinates while device is stationary `coordinates.filter`. Here is explanation https://www.traccar.org/configuration-file/ It can help not to miss stop/motion positions.

Actually motion event handler and trips detector uses same criteria of movement - speed. They will also miss stop if such position was filtered.

`/api/positions` is not used now in web client, but there are plans to use it again.
`/api/reports/route` used for reports, for now it return the same objects - positions. Also you can get them as `csv` file.
Can't say what will happen in future, but I think `/api/positions/` will always return only position objects.

`valid` is true then device see enough satellites to fix coordinates (in most cases)
`type` is not used for now.

**Comment by jaimzj** [comment]
@Abyss777  

Regarding Motion event handled, I have as well noticed that enabling `<entry key='filter.duplicate'>true</entry>` Where it still shows vehicle in motion and speed value more than 0. while the device is stationary.  not sure if in event it is managed already.

Does at present the motion event handler have, any conditions where  if time difference since last position logged (ir-respective of what filter has processed) is more than x value, set trip = stopped.

**Comment by sunhoww** [comment]
`coordinate.filter` is nice. I didn't know about this. I'll give it a try.

Actually, the reason I did `filter.distance`, was to have less records in the db.
- The filtered positions are not stored in the db, are they?

> Actually motion event handler and trips detector uses same criteria of movement - speed. They will
> also miss stop if such position was filtered.

So filtered positions never reach the motion event handler.
- Is it just for this event handler?
- Do the filtered positions reach other event handlers like the alert and ignition handlers?

I hope they do.

**Comment by tananaev** [comment]
Filtered positions are not stored in the database, and they don't reach event handlers either.

**Comment by Abyss777** [comment]
@jaimzj 
No it does not, and I think it is not very good idea. Device can lost connection or be configured to send positions every hour etc. I mean to many "if"s should be regarded.

**Comment by Abyss777** [comment]
@tananaev 
May be we should consider exclusion for filters again, what do you think?

My vision is:
do not filter some valuable positions:
- speed is switched to/from zero (threshold)
- position contain `KEY_RESULT`
- `KEY_IGNITION` has changed
- position contains `KEY_ALARM`

and of course it should be "disablable"

**Comment by sunhoww** [comment]
@tananaev 
I concur with what @Abyss777 is suggesting.

Otherwise, I guess the only alternative to have access to all features from the event system is to disable filtering altogether.

**Comment by tananaev** [comment]
I guess we can have an option to check if any attributes changed and not filter those messages.

**Comment by sunhoww** [comment]
That would be tremendously helpful.

**Comment by sunhoww** [comment]
Resolved by #2467.
