### ISSUE TITLE
Device not visible within the web-UI after upgrade to 3.7

### ISSUE THREAD

**Issue by TwizzyDizzy** [tananaev/traccar#2390]
Hi Anton,

after the upgrade to 3.7, I cannot see my device anymore in the web UI. It's similar to my old issue #1879.

This time though, all database migrations seem to have been applied successfully and I have also applied any changes to traccar.xml to my traccar config (since there have been query changes):

    STATUS | wrapper  | 2016/09/27 02:11:02 | --> Wrapper Started as Daemon
    STATUS | wrapper  | 2016/09/27 02:11:02 | Java Service Wrapper Community Edition 64-bit 3.5.28
    STATUS | wrapper  | 2016/09/27 02:11:02 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
    STATUS | wrapper  | 2016/09/27 02:11:02 |     http://wrapper.tanukisoftware.com
    STATUS | wrapper  | 2016/09/27 02:11:02 | 
    STATUS | wrapper  | 2016/09/27 02:11:03 | Launching a JVM...
    INFO   | jvm 1    | 2016/09/27 02:11:03 | WrapperManager: Initializing...
    INFO   | jvm 1    | 2016/09/27 02:11:03 | [WrapperSimpleAppMain] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
    INFO   | jvm 1    | 2016/09/27 02:11:04 | INFO 9/27/16 2:11 AM: liquibase: Clearing database change log checksums
    INFO   | jvm 1    | 2016/09/27 02:11:04 | INFO 9/27/16 2:11 AM: liquibase: Successfully acquired change log lock
    INFO   | jvm 1    | 2016/09/27 02:11:04 | INFO 9/27/16 2:11 AM: liquibase: Successfully released change log lock
    INFO   | jvm 1    | 2016/09/27 02:11:04 | INFO 9/27/16 2:11 AM: liquibase: Successfully acquired change log lock
    INFO   | jvm 1    | 2016/09/27 02:11:05 | INFO 9/27/16 2:11 AM: liquibase: Reading from traccar.DATABASECHANGELOG
    INFO   | jvm 1    | 2016/09/27 02:11:05 | INFO 9/27/16 2:11 AM: liquibase: Reading from traccar.DATABASECHANGELOG
    INFO   | jvm 1    | 2016/09/27 02:11:05 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.3::changelog-3.3::author: Marking ChangeSet: changelog-3.3::changelog-3.3::author ran despite precondition failure due to onFail='MARK_RAN': 
    INFO   | jvm 1    | 2016/09/27 02:11:05 |           /opt/traccar/schema/changelog-master.xml : Not precondition failed
    INFO   | jvm 1    | 2016/09/27 02:11:05 | 
    INFO   | jvm 1    | 2016/09/27 02:11:05 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.5::changelog-3.5::author: Marking ChangeSet: changelog-3.5::changelog-3.5::author ran despite precondition failure due to onFail='MARK_RAN': 
    INFO   | jvm 1    | 2016/09/27 02:11:05 |           /opt/traccar/schema/changelog-master.xml : Not precondition failed
    INFO   | jvm 1    | 2016/09/27 02:11:05 | 
    INFO   | jvm 1    | 2016/09/27 02:11:05 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Data updated in devices
    INFO   | jvm 1    | 2016/09/27 02:11:05 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Foreign key constraint added to devices (groupid)
    INFO   | jvm 1    | 2016/09/27 02:11:05 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Data updated in groups
    INFO   | jvm 1    | 2016/09/27 02:11:05 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Columns attributes(VARCHAR(4096)) added to devices
    INFO   | jvm 1    | 2016/09/27 02:11:06 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Column devices.motion dropped
    INFO   | jvm 1    | 2016/09/27 02:11:06 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Column devices.status dropped
    INFO   | jvm 1    | 2016/09/27 02:11:06 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Columns attributes(VARCHAR(4096)) added to groups
    INFO   | jvm 1    | 2016/09/27 02:11:06 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: Columns attributes(VARCHAR(4096)) added to server
    INFO   | jvm 1    | 2016/09/27 02:11:06 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7::author: ChangeSet changelog-3.7::changelog-3.7::author ran successfully in 1136ms
    INFO   | jvm 1    | 2016/09/27 02:11:06 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7-notmssql::author: Foreign key constraint added to groups (groupid)
    INFO   | jvm 1    | 2016/09/27 02:11:06 | INFO 9/27/16 2:11 AM: liquibase: /opt/traccar/schema/changelog-master.xml: changelog-3.7::changelog-3.7-notmssql::author: ChangeSet changelog-3.7::changelog-3.7-notmssql::author ran successfully in 130ms
    INFO   | jvm 1    | 2016/09/27 02:11:06 | INFO 9/27/16 2:11 AM: liquibase: Successfully released change log lock
    INFO   | jvm 1    | 2016/09/27 02:11:06 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @3720ms
    INFO   | jvm 1    | 2016/09/27 02:11:07 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
    INFO   | jvm 1    | 2016/09/27 02:11:07 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@5853d6bb{/api,null,AVAILABLE}
    INFO   | jvm 1    | 2016/09/27 02:11:07 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@a8a8c0a{HTTP/1.1}{localhost:8082}
    INFO   | jvm 1    | 2016/09/27 02:11:07 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @4558ms

Any clue where to begin debugging?

Cheers
Thomas

**Comment by tananaev** [comment]
Are you using official version of everything? You can login as admin and see if device is linked to the user.

**Comment by TwizzyDizzy** [comment]
Hi Anton,

yes, everytime I update traccar I take the x64 version for linux and only update the config file (and wrapper config to run as a specific user) if something has changed.

Getting away from the database, the problem seems to be rooted in the API, after some more digging.

> Request URL:http://my.host.name/api/groups?_dc=1475366519136&page=1&start=0&limit=25
> Status Code:401 Unauthorized

> Request URL:http://my.host.name/api/geofences?_dc=1475366519141&page=1&start=0&limit=25
> Status Code:401 Unauthorized

> Request URL:http://my.host.name/api/devices?_dc=1475366519150&page=1&start=0&limit=25
> Status Code:401 Unauthorized

Above errors, in turn, may be caused by this:

> Request URL:http://my.host.name/api/session?_dc=1475366645720
> Status Code:404 Not Found

Cheers
Thomas

**Comment by tananaev** [comment]
Those errors mean that you are simply not logged in.

**Comment by TwizzyDizzy** [comment]
Argh. Well I have tested this now against pure traccar-web (which might have been what you meant with "original"). Seems that I somehow have a fuckup in my reverse proxy setup with apache... sorry for the fuzz :-/

**Comment by tananaev** [comment]
I have changed Traccar to properly handle relative paths for everything including API. Maybe that what caused the problem.

**Comment by TwizzyDizzy** [comment]
In fact, the problem was, that the cookie path and cookie domain had not been set correctly through the reverse proxy.

I proxy `https://my.server/gps/` to `localhost:8082` (traccar-web). Therefore I had to rewrite the CookieDomain and CookiePath like this:

> ProxyPassReverseCookieDomain 127.0.0.1 my.server
> ProxyPassReverseCookiePath  "/api"  "/gps/api"

In fact, I was wondering, whether I could send a pull request to make some additions to this site in order to clarify some things. Since reverse-proxy-ing traccar seems to be quite common:

https://www.traccar.org/secure-connection/

Cheers
Thomas

**Comment by tananaev** [comment]
Sure, any contribution is welcome.

**Comment by TwizzyDizzy** [comment]
... but the traccar website itself is not on github, is it? Would make it a lot easier :)

**Comment by tananaev** [comment]
By website you mean [web interface](https://github.com/tananaev/traccar-web)?

**Comment by TwizzyDizzy** [comment]
Ah, no. I mean https://www.traccar.org/

**Comment by tananaev** [comment]
No, it's not. You can send me an email with what you want to add there.

**Comment by TwizzyDizzy** [comment]
Alright, gonna do that in a couple of days!

**Comment by moraus** [comment]
@TwizzyDizzy I struggle with the same kind of issue when proxy through port 443. I serve Owncloud and traccar from https://mydomain/owncloud and https://mydomain/traccar, and I've been trying to use the <Location> directive in Apache to proxy traccar as illustrated below. 
I face the same problem with websocket, and the error in the browser console is:
GET https://mydomain.org/traccar/api/socket [HTTP/1.1 405 HTTP method GET is not supported by this URL 189ms]
I'm pretty much out of ideas, so I would appreciate your input. 

        # Proxy section for Traccar                                                                                                  
        <Location /traccar/>                                                                                                         
            ProxyPass wss://localhost:8082/                                                                                          
            ProxyPassReverse wss://localhost:8082/                                                                                   
            ProxyPass http://localhost:8082/                                                                                         
            ProxyPassReverse http://localhost:8082/                                                                                  
            ProxyPassReverseCookieDomain localhost mydomain.org                                                                       
            ProxyPassReverseCookiePath /api /traccar/api                                                                             
        </Location>

**Comment by tananaev** [comment]
Have you enabled `proxy_wstunnel` Apache module?

**Comment by moraus** [comment]
Yes, I have.
I believe it is nearly there, because the proxy is working with showing the web page, but the position info is missing through the wss

**Comment by tananaev** [comment]
It means that WebSocket doesn't work. I'm sure it's something with the way you configured the proxy, or possibly just some network issue. I would recommend to check on relevant resources about Apache proxy.

**Comment by moraus** [comment]
I agree, and since I've ran out of different ways configure the proxy and websites to read, I desided to ask here and @TwizzyDizzy.

**Comment by TwizzyDizzy** [comment]
A little short on time these days, but I try to look at this mid-next-week.

Cheers
Thomas

**Comment by moraus** [comment]
@TwizzyDizzy. Do you have input on where I should start digging? Any tips for debugging or logging? For example: How did you debug or test WebSocket?
