### ISSUE TITLE
telic tracker history query

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2396]
Hi,

Telic trackers sends different event ID's which describes reasons why that GPS position is sent to server, i already see them under "State" section but that is only last message event ID. Example from Telic event ID's is below. 

Would it be possible to do so that when i query tracker history (route messages) then i see sent event ID code numbers behind every message (to add new column to history view table) ? It gives lot of information to user about what is going on with tracker.

![telic events](https://cloud.githubusercontent.com/assets/17290463/19038485/64613032-8984-11e6-813a-1421b3d1526b.png)

**Comment by tananaev** [comment]
You can see "state" for each of the item in history.
