### ISSUE TITLE
DEBUG problem

### ISSUE THREAD

**Issue by federicobalm** [tananaev/traccar#2401]
Hello

I was watching the tracker-server.log file and find my gps tracker tk306A (Chinese) through gprs send the following string:

```
2016-10-03 22:25:28 DEBUG: [90CBEE4D: 5001 < 10.200.126.104] HEX: 696d65693a3335393731303034393035373739382c4f42442c3136313030333139323735322c313738352c2c2c302c35342c39362e3437252c37352c32302e3030252c313839322c302e30302c50303133342c50303537312c2c3b
```

using the tool HEX-DECODE (https://www.traccar.org/hex-decoder/)

I visualize this:
```
imei:359710049057798,OBD,161003192752,1785,,,0,54,96.47%,75,20.00%,1892,0.00,P0134,P0571,,;
```
any of these data are housed in the Mysql "Positions" column "Other" table:
```
{"odometer":1785,"hours":"0","obd-speed":"54","temp1":"75","throttle":"20.00%","rpm":"1892","battery":"0.00","ip":"xx.xx.xx.xx"}
```

but I note that the latest data "`P0134, P0571 ,,;`" They are not currently loaded in mysql column.

This information is important for me because it indicates the engine fault codes.

**there is a way for absolutely all the tk306A send data to the tracker-server.log file will be written in the mysql column "other" ????**

Thank you for your collaboration, excellent project.

**Comment by tananaev** [comment]
Fixed the problem.
