### ISSUE TITLE
Unable to see device data or HEX messages in server log

### ISSUE THREAD

**Issue by santushet** [tananaev/traccar#2403]
While testing #2397 in web server , i am unable to see any HEX message or packet data in the tracker-server.log. 
Attached screenshot of tracker-server.log file.
![selection_005](https://cloud.githubusercontent.com/assets/6049394/19069594/2a4f99bc-8a45-11e6-8318-16c1759532d0.png)

I have followed below steps to build and deploy.
1. git clone -b [branch]
2. cd traccar && mvn package
3. Download ,extract  and [install](https://www.traccar.org/linux/) traccar-linux-64-3.7.zip. 
4. Replace tracker-server.jar generated from step 2 in the location /opt/traccar
5. Add trakmate.port = 5126 in conf file(/opt/traccar/conf/traccar.xml)

Server is visible from the internet.Verified using port check tool. Also to verify device configuration, i have tried creating serversocket listener on the port 5126 and able to receive data. Here is the screenshot.
![selection_004](https://cloud.githubusercontent.com/assets/6049394/19069555/0fe75a88-8a45-11e6-9a13-8a257dbdb7a4.png)

**Comment by tananaev** [comment]
Are you sure it uses UDP protocol?

**Comment by santushet** [comment]
No.It uses TCP.

**Comment by tananaev** [comment]
Why is it UDP (`ConnectionlessBootstrap`) in your pull request then?

Also, why are you sending pull request if you haven't even tested it?

**Comment by santushet** [comment]
I have changed it to TCP. Since this is my first PR in github, I was looking for your feedback . Hence the lable [WIP](work in progress). Sorry for not mentioning explicitly. Now it is completed and tested.

**Comment by santushet** [comment]
After changing from UDP to TCP, this issue is resolved.
