### ISSUE TITLE
shifted positions on map

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2406]

**Comment by tananaev** [comment]
What version did you have before? I don't think anything changed in Telic decoder.

Check logs and see if coordinates are decoded correctly. It might be a device issue.

**Comment by argokask** [comment]
Before i used vers 3.6.

I checked logs and it seems that incoming messages (hex) from device are correct but decoded ones are wrong.

**Comment by tananaev** [comment]
Well, I need to see those. Please provide HEX samples and expected coordinates for those messages.

**Comment by argokask** [comment]
2016-10-05 07:47:11 DEBUG: HEX (IMEI is replaced with xxxxxxxxxxxx)

7400000030353330xxxxxxxxxxxx362c3035313031363034343632382c302c3035313031363034343632382c3032343732353433362c35393339363337382c332c35342c3139342c362c33302c302c32362c353130303034352c32343830312c303031302c30302c3230392c302c302c303130382c302c3000

2016-10-05 07:47:11  INFO:

id: xxxxxx time: 2016-10-05 07:46:59, lat: 59.65674, lon: 25.20710, speed: 0.0, course: 195.0

Manually decoded (coordinates in bold text):

t0530xxxxxx6,051016044628,0,051016044628,**024725436**,**59396378**,3,54,194,6,30,0,26,5100045,24801,0010,00,209,0,0,0108,0,0

**Comment by tananaev** [comment]
This doesn't look like valid longitude: 024725436.

It says 24 degrees and 72.5436 minutes, but there can't be more than 60 minutes.

**Comment by argokask** [comment]
Ok, it try to use another Telic tracker and see what happens then.

Thank you.
