### ISSUE TITLE
GL200: handle command answers

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#2408]
If we send command...
According to protocol architecture device firstly answers with `+ACK:<COMMANDNAME>` packet then it send some `+RESP:...` packet with requested data like battery, coordinates and others or sends nothing if it was some configuration command.

Sometimes it is useful to understand if device accepted command. (It can ignore command if wrong password or wrong parameters)

Most `+ACK:` packets contains same (nothing) information as heartbeat (actually heartbeat packet is `+ACK:GTHBD`)

I want to handle such packets as command result and do something like `set(Position.KEY_RESULT,  "Accepted "+<COMMANDNAME>);`

And next answer `+RESP:``GTBAT|GTVER|GTTMZ|GTCSQ` and others plan to handle like `GTINF`

What do you think is it OK?
Or may be that `+REST:` packets also handle as command result? And requested information put in `Result` field?

**Comment by tananaev** [comment]
I think it would be better to have a single response. Not sure which one makes more sense. I guess `ACK` would be better. Then we can decode actual `RESP` with data as a position, so it won't be lost.
