### ISSUE TITLE
Refresh geofences via custom frontend

### ISSUE THREAD

**Issue by mrameezraja** [tananaev/traccar#2414]
Hi @tananaev @Abyss777 ,

Traccar server is not refreshing (neither removing deleted ones nor picking newly added) geofences. I am using a custom frontend and custom database (sql server). It only have those geofences which were loaded at the time of running server. It is working fine with preloaded geofences.

How can i force refresh geofences via custom frontend or is there any other way?

Your help would be much appreciated.

-Thanks

**Comment by tananaev** [comment]
If you use web API, everything should be refreshing.

**Comment by mrameezraja** [comment]
I am not using traccar api, but i managed to refresh geofences by adding new api end point in geofences resource.

```
@POST
    public Response refresh() throws SQLException {
        Context.getPermissionsManager().checkReadonly(getUserId());
        Context.getGeofenceManager().refreshGeofences();
        return Response.ok().build();
    }
```

Is that a good approach?

**Comment by jaimzj** [comment]
@tananaev  I also am facing similar situation, As I do not use API, but instead direct access to Database.
I think, it would be nice to have a small solution if possible to this scenario,. where any new additions into database on geo-fence and other relevant mapping is automatically added into the traccar services.

Maybe a feature, which can be configurable to be enabled/disabled if required.

**Comment by tananaev** [comment]
@mrameezraja, it doesn't make sense. You don't use API to add geozone, but then you still need API to refresh it? Can't you just use API to create a geozone?

@jaimzj, if you can tell me how to detect changes in the database, I'm happy to consider your solution.

**Comment by mrameezraja** [comment]
Actually we are using a custom developed api. Traccar is used only as a tcp server.

**Comment by tananaev** [comment]
Your solution with refresh should work in that case.

**Comment by marchantm** [comment]
Im having the same issue. When I create a geofence on my own frontend this is not reflected in traccar until a geofence is created using traccar. After that they appear all Geofences created.

**Comment by jaimzj** [comment]
@tananaev No, As such I do not have a way to do that, I think what @mrameezraja  does is much better where the traccar server need not check nor be aware of whats happening, until the api is triggered. do you think this can be added as a feature API addition, for users like me? where I dont use Traccar API at all,. except for commands.

**Comment by tananaev** [comment]
Added "refresh" parameter to the "GET" API call. Set it to "true" to force geofences to be reloaded from the database.
