### ISSUE TITLE
Information about the battery charge is not maintained in CGuard protocol.

### ISSUE THREAD

**Issue by mpak59rus** [tananaev/traccar#2419]
Attach log & screenshot.
[log.zip](https://github.com/tananaev/traccar/files/516091/log.zip)
![2016-10-07_15-20-54](https://cloud.githubusercontent.com/assets/1908254/19189924/314147b0-8ca3-11e6-996c-7aec42f97d2f.png)
All code in commit 19b17695867e00861c719292aad7ae48f33a8eeb

**Comment by tananaev** [comment]
Added support for additional information reported by cGuard devices.
