### ISSUE TITLE
Laipac Protocol 

### ISSUE THREAD

**Issue by vassyakin** [tananaev/traccar#2423]
Hello,
I have the same problem #1774 after download new firmware to my Laipac S911 BL.
New status "p" is not response by the server Traccar:
```
$AVRMC,96414215,170046,p,4310.7965,N,07652.0816,E,0.00,0.00,071016,0,4069,98,1,0,0*04 
```
I connected device to GpsGateServer. The following sequence is obtained via terminal:
```
Client: [0x0D][0x0A]$AVRMC,96414215,170046,p,4310.7965,N,07652.0816,E,0.00,0.00,071016,0,4069,98,1,0,0*04[0x0D][0x0A]
Server: $EAVACK,0,04*2F[0x0D][0x0A]
Client: [0x0D][0x0A]$AVRMC,96414215,174306,p,4310.7956,N,07652.0603,E,0.00,0.00,071016,0,4034,98,1,0,0*05[0x0D][0x0A]
Server: $EAVACK,0,05*2E[0x0D][0x0A]
```
Maybe it will help solve the problem.

Thank You,
Yevgeniy

**Comment by tananaev** [comment]
Fixed the problem in bc39a5aaa85813cb003405dd67387454011da450. Here is a new build if you want to try it:

https://www.dropbox.com/s/cgmlansv32j3ii0/tracker-server.jar?dl=0
