### ISSUE TITLE
Not showing in real time

### ISSUE THREAD

**Issue by marchantm** [tananaev/traccar#2424]
I recently updated to 3.7 and my devices are sending positions each 10 seconds but traccar capture only each 3 minutes. With the 3.6 traccar all the positions are registered even  when set the devices to send position each 5 seconds. Is this a issue or i missing some settings? Thanks for your kindly help

**Comment by tananaev** [comment]
Please provide logs.

**Comment by marchantm** [comment]
[traccar-log.txt](https://github.com/tananaev/traccar/files/518280/traccar-log.txt)
[wrapper.log.20161009.txt](https://github.com/tananaev/traccar/files/518282/wrapper.log.20161009.txt)


ip address and imei was changed for security reasons.
Thanks for your help.

Regards

**Comment by tananaev** [comment]
As far as I can tell, everything is decoded correctly. All received data is decoded.

**Comment by marchantm** [comment]
Thanks i will install traccar again. Regards
