### ISSUE TITLE
[GL300] SOS doesn't do anything 

### ISSUE THREAD

**Issue by kxp** [tananaev/traccar#2425]
If I have the function key configured for SOS mode, the received message is treated as a normal position update, shouldn't  something appear in the info? When I check the logs the position received appears as a normal one.
Here is the initial part of the HEX message.
```
2b524553503a4754534f532c3330303530302c3836303539393030313136363531312c2c302c302c312c312c302e302c34342c3
```

If you need the rest let me know.

**Comment by tananaev** [comment]
SOS messages are not supported yet, so they are decoded as regular location reports. Can I have full message sample?

**Comment by kxp** [comment]
That makes sense, here it is.

`2b524553503a4754534f532c3330303530302c3836303539393030313136363531312c2c302c302c312c312c302e302c34342c37332e392c2d392e3832313136342c33382e3232303833312c32303136313030393133353335342c303236382c303030332c313737412c323435462c2c39362c32303136313030393133353335352c3139334424`

Thanks

**Comment by tananaev** [comment]
It might take some time before this is implemented, but thanks for the provided info.
