### ISSUE TITLE
GT06f Ignition - Event not recorded

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2427]
Dear Anton,

Device GT06f, the ignition is showing up in position table, If filter is disabled,.

However in events table it does not show igntion status changes. and config is true
```
<entry key='event.ignitionHandler'>true</entry>
```

Is there anything particular I would need to share to identify the issue?, The new devices send igniton value only when the ignition value changes.

Earlier GT06n etc, would send Ignition value always with all GPS packets.

**Comment by tananaev** [comment]
I'm guessing that the problem is that your device doesn't report ignition status in every message.

Related to #2325.

**Comment by jaimzj** [comment]
Yes, True its related to #2325 

But, Even still, I think ignition event should have captured it right in normal scenario? thats the reason why I created a new post. :)

Please advice?

**Comment by tananaev** [comment]
Ignition event handled only generates event when ignition changes from one value to another. Because your device doesn't send ignition value in all messages, there is never a case when in last message ignition is one value, and in the new message it's different. There is always a message without ignition value at all in between.

**Comment by jaimzj** [comment]
Oh yes, now I understand how this works,. Is there any other protocol/device which works like this? has it already been handled?

**Comment by tananaev** [comment]
It's not handled yet, but you can vote for the feature (#2325) to be implemented.

**Comment by jaimzj** [comment]
Thanks for the information @tananaev  :) Today I learnt a little more about how things work :) always been a learning process here
