### ISSUE TITLE
Index on table "events" column "type"

### ISSUE THREAD

**Issue by bpali** [tananaev/traccar#2429]
I'm running traccar 3.6 with some 250 devices that actively transmit data some 30 times per minute.

The MariaDB database I'm running started to work slow and I looked for slow queries and found the "SELECT * FROM events ..." one running over 2 second quite often and while being many this matters.

Within it I found that there's no index on column "type" and after creating one, things got better.

So I'm just making a suggestion here.

Appreciate your work.

**Comment by Abyss777** [comment]
Hello

Such (lookup in events table for every income position) behavior was fixed in 3.7

Thanks for feedback.

**Comment by bpali** [comment]
thanks for the info
