### ISSUE TITLE
security bug?

### ISSUE THREAD

**Issue by Turbovix** [tananaev/traccar#2455]
Hello Tananaev when my server is logged in using web browser and ask to inspect the page and in the following section terminal I get the following errors:

> 

 http://107.179.69.11:8082/api/session?_dc=1476831769173 Failed to load resource: the server responded with a status of 404 (Not Found)
http://107.179.69.11:8082/fake-login.html Failed to load resource: the server responded with a status of 404 (Not Found)
http://107.179.69.11:8082/api/session Failed to load resource: the server responded with a status of 401 (Unauthorized)
http://107.179.69.11:8082/fake-login.html Failed to load resource: the server responded with a status of 404 (Not Found)

>

And when I click on one of the errors you receive the following information from my account. This is not wrong?

>
{"id":1,"attributes":{},"name":"track-web","email":"XXXXXXX@gmail.com","readonly":false,"admin":true,"map":"osm","distanceUnit":"km","speedUnit":"kmh","latitude":0.0,"longitude":0.0,"zoom":0,"twelveHourFormat":false,"password":"123456."}

>

**Comment by tananaev** [comment]
Looks correct to me. The error probably mean that you failed to login first, and then logged in correctly because you have an active session.

**Comment by Turbovix** [comment]
I understand that if there is an active session someone has logged on, but let's say a person is invited to view the map, so she can have access to my username and password?

**Comment by tananaev** [comment]
Password shouldn't be there. What do you mean by "invited"?

**Comment by Turbovix** [comment]
For example; I call a friend to see a car on the map and when I pull away it can have access to my username and password.

**Comment by tananaev** [comment]
As I said, password shouldn't be there. I don't have it there:
```
{"id":1,"attributes":{"qwefr":"af"},"name":"admin","email":"admin","readonly":false,"admin":false,"map":"osm","distanceUnit":"km","speedUnit":"kmh","latitude":30.0,"longitude":60.0,"zoom":10,"twelveHourFormat":false,"password":null}
```

Everything else is obviously going to be there because you haven't logged out. What do you expect?

**Comment by Turbovix** [comment]
I do not understand because my password is displayed; I am using the official version 3.7 without modification.
But as you say you do not see problem then skip the ticket.

Thank you.

**Comment by tananaev** [comment]
Are you sure you haven't changed the password during the session? There might be some problem there, but you need to give me steps to reproduce it.

**Comment by Turbovix** [comment]
The problem occurs after you try to enter a username and password nonexistent and then enters a valid username and password, then ask to inspect, terminal and you will see the link to open the information.

**Comment by tananaev** [comment]
Just tested it on the demo server. Not reproducible.

**Comment by Turbovix** [comment]
@tananaev  the demo server is the same problem!

`{"id":37555,"attributes":{},"name":"teste500","email":"mkmt.es@mail.com","readonly":false,"admin":false,"map":null,"distanceUnit":null,"speedUnit":null,"latitude":0.0,"longitude":0.0,"zoom":0,"twelveHourFormat":false,"password":"123456"}`

![captura de tela de 2016-10-19 08-01-34](https://cloud.githubusercontent.com/assets/3914126/19514734/6a21d660-95d3-11e6-977e-f11db613ce83.png)

**Comment by tananaev** [comment]
Doesn't happen for me:
![screen shot 2016-10-19 at 11 13 52 pm](https://cloud.githubusercontent.com/assets/1161863/19514911/c80f033c-9651-11e6-8833-0482a9f4847d.png)

I guess you are doing something differently, but I'm not sure what exactly.

**Comment by Turbovix** [comment]
first you try to enter a username and password that do not exist and then try to use a valid username and password, then you will be able to inspect the error using the terminal browse and access information.

**Comment by Turbovix** [comment]
The log of the previous session using user and wrong password should not be written, because after you log on using the valid username and password, this information is also saved in the previous log and are in evidence.

**Comment by tananaev** [comment]
I think you are misunderstanding what's happening. The link that you are opening is the session resource URL. It's the same, it's not unique to attempt.

I actually found the problem. It happens only when you registered a user or modified password recently.

**Comment by tananaev** [comment]
The problem is fixed.

**Comment by Turbovix** [comment]
You are right! sorry for bad English! Thanks for the feedback!
