### ISSUE TITLE
Filters logging

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#2458]
Hello Anton,
When I look at the logs for the filtering, I can see things like this:
```
2016-10-19 08:46:41  INFO: Position filtered by Duplicate filters from 4
```
However, unless I look into the database itself, there is no way to tell which device is "4".

Would it be better to incorporate the device identifier (or name) in the logs or to put the deviceId on the web interface?

**Comment by tananaev** [comment]
I don't think it's a good idea to show internal id to the user in the web interface. Logging unique id is a better option.

**Comment by renaudallard** [comment]
Why isn't this a good idea? Confusion?

If we log unique id, then the user still has to figure out which device it is since it's also not clearly shown in the web interface unless you click on edit for each device. Or maybe, the unique id could be shown in the web interface in a column not shown by default.

**Comment by renaudallard** [comment]
Note that the deviceId could also be in a column not shown by default.

**Comment by tananaev** [comment]
Yes, confusion. User has to entered unique id, so he must know what it is.

We can add it to list of columns, but then most people probably won't know that it's there.

**Comment by renaudallard** [comment]
That can be documented. Many people won't check logs like this anyway. Web interface is mostly for users and "lambda users" don't have access to the logs anyway, so no worries if they don't know that the column is there.

**Comment by renaudallard** [comment]
Check https://github.com/renaudallard/traccar-web/commit/0978b6eb284d34f6b1ad5593c8b7cff5209a105a

**Comment by tananaev** [comment]
I think I misunderstood. I was thinking to add "uniqueId" hidden column. I don't want to make internal id visible to regular users.

**Comment by renaudallard** [comment]
But then you also need to make the logging show the "uniqueId"

**Comment by tananaev** [comment]
Correct, but it shouldn't be hard. We do it in other place. For example when we log decoded position.

**Comment by renaudallard** [comment]
OK, here it is :)
https://github.com/tananaev/traccar/pull/2461

**Comment by renaudallard** [comment]
You already have the pull request, so it's useless to keep this issue open
