### ISSUE TITLE
Nominatim reverse geocode issue

### ISSUE THREAD

**Issue by kaustubhlohiya** [tananaev/traccar#2462]
HI,

I am using traccar 3.6 and have set up my own nominatim server. When i hit the server with following link http://xxxxxxxxxx/nominatim/reverse.php?lat=18.952013&lon=72.958817 i get the response as following
```xml
reversegeocode timestamp="Wed, 19 Oct 16 20:28:49 +0530" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="lat=18.952013&lon=72.958817">
<result place_id="1429569" osm_type="way" osm_id="383744546" ref="NH348" lat="18.940255" lon="72.9657963">
NH348, Sheva, Greater Bombay, Maharashtra, 400051, India
</result>
<addressparts>
<road>NH348</road>
<village>Sheva</village>
<county>Greater Bombay</county>
<state>Maharashtra</state>
<postcode>400051</postcode>
<country>India</country>
<country_code>in</country_code>
</addressparts>
</reversegeocode>
```
However when i try to use nominatim with traccar, the address is always returned as **null** . The following is the snippet of of traccar configuration 
```xml
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>nominatim</entry>
<entry key='geocoder.url'>http://xxxxxxxxxxxxxxxxx/nominatim/reverse</entry> 
```
Any help would be highly appreciated. Thanks a ton

**Comment by hackerunet** [comment]
please send me your configuration file, I can fix it for you.

**Comment by tananaev** [comment]
Why did you omit ".php" at the end? I think it should be
```xml
<entry key='geocoder.url'>http://xxxxxxxxxxxxxxxxx/nominatim/reverse.php</entry>
```

**Comment by hackerunet** [comment]
As long as I know and have in my own nominatim server, if you have well configured the server the string should be:
`http://xxxxxxxxxxxxxxxx/nominatim/reverse`
remove the .php because if you followed the nominatim documentation the .php is automatically interpreted by the web server.

**Comment by tananaev** [comment]
But the he needs to check URL without php as well:
```
http://xxxxxxxxxx/nominatim/reverse?lat=18.952013&lon=72.958817
```

**Comment by hackerunet** [comment]
add this to the anton's string:
`&format=json`

**Comment by kaustubhlohiya** [comment]
Hi i have hit the URL in the browser without PHP extension and it still works. I have also tried and did add format=json in the browser URL and i get the response in JSON format. For some reason it just does not work in traccar. Here is the response i got on hitting the following link

http://xxxxxxxxxxxxx/nominatim/reverse?lat=18.952013&lon=72.958817&format=json

Response:

```
{
  "place_id": "1429569",
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright",
  "osm_type": "way",
  "osm_id": "383744546",
  "lat": "18.940255",
  "lon": "72.9657963",
  "display_name": "NH348, Sheva, Greater Bombay, Maharashtra, 400051, India",
  "address": {
    "road": "NH348",
    "village": "Sheva",
    "county": "Greater Bombay",
    "state": "Maharashtra",
    "postcode": "400051",
    "country": "India",
    "country_code": "in"
  }
}
```
[traccar.xml.zip](https://github.com/tananaev/traccar/files/540962/traccar.xml.zip)



I am attaching the traccar configuration file here for your reference. Thanks a lot for helping me out

**Comment by tananaev** [comment]
Response looks fine. There must be some problem with requesting URL on the server. I would recommend to debug Traccar code and see what's happening.

**Comment by hackerunet** [comment]
my suggestion is, using CURL make a request from your server to the nominatim server, then make an iptables -F if you are using linux, if using windows, remove any anti virus or firewall from the system and check again, look using mysql console in tracking table so you can check if there is some data, finally, get the latitud and longitud you are receiving from your device and use it to check the respond using the browser, to discard missing maps from your nominatim instance.
regards

**Comment by kaustubhlohiya** [comment]
@tananaev , @hackerunet : Thanks a lot for the help. I finally figured out the problem and was very stupid. The firewall was preventing traccar from communicating with nominatim. Its working fine now, really appreciate all the effort and prompt replies.

**Comment by eduteko** [comment]
> por favor envíeme su archivo de configuración, puedo arreglarlo por usted.

puedes ayudarme por favor...

**Comment by eduteko** [comment]
> por favor envíeme su archivo de configuración, puedo arreglarlo por usted.

please help me...
