### ISSUE TITLE
traccar MongoDB development

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#2463]
Dear Anton, is glad to say hi again, I'm trying to build the mongodb traccar version and I need a hint about this:
1) In `/traccar/src/org/traccar/database` there are all database related classes but I see a lot of SQL handlers, so, once I try to change the default mysql jdbc driver for mongodb driver I suppose traccar will fail immediately because all classes uses SQL specific functions to handle Exceptions and query builders and much more so I need to know if there is any other aspect that needs to be updated outside the `/traccar/src/org/traccar/database` folder in order to finally get last traccar release stable and fully compatible with mongodb.
2) Where are all database definitions? in order to change everything to automatically create a mongodb schema definition on startup
3) Is the config file able to process mongodb queries by default or do this need to be updated in another part of the software to create nosql queries? is it related to the QueryBuilder class??

This is all I need so far, I'm ending up the new nodejs, angular version of the software and I'm planning to get traccar server up and running for mongodb this weekend.
Cheers.

**Comment by tananaev** [comment]
1. If exceptions are different, you obviously need to change the code.
2. They are in "schema" folder.
3. I haven't tried MongoDB with Java, so I don't know the answer.

**Comment by hackerunet** [comment]
fair enough, thanks a lot, I'll post the results here, I have already changed the driver and saw all errors, currently updating everything, I'll fork your repository and update the advances...
Regards.

**Comment by tananaev** [comment]
This might be helpful:

https://github.com/michaelloliveira/traccar-mongodb

**Comment by hackerunet** [comment]
Mongodb compatible traccar it's under development in https://github.com/hackerunet/traccar 
Collaborators are welcome.

**Comment by fcabrera23** [comment]
Hi @hackerunet have you finished traccar mongo dev? Thanks

**Comment by jpmens** [comment]
Follow the link to that repository; last commit 2Y ago.

**Comment by hackerunet** [comment]
This was not implemented due to the traccar restful api release and the
forwarding feature, both two makes possible easy mongodb implementations
without having to refactor traccar
