### ISSUE TITLE
Insert position directly to mysql database positions table

### ISSUE THREAD

**Issue by iotologist** [tananaev/traccar#2465]
I use SMS to receive coordinates, I tried to insert the coordinates with their proper device id but it won't show on map.

Please help :(

**Comment by renaudallard** [comment]
Did you update the positionId in the devices table?

**Comment by tananaev** [comment]
Please next time don't duplicate threads:

https://www.traccar.org/forums/topic/how-to-insert-position-to-database-via-url-or-api/
