### ISSUE TITLE
demo.traccar.org - no mail notifications

### ISSUE THREAD

**Issue by boblemus** [tananaev/traccar#2468]
Hi,

I've registered for an account at demo.traccar.org and have configured two GPS devices, one a tk103 and one an Android phone. I have set up notifications to test how they work. Web notifications work just fine (is there a way to set up per-device notifications, by the way) and I see in reports that events are generated. But I do not receive any mail alerts, despite having this configured. Events report confirms the events. 
Are mail alerts enabled on the demo server? Or do I have a misconfiguration somewhere?
My account ID is konk5 at artirio dot dk.

Thank you for any help you can offer :)

Best regards,
-Allan Jensen

**Comment by tananaev** [comment]
Have you configured SMTP server for your user account?

**Comment by boblemus** [comment]
Can I do that on the public demo.traccar.org server? If so, where do I do that?

**Comment by tananaev** [comment]
Yes, you can. More details here:

https://www.traccar.org/forums/topic/smtp-config-for-notifications/

**Comment by boblemus** [comment]
Perfect - that does work indeed! 
I would like to thank you for the support you've given; I honestly can't recall when I have received such swift and precise assistance before. This is an example to be learned from by others - THANK YOU :)
