### ISSUE TITLE
Watch protocol terminal status

### ISSUE THREAD

**Issue by marko89kv** [tananaev/traccar#2473]
I'm trying to read terminal status value, which is an 8 digit number in watch protocol, since it has the information if the watch is on or off the hand. I've tried adding 
`.number("xxxxxxxx")                  // status`
to the PATTERN_POSITION, but when trying to build, the tests are failing, saying that there is no group 19. Any help?

The terminal status is in the test strings

**Comment by tananaev** [comment]
You haven't added any capturing group. I'm guessing that you are trying to retrieve the value, but you are not capturing any value, that's why it's failing.

**Comment by marko89kv** [comment]
Sorry, I've forgot to add, yes I am capturing a value, after steps:
```

position.set("steps", parser.nextInt());
position.set("tumbles", parser.nextInt()); //capturing tumbles
position.set("terminalStatus", parser.nextInt()); //capturing terminalStatus
```

**Comment by tananaev** [comment]
Please read about regular expressions and how to capture values. From what I can see, you are not doing it.
