### ISSUE TITLE
sql-mode="ANSI_QUOTES"

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2475]
hi,

Are you aware of anything that would break if I set the sql-mode to ANSI_QUOTES? I am using MySQL database. From the documentations it says

**Setting sql-mode to ANSI_QUOTES has the following effect**

> Changes " to be treated as `, the identifier quote character. This may break older DB applications which assume that " is used as a string quote character.

Thanks,
R.W

**Comment by tananaev** [comment]
It shouldn't break anything.

**Comment by m-menon** [comment]
Thanks :+1:
