### ISSUE TITLE
Reports not working

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#2483]
Hello,
I tried a snapshot of after the merge of pull request #2480 and it seems I can't get reports anymore.
I can configure a report, but when I click on show or export, it does nothing. I have tested both with firefox and chrome.
The debugging console reports: "TypeError: data is null" in MapController.js line 178

Note: there are also errors in extjs on cloudflare: unreachable code after return statement

**Comment by tananaev** [comment]
Have you taken latest `traccar-web` changes as well? There have been a lot of changes to the reports.

**Comment by renaudallard** [comment]
yes, I have a traccar-web of the same time

**Comment by renaudallard** [comment]
I have cleared the browser cache.
Traccar is running behind a ssl proxy with the following headers:
        add_header      Cache-Control   no-cache;
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload;";
        add_header x-frame-options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";

**Comment by tananaev** [comment]
Reports work fine for me with the latest source. You must be missing something. Are you using debug version of the web interface or have you compiled a release version?

**Comment by renaudallard** [comment]
I am using the debug version (actually, I renamed debug.html in release.html)
The headers are not responsible for the problems, as it still shows up without them.

**Comment by tananaev** [comment]
I can only guess what's wrong. Check network requests in the browser console.

**Comment by renaudallard** [comment]
`
https://xxxxxxxxxx/api/reports/route?_dc=1477378340025&deviceId=6&type=allEvents&from=2016-10-24T22:45:00.000Z&to=2016-10-25T06:50:58.000Z&page=1&start=0&limit=25

500 Request failed

`

**Comment by tananaev** [comment]
What's in the response?

**Comment by Abyss777** [comment]
Also there should be right "Accept" header in request.

**Comment by renaudallard** [comment]
Not something really useful:
`<!DOCTYPE<html><head><title>Error</title></head><html><body>500 - Server Error</body></html>`

Headers
Cache-Control: must-revalidate,no-cache,no-store
Connection: keep-alive
Content-Length: 92
Content-Type: text/html; charset=ISO-8859-1
Date: Tue, 25 Oct 2016 06:56:22 GMT
Keep-Alive: timeout=5
Server: nginx

**Comment by tananaev** [comment]
It is useful. It means request never got to the REST resource handler. Possibly correct `Accept` header was missing in the request. I would recommend to try without proxy.

**Comment by renaudallard** [comment]
Same issue without the reverse proxy.

request headers:
Host: 91.183.56.64:8082
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Referer: http://91.183.56.64:8082/
Cookie: JSESSIONID=jlps8jdyncp5midxxz8j9tu0
Connection: keep-alive

response headers
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 92
Content-Type: text/html; charset=ISO-8859-1
Date: Tue, 25 Oct 2016 07:08:21 GMT
Server: Jetty(9.2.19.v20160908)

**Comment by tananaev** [comment]
Then there must be some problem with back-end.

**Comment by renaudallard** [comment]
OK, my bad, there was something missing in the libs. Sorry for the noise.
