### ISSUE TITLE
Storing the database queries in the configuration file

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#2484]
Hello,
Is there any reason why database queries are stored in the main configuration file?
A normal user should not have to modify those queries and I think they should be updated automatically each time there is an update in traccar.

**Comment by tananaev** [comment]
A lot of people are using Traccar as a back-end with their own system and database. It this case, they modify queries to store data directly in their database schema.

**Comment by renaudallard** [comment]
I can understand people modifying them to fit their own schema, but is it the most common use?
Perhaps there should be a "default queries" and if queries are found in the main config, then those override the default ones.

**Comment by tananaev** [comment]
Might be a good idea to have default queries, but then you will break it for everybody who uses their own set of queries. They would have to specify all queries instead of just the ones they need.

One option I was thinking about is to split queries into a separate config file. Even better would be an option to "include" extra config files into the main one, so you can split config into seperate modules.

**Comment by renaudallard** [comment]
I think splitting queries in a separate configuration file doesn't change anything as you will still have to update them manually on each upgrade.
Of course having 3 separate files for server, database and protocol configs would already make things clearer and easier to update. Actually, protocols section in the config would also be nice if it updates automatically on each upgrade.

Maybe having default queries, and then in the configuration file being able to specify things like:
`<entry key='database.loginUser.override'>`
or `<entry key='override.database.loginUser'>true</entry>`

**Comment by tananaev** [comment]
Splitting configuration file would help. You could just take the latest config with queries because you know that you want to use defaults and you haven't changed anything there. Same for protocols.

**Comment by renaudallard** [comment]
Indeed, but that still means you need to copy the default ones when updating.
I could be seamless if there was something like:
if database.selectServers exists then use it
else use default

**Comment by Abyss777** [comment]
Config file is updated automatically by installer when you upgrade.

**Comment by renaudallard** [comment]
But that's only for the platforms which have an installer. Having a default and an override would work on all platforms and simplify the installer task.

**Comment by tananaev** [comment]
I just thought of a better idea than importing configuration. We can have a default configuration file in addition to a regular config. If parameter is defined in the regular config, we use that value, otherwise use from default config. That should be fairly simple to implement.

**Comment by Abyss777** [comment]
I see one problem, if we use only a few protocols, how we will disable other? Now we just deleting them from config.

**Comment by tananaev** [comment]
Yes, I actually though about it as well. Don't have any solution. We can possibly bring back "enable" flags for protocols.

**Comment by renaudallard** [comment]
if port == 0, disable the protocol

**Comment by Abyss777** [comment]
Anyway, you have to put more then 120 lines to config just to disable unused protocols.

May be add some logic, if regular config has at least one protocol - enable only them, if does not - enable all from default config.

**Comment by tananaev** [comment]
That's actually a good idea.

**Comment by tananaev** [comment]
I have implemented default config. For now it doesn't solve the problem with removing protocol because I couldn't think of any simple clean way to do it.
