### ISSUE TITLE
Device positionid Not updating (Some devices)

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2486]
Dear @tananaev 

I have a particular device, working on GT06 protocol., the device is sending updates, and I can see it reflect in Position Table, However the device tables position id is selectively getting updated.

I have attached screenshot of both device tables entry and positions latest entry for that device. Please advise how should i go about with troubleshooting this?

![device](https://cloud.githubusercontent.com/assets/1138485/19691511/204f2e10-9af2-11e6-8961-d7993e804ccd.jpg)
![position](https://cloud.githubusercontent.com/assets/1138485/19691510/204aa304-9af2-11e6-869b-5171bdd9c3ec.jpg)

**Comment by jaimzj** [comment]
Just adding an update,.

1. I had restarted traccar server twice, still it did not resolve.
2. I stopped server for 5 mnt, and started it. not solved.
3. I removed the entry for the device, then re added a new entry for same device.
4. Restart server (Now it works perfectly).

Not sure why it happened, there is nothing in both wrapper log nor traccar  server log.

**Comment by tananaev** [comment]
So, what am I supposed to see on the screenshots? Please provide some more details about the problem. Where is the position with the id from the devices table?

**Comment by jaimzj** [comment]
Hello Anton,

Sorry for sharing less information.

What I did was in position table ran a query to retrieve deviceid 413's latest updates. (Thats the position table screenshot).

The device Table screenshot contains the lastpositionid 9565035 (Row in position also attached this time)

However considering the position table already having row 9639125 being the actual lastpositionid, my concern was why devices lastpositionid did not update.

My first thought was, maybe the imei did not register in traccar, well and a traccar restart will solve the problem, but it did not.

Eventually to get it started, i removed that device, and added a new device entry with same imei. and this time it worked. (after i restarted traccar) this is a totally new entry made in device table.

I hope I  haven't confused it up, here :)  my only concern was to see, if this was a bug of any sort,. Tried checking logs did not find any unusual errors either.

![row](https://cloud.githubusercontent.com/assets/1138485/19702574/d192ec2c-9b1d-11e6-83ea-f936b43ef08a.jpg)

**Comment by tananaev** [comment]
If you carefully look at the device time in the position, it's later than the other ones. That's one latest doesn't update, because according to the device time, that was the latest one.

**Comment by jaimzj** [comment]
Ohhhhhh, Thanks a lot or that Anton :) I totally Never noticed that part :+1:

**Comment by jaimzj** [comment]
@tananaev could this be a resolvable problem? 

If a user adds a device, and for some reason forgets to change the time zone of the device, and the device first sends a future date, then later user updates the device time zone setting. and the device sends the current date /time, in such case now the update does not happen.

I have a previous version of traccar running, which does not have this problem, however in 3.7 it does not update position id, but stores position updates,.

**Comment by tananaev** [comment]
All previous versions of Traccar have the same logic.

The solution is to remove and add device again.

**Comment by Ltech2** [comment]
hello tananaev,
thank you to making traccar, I am a novice.
I react on this log.
**Is it possible to get te update time for the device in stead of the device time?**
I lost lot of time by testing with a premade log file.
At a point I get back to first position log to make a permanet test loop.
So my tracking stopped and I look for a non existing bug

Thanks

**Comment by tananaev** [comment]
It's not possible. I don't see why you would want to do that. If you want to discuss it further, please create a separate issue.
