### ISSUE TITLE
Is it possible to pass battery Level from traccar to OpenGTS through forward.url gprmc ?

### ISSUE THREAD

**Issue by esteves67** [tananaev/traccar#2487]
Hello

Is it possible to pass battery percentage from traccar (extended info/battery) 
to OpenGTS Gprmc ('batt' parameter) through forward.url?

Forward URL is working without the batt parameter, for geozone / geofence notifications (it works because of the gprmc parameter).
But it would be good to have the batt parameter for battery low notifications..

Currently my config in traccar.xml is

```
<entry key='forward.enable'>true</entry>
<entry key='forward.url'>http://127.0.0.1:8080/gprmc/Data?id={uniqueId}&amp;code=0x0000&amp;batt={batteryLevel}&amp;gprmc={gprmc}</entry> 
```

I tried batt={batteryLevel} to pass battery level to forward.url, but no success..

```
INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address, batteryLevel)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:fixTime), @statusCode, :latitude, :longitude, :speed * 1.852, :course, :altitude, :extended_info, UNIX_TIMESTAMP(NOW()), :address, ExtractValue(:extended_info, '/info/battery');
```

Thanks

**Comment by tananaev** [comment]
It's possible to send all attributes using `{attributes}` parameter, but not battery separately.

**Comment by esteves67** [comment]
Thank you so much Mr. Anton +1:  :D

**Comment by esteves67** [comment]
The old Android APP Traccar sends message in gprmc protocol right? Where can i find that "old" app? 
It can be used with traccar 3.4?

**Comment by tananaev** [comment]
Do you mean Traccar Client app? Yes, it's supported by any version of server.

You can build it from source using one of the tags:

https://github.com/tananaev/traccar-client-android/releases

**Comment by esteves67** [comment]
https://www.traccar.org/traccar-client-protocol/

It says that the old Traccar Client sends message in gprmc mode,
I know that there are alot of GPRMC OpenGts clients, but i want to use traccar, because its much more better, in performance, also it has many more protocols than OpenGTS, etc...

**Comment by tananaev** [comment]
Traccar server does still support old protocol if that's what you are asking.

You can also compile older version of Traccar Client if you want.
