### ISSUE TITLE
traccar is not working

### ISSUE THREAD

**Issue by sourabhkhare** [tananaev/traccar#2488]
Dear Sir,

I found the following error 
FATAL  | wrapper  | 2016/10/26 09:48:17 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory
ERROR  | wrapper  | 2016/10/26 10:15:58 | 24821 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/10/26 10:15:58 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory
ERROR  | wrapper  | 2016/10/26 22:24:03 | 1440 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/10/26 22:24:03 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory
ERROR  | wrapper  | 2016/10/26 22:57:04 | 4651 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/10/26 22:57:04 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory
ERROR  | wrapper  | 2016/10/26 22:57:26 | 4809 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/10/26 22:57:26 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory
ERROR  | wrapper  | 2016/10/26 23:02:27 | 5307 pid file, /opt/traccar/bin/./traccar.pid, already exists.
FATAL  | wrapper  | 2016/10/26 23:02:27 | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: No such file or directory

**Comment by tananaev** [comment]
Is the problem solved?

**Comment by sourabhkhare** [comment]
yes sir,

is the problem solved.i have removed the traccar.pid file and again restart the traccar service.
