### ISSUE TITLE
Having my own tables inside traccar database

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2496]
hi,

I use MySQL with Traccar. Do you think it would be a bad (or good?) idea if I had couple of my own tables in traccar database? I'd be using these tables to store some additional information about the devices, users etc. I could have these tables in a different database too but it unnecessariy complicates things I guess - so thought of creating those tables in traccar db itself.

Cheers,
M.M

**Comment by tananaev** [comment]
It should be fine.

**Comment by m-menon** [comment]
cool thanks :+1:
