### ISSUE TITLE
Tramigo T23 ignition direction issues

### ISSUE THREAD

**Issue by gpproton** [tananaev/traccar#2504]
Hi @tananaev 
i been having issues with **Tramigo T23** devices as after ignition event has occurred it is only saved in database once till another ignition event is performed. To be more clear when ignition is turned on unlike other devices I've used before it's only sent once to server and when it is turned of it is only once too.
It will be good if the last ignition status is retained till a different one is received, that might fix the problem.
And for the direction it's still not working since direction is declared as  cardinal point like SW NE i'm not sure but i'll really appreciate you checking this @tananaev , thanks in advance.

**Comment by tananaev** [comment]
I think what you are looking for is #2325. It's already implemented and will be available in the next release.

**Comment by gpproton** [comment]
Ok thanks for the reply @tananaev but like when will there be a new release.

**Comment by tananaev** [comment]
Hopefully in a couple of weeks time.

**Comment by gpproton** [comment]
Ok cool
