### ISSUE TITLE
Identify the protocol and the port for the device

### ISSUE THREAD

**Issue by prashantgaikwad** [tananaev/traccar#2507]
The data that is received on the server logs is as follows. I'm not able to identify what protocol is this. What port should I send the data on?
```
,,01,868004022773884,$GPRMC,124421.000,A,2245.2116,N,07551.9939,E,0000,199.27,031116,,,A*79
,#01000110,0.5588539,-1.00,1.028,0,-1,0.000,0,28,BH,
```
868004022773884 is device id.

**Comment by tananaev** [comment]
It's Xexun protocol, port 5006 in Traccar.

**Comment by w32gold** [comment]
Just wanna ask how you were able to decipher the logs and identify the
protocol..
thanks.

**Comment by tananaev** [comment]
I usually use this:

https://www.traccar.org/identify-protocol/

Actually it's not Xexun, but it's somewhat similar. I guess question mark symbols indicate that it's a binary protocol, so you should provide original HEX instead of converting it to text.

**Comment by prashantgaikwad** [comment]
Thanks for the reply @tananaev 
Here is the hex string that I received.
022c142c30312c3836383030343032323737333838342c244750524d432c3030323835392e3030302c412c323234332e373631392c4e2c30373535332e333938342c452c303030302c3237362e33382c3037313131362c2c2c442a37370d0a2c2330313030303131302c35322e37342c2d312e30302c312e3033322c302c2d312c302e3030302c302c32362c42482c03

**Comment by tananaev** [comment]
It seems like this protocol is not supported yet. I need protocol documentation to implement it.

**Comment by mudrasonavane** [comment]
I am using TK500 gps device. Don't know which port to use

**Comment by tananaev** [comment]
@mudrasonavane, please next time create a separate thread. Don't just comment on a random unrelated threads.

As for your device, check this page:

https://www.traccar.org/ports-for-tk-gt-and-other-gps-devices/

**Comment by prashantgaikwad** [comment]
@tananaev Even I don't have the documentation. Will share with you once I have it. Closing the thread for now. Thanks for your help.
