### ISSUE TITLE
Location update on Map (Push)

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2508]
hi,

As far as Java is concerned, I am a noob. So just wanted to ask you if I could use some kind of push mechanism to update the marker on my custom map. Could I work with some web sockets or something so that I don't have to poll periodically? Any pointers will help. Thanks - M.M

**Comment by tananaev** [comment]
Yes, you can use WebSockets. That's what official web interface and apps do.

**Comment by m-menon** [comment]
cool thanks. Any links with a simple implementation that I could refer to, or build upon?

**Comment by tananaev** [comment]
Here is the JavaScript code: [Root.js](https://github.com/tananaev/traccar-web/blob/master/web/app/controller/Root.js#L104).

**Comment by m-menon** [comment]
excellent, thanks :100:

**Comment by kirantpatil** [comment]
Dear @m-menon, do you have the plain javascript code for it ? Since current code(asyncUpdate: function) is using Extjs.

Thanks.
