### ISSUE TITLE
Unable to see Server Settings

### ISSUE THREAD

**Issue by DavidFEUDJIO** [tananaev/traccar#2510]
Hello, I installed Traccar 3.7 on CentOS VPS. 
When I click on "Settings" menu, I can not see Server for configurations.
What can I do to make it appear? Thank a lot for your help.

**Comment by tananaev** [comment]
You have to login as a user that has admin privileges.

**Comment by DavidFEUDJIO** [comment]
Hello thank for the quick response
I did it, but the only available commands on "Settings" menu are:
- User
- Global 
- Notifications and 
- Default Preferences

**Comment by tananaev** [comment]
Can I see a screenshot? Traccar doesn't have the options that you named.

**Comment by DavidFEUDJIO** [comment]
Find attached the screenshot
[image: Images intégrées 1]

2016-11-06 11:19 GMT+01:00 Anton Tananaev <notifications@github.com>:

**Comment by DavidFEUDJIO** [comment]
Understood. 

I was working on Litvak version.

**Comment by DavidFEUDJIO** [comment]
Thk a lot for for your assistance.
