### ISSUE TITLE
Missing ../../ext-6.0.1 while installing traccar

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2516]
Hi,

Operating system: Ubuntu 14.04.4 LTS \n \l
```
traccar/setup$ java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
```
traccar/setup$ git branch
* (detached from v3.7)
  master
```
I am trying to install traccar and I am getting below error.
```
traccar/setup$ ./package.sh 3.7
Missing ../../ext-6.0.1 (https://www.sencha.com/legal/GPL/)
```
Please help me to resolve this issue.

**Comment by tananaev** [comment]
Why are you trying to build your own installer?

**Comment by kirantpatil** [comment]
Sir, I don't know how to install Traccar.
Please provide the installation steps.

**Comment by tananaev** [comment]
Download official installer and follow instructions in the readme file:

https://www.traccar.org/download/

**Comment by kirantpatil** [comment]
Thank you. It is started working.
