### ISSUE TITLE
Problemas con temperaturas bajo cero

### ISSUE THREAD

**Issue by fmelin** [tananaev/traccar#2521]
Estimados, muy buenas noches.

estoy teniendo problemas para capturar las temperaturas bajo cero del dispositivo Teltonika FM5300, el cual me muestra un valor como este 42949672960 al recibir temperaturas bajo cero, los sensores son el io72, io73

atento a sus comentarios saludos cordiales.
Francisco Melín C

**Comment by tananaev** [comment]
There is better chance of getting your problem solved if you write in English.

**Comment by tananaev** [comment]
Closing this as a duplicate of #2522.
