### ISSUE TITLE
Problem Dallas temperature teltonika fm5300

### ISSUE THREAD

**Issue by fmelin** [tananaev/traccar#2522]
Dear, good evening.

I'm having trouble capturing the temperatures below the Teltonika FM5300 device, which shows me a value like this 42949672960 when receiving temperatures below zero, the sensors are io72, io73

Attentive to your comments best regards.
Francisco Melín C

**Comment by tananaev** [comment]
You have to get documentation from Teltonika to be able to decode IO values.

**Comment by fmelin** [comment]
Dear, good day.

I attach the document sent by Teltonika, sorry for the delay.

Note: All documents are confidential

Best regards.
Francisco Melín C.

De: Anton Tananaev [mailto:notifications@github.com]
Enviado el: jueves, 10 de noviembre de 2016 0:00
Para: tananaev/traccar
CC: fmelin; Author
Asunto: Re: [tananaev/traccar] Problem Dallas temperature teltonika fm5300 (#2522)


You have to get documentation from Teltonika to be able to decode IO values.

**Comment by tananaev** [comment]
If it's confidential you probably shouldn't send it directly to a public GitHub thread. Also, GitHub doesn't handle email attachments.

**Comment by fmelin** [comment]
Attached is the fm5300 protocol.

Watch for your comments.
Greetings.

[FM5300-Protocols.pdf](https://github.com/tananaev/traccar/files/601443/FM5300-Protocols.pdf)

**Comment by tananaev** [comment]
Looks like this is what you are looking for:
![screen shot 2016-11-20 at 12 07 45 pm](https://cloud.githubusercontent.com/assets/1161863/20459052/0184fe92-af1a-11e6-8aa1-b2394d5684f9.png)

**Comment by fmelin** [comment]
Dear, is not what I need.
As mentioned above, the problem is that of tracer server that does not decode the temperatures below zero (negative) of io72, io73 and io74.
Please help me to solve the problem, if it is necessary to pay some fee, let me know how to do it.

**Comment by tananaev** [comment]
Do those ids mean the same thing for all Teltonika devices?

**Comment by tananaev** [comment]
As far as I can tell, the protocol is the same. The only difference might be IO mapping. I need a universal way to map IO ids to values. Please ask Teltonika if it's possible, and if it is, then how? What do those IO values map to on other Teltonika devices?

**Comment by fmelin** [comment]
Dear, already detect the problem.
The problem is the decoding since when decoding the message that appears in the log of TRACCAR in line "2567"
  0000000000000051080100000158d19527b800d5db0af1ec01c6c8020b00460d00000010060101020003000400f0001502070900140a00020b00031300034327b24238de1800000348ffffff744900000bb84a00000bb8000100004af5

![log](https://cloud.githubusercontent.com/assets/23340246/21071025/743d2312-be72-11e6-8181-f5c04559bea5.png)

[tracker-server.log.20161205.txt](https://github.com/tananaev/traccar/files/643550/tracker-server.log.20161205.txt)

[BasedeDatos.zip](https://github.com/tananaev/traccar/files/643551/BasedeDatos.zip)




It decodes it as decimal taking the value of 4294967156, but should be at -140 which is the decoding in 32bit (4bytes), which indicates the teltonika protocol (attached).
![teltonikaprotocol](https://cloud.githubusercontent.com/assets/23340246/21071041/33765398-be73-11e6-8295-1efb217a2bff.png)

Please help them to solve this problem.

Beforehand thank you very much!!!

**Comment by tananaev** [comment]
It's a negative number. At the moment Traccar decoder everything as positive integers. If you replace `readUnsignedXxx` with `readXxx`, it will work.

**Comment by fmelin** [comment]
Please let me know how to make the change, since I am not interested in Java. thank you very much.

**Comment by tananaev** [comment]
You have to make the change and compile source code. If you need further help with that, send me an email.

**Comment by fmelin** [comment]
What is your email? Or how to perform this procedure?

I have Traccar server v3.7 installed on Windows server 2012.

Download the source code and mount it in netbeans but I do not know how to compile it and pass the new files to the server.

**Comment by tananaev** [comment]
My email address is in profile.

**Comment by fmelin** [comment]
muchas gracias!!!
