### ISSUE TITLE
meiligao protocol Ignition Status

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2524]
Hello,

In meiligao protocol, the Ignition value is not showing up. can it be fixed?

Page 14, has the value or it..

`Bit11: Status of Input4    Engine ON/off
	If Bit11=0: Input4 is inactive; Bit11=1: Input4 is active.
`

[meiligao protocol.pdf](https://github.com/tananaev/traccar/files/583433/meiligao.protocol.pdf)

**Comment by tananaev** [comment]
It's device specific:

> For TK510

**Comment by jaimzj** [comment]
It means it cant be done on the existing protocol of meiligao? or there is another port / protocol that can be used?

**Comment by tananaev** [comment]
It means that I need to know what those bits mean for other devices.

It's Meiligao protocol, so it won't work with any other port or protocol.

**Comment by jaimzj** [comment]
Ohhh, I guess in that case the only way could be to wait it out for other device users to share some info as well...

**Comment by tananaev** [comment]
The only way is to get this information from the device vendor.

**Comment by jaimzj** [comment]
@tananaev The manufacturer has responded with the following details, and also said its the same for all devices.

input4, input 5 are for ACC detection
Input3: Door switch status
Input1:SOS button
Input2: line-broken status.
out1: control the relay to stop the car

**Comment by tananaev** [comment]
This is what I have in the original documentation:
```
(5) State: Status of input and output, in HEX string:

For GT30i/GT60

Bit0~Bit7: Reserved and default as ‘0’
Bit8: Status of Input1
If Bit8=0: Input1 is invalid; Bit8=1: Input1 is valid (be pressed/connected to negative)
Bit9: Status of Input2
If Bit9=0: Input2 is invalid; Bit9=1: Input2 is valid (be pressed/connected to negative)
Bit10: Status of Input3
If Bit10=0: Input3 is invalid; Bit10=1: Input3 is valid (be pressed/connected to negative)

For VT300

Bit 0: Status of Output1.
If Bit0=0: Out1 is closed; Bit0=1:Out1 is open.
Bit8: Status of Input1
If Bit8=0: Input1 is invalid; Bit8=1: Input1 is valid (be pressed/connected to negative)
Bit1~Bit7 and Bit8~Bit15: Reserved and default as ‘0’

For VT310

Bit0: Status of Out1
If Bit0=0: Out1 is closed; Bit0=1:Out1 is open.
Bit1: Status of Out2
If Bit1=0: Out2 is closed; Bit1=1:Out2 is open.
Bit2: Status of Out3
If Bit2=0: Out3 is closed; Bit2=1:Out3 is open.
Bit3: Status of Out4
If Bit3=0: Out4 is closed; Bit3=1:Out4 is open.
Bit4: Status of Out5
If Bit4=0: Out5 is closed; Bit4=1:Out5 is open.
Bit5~Bit7: Reserved.
Bit8: Status of Input1
If Bit8=0: Input1 is invalid; Bit8=1: Input1 is valid (be pressed/connected to negative)
Bit9: Status of Input2
If Bit9=0: Input2 is invalid; Bit9=1: Input2 is valid (be pressed/connected to negative)
Bit10: Status of Input3
If Bit10=0: Input3 is invalid; Bit10=1: Input3 is valid (be pressed/connected to negative)
Bit11: Status of Input4
If Bit11=0: Input4 is invalid; Bit11=1: Input4 is valid (be pressed/connected to positive)
Bit12: Status of Input5
If Bit12=0: Input5 is invalid; Bit12=1: Input5 is valid (be pressed/connected to positive)
Bit13~Bit15: Reserved and default as ‘0’

For VT400

Bit0: Status of Out1
If Bit0=0: Out1 is closed; Bit0=1:Out1 is open.
Bit1: Status of Out2
If Bit1=0: Out2 is closed; Bit1=1:Out2 is open.
Bit2~Bit7: Reserved.
Bit8: Status of Input1
If Bit8=0: Input1 is invalid; Bit8=1: Input1 is valid (be pressed/connected to negative)
Bit9: Status of Input2
If Bit9=0: Input2 is invalid; Bit9=1: Input2 is valid (be pressed/connected to negative)
Bit10~Bit15: Reserved and default as ‘0’
```

**Comment by jaimzj** [comment]
yes @tananaev I checked with my manufacturer, in this case the device i have that is 'for TK510' is same as

For VT310  int the above post you shared.

Myabe instead of identifying it for now as ignition, can the input values be parsed as is? at-least to get the values of each of them being active/inactive or true/false.

**Comment by tananaev** [comment]
Status field is already decoded. I don't see any good way to split it into bits if the meaning of each bit varies between devices.
