### ISSUE TITLE
when app is killed, theres no way to bring it back

### ISSUE THREAD

**Issue by juanmas07** [tananaev/traccar#2529]
After weeks of using the app, I notice that at some point the app is killed. As far as I can tell, there's no way to open it except reinstalling and re configuring. Shouldn't it has an option for re starting? Dialing traccar in the phone won't work either when the app is dead.

**Comment by tananaev** [comment]
You are talking about Traccar Client. Please create an issue in the right repository:

https://github.com/tananaev/traccar-client-android/issues
