### ISSUE TITLE
Event time parameters

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2532]
Hi,

Question about events time parameters and how to change thoes values.

How server decides to generate events like "device is offline" or "device is stopped", is it counting time and for example if no new incoming positions in 60 seconds then generates event "device is stopped"?

Does "online" and "offline" events depends on when device TCP connection starts or stops?

**Comment by Abyss777** [comment]
Here you can find some explanation about device status
https://github.com/tananaev/traccar/issues/2100

Also, stopped/moving not connected to online/offline, it is about speed.
Speed about zero - device is stopped. Speed more than zero - device is moving.

**Comment by argokask** [comment]
Thank you!
