### ISSUE TITLE
Send data to different URL's at the same time?

### ISSUE THREAD

**Issue by esteves67** [tananaev/traccar#2537]
Hi Mr. Anton 

Is it possible to send data coming from gps trackers to two different "url addresses", two destinations?

Like send data to Traccar and be stored into traccar database, and also send it to some custom front page through forward url?
(Send data to database.url and also to forward.url)

Thank you very much

EDIT: I saw another Opened Issue #1213 Data insert in to multiple tables
So i can insert the data coming from the gps to two different tables? Thats a way i see.

**Comment by tananaev** [comment]
It's not possible to have two forwarding URLs, only one. It's possible to save in the database and forward at the same time though.

It should be really easy to modify forwarding code to send to several URLs if you want.

**Comment by esteves67** [comment]
Oh ok, so if i take a look and study Issue #1213 i can reach what i want, right?

**Comment by tananaev** [comment]
It's possible to write data into two tables if that's what you want.

**Comment by esteves67** [comment]
Thats a way i can reach i want, but if i want to forward to several URLs i need to modify the java files and compile it?

**Comment by tananaev** [comment]
Correct.

**Comment by esteves67** [comment]
Traccar is pretty complete, so it store all and every data coming from the gps tracker, if i need just the Latitude, Longitude, and deviceID, modifying the sql query i can insert just these three info's to my secondary database (front end page)?

**Comment by tananaev** [comment]
Yes, correct.

**Comment by esteves67** [comment]
Thank you very much for the help and support !

**Comment by negamkpk** [comment]
how to see the values in database.

**Comment by esteves67** [comment]
Sorry for re-opening the issue

The only way to do it, is using Dynamic Query?

Im thinking of trying the bellow:

```
INSERT INTO SecondaryTable (deviceID, latitude, longitude)
            VALUES (@deviceID, :latitude, :longitude);
```
but i wont be sucessful because its already preset to store database into 

`<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES</entry>`

Can i store into two databases inside the same "START TRANSACTION; /  COMMIT;"  ?

**Comment by tananaev** [comment]
You don't need dynamic queries. Just put 2 inserts or whatever you need.

If it's the same DB server, you should be able to reference other database by prefixing table name.

**Comment by tananaev** [comment]
@negamkpk, I don't understand your question.

**Comment by esteves67** [comment]
Even with `<entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES</entry>` being set, i can reference other database from same db server by prefixing table name?

**Comment by esteves67** [comment]
Sorry i misclicked close issue, i typed a question, but i clicked "dismiss" two times than it clicked Close Issue
Sorry

**Comment by esteves67** [comment]
Thank you i will try, sorry for taking too much of your time

**Comment by negamkpk** [comment]
Hi,

The values received from the device are stored in server side.the values I
can see in the traccar webpage.

suppose I want to see the values in terminal window or any other console
window ,how to do that.

**Comment by tananaev** [comment]
@negamkpk, how is your question related to the topic? If it's not, please create a separate thread.

**Comment by esteves67** [comment]
Thank you Mr. @tananev Im doing progress in forwarding data to multiple databases, if i have any other question related to the topic I left this topic open and ask here later, Or do i close the topic and open another?

**Comment by tananaev** [comment]
You can keep this thread open till everything is working for you.

**Comment by esteves67** [comment]
Hi Mr. Anton

Thanks for helping me i got it to work,
but im trying to do another thing now - > Do you think its possible to have Traccar "standalone" and Traccar to Opengts method, working at the same time, in the same traccar.xml file? 
Like my data come from the gps tracker to Traccar and goes to Opengts through traccar, i want to after that or before it, the data also be inserted in Traccar, i tried to insert position data (latitude, longitude, id, speed e etc...) to Positions table, but it need more than that, it needs to update last position on Devices table and etc...

Do you think its possible to do it? if yes its gonna be very complicated.. Or you think it isnt possible.

Thanks for the help :D

**Comment by tananaev** [comment]
It might be possible to have full version of Traccar running and use forwarding to send data to OpenGTS as well.

**Comment by esteves67** [comment]
Thanks!

**Comment by esteves67** [comment]
Hello Mr. Anton !

Im almost reaching what i want, but i cant get through these sql query's below..
Im in a gts database connection

` <entry key='database.url'>jdbc:mysql://localhost/gts?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>`

I need to make these query's connect to the traccar database, because im in a gts database connection..

How to do these query's connect to an "outside database", is it in the same server, but its just another database, i tried variations of this for more than 4 - 5 hours trying but cant get this to work =( - > ```
<entry key='database.updateDeviceStatus'>
        UPDATE traccardevices SET status = :status, lastUpdate = :lastUpdate WHERE id = :id;
    </entry>

<entry key='database.selectLatestPositions'>
        SELECT * FROM traccar.positions WHERE id IN (SELECT positionId FROM traccar.devices);
    </entry>

    <entry key='database.updateLatestPosition'>
        UPDATE traccar.devices SET positionId = :id WHERE id = :deviceId;
    </entry>
```

Thank you very much

**Comment by tananaev** [comment]
I would recommend to do it other way around. Make "traccar" the main database and add extra queries to store data in the GTS database as a secondary thing.

**Comment by esteves67** [comment]
Thanks again!
Did what you suggested me, now its working :D

**Comment by kumareshsaran** [comment]
how to change the URL  or host name instant of demo.traccar.org

**Comment by tananaev** [comment]
@kumareshsaran, please don't comment on old closed threads.

**Comment by kumareshsaran** [comment]
yeah k thanks tananaev

**Comment by kumareshsaran** [comment]
Sorry For reopening the old thread.But i don,t know how to change the host name 
i changed the host name in swagger.json file but it will not reflect in web

**Comment by tananaev** [comment]
@kumareshsaran, again, please don't comment on old closed threads. If you want to ask question, create a new thread.
