### ISSUE TITLE
Traccar 2.10 or 2.11

### ISSUE THREAD

**Issue by esteves67** [tananaev/traccar#2540]
Hello ! xD

Do someone still have the `traccar-linux-64-2.10.zip` or `traccar-linux-64-2.11.zip` , so it can share with me? 
I need it but i can't find it =(

Thanks !

**Comment by tananaev** [comment]
You can build it from a tag:

https://github.com/tananaev/traccar/releases

**Comment by esteves67** [comment]
Thank you
