### ISSUE TITLE
websocket sample js client code

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2547]
Hi,

We have websocket access related issue at https://github.com/tananaev/traccar/issues/2201, but it is not complete.

Please share a sample working code here or in stackoverflow (Ex: http://stackoverflow.com/questions/38673851/how-to-use-traccar-api-to-get-devices).

Thanks.

**Comment by kirantpatil** [comment]
I tried below code but could not get any sessionresponse in console.log

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>try traccar api</title>
  </head>
  <body>
    <script src="js/jquery-2.2.2.min.js" charset="utf-8"></script>
    <script type="text/javascript">
      var name = "kiran"; //"kiran"; "28970"
      var uid = "31701"; //"355355059774397";

    $.ajax({
            //url: "http://[IP]:8082/api/session",
            url: "http://demo.traccar.org:8082/api/session",
            dataType: "json",
            type: "POST",
            data: {
                email: "kirantpatil1@gmail.com",
                password: "kiran123"
            },
            success: function(sessionResponse){
                console.log(sessionResponse);
                openWebsocket();
            }
        });

        var openWebsocket = function(){
            var socket;
            socket = new WebSocket('ws://demo.traccar.org:8082/api/socket');

            socket.onclose = function (event) {
                console.log("WebSocket closed");
            };

            socket.onmessage = function (event) {
                var i, j, store, data, array, entity, device, typeKey, alarmKey, text, geofence;
                console.log(event.data);
            };
        };
  
    </script>
  </body>
</html>
```

**Comment by tananaev** [comment]
The server (`demo.traccar.org:8082`) is invalid.

**Comment by kirantpatil** [comment]
So what would be the correct URL with port ?

**Comment by tananaev** [comment]
Demo server uses default HTTP port (80). You don't need to explicitly specify it.

**Comment by kirantpatil** [comment]
Just removed 8082 and same code started working thanks.

**Comment by kirantpatil** [comment]
I am getting 500 Server error while trying to connect to the socket, please find the screenshot below.
![screenshot from 2016-11-17 14 28 29](https://cloud.githubusercontent.com/assets/1178055/20382573/711729b4-acd2-11e6-8a01-f1c4ac8c1761.png)

**Comment by tananaev** [comment]
WebSocket URL should start with "ws", not "http".

**Comment by kirantpatil** [comment]
It is Firefox issue and now in chrome it is using "ws" and showing 503 error as below.
![screenshot from 2016-11-17 14 40 20](https://cloud.githubusercontent.com/assets/1178055/20382929/e6c6aeb8-acd3-11e6-9283-fc9e574bea2c.png)

**Comment by tananaev** [comment]
There might be a problem with your network provider. I would recommend to try on a local server.

**Comment by kirantpatil** [comment]
Yes, now in localhost it is running as below in Firefox but in Network tab it is not showing that websocket is connected. Is that the expected behaviour ?

![screenshot from 2016-11-17 14 51 06](https://cloud.githubusercontent.com/assets/1178055/20383411/b1b975fa-acd5-11e6-961f-8ff3e1733ee6.png)
![screenshot from 2016-11-17 14 51 56](https://cloud.githubusercontent.com/assets/1178055/20383415/b54d2ffe-acd5-11e6-9129-9c10e232079b.png)

**Comment by tananaev** [comment]
What does it look like in Chrome?

**Comment by kirantpatil** [comment]
Now I am getting on both browsers console same 503 error.

![screenshot from 2016-11-17 15 03 33](https://cloud.githubusercontent.com/assets/1178055/20383770/27a19d5a-acd7-11e6-8fe0-df0719989835.png)

![screenshot from 2016-11-17 15 04 05](https://cloud.githubusercontent.com/assets/1178055/20383827/482c3e36-acd7-11e6-92e0-9d8c1cbe8dd7.png)

**Comment by tananaev** [comment]
Please use local server.

**Comment by kirantpatil** [comment]
Yes Sir, I am using local server. Earlier socket connected from Firefox and I closed the tab to close the connection. My doubt is whether the connection is still persisting and not allowing new connections. How to close the Websocket connection in browser?

**Comment by tananaev** [comment]
Connection is destroyed when you refresh the page or close tab. Use "localhost" if it's a local server.

**Comment by kirantpatil** [comment]
The issue was authentication is not happening so created new user and password and in Firefox it started working but chrome is still showing 503 error.

**Comment by kirantpatil** [comment]
So the root cause of the issue is as below.
 I need to login to server in the browser for both Browsers then the code works on both browsers as below.

![screenshot from 2016-11-17 15 39 22](https://cloud.githubusercontent.com/assets/1178055/20385095/095e1940-acdc-11e6-9061-3f1889122b5e.png)

![screenshot from 2016-11-17 15 39 06](https://cloud.githubusercontent.com/assets/1178055/20385099/10be9ec6-acdc-11e6-8bbf-b5cea5fe95f0.png)

**Comment by kirantpatil** [comment]
If I logout from the app and refresh browser it throws 503 error.

**Comment by tananaev** [comment]
So, is the problem solved?

**Comment by kirantpatil** [comment]
I don't think it is solved. Why do I need to login to the application from browser to have websocket connection?

**Comment by tananaev** [comment]
I guess because session call doesn't work.

**Comment by kirantpatil** [comment]
So, what should I do now, to resolve this issue?

**Comment by tananaev** [comment]
Not sure. Maybe there is some problem with CORS and cookies.

**Comment by d33pak-s1ngh** [comment]
@kirantpatil  hiii tell me if you find solution for this i also have the same problem.

**Comment by kirantpatil** [comment]
hello @d33pak-s1ngh, no I could not find the solution yet.

**Comment by d33pak-s1ngh** [comment]
ok thanx share if you found something.

**Comment by kirantpatil** [comment]
This issue is resolved with the working example https://github.com/tananaev/traccar-web/blob/master/web/simple/app.js.

Thanks a lot @tananaev

**Comment by CodeWithOz** [comment]
@kirantpatil can you please briefly explain what the code in your example does that solves the problem? I'm having this problem but not using this library, so I'm not sure how to transfer your fix to my situation.

**Comment by AddoSolutions** [comment]
I am having the same issue, unable to resolve

**Comment by tananaev** [comment]
Please no comments on an ancient closed thread. If you want to ask something, there's [forum](https://www.traccar.org/forums/).
