### ISSUE TITLE
[How to] access apis from websocket

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2551]
Hi,

The below websocket code by default calls positions api as below. I would like to access other apis like devices, users and so on.

Please let me know how to access other apis.

![screenshot from 2016-11-18 12 59 14](https://cloud.githubusercontent.com/assets/1178055/20422201/d7157420-ad8e-11e6-96b2-9fd3875effe7.png)

Source Code:
------
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>try traccar api</title>
  </head>
  <body>
    <script src="js/jquery-2.2.2.min.js" charset="utf-8"></script>
    <script type="text/javascript">
     

    $.ajax({
            //url: "http://[IP]:8082/api/session",
            url: "http://demo.traccar.org/api/session",
            dataType: "json",
            type: "POST",
            data: {
                email: "kirantpatil1@gmail.com",
                password: "kiran123"
            },
            success: function(sessionResponse){
                console.log(sessionResponse);
                openWebsocket();
            }
        });

        var openWebsocket = function(){
            var socket;
            socket = new WebSocket('ws://demo.traccar.org/api/socket');

            socket.onclose = function (event) {
                console.log("WebSocket closed");
            };

            socket.onmessage = function (event) {
                var i, j, store, data, array, entity, device, typeKey, alarmKey, text, geofence;
                console.log(event.data);
            };
        };
  
    </script>
  </body>
</html>
```

**Comment by kirantpatil** [comment]
I think I got the pointer at https://github.com/tananaev/traccar/issues/2508. But feel free reopen it, if I am wrong.

I was under impression that web api can be called via websocket which is wrong and they are different. They try to solve different issues.

**Comment by kirantpatil** [comment]
Once device went online I could see devices and positions in console as below.

![screenshot from 2016-11-18 16 24 20](https://cloud.githubusercontent.com/assets/1178055/20427826/d6ec0f82-adab-11e6-8360-c3c8d20ca2eb.png)

**Comment by tananaev** [comment]
WebSocket is only used to get real-time updates. Everything else is regular REST web API.

**Comment by kirantpatil** [comment]
Sir, Websocket pushes once there is any change in the database right ? Currently I could see devices and positions, is there any other details it pushes ?

**Comment by Abyss777** [comment]
Yes, it also send Events via websocket.

**Comment by tananaev** [comment]
@kirantpatil, what other details are you interested in? WebSocket is only for data that comes from devices or triggered by data that comes from devices.

**Comment by kirantpatil** [comment]
I just wanted to check since there is no document(wiki) around Websocket at Traccar to know what does it offers, hence I raised this question.

A brief overview of Websocket and its working model in Traccar help newbie like us to understand it.

**Comment by tananaev** [comment]
WebSocket connection provides live access to positions, device status updates and events.

**Comment by varanasi48** [comment]
i only get positions,not devices.can you help me why?

**Comment by tananaev** [comment]
@varanasi48 please don't comment on old closed threads. For questions there is forum.
