### ISSUE TITLE
Group Report - Device Name [New Feature Request]

### ISSUE THREAD

**Issue by neilromig** [tananaev/traccar#2554]
This relates to another request of mine #2053 which has been mostly achieved by the Route report for a group - all that is missing is a means of identifying which map trail corresponds to which device.
This could be done by highlighting the relevant row in the "Device" pane when a position is selected (as currently happens with the live positions), or by adding a "Device Name" column to the report.

**Comment by tananaev** [comment]
I think the easiest option would be to show device name in the report table.
