### ISSUE TITLE
3.8 No Notification Options

### ISSUE THREAD

**Issue by rdentandt** [tananaev/traccar#2556]
Hi Anton,

New web interface Looks FANTASTIC! Well done and THANK YOU!

I have one issue though. Maybe its a mistake on my side but there are no Notification options to select? My notifications are blank. So I cannot set anything to send via e-mail. Are these still configured within the config?

Please assist.

Config Looks like this:

    <entry key='web.enable'>true</entry>
    <entry key='web.port'>8082</entry>
    <entry key='web.path'>/opt/traccar/web</entry>
    <entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>google</entry>
    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>
    <entry key='event.enable'>true</entry>
    <entry key='event.overspeedHandler'>true</entry>
    <entry key='event.overspeed.notRepeat'>true</entry>
    <entry key='event.motionHandler'>true</entry>
    <entry key='event.geofenceHandler'>true</entry>
    <entry key='event.alertHandler'>true</entry>
    <entry key='event.ignitionHandler'>true</entry>
    <entry key='status.timeout'>600</entry>
    <entry key='mail.smtp.host'>***********</entry>
    <entry key='mail.smtp.port'>******</entry>
    <entry key='mail.smtp.from'>***************</entry>
    <entry key='mail.smtp.auth'>true</entry>
    <entry key='mail.smtp.username'>***********</entry>
    <entry key='mail.smtp.password'>******</entry>
    <entry key='distance.enable'>true</entry>
    <entry key='filter.zero'>false</entry>
    <entry key='filter.duplicate'>true</entry>
    <entry key='filter.distance'>50</entry>

**Comment by tananaev** [comment]
Config parameters are still the same. Check `default.xml` config file which now contains most of the settings.

**Comment by rdentandt** [comment]
Hi Anton

I have checked the configs. They are correct in the default.xml.

The notifications dialog on the web interface is also empty. An no notifications are sent. I have test with geofence. 

Please assist.

On 19 Nov 2016, at 9:43 AM, Anton Tananaev <notifications@github.com> wrote:

Config parameters are still the same. Check default.xml config file which now contains most of the settings.

**Comment by tananaev** [comment]
Can I see a screenshot? Notifications dialog is pre-populated, so if it's empty, it probably means that you haven't installed Traccar correctly.

**Comment by rdentandt** [comment]
Hi Anton

I have made the mistake of replacing the new teacker.xml with my backed up copy. I was not aware that it has changed to default.xml.

I have resolved the issue and all is working now.

Thank you!!!

On 19 Nov 2016, at 11:19 PM, Anton Tananaev <notifications@github.com> wrote:

Can I see a screenshot? Notifications dialog is pre-populated, so if it's empty, it probably means that you haven't installed Traccar correctly.

**Comment by tananaev** [comment]
The intention is to keep modifications in the `traccar.xml` file and the default values for everything in `default.xml`.

**Comment by Turbovix** [comment]
@tananaev, so the email settings are in traccar.xml? Or any other too?

**Comment by tananaev** [comment]
Email settings can go into `traccar.xml` or if you want to set it up per user, it can go into user attributes.

**Comment by Turbovix** [comment]
Thank you, it worked perfectly!

**Comment by Turbovix** [comment]
Another question, which file is responsible for sending the email, I need to translate the information:

Device(Dispositivo): Renault GT-Line
Stopped(Parado)
Point(Local): http://www.openstreetmap.org/?mlat=-20.417819&mlon=-40.337014#map=16/-20.417819/-40.337014
(Horário e Data)Time: Mon Nov 21 01:18:19 UTC 2016

**Comment by tananaev** [comment]
It's it the [NotificationFormatter class](https://github.com/tananaev/traccar/blob/master/src/org/traccar/notification/NotificationFormatter.java).

**Comment by Turbovix** [comment]
Thank you

**Comment by viacom1234** [comment]
I put the email settings in the traccar.xml and the traccar service cannot start. Also it does not work if I paste them into the user attributes.


On a side note the notification options disappear once the traccar service stops.
