### ISSUE TITLE
3.8 No Trip Log Events

### ISSUE THREAD

**Issue by rdentandt** [tananaev/traccar#2557]
Hi Anton

Another issue detected on V3.8.

The trip log report does not show any data. 
The route log reports correctly.
The Event report Remains empty, even though it is enabled in the default.xml file.
The Summary report works correctly.

Please advise

**Comment by Abyss777** [comment]
Looks like you misconfigured something, please check if your `traccar.xml` have link to `default.xml`
````
<entry key="config.default">./conf/default.xml</entry>
````

**Comment by rdentandt** [comment]
Excellent!!!!

You were right. 

My apologies its working.

The ticket for notifications is also resolved by this.

Thanks

On 19 Nov 2016, at 5:25 PM, Andrey Kunitsyn <notifications@github.com> wrote:

Looks like you misconfigured something, please check if your traccar.xml have link to default.xml

<entry key="config.default">./conf/default.xml</entry>

**Comment by CapnBob** [comment]
Hello Anton.  I'm having a related issue.  For instance, If  make a 1 week inquiry.   trip reports are few or non-existent, The same is true of events. even though a route report shows multiple trips over multiple days.
I am running a MySQL database.   <entry key="config.default">./conf/default.xml</entry>   is in default.xml.  Where would I look to track down the issue?  Thank You.

**Comment by tananaev** [comment]
@CapnBob, first of all, you should create a new thread instead of commenting on an old closed thread. Secondly, the trip is calculated based on some parameters and the default parameters might not work for everybody. You might need to tweak them.
