### ISSUE TITLE
3.8 database.registerUnknown does not map device to user

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2559]
Hello,

`database.registerUnknown` in 3.8 registers the device into device table, however does not map the device to any user. in user_device table.

This makes it difficult even for admin to manage the device. other than manually making entries into db.

Am i missing out on something, or is this a bug?

**Comment by Abyss777** [comment]
It behaves as should. 
Admin can link any device to any user, even device linked nobody, just via web-interface/API.
It is not necessary make entries into db manually.

**Comment by jaimzj** [comment]
@Abyss777 I think, maybe i should have logged out and re-loged into web-interface? then it would show up maybe? because it wasnt showing up then.. I will try with another device :) Thanks for the info

**Comment by jaimzj** [comment]
Works as expected.
