### ISSUE TITLE
3.8 Statistics not being recorded

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2560]
Dear Team,

3.8 statistic table is empty, its been 2 hour since upgrade and, 3 restarts.

Is there a way it can be checked,? on what is wrong?

**Comment by Abyss777** [comment]
Be patient, wait a few days, statistics is stored to database once a day.
And want to note that all collected information between last save and restart are lost.

**Comment by tananaev** [comment]
Statistics is collected daily. Also, if you restart server, you will lose data stored for the day so far.

**Comment by jaimzj** [comment]
@tananaev @Abyss777  Yes it worked, as shared by you all, End of the day it did log the statistics. so closing this issue. thanks :)
