### ISSUE TITLE
Error during packaging.

### ISSUE THREAD

**Issue by Turbovix** [tananaev/traccar#2564]
@tananaev, I get the error below, the moment I am packing using sript (package.sh). I have noticed that there is no app.min.js file in the directory you entered, even after adding the Traccar-Web. Should I disregard the error?
```
Self-extractable archive "traccar.run" successfully created.
   Adding: traccar.run (deflated 0%)
   Adding: README.txt (deflated 54%)
Rm: could not remove '../trac-web/web/app.min.js': File or directory not found
```

**Comment by tananaev** [comment]
If there is no `app.min.js`, it means that you had some other errors before this one.

Also, `../trac-web/web/app.min.js` is incorrect path. It seems like you have modified the script. I have `../traccar-web/web/app.min.js` in my one.

**Comment by Turbovix** [comment]
@tananaev , The only modification was commenting the script line: `#check_requirement "which sencha" "Missing sencha cmd package (https://www.sencha.com/products/extjs/cmd-download/)"`
Should Sencha be installed on my OS (Ubuntu X64) or should I download the .exe package and leave it in view of the script?

**Comment by tananaev** [comment]
You should have sencha cmd on your path. Why did you comment it out? It's the command required to generate `app.min.js` file.

**Comment by Turbovix** [comment]
The script can not find it even though it is there in the directory.

**Comment by tananaev** [comment]
Which script cannot find what?

**Comment by Turbovix** [comment]
sencha cmd package

**Comment by tananaev** [comment]
It means that it's not on your path.

**Comment by Turbovix** [comment]
Thanks for the long patience, now everything went well!

**Comment by Turbovix** [comment]
I have no words to say and thank you for the excellent work. Congratulations!

**Comment by tananaev** [comment]
You are welcome.

Closing this thread. Reopen or create a new one if you have any further questions.
