### ISSUE TITLE
Setting Speed limit using web interface

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2572]
how user can set speed limit group-wise or device-wise through web interface?

**Comment by tananaev** [comment]
You can set "speedLimit" attribute for device or group:

https://www.traccar.org/configuration-file/

**Comment by d33pak-s1ngh** [comment]
thank you for your reply sir,
below is the entry which i have in my configuration file.
<entry key='event.globalSpeedLimit'>10</entry>
but i am not getting any speed alert notification on web or in my events table. so can you please give an example how to configure speed into configuration file. that will be very helpful.

**Comment by tananaev** [comment]
Have you even looked at the link? It doesn't mention `event.globalSpeedLimit` anywhere there. It's an outdated name which is not used anymore.

Speed is not configured in the config file. It's configured in the attributes:
![screen shot 2016-11-22 at 6 02 49 pm](https://cloud.githubusercontent.com/assets/1161863/20511523/ed355502-b0dd-11e6-9a1b-190329d7c137.png)

**Comment by kirantpatil** [comment]
It is better to autoload all attributes with some default value, along with enable or disable each attribute. So that all attributes are visible to user to turn on or off.

**Comment by tananaev** [comment]
The idea is that there can be hundreds of attributes, so it doesn't make any sense to add all of them.

**Comment by kirantpatil** [comment]
May be we can maintain a wiki to list all attributes with value range.

**Comment by tananaev** [comment]
That's exactly what the page (see my link above) is for.

**Comment by kirantpatil** [comment]
Great, thanks.

**Comment by d33pak-s1ngh** [comment]
thank you sir for your reply,
now i got the idea how to set attributes for speed.
but by just looking on that configuration link i was not getting  any idea where to store those settings because above they mention path of traccar.xml so i thought settings need to be apply in that file.
There should be a comment or note on above link saying that these settings need to be apply in attributes from web interface.

any way great job thank you once again..
