### ISSUE TITLE
[Feature Request] Reporting based on driver behaviour, speed control, start and stop status

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2579]
From https://github.com/tananaev/traccar/issues/2308

A dashboard for reporting purposes where we will collect reporting based on driver behaviour, speed control, start and stop status... and so on

**Comment by tananaev** [comment]
You should probably elaborate on what it should look like.

**Comment by kirantpatil** [comment]
@akmal1999, please add more details to this requirement

**Comment by kirantpatil** [comment]
I am closing this issue.

**Comment by kirantpatil** [comment]
From OBD device we can get below parameters to know driver behaviour.

Website: http://www.thinkobd.com/, http://www.thinkobd.com/service-oem-odm.aspx

Driving behavior report:

Vibration alert, sudden acceleration, deceleration, sharp lane change, sharp turn, breaking all become a score to display front of driver, company, help business of all sizes track their vehicles and assets, remove paperwork, stay compliant, improve vehicle utilization, reduce accidents and increase.

I could see now in report, Chart "Chart Type", OBD Speed, OBD Odometer.

@tananaev, with OBD data in hand can we come up with Driving behaviour report ?

Thanks.

**Comment by kirantpatil** [comment]
http://www.thinkobd.com/VT400-LTE-OBD-%E2%85%A1.aspx

Driving behavior analysis:

Dangerous driving behavior identification based on accurate detect, over speed driving, hard acceleration, hard deceleration, hard breaking, sharp turn, urgent lanes change, hard refuel, fatigue driving all kind of bad driving behavior should not happen any time for teenager or adult. Scoring after every trip ending, store in database as a reference judge condition for Usage Base Insurance (UBI), it is possible for parents to correct their kid’s driving behavior base on big data.

**Comment by tananaev** [comment]
Traccar already supports driving behaviour events.

**Comment by kirantpatil** [comment]
I am closing this issue in favour of https://github.com/tananaev/traccar/issues/3501
