### ISSUE TITLE
How to access API token 

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2580]
Hi,

From below screenshot, I don't know how to get API token. I logged in as normal user.

![screenshot from 2016-11-22 12 57 00](https://cloud.githubusercontent.com/assets/1178055/20514691/682004c2-b0b3-11e6-8438-215f6d24a2ee.png)

**Comment by tananaev** [comment]
Only admin user can assign/generate tokens.

**Comment by kirantpatil** [comment]
Yes it works in v3.8
