### ISSUE TITLE
[Traccar v3.7] Group delete by user is deleted at admin 

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2582]
Hi,

Steps to reproduce:
-------------------------
1. login to admin as admin/admin
2. create a group 
3. Assign group to user account
4. logout 
5. login to user account
6. select Group and delete 
7. logout
8. login to admin 
9. Check the group and it is deleted at admin as well.

**Comment by tananaev** [comment]
That's expected behaviour. Removing the group removes it from the database.

**Comment by kirantpatil** [comment]
Since group is created by Admin, only Admin should have capability to delete it. Expected behaviour is not correct.

**Comment by tananaev** [comment]
It's not how permissions system works in Traccar. Creator of the object doesn't get any special rights. If an object is shared, any user with access to that object can remove it.

**Comment by kirantpatil** [comment]
Ok, only option left is to make that user account readonly right ?

**Comment by tananaev** [comment]
If you want user to not be able to remove it, then yes.

**Comment by kirantpatil** [comment]
Anyway closing this issue based on the current permission system. Thanks.
