### ISSUE TITLE
[Info] About user registrations at /api/users

### ISSUE THREAD

**Issue by sunhoww** [tananaev/traccar#2589]
Hi

First of all... The new version is the greatest. You guys seem to have gone over and above the feature requests here.

**traccar-web** uses only the _User_ properties - `name`, `email` and `password` during new user registration. However, I am able to pass params like `deviceLimit` and `expirationTime`, and correctly set the appropriate _User_ properties.

I was hoping to use this during user registration to set default properties. But since only admin users have the privilege to set said properties, I was wondering whether new users having this ability to set these properties themselves is the intended behavior. If not, maybe the behavior would get removed in future releases.

**Comment by tananaev** [comment]
Fixed the problem. Now server will check some attributes on new users.

**Comment by sunhoww** [comment]
Great. Any ideas how we could have default `deviceLimit` and `expirationTime` for new users though?

**Comment by tananaev** [comment]
Probably the easiest option is to force it in the `UserResource` class.
