### ISSUE TITLE
Suggestion use HTTPS url notifications

### ISSUE THREAD

**Issue by Turbovix** [tananaev/traccar#2590]
@tananaev , the Google has changed some policies on how the Chrome browser handles users' geolocation requests, so it is necessary to add https in the urls of the file (NotificationFormatter.java). When the URL is accessed via HTTPS the services are more complete. Example: Verify the distance between the Traccar user and the vehicle.

Detailed explanation: https://goo.gl/yEj56q

Before: "Point: http://www.openstreetmap.org/?mlat=%3$f&mlon=%4$f#map=16/%3$f/%4$f%n"
After:    "Point: https://www.openstreetmap.org/?mlat=%3$f&mlon=%4$f#map=16/%3$f/%4$f%n"

**Comment by tananaev** [comment]
Feel free to send a pull request.

The plan is to replace those URLs with links to Traccar web interface in future.
