### ISSUE TITLE
https integration

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2597]
Hi,

What does it takes to integrate https for my Traccar web server?  Does it require to do some code changeing or is there any other option for users who do not have code writing skills.

Some web servers have integrated support for https connection clients like " https://letsencrypt.org ".  Would it be idea to add something like this also to Traccar server in near future ?

By the way, big thanks to Traccar developers for frequent server updates, you are doing good job !

**Comment by Abyss777** [comment]
You can use some proxy web server for it.
Here is Apache example https://www.traccar.org/secure-connection/

Also, I've seen "success stories" here or on the forum for nginx and IIS

**Comment by argokask** [comment]
Good infomation, thank you!
