### ISSUE TITLE
TK103: StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#2598]
I've temporary got Chinese device, that use TK103 protocol (as I could determine)

Without GPS it sends something like login packet
````
(087073005534BP00HSO)
````
And cause a subj error
````
2016-11-24 13:27:11  INFO: [23F36031] connected
2016-11-24 13:27:13 DEBUG: [23F36031: 5002 < 192.168.0.250] HEX: 283038373037333030353533344250303048534f29
2016-11-24 13:27:13  WARN: [23F36031] error - String index out of range: 15 - StringIndexOutOfBoundsException (... < Tk103ProtocolDecoder:116 < ExtendedObjectDecoder:58 < ...)
2016-11-24 13:27:13  INFO: [23F36031] disconnected
````

I've started to investigate and found strange https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Tk103ProtocolDecoder.java#L116
Am I missing something or there should be `id` instead of `content.substring(0, 15)` ?

**Comment by Abyss777** [comment]
This code works for me:
````java
            if (type.equals("BP00") || type.equals("BP05")) {
                String content = sentence.substring(16);
                getDeviceSession(channel, remoteAddress, id);
                if (type.equals("BP00")) {
                    channel.write("(" + id + "AP01" + content + ")");
                    return null;
                } else if (type.equals("BP05")) {
                    channel.write("(" + id + "AP05)");
                }
            }
````

**Comment by tananaev** [comment]
Fixed the problem. Some devices send full IMEI with `BP00` message, so I decided that it would be good idea to capture it for identification.

From documentation:

![screen shot 2016-11-24 at 10 38 23 pm](https://cloud.githubusercontent.com/assets/1161863/20593317/c5d83474-b296-11e6-885a-791418c2a141.png)

**Comment by Abyss777** [comment]
But if we do `getDeviceSession(channel, remoteAddress, id)` we will get device online as soon as it send handshake. And It will be consistence with other part of parser, there device unique id is first 12 digits.

**Comment by tananaev** [comment]
The problem is that most people don't know that they should be using "0" plus last 11 digits of their IMEI for the device id. So, I implemented this as a fallback option.

**Comment by Abyss777** [comment]
May be if it is fallback anyway we can use:
````java
                if (content.length() >= 15) {
                    getDeviceSession(channel, remoteAddress, content.substring(0, 15));
                } else {
                    getDeviceSession(channel, remoteAddress, id);
                }
````

**Comment by tananaev** [comment]
There is no need for id there... it's only a heartbeat message. For real location data, if device is not identified yet, it will use 12-digit id anyway.
