### ISSUE TITLE
e-mail notification problem

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2599]
Hi,

E-mail notifications are not working and i get WARN when i look into my server log file. That problem occurd after server update 3.7 to 3.8.

2016-11-23 18:43:17  WARN: Could not connect to SMTP host: smtp.gmail.com, port: 587 - MessagingException (... < NotificationMail:110 < *:33 < *:127 < ...)

I added SMTP conf to " traccar.xml" file.

	
	
	<entry key='mail.smtp.host'>smtp.gmail.com</entry>    
	<entry key='mail.smtp.port'>587</entry>						
	<entry key='mail.smtp.starttls.enable'>true</entry>
	<entry key='mail.smtp.ssl.enable'>true</entry>
	<entry key='mail.smtp.from'>forexample@gmail.com</entry>
	<entry key='mail.smtp.auth'>true</entry>
	<entry key='mail.smtp.username'>forexample@gmail.com</entry> 
	<entry key='mail.smtp.password'>forexample</entry>

Any sugestions what to do ?

In config folder there is also file named "default.xml". Do i have to add SMTP config there instead of " traccar.xml " ?

**Comment by Abyss777** [comment]
You are using right place, but you should remove
````
<entry key='mail.smtp.ssl.enable'>true</entry>
````
It is impossible use SSL and STARTLS in the same time.

**Comment by argokask** [comment]
Unfortunally still no e-mail notifications.

I also tried to change starttls (port 587) to ssl (port 465).

	
	
	<entry key='mail.smtp.host'>smtp.gmail.com</entry>    
	<entry key='mail.smtp.port'>465</entry>						
	<entry key='mail.smtp.ssl.enable'>true</entry>
	<entry key='mail.smtp.from'>forexample@gmail.com</entry>
	<entry key='mail.smtp.auth'>true</entry>
	<entry key='mail.smtp.username'>forexample@gmail.com</entry> 
	<entry key='mail.smtp.password'>forexample</entry>

What would be next thing to check ?

**Comment by Abyss777** [comment]
Errors should be different with ssl and startls, are they? Could you provide?

Also, have you changed something in gmail account? Like "Allow insecure applications" or application password?

**Comment by argokask** [comment]
Funny thing is that online/offline notificationts are not working but geofence notifications are fine. That means SMTP config is correct and problem is somewhere else.

**Comment by tananaev** [comment]
Likely following line is missing in the config:
```xml
<entry key='event.statusHandler'>true</entry>
```

**Comment by argokask** [comment]
Yes, i added that line and now everything works fine.

Thank you!
