### ISSUE TITLE
[Feature Request] Polyline for Geofencing

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2600]
Hi,

Please add Polyline for Geofencing.

Since currently there is no feature to draw a vehicle route on map, except using Polygon or Circle.

Thanks.

**Comment by Abyss777** [comment]
Hello,
Could you share a use case of polyline geofence?

**Comment by tananaev** [comment]
That won't be really a geofencing. It's basically checking if an object is following a pre-defined route. Ideally it can come with some time limits as well.

Actually geofences should probably have options to set time as well.

**Comment by kirantpatil** [comment]
As @tananaev mentioned, I would like to check if an object is following a pre-defined route.

**Comment by kirantpatil** [comment]
May be I should have renamed this Feature request as "Add pre-defined route".

**Comment by kirantpatil** [comment]
Shall I close this issue, if it did not add any value ?

**Comment by Abyss777** [comment]
@tananaev 
How we will treat distance from polyline to device to decide if device on line or out of line? One default in config or per geofence?

WKT will fit `LINESTRING (30 10, 10 30, 40 40)`

**Comment by kirantpatil** [comment]
@tananaev, shall I open a new feature request for "Pre-defined route with Source and Destination points".

**Comment by tananaev** [comment]
@Abyss777, I think for now we can use global distance.

@kirantpatil, I think we can keep this thread.
