### ISSUE TITLE
route shows arrow instead of bus (category)

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2602]
Hi,

Please find the below screenshot. Is that the expected behaviour ?

![screenshot from 2016-11-25 15 55 57](https://cloud.githubusercontent.com/assets/1178055/20622378/966bab98-b328-11e6-9d4c-7fefb631c387.png)

Thanks.

**Comment by tananaev** [comment]
Yes, it is expected behaviour for report. It would be too much clutter if we draw big icons for every point.

**Comment by kirantpatil** [comment]
Just a thought, how about adding small icons for every point ?

**Comment by tananaev** [comment]
I guess that's an option. Not sure if it's going to look good though.
