### ISSUE TITLE
[feature request] Idea to have time limits for querying reports

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2603]
Hi Traccar developer team.

The idea would be to have more control over reports what user can and can not see when doing query from database. At the moment if i add device which have been in use eralier to some new user then that new user sees all the reports which has been related to that device.

Scenario where my problem occurs would be: 

User 1 is having device A and let's say something happens with that device and it need to be replaced. 
For example i have device B available in drawer but earlier it has been related with user 2.
Now, if i add device B to user 1 then he or she sees all the history of user 2 which is not good in privacy considerations.

Solution would be that admin could manage the query time periods for each user. For example: user 1 can do reports query only from dd.mm.yy to dd.mm.yy.

Would it be idea to add Traccar this kind of functionallity ?

**Comment by tananaev** [comment]
I don't think it's a right solution. I remember this was discussed before somewhere on the forum.

I suggest following approach. When you remove physical device from user 1, instead of removing device in the database, you just changed unique id to something else (e.g. add prefix or just replace with some random number). Then you add a new device for user 2 with actual unique id. Now both users have access to their own data.

**Comment by argokask** [comment]
Thank you for answering.

If i understand correctly then that works only when i have no plan using "device A" again for some other users?

For example when doing software update, it would be much quicker to give "user A" new device ("device B") instead of updateing "device A" somewhere outside the office not knowing if that works or not. 

My point is that sometimes there is just need to swap devices between users and in this case it would be good if "user 1" can not query "device B" history and "user 2" can not query "device A" history. Of course user 1 loses all the history he had with "device A" but for me it would not be the problem because there is possible to export all older data if needed.

**Comment by tananaev** [comment]
It works in any case, and you don't even have to lose the history.

**Comment by argokask** [comment]
That solution works very well for me. Thank you !
