### ISSUE TITLE
How to enable Trip and Trip report

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2604]
Hi,

I could see route report but not Trip report. I would like to know how it has to be enabled ?
I don't see the Trip configuration either at admin or user page, since it mentions Start Address and End Address. I am using android mobile as device.

I found below configuration parameters from configuration page. Do I need to add all of them to default.xml file to enable Trip report ?

report.trip.minimalTripDuration config Trips less than minimal duration and minimal distance are ignored. 300 seconds and 500 meters are default.

report.trip.minimalTripDistance config Trips less than minimal duration and minimal distance are ignored. 300 seconds and 500 meters are default.

report.trip.minimalParkingDuration config Parking less than minimal duration does not cut trip. Default 300 seconds.

report.trip.greedyParking config If true, the device is considered to be in parking state and only continuous trips are detected.

Thanks.

**Comment by tananaev** [comment]
I already answered here:

https://github.com/tananaev/traccar-web/issues/336#issuecomment-262955413
