### ISSUE TITLE
Sever

### ISSUE THREAD

**Issue by sms1515** [tananaev/traccar#2610]
Hello, I need an indication, how to rotate traccar in the cloud?

**Comment by tananaev** [comment]
What do you mean by "rotate"? Do you mean deploy? Download installer and follow readme file instructions.

**Comment by sms1515** [comment]
Can you tell me a server, with a good cost benefit, to deploy traccar?

**Comment by tananaev** [comment]
If you want a cheap server, you can try DigitalOcean, or you can find even cheaper options here:

https://lowendbox.com/

Note that you need at least 1GB of RAM.
