### ISSUE TITLE
[Feature Request] create multiple points(marker) on the map for a group or a device

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2611]
Use case:
1. a group is assigned with multiple device 
2. a group or a device is assigned with a map co-ordinates (with source and destination points)
3. Manager login to his account to see his predefined route co-ordinates and position of the vehicles as well

I felt this usecase generic enough to support for most of the usecases of fleet management and so on.

Thanks.

**Comment by tananaev** [comment]
It's already implemented.

**Comment by kirantpatil** [comment]
Where do we have an option to set Source, Destination and intermediate lat-lng for Device and Group ?

**Comment by tananaev** [comment]
You can create a polyline geofence and assign it to device or a group.

**Comment by kirantpatil** [comment]
Ok Sir thanks.
