### ISSUE TITLE
[Docker] 403 - Forbidden

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2612]
Hi,

I tried to build docker version to check master branch updates.

When I tried to access traccar link (http://172.17.0.2:8082/), I am getting "403-Forbidden" message in browser as below.

![screenshot from 2016-11-28 13 38 35](https://cloud.githubusercontent.com/assets/1178055/20660505/fba36016-b56f-11e6-8cdd-2adffdf847e1.png)

Docker and container details:
---
traccar$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
tananaev/traccar    3.8-SNAPSHOT        0e49a4cdb389        23 minutes ago      184.8 MB
java                8-alpine            bcf89b10abe4        10 days ago         145 MB

traccar$ sudo docker ps
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS              PORTS                     NAMES
85880753cbff        0e49a4cdb389:latest   "java -jar traccar-s   21 minutes ago      Up 21 minutes       5000-5150/tcp, 8082/tcp   grave_mayer

traccar$ sudo docker top 8588
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                12994               10372               2                   13:19               ?                   00:00:33            java -jar traccar-server.jar traccar.xml

traccar$ sudo docker exec -it 8588 bashbash-4.3
\# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02  
          inet addr:172.17.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:2%32697/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:50 errors:0 dropped:0 overruns:0 frame:0
          TX packets:26 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4485 (4.3 KiB)  TX bytes:3028 (2.9 KiB)

Thanks.

**Comment by kirantpatil** [comment]
Sorry, I did not copy the traccar-web in to the traccar server directory and now webui shows up.

**Comment by greyarch** [comment]
It is not immediately clear, but traccar uses refers to traccar-web via a git module. Unfortunately, git will not automatically clone modules when you clone the parent project. So to get the traccar-web code as well, instead of copying it into the traccar root dir, you need to clone traccar recursively like this:
```
git clone --recursive git@github.com:tananaev/traccar.git
```
