### ISSUE TITLE
Geofencing with polyline is not diplayed on user map

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2613]
Hi,

Geofencing is not displaying when I login as user1@gmail.com.

I cloned traccar master branch and compiled manually (mvn package) and running from command line as "java -jar tracker-server.jar conf/traccar.xml"

Steps to reproduce:
------------------------
1. Login as admin
2. Create a user with uname/passwd as user1@gmail.com/user123 with Readonly
2. Create a device say bus1
3. Create a geofence gf1 with  polyline
4. Assign gf1 to bus1
5. Assign bus1 to user1
6. Login to user1
7. Now click on either device or Geofencing Icon, the polyline route is not diplaying on the map

Thanks.

**Comment by Abyss777** [comment]
Hello,

Can't reproduce.
Do you see the geofence if you login back as admin?

**Comment by kirantpatil** [comment]
Yes, I see the geofence if I login back as admin.

**Comment by Abyss777** [comment]
There is no any differences in displaying geofences for admin and user.
Please, double check that you link geofence to user and check browser console for any errors.

**Comment by tananaev** [comment]
Also check the list of geofences available for the user.

**Comment by kirantpatil** [comment]
I have assigned geofence to device and not to user.

![screenshot from 2016-11-28 16 07 43](https://cloud.githubusercontent.com/assets/1178055/20665325/45ad141c-b585-11e6-8e0d-9e810cb56ed7.png)

**Comment by kirantpatil** [comment]
Bus2 with its geofence:

![screenshot from 2016-11-28 16 08 51](https://cloud.githubusercontent.com/assets/1178055/20665367/6f9a5d66-b585-11e6-8c28-c7eb96f65576.png)

Bus1 with its geofence:

![screenshot from 2016-11-28 16 08 32](https://cloud.githubusercontent.com/assets/1178055/20665382/779beaca-b585-11e6-822d-ee0d55bcfc4d.png)

User with both Bus1 and Bus2 assigned 

![screenshot from 2016-11-28 16 08 06](https://cloud.githubusercontent.com/assets/1178055/20665390/7e4c6462-b585-11e6-921c-2ff52fd10389.png)

User1 login with no major errors on console:

![screenshot from 2016-11-28 16 06 09](https://cloud.githubusercontent.com/assets/1178055/20665401/8566b950-b585-11e6-9302-0804ab1931aa.png)

Admin login with console:

![screenshot from 2016-11-28 16 03 52](https://cloud.githubusercontent.com/assets/1178055/20665406/8ae33eee-b585-11e6-9504-bba438bff0d6.png)

**Comment by Abyss777** [comment]
You have to assign geofence to user1 to see it on map and other things related.

**Comment by kirantpatil** [comment]
But I have assigned geofence to device and device is assigned to user.

**Comment by kirantpatil** [comment]
@Abyss777, if I assign geofence to user1 then it shows on the map. But why do I need to assign it to user1 since already a device/group assigned with geofence is assigned to user1 ? This will become too much assignment work.

**Comment by Abyss777** [comment]
It is the way how permissions work in traccar.
If user do not assigned to object he do not have access to it, rather logically I think.

If device is assigned to geofence then traccar generate enter/exit geofence events for that particular geofence. 

If user is assigned to geofence he will get access to that events and can see and edit that geofence.

**Comment by kirantpatil** [comment]
Right now user1 account is in Readonly mode so he cannot edit but see the geofence.

**Comment by kirantpatil** [comment]
The Idea was to allow if geofence is assigned to device/group to view in readonly mode for User1. Once geofence is assigned to User1 then he can add new/edit geofence. 

Anyway am closing this issue.

**Comment by kirantpatil** [comment]
The same logic applies to Group also. A group gp1 containing bus1 and bus2 should display in readonly mode to User1 since he is assigned Group gp1.  Once he is assigned to any device then it should allow him to modify.
