### ISSUE TITLE
[Feature Request] Markers on map

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2614]
The map with route using Geofence works great, but the only missing major visual enhancement needed is to allow adding multiple markers on the map with location details.

**Comment by tananaev** [comment]
Do you mean like POIs? There is already a feature request for that somewhere.

**Comment by kirantpatil** [comment]
Yes.

There are multiple issues but I got confused so opened new one.
https://github.com/tananaev/traccar/issues/926
https://github.com/tananaev/traccar/issues/1680

**Comment by tananaev** [comment]
Neither of those seem to be related to your request. Can you please explain again your feature request. Is it for POIs or what kind of markers are you talking about?

**Comment by kirantpatil** [comment]
Sir, for each route of geofence, I would like to create markers on map to see what is the starting point, end point and if there are any other intermediate points that vehicle has to visit on the way, as shown in below screenshot.

![screenshot from 2016-11-29 09-03-21](https://cloud.githubusercontent.com/assets/1178055/20695598/4701d120-b613-11e6-9c54-7ca11af3c64a.png)

**Comment by tananaev** [comment]
I see now. And it's just for displaying on the map, right?

**Comment by Abyss777** [comment]
May be use small circle geofences?
![image](https://cloud.githubusercontent.com/assets/5688080/20697676/e996052e-b61c-11e6-9b6a-e9d80d55993b.png)

The benefit is that you will get events in the middle of route.

**Comment by kirantpatil** [comment]
@tananaev, yes it is to display on map to highlight the places( location/address) that vehicle is either visiting to pick something or halting for brief period.

**Comment by tananaev** [comment]
I agree with @Abyss777. You can already do similar thing with regular geo-zones.

**Comment by kirantpatil** [comment]
I am unable to create or edit geofence to add polyline with circle as shown in @Abyss777 screenshot, since it erases the earlier shape.

**Comment by Abyss777** [comment]
You can't create "multi-shape" geofence.
It is three geofences in screenshot, not one.

**Comment by kirantpatil** [comment]
Right now geofence is showing only in one colour ie blue. We need an option to change colour of geofence to denote points such as start, intermediate and end.

**Comment by kirantpatil** [comment]
@Abyss777, can please elaborate on "The benefit is that you will get events in the middle of route ?

**Comment by Abyss777** [comment]
For example, there are one geofence with labels (as you suggested): "the route"
You can get two events: device on the route, device out the route.

For example, there are four geofences: "the route", "the beginning", "the middle point", "the end".
You can get events about:
- device on/out the route
- device started its trip (out the beginning geofence)
- device came to the middle point
- device continued its trip (out the middle point)
- device ended its trip (in the end geofence)

**Comment by kirantpatil** [comment]
Great. Thanks.

**Comment by kirantpatil** [comment]
Thanks to @tananaev and @Abyss777.
