### ISSUE TITLE
coordinate related aadress is missing

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2620]
Hi,

Problem occurs on the client's computer. Under the "State" section address is missing. Seems like client's computer blocks address query from somewhere where that address comes. 

Can you support me with information from where (IP address or URL) that coordinate related address comes, so I'd know what IP I should open for that.

**Comment by argokask** [comment]
Btw I am using OpenStreetMap layer.

**Comment by tananaev** [comment]
Have you configured reverse geocoding?

**Comment by argokask** [comment]
No, I am using default values, everything exept SMTP config is as it is at the beginning. What i do not understand is that when i install traccar server to my computer then that address box is filled and everything is ok, but when i install that to one of my linux based server then that address box remains empty. I was thinking that maybe firewall or some other security feature blocks that query.

Do i understand correctly that when i am using OpenStreetMap layer then i should add nominatim url?

**Comment by tananaev** [comment]
It has nothing to do with the map. You need to configure reverse geocoder:

https://www.traccar.org/reverse-geocoding/

**Comment by argokask** [comment]
I have these lines in my config file already:

<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>google</entry>

**Comment by tananaev** [comment]
I think Google blocks Traccar because people overuse their free service. You should use other options. Note that free Nominatim server is also blocking Traccar because people abuse it.

**Comment by argokask** [comment]
Hi,

Would it be possible to use my own google API for reverse geocoding to be not blocked out ?

When using my own google API then where do i have to insert my google API in traccar server ? Maybe inside default.xml or traccar.xml ?

**Comment by tananaev** [comment]
What do you mean your own Google API? Do you mean the API key?

**Comment by argokask** [comment]
Yes, i ment API key.

**Comment by tananaev** [comment]
You can put it in the config:
```xml
<entry key='geocoder.key'>YOUR API KEY</entry>
```

**Comment by argokask** [comment]
Ok, thank you !

**Comment by malkitsingh** [comment]
@tananaev I am trying to use LocationIQ and have configuration like this
`	<entry key='geocoder.enable'>true</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'>http://locationiq.org/v1/reverse.php</entry>
    <entry key='geocoder.key'>MY API KEY</entry>`
But this is not working, I wrote nominatim because there is no matching reverse geocoder in geocode folder at github. Whats wrong I am doing here? Response of LocationIQ is same as of nominatim.

**Comment by tananaev** [comment]
@malkitsingh, your config looks fine to me. It should work.

**Comment by malkitsingh** [comment]
@tananaev you sure to keep it nominatim while actually calling locationiq url? And this all works on 3.8?
It's not working for me ❌

**Comment by tananaev** [comment]
Turns out Nominatim geocoder didn't support "key" parameter. Fixed it.

**Comment by malkitsingh** [comment]
great, (Y)

**Comment by malkitsingh** [comment]
@tananaev where can I get latest build which include this commit?

**Comment by tananaev** [comment]
There is no latest build. You have to build it yourself or wait for a new release.
