### ISSUE TITLE
SMTP Configuration in Traccar 3.8

### ISSUE THREAD

**Issue by diegor84** [tananaev/traccar#2622]
Hello Anton,
I review  https://www.traccar.org/configuration-file/
but the SMTP Configuration doesn't appears in the new desfault.xml file - inside `C:\Program Files (x86)\Traccar\conf`
Please your help.
Regards

**Comment by tananaev** [comment]
First of all, I don't recommend editing `default.xml` file. All your config modifications should go into `traccar.xml`.

Secondly, you have to add those values. By default Traccar doesn't have any SMTP server configured.

**Comment by negamkpk** [comment]
kindly tell us what to add to enable this feature

**Comment by tananaev** [comment]
Depends on your SMTP server. You can find some examples here:

https://www.traccar.org/forums/topic/smtp-config-for-notifications/

**Comment by negamkpk** [comment]
thanks
