### ISSUE TITLE
How to reset traveled distance in :attributes?

### ISSUE THREAD

**Issue by esteves67** [tananaev/traccar#2624]
Hello !

Is there a way to reset distance traveled? for the next record (Without deleting previous records).

Like i have data at 04:31am (`"distance":1456.25`) and i want to reset that distance to 0 for the next data, without having to delete old records.

Maybe do i have to remove distance.enable parameter and send some data without distance parameter, and enable it again, than it resets?

ps: in my case the distance is calculated by `distance.enable` parameter, since my gps device dont send odometer info.

Other question, is it there a way to set a predefined value for distance in :attributes parameter, like if i have a vehicle with 50.000km is there a way to set that start value?

Thank you Mr. Anton

**Comment by tananaev** [comment]
You should update to version 3.8. It has a function to set/reset distance.
