### ISSUE TITLE
can not see devices on map

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2626]
Hi,

Problem occurs when using ipad or iphone (tested with safari and google chrome browser). When i login to my traccar account then under "Devices" i see all the list of my added devices but i do not see them on the map even if i click on device in list or switch between them.  

In earlier times i have seen same issue on windows platform also but that was not so big problem beacause when i clicked on the device then device appeared on the map.

**Comment by tananaev** [comment]
Sounds like you have a problem with WebSocket connection. I suspect it's something with your network.

**Comment by argokask** [comment]
Ok, do you have some suggestions how to torubleshoot that problem? Lately I installed apache server and generated SSL certificate for https connection, maybe that issue is somehow related with that?

**Comment by tananaev** [comment]
Have you forwarded WebSocket connection in the Apache proxy?

**Comment by argokask** [comment]
Hi,
 
Everything is done according to:  "https://www.traccar.org/secure-connection/".

Inside "apache2/sites-available/traccar.conf" i have these lines:

<IfModule mod_ssl.c>
        <VirtualHost _default_:443>

                ServerName IP.IP.IP.IP
                ServerAdmin webmaster@localhost

                DocumentRoot /var/www/html

                ProxyPass /api/socket ws://localhost:8082/api/socket
                ProxyPassReverse /api/socket ws://localhost:8082/api/socket

                ProxyPass / http://localhost:8082/
                ProxyPassReverse / http://localhost:8082/

                SSLEngine on
                SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
                SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

        </VirtualHost>
</IfModule>

**Comment by tananaev** [comment]
Have you enabled all necessary Apache modules?

**Comment by argokask** [comment]
Yes all modules are enabled,

At the moment i am in situation where everything works with Andorid devices but not working with Apple devices even with different browsers. I see devices on map with Apple devices only when i am in LAN network with server. Problem might be that i have self singned https certificate and maybe that is issue for Apple devices but not for Android.

So i am trying to get normal certificate and then see what is going to happen.

**Comment by argokask** [comment]
Good info, thank you!
