### ISSUE TITLE
osmand device identifier

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2627]
hi, when using your Android Traccar Client it shows me a 6 digit device identifier. I was wondering how this is generated or where it is picked up from? Thanks

**Comment by tananaev** [comment]
It's a randomly generated number.

**Comment by m-menon** [comment]
alright thanks :+1:

**Comment by m-menon** [comment]
so would it be ok if I used any alphanumeric string instead?

**Comment by tananaev** [comment]
Yes, it can be any string.

**Comment by m-menon** [comment]
alright thanks :)
