### ISSUE TITLE
[Feature Request] Autogenerate Token

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2628]
Right now Admin need to create Token for all users manually.

Please provide the global checkbox "Autogenerate Token" to create Token for every new user created by Admin.

Screenshot:

![screenshot from 2016-12-01 18 09 29](https://cloud.githubusercontent.com/assets/1178055/20794325/b9bebf7c-b7f1-11e6-8081-41fe37019834.png)

Thanks.

**Comment by tananaev** [comment]
It's just one extra click in the same window to assign a token.

**Comment by kirantpatil** [comment]
For me I would like to create multiple users by uploading a csv or ods (spreadsheet) with list of username, email id and password.

**Comment by tananaev** [comment]
Traccar doesn't support that at the moment.

**Comment by kirantpatil** [comment]
Another usercase would be,

Creating user using API.

**Comment by tananaev** [comment]
I don't see any issue with assigning token via API.
