### ISSUE TITLE
[Feature Request] Google Distance Matrix API support

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2629]
I would like to make use of google distance matrix api to get the time to travel for the route which includes traffic duration of traffic.

https://developers.google.com/maps/documentation/distance-matrix/

How can we achieve it ?

Sample API output:
```
https://maps.googleapis.com/maps/api/distancematrix/json?origins=MajesticBengaluru&destinations=RajajinagarBengaluru&departure_time=1479294521&mode=driving&key=xxxxxxxxxx
```
```json
{
   "destination_addresses" : [ "Rajaji Nagar, Bengaluru, Karnataka, India" ],
   "origin_addresses" : [ "Majestic, Bengaluru, Karnataka, India" ],
   "rows" : [
      {
         "elements" : [
            {
               "distance" : {
                  "text" : "3.7 km",
                  "value" : 3745
               },
               "duration" : {
                  "text" : "13 mins",
                  "value" : 756
               },
               "duration_in_traffic" : {
                  "text" : "14 mins",
                  "value" : 832
               },
               "status" : "OK"
            }
         ]
      }
   ],
   "status" : "OK"
}
```
Thanks.

**Comment by tananaev** [comment]
We would need a more open alternative before we can implement it.

**Comment by kirantpatil** [comment]
I don't think we have much alternative except following, found in https://github.com/perliedman/leaflet-routing-machine.

Find the way from A to B on a Leaflet map. The plugin supports multiple backends:

    OSRM - builtin and used by default
    Mapbox Directions API - builtin with the class L.Routing.Mapbox
    GraphHopper - through plugin lrm-graphopper
    Mapzen Valhalla - through plugin lrm-valhalla
    TomTom Online Routing API - through plugin lrm-tomtom by Mathias Rohnstock

**Comment by tananaev** [comment]
I'm sure there are alternatives based on OSM data.

**Comment by kirantpatil** [comment]
@tananaev: How about using http://opentraffic.io/ ?

**Comment by tananaev** [comment]
The link that you provided doesn't have much information.

**Comment by kirantpatil** [comment]
closing this issue.

**Comment by RafaelMiquelino** [comment]
Hello, is there any plan to update this feature on Traccar? That would be really valuable for fleet managers who needs to define which is the most suitable vehicle to send to a specific location. Regarding having a more open alternative based on OSM, I know at least the following that provide an API for this:

- https://openrouteservice.org/dev/#/api-docs/matrix/
- https://valhalla.readthedocs.io/en/latest/api/matrix/api-reference/
