### ISSUE TITLE
Feature Request : Reverse Geo-Coder Multiple URL/Server

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2630]
Dear All,

I have noticed with 1000's of devices, the number of hits to the reverse geo-coder service providers URL / web-service can be 100+ hits per second.

This causes two issues, one usage limit related blockage by provider.
And In case of own reverse-codding system, the queries and frequency of hits can increase the system load to a very high level.

Is it possible to add a feature, where users can define multiple URL/Server IP or Domain to be queried for maybe based on a certain logic to equally distribute the number of queries...to a server?

**Comment by tananaev** [comment]
Standard load balancer should be able to do it. I don't see any point of having this functionality in Traccar itself.

**Comment by jaimzj** [comment]
Oh Yes Anton, You are right :) I had completely forgotten about the load balancers. will close this in that case.
