### ISSUE TITLE
How to name Distance Attribute as Odometer

### ISSUE THREAD

**Issue by esteves67** [tananaev/traccar#2632]
Hello Mr. Anton

Is there a option to change name Distance from :attributes to Odometer?

Thanks

**Comment by tananaev** [comment]
Yes, you can rename it using attribute aliases.

**Comment by esteves67** [comment]
My bad, it was right in front of me, in the device tab, i didnt saw at first because im using version 3.4 (that doesn't have attributes aliases) in my machine, than i logged at demo.traccar.org than i saw it..

Thanks again
