### ISSUE TITLE
api login error

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2633]
i want to check that username and password is exist by login i am calling following api(api/session as per web api login). i am using guzzle to call api from my server i am able to get user details by calling api/users with the guzzle.
API_PATH contains server path. and i am passing email and password.
```
$client = new GuzzleHttp\Client();
$res = $client->post(API_PATH.'session',array('email'=>$email,'password'=>$password));
```
i am getting following error
```
"details":"The @FormParam is utilized when the content type of the request entity is not application
```

**Comment by tananaev** [comment]
Looks like request is incorrect. You should compare your request with what default web UI sends.

**Comment by d33pak-s1ngh** [comment]
thanx i got it.

**Comment by d33pak-s1ngh** [comment]
is there any list of api's available which i can use.
i want to insert record into user_group table i cant see any api for that in swagger.json documentation.
i have to do it manually or any api available.

**Comment by sunhoww** [comment]
You can `POST /permissions/groups` to set a user to a group. It's in the swagger specs.

**Comment by d33pak-s1ngh** [comment]
@sunhoww  thanx...
