### ISSUE TITLE
Setting speed limits

### ISSUE THREAD

**Issue by paraisotech** [tananaev/traccar#2641]
How can I set up an speed limit for each car that traccar is monitoring? Is it possible?
In example: My dad's car will run with 80km/h limit, my with 100km/h, mom's 120km/h...

**Comment by Abyss777** [comment]
You can set `speedLimit` attribute for every device https://www.traccar.org/configuration-file/

**Comment by paraisotech** [comment]
Could you please give me an example?
I have already see the configurations file manual, but it doens't
especifies clearly how can we set an speed limit for each device. In my
mind I think we need to create a particular session for each device and
inside of this session get all things parametrized...

Em 4 de dez de 2016 14:17, "Andrey Kunitsyn" <notifications@github.com>
escreveu:

**Comment by Abyss777** [comment]
You can do it via web-interface. Device dialog has button «Attributes». You need to put speedLimit there.

**Comment by paraisotech** [comment]
Great!!! Worked...

Em 4 de dez de 2016 2:52 PM, "Andrey Kunitsyn" <notifications@github.com>
escreveu:
