### ISSUE TITLE
Configurable default group/category for automatically registered devices

### ISSUE THREAD

**Issue by duke2906** [tananaev/traccar#2646]
Hello,

in my opinion a configurable default group and a default category would be usefull when using the optinal functionality to register devices automatically on incoming positions.

Therefore I allready did some adjustments in my fork. May I just create a pull request for an easy review and discussion or should I first post my snippets in this issue here?

https://github.com/tananaev/traccar/compare/master...duke2906:master

**Comment by tananaev** [comment]
Pull request is better, but your code will need some cleanup.

**Comment by duke2906** [comment]
Maybe you can sum up or give me an example of affected code/sections?

**Comment by tananaev** [comment]
I can put comments as soon as you create pull request.

**Comment by duke2906** [comment]
Thank you! Didn't knew that it is possible to discuss on pull requests as well.
