### ISSUE TITLE
Geo-Fence Error - On Startup 3.7

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2647]
Dear Anton,

please help me with what this error means?
```
WARN: InvocationTargetException (... < QueryBuilder:344 < *:421 < DataManager:357 < GeofenceManager:123 < ...)
```

**Comment by tananaev** [comment]
It likely means that you have some configuration issue, or that you made some modification to the code.

**Comment by jaimzj** [comment]
No modifications to the code at all.

Configuration issue might be a possibility, I am creating the Geo-Fences manually into the DB. 

I created a geo-fence using traccar-web and then created same geo-fence manually,. in database all the entries/format and spacing etc matched in both case. however it returned this error. for manual entry.

**Comment by tananaev** [comment]
The error indicates that it fails on "database.selectGeofencesAll" query, so I suspect it has something to do with your geofences.

**Comment by jaimzj** [comment]
Will try to test these.
