### ISSUE TITLE
3.8 Update : Attributes column changes Issue

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2648]
Dear Anton,

My MySQL database size for position table is huge in size.

And when I tried to update from 3.7 to 3.8 traccar,. the following update query listed below stops and mysql is stuck for long unable to upgrade.
```
<dropNotNullConstraint tableName="positions" columnName="attributes" columnDataType="VARCHAR(4096)" />
<modifyDataType tableName="positions" columnName="attributes" newDataType="VARCHAR(4000)" />
```
DATABASECHANGELOGLOCK = 1

Also the query running at that point, shows copying to tmp table in mysql, However there is no progress. (the attributes column type change query).

Could you please help me or guide me on how to troubleshoot this? or the reason behind it

**Comment by tananaev** [comment]
You just have to wait. It took about 5 hours to upgrade demo server.

**Comment by jaimzj** [comment]
Wow, Thats a lot of time,. I will try again. and let it run on its own. Thank You.
