### ISSUE TITLE
General Query : Related to on Start DB Query Slow

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2649]
Dear Anton,

I believe I might have posted this in past, However, I want to bring it up again, to see if this can be further investigated, I would like to investigate the issue i face further, where on traccar start this query takes more than 2 hours of time to load.

When the Server is started, if when the query listed below is being run by traccar, if that query is killed/or terminated half way through will it affect traccar or its performance or working?
```
SELECT * 
FROM positions
WHERE id
IN (

SELECT positionId
FROM devices
)
```

**Comment by tananaev** [comment]
What version of MySQL are you using? The issue indicates that you are either using old version of MySQL or it's misconfigured.

**Comment by jaimzj** [comment]
I am using, 
MySQL Server version: 5.5.49-0 ubuntu0.14.04.1 - (Ubuntu)

I have not done any configuration changes on db nor traccar (yes, I do have additional tables and columns in db). I have compared the configurations with another instance that works totally fine and no difference on db either.

**Comment by jaimzj** [comment]
@tananaev Is it possible, you could spare a moment and help me with it by checking on my server? what could be the issue?

**Comment by tananaev** [comment]
You can find a workaround in #2374.

**Comment by jaimzj** [comment]
Thank You Anton, Will try that
