### ISSUE TITLE
Notification emails cannot be sent to servers requiring TLSv1.2

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#2651]
As said in the title :)
Notification emails cannot be sent to servers requiring TLSv1.2
It seems mail.smtps.ssl.protocols has to be set to "TLSv1 TLSv1.1 TLSv1.2" for this to work, otherwise java uses TLSv1.0.

**Comment by tananaev** [comment]
What's the error message?

**Comment by renaudallard** [comment]
(SSL_accept): error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher

**Comment by tananaev** [comment]
Is that from Traccar logs?

**Comment by renaudallard** [comment]
No, this is from the mail server, I can't see anything wrong in traccar logs.
I am testing with this now: https://github.com/renaudallard/traccar/commit/469734eba6a8e781879c4e9802664a5315a8445f

**Comment by tananaev** [comment]
If there is a problem, you should be able to see an error in Traccar logs.

**Comment by renaudallard** [comment]
I found out:
2016-12-06 08:20:52  WARN: Could not convert socket to TLS - MessagingException (... < NotificationMail:110 < *:33 < *:127 < ...)

**Comment by tananaev** [comment]
Are you sure the issue is not with "mail.smtp.ssl.trust"?

**Comment by renaudallard** [comment]
Yes, the certificate is valid and I tried with and without trust set.
Is there a way to easily generate an alarm with osmand protocol?

**Comment by tananaev** [comment]
Yes, just use "test-generator.py" script.

**Comment by tananaev** [comment]
Also, if you didn't know, you can send a test email now. Assuming that you are using latest source code from GitHub.

**Comment by Abyss777** [comment]
Can't confirm your suggestion about default version:
![image](https://cloud.githubusercontent.com/assets/5688080/20921471/037a7e8a-bbc6-11e6-899d-376e634e3880.png)

**Comment by renaudallard** [comment]
When I test with my patch, I don't get any SSL error anymore in the mail server logs, but it still doesn't send the email. And I have another error in the logs.

**Comment by renaudallard** [comment]
After the patch, the error is:
2016-12-06 11:17:02  WARN: Could not connect to SMTP host: mail.arnor.org, port: 465 - MessagingException (... < NotificationMail:112 < *:33 < *:129 < ...)

So that proves the patch did something as I don't have any SSL error anymore. Still, I get a connection drop, but that one may be server side.

**Comment by Abyss777** [comment]
Could you provide the smtp config?

I could not understand what transport are you using, starttls or ssl? 
In the first log you've provided you use starttls, but in second you use 465 port.

**Comment by renaudallard** [comment]
I tried with both starttls and ssl, that's why logs differ

**Comment by Abyss777** [comment]
You can add `session.setDebug(true)` in 95 line, and show what will be in wrapper log.

**Comment by renaudallard** [comment]
that's not very efficient at debugging :-)
``DEBUG: setDebug: JavaMail version 1.4.7
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "mail.arnor.org", port 465, isSSL true
``
And in the log, still only
``2016-12-06 12:34:24  WARN: Could not connect to SMTP host: mail.arnor.org, port: 465 - MessagingException (... < NotificationMail:112 < *:33 < *:129 < ...)
``

**Comment by Abyss777** [comment]
Try to switch on starttls it will go further.

**Comment by renaudallard** [comment]
Not really...
`DEBUG: setDebug: JavaMail version 1.4.7
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "mail.arnor.org", port 587, isSSL false
220 arnor.org ESMTP
DEBUG SMTP: connected to host "mail.arnor.org", port: 587

EHLO eriador.org
250-arnor.org Hello uof8q484w81i9s0r4gvd at arnor.org [91.183.56.64]
250-SIZE 26214400
250-8BITMIME
250-STARTTLS
250 HELP
DEBUG SMTP: Found extension "SIZE", arg "26214400"
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "STARTTLS", arg ""
DEBUG SMTP: Found extension "HELP", arg ""
STARTTLS
220 TLS go ahead
`

**Comment by renaudallard** [comment]
and with the `WARN: Could not convert socket to TLS`
Note that I removed my patch

**Comment by Abyss777** [comment]
Hm, just noticed
`(SSL_accept): error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher`
That means that server and client does not have intersection in ciphers.

Do you have list of ciphers of your server?

**Comment by Abyss777** [comment]
Also the best way to debug is catch few first packets with something like wireshark.
Does your server available from outside? I can make some debug requests.

**Comment by renaudallard** [comment]
The ciphers enabled are CHACHA20:AESGCM+EECDH:EDH+AES256:!DSS:!ECDSA:!SHA:@STRENGTH
If I trust qualys, for java 8, there is a shared cipher:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

Yes, that server is available from outside, you can test on port 587 starttls or 465 ssl

**Comment by Abyss777** [comment]
You are right this cipher are supported only from java 8 http://stackoverflow.com/questions/21289293/java-7-support-of-aes-gcm-in-ssl-tls

But traccar is java 7...

**Comment by Abyss777** [comment]
But you are right if I add
````java
properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
````

It will connect to your server

**Comment by renaudallard** [comment]
Yes, with that parameter, it can connect, but it seems to drop the connection after the SSL negotiation. 
Although I have seen you trying to send an authentication.
This is very strange.

**Comment by Abyss777** [comment]
Yes, I can connect to your server.
````
DEBUG: setDebug: JavaMail version 1.4.7
DEBUG: getProvider() returning javax.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
DEBUG SMTP: useEhlo true, useAuth false
DEBUG SMTP: trying to connect to host "mail.arnor.org", port 465, isSSL true
220 arnor.org ESMTP
DEBUG SMTP: connected to host "mail.arnor.org", port: 465

EHLO wsit007.rg.local
250-arnor.org Hello wsit007.rg.local [91.207.40.229]
250-SIZE 26214400
250-8BITMIME
250-AUTH PLAIN
250 HELP
DEBUG SMTP: Found extension "SIZE", arg "26214400"
DEBUG SMTP: Found extension "8BITMIME", arg ""
DEBUG SMTP: Found extension "AUTH", arg "PLAIN"
DEBUG SMTP: Found extension "HELP", arg ""
DEBUG SMTP: Attempt to authenticate using mechanisms: LOGIN PLAIN DIGEST-MD5 NTLM 
DEBUG SMTP: mechanism LOGIN not supported by server
DEBUG SMTP: AUTH PLAIN command trace suppressed
DEBUG SMTP: AUTH PLAIN failed
````

**Comment by Abyss777** [comment]
You can mail me test credentials for full tests, but anyway I will prepare pull request for `mail.smtp.ssl.protocols` support

**Comment by renaudallard** [comment]
Is your email address the same as the one you tried to authenticate with?

**Comment by Abyss777** [comment]
Better use from github profile or project readme.
That one is for tests.

**Comment by renaudallard** [comment]
I have just sent them

**Comment by renaudallard** [comment]
the user for the authentication is without the domain name

**Comment by renaudallard** [comment]
You used TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256
So better than expected.

**Comment by Abyss777** [comment]
It is not my decision :) They negotiated about it :)
also you can see that everything is OK.

**Comment by Abyss777** [comment]
@renaudallard 
I made pull request.
Thanks for feedback and testing.

**Comment by renaudallard** [comment]
great
