### ISSUE TITLE
Improvement: notification for low battery

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#2656]
Hello,
I don't know if it's really possible as I have no real overview of the numerous supported protocols, but it would be really handy to have a (email) notification when the battery reaches a certain threshold.

**Comment by tananaev** [comment]
Some protocols already support it:

https://github.com/tananaev/traccar/search?q=ALARM_LOW_BATTERY

**Comment by renaudallard** [comment]
But doesn't that mean I need to enable the notification for all "alarms"? I might not wish to receive the alarm for "movement" for example.

**Comment by tananaev** [comment]
Yes, you would have to enable all alarms. There is no way to filter those out at the moment.

**Comment by joepr** [comment]
I'm also searching  for this answer. I'm using mini finder Pico protocol on port 5062. I'm using traccar version 3.9  . Does this low battery alarm is available  on this version?

Best regards

**Comment by tananaev** [comment]
It should be.

**Comment by renaudallard** [comment]
Closing because I am posting in a more useful issue thread
https://github.com/tananaev/traccar/issues/2920
