### ISSUE TITLE
Getting Power Status from Events

### ISSUE THREAD

**Issue by carlost89** [tananaev/traccar#2658]
Hi, I have the following doubt about how getting a device's power status from events table.

The tests were made with a device that uses the **gps103** protocol.

In **events** table is received an event called **ignitionOn** that is related to a **position** which has an **alarm:powerOn** in the attributes field. That makes me think that when this event is received means that the vehicle was recently powered on.

But after a few seconds is received an **ignitionOff** event that is related to a **position** that doesn't have any **alarm** or **alarm:powerOff** in the **attributes** field. Also the vehicle hasn't been powered off when this event is received.

One of the questions is what do really **Ignition** events mean? Aren't they related to the power status of the vehicle?

In order to get the power status I'm using the **powerOn** and **powerOff** Alarms instead of the **ignition** events, but I would appreciate any help to know what these events mean and how is the best way to use them.

Thanks.

**Comment by tananaev** [comment]
Ignition event is based on the "ignition" attribute. Nothing else.

Power on and power off events are received directly from the device. Power on is "acc on"; power off is "acc off".

**Comment by carlost89** [comment]
Thanks for the information.
