### ISSUE TITLE
Devices in map are marked as offline (red) when using osmand 

### ISSUE THREAD

**Issue by duke2906** [tananaev/traccar#2660]
Hi,

I am wondering why all the devices are marked red on the map even if there are positions incoming. In addition the field lastupdate in table devices is always null.... The positions are imported via OSMAND Protocol. Any idea?

**Comment by tananaev** [comment]
They are not marked red for me. Are you using latest official release of Traccar?

**Comment by duke2906** [comment]
3.8, installed 2 days ago. Maybe an Issue due the database? The Database schema was from version ...(3.6?) before updating to 3.8.

![image](https://cloud.githubusercontent.com/assets/6961400/20986517/4c2e84e2-bcc9-11e6-9224-55c5ea1f80fd.png)

Or because of the huge amount of devices? I added 10.000 Devices with UniqueID from 1 to 9999 due to more "flexability". Because most of our vehicles have an ID in between this range. For unplanned vehicles   (doesn't happen that often) we are using the "autoregister" function, because these are not added to the map dynamically. (If a devices is registered automatically, this is only shown on the Map after a refresh)

**Comment by tananaev** [comment]
Note that after server restart status for all devices is reset to "offline". That's the only way OsmAnd-based devices can get into red (offline) state.

**Comment by duke2906** [comment]
Server is being restarted every day 2 pm. But the devices should get online after receiving new positions again, shouldn't they?
Atm positions are incoming (these vehicles are driving in the night only), so the markers are moving... 
The request to send the position is the following:
http://xxxxxxxxxxxx:5055/?id={0}&lat={1}&lon={2}&timestamp={3}&heading={4}&speed={5}

**Comment by tananaev** [comment]
Yes, they should. I can take a look if you provide access to the web console.

**Comment by duke2906** [comment]
Shall i send you an email with the credentials? Don't know an direct message function in github... You need an admin user, or the "standard" user the people are supposed to use when checking positions?

**Comment by tananaev** [comment]
Standard user should do. You can send me details by email (address is in profile).

**Comment by duke2906** [comment]
Send it to you via mail. I have to leave for today now, thank you very much for you help!! 👍 :-)

**Comment by tananaev** [comment]
I have checked your server and it doesn't send any status updates at all. Are you sure you are using official source code without any modifications? Are you building from "master" or from a tag?

**Comment by duke2906** [comment]
Used this one
https://github.com/tananaev/traccar/releases/download/v3.8/traccar-linux-3.8.zip and than 
`sudo ./traccar.run`
`after unzip.

**Comment by tananaev** [comment]
Sorry, I misread your previous comment. If you are using official release, then everything should work. Please try demo server and see if you have similar problems.

**Comment by duke2906** [comment]
Demo is working...well than ill try to reinstall and dropping database

**Comment by duke2906** [comment]
Mhh now they are yellow. I guess when I restart the server they are going and keeping red again... Am I doing anything wrong? I just run ./traccar.run as root, create a schema "traccar" with collection UTF-8 and configure traccar to use the mysql-db

**Comment by tananaev** [comment]
Did it happen again after restart?

**Comment by duke2906** [comment]
I'll try right after I'm back in the office in the late evening and give
you feedback. To ensure that I am not sending incorrect data via OSMAND
with my custom process I added my smartphone via the official android
client. Same result

Anton Tananaev <notifications@github.com> schrieb am Do., 8. Dez. 2016,
10:14:

**Comment by duke2906** [comment]
Restarted - red

**Comment by tananaev** [comment]
The fact the status is reset to red after restart is an expected behavior. The question is weather is stays red even after devices start sending data.

**Comment by duke2906** [comment]
It does . That's what I meant

Anton Tananaev <notifications@github.com> schrieb am Do., 8. Dez. 2016,
22:17:

**Comment by tananaev** [comment]
I guess I would need access to your server to check what's going on.

**Comment by duke2906** [comment]
Not that easy due this server is from my work and not accessable via ssh etc. from outside the company-network or vpn. ill have to think about a way...

**Comment by duke2906** [comment]
Updated to Version 3.9

Seems to work now as it is supposed to... curious

thanks a lot for you help and for your time!!

**Comment by duke2906** [comment]
Sorry, have to reopen cause I'm able to reproduce this Issue.

The missing updates (last updated, device status) occour only when setting parameter decoder.ignoreSessionCache is set to true...

**Comment by tananaev** [comment]
Are you saying that problem happens with `ignoreSessionCache` set to `true`, or the problem doesn't happen when it's set to `true`?

**Comment by duke2906** [comment]
If you set ignoreSessionCache to true you will be able to reproduce this issue.

[https://github.com/tananaev/traccar/blob/master/src/org/traccar/BaseProtocolDecoder.java#L172](url)

If you consider the linked code-line you can see that the `onMessageEvent` methos queries `getDeviceSession` with `channel` and `remoteAddress` parameters. `UniqueIds` is even not implemented in the `onMessageEvent` method. Obviously this isn't that easy due this attribute is not known in the section where `onMessageEvent` is called. But due to `database.ignoreSessionCache` the DeviceSession is allways queried with uniqueId's. Even if it would be queried via `remoteAddress` it would be result in null cause the previous DeviceSession is not stored in `addressDeviceSessions`

I'm not an professional programmer - to be honest I think that my skills are just on an amateur level (like my english :-D ) So I haven't found an solution right now, but I'll think about it and update this post.

**Comment by tananaev** [comment]
Thanks for the details about the problem. I have fixed it.

**Comment by duke2906** [comment]
I am glad I was able to help. Again, thanks all lot for you fast support and fix.
