### ISSUE TITLE
New unknown port: 15003

### ISSUE THREAD

**Issue by TwizzyDizzy** [tananaev/traccar#2671]
Hi Anton,

I just upgraded from traccar 3.7 to traccar 3.9. Worked like a charm, yet there is a new port that is opened and I can't seem to find any information on what this port is. If I try to connect to it, the connections is reset, yet traccar logs:

    INFO|13963/0|Service traccar|16-12-10 16:21:32|app already logged on -> rejecting new connection

What's going on with this port and can I limit it to only listen on localhost (give it provides no function I new from the outside world).

Cheers & thanks
Thomas

**Comment by tananaev** [comment]
Looks like it's a YAJSW port. Here is the documentation:
> The Wrapper uses a socket to communicate with the java or groovy application. It waits for the application to connect. Only connections from localhost are accepted. Only a single connection which has been authenticated is accepted. All other connections are rejected. If the application has not authenticated itsself within a timeout, the wrapper will restart it.
>
> Generally the wrapper will search for a free port. In some cases you may need to assign a specific port or a range of ports.
>
> This property allows the configuration of a specific port.
>
> NOTE: native applications are currently not wrapped by java. Therefore the wrapper (controller) only monitors that the application is running. It does not monitor hangging of the application and therefore does not require a port.

Sounds like it should accept local connections only. Port number can be configured using `wrapper.port` parameter.

**Comment by TwizzyDizzy** [comment]
Thanks for the pointer to the documentation, yet I see no abvious reason why this port must be open to the outside world. Of course, the wrapper application might drop any request that is not from localhost, but it would be much wiser to not open the port at all, since application code might be buggy.

Anyhow, since YAJSW doesn't support the binding to a specific address (not port, that's possible as said abobe) the critique may at best be directed towards the decision to choose YAJSW, since traccar itself seems to have no word in the service wrapper address/port-bindings.

My solution is to bind YAJSW to a specific port (via wrapper.port in `/path/to/traccar/conf/wrapper.conf`) and to drop any traffic to this port from the outside world via iptables.

Still, thanks for getting back to me :)

Cheers
Thomas
