### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by sunhoww** [tananaev/traccar#2680]
@tananaev Would you care for something like this?

https://github.com/sunhoww/traccar/blob/update_swagger/docs/api.md

I'm using _swagger.json_ to generate this.

**Comment by sunhoww** [comment]
I made a simple python script for the Markdown. With a few changes, I might get it to generate HTML. I can give a shot.

**Comment by tananaev** [comment]
That would be great, thanks.

**Comment by sunhoww** [comment]
So should I just use plain HTML for the markup? Organize everything semantically. Or would you need the tags to be styled using stylesheets from the official website?

**Comment by tananaev** [comment]
I think it would be easier if it was just plain HTML.

**Comment by sunhoww** [comment]
OK.

In the meantime, would you still want me to commit the API doc file in the OP? I also made lot of changes in _swagger.json_ as well.

**Comment by tananaev** [comment]
I definitely want improvements to swagger, not sure about the md mod.

**Comment by sunhoww** [comment]
Alright. I'll commit just the swagger changes.

**Comment by sunhoww** [comment]
Tentatively, https://gist.github.com/sunhoww/e28353cadb3864158e616090f39a1b81

We could change the organization / format.

**Comment by tananaev** [comment]
I have put a draft here:

http://www.traccar.org/api-reference/

Looks almost right. I think we need to add some table CSS classes. Take a look at the first table there. I've tried to add `class="table-bordered"`.

It would be nice if you include the script into the `tools` folder.

**Comment by sunhoww** [comment]
I'll add the classes. Also the `h4` tags holding the endpoints seem a bit lost among the other texts. Maybe we could highlight it or something.

**Comment by tananaev** [comment]
You can try to use `h2` for headers.

**Comment by sunhoww** [comment]
I don't think we should change the tag. Hierarchically, `h2` is being used at a different level. Instead, we could give it some `class`.

**Comment by tananaev** [comment]
Possibly adding table classes would be enough to separate everything.

**Comment by sunhoww** [comment]
https://gist.github.com/sunhoww/e28353cadb3864158e616090f39a1b81

Added the table class.

**Comment by tananaev** [comment]
Looks good now:

https://www.traccar.org/api-reference/

**Comment by sunhoww** [comment]
Great. I'll include the script with the PR I have open.
