### ISSUE TITLE
Xexun XT107 dont display alarm SOS

### ISSUE THREAD

**Issue by norgaston** [tananaev/traccar#2689]
Hello, I'm trying out a Xexun Xt107 in Traccar and I've noticed that SOS notification is not sent via the web. I have researched a bit and here are the data sent by the Xexun:
```
161213123444, + 5492932630xxx, GPRMC, 153444.704, A, 3852.9240, S, 06204.8832, W, 0.94.31.95,131216 ,,, A * 56, F, help me, imei: 013227xxxxxxxxx, 04.7.5, F: 3.92V, 0.146 , 45867,722,310.1FAA, 2EEA
```
What I have noticed is that in the decoding of the frame, the software expects a "help me!" And not a "help me" ... How could you correct this problem? Thank you very much.

**Comment by norgaston** [comment]
Hi, I have edited XexunProtocolDecoder.java and I was able to solve this detail. I downloaded NetBeans and the Github source code. Thank you.

**Comment by tananaev** [comment]
It would be nice if you can send a pull request. Thanks.
