### ISSUE TITLE
User position is not shown with https connection

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2691]
Hi,

I configured nginx and ssl to enable HTTPS setup. I am still using Traccar version 3.8.

Now if I login using https I dont see the user position on the map. Please find below screenshots for both HTTP and HTTPS connection.

**HTTP:**
![screenshot from 2016-12-15 20 03 54](https://cloud.githubusercontent.com/assets/1178055/21228004/2fbd4c8c-c302-11e6-9681-ea3824bf2392.png)

**HTTPS:**
![screenshot from 2016-12-15 20 04 50](https://cloud.githubusercontent.com/assets/1178055/21228014/348ede42-c302-11e6-8696-a818a967cf5c.png)

**Comment by kirantpatil** [comment]
I created ssl key and certificate using below link:
https://www.digitalocean.com/community/tutorials/how-to-create-an-ssl-certificate-on-nginx-for-ubuntu-14-04

**Comment by kirantpatil** [comment]
Additional screenshots of HTTPS with socket error 

![screenshot from 2016-12-15 20 24 56](https://cloud.githubusercontent.com/assets/1178055/21228695/d5eae784-c304-11e6-9d0e-49f250f504c5.png)

![screenshot from 2016-12-15 20 22 59](https://cloud.githubusercontent.com/assets/1178055/21228703/daac7af8-c304-11e6-9863-62e19c6fbf39.png)

**Comment by kirantpatil** [comment]
# NGINX HTTPS configuration at /etc/nginx/sites-available/default in Ubuntu 14.04

```
server {
        listen 443;
        server_name localhost;

        root html;
        index index.html index.htm;

        ssl on;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        ssl_session_timeout 5m;

        ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
        ssl_prefer_server_ciphers on;

        location / {

proxy_redirect off;
proxy_buffering off;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
port_in_redirect off;
proxy_connect_timeout 900;
proxy_send_timeout 900;
proxy_read_timeout 900;
send_timeout 900;

#               try_files $uri $uri/ =404;
proxy_pass http://127.0.0.1:8082;
#              proxy_redirect ws://localhost:8082/api/socket /api/socket;
        }
}
```

**Comment by tananaev** [comment]
How do you forward WebSocket connection? I don't see anything related to WS in your nginx config.

**Comment by kirantpatil** [comment]
I tried to enable the last line for WS, but it didn't work. Is that correct way to forward Websocket connection.

#              proxy_redirect ws://localhost:8082/api/socket /api/socket;

**Comment by tananaev** [comment]
I don't know how to do it on nginx. I remember it was discussed before, so you can try to find a config on GitHub or forum.

**Comment by kirantpatil** [comment]
https://github.com/tananaev/traccar-web/issues/277 helped me to resolve issue.

Please find the below updated configuration file.

# HTTPS server

```
server {
        listen 443;
        server_name localhost;

        root html;
        index index.html index.htm;

        ssl on;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        ssl_session_timeout 5m;

        ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES";
        ssl_prefer_server_ciphers on;

        location / {
proxy_redirect off;
proxy_buffering off;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
port_in_redirect off;
proxy_connect_timeout 900;
proxy_send_timeout 900;
proxy_read_timeout 900;
send_timeout 900;
#               try_files $uri $uri/ =404;
                proxy_pass http://127.0.0.1:8082;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
#       proxy_redirect ws://localhost:8082/api/socket /api/socket;
        }
}
```

**Comment by sunhoww** [comment]
Seems I'm  a bit late. But anyways, http://nginx.org/en/docs/http/websocket.html says the `Upgrade` and `Connection` headers need to be explicitly passed.

Also, I think it would be better to use _letsencrypt_ instead of self signed certificates. True updating them every few months can be quite a hassle. But you could `cron` it or something. At least that's what I do.

**Comment by kirantpatil** [comment]
Thanks a lot. I will follow your suggestion.
