### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2693]
@tananaev sorry for any kind of inconvenience i am closing the existing ticket and starting a new one specially for websocket access from diffrent web interface.
As you are aware of the my situation that  i want to consume websocket from traccar server which is hosted on my server 104.131.22.103:8082 on same server i have hosted another web interface from which i want to consume websocket which is working fine if i logged in into traccar web app.
But as soon as i got logged out from traccar app websocket connection fails. 
i dont have any domain name yet so i am not using https.
is there any other way to authenticate webscoket?

suggest me any solution  for this because it's very important to me to use websockets because right now i am using ajax call every second to check for position updates which is not efficient for me.
thak you.

**Comment by tananaev** [comment]
You can find a working example here:

https://github.com/tananaev/traccar-web/blob/master/web/simple/app.js

**Comment by d33pak-s1ngh** [comment]
@tananaev  thank u so much it is working man. i dont know what was wrong with my ajax call but with your code it is working fine thanx again for support.
