### ISSUE TITLE
Traccar 3.8 or  3.9  issues

### ISSUE THREAD

**Issue by kedarnathjimage** [tananaev/traccar#2694]
hi tananaev,

In traccar version 3.8 and 3.9 not inserting device status like online or offline.
please revert on this.

**Comment by tananaev** [comment]
What is the question exactly? There is no point in saving connection status in the database.

**Comment by kedarnathjimage** [comment]
I was replying on the connection status which stated if device was online or offline. Is it removed now from new version ??

**Comment by tananaev** [comment]
Status is not saved in the database anymore, but it's still available through the API.

**Comment by kedarnathjimage** [comment]
Can you please guide me on the API. 

highly appreciate it. Thanks

**Comment by tananaev** [comment]
Please read the official documentation:

https://www.traccar.org/traccar-api/
https://www.traccar.org/api-reference
