### ISSUE TITLE
[Feature Request] Expiry time for Embedded public view

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2695]
Hello @tananaev,

I would like to set the Expiry Time (1 hour, 2 hour, 1 day ...) for Embedded public view by the user.

Thanks.

**Comment by tananaev** [comment]
You can set expiration time on user, so the functionality is already available.

**Comment by kirantpatil** [comment]
Yes Sir, I know the user expiration feature. But what I would like to achieve is expire the public view only rather disabling the user itself. 

Use case would be like, I might share my tracking link to my parents for safe commute. So they can check if I reached the destination.

**Comment by tananaev** [comment]
You create separate user with limited expiration time, assign it same devices, and get exactly what you want.

**Comment by kirantpatil** [comment]
Ok Sir, right now I will go by your advise.
