### ISSUE TITLE
Additional attributes for Events

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#2701]
If we started store some attributes in Events I have couple suggestions:

1. For OverspeedEventHandler - store effective `speedLimit` and device `speed`, Because it is impossible determine `speedLimit` for old events (it could be changed after). Also user can get information how much was overspeeding, like "Device exceeds the speed on 5 km/h"

2. For MaintenanceEventHandler  - store `totalDistance`, just for historical reports, without additional requests to positions table.

**Comment by tananaev** [comment]
Both suggestions sound good to me.
