### ISSUE TITLE
field details

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2704]
i want to know about some database fields and what value need to set for that.
1. in a socket response for positions there is field call outDated=false and valid=true what this means?
2. what will happen if i will set status=false into device table for device? it will stop recording position for that device or device will no more visible into web-interface?

**Comment by tananaev** [comment]
1. `outdated` means that GPS info was taken from older report
`valid` is a flag reported directly by GPS module
2. there is no `status` in the device table

**Comment by d33pak-s1ngh** [comment]
how do i stop device from sending location is there any way to off device?

**Comment by tananaev** [comment]
Only by sending command to the device, if it's supported for the protocol.
