### ISSUE TITLE
deleted Geofence is visible from Admin login -> Users

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2706]
Hi,

This issue may be fixed in current release version 3.9, since I am using Traccar version: Master branch (On Nov 28, compiled Master build to check Polyline geofence), please feel free to close the issue.

I deleted all Geofence from admin panel and now if I go to Users -> Geofences, the deleted Geofence is still visible for User (admin and other users to which it is assigned).

Please find the below screenshots in order.

![screenshot from 2016-12-19 12 09 47](https://cloud.githubusercontent.com/assets/1178055/21303471/92866f44-c5e4-11e6-9068-e32c79fa7e89.png)

![screenshot from 2016-12-19 12 09 24](https://cloud.githubusercontent.com/assets/1178055/21303473/98436d06-c5e4-11e6-9422-fca2f667fe1e.png)

![screenshot from 2016-12-19 12 08 28](https://cloud.githubusercontent.com/assets/1178055/21303476/a079b69c-c5e4-11e6-94b4-6e36005e5506.png)

**Comment by Abyss777** [comment]
I've tested, but can not confirm the issue. Do you have any errors in browser console or traccar logs?

**Comment by kirantpatil** [comment]
I did not find any error in browser.

I restarted the server, app still show the geofence and below is the log with some error and I don't think it is related to geofence.

### $ java -jar tracker-server.jar conf/traccar.xml
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO 12/19/16 2:27 PM: liquibase: Clearing database change log checksums
INFO 12/19/16 2:27 PM: liquibase: Successfully acquired change log lock
INFO 12/19/16 2:27 PM: liquibase: Successfully released change log lock
INFO 12/19/16 2:27 PM: liquibase: Successfully acquired change log lock
INFO 12/19/16 2:27 PM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO 12/19/16 2:27 PM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO 12/19/16 2:27 PM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::author: Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  Error: Constraint "UK_USER_TOKEN" not found; SQL statement:
ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token [90057-193] [Failed SQL: ALTER TABLE PUBLIC.users DROP CONSTRAINT uk_user_token]
INFO 12/19/16 2:27 PM: liquibase: Successfully released change log lock
[main] INFO org.eclipse.jetty.util.log - Logging initialized @2842ms
[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@56d8db57{/api,null,AVAILABLE}
[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@64bce009{HTTP/1.1}{0.0.0.0:8082}
[main] INFO org.eclipse.jetty.server.Server - Started @4291ms

![screenshot from 2016-12-19 14 33 10](https://cloud.githubusercontent.com/assets/1178055/21306648/1ee29c84-c5f8-11e6-81d9-ceb3db013058.png)

**Comment by Abyss777** [comment]
- Open browser console.
- Link geofence to admin back and delete it again.
- Check if delete request was successful

**Comment by kirantpatil** [comment]
Now after restart "circle" geofence appeared in Geofences, I removed it and now it no more present as earlier shown. Right now am closing this issue. I will retest once again to confirm and reopen it.
