### ISSUE TITLE
State column width changes

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#2707]
Device is selected. With every update column size changes in the State table. Does anybody else have the same issue?

@Abyss777, does it happen to you?

**Comment by Abyss777** [comment]
Oh, really, did not notice it before.

Selecting device increases left state column, happen only 3-4 times, then stops.

**Comment by tananaev** [comment]
Very weird. Please check when you have time. I'll check tomorrow as well.

**Comment by Abyss777** [comment]
`forceFit: true,` causes it

if we make `State.js` like this:
````java
//forceFit: true,

    columns: {
        defaults: {
            minWidth: Traccar.Style.columnWidthNormal
        },
        items: [{
            text: Strings.stateName,
            dataIndex: 'name',
            flex: 1
        }, {
            text: Strings.stateValue,
            dataIndex: 'value',
            flex: 1,
            renderer: function (value, metaData, record) {
                if (record.get('attribute') === 'alarm') {
                    metaData.tdCls = 'view-color-red';
                }
                return value;
            }
        }]
    }
````

It will changes width only once then switch from empty state to state containing something and back. And what is weird it does not happen in mobile chrome.

Also we can play with flex ratio, like 3/5, because attribute names are mostly shorter than its values.

**Comment by tananaev** [comment]
Looks like it's an ExtJS issue. Implemented a workaround for now:

https://github.com/tananaev/traccar-web/commit/0a465cee9200e0ae297aa9fe7eb9ac78be4636ad
