### ISSUE TITLE
traccar with Openjdk by default

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2708]
Hi,

I came across the below link,

http://www.theregister.co.uk/2016/12/16/oracle_targets_java_users_non_compliance?mt=1482153463991

I felt we need to make Openjdk by default while building the traccar stack.

Thanks.

**Comment by tananaev** [comment]
Traccar can use any Java JRE. What do you mean by "OpenJDK by default"?

**Comment by kirantpatil** [comment]
IMHO during installation some kind of message to use OpenJDK by default would be appropriate

**Comment by tananaev** [comment]
I don't think it would be appropriate. User can use whatever runtime he wants. Oracle has terms and conditions, and if you user uses it, it must accept those conditions.

**Comment by kirantpatil** [comment]
Just wanted to convey the message that Oracle is projecting Oracle Java as non Freesoftware

**Comment by tananaev** [comment]
It's good to know, but I don't think any software should recommend user what JRE to use.

**Comment by tananaev** [comment]
Answer from RedHat:

https://developers.redhat.com/blog/2016/06/27/openjdk-now-available-for-windows/

It might also be useful for people who have problems with Oracle JRE on Windows.
