### ISSUE TITLE
[Dev help] How to modify front end source code ?

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2720]
Hi,

I would like to dive in to understand how to change the front end (html, Javascript) ?

I want to add one more type for "Reports" along with "Route, Event, Trips ..." and once I click on it would like to display a html page 

Please guide me how to do it.

![screenshot from 2016-12-21 14 15 33](https://cloud.githubusercontent.com/assets/1178055/21382879/e944faf8-c788-11e6-863e-650909ebb02d.png)

Thanks.

**Comment by tananaev** [comment]
I would recommend to start with ExtJS documentation:

http://docs.sencha.com/extjs/6.2.0/index.html
