### ISSUE TITLE
unable to assign Geofence to device

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2721]
Steps to reproduce:
---------
1. login to http://demo.traccar.org/
2. Create a Geofence
3. Try to assign to Device.

![screenshot from 2016-12-21 18 58 55](https://cloud.githubusercontent.com/assets/1178055/21391120/3bdebe8a-c7b0-11e6-9fc3-15c36041a8dc.png)

**Comment by Abyss777** [comment]
Usual question... what is in browser console, especially response on XHR request?

**Comment by kirantpatil** [comment]
Sir, I don't see any error in browser console after trying to select the Geofence.

![screenshot from 2016-12-21 19 11 50](https://cloud.githubusercontent.com/assets/1178055/21391366/6e2128dc-c7b1-11e6-822a-3325719d244b.png)

**Comment by Abyss777** [comment]
Please, show the Network tab.

**Comment by Abyss777** [comment]
Oh, looks like Firefox/ExtJS issue. Try to click a bit righter

![image](https://cloud.githubusercontent.com/assets/5688080/21391758/dc2dd986-c7ae-11e6-9c5d-d5c6afbc10a7.png)

**Comment by kirantpatil** [comment]
Yup, you nailed it. I need to click a bit righter. Thanks.

I am curious to know why ExtJS compared to Emberjs or Angular or React, since all of them are Opensource ?

**Comment by tananaev** [comment]
ExtJS is a framework that has everything. Angular, React etc are completely different things. They don't provide any ready-to-use components. In the long term, we might use one of them.

**Comment by kirantpatil** [comment]
@Abyss777, pre 3.9 release version of master branch is working fine. I believe during last 10 day of before 3.9 release this issue has propped up.

**Comment by tananaev** [comment]
It probably means that it's an ExtJS 6.2.0 issue. The only thing we can do is to wait for them to fix it.

**Comment by Abyss777** [comment]
Looks like it is already fixed in 6.2.1 branch
https://fiddle.sencha.com/#view/editor&fiddle/1n36
If you switch to ExtJS 6.2.1.167, it will work correctly.

**Comment by tananaev** [comment]
The problem is that 6.2.1 is not GPL version.

**Comment by JohnnyDevine** [comment]
FYI this is still the same in Firefox 56.0.1 on OSX, I have to click a bit righterer
