### ISSUE TITLE
Building upper version (3.3)  with Netbeans

### ISSUE THREAD

**Issue by DrWaves** [tananaev/traccar#2730]
Hi !
 I try to build the project by NetBeans IDE 8.2 on mac and but it's possible with the version  up to 3.3 (included). Indeed, i don't find the file "org.traccar.Main" with the upper version.
Is it an issue ? 

( documentation : https://www.traccar.org/build-in-netbeans/ )
<img width="1307" alt="capture d ecran 2016-12-26 a 22 56 59" src="https://cloud.githubusercontent.com/assets/24669466/21486978/d0704034-cbbe-11e6-8b14-bed973aaf42b.png">
 thanks a lot !

**Comment by tananaev** [comment]
What do you mean by "upper version"? Any version has a main class.

**Comment by DrWaves** [comment]
The release from 3.4 to 3.9 (the current latest version). 
Netbeans doesn't detect org.traccar.Main for theses releases.

**Comment by tananaev** [comment]
There is no difference. All of the versions have the main file. I would recommend to use IntelliJ IDEA instead of NetBeans.

**Comment by DrWaves** [comment]
My bad, You are right. I try it with IntelliJ and it's work perfectly. thanks !
