### ISSUE TITLE
positionId in devices table doesn't get updated

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#2732]
Hello,
I am running a snapshot of traccar (and traccar-web) of the 27th dec. I noticed that in the database, positionId in devices table is now set to NULL for all devices instead of the latest positionId.

**Comment by Abyss777** [comment]
Hello,
What is in the logs?
Have you migrated from some previous DB or use new one?

**Comment by renaudallard** [comment]
It's the same DB. All the schemas were present at start.

**Comment by renaudallard** [comment]
It might be due to this:
`2016-12-27 13:07:44  WARN: Unknown column 'accuracy' in 'field list' - MySQLSyntaxErrorException (... < QueryBuilder:473 < DataManager:292 < DefaultDataHandler:27 < ...)
`

**Comment by Abyss777** [comment]
That means that your database have not been migrated.
Possible reason that you used github snapshot before, and already applied 3.10 changelog. It won't be applied again even if there is some changes.

You need to manually migrate your DB.

**Comment by renaudallard** [comment]
So I would need to re-apply parts of the 3.10 changelog?

**Comment by Abyss777** [comment]
Yes. Changes from this commit https://github.com/tananaev/traccar/commit/12e88e5cccc00eb5882124db9e0350ae568902e6
Just two columns

**Comment by renaudallard** [comment]
I left a comment in that commit. Isn't a varchar(4000) a little bit huge?

**Comment by renaudallard** [comment]
OK, that solves the issue. Thanks
