### ISSUE TITLE
How to work with Postgresql?

### ISSUE THREAD

**Issue by salvador11233** [tananaev/traccar#2734]
Hi I have a question like I can work with postgresql, I do not know the variables of the coloumnas, I know that I must replace the following commands:
```
<Entry key = 'database.driver'> org.postgresql.Driver </ entry>
<Entry key = 'database.url'> jdbc: postgresql: //127.0.0.1: 5432 / [DATABASE] </ entry>
<Entry key = 'database.user'> [USER] </ entry>
<Entry key = 'database.password'> [PASSWORD] </ entry>
```
thanks friends.

**Comment by salvador11233** [comment]
Sorry columns

**Comment by tananaev** [comment]
Then the question doesn't make sense to me. What columns are you talking about?

**Comment by salvador11233** [comment]
Forgive, what kind of records or what should be captured in the postgresql table?

**Comment by tananaev** [comment]
Which table?

**Comment by tananaev** [comment]
Traccar will create multiple tables, not just one.

**Comment by salvador11233** [comment]
Then traccar automatically creates the tables

**Comment by tananaev** [comment]
Yes, it does.

**Comment by salvador11233** [comment]
Thank you very much for your attention and very good contribution, good day, bye.
