### ISSUE TITLE
speed conversion

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2740]
which formula you are using to convert kilometer to knot and vise versa
what i am doing is
if user will enter speed in km then i am converting it into knot and storing it into databse.
knot = $km / 1.943844
and for knot to km i am using following
km = ((knotspeed / 1.943844) * 3600) / 1000

**Comment by Abyss777** [comment]
https://github.com/tananaev/traccar/blob/master/src/org/traccar/helper/UnitsConverter.java
