### ISSUE TITLE
mirroring...

### ISSUE THREAD

**Issue by marsu211** [tananaev/traccar#2746]
I have 2 traccar servers running. Only 1 is receiving the GPS trackers' information.
The second server is

1) Backup
2) Consultation

I would like to have the Liver server to automatically update the second server if possible every time it received a geolocalisation info form a tracker but at least every minute.

Is there anyway doing it?

Thx for any help on this

patrick

**Comment by tananaev** [comment]
What is "Liver server"? Do you mean main server?

It's possible to configure data forwarding to the second server, but it won't save all the attributes.

**Comment by marsu211** [comment]
Yes it is the main server.

I need th secon as backup and for visualisation, 
There will be no attribute changes during event, so only tracking data needed

**Comment by tananaev** [comment]
I can think of two options:

1. Configure database replication
2. Make main Traccar server forward data to the secondary one

**Comment by marsu211** [comment]
ok, any idea where to configure this? I have tried with cluster file copy....no errors but copies

**Comment by tananaev** [comment]
Which option are you talking about? Replication is a database feature and has nothing to do with Traccar. The problem with replication is that Traccar has some internal cache which won't be updated in this case.

With data forwarding everything will work properly, but additional attributes won't be saved. Search GitHub and/or forum for more details on how to configure it.

**Comment by marsu211** [comment]
I'm clustering both servers.
I'l update here once I found how to.
Thx
patrick

**Comment by blackmonk88** [comment]
I agree with @tananaev  that it's should be database mirroring / replication.

So the solution is what is your database system, I prefer MySQL as it's easy to do mysql replication (master-master or master-slave)

**Comment by marsu211** [comment]
Hi,
I use the default brought with traccar. I made no specific settings for any DB system

**Comment by tananaev** [comment]
@blackmonk88, the problem is that Traccar has internal cache that replication won't update.

@marsu211, I would not recommend to use default H2 database for production use.

**Comment by marsu211** [comment]
OK, so do I need to create a MySql DB instead? Thx for the tip

**Comment by tananaev** [comment]
Yes, either MySQL or any other fully featured database.

**Comment by marsu211** [comment]
Well, to get back to the base question:

Would it be possible to open a "request" for future development to have a Traccar mirroring option?

**Comment by tananaev** [comment]
As I said, you can already forward the data. Please carefully read my previous comments.

**Comment by marsu211** [comment]
Thank you for the support. Now closing this.
