### ISSUE TITLE
[Request] - CouchDB ?

### ISSUE THREAD

**Issue by marsu211** [tananaev/traccar#2749]
HI,

Getting back to my other DB and mirroring issue, I would like to address this request:

Anyway to use CouchDB or the-like as DataBase system for Traccar?

Thank you
Patrick

**Comment by tananaev** [comment]
How does it solve the problem of mirroring?

As for using CouchDB, you would have to do some significant code modifications to be able to use it.

**Comment by marsu211** [comment]
Well I agree it might ave been a bad idea. I was just thinking about having the DB in the cloud. We used that for events and worked amazingly good and fast.

I have now setup MySql on both servers. Not yet replicating, this will be next goal, after getting all my Test trackers to work. I need 80 working trackers in 4 months....

Thx for all
Patrick

**Comment by tananaev** [comment]
You can put any database in the cloud, but it won't solve any problems. It just makes it easier to maintain... usually.

Why do you need two servers?

**Comment by marsu211** [comment]
Failover
