### ISSUE TITLE
CalAmp ignition

### ISSUE THREAD

**Issue by gbvaz** [tananaev/traccar#2752]
Hello,

I've successfully setup a CalAmp device under UDP protocol, it's all working well, except the ignition flag.

Here's what I get from the attributes column from a couple of my positions:
```json
{"sat":8,"carrier":23,"gsm":-73,"modem":47,"hdop":11,"input":5,"status":0,"event":30,"acc0":12900,"acc1":3993,"acc2":500,"acc3":8842212,"acc4":8,"acc5":0,"acc6":0,"acc7":0,"acc8":127,"acc9":47448903,"acc10":3550886,"acc11":5040,"acc12":5040,"acc13":5,"acc14":0,"acc15":0,"distance":384.32,"ip":"201.20.37.27"}

{"sat":10,"carrier":23,"gsm":-69,"modem":47,"hdop":8,"input":5,"status":0,"event":30,"acc0":13100,"acc1":3987,"acc2":500,"acc3":8842212,"acc4":8,"acc5":0,"acc6":0,"acc7":0,"acc8":131,"acc9":47448903,"acc10":3550886,"acc11":10320,"acc12":10320,"acc13":5,"acc14":0,"acc15":0,"distance":566.91,"ip":"201.20.37.27"}
```
I can see that there are a lot of acc attributes, and that they stand for a lot of stuff according to CalAmp manual. But I don't understand why ignition is not showing up like the distance attribute or if I should I manually convert any of these acc values into the ignition? I couldn't correspond the acc number with the manual info. Which one is it? I'm using Traccar version 3.7

Thank you!

**Comment by tananaev** [comment]
It might be one of those acc(umulator) values. I guess it's better to check with CalAmp.

**Comment by gbvaz** [comment]
Can I send you the manual I have so you can take a look? I couldn't figure it out..

**Comment by tananaev** [comment]
I have all the information, but it's not very clear for me either.

**Comment by gbvaz** [comment]
Ok, thanks! I'll contact the manufacturer, and I'll post here the outcome.

**Comment by shakiru** [comment]
tananaev, to decode ignition, you need convert the input signal (Input statuses of the unit; bit0=Ignition, bit2 on 2x00 & 4x00 =motion, bit5 on 1x00 = motion (1 byte)).
Input value is a binary value.
If input is 05 the binary value is 00000**1**0**1** (bit0 = 1, bit2 = 1) and the decoded value is IgnitionOn and Input2 active.

**Comment by tananaev** [comment]
How do you know that "bit0=Ignition"? I can't find anything about it in the documentation.

**Comment by shakiru** [comment]
Hi, Calamp documentation is here https://puls.calamp.com/wiki/LM_Direct_Reference_Guide but it is private only for customers. 
If you have access, you can download CalAmp LMU Toolbox program and decode the hex message.
The documentation is very large but I paste a fragment to you. Please refer for Inputs section.
Congrats for traccar, is good job.

Update Time (4 bytes)
The time tag of the message in seconds, referenced from Jan. 1, 1970

Time of Fix (4 bytes)
The last known time of fix from the GPS satellites. This value is reported in seconds from Jan. 1, 1970

Latitude (4 bytes)
The latitude reading of the GPS receiver, measured in degrees with a 1x10^-7 degree lsb, signed 2’s complement

Longitude (4 bytes)
The longitude reading of the GPS receiver, measured in degrees with a 1x10^-7 degree lsb, signed 2’s complement

Altitude (4 bytes)
The altitude reading of the GPS receiver measured in centimeters above the WGS-84 Datum, signed 2’s complement

Speed (4 bytes)
The speed as reported by the GPS receiver, measured in centimeters per second

Heading (2 bytes)
The heading value reported in degrees from true North

Satellites (1 byte)
The number of satellites used in the GPS solution

Fix Status (1 byte)
The current fix status of the GPS receiver bitmapped as follows:
Bit 0 – Predicted
Bit is set when the position update has a horizontal position accuracy estimate that is less that the Horizontal Position Accuracy Threshold defined in S-Register 142 (and the threshold is non-zero).
Bit 1 – Differentially Corrected
This bit is set when WAAS DGPS is enabled (S-Register 139) and the position has been differentially corrected
Bit 2 – Last Known
This bit is set when the current GPS fix is invalid but a previous fix’s value is available.
Bit 3 – Invalid Fix
This bit is set only after a power-up or reset before a valid fix is obtained.
Bit 4 – 2D Fix
This bit is set when 3 or fewer satellites are seen/used in the GPS fix. (i.e. with 3 satellites or less, an altitude value cannot be calculated)
Bit 5 – Historic
This bit is set when the message has been logged by the LMU.
Bit 6 – Invalid Time
This bit is set only after a power-up or reset before a valid time-sync has been obtained.

Carrier (2 bytes)
The identifier of the Carrier/Operator the wireless modem is currently using. For GSM, HSPA, and LTE networks, this is the MNC (mobile network code). For CDMA networks this is the SID (system identification number).

RSSI (2 bytes)
The received signal strength of the wireless modem in dBm. This value is signed in a 2’s complement format.

Comm State (1 byte)
The current state of the wireless modem bit mapped as follows
Bit 0 – Available
Bit 1 – Network Service
Bit 2 – Data Service
Bit 3 – Connected (PPP Session Up)
Bit 4 – Voice Call is Active
Bit 5 – Roaming
Bits 6-7 – Network Technology
00 = 2G Network (CDMA or GSM)
01 = 3G Network (UMTS)
10 = 4G Network (LTE)
11 = Reserved

HDOP (1 byte)
The GPS Horizontal Dilution of Precision - it is a unit-less value reported with a 0.1 lsb.

**Inputs (1 byte)
The current state of the inputs, bit mapped as follows:
Bit 0 – Ignition
Bit 1 – Input 1
Bit 2 – Input 2
Bit 3 – Input 3
Bit 4 – Input 4
Bit 5 – Input 5
Bit 6 – Input 6
Bit 7 – Input 7**

Unit Status (1 byte)
Status of key modules within the unit:
Bit 0 – LMU32: HTTP OTA Update Status (0=OK, 1=Error), LMU8: Unused
Bit 1 – GPS Antenna Status (0=OK, 1=Error)
Bit 2 – GPS Receiver Self-Test (0=OK, 1=Error) (LMU32 only)
Bit 3 – GPS Receiver Tracking (0=Yes, 1=No)
Bit 4 – Reserved, Currently Unused
Bit 5 – Reserved, Currently Unused
Bit 6 – Reserved, Currently Unused
Bit 7 – Unused

Event Index (1 byte)
The index number of the event that generated the report; values should range from 0-74. 255 represents a Real Time PEG Action request.

Event Code (1 byte)
The event code assigned to the report as specified by the event’s Action Parameter

Accums (1 byte)
The number of 4-byte values in the AccumList and the Accumulator Reporting Format Type (upper 2 bits). Refer to Appendix G, ‘Accumulator Reporting Formats’ for details.

Append (1 byte)
This bit-mapped byte is used to indicate the presence, when corresponding bit is set, of specific data types appended to the end of the Event Report following the list of accumulators. Each data type starts with a single length byte followed by the data. If multiple data types are present, they shall appear in order of the bits set in the ‘Append’ byte, starting with bit 0.
Bit 0 – Cell Info (see ‘Appended Data’ section below).
Bit 1 thru 7 – reserved, set to zero (0).

AccumList (4 bytes x ‘n’)
A list of ‘n’ 4-byte fields where ‘n’ is defined in the Accums field. The format for this list is dependent upon the Accumulator Reporting Format Type also defined in the Accums field. Refer to Appendix G, ‘Accumulator Reporting Formats’ for details.

**Comment by tananaev** [comment]
I see it now. I guess it was not there before because I checked and couldn't find it on their wiki.

**Comment by tananaev** [comment]
I have added support for ignition.
