### ISSUE TITLE
Unable to uncheck "Disabled" checkbox

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2755]
I am using Traccar version 3.9.

I created user and disabled it using his account details.

Now I tried to enable account by unchecking the "Disabled" checkbox and it is not working.

![screenshot from 2017-01-04 16 20 47](https://cloud.githubusercontent.com/assets/1178055/21640176/1c5d2566-d29a-11e6-8f8d-00f46ab72d30.png)

**Comment by tananaev** [comment]
The issue is already fixed in https://github.com/tananaev/traccar-web/issues/356.

**Comment by kirantpatil** [comment]
Thanks.

**Comment by kirantpatil** [comment]
Same issue holds good for "Admin" and "Readonly" checkboxes

**Comment by tananaev** [comment]
It applies for all checkboxes. Please see the linked issue.
