### ISSUE TITLE
Can not add Devices nor groups to users anymore..

### ISSUE THREAD

**Issue by marsu211** [tananaev/traccar#2757]
I made some changes and started with a freshly installed MySQL DB.

I have setup 10 trackers and asked my users to register again.
Had them promoted as admins. I wanted to add devices and groups, but does not work.
I rebooted the server (physicall reboot) and cleaned my brother's cache.

I'm stuck...

Will it make sense to uninstall traccar and re-install back?
Thx
Patrick

**Comment by tananaev** [comment]
You should find out what the problem is. Check network call errors and logs.

**Comment by marsu211** [comment]
So,
I already found out that Firefox is a NO GO for Traccar administration. Chrome works much better

**Comment by tananaev** [comment]
It might be because of the #2721.

**Comment by marsu211** [comment]
Well done....thx
I stick on Chrome, that works ;o)

**Comment by marsu211** [comment]
On the other Hands, it is better to Chrome for managing, or using FF as you explained. But in Live FF is much more reactiv than Chrome

**Comment by tananaev** [comment]
I use Chrome, so it's likely that Chrome would have less issues, because it's tested much more than FireFox.

**Comment by marsu211** [comment]
This case can now be closed. Answers in #2721 & as above
