### ISSUE TITLE
GPS that receive commands

### ISSUE THREAD

**Issue by tyepez** [tananaev/traccar#2761]
Please help me,

Send Commands from Traccar.
Is it possible to send commands to device using Traccar web page Command function?

Anyone knows what devices supports receive commands by internet (for cut oil, engine lock, remote open/close).

Please help me with a list of GPS GPRS tracker, that support this function.

**Comment by tananaev** [comment]
You can easily search for supported commands in various protocols:

https://github.com/tananaev/traccar/search?q=setSupportedCommands
