### ISSUE TITLE
handle chunked http requests

### ISSUE THREAD

**Issue by gutcZHAW** [tananaev/traccar#2765]
Hello everybody :)

I've implemented a new protocol where the data is attached as a xml file. 
The decoding works fine if the xml file is smaller or even to 1024 and the file can be sent within one request. Unfortunately sometimes the xml file is bigger than 1024 and has to be sent within two (or more) request using the 100-Continue state. Is there a protocol where this is already implemented or does someone have an example code or a hint how to handle this issue?

thanks a lot :D

**Comment by tananaev** [comment]
You have to use `HttpChunkAggregator`. It's really easy. Check `PiligrimProtocol` for example.

**Comment by gutcZHAW** [comment]
Thank you for your hint! It works :+1:
