### ISSUE TITLE
Problems starting server after copying target .JAR

### ISSUE THREAD

**Issue by edtronic** [tananaev/traccar#2767]
I did a successful build

after that, I stoped the server and copied the following files
```
sudo cp ./setup/traccar.xml /opt/traccar/traccar.xml
sudo cp -R ./setup/default.xml /opt/traccar/conf/default.xml
sudo cp -R ./schema/ /opt/traccar/schema/
sudo cp -R ./templates/ /opt/traccar/templates/
sudo cp -R ./traccar-web/ /opt/traccar/web/
sudo cp -R ./target/lib/ /opt/traccar/lib/
sudo cp ./target/tracker-server.jar /opt/traccar/tracker-server.jar
```
Then I did a ./traccar start in /opt/traccar/bin and got:
```
Starting traccar...
Waiting for traccar......
WARNING: traccar may have failed to start.
```
Its important to say that before I copied the files, the page server was up and runing. Its only I copied the compiled files that failed.

Thanks in advance for the time and help

Eduado.

**Comment by edtronic** [comment]
root@ip-172-31-53-237:/opt/traccar/logs# cat wrapper.log.20170109
STATUS | wrapper  | 2017/01/09 15:40:28 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2017/01/09 15:40:28 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2017/01/09 15:40:28 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2017/01/09 15:40:28 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2017/01/09 15:40:28 |
STATUS | wrapper  | 2017/01/09 15:40:28 | Launching a JVM...
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperManager: Initializing...
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp:
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error: java.lang.NoClassDefFoundError: com/ning/http/client/AsyncHttpClient
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at org.traccar.Context.<clinit>(Context.java:155)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error: Caused by: java.lang.ClassNotFoundException: com.ning.http.client.AsyncHttpClient
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
INFO   | jvm 1    | 2017/01/09 15:40:28 | WrapperSimpleApp Error:       ... 8 more
STATUS | wrapper  | 2017/01/09 15:40:30 | <-- Wrapper Stopped

**Comment by tananaev** [comment]
It looks like some library is missing.

**Comment by edtronic** [comment]
¿Any idea on a quick fix? you help me out yesterday with a quick fix. you took away a test.poits

**Comment by edtronic** [comment]
¿Any idea or hint on how to fix it? . . . yesterday you made a quick fix on test, that helped me compile it

**Comment by tananaev** [comment]
You can try to use the JAR file with dependencies. That's the easiest option.

**Comment by edtronic** [comment]
Just copy and paste it?

**Comment by tananaev** [comment]
Yes, replace `tracker-server.jar` file with it.

**Comment by edtronic** [comment]
No luck, I got this:

STATUS | wrapper  | 2017/01/09 20:40:05 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2017/01/09 20:40:05 | Java Service Wrapper Community Edition 64-bit 3.5.28
STATUS | wrapper  | 2017/01/09 20:40:05 |   Copyright (C) 1999-2016 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2017/01/09 20:40:05 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2017/01/09 20:40:05 |
STATUS | wrapper  | 2017/01/09 20:40:05 | Launching a JVM...
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager: Initializing...
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperSimpleApp Error: Unable to locate the class org.traccar.Main : java.lang.ClassNotFoundException: org.traccar.Main
INFO   | jvm 1    | 2017/01/09 20:40:05 |
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperSimpleApp Usage:
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error: Error in WrapperListener.start callback.  java.lang.IllegalArgumentException: can't parse argument number: app_class{/app_method}
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error: java.lang.IllegalArgumentException: can't parse argument number: app_class{/app_method}
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at java.text.MessageFormat.makeFormat(MessageFormat.java:1429)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at java.text.MessageFormat.<init>(MessageFormat.java:362)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at java.text.MessageFormat.format(MessageFormat.java:840)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at org.tanukisoftware.wrapper.WrapperResources.getString(WrapperResources.java:194)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at org.tanukisoftware.wrapper.WrapperSimpleApp.showUsage(WrapperSimpleApp.java:597)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at org.tanukisoftware.wrapper.WrapperSimpleApp.start(WrapperSimpleApp.java:441)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at org.tanukisoftware.wrapper.WrapperManager$10.run(WrapperManager.java:4241)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error: Caused by: java.lang.NumberFormatException: For input string: "app_class{/app_method}"
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at java.lang.Integer.parseInt(Integer.java:580)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at java.lang.Integer.parseInt(Integer.java:615)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         at java.text.MessageFormat.makeFormat(MessageFormat.java:1427)
INFO   | jvm 1    | 2017/01/09 20:40:05 | WrapperManager Error:         ... 7 more
STATUS | wrapper  | 2017/01/09 20:40:06 | <-- Wrapper Stopped

**Comment by edtronic** [comment]
was i supposed to change the name from  tracker-server-jar-with-dependencies.jar to tracker-server.jar?

**Comment by tananaev** [comment]
Yes, I think it's implied by word "replace".

**Comment by edtronic** [comment]
Dah!.... boom, now it works.

Any ideas why the "original" tracker-server.jar did not worked?

**Comment by tananaev** [comment]
You were missing some libraries, but I'm not sure why.

**Comment by edtronic** [comment]
No problem, I have officially been pimped. I´ll let you know if i figure it out.

Closing in 3...2...1... PUFF!
