### ISSUE TITLE
error - invalid version format: ￀DC3 NUL 3?.....Illegal argument...

### ISSUE THREAD

**Issue by marsu211** [tananaev/traccar#2768]
Hello Anton,

I just received my new gadget for evaluation which runs under Android.
It is a Phone/Radio with SIM card model F25.
I have installed the latest Traccar client and manager from the playstore, as I did with my Motorola and for my iPhone.

Here is the issue:
2017-01-09 22:10:12  WARN: [AABFAC72] error - invalid version format: ￀

Attached a screen shot from the Log file.
![screen shot 2017-01-09 at 22 26 09](https://cloud.githubusercontent.com/assets/4009034/21784174/b9eb9d84-d6ba-11e6-80e8-6264f9375387.png)

**Comment by tananaev** [comment]
Are you sure you didn't enable encryption in the Traccar Client?

**Comment by marsu211** [comment]
Absolutely sure and Android is version 5.1

**Comment by tananaev** [comment]
Please attach a screenshot of the Traccar Client main screen.

**Comment by marsu211** [comment]
![img_3590](https://cloud.githubusercontent.com/assets/4009034/21797478/933b83fc-d70f-11e6-8880-d2879cf651c8.JPG)
![img_3591](https://cloud.githubusercontent.com/assets/4009034/21797480/9341b452-d70f-11e6-8cfa-c44b049fbde6.JPG)
![img_3592](https://cloud.githubusercontent.com/assets/4009034/21797479/93417b68-d70f-11e6-9e40-cb7490a666b2.JPG)

![image](https://cloud.githubusercontent.com/assets/4009034/21797492/a9ea1384-d70f-11e6-9023-2b26ac2778db.jpg)

Brgds

**Comment by tananaev** [comment]
Looks fine to me. It probably means that the HEX example that you provided wasn't from Traccar Client. What do you see on the status screen in the Client app?

**Comment by marsu211** [comment]
![img_3593](https://cloud.githubusercontent.com/assets/4009034/21825544/79215f08-d784-11e6-980f-cb779ef80a65.JPG)

**Comment by marsu211** [comment]
That was the only tracker runing at time of tests.
And it inly appears when I start the cient on this device.

**Comment by tananaev** [comment]
If the port is open to internet, it can receive any message from anybody, not only your own devices.

On the status screen, you should see "location update" messages. If you don't, it means that device doesn't have location info, so it won't send anything.

**Comment by marsu211** [comment]
Well,
the problem is that it only happens the first time I run the client on the device after I shut down and back on again.
Last was :

16030100d2010000ce030306198caa74652db257723a793e8778b39699af8d9d782f2a9bd357ae34bad3d800002a0a0acca9cca8cc14cc13c02bc02f009ec02cc030c009c0130033c00ac0140039009c009d002f0035000a0100007b8a8a0000ff0100010000000014001200000f6d617273752e64796e646e732e74760017000000230000000d0012001006010603050105030401040302010203000500050100000000001200000010000e000c02683208687474702f312e3175500000000b00020100000a000a00081a1a001d00170018aaaa000100

you have the URL in clear after decoding in the HEX decoder.And this is correct.
Then I don't get anything until I put in standby mode and back on.

I will check with a similar device if it also has the same issue.
Thx for the support
Patrick

**Comment by tananaev** [comment]
Traccar Client sends a regular HTTP request, so it should be completely human readable text after decoding HEX string. Your message looks more like encrypted data. Did you turn encryption at some point by any chance? I would recommend to re-install the app, and try without touching encryption switch.

**Comment by marsu211** [comment]
GET / HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; F25 Build/LMY47D)
Host: marsu.dyndns.tv:5055
Accept-Encoding: gzip
X-WISP: spgw01pogc
(already decoded)

Is when I change from GPS to Network provider in "Location Provider" section

As said, nothing is encrypted in anyway. I check and double checked.

**Comment by marsu211** [comment]
I guess I found something. Can it be that the GPS function from the device does not work?

**Comment by tananaev** [comment]
Well, if you don't have location enabled, obviously you won't get anything.

Your last example is also NOT from Traccar Client.

**Comment by marsu211** [comment]
Sorry, but defintely must be...
"ser-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1; F25 Build/LMY47D" corresponds to the radio, and only Traccar client is installed with the connection information to the server with port number...

This was sent once:

474554202f3f69643d3630363138372674696d657374616d703d31343834303837313335266c61743d34362e35303738323837266c6f6e3d362e36333336342673706565643d302e302662656172696e673d302e3026616c7469747564653d302e3026626174743d35342e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f322e312e3020284c696e75783b20553b20416e64726f696420352e313b20463235204275696c642f4c4d59343744290d0a486f73743a206d617273752e64796e646e732e74763a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a

And that worked, the device appeared on the map, but only worked once.

I'll make some additional tests tomorrow and so on, and let you know what I find out.
Thx again

**Comment by tananaev** [comment]
Now that looks like data from the Client app.

> Sorry, but defintely must be...

If it's from your phone, it doesn't necessarily mean it's from the app.

**Comment by marsu211** [comment]
Dear Anton,
Just want to let you know that the issue has now been solved. We adjusted some GPS settings from within the device and the trackers are now sending correct data to the server.

Best regards
Patrick

**Comment by tananaev** [comment]
Great. Closing the issue.
