### ISSUE TITLE
Email notification template localization

### ISSUE THREAD

**Issue by weseli** [tananaev/traccar#2772]
Hi Anton

I have a question;
How can I get email notification in my language(Serbian)
I tried to modify template >online device

#set($subject = "$device.name: na mreži")    <----- online on serbian is > na mreži

<!DOCTYPE html>
<html>
<body>
Uređaj: $device.name<br>
Na mreži<br>
Vreme: $event.serverTime<br>
Link: <a href="$webUrl?eventId=$event.id">$webUrl?eventId=$event.id</a>
</body>
</html> 

result is when I get email

**UreÄ‘aj: Gosafe
Na mre\u009Ei
Vreme: Tue Jan 10 12:48:43 CET 2017**
Link: it is OK**

it should be 

****Uređaj: Gosafe
Na mreži
Vreme: Tue Jan 10 12:48:43 CET 2017**
Link: ok**

non ASCII characters shows as odd characters

**How can I modify template to get correct characters in Serbian when I get email ?**

thank you in advance

**Comment by tananaev** [comment]
The issue will be fixed as soon as we merge #2775.

**Comment by weseli** [comment]
Ok,thank you.Hope it will be soon
