### ISSUE TITLE
Unable to get Login page ...

### ISSUE THREAD

**Issue by alltechnostuffs11** [tananaev/traccar#2781]
I am Unable to get Login page while running Traccar on Netbeans.  Getting 404 page not found error.  
I have downloaded "traccar-master" and loaded it into Netbeans, as directed in the guide https://www.traccar.org/build-in-netbeans/ and when trying accessing it on browser at http://localhost:8082/ then getting 404 - Not found error.....
I followed the guide on https://www.traccar.org/build-in-netbeans/  Still stuck.

**Comment by tananaev** [comment]
Sound like you haven't checked out `traccar-web` repository.

**Comment by alltechnostuffs11** [comment]
Thank you very much for you kind reply.
Oh yeah, I got it now, but the problem now arriving is I am not getting Information from android Traccar Client, its telling, "Send failed" in the status window,  Actually I wanna know what exactly server address should I put there, I put 192.168.1.1, 192.168.1.1:8082, both failed

**Comment by tananaev** [comment]
Are both on the same network? It seems like you are using local IP address.

Also, make sure that you are using correct port for the Client. It should be 5055 by default.

**Comment by alltechnostuffs11** [comment]
I am running Traccar from Netbeans, and tracking my Cell Phone (By having Traccar Client android app on it).  What Server Address should I give now?
Thank you

**Comment by tananaev** [comment]
If you want to connect your local server, you should give the IP address of your local server.

**Comment by alltechnostuffs11** [comment]
Okay, here I am in a LAN of many PC's, Suppose the global IP of my LAN is 182.75.xxx.xx , then I tried using this IP in Traccar Client, but the same error came, i.e. : "Send failed"

**Comment by tananaev** [comment]
Please follow this guide:

https://www.traccar.org/troubleshooting/

**Comment by alltechnostuffs11** [comment]
Thank you very much got it !
