### ISSUE TITLE
Add new changes to traccar production

### ISSUE THREAD

**Issue by tyepez** [tananaev/traccar#2791]
I have installed traccar 3.9, but I see new updates at https://github.com/tananaev/traccar/commits/master/test/org/traccar/protocol/Tk103ProtocolDecoderTest.java

How can I put this updates in my server?

**Comment by tananaev** [comment]
You should either wait for the next release or compile it from the source code.

**Comment by tyepez** [comment]
when is the next release?

**Comment by tananaev** [comment]
There is no date yet. Probably within a month or so.
