### ISSUE TITLE
Telic protocol improvement

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#2793]

**Comment by tananaev** [comment]
Can I have some message samples?

**Comment by argokask** [comment]
Yes,

I would like to add two more event ID codes to that table which is not represented in the table i posted before.

98 distance  (configurable distance travelled since last message)
99 timer (configurable time period elapsed since last message)

Example message:

HEX message:

6500000033313230**3939xxxxxxxxxxxx**2c3137313131363036303230302c302c3137313131363036303230302c**xxxxxxxxxxxx**2c**xxxxxxxxxxxx**2c332c33372c3130362c31312c2c2c34332c353933313530382c2c303031302c30302c3134312c302c302c3031303800

Output message:

e3120**99xxxxxx**,171116060200,0,171116060200,**xxxxxx**,**xxxxxx**,3,37,106,11,,,43,5931508,,0010,00,141,0,0,0108

In that example 3939 (hex) means event ID 99 what according to table means that configurable time has elapsed since last message. The xxxx marks is not related with that message ID, i just replaced IMEI and coordinates with that.

**Comment by tananaev** [comment]
I don't see 98 and 99 in your table.

**Comment by argokask** [comment]
Yes, but i would like to if you can add these two event ID's also to traccar. I have checked them and these are also common to all telic tracking devices.

Descriptions:

98 distance (configurable distance travelled since last message)
99 timer (configurable time period elapsed since last message)

**Comment by tananaev** [comment]
I would need documentation for those.

**Comment by argokask** [comment]
Ok, i do not have documentation for those event codes but i can reference to one older issue in this forum [https://github.com/tananaev/traccar/issues/691](url) which also describes those event ID's.

**Comment by tananaev** [comment]
So, which ones do you want me to add? We can only add alarms:

[Position.java#L71](https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/Position.java#L71)

**Comment by argokask** [comment]
Hi,

Atm in Traccar server under "State" section i see attribute "Type" with (for example) "Value" 99

My wish would be that instead of number 99 i see word "timer" because for most users that value 99 do not give any strait forward information. So to do that it is neccessary to make relations between Type values and descriptions in table (+ 98 and 99 types i sent you later).

Best regards,
Argo

**Comment by tananaev** [comment]
Why would user need to know if it's a timer or distance report?

**Comment by ssmipp** [comment]
Pls add emergency, low battery, motion and stationary alarms, that is event ids 2, 22, 25 and 26. And consider also adding Charger connected/disconnected events, 13 and 14. This is valid for Telic Picotrack.

**Comment by tananaev** [comment]
Well, I need some documentation that explains the meaning of each id.

**Comment by argokask** [comment]
[event ID.pdf](https://github.com/tananaev/traccar/files/718722/event.ID.pdf)

If needed i can give more detailed explanations for those event ID's.

**Comment by tananaev** [comment]
In the message samples that I have, I get following values: 43, 78, 97. None of them are in your document. I would need proper full documentation to implement anything.
