### ISSUE TITLE
pin on map.

### ISSUE THREAD

**Issue by cesarruben** [tananaev/traccar#2803]
Hello how can you filter the pin to display on the map only the devices online.

**Comment by tananaev** [comment]
It's not possible at the moment.

**Comment by claymarvelous** [comment]
hello, can we make a custom point bulding or some address on the map..?
i'm a newbie, please advise..

**Comment by tananaev** [comment]
@chivasregal001, your question has nothing to do with the original suggestion. Please comment on an appropriate thread or create a new one.

**Comment by cesarruben** [comment]
thank you.
