### ISSUE TITLE
device offline status

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2825]
by using traccar client android app when i start a service event is generated for device online but as soon as i stop a service device offline event is not generated. what i want is if user stop a service immediate device offline event should be generated so it will be a real time.

**Comment by tananaev** [comment]
It's not possible because of the nature of the protocol used by Traccar Client.

**Comment by d33pak-s1ngh** [comment]
so is there any other way through which can know that client has disable tracking.

**Comment by tananaev** [comment]
No. That would require some significant changes to the protocol.
