### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2826]
what we can do is to display various information in graphical format using charts.
like distance coverd by devices for period of time can be shown in chart.
![chart](https://cloud.githubusercontent.com/assets/23626544/22239283/c751eb04-e23b-11e6-927e-8154e8f01805.png)

like wise we can display various events genrated by device base on chart which will make it more easy to understand.
also report can be base on charts.
what you guys think.

**Comment by tananaev** [comment]
There are already charts in Traccar. Not like your example though.

**Comment by d33pak-s1ngh** [comment]
i haven't seen any yet where i can find.

**Comment by tananaev** [comment]
It's on GitHub and will be available with the next official release.

**Comment by d33pak-s1ngh** [comment]
ok thanx for this information waiting for it.which information will be available in chart format in next release?

**Comment by tananaev** [comment]
Initially there will be speed and distance information against time. In future it should be easy to add more options.
