### ISSUE TITLE
GT06 Bug on processing 7979 start bit packet, ignition state changes

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2832]
Hello,

I just came across a small problem, in traccar 3.9 when GT06 protocol,

Physical Devices Ignition = True
Traccar Shows and records it as = True

However the moment packet starting with start bit `7979` sub type `94` is received the Ignition status gets changed to = Off / false

-Then it gets into a infinite loop of ignition status change event.. (This happens because, everytime device sends igntion on via all other packets, and then in between when server receives the 7979 start bit packet it changes ignition state to off, then new other packets make it on)

The above is in version 3.9,   So I tested the same scenario in version 3.7 and here this problem did not occur in 3.7.

**Comment by tananaev** [comment]
As far as I can tell, message type `94` doesn't have any ignition info, so you should probably use `processing.copyAttributes` config parameter to copy the ignition value over from previous record.

**Comment by jaimzj** [comment]
You are right it message type 94 doesn't have ignition info, I am already using the processing.copyAttributes . with copyAttributes also this issue continues.

What I shared as a possible bug, above is not related to the attributes being copied from previous record.

Basically every time type 94 packet is received some change in the code probably is triggering a ingition off state in Traccar. (So if the packet 94 interval is 5 seconds) when the ignition value in actual is on (Every 5 second when the 94 packet comes in, there is an entry made as ignition off) then when the normal or any other packet with ignition on comes in which is the actual value it turns back to on. thus leading to a huge list of events on/off/on/off/on/off ........ (while the actual status is On only).

**Comment by tananaev** [comment]
Message type `94` doesn't have any ignition value, so if you have `copyAttributes` configured properly, it won't cause notifications. You have to track down exact message that triggers it.

**Comment by jaimzj** [comment]
Sure, I am going to enable copyAttributes test it now and share the results with you.
As for exact message, from the earlier tests I did I had noticed any message with start bit 7979 this gets triggered.

But allow me few minutes I Will update the copyAttributes test result.

**Comment by jaimzj** [comment]
@tananaev I enabled copyAttributes, 

And with `copyAttributes` enabled for ignition, on receiving packet 94 or start bit 7979, while the ignition status was on, it did not update to off state anymore.

**Comment by tananaev** [comment]
So, everything is working correctly. I thought you already tried it and it didn't work.

**Comment by jaimzj** [comment]
No it was my mistake, I wrote I had copyAttributes enabled, but it was not enabled.

However my concern is, if its not enabled then the off state getting triggered while ignition is on, could be a issue right? I might be wrong as well.

**Comment by tananaev** [comment]
Good point. We should probably ignore messages if ignition value is not present. Currently no ignition is treated as ignition "off".

**Comment by jaimzj** [comment]
Should you want me to test with any other message type as well which does not have ignition and test it? if this happens.

**Comment by Abyss777** [comment]
@tananaev should we make "ignore messages if ignition value is not present" as default behavior or make it configurable?

**Comment by tananaev** [comment]
I think we should make it the default behavior. Distance works the same, right?

**Comment by Abyss777** [comment]
Distance is always must be there, its handler is not switchable.

**Comment by tananaev** [comment]
Yes, bad example. Anyway, I think we should only send event when both positions have ignition values.

**Comment by Abyss777** [comment]
In some protocols we will never get such event, because ignition value will be sent only then real switching happen on device.

**Comment by tananaev** [comment]
Yes, but then `copyAttributes` would help.

**Comment by tananaev** [comment]
Fixed by #2833.
