### ISSUE TITLE
Protocol decoder delimiter doubt

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#2834]
Hello anton, I have a doubt about framedecoder and a new protocol implementation:
if the data frame is:
```
;9357330052597069,POS=1,2,3,11,20/1/2017,21:25:04,20/1/2017,21:25:04,19.486688,-99.143458,49,115.1,0.9,679.4,72;
```
Delimited by ";" and I choose as frame decoder this:
```
pipeline.addLast("frameDecoder", new CharacterDelimiterFrameDecoder(2048, "\r\n", "\n", ";"));
```
Should I get troubles trying to decode the string? the string starts with ; and ends with it too, so, should I choose another delimiter instead of ";" ?
I've been debuggin, testing the new protocol and I have no errors, no sql exceptions, no position is null message in the output, I printed all parts of the dataframe separetly and no null values at all, but all I get from the logger is the HEX representation of the data frame but it's not storing data, is not displaying unknown device, I have several weeks on this and I'm not sure about why my protocol is not trying to decode the message.
I have checked debug configuration, ports opened, in the tests no failures at all, so, I also enabled gps103 protocol and sent a frame to port 5001 and I received a unknown device message which means is decoding messages, so, I'm totally stuck.

**Comment by tananaev** [comment]
Can you provide original HEX?

**Comment by hackerunet** [comment]
3b313231323132313231322c504f533d312c322c332c31312c32352f312f323031372c31333a32353a30342c32352f312f323031372c31333a32353a30342c31392e3438363638382c2d39392e3134333435382c34392c3131352e312c302e392c3637392e342c37323b

**Comment by tananaev** [comment]
Looks like you have to use `;` as a delimiter. You can just ignore the empty message at the beginning.

**Comment by hackerunet** [comment]
this is the protocol delimiter configuration file:
```
public void initTrackerServers(List<TrackerServer> serverList) {
        serverList.add(new TrackerServer(new ServerBootstrap(), getName()) {
            @Override
            protected void addSpecificHandlers(ChannelPipeline pipeline) {
                pipeline.addLast("frameDecoder", new CharacterDelimiterFrameDecoder(1024, ";"));
                pipeline.addLast("stringEncoder", new StringEncoder());
                pipeline.addLast("stringDecoder", new StringDecoder());
                pipeline.addLast("objectEncoder", new IwatcherProtocolEncoder());
                pipeline.addLast("objectDecoder", new IwatcherProtocolDecoder(IwatcherProtocol.this));
            }
        });
        serverList.add(new TrackerServer(new ConnectionlessBootstrap(), getName()) {
            @Override
            protected void addSpecificHandlers(ChannelPipeline pipeline) {
                pipeline.addLast("stringEncoder", new StringEncoder());
                pipeline.addLast("stringDecoder", new StringDecoder());
                pipeline.addLast("objectEncoder", new IwatcherProtocolEncoder());
                pipeline.addLast("objectDecoder", new IwatcherProtocolDecoder(IwatcherProtocol.this));
            }
        });
    }
```

**Comment by tananaev** [comment]
Looks fine to me. Not sure why you need UDP though.

**Comment by hackerunet** [comment]
This is TCP only, how can I remove UDP support??

**Comment by tananaev** [comment]
I don't know. Is your device UDP or TCP?

**Comment by hackerunet** [comment]
My device is TCP based only.

**Comment by tananaev** [comment]
Then, as I said, you don't need UDP part (`ConnectionlessBootstrap`).

**Comment by hackerunet** [comment]
removed UDP part, well, turns out that Decoder remove the ; from the pattern so I had to remove the semicolon from it and everything works nicely... Thanks a lot anton for clearifying everything, you are amazing as a teacher.
thanks
