### ISSUE TITLE
Potential problem with notifications

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#2836]
See this thread:

https://www.traccar.org/forums/topic/receiving-email-notifications-for-all-devices/

**Comment by Abyss777** [comment]
It uses function `getDeviceUsers` https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/NotificationManager.java#L56

same as in `ConnectionManager`
https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/ConnectionManager.java#L128
https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/ConnectionManager.java#L140

I do not think it works incorrectly.

**Comment by tananaev** [comment]
OK, let's close it for now. We can reopen it later.

**Comment by Abyss777** [comment]
Oh, but there is a problem. Not connected to notifications but...

I have unlinked device from admin, refreshed the page, run test, and got device updates in websocked. Looks like some cashed permissions was not updated correctly.
Will investigate it tomorrow.
