### ISSUE TITLE
trip calculation

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2842]
i want to understand how a trip is calculated.
also in a route report we are displaying all the positions user have visited with a direction line.
i think there should be same feature for trip also which will display multiple trips done by devices in map with number like trip 1 trip 2.

![traccar map](https://cloud.githubusercontent.com/assets/23626544/22370307/c9286598-e4b6-11e6-8a9a-f2c83b1c77f3.png)

also in above image a direction  of arrow marker is always in users moving position i want to achieve same functionality with google map. i have a following map in which marker will animate on the following polyline path i am able to move marker on the path but the direction of marker is not changing as device direction. do you have any idea how i can do this in google map.
![map2](https://cloud.githubusercontent.com/assets/23626544/22370422/5d8f7906-e4b7-11e6-9354-d010426759c8.png)

**Comment by Abyss777** [comment]
You can select trip in report panel and its route will be shown on map.

**Comment by d33pak-s1ngh** [comment]
yeah i got it awesome feature.
