### ISSUE TITLE
Mysql connection keep on increasing even after adding maxpool size

### ISSUE THREAD

**Issue by AnshulJain1985** [tananaev/traccar#2844]
Hi

I have install the latest version 3.9 on one of my Ubuntu servers. There are no errors in the logs but my connections are kept increasing. I am using below configuration and even set the maxPoolSize to 5.
After every few mins a new connection is added. I have restarted mysql, traccar server but nothing helped. Also I checked the timeout parameters of mysql and everything is set to default.
In 1 hour it has created around 50 connections from traccar.
```xml
    <entry key="config.default">./conf/default.xml</entry>
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://localhost:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES&amp;useSSL=false</entry>
    <entry key='database.user'>user</entry>
    <entry key='database.password'>pwd</entry>
    <entry key='database.maxPoolSize'>5</entry>
```

Could you please help me out here.
Thanks

**Comment by tananaev** [comment]
Traccar uses Hikari library for connection. Possible there is some issue with it.

**Comment by AnshulJain1985** [comment]
ok thanks. I will check Hikari library and will update you if I found anything. 
Thanks for your response. I will close this once I have an answer for this as it may help someone else in future.

**Comment by AnshulJain1985** [comment]
Can you provide me some details, how i can enable logs for hikari. I got the below response from Hikari issue.
>>>>>>>>>>>>>
Please enable debug logging for the package com.zaxxer.hikari, you should see a log entry for every created connection.

**Comment by tananaev** [comment]
I don't know. They should have some documentation for it.

**Comment by drecchia** [comment]
I have been using hikari for years without any issues, which db are you using, and which version?
Can you run "show processlist" on mysql console when the connection leak happens and report back to me the content ?

Thanks

**Comment by AnshulJain1985** [comment]
I am using mysql  version 5.7.17-0ubuntu0.16.04.1
Please find below details in 30 minutes interval. It has created almost 25 connections.
Let me know if you need any other details.

mysql> show processlist;
+-------+-----------------+-----------------+---------+---------+--------+------------------------+------------------+
| Id    | User            | Host            | db      | Command | Time   | State                  | Info             |
+-------+-----------------+-----------------+---------+---------+--------+------------------------+------------------+
|     1 | event_scheduler | localhost       | NULL    | Daemon  | 261625 | Waiting on empty queue | NULL             |
| 41569 | douser          | localhost:38538 | traccar | Sleep   |     12 |                        | NULL             |
| 41604 | root            | localhost:38612 | NULL    | Sleep   |     34 |                        | NULL             |
| 41605 | root            | localhost:38614 | NULL    | Sleep   |     34 |                        | NULL             |
| 41611 | root            | localhost:38628 | NULL    | Sleep   |      9 |                        | NULL             |
| 41612 | root            | localhost:38630 | NULL    | Sleep   |      6 |                        | NULL             |
| 41616 | douser          | localhost:38638 | traccar | Sleep   |    256 |                        | NULL             |
| 41617 | douser          | localhost:38640 | traccar | Sleep   |    256 |                        | NULL             |
| 41618 | douser          | localhost       | NULL    | Query   |      0 | starting               | show processlist |
| 41619 | douser          | localhost:38644 | traccar | Sleep   |    160 |                        | NULL             |
| 41620 | douser          | localhost:38648 | traccar | Sleep   |    137 |                        | NULL             |
| 41621 | douser          | localhost:38650 | traccar | Sleep   |    137 |                        | NULL             |
| 41622 | douser          | localhost:38658 | traccar | Sleep   |     74 |                        | NULL             |
| 41623 | douser          | localhost:38666 | traccar | Sleep   |     13 |                        | NULL             |
+-------+-----------------+-----------------+---------+---------+--------+------------------------+------------------+
14 rows in set (0.00 sec)

mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2017-01-31 06:36:28 |
+---------------------+
1 row in set (0.00 sec)

mysql> show processlist;
+-------+-----------------+-----------------+---------+---------+--------+------------------------+------------------+
| Id    | User            | Host            | db      | Command | Time   | State                  | Info             |
+-------+-----------------+-----------------+---------+---------+--------+------------------------+------------------+
|     1 | event_scheduler | localhost       | NULL    | Daemon  | 263274 | Waiting on empty queue | NULL             |
| 41604 | root            | localhost:38612 | NULL    | Sleep   |      5 |                        | NULL             |
| 41605 | root            | localhost:38614 | NULL    | Sleep   |      4 |                        | NULL             |
| 41611 | root            | localhost:38628 | NULL    | Sleep   |      8 |                        | NULL             |
| 41612 | root            | localhost:38630 | NULL    | Sleep   |      6 |                        | NULL             |
| 41618 | douser          | localhost       | NULL    | Query   |      0 | starting               | show processlist |
| 41619 | douser          | localhost:38644 | traccar | Sleep   |   1809 |                        | NULL             |
| 41620 | douser          | localhost:38648 | traccar | Sleep   |     23 |                        | NULL             |
| 41622 | douser          | localhost:38658 | traccar | Sleep   |   1723 |                        | NULL             |
| 41623 | douser          | localhost:38666 | traccar | Sleep   |   1662 |                        | NULL             |
| 41624 | douser          | localhost:38674 | traccar | Sleep   |   1576 |                        | NULL             |
| 41625 | douser          | localhost:38684 | traccar | Sleep   |   1484 |                        | NULL             |
| 41626 | douser          | localhost:38694 | traccar | Sleep   |   1388 |                        | NULL             |
| 41627 | douser          | localhost:38702 | traccar | Sleep   |   1321 |                        | NULL             |
| 41628 | douser          | localhost:38710 | traccar | Sleep   |   1231 |                        | NULL             |
| 41629 | douser          | localhost:38716 | traccar | Sleep   |   1154 |                        | NULL             |
| 41630 | douser          | localhost:38726 | traccar | Sleep   |   1058 |                        | NULL             |
| 41631 | douser          | localhost:38736 | traccar | Sleep   |    965 |                        | NULL             |
| 41632 | douser          | localhost:38746 | traccar | Sleep   |    866 |                        | NULL             |
| 41633 | douser          | localhost:38754 | traccar | Sleep   |    778 |                        | NULL             |
| 41634 | douser          | localhost:38762 | traccar | Sleep   |    691 |                        | NULL             |
| 41635 | douser          | localhost:38772 | traccar | Sleep   |    597 |                        | NULL             |
| 41636 | douser          | localhost:38782 | traccar | Sleep   |    497 |                        | NULL             |
| 41637 | douser          | localhost:38792 | traccar | Sleep   |    398 |                        | NULL             |
| 41638 | douser          | localhost:38802 | traccar | Sleep   |    306 |                        | NULL             |
| 41639 | douser          | localhost:38812 | traccar | Sleep   |    213 |                        | NULL             |
| 41640 | douser          | localhost:38816 | traccar | Sleep   |    196 |                        | NULL             |
| 41641 | douser          | localhost:38822 | traccar | Sleep   |    136 |                        | NULL             |
| 41642 | douser          | localhost:38826 | traccar | Sleep   |    121 |                        | NULL             |
| 41643 | douser          | localhost:38830 | traccar | Sleep   |    106 |                        | NULL             |
| 41644 | douser          | localhost:38838 | traccar | Sleep   |     29 |                        | NULL             |
| 41645 | douser          | localhost:38842 | traccar | Sleep   |     16 |                        | NULL             |
+-------+-----------------+-----------------+---------+---------+--------+------------------------+------------------+
32 rows in set (0.00 sec)

mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2017-01-31 07:04:00 |
+---------------------+

**Comment by AnshulJain1985** [comment]
I have recreated the server and issue is no longer there.
