### ISSUE TITLE
Traccar doesn't respond to received MXT protocol messages, causing disconnection.

### ISSUE THREAD

**Issue by gustavofcalmeida** [tananaev/traccar#2847]
As in other protocols, MXT protocol requires the server to give some feedback to the device from time to time. In the case of MXT protocol the feedback is an ACK message to be sent as soon as a position message is received. Without it, the device stops sending messages, the connection is broken and only reestablished a few minutes later.

Here is Traccar log for a device configured to send messages every 30 seconds:
```
2017-01-28 17:25:09  INFO: [B960ADB9] connected
2017-01-28 17:25:09 DEBUG: [B960ADB9: 5087 < ...
2017-01-28 17:25:09  INFO: [B960ADB9] id: ***
2017-01-28 17:26:22  INFO: [B960ADB9] disconnected

2017-01-28 17:26:23  INFO: [97587D17] connected
2017-01-28 17:26:23 DEBUG: [97587D17: 5087 < ...
2017-01-28 17:26:23  INFO: [97587D17] id: ***

2017-01-28 17:30:52  INFO: [FC01AD82] connected
2017-01-28 17:30:52 DEBUG: [FC01AD82: 5087 < ...
2017-01-28 17:30:52  INFO: [FC01AD82] id: ***
2017-01-28 17:33:52  INFO: [FC01AD82] disconnected

2017-01-28 17:33:53  INFO: [842D23D6] connected
2017-01-28 17:33:53 DEBUG: [842D23D6: 5087 < ...
2017-01-28 17:33:53  INFO: [842D23D6] id: ***

2017-01-28 17:38:15  INFO: [6F815030] connected
2017-01-28 17:38:17 DEBUG: [6F815030: 5087 < ...
2017-01-28 17:38:17  INFO: [6F815030] id: ***
2017-01-28 17:41:16  INFO: [6F815030] disconnected

2017-01-28 17:41:17  INFO: [3F276A4B] connected
2017-01-28 17:41:17 DEBUG: [3F276A4B: 5087 < ...
2017-01-28 17:41:17  INFO: [3F276A4B] id: ***
```

The ACK is like this:
0x01 + (device_descriptor + 0x02 + device_id + CRC_from_message + CRC_to_ACK) + 0x04

If there are any occurrence of bytes 0x01, 0x04, 0x10, 0x11 or 0x13 in the section between ( ), they must be changed to 0x1021, 0x1024, 0x1030, 0x1031 and 0x1033 respectively before transmission.

I checked this information monitoring the conversation between an MXT device and MXT PCtool (a software to configure the device). Here is an example:
![how to make ack](https://cloud.githubusercontent.com/assets/11458901/22399423/08327f70-e57b-11e6-97a6-63be93c2accc.png)

**Comment by tananaev** [comment]
I would need protocol documentation to check.

**Comment by gustavofcalmeida** [comment]
I don't have it. In fact it is super ultra high classified, for some reason I can't understand.
But I can send you all the packets I captured, de decoding made by PCtool and other intel I gathered.
I can even point the device to any IP and port you need so you can check yourself.

By the way, how did you implement the protocol decoder without the documentation?

**Comment by tananaev** [comment]
I think I had the documentation somewhere, but it would be hard to find and it probably also out of date.

Where did you get the response format if you don't have the documentation?

**Comment by gustavofcalmeida** [comment]
@tananaev here: https://groups.google.com/d/msg/traccar-pt-br/KJclP_SzTQI/k9DGWYStCAAJ

**Comment by drecchia** [comment]
DOCS:

2.2. Byte stuffing
The used byte stuffing method on this protocol is the insertion of one token byte (0x10), followed by the real byte added to 0x20. The bytes coded by this method are only: 0x01, 0x04, 0x10, 0x11 and 0x13.
Example
With Byte Stuffing process: 01 AC 33 CB D3 6A 00 20 10 2110 21 3D 8E 04 Without Byte Stuffing process: 01 AC 33 CB D3 6A 00 20 0101 3D 8E 04

3.1. ACK
This is the general acknowledgment command. Used for confirmation of position packets and other packets when necessary.
MT: 0x02; DATA FIELD: 2 bytes; UINT16 CRC_received;


CRC: The CRC16-CCITT calculation from DD until the last byte of DATA. CRC is calculated before the byte stuffing process.


Hope it helps

**Comment by gustavofcalmeida** [comment]
@drecchia

> MT: 0x02; DATA FIELD: 2 bytes; UINT16 CRC_received;

This doesn't seem complete. MT might be "message type".

> calculation from DD until

Where is DD? Might be "device descriptor".

**Comment by drecchia** [comment]
The full frame is SOF + DD + MT + DEVID + DATA + CRC + EOF

SOF: Start of Frame, 0x01, 1 byte. This byte starts every packet sent;

DD: Device descriptor, according to the following table: If no encrypt:
0xA0: MXT-100 (portable, no 2.4Ghz transceiver) 
0xA1: MXT-101 (portable, 2.4Ghz enabled)
0xA2: MXT-150 (automotive, no 2.4Ghz transceiver) 
0xA3: MXT-151 (automotive, 2.4Ghz enabled) 
0xA4: MXT-120
0xA5: iMXT 
0xA6: MXT-140 
0xA7: MXT-141 
0xA8: MXT-100N 
0xA9: MXT-101N 
0xAA: G-100 
0xAB: Reserved 
0xAC: MXT-142 
0xAD: MXT-130D 
0xAE: Reserved

MESSAGE TYPE: Message type, 1 byte, described more ahead in this document. 

DEVID: Device ID, 4 bytes;
For encrypted packets: the high 4 bit of the high byte is using to indicate the encrypt data added bytes, because the encrypt data must be 16 bytes align, so if the original data is not, it need added some bytes to align.

DATA: Reserved for data, size-varying according with message type and destination device type. This field is coded by the byte stuffing method explained on the next topic;

CRC: The CRC16-CCITT calculation from DD until the last byte of DATA. CRC is calculated before the byte stuffing process.

EOF: End of Frame, 0x04, 1 byte. This byte ends every packet sent.

**Comment by tananaev** [comment]
Here is a related topic - #1633.

**Comment by tananaev** [comment]
I have implemented the response. It needs to be tested though.

**Comment by gustavofcalmeida** [comment]
Took the messages below from Traccar log file.

```
           ST DD MT DEVIC_ID DATA      CRC  EN
received:  01 a6 31 ddccbbaa [omitted] f362 04
sent:      01 a6 02 aabbccdd 62f3      591c 04
should be: 01 a6 02 ddccbbaa f362      40ab 04

           ST DD MT DEVIC_ID DATA      CRC  EN
received:  01 a6 31 ddccbbaa [omitted] a3e4 04
sent:      01 a6 02 aabbccdd e4a3      b2d7 04
should be: 01 a6 02 ddccbbaa a3e4      b154 04
```

Explanation:
- device id bytes are inverted
- received crc bytes are inverted
- the calculated CRC
  - is being calculated from ST until DATA (should be from DD ultil DATA)
  - is using 0xFFFF initial value (should use Xmodem 0x0000)
  - bytes are inverted

**Comment by tananaev** [comment]
@gustavofcalmeida, thanks for the information. Please check if it works now.

**Comment by gustavofcalmeida** [comment]
Almost there. Check the pull request.

**Comment by BrunoBarrosAL** [comment]
Gustavo, bom dia.

Você conseguiu resolver o problema com o rastreador da maxtrack?

Eu consegui fazer funcionar o modelo MXT 140, mas o modelo MXT 151 não funcionou. Aparece a seguinte mensagem no debug:

`2018-08-02 08:40:52 DEBUG: [f5ad29f8: 5087 < 179.126.222.164] HEX: 01a331de6b50000867ba07f4e61024351d46d3fedde1fffc10213a1030000000000000000000000000102112173100003002000000222a00002a5104
2018-08-02 08:40:52  WARN: [f5ad29f8] error - readerIndex(53) + length(4) exceeds writerIndex(56): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 53, widx: 56, cap: 60) - IndexOutOfBoundsException (... < MxtProtocolDecoder:153 < ExtendedObjectDecoder:51 < ... < WrapperContext:102 < ...)
`

Base o que pode estar acontecendo?


Grato.
