### ISSUE TITLE
Bug sensor

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar#2856]
Also on sensors should correct values;
I use gps Teltonika and are present i/o

For the i/o72 , i/o73 and i/o74 the value are reported as follows: 
the value 300 that corresponds to 30°C in fact for teltonika is "10* i/o72
From sensor i/o78 is visible out a long value should have the opportunity to associate this value the name of the driver.
Sensore i/o241 is the operator code should have correspondence with the operator name example: Wind / 22288;
The sensor i/o66, i/o67 e i/o68 is set in the millivolts value  example 12,55V / 1255
Sensor i/o21 representing signal GSM with value from 1 to 5 maybe write good, very good or symbol level
other sensors that report with value  1 or 0 should have possibility of becoming a description example is stop motion sensor 0/1 is moving;

**Comment by tananaev** [comment]
I would need documentation from Teltonika with description on how to decode IO values.

**Comment by netluca1** [comment]
I send the protocol at your email anton@traccar.org

**Comment by tananaev** [comment]
You sent me the documentation for FM5500. What about other Teltonika devices?

**Comment by netluca1** [comment]
The documentation fm5500 include the past devices. Serie fm11xx is egual with minor function

I have documentation for fm3200 and fm4200

**Comment by tananaev** [comment]
Do FM3200 and FM4200 documents have the IO mapping table as well? If yes, can I have them? If not, what makes you think it's the same? Also, what about FM11xx?

**Comment by netluca1** [comment]
i sent email for old fm

**Comment by tananaev** [comment]
It doesn't have anything about sensors, which brings us back to my other questions from previous comment, that you haven't answered.

**Comment by netluca1** [comment]
i sent email all I/O

**Comment by tananaev** [comment]
I have added some more attributes.

**Comment by netluca1** [comment]
there is present error 
io78 you wrong called RFID but io78 is used for IbuttonID
for Rfid the correct is io207

**Comment by netluca1** [comment]
You 'can change the scale of values
example:
Io power corresponding to the drive voltage would change the mV value in volts esp.12526mV become 12,526V
Io battery which corresponds to the voltage of the battery GPS would change the mV value in volts esp.5961mV becomes 5,961V
Io70 Temperature PCB is possible put the comma esp. 285 would become 28.5 by adding °C
io24 speed would add to the number beside the written Km / h
io199 that corresponds to the GPS odometer add KM  after the value
io23 corresponding accelerometer GPS to add the digitura after the value m / s2
I temp1 or Temp2 or TEMP3 would add digit after the value ° C

**Comment by tananaev** [comment]
In Traccar any identification information is saved in "rfid" value. It can be iButton or RFID.

Voltage is store in mV. Temperature already includes decimal point.
