### ISSUE TITLE
format date

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar#2861]
The dates must have the possibility of being set up as YYYY / MM / DD or DD / MM / YYYY

**Comment by tananaev** [comment]
Why?

**Comment by netluca1** [comment]
In all device is possibile set more formato. 
International is yyyymmgg
Europe is ggmmyyyy

**Comment by tananaev** [comment]
You should provide a bit more details. Why international format doesn't work for you?

**Comment by netluca1** [comment]
in all europe every document is set this thus

**Comment by tananaev** [comment]
First of all, I am originally from Europe, and I've seen both version.

Secondly, if you are talking about Excel reports, the format can be configured through templates.

**Comment by netluca1** [comment]
i talk about excel but if possible set set in the program.
More competitor is set thus

**Comment by tananaev** [comment]
It's already possible to configure it in Excel.

**Comment by netluca1** [comment]
how can I configure

**Comment by tananaev** [comment]
Please read my messages more carefully. You can configure it in templates. Open Excel template and edit date format there.

**Comment by netluca1** [comment]
ok thx i view
