### ISSUE TITLE
report bug

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar#2862]
The address is reported incorrectly before the house and then the way

**Comment by hackerunet** [comment]
can you be more specific about this? if you talk in a different language like spanish can you please explain it in spanish to understand what you mean?

**Comment by tananaev** [comment]
Format of the address can be configured using `geocoder.format` parameter.

**Comment by netluca1** [comment]
when is possible set the parameter "geodecoder.format"?
in config File? or si code in other part?

**Comment by tananaev** [comment]
It's NOT "geodecoder". Please use correct key.

It goes into the config file.

**Comment by netluca1** [comment]
for modding this parameter is necessary recompiler or is possible change in file called AddressFormat.java

**Comment by tananaev** [comment]
The parameter can be set in the config file. You don't need to change any code or recompile anything.

**Comment by netluca1** [comment]
I can not find the documentation you make me an example of what I enter in traccar.xml file

**Comment by tananaev** [comment]
Here is an example:
```xml
<entry key='geocoder.format'>%r, %h, %c</entry>
```

**Comment by netluca1** [comment]
ok thx
