### ISSUE TITLE
WARNING : Traccar may have failed to start (Inapproiate ioctl for device)

### ISSUE THREAD

**Issue by FanerK** [tananaev/traccar#2864]
Hi Tananaev,

while i running on terminal with console:
```
root@Track ~] # sudo   /opt/traccar/bin/traccar console
wrapper   | 4631 pid file, /opt/traccar/bin/./traccar.pid, already exist
wrapper   | ERROR: Could not write pid file /opt/traccar/bin/./traccar.pid: Inapproiate ioctl for device
```
Can you help me? thanks

**Comment by hackerunet** [comment]
I have fixed this issue before by removing the PID file by hand and then restarting the service.
However the last wrapper error could suggest IO issues which you may check in OS logs.

**Comment by FanerK** [comment]
Hi,
I had to restart the OS and update the OS, but no significant results. We would be able to provide solutions that fit. Thanks

**Comment by tananaev** [comment]
It seems like you are using old version of Traccar. I would recommend updating.
