### ISSUE TITLE
[Feature Request] OSRM integration with traccar

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2866]
Hi,

We would like to add route between source and destination using [OSRM](https://github.com/Project-OSRM/osrm-backend) as backend.

Right now it is provided using [Leaflet routing machine](http://www.liedman.net/leaflet-routing-machine/) project.

How to achieve it using traccar ?

Thanks.

**Comment by tananaev** [comment]
It's a completely new functionality that has never been implemented on Traccar, so I don't have the answer to your question.

**Comment by kirantpatil** [comment]
Ok Sir, Thanks.

**Comment by kirantpatil** [comment]
Closing this issue.
