### ISSUE TITLE
EventForward.java issue - post request

### ISSUE THREAD

**Issue by al3x1s** [tananaev/traccar#2870]
Hello guys, I was trying to use the EventForward feature and I had an issue with it,

when traccar-server receive an event and forward to a nodejs server, this is what nodejs receive:

```json
{ '{"event":{"geofenceId":0,"serverTime":"2017-02-03T18:03:23.321-06:00","positionId":50546755,"deviceId":257,"type":"alarm","id":558463,"attributes":{}},"position":{"deviceTime":"2017-02-03T18:02:54.000-06:00","outdated":false,"valid":true,"latitude":xx.72566,"longitude":-xx.71874166666667,"altitude":0.0,"speed":0.0,"course":264.66,"fixTime":"2017-02-03T18:02:54.000-06:00","address":"xx","protocol":"totem","deviceId":257,"id":50546755,"attributes":{"alarm":"powerOn","hdop":"01.0","io1":"000000000000","battery":"429","power":1240.0,"adc1":"00000000","lac":40,"cid":4979,"temp1":"0000","odometer":0.0,"ip":"xxx.56.xxx.136","distance":0.0,"totalDistance":2.25}},"device":{"category":"","model":"","status":"online","phone":"","contact":"","lastUpdate":"2017-02-03T18:03:23.184-06:00","positionId":50546754,"geofenceIds":': [ '' ] },
```

a wrong object with all data in the key and with value = ['']

I found the solution changing this line:

https://github.com/tananaev/traccar/blob/master/src/org/traccar/notification/EventForwarder.java#L52

to this:
```java
requestBuilder.addHeader("Content-Type", "application/json; charset=utf-8");
```

I was searching about it in traccar issues and I found the issue (https://github.com/tananaev/traccar/issues/2395) where @Abyss777 explain why he change that line, I just want to leave this here if anyone has this issue only have to change that line and everything will work like a charm 

best regards

**Comment by Abyss777** [comment]
@al3x1s 
Just curious, what if you add content-type in `event.forward.header` without changing the code. How will your application treat two content-type headers?

@tananaev 
I think we should improve this part a bit, `event.forward.header` should override content-type and user-agent default headers (if present). What do you think?

**Comment by tananaev** [comment]
Why did we set content type and user agent?

**Comment by Abyss777** [comment]
Just default values to user convenience. But looks like they are not very universal.

**Comment by tananaev** [comment]
I think we should remove user agent. Let Java set it automatically. As for content type, it should match the actual content. Is it JSON?

**Comment by Abyss777** [comment]
Yes, it is JSON.

**Comment by tananaev** [comment]
Then it should be `application/json`.
