### ISSUE TITLE
Tiempos - Email - Solo lectura - reportes

### ISSUE THREAD

**Issue by djbo1982** [tananaev/traccar#2873]
@hackerunet Hola amigo como estas...

Estoy tratando de configurar varias cosas en el sistema, pero no encuentro la forma.

1.: Cambiar el tiempo para que desaparezca la ultima ubicacion del auto, necesito que este tiempo sea mas largo, ya que a veces el dispositivo se desconecta por alguna razon y cuando le doy click para ubicarlo no aparece en el mapa.

2.: Como configurar los valores del correo electronico de los usuarios para que reciban las notificaciones

3.: Como hacer para que los usuarios solo lectura no puedan enviar comandos a los dispositivos

4.: cuando trato de hacer un reporte de sumario de un grupo de autos (50 autos), la plataforma no lo muestra, tengo que seleccionar grupos mas pequeños (maximo de 10 autos)

5.: He intentando configurar mi iphone para que reporte a mi plataforma, para poder usarlo mi punto de ubicación como referencia cuando estamos buscando otros autos, pero no he conseguido ni una vez que esto funcione

**Comment by tyepez** [comment]
Compañero,

Los valores para configurar para el envío de correo lo encuentras en **/Ruta/Donde/Lo/Instalaste/traccar/conf/traccar.xml**
Y agregas los siguientes valores:

    <entry key='mail.smtp.host'>ServidorDeCorreo</entry>
    <entry key='mail.smtp.port'>25</entry>
    <entry key='mail.smtp.ssl.enable'>false</entry>
    <entry key='mail.smtp.ssl.trust'>false</entry>
    <entry key='mail.smtp.from'>CorreoQuienEnvia</entry>
    <entry key='mail.smtp.auth'>true</entry>
    <entry key='mail.smtp.username'>Usuario</entry>
    <entry key='mail.smtp.password'>Clave</entry>


Los valores pueden varias según las opciones de conectividad de tu servidor de correo.
