### ISSUE TITLE
LOG VIEWER

### ISSUE THREAD

**Issue by djbo1982** [tananaev/traccar#2880]
@tananaev @Abyss777 

I now we can see the LOGs file in the folder of traccar system or see the folder trough FTP or what ever, and in some case we can have a config address like me to download the log and review, but maybe if i´m a admin user we can have a button in the WEB view to can see the log with out problem, is More useful and fast way to find problem. 

Think in: if im a admin user, and im add devices in the platform, i can see why one devices is not reporting, or it is this devices have a issue in the IMEI number, or im wrong when i write the IMEI number.

Every body go to love this function

**Comment by tananaev** [comment]
I don't think it makes much sense. Log files can be huge. We interface is not the best option to handle massive text files.
