### ISSUE TITLE
Feature Request -  SMS Notification / SMPP 

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2882]
Dear All,

Along with web and email notification, There are some Critical Alerts such as (Power Cut Off, SOS), Which would be alerts that users would like to be made aware of Instantly. ( I have been also wondering if implementing Firebase Cloud Messaging for Android and Apple Push Notifications for iOS would help),. Where each user login  in via their Android and or iOS APP will get registered for notifications on their mobile App.

Coming back to the feature request of SMS Notification. I would like to propose a certain plan.
1. To create a `sms_out` table where, on selection by user for SMS notification for any event, Traccar will populate the table with the events details (SMS templates similar to email template)
- Table proposed columns (`id, createtime, deviceid, msisdn, message, messageid, status, senttime, deliverytime`) `messageid` = unique id returned by SMPP server to identify and trace this message in future, for delivery report etc.  and` status` can be default `pending` , later updated to `sent` or `failed` based on delivery status or smpp response.
- Users MSISDN (Mobile Number) can be stored in user table. and taken from there.

- Implementing the above, will benefit in two ways, users can implement their own tasks/apps to process these SMS's to begin with.
- And in future as Traccar implements SMPP and SMS Notification, the same table can be used to create and update SMS's.

2. SMPP Implementation, It would be nice to have two columns agains each user to maintain the number of SMS a user has access to. as SMS is generally chargeable by almost all operators.
- A cost column and a Total Credit Column, cost being the amount to be deducted for each SMS being sent, thus if a user needs to be given USD 100 worth of sms and each SMS costs USD 0.08, the Total Credit column could contain 100, and each SMS sent will reduce the Total Credit column value by 0.08

These are just few of my suggestions,.

**Comment by tananaev** [comment]
I agree in general that it would be nice to send SMS messages, but I don't see why we need a separate table for it and why we need to calculate cost. It's kind of out of scope for tracking system.

**Comment by jaimzj** [comment]
Surely let me explain the reason I chose to suggest a separate table and cost calculation.

Seperate Table
1.  SMS delivery is not always guaranteed, and for each SMS sent a messageid is generated by the SMPP server and returned to the client (this needs to be stored for troubleshooting/reconciliation plus delivery status checking if need be).
2. Having a seperate table suggestion primarily was so that, until SMPP is implemented into traccar users can as well use this table and deploy their own services/applications to process sms from this table.
3. Having worked with telco operators on Network side, I have always seen it generally being a practice by most SMS Application providers to store the SMS Into a table along with its (status). so failed sms' can be retried, delivery can be checked,
- One major reason being many countries have regulations, saying any and all SMS be it promotional or transactional, sent should be stored for x days by the user/sender. This policy is applicable in many Regions where SPAM/Bulk SMS is a major concern and calls for huge penalties. although these SMS by Traccar will fall under transactional category, records might be required by and in many regions.


As for cost, It can totally be avoided, and just a number count would do the work as well, the only reason I mentioned it was, If a user wanted to charge his clients a different SMS consumption rate he could manage it better as SMS are charegable, and users would want to recover the cost. However he can do that with simple number of sms count as well.

**Comment by Abyss777** [comment]
I think something like "notification queue" (separate table) is not a bad idea. There was some requests for delayed and grouped notifications. But it should be implemented for all type of notifications.

**Comment by tananaev** [comment]
Totally agree with @Abyss777. SMS notifications is one thing. Table to store sent/unsent notifications is a completely different thing, and it shouldn't be SMS-specific.

**Comment by tyepez** [comment]
yes, it is a great idea. please!

**Comment by tyepez** [comment]
But all notifications must be individual for each device. (not per account)
