### ISSUE TITLE
Different color marker icon

### ISSUE THREAD

**Issue by bernamaxim** [tananaev/traccar#2883]
What is represented by this different color?

<img width="173" alt="screen shot 2017-02-08 at 3 07 10 pm" src="https://cloud.githubusercontent.com/assets/2969479/22728432/77517062-ee10-11e6-8e12-0df122a3ce56.png">

**Comment by tananaev** [comment]
Please use search:

https://github.com/tananaev/traccar/issues/2100#issuecomment-231784949
