### ISSUE TITLE
MS SQL foreign key issue

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#2884]
Checked recent changes on MS SQL and got an error (not surprised):
````
SEVERE 2/8/17 1:01 PM: liquibase: schema/changelog-master.xml: changelog-3.10::changelog-3.10::author: Change Set changelog-3.10::changelog-3.10::author failed.  Error: Введение ограничения внешнего ключа (FOREIGN KEY) "fk_user_user_manageduserid" для таблицы "user_user" может привести к появлению циклов или множественных каскадных путей. Укажите ON DELETE NO ACTION или ON UPDATE NO ACTION либо измените другие ограничения внешнего ключа (FOREIGN KEY). [Failed SQL: ALTER TABLE [dbo].[user_user] ADD CONSTRAINT [fk_user_user_manageduserid] FOREIGN KEY ([manageduserid]) REFERENCES [dbo].[users] ([id]) ON DELETE CASCADE]
````

I'm going to add "-notmssql" changeset like in 3.7.
Also I'm thinking of improving  `database.deleteUser` request to cleanup `users_users` table after it.
Is that appropriate way?

**Comment by tananaev** [comment]
Wouldn't in automatically remove it if we have the foreign key?

**Comment by Abyss777** [comment]
MS SQL do not allow us to have such key. (with ON DELETE CASCADE).

In other DB's it will be automatically removed.

**Comment by tananaev** [comment]
We can possibly implement some trigger for MS SQL, but I don't think we should put any database specific code in the generic configuration or code.

**Comment by Abyss777** [comment]
We can just add:
````
    <entry key='database.deleteUser'>
        DELETE FROM users WHERE id = :id;
        DELETE FROM user_user WHERE managedUserId = :id;
    </entry>
````

It is not 100% guarantee but...

**Comment by tananaev** [comment]
I don't think we should do this. It adds unnecessary redundancy.
