### ISSUE TITLE
TK103B log-on failure help

### ISSUE THREAD

**Issue by wotmae** [tananaev/traccar#2888]
Please help with my unsuccessful attempts to login to your Traccar programme with a TK103B Tracker.
To prove the Traccar programme I have successfully logged on with Traccar Client on two smart phones and these work very well:
	ID 325689 and 320216 / IP: 192.168.0.1 on port:5055.
However, despite a number of attempts I am unable to log-on with my TK103B device. I have used:
   1.	Web Firewall disabled
   2.	Device Name: 187YUY
   3.	Unsuccessful Log-on data attempts
        a.	Device identifier: 868683021715143 (emei number)
                IP Address: 192.168.0.1 (from the Virgin Media router)
                Port number: 5001  /  5002  /  5006  /  5013  /  5023  /  5036  /  5093 
	b	Traccar Device Identifier 083021715143 (short 12 digit ID)
                IP Address: 192.168.0.1
                Port Number: 5002
        c.	Traccar Device identifier: 868683021715143 (emei number)
                IP Address: 192.168.0.1
                Port number: 9000 (suggested in the TK103B Supplier Manual)
Any suggestions would be most appreciated
Thanks

**Comment by papz77** [comment]
Hi,
the port for TK103B is 5001, the id is the IMEI (868683021715143), the address of gateway is not your private address (router 192.168.0.1). Your smartphone work in local area network via wifi and can send data via LAN. The tk103B use gprs protocol in 2G network and you must to specify APN name, GPRS mode and ip and port of your router (public address of your router, not class C address).

**Comment by tananaev** [comment]
Please follow this guide:

https://www.traccar.org/troubleshooting/

**Comment by wotmae** [comment]
Hi,

Thanks for such a prompt response, very impressive, clear and helpful.

I followed your instructions and sorted most of the issues (I think) but it still won’t work. The issue I think is that it will not engage GPRS mode.

I have given the instruction several times (gprs123456 / GPRS123456 / Gprs123456) and each time it responds with GPRS ok  -  but the Check123456 command responds with:

Power:ON  /  Bat: 100%  /  GPRS: OFF  /  GPS: ON  / ACC:OFF  / Door: OFF  /  GSM:10  /  Oil: 0.00%  /  APN:giffgaff.com,,;  /  IP: 77.99.246.65:5001  /Arm:ON 

 

Any further help would be much appreciated

 

Thanks

**Comment by tananaev** [comment]
I would recommend checking with your device vendor. It seems like it's some device issue.

**Comment by wotmae** [comment]
Thanks - The unit has never been used but unfortunately I bought it a couple of years ago, on Ebay, from china. So the vendor is long gone. 
I have tried resetting it with begin123456 and re-inputting the details with no success.
Any other advice on a reset would be helpful ..........
Looks like I'm stuffed but thanks for your advice.  Much appreciated.

**Comment by papz77** [comment]
Your SIM card support 2G mode? The TK103B don't work on 3G, 3GS and 4G networks. you must to use a SIM 2G such as http://www.onesimcard.com/machine-to-machine-communications-sim/ or similar.

Make a check through the IMEI on COBAN website or on gpstrackerxyz.com site to verify the manufacturer

If tracker go to response "ok!" at the command GPRS123456 he went in GPRS mode. The problem is the SIM or APN address of your network. If you are using your home router, you can open port in firewall and set the port forwarding to your home server (redirect all traffic on port 5001 to your server address)

**Comment by wotmae** [comment]
Working now - thank you. The final problem was the port forwarding setting in the Virgin Media router. Once set to accept 5001 traffic it immediately worked.
Thank you for your assistance - I would never have done it alone.
Please close this request for assistance.
