### ISSUE TITLE
Server connection failed

### ISSUE THREAD

**Issue by toromand** [tananaev/traccar#2895]
Hi,
I've just installed traccar 3.9 on Ubuntu 16.04_64. The web interface is working both locally and from the Internet using a browser on default port 8082

Current Goggle Play Android version reports "Server connection failed" when trying to enter
http://xxx.xxx.xxx.xxx:8082 
demo server works
My URL works just fine in the browser on the same device.

Any idea?

P.S, Using OnePlus 3t / Android 7.0

**Comment by tananaev** [comment]
Are you sure you are using official version without any modifications?

By "Android version" I'm assuming you mean Traccar Manager app, right?

**Comment by toromand** [comment]
Yes and Yes

**Comment by toromand** [comment]
What is interesting, the message "Server connection failed" is instant as soon as I press the button.... It doesn't even look like it's trying to connect

**Comment by tananaev** [comment]
Can you please send the actual IP address to check myself. My email address is in profile.

**Comment by toromand** [comment]
Sent it to you

**Comment by tananaev** [comment]
That's not an OFFICIAL version of Traccar.

**Comment by toromand** [comment]
Downloaded here 
https://www.traccar.org/download/

**Comment by tananaev** [comment]
If you did, it should look like this:

http://demo.traccar.org/

**Comment by toromand** [comment]
I'm perfectly sure I downloaded 
traccar-linux-3.9.zip
I will recheck tomorrow if I maybe accidentally  installed again the 2.x version running before on the same machine as I still have the installation files. there. 

To be sure I will download again and repeat the installation and report back

**Comment by tananaev** [comment]
It seems like you have Web UI mod installed, which is not an official Traccar project.

**Comment by toromand** [comment]
I'm perfectly sure I just started the unpacked. run file and left everything default. I will recheck if I have started the right thing

**Comment by tananaev** [comment]
Well, then it's probably version 2.x.

**Comment by toromand** [comment]
You were right, it was the old version reinstalled :(
