### ISSUE TITLE
GT02a Chinesse clon

### ISSUE THREAD

**Issue by inghoward** [tananaev/traccar#2898]
Hello,
Got a device that sends this:
```
283032373034343731353736314250303033353532323730343437313537363148534f31613429
```
I'm unable to find what is the protocol used fot this device. Can some help me?

**Comment by tananaev** [comment]
It's TK103 protocol, port 5002 in Traccar. Device id is 027044715761.

**Comment by inghoward** [comment]
Thank you very much Anton.
