### ISSUE TITLE
3.9 to 3.10 database migration problem

### ISSUE THREAD

**Issue by djbo1982** [tananaev/traccar#2900]
Hello @tananaev 

I´m trying to migrate my MySql database of version 3.9 to the new 3.10 version.

I´m followng the step @Abyss777 

_Abyss777 commented 18 days ago
Hello

The most correct way backup/restore to me is:

Backup DB without two tables DATABASECHANGELOG and DATABASECHANGELOGLOCK
Run once new instance of server, to create db scheme correctly, and write DB changelog records.
Stop server
Restore backup
Start server
Of course source and new servers should have the same version._

you know, we can migrate table by table, because we can erase some tables, or we cant import data, we need to erase all and upload the file with old files

but, i received error in:
```sql
CREATE TABLE `attribute_aliases` (
  `id` int(11) NOT NULL,
  `deviceid` int(11) NOT NULL,
  `attribute` varchar(128) NOT NULL,
  `alias` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
MySQL ha dicho: Documentación
```
#1050 - Table 'attribute_aliases' already exists

i can restore the databe, if i erase all tables without two tables DATABASECHANGELOG and DATABASECHANGELOGLOCK, the mysql restore the backup and show all info with out problem but i have another problem when i login in the system, because the new schema of the database is diferent and have another tables and example user have another structure

**Comment by tananaev** [comment]
I believe I have already explained how to upgrade in #2828.

You don't have to remove `DATABASECHANGELOG` and `DATABASECHANGELOGLOCK`.
