### ISSUE TITLE
High CPU usage under windows 64

### ISSUE THREAD

**Issue by slachtar** [tananaev/traccar#2905]
Hello,
I'm using traccar latest versions, I noticed a high CPU usage (about 50%), and traccar is managing about 360 trackers. Please see attached screenshot.
I'm using it only as url forwarder to another system, i.e, gps positions are being forwarded, no db storage.

Does the number of threads equal number of connected trackers? Why the cpu usage is hight?

Aside question: can I set two ports for the same protocol?

Regards,

[http://imgur.com/a/Kb57l](http://imgur.com/a/Kb57l)

**Comment by tananaev** [comment]
Depending on the frequency of reporting, it might be a reasonable CPU usage. Another possibility is that you have something misconfigured.

**Comment by slachtar** [comment]
Hello,
I've no reporting, indeed web is disabled.
I'm using the forward url only.
Should l remove all db queries entries in such config?
Is the number of threads equal number of connected trackers?

For my 2nd question about using two ports for the same protocol. should I
simply duplicate protocol entries in config file and use two ports.

Regards

**Comment by tananaev** [comment]
I think you misunderstood. By "reporting" I meant the frequency of the device reporting the data to the server.

> Is the number of threads equal number of connected trackers?

It shouldn't be the case.

> should I simply duplicate protocol entries in config file and use two ports.

No, it won't work like that.

**Comment by slachtar** [comment]
I removed insertPosition sql statement, and everything is going fine now.
Thanks
