### ISSUE TITLE
Traccar 3.9 api/positions

### ISSUE THREAD

**Issue by jordyjonatan** [tananaev/traccar#2908]
Hi, I'm using Traccar 3.9, I got an error when I hit /api/positions but got success on others

Here is the error:
```
Device access denied - SecurityException (PermissionsManager:194 < PositionResource:76 < ...)
```
I have checked the permission in the web client and it showed that the permission is enabled. 
Help me to check this out. Thank you

**Comment by tananaev** [comment]
Duplicate of #2890.
