### ISSUE TITLE
Ignition Notifications

### ISSUE THREAD

**Issue by Arturo2017** [tananaev/traccar#2911]
I have my [iTracMT-1V8](http://s.aliexpress.com/meMNzuEZ) (H02 port 5013) working "correctly" with your TraccarDemo4 server.

![14 de febrero de 2017 141029 cet](https://cloud.githubusercontent.com/assets/25770031/22931152/db53af1e-f2c3-11e6-85be-ea72215c40b0.jpg)

Web/email notifications work correctly for example with the GeoFences, ...but I do not receive Ignition ON/OFF changes which are displayed ([reversed](https://www.traccar.org/forums/topic/mistake-in-ignition/)) on the device screen.

Do I have to configure ignition notifications somewhere else?
THANKS

**Comment by tananaev** [comment]
Please check following thread:

https://www.traccar.org/forums/topic/mistake-in-ignition/

**Comment by Arturo2017** [comment]
From there i'm coming because you told me:

"That’s a completely different issue. Please don’t make a mess out of this thread"

...????

**Comment by tananaev** [comment]
OK, I though you were talking about them being reversed. Is ignition information included in every message?

**Comment by Arturo2017** [comment]
Status: TRUE / FALSE. This is what appears in the ATTRIBUTES column when I export reports:

![screenshot_2017-02-15-02-55-22](https://cloud.githubusercontent.com/assets/25770031/22957856/9be54bea-f32b-11e6-93c8-631c527449cb.png)

**Comment by tananaev** [comment]
What do you see in the "state" panel? Does it change there?

**Comment by Arturo2017** [comment]
Ignition: toggles between YES and NO for each movement of the ignition-key.

I do not know if it can be related, but in the StatePanel the "Valid" field always stays in "NO" (and when exporting reports the "VALID" column always "FALSE")

**Comment by tananaev** [comment]
Can I have access to the web console to take a look?

**Comment by Abyss777** [comment]
@tananaev 
should we remove check for "valid" here? https://github.com/tananaev/traccar/blob/master/src/org/traccar/events/IgnitionEventHandler.java#L36

**Comment by tananaev** [comment]
I didn't even realize we had it there. Yes, we should probably remove it.
