### ISSUE TITLE
problem smtp

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar#2914]
hello i have problem for function email.
i have configured the smtp in the file traccar.xml
```xml
<entry key='mail.smtp.host'>smtp.gmail.com</entry>
<entry key='mail.smtp.starttls.enable'>false</entry>		
<entry key='mail.smtp.host'>smtp.gmail.com</entry>
<entry key='mail.smtp.port'>465</entry>
<entry key='mail.smtp.ssl.enable'>true</entry>
<entry key='mail.smtp.from'>pluto@gmail.com</entry>
<entry key='mail.smtp.auth'>true</entry>
<entry key='mail.smtp.username'>pluto@gmail.com</entry>
<entry key='mail.smtp.password'>pluto</entry>
```
i have start traccar
but in the file tracker-server.log is present this error
```
2017-02-15 22:12:53  WARN: 530 5.7.0 Must issue a STARTTLS command first. k9sm3127508wrd.51 - gsmtp - SMTPSendFailedException (... < NotificationMail:119 < *:129 < ...)
```

**Comment by tananaev** [comment]
Looks like your configuration is incorrect. It seems like your SMTP server requires STARTTLS.

**Comment by netluca1** [comment]
if i enable this parameter

<entry key='mail.smtp.starttls.enable'>true</entry>

is necessary change other parameter?

**Comment by tananaev** [comment]
If you enable it, you should probably remove SSL parameter. For more info please see following documentation:

https://javamail.java.net/nonav/docs/api/com/sun/mail/smtp/package-summary.html
