### ISSUE TITLE
maps

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar#2918]
Hello, 
you can move from one map to another without exiting the program?
how it was done in WEB UI version of Livtak?
![immagine](https://cloud.githubusercontent.com/assets/23439828/22996997/0799a7dc-f3d1-11e6-98ba-312a71715eb5.jpg)

**Comment by tananaev** [comment]
All you need to do is refresh the page.

**Comment by tananaev** [comment]
By the way, this question belongs to `traccar-web` repository.

**Comment by netluca1** [comment]
close and reopen in traccar-web repository
