### ISSUE TITLE
menu calendar

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar#2924]
hello i would say what is function?
I tried insert a new calendar but is not possible activate because i not insert file?
What should I enter as a file?

![calendar](https://cloud.githubusercontent.com/assets/23439828/23046919/c8ce205a-f4ac-11e6-852b-c2721f46bd52.jpg)

If i tried insert name without insert file is generated error

![errore calendar](https://cloud.githubusercontent.com/assets/23439828/23047026/649828fa-f4ad-11e6-8fa3-8595d4f5bfbe.jpg)

Furthermore, and also here attibute button.
I have to insert some data?
There are possible variables

![attrib calendar](https://cloud.githubusercontent.com/assets/23439828/23046930/d72aacf4-f4ac-11e6-9dc5-16fc2974b302.jpg)

**Comment by tananaev** [comment]
Documentation is coming soon.
