### ISSUE TITLE
Refresh issue

### ISSUE THREAD

**Issue by vastangiul** [tananaev/traccar#2926]
Hello ,
I have an account to primary traccar demo server and i have found 2 bugs.
Username elenga.jean@yahoo.com
Identifier : 355488020113911
1) Ignition its wrong : it's off when its on and on when its off 
2) The refresh rate from application  its too faster i cannot send commands via web.
1 or 2 weeks ago refresh rate works fine.

Thank you

**Comment by vastangiul** [comment]
Protocol h02

**Comment by tananaev** [comment]
1. Please check following thread:

https://www.traccar.org/forums/topic/mistake-in-ignition/

2. I believe that there were no changes to the H02 commands recently.

**Comment by vastangiul** [comment]
Now its ignition  on and its displayed off
 When i will switch off the car appears on
You can login into my account to see about the refresh what i mean . 
The username its registered in demo.traccar.org .
Thanks

**Comment by tananaev** [comment]
Have you read the link? It's a know issue.

**Comment by vastangiul** [comment]
Sure for the first bug.
The second problem with the refreshing continously 2 in2 seconds .
That can be fixed?

**Comment by tananaev** [comment]
I can investigate the issue if you provide enough information. I need exact time (including timezone) when you sent the command. What command and what value. Also, I would need protocol documentation with commands format description.

**Comment by vastangiul** [comment]
I cannot give any command because access the button for commands becuase its grey.
Its refreshing all the time.
I dont know how to explain.
You can login to my account to see it live.

**Comment by tananaev** [comment]
Then it's a problem with your device.

**Comment by vastangiul** [comment]
I have reset it.
But thensame problem.
I dont have modified the device config.

With 1 or 2 weeks ago works fine.

Print screen :
http://imgur.com/ej16bDy

**Comment by tananaev** [comment]
Here is the problem:
```
2017-02-17 01:29:47  INFO: [B728EE3C] connected
2017-02-17 01:29:47 DEBUG: [B728EE3C: 5013 < 213.233.85.205] HEX: 2a48512c3335353438383032303131333931312c56312c3031323934352c412c353233312e37393238332c4e2c30313332342e31303731382c452c302e30352c302c3137303231372c4646464646464646230d0a
2017-02-17 01:29:47  INFO: [B728EE3C] id: 355488020113911, time: 2017-02-17 01:29:45, lat: *, lon: *, speed: 0.1, course: 0.0
2017-02-17 01:29:47  WARN: [B728EE3C] error - IllegalArgumentException (H02FrameDecoder:84 < ...)
2017-02-17 01:29:47  INFO: [B728EE3C] disconnected
```

**Comment by tananaev** [comment]
I have fixed the problem. The fix will be included in the release.

**Comment by vastangiul** [comment]
Thank you.
