### ISSUE TITLE
Link wrong email notification

### ISSUE THREAD

**Issue by Turbovix** [tananaev/traccar#2927]
Hi Tananaev,  I noticed that the e-mail notifications of version 3.10 that I receive with the link of the location that occurred the event points to the following link: (http://127.0.1.1:9272/?eventId=52).

I noticed that there were changes in the code of the files (XXXXX.vm)

**Archive alarm.vm - Traccar v. 3.9**

```
#set($subject

 = "$device.name: alarm!")
<!DOCTYPE html>
<html>
<body>
Dispositivo: $device.name<br>
Alarme:  $position.getString("alarm")<br>
Local: <a href="https://www.openstreetmap.org/?mlat=$position.latitude&mlon=$position.longitude#map=16/$position.latitude/$position.longitude">#if($position.address)$position.address#{else}$position.latitude°, $position.longitude°#end</a><br>
Data: $event.serverTime<br>
</body>
</html>
```

**Archive alarm.vm - Traccar v. 3.10**

```
#set($subject = "$device.name: alarm!")
<!DOCTYPE html>
<html>
<body>
Dispositivo: $device.name<br>
Alarme:  $position.getString("alarm")<br>
Data: $event.serverTime<br>
Local: <a href="$webUrl?eventId=$event.id">#{if}($position.address)$position.address#{else}$position.latitude&deg;, $position.longitude&deg;#{end}</a><br>
</body>
</html> 
```

**Comment by tananaev** [comment]
You can configure it using "web.url" parameter.

**Comment by Turbovix** [comment]
I got it, thanks!

**Comment by Turbovix** [comment]
Hi Anton, I inserted directly in the file traccar.xml the parameter below:

`<Entry key = 'web.url'> https://www.openstreetmap.org </ entry>
`

However I am now receiving the following link:

`Https://www.openstreetmap.org/?eIdId=140#map=19/-20.41776/-40.33685
`

In this way the marker of the exact location where the event occurred is not shown.
In the link what would this be (eventId = 140) and what function in the link?

**Comment by Abyss777** [comment]
@Turbovix 
try to add `/` at the end of `web.url`

**Comment by Turbovix** [comment]
@Abyss777 , I've tried this before, the end result is the same!

From the tests I did, what makes the bookmark appear are this information:

`Mlat = -20.4178193 & mlon = -40.3370138`

**Comment by Abyss777** [comment]
OK. What is `web.url` in your config exactly? Also please provide text of template and source of result email?

**Comment by Turbovix** [comment]
The web.url is parameterization that makes the url available to the files (xxxx.vm) that generate the email with the notifications.


**Archive alarm.vm - Traccar v. 3.10**
```
#set($subject = "$device.name: alarm!")
<!DOCTYPE html>
<html>
<body>
Dispositivo: $device.name<br>
Alarme:  $position.getString("alarm")<br>
Data: $event.serverTime<br>
Local: <a href="$webUrl?eventId=$event.id">#{if}($position.address)$position.address#{else}$position.latitude&deg;, $position.longitude&deg;#{end}</a><br>
</body>
</html> 
```

The email I get is like this:

```
<!DOCTYPE html>
<html>
<body>
Dispositivo: Renault Sandero <br>
Parado<br>
Data: Fri Feb 17 08:15:40 BRST 2017<br>
Local: <a href=3D"https://www.openstreetmap.org?eventId=3D142">197-223 R. N=
ossa Sra. do Ros=C3=A1rio, Vila Velha, ES, BR</a><br>
</body>
</html> =20
```

**Comment by Abyss777** [comment]
````xml
<entry key='web.url'>https://www.openstreetmap.org/</entry>
````

and the template should look like this:

````html
#set($subject = "$device.name: alarm!")
<!DOCTYPE html>
<html>
<body>
Dispositivo: $device.name<br>
Alarme:  $position.getString("alarm")<br>
Data: $event.serverTime<br>
Local: <a href="$webUrl?mlat=$position.latitude&mlon=$position.longitude">#{if}($position.address)$position.address#{else}$position.latitude&deg;, $position.longitude&deg;#{end}</a><br>
</body>
</html>
````

**Comment by Turbovix** [comment]
@Abyss777 , So I have to change all email notification files (xxxxxx.vm) directly in the sources.

**Comment by Abyss777** [comment]
Yes, you should replace link with `href="$webUrl?mlat=$position.latitude&mlon=$position.longitude"` in all templates (*.vm) in your traccar installation.

**Comment by Turbovix** [comment]
Andrey, thanks for your attention!

**Comment by Turbovix** [comment]
@tananaev , Hello Anton, is the problem reporting a bug or do you really need an intervention on the files (sources) responsible for the email alerts?

**Comment by tananaev** [comment]
It's not a bug. You just want to change the behavior, so you need to change templates. The idea is that URL should point to the Traccar server, not OSM.

**Comment by Turbovix** [comment]
Anton, I can not see the advantage of this change, since in the previous version the url already pointed to the OpenStreetMap page, I even managed to put Gooogle maps in the attributes, but there was no bookmark.

**Comment by tananaev** [comment]
Bookmark? I don't follow.

The advantage is that you get actual event information, not only location on map.

**Comment by Turbovix** [comment]
Can you give me an example url to be placed in the attribute (web.url) to use OSM? Everything is working, but I did not want to modify the original Traccar code.

**Comment by tananaev** [comment]
It this you are still misunderstanding how it work. The URL should point to your Traccar web interface.

**Comment by Turbovix** [comment]
Sorry, but I still do not understand. Should I point to the url of my server?

**Comment by tananaev** [comment]
Yes.

**Comment by Turbovix** [comment]
Okay, I'll test it.

**Comment by Turbovix** [comment]
Anton, I tested it here and it worked, but only those who can receive the notifications are registered users of the system, that is, they need to be logged in or have access to the platform. I am sure ?

**Comment by tananaev** [comment]
Yes, they have to be.

**Comment by Turbovix** [comment]
Okay, just a detail, I know that you spend a lot of time in development, in addition to paid work (company) and leisure or family.
But some new features there is no explanation of how to use them, for example the Calendar feature.
So I apologize for the questions that are simple to you.

**Comment by netluca1** [comment]
Hello everyone @tananaev; @ Abyss777; @Turbovix
I agree with the idea that we should point to the Traccar server but if we already send an email with the alerts to the selected user and we point the Traccar server I do not think it is necessary to authenticate.
There is a solution or we have to change as suggested by Andrey Kunitsyn losing information on real events
