### ISSUE TITLE
Headers like cache-control, postman-token etc

### ISSUE THREAD

**Issue by m-menon** [tananaev/traccar#2928]
hi,

If I want the traccar server to be expecting additional headers like cache-control or some other token, custom header etc, where can I set it to 'expect' such headers? Thanks a ton....cheers ,, MM

**Comment by tananaev** [comment]
What do you mean by "expect"?

**Comment by m-menon** [comment]
Well, I was trying to send a postman-token to the API. The error that I was getting is

Request header field postman-token is not allowed by Access-Control-Allow-Headers in preflight response

Which led me to this SO post: http://stackoverflow.com/a/25727411/3524579 ..... which in a way seem to be similar to the problem I am facing when I send an additional header. Once I remove the header it seems to be working fine but just curious that if I want to add additional headers like postman-token .... or cache-control ( this may not really be needed ) ....thanks

**Comment by tananaev** [comment]
These are the allowed headers:

[CorsResponseFilter.java#L29](https://github.com/tananaev/traccar/blob/master/src/org/traccar/api/CorsResponseFilter.java#L29)

**Comment by m-menon** [comment]
Excellent ... thanks :100:
