### ISSUE TITLE
Trouble: "Username is already taken"

### ISSUE THREAD

**Issue by morpheus1000** [tananaev/traccar#2929]
Good morning

I have been working on the mount this project since a few weeks ago, and I have just discovered the litvak project,

I have performed the entire procedure as indicated on its website: http://traccar.litvak.su/installation.html

However I have not managed to make the devices visible on the map, I also have problems creating new users since the following message always appears:  
"Username is already taken"

Where could I find the solution to this problem?

Thanks in advance.

**Comment by tananaev** [comment]
Litvak project is not an official Traccar project, so you should ask your question on their issue tracker:

https://github.com/vitalidze/traccar-web/issues
