### ISSUE TITLE
Accuracy vs HDOP

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#2944]
What is the difference between "accuracy" (i.e., position.setAccuracy()) and "hdop"?

**Comment by tananaev** [comment]
Accuracy is a location accuracy in meters. HDOP (horizontal dilution of precision) is a value reported by the GPS module. I believe it's possible to calculate accuracy from HDOP, but you need to know GPS module parameters.

**Comment by jon-stumpf** [comment]
So, for those protocols that report "accuracy" as commented in the code, is it safe to assume that these should be recorded using this key?

**Comment by tananaev** [comment]
Not really. You need to check protocol documentation. Even if device reports accuracy, it might not be in meters.
