### ISSUE TITLE
traccer not updating

### ISSUE THREAD

**Issue by freebie12345** [tananaev/traccar#2946]
I'm relatively new to traccar. I set up a pt600 tracker which does connect to the server but doesnt update the position. Please help. I've attached the log file
[tracker-server.txt](https://github.com/tananaev/traccar/files/792823/tracker-server.txt)

**Comment by tananaev** [comment]
It looks like your device worked at some point and then you removed it or changed id for some reason.

Also, the devices sends a lot of rubbish data, so I think it's malfunctioning.

**Comment by freebie12345** [comment]
It worked at some point but was not updating position until I restart the server. I set the device to update every 120 seconds. is that the info that is getting corrupted? I'll try to delete then return the device.

**Comment by tananaev** [comment]
You should be able to see the device because data is decoded. There is some problem with the device, but even with this issue it seems to work. I would recommend contacting device vendor to solve the device problem though.

**Comment by freebie12345** [comment]
It seems to be working again. Thanks for your insight.
