### ISSUE TITLE
wialon

### ISSUE THREAD

**Issue by cesarruben** [tananaev/traccar#2953]
Hello the wiatrack pro application uses wialon protocol. Should I use wialon.utf8 to be able to receive messages ?

This is implemented in default.xml ?
```xml
<entry key='wialon.utf8'>enable</entry>
```
![wiatrack pro](https://cloud.githubusercontent.com/assets/18680817/23267450/9375c92c-f9c9-11e6-9748-debc118c5e2c.jpg)

**Comment by tananaev** [comment]
You can try with and without, but the value in your example is definitely incorrect. It should be either `true` or `false`. Not sure where you even got the `enable` value.

**Comment by cesarruben** [comment]
Thank you.
