### ISSUE TITLE
Most common gps choice

### ISSUE THREAD

**Issue by al3x1s** [tananaev/traccar#2959]
I wanted to open this thread to ask to the traccar users which devices are the best You have tried

as everyone know, each GPS have different features for different purpose

so if could You share wich gps you are using and for what kind of vehicle or personal,  and maybe could share the approximate price of this device, I think this will very useful to many people who are searching the best gps to use

Im using AVL-05 from TZone company, this device has been the best gps i have tried at the moment and the price round USD$60 (FOB), I use them for heavy trucks and conventional vehicle like pick-up and cars

Pd. FOB means that price not include shipping and taxes, that depends of your country

**Comment by tananaev** [comment]
I think it's better to ask this question on the forum:

https://www.traccar.org/forums/forum/devices/
