### ISSUE TITLE
Can not update password

### ISSUE THREAD

**Issue by jssenyange** [tananaev/traccar#2962]
Recent fix for issue "Serialization warning in QueryBuilder #2941" excludes members annotated with JsonIgnore. This affects the update of user password since  getHashedPassword is also annotated with JsonIgnore leading to error below given hashedPassword parameter is not set:
```
Parameter "#1" is not set; 
SQL statement: UPDATE users SET hashedPassword = ?, salt = ? WHERE id = ? [90012-193] - JdbcSQLException (... < QueryBuilder:476 < DataManager:179 < PermissionsManager:365 < ...)

**Comment by tananaev** [comment]
Thanks for reporting the problem. I have fixed it. Please check if it works now.

**Comment by jssenyange** [comment]
It works now. Thanks
