### ISSUE TITLE
user password

### ISSUE THREAD

**Issue by d33pak-s1ngh** [tananaev/traccar#2964]
how do i get user password? i try to get user details in which password fields is contains null value.

**Comment by tananaev** [comment]
You can't get password. Only hashes of passwords are stored on the server for security reasons.

**Comment by d33pak-s1ngh** [comment]
so how you are comparing password enter by user with system at login ?
actually i want it to check for current password so if that is correct than only user can apply new password.

**Comment by d33pak-s1ngh** [comment]
what i am doing right now is i am trying to call an api with the password enter by user if it returns error that means password is wrong if api will return user data means password is correct.

**Comment by tananaev** [comment]
You can calculate hash yourself and compare hashes.
