### ISSUE TITLE
ClassCastExecption 

### ISSUE THREAD

**Issue by conorwhyman** [tananaev/traccar#2967]
Hi, 
I have started using a meitrack tc68s device, however when I try and generate a summary/trip report it returns the following error in console: 
```
java.lang.String cannot be cast to java.lang.Number - ClassCastException (Extensible:81 < ReportUtils:66 < Summary:64 < ...)
```
The device is not in the future and has the correct timezone, also I am using the official build. Any recommendation?
All the other, osram works fine.

**Comment by tananaev** [comment]
I would need some logs with messages from the device.

**Comment by conorwhyman** [comment]
Thank you, I have attached the a sample message from the device from the 1st of March. The device is visible on the map, so I am using the correct port. 
Meitrack TC68S messages:

`17-03-01 00:01:46 DEBUG: [3D0B5B58: 5020 < 176.77.143.101] HEX: 24245f3133392c3836373134343032373339393632332c4141412c33352c34372e3630343130312c31372e3931303733382c3137303232383233303134332c412c31312c31372c302c302c302e392c3133362c3830323534372c3235343730312c3231367c317c304531427c344139462c303030302c7c7c7c304134417c303346302c30303030303030312c2a32420d0a
2017-03-01 00:01:46  INFO: [3D0B5B58] id: 867144027399623, time: 2017-03-01 00:01:43, lat: 47.60410, lon: 17.91074, speed: 0.0, course: 0.0
2017-03-01 00:01:56 DEBUG: [3D0B5B58: 5020 < 176.77.143.101] HEX: 2424603133392c3836373134343032373339393632332c4141412c33352c34372e3630343130312c31372e3931303733382c3137303232383233303135332c412c31312c31372c302c302c302e392c3133362c3830323534372c3235343731312c3231367c317c304531427c344139462c303030302c7c7c7c304134427c303346302c30303030303030312c2a32460d0a
2017-03-01 00:01:56  INFO: [3D0B5B58] id: 867144027399623, time: 2017-03-01 00:01:53, lat: 47.60410, lon: 17.91074, speed: 0.0, course: 0.0`

The only thing in the wrapper log is the following:
`FINEST|2742/0|Service traccar|17-03-01 23:56:15|Wed Mar 01 23:56:15 CET 2017 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.`

This message keeps repeating itself but I don't think this is important at all. Also I am happy to give you access to the website if required.

**Comment by tananaev** [comment]
The problem is fixed.
