### ISSUE TITLE
Feature Request - SMS - Time Zone As per User set zone

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2969]
Hello,

Currently when a SMS is sent, the time displayed in the Message us 'UTC' which could be hard for some end-users to understand, and also confuse them.

Web-UI already displays the time as per the client time zone,. similarly for emails/sms etc can the admin and or user set his preferred time zone for the server or per user, based on which the time/date would be displayed in notifications etc.

**Comment by tananaev** [comment]
We would have to add timezone into user preferences.

**Comment by jaimzj** [comment]
It would be great to have this feature implemented, as it would benefit all users I feel.

**Comment by Abyss777** [comment]
@tananaev 
Lets discuss it a bit

- I think we should add `timezone` field to both `User` and `Server` model for consistence.
- How will we store it in DB? As string ID like "Asia/Yekaterinburg", "America/Los_Angeles", "UTC-08:00", "UTC+07:00" or as `int hoursOffset` or may be as `int millisOffset` something that supports http://www.joda.org/joda-time/apidocs/org/joda/time/DateTimeZone.html `for*` constructors. 
We should consider it carefully to allow easily set it in web-part.

**Comment by tananaev** [comment]
I think we should store it in the format supported by standard Java:

https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html#getTimeZone(java.lang.String)

There must be a way to list timezones on the JavaScript side as well. Maybe ExtJS has something.

**Comment by Abyss777** [comment]
I do not know what to do with `java.util.Date` and `java.util.TimeZone` in template. Velocity do not allow create objects like Apache POI:
`${new("org.joda.time.DateTime", event.serverTime, timezone).toString("YYYY.MM.dd HH:mm:ss")}`

Firstly I wanted to pass some proxy object in template (from standard) like `DateFormat` but format can be passed only via constructor.

If we had `event.serverTime` as `org.joda.time.DateTime` we could just do:
`$event.serverTime.withZone($timezone).toString("YYYY.MM.dd HH:mm:ss")` but... we need fully migrate to joda.time for that

another option is pass something like DateUtil and implement formatting function.

**Comment by tananaev** [comment]
We can have some helper method in the model to format the time. For example something like `getFormattedServerTime`.

**Comment by Abyss777** [comment]
It is for Event, but we will limit users in using templates, they may want use formated `$position.fixTime` or rest 2 "times"

**Comment by Abyss777** [comment]
I've found something http://velocity.apache.org/tools/devel/apidocs/org/apache/velocity/tools/generic/DateTool.html

**Comment by tananaev** [comment]
That looks like a better solution.
