### ISSUE TITLE
Traccar service cannot start (automaticaly stop) in MS Windows 

### ISSUE THREAD

**Issue by amzyoung** [tananaev/traccar#2976]
I've installed Traccar Server for Windows 10 but every time i start the service it automatically stop. How to solve this problem?

**Comment by gpproton** [comment]
It's b best you place it on delayed start So it's dependency which is database can start first.

**Comment by amzyoung** [comment]
Still the same problem.....

**Comment by tananaev** [comment]
You should check log files for errors.

**Comment by amzyoung** [comment]
i've reinstall it on windows server 2008 and it runs now.
