### ISSUE TITLE
Traccar+Mysql problem when positions more than 6mln records

### ISSUE THREAD

**Issue by romariogland** [tananaev/traccar#2977]
Hello!
There is a probem with build:
CentOS6 i386, i3-2130,4GbRam, MySQL 5.1.73/InnoDB, Traccar-3.10
If records count in tbl positions more than 6 mln, insert query becomes very slow. This can be seen in the result of the osmand script. Are there ways to improve performance?
PS The same problem was in builds: x64 Linux, 8GbRam, traccar-3.7....traccar-3.10
PS2 traccar web-service starts normally (but very slowly, 3-5 minutes aprox), but problem with performance is present. 
PS3 OpenGTS is installed In this server (but switched off), that has engine InnoDB and more than 75 mln records in EventData. It works normally and fast, if started.
Thanks

**Comment by tananaev** [comment]
That's a very old version of MySQL. I would recommend upgrading.

**Comment by romariogland** [comment]
[SOLVED]
It works fine! Config:
Centos 6.5/i386, i3-2130, 4GbRAM, Oracle JRE 8u121, MySQL-5.7.17 (installed on clear system)
Many thanks for help!
