### ISSUE TITLE
Can't add new devices

### ISSUE THREAD

**Issue by WalrusHat** [tananaev/traccar#2981]
I've got a VPS running a traccar server with the WEB UI mod from vitalidze. It seems I have hit some sort of limitation because I can not get the location updates from any device I have added recently. Currently there are about 1,000 devices on the system. I have taken the opportunity to update my `ulimit`  security settings  so that `ulimit -a` prints:
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 514772
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 10240
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 514772
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
however I am still unable to get information from the recently added devices. I have also added the `resetDelay` entry to `traccar.xml` however again to no avail. 

I have not restarted my full server, but I have restarted the traccar service.

I'm very confused as to what to do here because I can't add any more devices to my server. Please help.

Also, I am running the server on Ubuntu 15.

**Comment by tananaev** [comment]
Check this page:

https://www.traccar.org/optimization/

**Comment by WalrusHat** [comment]
Yup i did all of that but the devices a provisioned still aren;t reporting.

**Comment by tananaev** [comment]
Are you sure devices are functional? If there are no HEX messages in the log, it means that server doesn't received any data.

**Comment by WalrusHat** [comment]
They came online finally!!! I had the hard and soft limits set to 10240, but after I set them to 50000 everything came online!

**Comment by tananaev** [comment]
Good to hear. Closing the issue then.
