### ISSUE TITLE
Data Model Questions

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#2983]
1. Why does the **devices** table have a _groupID_ foreign key and the **users** and **geofences** tables use relation tables instead (i.e., **user_group** and **group_geofence**, respectively)?
2. Why does the **groups** table have a second (parent?) _groupID_ where the **users** table uses a relation table?  Is it because you want a strict hierarchical tree for groups?
3. If a device is managed by more than one _userID_, are notifications for a device sent to all users?
4. Can a _userID_ be managed by more than one _userID_?  What is an example use case for this?
5. When a _userID_ is managed by another _userID_, is the typical use case a manager having administrative access over the managed "readonly" users?
6. If devices, geofences, and users are all assigned to groups, why are the relation tables necessary for user_device and user_geofence?  What additional information is captured by these relations?

**Comment by tananaev** [comment]
1. To make it simpler we decided that device should have only one group. Also, originally the idea was to display it as a tree, so one parent would be easier to handle.
2. Same answer as above.
3. Yes, if those users enabled notifications.
4. I guess one organization can have several managers with access to user accounts.
5. Yes, but it doesn't have to be readonly.
6. Creating and assigning groups is an extra step. Most users don't even use them. I would imagine only companies with large number of devices would use groups.

**Comment by jon-stumpf** [comment]
I have multiple groups that are part of one parent organization.  There are departments in this organization that will have their own devices, geofences, and users.  I have a requirement that these departments cannot see each other's data.  Some special admins in the parent organization are permitted to see all departments and make modifications to department settings, membership, etc.

In your opinion, is it possible to implement the above use-case using the existing data model or must I extend the data model?

**Comment by tananaev** [comment]
I believe it is.

**Comment by tananaev** [comment]
Do you have more questions?

**Comment by jon-stumpf** [comment]
This is fairly long but I want to confirm with you first before I start any development.

**My Objective**
----
I have a hypothetical, 3-layer, hierarchical organization:
- Layer 1 (enterprise):  organization
- Layer 2 (division):  div-1, div-2, div-3
- Layer 3 (department): dpt-1a, dpt-1b, dpt-1c, dpt-2a, dpt-2b, dpt-2c, dpt-3a, dpt-3b, dpt-3c
All **divisions** report into the **organization**.  Each **division** has three **departments**.

A **user** in a **department** should only see entities also assigned to its **department** (and any subgroups defined).  An _admin_ **user** in a **division** should only see entities assigned to the **division** and any **departments** under it.  An _admin_ **user** in the **enterprise** can see everything.

**Test Implementation w/ Existing Data Model**
----
I have set up the 3-layer, hierarchical organization using groups.  I have created the groups (name[parent]) as follows:
- org []
- div-1 [org], div-2 [org], div-3 [org]
- dpt-1a [div-1], dpt-1b [div-1], dpt-1c [div-1]
- dpt-2a [div-2], dpt-2b [div-2], dpt-2c [div-2]
- dpt-3a [div-3], dpt-3b [div-3], dpt-3c [div-3]

All **divisions** have the **organization** as the parent group.  Each **division** has three **departments**.

Each department has five users - two admins and three readonly.  Each division has two users - both admins.  The organization has two users - both admins.  

Each department is assigned 10 devices each.  Each division is assigned 10 devices as spare inventory for departments under the division.. The organization is also assigned 10 devices as spare inventory.

**Observations and Questions**
----
When logged in as a departmental admin, I can:
1. See and edit users that are outside of my group using the Users screen.  I can also see geofences, devices, and groups that are outside of my group.  _Is this expected behavior?  Can I limit this with the existing data model?_
2. See only groups on the Groups screen that were created by myself.  _How can I see all geofences assigned to my group and its subgroups?_

**Comment by tananaev** [comment]
1. Admins are global. There is no way to limit it.

2. You can link groups to users. Admin can do it from the "Users" menu.

**Comment by jon-stumpf** [comment]
Given this, I should adjust my implementation as follows:
1. Only organizational administrators should have "admin" enabled.
2. Organizational administrator should create and assign all other users to appropriate groups.
3. Registration should be turned off.
Correct?

**Comment by tananaev** [comment]
I guess the easiest option is to have organizational admins create the whole hierarchy and assign users. It's also possible to assign users to another users (managers). @Abyss777 might be able to provide some more info on this.

**Comment by jon-stumpf** [comment]
I was just looking at the user assignment to users, to understand what capabilities this enables.  Was @Abyss777 responsible for the group concept?

**Comment by jon-stumpf** [comment]
There are 5 users in a group: 1-5.  I assigned user 1 to manage users 2-5:
`INSERT INTO user_user (userId, managedUserId)
    (SELECT '1', id FROM users WHERE id > 1 AND id <= 5);`

What capabilities does this enable?  I re-logged in as user 1 and see no ability to "manage" the users 2-5.

**Comment by Abyss777** [comment]
Hello, @jon-stumpf 
What should be able to do "admins" on the division and departments level?
May be "managers" will fit better to him?

Here is some explanations about  permissions https://www.traccar.org/documentation-user-management/

As for last question, have you set `userLimit` for "user 1" to 4?

**Comment by jon-stumpf** [comment]
I have reviewed the documentation.  Thank you for that.  I will attempt to use "managers" to see if this addresses the use case.

**Comment by jon-stumpf** [comment]
This will address my use case.  I do see opportunities for improvement in the data model but this may represent more change than would be acceptable to a point release.  My thoughts are the following:
1. The "group" would be the central entity instead of user.
2. Each group would have a list of managing user ids (not necessarily members of the group itself).
3. Groups would have users, devices, geofences, and calendars.
4. Entities can only relate to other entities that belong to the same group.
5. Group managers would be able to manage all entities within that group.
6. Individual users of a group would have read or read/write permissions for each entity type: users, devices, geofences, and calendars.
7. Groups could have a parent group (i.e., tree hierarchy).
8. Attributes could be attached to any group entity: users, devices, geofences, and calendars.
9. Subgroups can have inherited attributes of the parent at creation or in perpetuity (preferred).
a) Managers of parent groups may/may not manage entities of groups.
b) Entities of parent groups may/may not be available for use/reassignment to groups.
c) etc.

(1-8) would implement all the capabilities possible in the data model today while reducing the complexity and inconsistencies of the relationships in the model.  (9) would extend the capabilities.

I welcome your thoughts.

\- jss

**Comment by tananaev** [comment]
I don't think extending groups to contain users is a good idea. Currently groups represents a group of devices. Changing it would complicate a lot of things.

It might be a good idea to add user groups, but it would be a huge change.

**Comment by Abyss777** [comment]
IMHO there are a lot of things more related to device tracking worth to be implemented than inventing Active Directory inside traccar.

It might be more productive use some external framework like [Apache Shiro](https://shiro.apache.org/) or [OACC](http://oaccframework.org/) also It might solve some vital problems, like external authorization, password resetting and others.

**Comment by tananaev** [comment]
I agree with that. The whole permissions system already got a bit too complicated.

**Comment by jon-stumpf** [comment]
Thanks
