### ISSUE TITLE
Update 3.10

### ISSUE THREAD

**Issue by sms1515** [tananaev/traccar#2984]
Hello, after upgrading to version 3.10, the system is not starting with the version 3.9 database.
Note: System default database.
It is not compatible?
When installing starts normally, however, when replacing the database, the system no longer starts.

**Comment by tananaev** [comment]
It should work just fine. You should probably check logs for errors.

**Comment by sms1515** [comment]
log:
INFO|832/0|Service traccar|17-03-07 12:18:46|INFO 3/7/17 12:18 PM: liquibase: Waiting for changelog lock....

**Comment by tananaev** [comment]
Your database is locked, which means that you terminated the service during upgrade process. You would have to restore database from a backup and try again.

**Comment by sms1515** [comment]
So I did the way you said it, but the problem continues.

**Comment by tananaev** [comment]
It means that you created created backup after it was already locked. In this case you can either start from scratch, or manually go through the database and fix the schema.

**Comment by sms1515** [comment]
I returned to version 3.9 and it works normal, the error is only in version 3.10

**Comment by tananaev** [comment]
You are doing something wrong during the upgrade.

**Comment by sms1515** [comment]
Is there any news in this version 3.10?

**Comment by tananaev** [comment]
News?

**Comment by tananaev** [comment]
If you are asking if there is anything new (not "news"), then you should check blog:

https://www.traccar.org/blog/category/releases/

**Comment by sms1515** [comment]
How can I go through the database manually?

**Comment by tananaev** [comment]
Connect to the database, check Traccar changelog files and compare actual database schema to the changelogs.
