### ISSUE TITLE
Vehicle  false position when recorded history is uploaded to server

### ISSUE THREAD

**Issue by DanSkytrack** [tananaev/traccar#2988]
Hi there,
I  am testing Traccar using  Telic SBC-AVL as a tracking device. When  there is no GPRS/3G coverage, the device records the positions; when is back online, these recorded positions are uploaded to server.  During this  uploading period the vehicle is shown on the map   in the previous positions and the State panel shows corectly  this fact.   But there is no way to see where is  the current position, even the Device panel shows there is a recent update. Please see the attached image.
I am using version 3.10.
(This is my first post here... sorry if isn't the right place to place it)
![position false indicated](https://cloud.githubusercontent.com/assets/26308874/23764325/ceffd630-0505-11e7-99c0-6339cf59fd64.jpg)

Thanks

**Comment by tananaev** [comment]
Traccar always shows latest location by time. If it's old, it means that your device hasn't reported any newer location yet.

**Comment by DanSkytrack** [comment]
OK. Thank you. So _Last Update_ field in Devices panel shows the server time...
If so, this issue can be closed.

**Comment by tananaev** [comment]
Yes, it's server time.
