### ISSUE TITLE
TimeZone in Email Notification Is Wrong

### ISSUE THREAD

**Issue by muratcesmecioglu** [tananaev/traccar#2989]
Hi. I'm using Traccar with GT02 Gps tracker. I installed th server to my VPS and it works perfect.
But date and times in e-mail notifications are wrong.

Tracker's time is correct, my server's time is correct. And they are same. It's OK. I can see the times in log file and web-ui. I'm in GMT+3 but email says GMT+5

what is wrong?
I'm using Traccar3.10-Win

**Comment by tananaev** [comment]
I guess email uses server timezone. Is that correct?

**Comment by muratcesmecioglu** [comment]
In email template it uses $event.serverTime variable.

**Comment by tananaev** [comment]
Server doesn't know which timezone your user is, so it's formatted with server timezone. We would have to add timezone preference to user preferences to fix this issue.

**Comment by muratcesmecioglu** [comment]
I haven't got any experience about Java. Can i change the timesone from mail template?

**Comment by tananaev** [comment]
There must be a way to do it through templates as well.
