### ISSUE TITLE
traccar server websocket connection error 

### ISSUE THREAD

**Issue by amzyoung** [tananaev/traccar#2993]
My Traccar server running on windows server 2008 giving me this error "Web socket connection error". what should i do?
![error](https://cloud.githubusercontent.com/assets/10585370/23834188/23abf220-078d-11e7-8218-ee9a0888f22a.jpg)

**Comment by tananaev** [comment]
It means that WebSocket connection is failing for some reason. It can be a firewall blocking the connection, or one of many other reasons. If it's a corporate network, contact your IT department. They should know how to fix it.

**Comment by amzyoung** [comment]
it's my personal server for testing and i've already disabled all local and public firewall.

**Comment by tananaev** [comment]
Then there must be some other network issue. Are you connecting from outside network? Sometimes internet providers block it.

**Comment by amzyoung** [comment]
for now i'm using local network and client from my iphone fail to send update (client point to my server ip)... but when i using your  demo.traccar.org server, my iphone works.

**Comment by tananaev** [comment]
If you see sending errors in the Client app, then it means that the configuration is incorrect, or server port is not open.

**Comment by amzyoung** [comment]
i've made a new inbound rule for traccar and i open all ports for now... and it's running now...

tq sir!!!

**Comment by srinikandula** [comment]
Hi there I'm having the same exact error. The socket connection attempt(ws://traccar.srikrishnatravels.in/api/socket) is failing. I have added an inbound rule for port 0-9999. I still see this error. What could be wrong?

**Comment by tananaev** [comment]
Please don't comment on closed threads. You should check browser developer tools to find out more about the problem.

**Comment by NARASIMHA23** [comment]
check it http://unifymap.com

web socket connection error pop up raising.
what should i do, can any one help me.

**Comment by tananaev** [comment]
Please read my previous comment.
