### ISSUE TITLE
Millisecond information

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#2995]
There are currently 19 protocols that have a regex string that indicates the possibility for millisecond information.  Of these 19, only 9 protocols attempt to capture it.  Of these 9, only 3 capture it correctly.  L100, Pt502, and Trackbox all look for ".(ddd)" indicating that they expect millisecond information to always be present and capturing the 3 digits as an integer to be passed to DateBuilder.setTime().

Enfora, GpsGate, Gt30, Meligao, Riti, and Xexun all use ".(d+)" which may capture more or less than 3 digits and, therefore, set incorrect information (e.g., capturing "12345" would set 12,345 milliseconds).  And, GpsGate makes milliseconds optional (i.e., ".?(d+)?") but doesn't test for this condition (like Meiligao), always assuming that the data is present when calling DateBuilder.setTime().

I have attempted to correct the 6 protocols but the test data fails on some of them so I am reluctant to move forward without understanding this better.  Documentation is either not present or not specific enough.  Given the discrepancy, I think the best course of action is to make the 6 protocols optional (i.e., ".?d*") and not capture millisecond information - similar to Appello, HunterPro, Pt3000, Riti, and T55.  **_What are your thoughts?_**

Back to the 19 protocols, 12 protocols are GPRMC-based protocols.  The twelve have inconsistent methods to capture data.  **_Why is that?_**

**Comment by tananaev** [comment]
It's better to capture more information, so I'm not sure if removing it is a good idea. If optional parameter is missing, method would return 0, so it's handled fine.

Protocols have been developer in different time and possibly by different people, so of course there will be inconsistencies. Some inconsistencies are intentional. For example, some devices report GPRMC in exactly the same format, but some others have bugs in the implementation and server has to cater for that.

**Comment by jon-stumpf** [comment]
How should the potential bug be dealt with?  ".(d+)" can capture more/less digits than three.  Some protocols tests fail when I set it to ".(ddd)".

**Comment by tananaev** [comment]
What protocols fail?

**Comment by jon-stumpf** [comment]
I have quit coding for the day.  I will get that to you when I pick up again.

**Comment by jon-stumpf** [comment]
I have changed ".(d+)" to ".(ddd)" in Enfora, GpsGate, Gt30, Meiligao, Sanav, and Xexun.  Enfora, Meiligao, and Xexun all fail on binary tests. I can push the commit to my branch so that you can see it yourself.

**Comment by tananaev** [comment]
OK, for now let's drop milliseconds for those protocol that fail with ".(ddd)".

**Comment by jon-stumpf** [comment]
I will provide a commit in my current [pull request](https://github.com/tananaev/traccar/pull/2994) that implements this.

- jss
