### ISSUE TITLE
Hardcoded Timezones

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#2996]
There are three protocols that specifically set the timezone for the data capture of time:

1. Gnx (GMT+05:30)
2. Huabao (GMT+8)
3. Siwi (IST)

Is this correct?

**Comment by tananaev** [comment]
Should be correct. All those values are from official documentation.

I think those devices designed mostly for local market, so the timezone is hardcoded in the firmware to the country/area timezone.
