### ISSUE TITLE
Error in MD5 checksums

### ISSUE THREAD

**Issue by AravinthElangovan** [tananaev/traccar#3005]
while installing traccar-macos-3.10 in mac it shows an error called Error in MD5 checksums: d41d8cd98f00b204e9800998ecf8427e is different from bf7a8ddec10dc91618276bbeb1532592

**Comment by tananaev** [comment]
Where does it show the error? Have you tried downloading the installer again?

**Comment by kumareshsaran** [comment]
i am all so having the same error while installing traccar-macos 3.10 in mac 10.11.5 os..

**Comment by AravinthElangovan** [comment]
It showed in my terminal window and I have also tried newly downloaded file
![screen shot 2017-03-14 at 9 25 44 am](https://cloud.githubusercontent.com/assets/11457990/23885336/4b6706cc-0898-11e7-9914-224c69561303.png)

**Comment by tananaev** [comment]
Can I see the full output. Ideally in text format, not a screenshot.

**Comment by AravinthElangovan** [comment]
Susee-Mac-mini:traccar-macos-3.10 apple$ sudo chmod +x traccar.run
Password:
Susee-Mac-mini:traccar-macos-3.10 apple$ sudo ./traccar.run
Verifying archive integrity...Unknown option: n
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output
Error in MD5 checksums: d41d8cd98f00b204e9800998ecf8427e is different from bf7a8ddec10dc91618276bbeb1532592

**Comment by kumareshsaran** [comment]
Me too having the same error which is mentioned above

**Comment by tananaev** [comment]
Just tried on Mac 10.11.6. Works fine for me.

**Comment by tananaev** [comment]
What's the MD5 of the package itself? Mine is:
```
$ md5 traccar-macos-3.10.zip 
MD5 (traccar-macos-3.10.zip) = ca1b307ee53d54d13f3ad593ff00209d
```

**Comment by AravinthElangovan** [comment]
I'm also working on Mac 10.11.6 and my MD5 (traccar-macos-3.10.zip) = d41d8cd98f00b204e9800998ecf8427e

**Comment by tananaev** [comment]
Just tested on another Mac and the same hash as before. Where did you download the package?

**Comment by AravinthElangovan** [comment]
from here https://www.traccar.org/download/

**Comment by tananaev** [comment]
Just checked third time. Same correct hash sum as first time. I'm not sure how you get a different one. Possibly some network issue or some kind of malware on your computer. Have you tried re-downloading it? Try on a different computer.

**Comment by AravinthElangovan** [comment]
ok I'll try....

**Comment by AravinthElangovan** [comment]
I'm tried on another Mac too but it tells the same error

**Comment by tananaev** [comment]
On the same network? In that case the only explanation I can think of is that it gets modified somewhere on the way to your computer.

**Comment by AravinthElangovan** [comment]
ok... I will try....

**Comment by kumareshsaran** [comment]
i tried in different mac system.But i got the same error above mentioned.i have no idea to solve this problem

**Comment by tananaev** [comment]
Please try to download a version from SourceForce and see if it has the same problem:

https://sourceforge.net/projects/traccar/files/

**Comment by AravinthElangovan** [comment]
ok fine..... Successfully installed...

**Comment by AravinthElangovan** [comment]
But in my tracer client(android) not updating the location while my GPS is working good in google maps and I have turn on my data pack

**Comment by tananaev** [comment]
That's a different story. Please create a separate issue and provide as much information as possible. Also check following page:

https://www.traccar.org/troubleshooting

**Comment by AravinthElangovan** [comment]
It tells only the send failed message and my device is le 2 and asus zenfone 2 laser

**Comment by tananaev** [comment]
Related forum topic with some more details:

https://www.traccar.org/forums/topic/md5-checksum-error-when-downloading-3-11-macos-server/
