### ISSUE TITLE
 GT100 without ignition status

### ISSUE THREAD

**Issue by cadastro2005** [tananaev/traccar#3012]
The GT100 tracker is not passing the ignition status to the attribute property. =(

Only this information is being written to the gt100: 
```json
{"sat":12,"ip":"177.79.224.108","distance":2.72,"totalDistance":912790.62}
```

**Comment by tananaev** [comment]
For GL100 protocol only essential GPS data is supported at the moment.

**Comment by cadastro2005** [comment]
GL100 or GT100?

**Comment by tananaev** [comment]
Sorry, what's GT100? What protocol does it use?

**Comment by cadastro2005** [comment]
Uses the gt06 protocol

**Comment by tananaev** [comment]
Then it means that your device just doesn't send ignition info.

**Comment by cadastro2005** [comment]
Thanks for the support. ;D
