### ISSUE TITLE
Use of tcp keepalives

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#3028]
Hello

Does traccar use tcp keepalives for client connections? I have seen some trackers (mainly 3G LKGPS devices), which keep the connections open. This means the data connection never ends on the tracker, even if it doesn't send data. This uses more battery and also can increase costs if you are billed by connection/connection time. When I enabled the tcp keepalives OS wide, I didn't see this problem anymore.
I know this is probably a flaw in the implementation of the TCP stack on the tracker, but enabling keepalives shouldn't cause any issue and won't really increase server traffic.

**Comment by tananaev** [comment]
Traccar doesn't explicitly enable keepalive messages, but some many devices/protocols support special heartbeat messages to keep connection open.

**Comment by renaudallard** [comment]
What I meant is using setKeepalive(True) in SocketOptions

**Comment by tananaev** [comment]
I know. As I said, Traccar doesn't do it. Possibly Netty library does it internally, but it's unlikely.

**Comment by renaudallard** [comment]
Netty indeed doesn't do it by default.
It's described here: http://netty.io/wiki/user-guide-for-4.x.html
