### ISSUE TITLE
Split Configuration

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#3031]
The behavior of traccar currently models the current state in memory, treating the database as a backing store.  This requires both the management of the devices and the management of the connected users to be performed by the same server (i.e., there can only be one server).

Is it possible to have multiple traccar servers running:
1. some managing devices, the number dictated by the number of devices under management;
2. some managing web connections, the number dictated by the number of concurrent users;

where the database is the real-time store of information?

\- jss

**Comment by tananaev** [comment]
Using database for everything would significantly slow down the server. For example, groups hierarchy would need to be calculated every time.

As for horizontal scaling that you are talking about, I think it's better to have some kind of "load balancer" that would forward request to a server that's responsible for particular subset of users/devices.

**Comment by jon-stumpf** [comment]
So, partition users and devices using the load balancer.

**Comment by tananaev** [comment]
Yes, that's what I was thinking is the easiest solution.
