### ISSUE TITLE
Use of Geospatial datatypes

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#3032]
Have you considered using geospatial datatypes and associated functions (e.g., geofence calculations) now that they are standard fare in Hibernate5 and most modern databases?

\- jss

**Comment by tananaev** [comment]
It's not a standard and it's not available in all databases. At this point it doesn't make much sense to use any indexes like that. Geofences are linked to devices, so I don't expect a single device to have more than say 100 geofences. Even 100 is probably much more than most users would have. With such low numbers, it's easier and probably faster to just iterate through all geofences.
