### ISSUE TITLE
Connect to existing mySQL DB

### ISSUE THREAD

**Issue by viveklivingstone** [tananaev/traccar#3037]
How Can I connect a new traccar installation to an existing mySQL server?

**Comment by tananaev** [comment]
Here is the documentation:

https://www.traccar.org/mysql/

**Comment by viveklivingstone** [comment]
To be more specific, the server in which the traccar is installed has crashed and I had to make a fresh deployment.
MySQL database was on another server. Now I want to connect the new traccar server to the previous database. While starting, it is showing that the tables exists. Will it be possible to use the old database as it is?
Any configuration change I have to make?

**Comment by viveklivingstone** [comment]
Got the answer from another thread...  Remove “database.changelog” from the config.
https://www.traccar.org/forums/topic/stop-creating-table-when-start-traccar-server/ 
Thank you :)
