### ISSUE TITLE
Markers every 3 or 5 seconds

### ISSUE THREAD

**Issue by RobertoVillegasA** [tananaev/traccar#3038]
Hello Anton
First say congratulation for Traccar.
My question. Is possible get markers every 3  or 5 seconds actually markers are every 10 seconds but is not 
Enough for my I need marks  between, looks better in tracking report.

Regards.

**Comment by tananaev** [comment]
I don't understand the question. How is it related to Traccar server? Your device controls report frequency.

**Comment by RobertoVillegasA** [comment]
I want to improve the visualization of the tracking each mark is very separated so some streets are specifically skipped when touring, there is some way to do it from the tractor server or it must be in the device (frequency of sending data to the server 10 seconds minimal option)

**Comment by tananaev** [comment]
Have you actually thought before asking this question? If the minimal reporting frequency of your device is 10 seconds, how would server get location more frequently than that?

**Comment by RobertoVillegasA** [comment]
sorry... about that..... my mistake
