### ISSUE TITLE
Mail Alert - Velocity

### ISSUE THREAD

**Issue by hceccacci** [tananaev/traccar#3041]
There is a way to input the value of velocity into the text message?
Today, the default message don´t include this information.
Thanks!

**Comment by tananaev** [comment]
You can modify template.

**Comment by hceccacci** [comment]
Please, can you indicate what is necessary to do in the file?
The default content is:

#set($subject = "$device.name: exceeds the speed")
#if($speedUnits == 'kmh')
#set($speedString = $position.speed * 1.852 + ' km/h')
#elseif($speedUnits == 'mph')
#set($speedString = $position.speed * 1.15078 + ' mph')
#else
#set($speedString = "$position.speed kn")
#end
<!DOCTYPE html>
<html>
<body>
Device: $device.name<br>
Exceeds the speed: $speedString<br>
Time: $event.serverTime<br>
Point: <a href="$webUrl?eventId=$event.id">#{if}($position.address)$position.address#{else}$position.latitude&deg;, $position.longitude&deg;#{end}</a><br>
</body>
</html>  

Thanks!

**Comment by tananaev** [comment]
That's an email template and it already has speed value.

**Comment by hceccacci** [comment]
I will check, Thanks!

**Comment by hceccacci** [comment]
The system is sending only the alert message:

De: alertas@mydomain.com [mailto:alertas@mydomain.com.br] 
Enviada em: quinta-feira, 23 de março de 2017 14:19
Para: andre@clientdomain.com.br
Assunto: FTS5815: alarm!
 
Device: FTS5815
Alarm: overspeed
Point: 758 SP-330, SP, BR
Time: Thu Mar 23 14:19:12 BRT 2017

But the all the notifications are selected.
![image](https://cloud.githubusercontent.com/assets/26606118/24274165/5615759e-1005-11e7-9b6d-ebead4c7754f.png)

Can you help-me?
Thanks!

**Comment by tananaev** [comment]
What other notifications are you expecting? Provide some evidence that it happened.

**Comment by hceccacci** [comment]
The system is sending only the alert email, the velocity email it is not been sent.

**Comment by tananaev** [comment]
Have you configured speed limit?

**Comment by hceccacci** [comment]
Only in the device. Where should I do this in system?

**Comment by tananaev** [comment]
Please provide a screenshot of the speed limit.

**Comment by hceccacci** [comment]
Sorry, but where I setup this in Traccar?

**Comment by tananaev** [comment]
You said that you set it for device. Please provide a screenshot of where you set it.

**Comment by hceccacci** [comment]
Sorry again!
I´ve find the way to configure per device. The issue #2572 solve this question.
Thank you Tananev!

**Comment by Turbovix** [comment]
@hceccacci You need to set the maximum speed you want in device attributes!

![image](https://cloud.githubusercontent.com/assets/3914126/24276575/69614112-1016-11e7-99f9-4a5bccbf47a6.png)

**Comment by tananaev** [comment]
@hceccacci, please clarify what you meant by "Only in the device" comment earlier? The comment implies that you already configures speed limit for the device. Am I missing something?

**Comment by hceccacci** [comment]
Yes! I had not understood where to put the parameters. Sorry for bringing such a basic doubt and take your time with this.

**Comment by hceccacci** [comment]
@tananaev, I was configured only in the hardware device, not in the item device in Traccar. But now I learned! Thanks!
