### ISSUE TITLE
Websocket issue with custom monitoring app

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#3051]
Hi @tananaev,

I tried to use https://github.com/tananaev/traccar-web/tree/master/web/simple for monitoring purpose by different users (in my case fleet supervisors Ex: FS1, FS2 and so on).

Steps to reproduce:
1. Login to FS1 and click on map button and it will open new window with map with devices of FS1.
2. Close the map window.
3. Logout and Login to FS2 and click on map button and it will open new window with map, now it still   
    shows FS1 devices.

Please let me know how to fix it in app.js file.

Thanks.

**Comment by kirantpatil** [comment]
Please find the screenshot where the socket is still listening of previous session.

![screenshot from 2017-03-24 18 36 16](https://cloud.githubusercontent.com/assets/1178055/24295501/023932dc-10c1-11e7-8411-6821814b7cdc.png)

**Comment by tananaev** [comment]
You can't login with two different users in the same browser.

**Comment by tananaev** [comment]
I guess you are still logged in as a first user.

**Comment by kirantpatil** [comment]
No Sir, I am logging out of FS1 user and logging in to FS2 user.

On Mar 25, 2017 2:54 AM, "Anton Tananaev" <notifications@github.com> wrote:

I guess you are still logged in as a first user.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tananaev/traccar/issues/3051#issuecomment-289146519>,
or mute the thread

**Comment by tananaev** [comment]
How do you logout and login?

**Comment by kirantpatil** [comment]
Sir, app login with FS1 user will pass token specific to it to map window.
I logout and login as FS2 user and I pass again token of FS2 user while
opening map window.

**Comment by tananaev** [comment]
How exactly did you logout?

**Comment by kirantpatil** [comment]
Sir, I logout from rails app.

**Comment by tananaev** [comment]
So, how do you know the problem is not with your code? If you think there is a problem with Traccar, I need steps to reproduce it with original Traccar.

**Comment by kirantpatil** [comment]
I will upload the code and share link.

**Comment by kirantpatil** [comment]
Sir, please find the screenshots below, if I try to use  token to login user f12@gmail.com, it is still getting f11@gmail.com user details in the session.

f11@gmail.com token is 500763a1d2825c26836f.
f12@gmail.com token is 167a6805ef424c03dc82.

Do I need to delete session or set cookie for each session in app.js code?

![screenshot from 2017-03-27 13 40 38](https://cloud.githubusercontent.com/assets/1178055/24346739/5381f76c-12f3-11e7-8386-ff653c9eab01.png)

![screenshot from 2017-03-27 13 39 18](https://cloud.githubusercontent.com/assets/1178055/24346744/595d6400-12f3-11e7-8b39-4ba234ab9587.png)

**Comment by tananaev** [comment]
That's why I asked how you logged out. I don't see any logout calls.

**Comment by kirantpatil** [comment]
I do logout from my main app. I donot use any logout specific to traccar.

**Comment by tananaev** [comment]
So, you don't logout from Traccar? Not sure why you expect session to change in that case. That's not how it works. You need to logout before you can login again.

**Comment by kirantpatil** [comment]
Sir, I modified the app.js code to use google and my main app is Rails.

Please find the code here https://gitlab.com/snippets/1656049.

1. When a user logs in and clicks on "View_map" button it opens a new window and tracker.js file loads google map and markers on that window.

2. I logout from rails app and login as another user where I get his token and try to open the  map. It is here that session is getting the previous user details.

Hope I clarified the login and logout process.

Please let me know if you need more information.

I hope now we nailed the issue here.

**Comment by tananaev** [comment]
Well, it means that you are doing something wrong in your rails app.

**Comment by kirantpatil** [comment]
I am sending only logged in user token to tracker.js and rest of the rails app is not touching the traccar in any way.

**Comment by kirantpatil** [comment]
I get from rails only below two details, as shown in the https://gitlab.com/snippets/1656049.

var url = gon.live_url; 
var token = gon.user_token;

**Comment by tananaev** [comment]
Then you should probably read my previous comment more carefully.

**Comment by kirantpatil** [comment]
I guess you mean by "I guess you are still logged in as a first user."

How should I close previous user, who is logged in using token and API  shown below?
    ajax('GET', url + '/api/session?token=' + token, function(user)

**Comment by kirantpatil** [comment]
Found answer [here](https://www.traccar.org/forums/topic/commands-api-help-needed/).

```
public static function logout($cookie) {
                return self::curl('/api/session', 'DELETE',$cookie ,'',array('Content-Type: application/x-www-form-urlencoded'));
    }
```
Thanks for pointing me in the right direction.

**Comment by kirantpatil** [comment]
@tananaev, I am yet to implement the feature using cookie as shown above comment. Meanwhile please let me know if there is a way to logout using API.

Thanks.

**Comment by tananaev** [comment]
Hmmm... the example from your previous comment is the logout API.

**Comment by kirantpatil** [comment]
Right now I am doing as below.

ajax('GET', url + '/api/server', function(server) {
  ajax('DELETE', url + '/api/session?token=' + token , function(user) {
    ajax('GET', url + '/api/session?token=' + token, function(user) {

But I am getting below issue as shown in screenshot, where it is asking me to enter username and password.

I believe if we could DELETE session before creating new one using token, may resolve our issue.

![screenshot from 2017-03-28 11 50 42](https://cloud.githubusercontent.com/assets/1178055/24391485/06f164b8-13ad-11e7-9951-cce12060eb87.png)

**Comment by tananaev** [comment]
You can't remove a session if you don't have a session.

**Comment by kirantpatil** [comment]
Then how to close the session which is opened using token as below ? So that subsequent session GET requests should not fetch the same user details.

 ajax('GET', url + '/api/session?token=' + token, function(user)

**Comment by tananaev** [comment]
You can find API documentation here:

https://www.traccar.org/traccar-api/

**Comment by kirantpatil** [comment]
Sir, I have gone through it.

**Comment by tananaev** [comment]
Then you should know how to remove existing sessions (logout).

**Comment by kirantpatil** [comment]
We are now creating proper session and deleting it on logout, as below.

$.ajaxSetup({
    crossDomain: true,
    xhrFields: {
        withCredentials: true
    }
  });

$.post(url + '/api/session', {email: email, password: password })
   .done(function(data){
      $.get(url + '/api/session').done(function(data){
        ajax('GET', url + '/api/devices', function(devices) {
...
...

Thanks.
