### ISSUE TITLE
Old Traccar protocol doubt

### ISSUE THREAD

**Issue by andrescor** [tananaev/traccar#3065]
Hello,

I am working on a project that involves using Traccar. I have a GPS module that remotely sends its position (NMEA frame) to a PC. There, the NMEA frame is parsed and turned into old Traccar protocol format (https://www.traccar.org/traccar-client-protocol/). Then I want this PC to act as a server and send the Traccar information to another PC, that would be the client. 

For only one GPS I believe I understand it. I send the "Login" first and then keep sending the GPRMC sentences. But what if I want to connect 2 (or more) GPS to the "PC server"? Should I send 2 dofferent Logins? And then? How would I associate each GPRMC sentence to its respective ID? 

Thank you.

Andrés

**Comment by tananaev** [comment]
Traccar Client protocol is based on TCP connections. Every device opens a separate connection and at the beginning of every connection it sends its id, so there is no problem with identification.

P.S. Please don't duplicate your messages on GitHub and over email.
