### ISSUE TITLE
Front-end Applications Reconnect

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#3068]
When the traccar server restarts, the devices will (generally) reconnect automatically to the server to send information.  Is there a way for the web and mobile applications to automatically reconnect so that notifications are not missed?

**Comment by tananaev** [comment]
I guess technically it's possible with saved login, but web app doesn't re-login automatically at the moment.

**Comment by jon-stumpf** [comment]
I would think that it would be simplest for the applications to attempt to re-login rather than the server to preserve and recreate sessions.  Front-end applications are not my forte.  Can you suggest a few design choices that I could consider?  Or, is this something you could take on?

**Comment by tananaev** [comment]
I was not talking about server side.

I have just implemented page reload in case of authentication error:

https://github.com/tananaev/traccar-web/commit/47eff075095604afa7405993ce2d7b4ae29fc939

Basically it would return user to the login screen after restart.

**Comment by jon-stumpf** [comment]
Thanks.  I will look into it.

**Comment by jon-stumpf** [comment]
Is it possible to contribute to traccar-web/ without a license from Sencha?  I use NetBeans for my IDE.

- jss

**Comment by tananaev** [comment]
We use open source version of Sencha. You don't need to have any license to use it.

**Comment by jon-stumpf** [comment]
Thanks.  I just requested a copy.

**Comment by jon-stumpf** [comment]
Sorry to keep reopening this issue but, as I said, front-end applications are not something I do regularly.

Do you have instructions on how to appropriately add the ExtJS libraries to NetBeans so that I can mark them as a dependency for the traccar-web project?

**Comment by tananaev** [comment]
No, I don't know.

**Comment by jon-stumpf** [comment]
Thanks.
