### ISSUE TITLE
Traccar 3.10 - Not receiving any data

### ISSUE THREAD

**Issue by jsimunic** [tananaev/traccar#3074]
Hello @tananaev, I am trying to get Traccar Server 3.10 running on my work machine (the PC is Lenovo Thinkpad T60 with win7) and sending my location from my Android smartphone (Gsmart Roma R2) with the Traccar Client app, the Traccar Server starts up fine, using the default configuration conf/traccar.xml, I can access the web interface, register/login, create a new device. The Traccar Client app on my Android device is also running fine, but when I create a new device with a new identifier (the one that the Traccar Client provides me with) the Traccar Server never gets any GPS data. I inspected the Traccar Client HTTP GET requests and they seem fine to me (latitude, longitude, bettery level parameters are accurate).
My installed Java version:
![image](https://cloud.githubusercontent.com/assets/24455448/24794767/32ed7278-1b87-11e7-95a9-1e70588fd98e.png)
Traccar server manual start log:
![image](https://cloud.githubusercontent.com/assets/24455448/24794844/78883b9c-1b87-11e7-8992-0dbbd9dc175c.png)
Traccar server wrote down three log files (for each of the days i tried to get it running) and only one log file has some data in it, I am attaching the file here (converted to .txt):
[tracker-server.log.20170406.txt](https://github.com/tananaev/traccar/files/905193/tracker-server.log.20170406.txt)

Traccar Client HTTP GET request:
![image](https://cloud.githubusercontent.com/assets/24455448/24795608/2d8fb8e2-1b8a-11e7-9e88-a762700f6f05.png)

Edit: 
I tried to connect my Android device to demo4.traccar.org and it works, so I assume that the problem is with my PC/local network, my firewall is off, I have Avast Free Antivirus installed.

My question/issue is could you explain what could be wrong with this? Should i try an older version of Traccar Server?

**Comment by tananaev** [comment]
Correct port for Traccar Client is 5055. Why are you using port 8081?

**Comment by jsimunic** [comment]
I used port 8081 just to inspect the GET request from the Traccar Client (I inspected it with echotool
[https://github.com/PavelBansky/EchoTool](url) ), but the Traccar server runs with default configuration, meaning it is sitting on port 8082, right?

**Comment by tananaev** [comment]
Default port for Traccar Client is 5055. Port 8082 is ONLY for web interface. Those are two completely different ports.

**Comment by jsimunic** [comment]
That solved the problem, thank you. Didn't dig through the config file, sory about that.  On the Quick Start page it says that Traccar starts automatically when the OS boots up, but on my machine it doesn't, probably some Windows issue, would it be good to start Traccar through a startup script (batch file)?

**Comment by tananaev** [comment]
On Windows you should check Traccar config in the services menu. There is an option to make it auto-start.

**Comment by jsimunic** [comment]
![image](https://cloud.githubusercontent.com/assets/24455448/24908908/343bf86e-1ec2-11e7-879c-3a0ab46a60be.png)
The picture above shows my current configuration of Traccar, it seems to me that it already is configured to start automatically, but it doesn't, am I wrong?

**Comment by tananaev** [comment]
It should start. Have you checked server logs?

**Comment by jsimunic** [comment]
The PC had a faulty network adapter, thanks anyway!
