### ISSUE TITLE
Help needed for Spring boot framework

### ISSUE THREAD

**Issue by parveenkumardeeva** [tananaev/traccar#3078]
Hi, can we use your code into spring boot framework and if yes then any specific guidelines?

**Comment by tananaev** [comment]
Traccar does not use Spring, so I'm not sure why you would want to use Spring Boot. Traccar is already stand-alone application on its own.

**Comment by parveenkumardeeva** [comment]
Yeah tananaev I know, but I am working from scratch with spring boot framework and using mongodb as a db , merged your code into my own code because I needed more functionalities.
Successfully merged but not able to open all ports for capturing devices data.

So, Is there any way to open ports in Spring boot?

**Comment by tananaev** [comment]
I am not familiar with Spring Boot, so I won't be able to help.

**Comment by parveenkumardeeva** [comment]
Ok thanks tananaev :)
