### ISSUE TITLE
Linux - conection not finished

### ISSUE THREAD

**Issue by RaulBernal** [tananaev/traccar#308]
I note with the 'client' not free the conection when finish it:

netstat -ant

tcp6       0      0 :::5022                 :::*                    ESCUCHAR
tcp6       0      0 192.168.0.252:5005      84.124.203.14:58169     ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:47686    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:48242    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:52876    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:57800    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:34285    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:56329    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:45318    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:58932    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:59907    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:49678    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:46196    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:53935    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:43900    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:55231    ESTABLECIDO
tcp6       0      0 127.0.0.1:37834         127.0.0.1:3306          ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:43964    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:57041    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:40663    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:59653    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:49282    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:38218    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:48180    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:50132    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:34697    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:45412    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:41959    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:56534    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:38220    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:54820    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:50950    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:49477    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:52825    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:49591    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:46869    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:45268    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:42505    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:50514    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:34493    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:50298    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:57097    ESTABLECIDO
tcp6       0      0 192.168.0.252:8082      81.231.167.145:1868     FIN_WAIT2
tcp6       0      0 192.168.0.252:5001      32.4.244.231:29524      ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:59190    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:36342    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.124.203.14:59731     ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:58899    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:56920    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:37556    ESTABLECIDO
tcp6       0      0 127.0.0.1:37836         127.0.0.1:3306          ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      32.4.206.65:43882       ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:44828    ESTABLECIDO
tcp6       0      0 192.168.0.252:8082      64.237.55.3:34400       TIME_WAIT
tcp6       0      0 192.168.0.252:5005      84.221.233.253:44703    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:57055    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:34250    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:49392    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:44605    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:41822    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:39324    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      32.4.203.193:41896      ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:49673    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:51459    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:46017    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      32.4.202.103:45958      ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      95.169.242.249:25154    ESTABLECIDO
tcp6       0      0 127.0.0.1:37903         127.0.0.1:3306          ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:39979    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:46893    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:33675    ESTABLECIDO
tcp6       0      0 192.168.0.252:8082      95.169.243.208:23107    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:36882    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:49927    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:52146    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:38196    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:39826    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:50884    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:48383    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:35777    ESTABLECIDO
tcp6       0      0 192.168.0.252:5001      32.4.244.202:17632      ESTABLECIDO
tcp6       0      0 127.0.0.1:31000         127.0.0.1:32000         ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:55100    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:34890    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:40811    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:36290    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:40354    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:45510    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:53985    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:33452    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:34863    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:45728    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:54672    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:40538    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      32.4.204.32:2490         ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:40451    ESTABLECIDO
tcp6       0      0 192.168.0.252:8082      81.231.167.145:2461     ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:59383    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:50491    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:41437    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:40692    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:54917    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:50108    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:49811    ESTABLECIDO
tcp6       0      0 192.168.0.252:5005      84.221.233.253:36544    ESTABLECIDO

Thank's, very good job!

**Comment by tananaev** [comment]
The only possible solution is to use `resetDelay` or change connection timeouts on the OS level.
