### ISSUE TITLE
TK228 OBD Distance Report - Inaccurate 

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#3086]
Dear @tananaev  

Device : TK 228 OBD
Protocol : meiligao  
Port : 5009

When the vehicle travels, the distance report is always wrong.

Problem : Device has traveled over 25km+ in about 40 Minutes. However In Summary the distance shown is 0.03km.

And in trips also the same. 0.03km.

Report->Route-> option shows the markers and route properly with perfect tracking path.
However distance calculations are wrong, 

Please advice what specific Log/Record would you require from my end to help identify the issue,.  If you would require I can point the device to demo server as well, or provide you access to my server.

**Comment by tananaev** [comment]
Does your device report odometer value? Is it correct?

**Comment by jaimzj** [comment]
Yes it does report odometer value, and its correct.

**Comment by tananaev** [comment]
OK, then do a route report and compare odometer values in the first and last positions.

**Comment by jaimzj** [comment]
The following are the odometer value.

Start Point : odometer 0.20 km
End Point : odometer 0.02 km

Extra values as well sharing from the first and last positions.
Distance value : 0.00km (for both start point and end point)

Start Point : Total Distance : 210.16km
End Point : Total Distance 245.13km

**Comment by tananaev** [comment]
OK, so your device clearly reports incorrect odometer value. You can try this parameter:
```xml
<entry key='report.ignoreOdometer'>true</entry>
```

**Comment by jaimzj** [comment]
Sure I shall try that configuration parameter.

I would like to add one thing here, the odometer value in the first and last point is wrong, however the odometer value in the last updated position id entry is correct. Does that mean? its a device specific issue?

**Comment by tananaev** [comment]
If you see wrong odometer value, it's a device issue.

**Comment by jaimzj** [comment]
Thank you @tananaev  :) for guiding me to the root cause, I have taken it up with the manufacturer and also `report.ignoreOdometer` has worked 👍
