### ISSUE TITLE
Help me with db Traccar-Server

### ISSUE THREAD

**Issue by proyntec** [tananaev/traccar#3096]
Hi, I am new in this and I need help with any problems with upgrade installation of traccar server. my problem is that icon of my device no show ,  and the log say the problem
```
 WARN: Column count does not match; SQL statement:
INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); [21002-194] - JdbcSQLException (... < QueryBuilder:58 < *:135 < DataManager:293 < DefaultDataHandler:27 < ...)
```
I dont create db and dont know how.

please can you help me. note: sorry for english idiom but I speak and write only spanish,

**Comment by tananaev** [comment]
Traccar creates database schema automatically. I guess you did something wrong, but without any information on what you did, there is no way to tell what the problem is.

**Comment by tananaev** [comment]
Are you sure you are using official version without modifications? It seems like you at least modified config file.

**Comment by proyntec** [comment]
I try upgrade the version modified with google maps traccar GUI

**Comment by tananaev** [comment]
What version?

**Comment by proyntec** [comment]
http://traccar.litvak.su/installation.html

I have you version 3.11 and try upgrade to 3.8 of traccar.litvak.su

**Comment by tananaev** [comment]
That's not an official Traccar project, so you should ask on the project issue tracker, not here. Also, I don't think you can easily migrate between two.
