### ISSUE TITLE
Unwired geocoding help

### ISSUE THREAD

**Issue by evilforest** [tananaev/traccar#3098]
I'm trying to set up unwired reverse geocoding.
Added lines to traccar.xml:
```
<entry key='geocoder.enable'>true</entry>
<entry key='geocoder.type'>unwired</entry>
<entry key='geocoder.url'>https://unwiredlabs.com/v2/search.php?accept-language=ru</entry>
<entry key='geocoder.key'>xxxxxxxxxxxxx</entry>
```
Traccar starts but gives out addresses in English.
I tried this:
`<entry key='geocoder.url'>https://unwiredlabs.com/v2/search.php?accept-language=ru,token=xxxxxxxxxxxxx</entry>`
Addresses are still in English.
Later tried like this:
`<entry key='geocoder.url'>https://unwiredlabs.com/v2/search.php?token=xxxxxxxxxxxxx&accept-language=ru</entry>`
& this:
`<entry key='geocoder.url'>https://unwiredlabs.com/v2/search.php?accept-language=ru&token=xxxxxxxxxxxxx</entry>`
And traccar did not start with errors.
When I make an address request in the unwired dashboard, I get this result:
```
{
    "status": "ok",
    "balance": 10000,
    "address": {
        "house_number": "10 с4",
        "road": "Большая Тульская улица",
        "suburb": "Даниловский",
        "city": "Danilovsky District",
        "county": "Southern Administrative Okrug",
        "state": "Moscow",
        "postcode": "115191",
        "country": "Russian Federation",
        "country_code": "ru",
        "display_name": "10 с4, Большая Тульская улица, Даниловский, Danilovsky District, Southern Administrative Okrug, Moscow, 115191, Russian Federation"
    }
}
```
And this is exactly what I want.
The official documentation says the following:
**HTTP Request**
`GET https://unwiredlabs.com/v2/search.php?token=YOUR_API_TOKEN&lat=LATITUDE&lon=LONGITUDE`
Query Parameters:
```
token
lat
lon
zoom
accept-language
```
**Accept Language**
Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Either uses standard rfc2616 accept-language string or a simple comma separated list of language codes.
**Country Codes**
Limit search results to a specific country (or a list of countries). Should be the ISO 3166-1alpha2 code. Here is a sample:
Country code:
```
de    Germany
gb    United Kingdom
us     United States of America
```
Tell me please, do I configure the reverse geocoding correctly from this provider?
And how to get the traccar to request addresses in other languages?

**Comment by tananaev** [comment]
It looks similar to Nominatim provider. That's why it works, but it doesn't take extra parameters in the URL.

**Comment by evilforest** [comment]
And is there a way to request these parameters?
How the traccar makes a request to the server that he answers it in English.
My server is running on windows server 2012r2 and for me the big problem is to install my geo server, because the gisgraphy requires money to download maps, photon works but it does not supported the tracсar and for nominatim need to run a virtual machine.
It turns out that on windows there are no normal ways to receive free reverse geocoding without launching a virtual machine?

**Comment by tananaev** [comment]
I don't follow your logic. Is Unwired a free service?

As for parameters, at the moment you can add anything extra only by changing the code.

**Comment by evilforest** [comment]
I just got it for a very small amount.
And there is then the opportunity to implementing support for photon?
In this post https://www.traccar.org/forums/topic/photon-support/ you said that adding his support is fairly easy.

**Comment by tananaev** [comment]
Added support for language parameter.

**Comment by evilforest** [comment]
Thanks a lot for your help.
