### ISSUE TITLE
Date headers in the emails

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#3103]
Hello,
It seems some mail providers are putting traccar emails in spam (or rejecting them) because they are missing the DATE: header field.
Also, it seems to cause issues with some email client which is unable to tell when the mail has been sent and thus use the date of the fetch as the display date.
Maybe it would be a good idea to add a message.setSentDate in NotificationMail.java

Regards

**Comment by tananaev** [comment]
How do you know that it's marked as spam because of the date.

**Comment by Abyss777** [comment]
I see the Date header in mails received from traccar

**Comment by renaudallard** [comment]
@tananaev because I know it's a standard spamassassin rule
@Abyss777 your server might add it automatically when sending

Besides that, on RFC2822 3.6:
The only required header fields are the origination date field and
   the originator address field(s).  All other header fields are
   syntactically optional

**Comment by renaudallard** [comment]
Even only technically speaking, this is a very small change and it makes the message RFC2822 compliant.
Also, with thunderbird, if you receive multiple mails at different times of the day, given they do not have a Date: header, it looks like the attached picture.
![snapshot9](https://cloud.githubusercontent.com/assets/478410/25279182/ec513f1e-26a5-11e7-8c3f-47cf35a5bc30.png)

**Comment by tananaev** [comment]
I have merged the code. Thanks for pull request.
