### ISSUE TITLE
All devices command send and change time of reporting

### ISSUE THREAD

**Issue by djbo1982** [tananaev/traccar#3105]
Hello @tananaev @Abyss777 

I want to know is possible send command to all devices at same time.

I ask this, because i want to change the periodic reporting time to all my devices, or change the server Ip to migrate, or send some update.

By the way, i want to know is possible to change the reporting time when the device change the status from ON to OFF, this for reduce the latency of the car battery or GPS internal Battery, because when the car is ON, we used the power of the altenator of the car, but when the car is OFF, we use the CAR Battery, and when the car battery is DOWN, we used the internal GPS Battery, in 10 second report the battery down to fast. I think is a good idea to can have this, because is the car stop, we don´t need to much reports of the device positions, only when the device is on the way

Can we?

**Comment by tananaev** [comment]
You can use API and write a simple script to send commands to all devices.
