### ISSUE TITLE
User tree view feature

### ISSUE THREAD

**Issue by djbo1982** [tananaev/traccar#3106]
Hello @tananaev @Abyss777 

Some time ago, i see in one open Issue some body are developing the TREE view for user and group list,

That will be great to have this User tree view to can handle and know better the car and the level of the user.

For example, to add a new user to another user can we select the all ready registre user and select ADD, and when we finish, we can have the tree view. 

Maybe we can integrate this feature in next release.

Thanks for all your work... Your project make our life better

**Comment by tananaev** [comment]
As far as I know, there was never a tree of users. There was a tree for devices.

**Comment by djbo1982** [comment]
Ok, this is my image...

To can see better the car, we can select to expand or select to retract the user, and inside the user are the GPS devices

Is possible to add this feature?

[Rigth manager.pdf](https://github.com/tananaev/traccar/files/945980/Rigth.manager.pdf)

**Comment by tananaev** [comment]
That looks like a tree of devices, not users.

**Comment by djbo1982** [comment]
Well @tananaev ... User with they devices... 

Can we have this?

**Comment by tananaev** [comment]
There are already groups for devices, but there is no plan for adding tree view because there were many issues with it in the past. You can try to find the code in one of the pull request and try it yourself if you want.
