### ISSUE TITLE
Not delete the older unit from database

### ISSUE THREAD

**Issue by medveczki** [tananaev/traccar#3108]
Hi,
I would like to delete an older unit from database but the system isn't delete this unit from database.
I use V3.11. This problem was not in 3.10.
Can You help me?

Zoltan

**Comment by medveczki** [comment]
Now is correct. If I fill all field and renew the database the system is enabled this file deleted.
Thanks, and sorry.

**Comment by tananaev** [comment]
The issue is already fixed in https://github.com/tananaev/traccar-web/issues/471.
