### ISSUE TITLE
MariaDB support deprecated?

### ISSUE THREAD

**Issue by QROkes** [tananaev/traccar#3114]
I can't find it in the documentation page.
Seems like its not supported anymore. 👎

**Comment by tananaev** [comment]
There was never a separate documentation for MariaDB. It's compatible with MySQL, so instructions are the same:

https://www.traccar.org/mysql/

**Comment by QROkes** [comment]
Sorry, I'm actually using MariaDB in my Traccar Installation, so I think I did it "automatically" based in the well known compatibility.
