### ISSUE TITLE
Web socket connection error

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#3115]
Hello,
Since traccar 3.11, I keep getting "Web socket connection error" with firefox. The site is reverse proxied in https through nginx. Firefox console shows an error 400 when accessing https://.../api/socket
Since this was working before, I am wondering if something changed with the websocket between 3.10 and 3.11. There is no error in either nginx or traccar logs.

**Comment by tananaev** [comment]
I don't think there were any changes to WebSocket connection since 3.10. I suspect there is something wrong with the proxy.

**Comment by renaudallard** [comment]
I have increased logging and found something in nginx logs.
2017/04/24 08:39:08 [info] 15352#0: *143368 client sent too long header line: "Cache..." while reading client request headers, client: yyyyyyyy, server: xxxxxxxxx, request: "GET /api/socket HTTP/1.1", host: "xxxxxxxxx"

**Comment by tananaev** [comment]
Interesting... but that's not an error.

**Comment by renaudallard** [comment]
No, it's not logged as an error, but that's the cause of the 4xx response. I have increased the maximum header size and the error is gone.

**Comment by tananaev** [comment]
How do you increase the limit?

**Comment by renaudallard** [comment]
The problematic one was this
>        large_client_header_buffers 1 1k;
I changed it to
>        large_client_header_buffers 4 8k;

doc: https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

I don't remember why it was set so low, there must have been a reason in the past.

**Comment by tananaev** [comment]
Thanks. It might help some other people with the same issue.

**Comment by arjuntu** [comment]
hi,
I am trying to use traccar and getting the same error. I don't know where to change the header value. can some help me?

**Comment by ondrejbaranek** [comment]
Error Is gone after enabling Apache module proxy_wstunnel (if using reverse proxy)

**Comment by ondrejbaranek** [comment]
Error in Apache error.log related to above was:
AH01144: No protocol handler was valid for the URL /api/socket (scheme 'ws'). If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.
