### ISSUE TITLE
API error while trying to update device attributes - PUT/devices/id

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#3116]
Hello @tananaev 

for the attribute value in device table to be updated via api, what is the format to be used? I am getting the following error.

`Can not construct instance of java.util.LinkedHashMap: no String-argument constructor/factory method to deserialize from String value ('{') at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@5d7926f9; line: 1, column: 56] (through reference chain: org.traccar.model.Device["attributes"])`

**Comment by tananaev** [comment]
What do you send in the request? You should send the same format as you receive from the server.

**Comment by jaimzj** [comment]
I am sending the attributes as JSON. Also the format I receive from the server is in JSON (The content of attributes).
Sharing below exact value/format I am using in the API
`{"speedLimit":"20"}`

**Comment by jaimzj** [comment]
Also would like to add, I am able to edit the device all other values via API, only when I add the attributes I am stuck with the following error.

**Comment by tananaev** [comment]
Can I see full request?

**Comment by jaimzj** [comment]
@tananaev I have been using php/curl  hence when you asked for full request, I tried to get the same out and realised that the  `Content-Type:` value was configured wrong as text/plain every time I set the attributes, I corrected the request content type to `Content-Type: application/json` and it worked perfect now 👍 

Thanks a lot.
