### ISSUE TITLE
Teltonika device FM 1120 not sending data to Traccar

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#3117]
Hi,

I am trying to configure Teltonika device with Traccar server.

This issue may not be related to Traccar but would like to know anyone from India is facing the same issue.

Please find the Terminal log file with captured data of GPS device [fm1120.txt](https://github.com/tananaev/traccar/files/954514/fm1120.txt)

Teltonika device basic configuration:

APN: rcomnet   <= Reliance mobile operator

Domain name: 35.154.6.224

Server port: 5055

But I am not getting any data to server.

Please help me to resolve this issue.

Thanks.
Kiran.

**Comment by tananaev** [comment]
I'm not sure why you are using port 5055 for Teltonika, but if you don't see anything in the server log it likely means that the problem is either with the device or some network issue.

**Comment by kirantpatil** [comment]
Sir, do I need to add below configuration as you mentioned in other thread.

<entry key='teltonika.enable'>true</entry>
<entry key='teltonika.port'>5027</entry>

**Comment by tananaev** [comment]
What version of Traccar are you using? That's a very outdated config.

**Comment by kirantpatil** [comment]
I am on Traccar v3.9

**Comment by tananaev** [comment]
By default all ports are enabled.

**Comment by kirantpatil** [comment]
Sir thanks, I will check it.

**Comment by kirantpatil** [comment]
I changed as per your suggestion, but still I am not seeing anything in server log.

**Comment by tananaev** [comment]
Then it probably means that your device doesn't report data or there is some network issue.

**Comment by kirantpatil** [comment]
Sir, Yes it was simcard issue.

**Comment by tracker-pro** [comment]
Hello, the default port on 5027, check and your firewall is open.

**Comment by kirantpatil** [comment]
Thank you @tracker-pro.
