### ISSUE TITLE
converting the coordinates to be accepted in Open Street Map

### ISSUE THREAD

**Issue by cadastro2005** [tananaev/traccar#3125]
good evening,

I'm having some trouble converting the coordinates to be accepted in Open Street Map.

Would anyone have some method that converts this coordinates into javascript?

Example.:
Ol.proj.transform ([parseFloat (coord [0]), parseFloat (coord [1])], 'EPSG: 3857', 'EPSG: 4326');

But the position of the pin never stays in the correct place.

Can anybody help me?

**Comment by tananaev** [comment]
How is this question related to Traccar back-end?
