### ISSUE TITLE
Extjs Chnages not reflected in linux server

### ISSUE THREAD

**Issue by Sargunan** [tananaev/traccar#3128]
Hi,
We made change in extjs file (Web),  but corresponding changes are not reflected in the browser UI, Same changes are made in windows platform and upload to linux server,  In window platform  chnages are refelcted but not in the linux platoform

We using Traccar 3.11 and linux OS is "ubuntu",  Could you please help me out what is wrong here?

**Comment by tananaev** [comment]
Are you sure you compiled your code after changing it?

**Comment by Sargunan** [comment]
Hi, 
 It is extjs file (js), do i need to compile it?  It should load in browser when i refresh. Please correct me if i am wrong.

**Comment by tananaev** [comment]
Yes, you need to compile a minified version.

**Comment by Sargunan** [comment]
Thanks had look into your documentation and it explained clearly, I havent noticed this before,
Yes, changes are reflecting now by enabling debug option,  I will look how it can be done by using "Minified"

I will close this issuse 


"If you modify web interface files, there are two deployment options:
    Upload new files into the server “web” folder and use “debug.html” to load non-compressed version of the web interface
    Generate compressed version of the web interface (app.min.js) using “tools/minify.sh” shell script which requires ExtJS and Sencha CMD"

**Comment by Sargunan** [comment]
Hi, 
I have download extjs command and extj sdk ,  and tried to compile using minify bat file, but it shows following error, 
----------
Sencha Cmd v6.2.2.36
[INF] Loading compiler context
[ERR] com.sencha.exceptions.ExParse: Not a valid name/version "@extjs/ext-react-font-ios@6.5.0.775"
-----------

extjs sdk version : 6.5.0 (trail)

could you please help me out to solve this,  Thanks

**Comment by tananaev** [comment]
You can't use extjs 6.5 because there is no GPL version. You have to use 6.2.

**Comment by saranshchat** [comment]
Hello,
I have complied the source code but i am making changes on the html file are not reflecting on the UI .
Can you please help me.

**Comment by tananaev** [comment]
1. Your question is off-topic. You should create a separate thread for it.
2. Which HTML file are you changing?
3. Are you using debug or release mode?

**Comment by saranshchat** [comment]
1.I am using the debug mode.
2. I read the documentation but I am facing the problem in how to implement the web interface.
