### ISSUE TITLE
Telic protocol issue after update (3.10 to 3.11)

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#3134]

**Comment by tananaev** [comment]
No, it's not possible at the moment because different Telic models have different formulas for calculating power and battery.

**Comment by argokask** [comment]
Telic devices has all the same protocol. In that protocol there are two different values, one is for "battery"and another is for "power", where battery means internal battery value in voltage and power means external power (car battery for example). Both values are calculated with different equations which i sent you before. 

But what has changed, before everything was ok?

**Comment by tananaev** [comment]
I think my comment was pretty clear. Different devices use different equations, so I had to revert it back to ADC.

**Comment by argokask** [comment]
HEX message to server:

6500000033313230iiiiiiiiiiii39392c3137313131363036303230302c302c3137313131363036303230302cxxxxxxxxxxxx2cyyyyyyyyyyyy2c332c33372c3130362c31312c2c2c34332c353933313530382c2c303031302c30302c**313431**2c302c**3339**2c3031303800

*iiiiiiiiiiii = last 6 digits of IMEI
*xxxxxxxxxxxx = longitude 
*yyyyyyyyyyyy = latitude

Battery:
Value in protcol string = **313431(hex)** = 141 (ascii)
=3.4 + (141 * 0.00345) = 3,88V

Power:
Value in protcol string = **3339(hex)** = 39 (ascii) 
= 6 + (39/8) = 10,8V

**Comment by argokask** [comment]
Different Telic models have exactly same protocol. The point is that different Telic models uses different part of the protocol to express valuses like "power" and "battery". 

For example, Telic Picotracker is not using value "power" and that means in data string that part is just 0 value. Another example is that SBC-AVL is not using value "battery" and therefore in data string that part is 0.

Telic uses always same protcol to keep things simple.

**Comment by tananaev** [comment]
There is your formula and then there are other formulas below. Most of the information that you provided is incorrect. Even information about battery in SBC-AVL protocol.

### SBC-AVL protocol

To calculate external power and analog input value, use equation:
Voltage = value * 128mV + 6000mV
The maximum range is 0 - 255 also 6V - 38.64V (when voltage is below 6V device sends 0)

Internal Battery value is only available for SBC AVL Power devices and will transmit a digital value from 0 to 255 here.
To calculate internal battery voltage use equation:
Voltage = value * 19.8 mV
The range is 0 - 5V

### Standard BC protocol

The Analogue Input 1 in all TTU is connected to the internal power supply. So all mobile devices will measure the internal battery voltage using this analog input.

In CT and HiPer one digit is 0.018V. If a SMS should be sent as soon as the internal voltage falls below 3.5V, the lower threshold must be set to 194 and i.e the upper to 210 (3.8V).

| | BC | CT GPS | HiPER Pro |
|-|-|-|-|
| Analog Input 1 | 1 digit = 0,1V internal power supply | 1digit = 0,018V internal power supply (battery) | 1digit = 0,018V internal power supply (battery) |
| Analog Input 2  | 1 digit = 0,2V | 1 digit = ??? external power supply | Not supported |

In the CT the analog input 2 can be used to generate events as soon as the charging device is diconnected or the celltrack respectively the complete device is removed.

**Comment by argokask** [comment]
Ok. 

For SBC-AVL analog input 1 `Equation Voltage = value * 128mV + 6000mV`, gives pretty much same result as equation i gave but i understand your point. 

For Picotracker i found that equation from Picotracker user manual.

I am going to try contact with telic and get some better information about those calculations.
