### ISSUE TITLE
Traccar  REST APi get position returning Null pointer exeception

### ISSUE THREAD

**Issue by karthikbalu** [tananaev/traccar#3141]
I was able to retrieve JSON data response for get devices but for get positions (http://IP:8082/api/positions?deviceId=1)

 i am getting the below error:
`NullPointerException (... < DateUtil:65 < PositionResource:80 < ...)`

Is there any other server setup i need to do to avoid this error, Thanks

**Comment by tananaev** [comment]
It has been discussed many times before. You have to provide `Accept` header.

**Comment by karthikbalu** [comment]
It worked but I would still recommend there is a proper error message returned or we should default it JSON or any other format

**Comment by tananaev** [comment]
Unfortunately it's not possible to specify default format.

**Comment by saranshchat** [comment]
@karthikbalu  can you please tell how can we provide the Accept header as I am new to traccar.

**Comment by tananaev** [comment]
It has nothing to do with Traccar. Headers are part of HTTP standard and there is nothing specific to Traccar there.
