### ISSUE TITLE
Sudden jumps in position due to GPS device error

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#3149]
Implement filtering of invalid data. More info:

https://www.traccar.org/forums/topic/sudden-jumps-in-position-due-to-gps-device-error-its-effect-to-traccar-server/

**Comment by mpaaron** [comment]
hi, is there and update for this issue? same problem reported for tk103 devices

**Comment by tananaev** [comment]
It is already implemented in 17a023a62366ed4b85fd8f0f9cb41d591169c940.
