### ISSUE TITLE
Teltonika FMA110 o FMA120

### ISSUE THREAD

**Issue by jboscosimj** [tananaev/traccar#3151]
Hello, do they work on these GPS devices?

**Comment by tananaev** [comment]
Traccar supports all Teltonika devices, as far as I know.

**Comment by weseli** [comment]
FMA110  is same as  FM11XX with few hardware changes and it is supported by traccar server

**Comment by weseli** [comment]
FMA110  is same as  FM11XX with few hardware changes and it is supported by traccar server

**Comment by jboscosimj** [comment]
thanks for everything
