### ISSUE TITLE
device.status does not match event.type

### ISSUE THREAD

**Issue by maximilianloy** [tananaev/traccar#3165]
Hi,

First of all, thanks for this great software!

I am using Traccar Linux 3.11 and configured it to forward events to a webservice. What I noticed is that device.status is not according to event.type:

```json
{
    "event": {
      "id": 9091,
      "attributes": {},
      "deviceId": 75,
      "type": "deviceOnline",
      "serverTime": "2017-05-16T08:43:43.369+0000",
      "positionId": 0,
      "geofenceId": 0
    },
    "device": {
      "id": 75,
      "attributes": {},
      "name": "Tristar 2G",
      "uniqueId": "123456",
      "status": "offline",
      "lastUpdate": "2017-05-16T07:59:03.188+0000",
      "positionId": 26631,
      "groupId": 0,
      "geofenceIds": [],
      "phone": "",
      "model": "",
      "contact": "",
      "category": ""
    }
  }
```

So according to the event the tracker went online, but device.status still claims to be offline. Same for the other way around. Seems to me that the device status gets updated after the event was forwarded, as also seen by the timestamp mismatches ("serverTime" / "lastUpdate").
I can of course work around this, but I would expect Traccar to behave differently.

Thanks!

**Comment by tananaev** [comment]
Good catch, thanks. I have fixed the problem.
