### ISSUE TITLE
Admin cant see devices created by other users.

### ISSUE THREAD

**Issue by kumbiK** [tananaev/traccar#3167]
Hi
 I logged into the system as admin then created user A then I logged out. I then logged in again as user A added a device and the device is online and I can track it. However when I logged in again as Admin I could not see the device.

is there a way that admin   can see devices that have been added by other users?. 
I am using traccar 3.11 on a windows server

**Comment by tananaev** [comment]
Please use search before posting any questions:

https://www.traccar.org/forums/topic/seeing-all-devices/
