### ISSUE TITLE
Problem receiving information from GPS device

### ISSUE THREAD

**Issue by jriverarojas** [tananaev/traccar#3168]
Hi
my server is receiving information for xt2400 device in port 5002. Configuration is as follows:

```xml
<entry key='xt2400.port'>5002</entry>
```

But in the log i get : 
```
2017-05-16 19:33:19 DEBUG: [80193321: 5002 < 50.57.193.148] HEX: 24243335323235323036383332383036322c343030342c323031372f30352f31362c31373a33373a33322c34312e33383338322c2d37332e35333234322c3231352c302e302c302e302c302e302c302c302c392c302e392c352c302e302c31322e352c392c302c3131352c302e302c2d3939322c2d3138302c342323
```

and is not followed by any other log records.

The ascii information is : 
```
$$352252068328062,4004,2017/05/16,17:37:32,41.38382,-73.53242,215,0.0,0.0,0.0,0,0,9,0.9,5,0.0,12.5,10,0,100,0.0,-1000,-187,0##
```

What could be the problem?

**Comment by tananaev** [comment]
What makes you think you are using correct port? Your sample looks like a "xirgo" protocol.

**Comment by jriverarojas** [comment]
Yes, it's a Xirgo protocol Xirgo XT2400 Series. It's suposed to use 5138 port and i changed it to 5002 port.

Is not possible to change ports in configuration file?

**Comment by tananaev** [comment]
Please read my message more careful. You are using wrong protocol.

**Comment by jriverarojas** [comment]
According to device manual I have a Xirgo XT2450 | XT2460 device. And in [https://www.traccar.org/devices/](url) Xirgo XT2400 Series uses protocol xt2400. It also says that this protocol was implemented on 3.11 version.

According to  maven/org.traccar/traccar/pom.xml file i have 3.10-SNAPSHOT version, but in log file I have 

> INFO:

 Version: 3.11-SNAPSHOT

**Comment by tananaev** [comment]
If you think you know better then can keep trying, but it's never going to work because it's a wrong protocol. I have already told you which one you should be using.

**Comment by jriverarojas** [comment]
Yes, you are right. Sorry

Its working now
