### ISSUE TITLE
Addition of "Heart" parameter similar to existing "Pulse" 

### ISSUE THREAD

**Issue by atulbothe** [tananaev/traccar#3171]
Some manufacturer use "heart" for sending pulse instead of "PULSE". This is exactly similar to issue - https://github.com/tananaev/traccar/issues/2291#issuecomment-301909949. If I understand correctly, the only addition that needs to be done is to accept the parameter as "heart" - rest of the things should work as is.

I have attached the official documentation from manufacturer. 

---- from the attached document -----
32. Terminal heart uploaded 
     Terminal upload: 
     [3G * 8800000015 * len * heart, x] 
     X is the heart rate data per minute. 
     Example: [3G * 8800000015 * len * heart, 100] 
     The heart rate of the representative terminal is 100 times / minute 
[heart_ communication protocol.docx](https://github.com/tananaev/traccar/files/1006603/heart_.communication.protocol.docx)

**Comment by tananaev** [comment]
Please provide a HEX message sample from Traccar logs.

**Comment by atulbothe** [comment]
Couple of sample HEX message from Traccar logs:

5b33472a363030353431323930322a303030372a68656172742c305d

5b33472a363030353431323930322a303030382a68656172742c37315d

**Comment by tananaev** [comment]
I have added support for it.

**Comment by atulbothe** [comment]
That was too fast ! - Thank you! - when is the next official release? I am assuming this will be part of next official release.

**Comment by tananaev** [comment]
Yes, it will be included in the next official release. It will probably be in a month or two.

**Comment by atulbothe** [comment]
Thank you!
