### ISSUE TITLE
REST API methods are not working 

### ISSUE THREAD

**Issue by ramesh456** [tananaev/traccar#3173]
Hi , first i have create session with api/login method and i am getting perfect output. check below image:

![1](https://cloud.githubusercontent.com/assets/28094126/26215105/a8401f98-3c1c-11e7-80ce-235217e71b18.PNG)

Now , when i use api/devices then it gives me error  "HTTP 415 Unsupported Media Type - NotSupportedException (...)"

check below image:

![2](https://cloud.githubusercontent.com/assets/28094126/26215148/d5820a7a-3c1c-11e7-847d-0c25f245e587.PNG)

I am using POSTMAN to check the API response.

Please solve this !!!

**Comment by tananaev** [comment]
Value for "all" key should be all lowercase "true".

**Comment by ramesh456** [comment]
yeah , i have tried that but it shows same output.

**Comment by tananaev** [comment]
Does official web app work? I would recommend to compare what it sends with what you are sending.
