### ISSUE TITLE
Update traccar

### ISSUE THREAD

**Issue by kedarnathjimage** [tananaev/traccar#3192]
Hi tananaev,

How to update traccar 3.10 to 3.11 without losing database. And also i want update new parameter in db.

thanks

**Comment by tananaev** [comment]
There is official documentation for it:

https://www.traccar.org/upgrading-traccar/

**Comment by kedarnathjimage** [comment]
I have already seen the link but i am wondering if it will clean swipe the database. I have DB of over 4 GB which i cannot afford to loose. I can see some difference in 3.10 and 3.11 with new parameters such as phone, GMT in users table. How do i manage this ? Or Traccar will take care of this automatically

Thanks again

**Comment by tananaev** [comment]
Traccar will take care of database migration automatically. Obviously it's a good idea to make a backup of your current database state before doing upgrade.

**Comment by kedarnathjimage** [comment]
ok thanks
