### ISSUE TITLE
sign up

### ISSUE THREAD

**Issue by kedarnathjimage** [tananaev/traccar#3193]
Hi Tananaev

When i create new user from using PHP and insert it in database, I get error null pointer exceptions when i try to log on from traccar 

![screenshot from 2017-05-25 18-48-15](https://cloud.githubusercontent.com/assets/16332684/26451716/da44e236-417a-11e7-8f34-1e8c52437af1.png)

However when I restart traccar then the login works fine in traccar. Can you please put some light on this

**Comment by tananaev** [comment]
Looks like you are using wrong user id.

**Comment by kedarnathjimage** [comment]
![screenshot from 2017-05-26 09-34-19](https://cloud.githubusercontent.com/assets/16332684/26480291/88d52b46-41f6-11e7-962a-7a1eb80b1401.png)

With wrong username / password combination i get proper error like this above screenshot. The null pointer exception error is when i punch right username and password. Weirdly this pointer exception error goes away when i restart the server.

While creating user through PHP form i have inserted Name, email, hashed password, salt,map = 'osm', distanceunit='km', speedunit='kmh', attributes='{}', phone

**Comment by tananaev** [comment]
Just compare your request to what official web app sends.

**Comment by jaimzj** [comment]
@tananaev Jumping into the discussion. just noticed that @kedarnathjimage has mentioned below the first screenshot that after restarting traccar he is able to login.

So I belive he might not be using Traccar API and is making direct entries into Database insert queries via PHP.??

@kedarnathjimage If you are creating records directly into the database, Traccar has internal cache's and those will not be updated until and unless you restart traccar.

So the best option would be you start using the Traccar API

**Comment by kedarnathjimage** [comment]
Thank @jaimzj
