### ISSUE TITLE
windows could not start traccar service on local computer . system cannot find specific file 

### ISSUE THREAD

**Issue by ramesh456** [tananaev/traccar#3194]
I am getting this error when i am starting service of traccar but i can see that i am getting data from devices.

So can you tell me for what is the purpose to start this service ? 

so how much it affected if service is not started ?

**Comment by tananaev** [comment]
What is the error? Screenshot please.

**Comment by ramesh456** [comment]
![error](https://cloud.githubusercontent.com/assets/28094126/26519529/5793c0e8-42e0-11e7-812c-b111f25db3ed.png)

**Comment by tananaev** [comment]
If service is not running but Traccar still works, it means that there is either another service or you are running it as a regular application.

**Comment by ramesh456** [comment]
There is not other traccar service is ruunig. !! i have started traccar from cmd with command :  java -jar tracker-server.jar conf/traccar.xml

**Comment by ramesh456** [comment]
after started it from cmd i am starting this service but it shows the error !!!

**Comment by tananaev** [comment]
Hmmm.. so if you are already running the server, why do you need a service?

**Comment by ramesh456** [comment]
Ok. So it is like either run service from cmd or from this service .. So if i can close cmd and start service from here then traccar will work ?

**Comment by tananaev** [comment]
Probably not because it fails for some reason.

**Comment by ramesh456** [comment]
So . is this ok if this service is not running but cmd running ?

**Comment by tananaev** [comment]
It's OK, but it won't automatically start with system, unlike service.

**Comment by ramesh456** [comment]
Ok. so each time i have to manually start with cmd  . right ?

**Comment by tananaev** [comment]
That's exactly what I said.

**Comment by ramesh456** [comment]
Ok. Thank you.
