### ISSUE TITLE
Traccar Group - Cycle in group hierarchy

### ISSUE THREAD

**Issue by Kanakala** [tananaev/traccar#3195]
Hi Tananev,

I have several group on my traccar server. Everything is working fine till yesterday. But today, when i am trying to create a new group - it raising an error - `Cycle in group hierarchy - IllegalArgumentException (DeviceManager:353 < *:361 < GroupResource:63 < ...)`. I would appreciate helping fix this error.

**Comment by tananaev** [comment]
Well, the problem is that you are trying to create a cycle with groups. Don't create a cycle and it will work just fine.

**Comment by Kanakala** [comment]
I deleted all the entries that are entered from yesterday
even when i tried creating a group like this
post /api/groups
{
    "name" : "Tananev"
}
It raising the same error. I couldn't able to find where i have created a cycle with groups. Could you please help me.

**Comment by tananaev** [comment]
I have double-checked everything and it can only happen if you have a parent group.

**Comment by Kanakala** [comment]
I have two groups with groupId = 0; when i deleted the unwanted one, it works like a charm.
Thanks
