### ISSUE TITLE
Constraint typo

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#3197]
@Abyss777, I have noticed that there seems to be a typo in foreign key name:

`fk_user_calendar_geofenceid` - it should be `fk_user_calendar_calendarid`

Can we fix it? I think we can probably re-create it. Also, can you please check if other names are correct.

**Comment by Abyss777** [comment]
Hello,
Sorry, copy/past issue.

Just to clarify, how we name it:
`fk_[baseTableName]_[baseColumnNames]`
right?

Then we should also rename this FKs:
https://github.com/tananaev/traccar/blob/master/schema/changelog-3.7.xml#L16
https://github.com/tananaev/traccar/blob/master/schema/changelog-3.7.xml#L48

Here is `event` also not plural
https://github.com/tananaev/traccar/blob/master/schema/changelog-3.6.xml#L35

Here is unneeded `user_`
https://github.com/tananaev/traccar/blob/master/schema/changelog-3.6.xml#L90
https://github.com/tananaev/traccar/blob/master/schema/changelog-3.6.xml#L91

Also found:
https://github.com/tananaev/traccar/blob/master/schema/changelog-3.3.xml#L138

**Comment by tananaev** [comment]
Yes, let's agree on that naming conversion.
