### ISSUE TITLE
database.positionsHistoryDays doesn't delete positions from database

### ISSUE THREAD

**Issue by Kallu609** [tananaev/traccar#3198]
Hello! 

I can't seem to get _database.positionsHistoryDays_ configuration option to work. It doesn't seem to delete anything from my database even though I have set the days to 3, and at least 4 days have already passed. See these pictures: http://imgur.com/a/dM7rN

I'm using XAMPP, these are my database details:
_mysql  Ver 15.1 Distrib 10.1.21-MariaDB, for Win32 (AMD64)
libmysql - mysqlnd 5.0.11-dev - 20120503_

Traccar version is 3.11 and below is my current traccar.xml
```xml
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <entry key="config.default">./conf/default.xml</entry>

    <entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
    <entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
    <entry key='database.user'>root</entry> 
    <entry key='database.password'>password123</entry>
    <entry key='database.positionsHistoryDays'>3</entry>

</properties>
```

Thanks in advance!

**Comment by tananaev** [comment]
Are you sure you didn't restart server during those 4 days?

**Comment by Kallu609** [comment]
I did actually, yes. But I've had this problem earlier also with the setting set to 1 and had the server running for several days, it still wouldn't clear the position history. Only way I seem to be able to clear it is to stop Traccar server and truncate the table manually, and then restart the server.

**Comment by tananaev** [comment]
I have added a log message, so we can track database clear events.
