### ISSUE TITLE
MU-201 v3.xx doesnt work?

### ISSUE THREAD

**Issue by Castor123** [tananaev/traccar#3220]
Hi,
i've tried to install my tracker in Traccar but it doesn't work.

The Logfile was generated and everything is running but not the tracker...

HEX is translatet to:
```
imei=1234567890&rmc=$GPRMC,091950.00,V,53xx.10xxx,N,009xx.14xxx,E,0.160,,200513,,,A*68,STOP,V3.872;67%,S4,H8.3,D2.38
```
Port 5051

How can i add the device?

Kind regards
Daniel

**Comment by tananaev** [comment]
I have fixed the problem.

**Comment by Castor123** [comment]
Thanks.
