### ISSUE TITLE
Import calendar error

### ISSUE THREAD

**Issue by thiagoaraujo84** [tananaev/traccar#3223]
When using traccar with postgres I get this error when I try to import an ics file.
```
  ERROR: column "data" is of type oid but expression is of type bytea
  Hint: You will need to rewrite or cast the expression.
  Position: 68 - PSQLException (... < QueryBuilder:475 < DataManager:508 < CalendarManager:100 < ...)
```
I have tried files generated from iCalendar, Google Calendar and Thunderbird.

**Comment by tananaev** [comment]
@Abyss777, have you tested calendar blob with postgresql? Can it be an old version on the database?

**Comment by thiagoaraujo84** [comment]
I have tested it on PostgreSQL 9.4 and 9.6.
The only solution I found was changing the column type`calendars.data` from `oid` to `bytea` after Traccar database creation.

**Comment by Abyss777** [comment]
I remember that I have tested, looks like behavior was changed some time ago:
https://liquibase.jira.com/browse/CORE-1863

Possible solution:
https://stackoverflow.com/questions/42388886/force-liquibase-to-map-blob-to-bytea-on-posgresql

**Comment by Abyss777** [comment]
My theoretical solution is:
````xml
  <changeSet author="author" id="changelog-3.12-pgsql">

    <preConditions onFail="MARK_RAN">
      <dbms type="postgresql" />
      <sqlCheck expectedResult="oid">SELECT data_type FROM information_schema.columns WHERE table_name = 'calendars' AND column_name = 'data';</sqlCheck>
    </preConditions>
    <dropColumn tableName="calendars" columnName="data" />
    <addColumn tableName="calendars">
      <column name="data" type="bytea">
        <constraints nullable="false" />
      </column>
    </addColumn>

  </changeSet>
````

I'm assuming that if it is `oid` then it is impossible to create calendar and table is empty. We can easily drop column and recreate with right type

**Comment by Abyss777** [comment]
Works OK
````
INFO 6/6/17 1:30 PM: liquibase: ./schema/changelog-master.xml: changelog-3.12::changelog-3.12-pgsql::author: Column calendars.data dropped
INFO 6/6/17 1:30 PM: liquibase: ./schema/changelog-master.xml: changelog-3.12::changelog-3.12-pgsql::author: Columns data(bytea) added to calendars
INFO 6/6/17 1:30 PM: liquibase: ./schema/changelog-master.xml: changelog-3.12::changelog-3.12-pgsql::author: ChangeSet changelog-3.12::changelog-3.12-pgsql::author ran successfully in 95ms
````

**Comment by tananaev** [comment]
Can you please send a pull request.
