### ISSUE TITLE
Session Post api not returning the updated Mysql values

### ISSUE THREAD

**Issue by parveenkumardeeva** [tananaev/traccar#3225]
Hi,

I'm using your project on my own server and trying to create a new session with username admin and password admin as it creates. I manually changed the db values from mysql db tool but when accessing the same values via Session post api it's not returning the updated values.

**Comment by parveenkumardeeva** [comment]
Kindly also specify the way by which I can generate token in this POST api?

**Comment by tananaev** [comment]
You shouldn't modify database directly. Traccar has an internal cache which won't be updated until you restart the service. For any modifications you should use official API.

If you are asking about use token, you set it as a part of user account call.

**Comment by parveenkumardeeva** [comment]
what I'm changing is only login method in your Permission manager class where I'm generating a jwt token and setting it to the user class and saving it. Even I have added some log info to this method but on call to session POST there is no log against it.
But it's not working, others things working like creating new device etc. via basic authorization.

**Comment by tananaev** [comment]
OK, so you should have probably started with the fact that you are not using official version of Traccar.

**Comment by parveenkumardeeva** [comment]
So by what means I can generate token in the official version just by your code?

**Comment by tananaev** [comment]
I have already said how to set a token in the official version.

**Comment by parveenkumardeeva** [comment]
Can't we generate it on the server end instead of client end?

**Comment by tananaev** [comment]
Anything is possible. It's just not how it works at the moment.

**Comment by parveenkumardeeva** [comment]
That's what I'm exactly saying, I'm generating it in your permission manager class login method 
public User login(String email, String password) throws SQLException {
       
        User user = dataManager.login(email, password);
        if (user != null) {
            checkUserEnabled(user.getId());
//token generation is here and then update user
            updateUser(user);
            return users.get(user.getId());
        }
        return null;
    }

But it's not working, Am I doing something wrong.

**Comment by tananaev** [comment]
Looks fine from the first glance. If it doesn't work, you should debug it instead of creating an issue for it.
