### ISSUE TITLE
How can i design my custom web view

### ISSUE THREAD

**Issue by ramesh456** [tananaev/traccar#3227]
Hi , 

I want to create my custom web view. so how can i do that ? 

I can see the data is auto refreshing on web side and i think no ajax is called for that !!

can you guide me on this ?

**Comment by tananaev** [comment]
Traccar uses WebSockets for live updates. You are in the wrong repository though. Here is the web application code:

https://github.com/tananaev/traccar-web

**Comment by ramesh456** [comment]
Ok. thanks
