### ISSUE TITLE
Unknown Protocol

### ISSUE THREAD

**Issue by masoud14** [tananaev/traccar#3233]
I have got this device from topten company see the protocol description document.

The following are the HEX:

1. 2017-06-09 14:26:56 DEBUG: [23094BFB: 5009 < 197.250.102.134] HEX: 2424001158042080029010500115220d0a
1. 2017-06-09 14:26:56  WARN: Unknown device - 58042080029010 580420800290106 (197.250.102.134)
1. 2017-06-09 14:26:56 DEBUG: [23094BFB: 5009 < 197.250.102.134] HEX: 2424001158042080029010500115220d0a2424001158042080029010500115220d0a

I have tried the following ports but it did not work:
1. 5023
1. 5001
1. 5002
1. 5006
1. 5013
1. 5036
1. 5093
1. 5009
1. 5024
1. 5002
1. 5009
1. 5020
1. 5061

After trying hex decoder of the third line above the following was output:
<pre>
... removed ...
</pre>

Which I have already tried in the above list of ports.

[TOPTEN GPRS Communication Protocol V5.0_20170518 (002).pdf](https://github.com/tananaev/traccar/files/1064380/TOPTEN.GPRS.Communication.Protocol.V5.0_20170518.002.pdf)

**Comment by tananaev** [comment]
It's Meiligao protocol, port 5009.

**Comment by masoud14** [comment]
Thanks it worked. I had issues writing the imei. I had to remove the first number of the imei for it to work.
