### ISSUE TITLE
Problem with Liapac StarFinderLite with 5048 port

### ISSUE THREAD

**Issue by okjokj2** [tananaev/traccar#3237]
I have liapac StarFinderLite
I configured it to send TCP data to port 5048 but the device doesn't appear as Online on web server.

I captured the received data 
Here the received (80 byte) data packet
String:
```
$AVRMC,99999999,002553,A,1520.8990,N,04411.6959,E,0.00,,120617,0,,41,1,628,*18
```
Hex stream:
```
244156524d432c39393939393939392c3030323535332c412c313532302e383939302c4e2c30343431312e363935392c452c302e30302c2c3132303631372c302c2c34312c312c3632382c2a31380d0a
```

Here another received (61 byte)  data packet
String :
```
$AVRMC,99999999,003849,V,,N,,E,0.00,,120617,0,,41,1,186,*36
```
Hex stream:
```
244156524d432c39393939393939392c3030333834392c562c2c4e2c2c452c302e30302c2c3132303631372c302c2c34312c312c3138362c2a33360d0a
```
Please guide me what to do .

Best regards.

**Comment by tananaev** [comment]
I need protocol documentation.

**Comment by tananaev** [comment]
Also, please next time don't spam everywhere with your question. If there is a recent OPEN thread about your exact problem, you can comment on it. In any other case you should create a separate issue.

**Comment by okjokj2** [comment]
Im so sorry sir im new with github hope u appriciate it .
Anyways i have tested the port 5048 with another laipac StarFinderLite and its working well. 
The problem was because my device was sending a null course value so the database was rejecting the queries and showed as offline .
I guess i should replace my gps antenna .
Thank you so much and best regards.

**Comment by tananaev** [comment]
Can you please stop commenting on both threads.
