### ISSUE TITLE
Inconsistent device limit reached

### ISSUE THREAD

**Issue by jcorreajr** [tananaev/traccar#3238]
If the same device is also linked to more than one user, this device counts as more than one.
Note: The user must be managed by the primary user. In my case “instalador_sc”

Example:
User manager: “instalador_sc”
Devices: device01; Device02
Device Limit: 3
Managed users:
Client01 (linked – device01 and device02)
Client02 (linked – device01 and device02)
. Total devices associated with user “instalador_sc”: 4
. The user will not be able to create new devices.
. Although the user can no longer create devices he can make new links which further increases the total device limit count

I believe the best solution would be to add user-manager devices to devices created by 'normal' users that are not linked to the user manager.
The total would be analyzed by the field: devices limit

what do you think?

**Comment by tananaev** [comment]
@Abyss777, I think we thought about it before, right?

**Comment by Abyss777** [comment]
Looks like I've missed this situation, sent PR.
