### ISSUE TITLE
[Feature Request] Report to show locations where vehicle stopped for more than 15 min

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#3241]
Hi,

I would like to know if it is possible to find the locations where vehicle is stopped for more than 15 min from the report ?

Usecase: It helps to see where are my assets spending more time frequently without moving.

Thanks.

**Comment by tananaev** [comment]
How would you define "stopped" state?

**Comment by kirantpatil** [comment]
I have event report as below. But it shows most of the time "Device Unknown". I am getting confuse to deduce that where and all the device has stopped, since only once "Device Stopped" event has happened.

![image](https://user-images.githubusercontent.com/1178055/27073771-a6237932-5042-11e7-889f-1856594fe340.png)

Thanks.

**Comment by tananaev** [comment]
I don't think it answers my question.

**Comment by kirantpatil** [comment]
Sorry Sir, I don't know about "Stopped" state.

Please correct me, I thought "Stopped" event as "Stopped" state.

**Comment by tananaev** [comment]
Event just uses speed value. It is not very reliable.

**Comment by kirantpatil** [comment]
Closing this issue, based on PR #3252.

Please feel free reopen if it is not addressed.

**Comment by kirantpatil** [comment]
Also based on #3247
