### ISSUE TITLE
Geofence are parameter

### ISSUE THREAD

**Issue by ramesh456** [tananaev/traccar#3243]
Hi , 

i  have created a geo-fence and i can see the value in database is like 

`CIRCLE (22.XXXXXXXXXXX 73.XXXXXXXXX, 139.2)`

So is this 139.2 is in meter ? or is in any other form ?

**Comment by tananaev** [comment]
Yes, I believe it is in meters.

**Comment by ramesh456** [comment]
Ok. thanks
