### ISSUE TITLE
How to implement new protocol in your existing code

### ISSUE THREAD

**Issue by jackeychina** [tananaev/traccar#3246]
Hi ,

I have checked all your protocol and its really very helpful for china device but i have once device which is not suited with any one of your protocol. so i would like to add custom protocol for that . 

So how can i do that ? or are you able to create protocol for it if i will provide you protocol documentation ? 

Thanks

**Comment by tananaev** [comment]
Please read official documentation:

https://www.traccar.org/implement-protocol/

If you need help with implementing it, send me an email to discuss options.

**Comment by jackeychina** [comment]
Ok thanks.  Please share your email id. so we can discuss it .

**Comment by tananaev** [comment]
It's in the profile.

**Comment by jackeychina** [comment]
Ok. i have mailed you . please check it.

**Comment by tananaev** [comment]
I don't see any emails from you.
