### ISSUE TITLE
"TK102" nothing logging in traccar gui

### ISSUE THREAD

**Issue by oimr** [tananaev/traccar#3254]
Server Log can be viewed here: https://pastebin.com/raw/T6pJmbBX

have tried all the ports but the gui still showing offline,
have also added a 0 in front of the imei.
5001
5002
5006
5013
5023
5036
5093

any help apprieciated

**Comment by tananaev** [comment]
Port 5002, device id 087075162432. I guess you haven't tried all of them properly.
