### ISSUE TITLE
Repeating last 4 records with my new protocol implementation

### ISSUE THREAD

**Issue by gauranggaurang** [tananaev/traccar#3261]
Hello Greetings !!

I have implemented my own protocol in your existing code and i was successfully done with that but the problem is here is : 
```

@Override
 protected Object decode(Channel channel, SocketAddress remoteAddress, Object msg) throws Exception {

        String sentence = (String) msg;

```

In here msg , i am getting last 4 data  continuously with no change while my device is sending data at every seconds with different data and time !!!! 

I have refer your other protocol also and i found i have done the same thing only !!

And other problem is -> my device is changed to offline for some seconds but after 1 /2 seconds it show status online !!!

I have added all data in `position` !!

Any idea about this ???

**Comment by tananaev** [comment]
Have you checked server logs? How do you know that the problem is not on the device side?

**Comment by gauranggaurang** [comment]
Yes , i have checked it . No problem is device side. !!!

So , when i am shutting down traccar and restart after 10 minutes then device is sending more than 50 records at a time !!!!

**Comment by tananaev** [comment]
Usually something like this happens when device expects a acknowledgement from server, but server doesn't sent it.

**Comment by gauranggaurang** [comment]
Yes you are right !!! device expects a acknowledgement from server. 

Do you have any example how to send acknowledgement to device ?

**Comment by tananaev** [comment]
There are plenty of examples in Traccar. Just look for methods like "sendResponse" in Traccar decoders.

**Comment by gauranggaurang** [comment]
Hi , I have checked it method "sendResponse" but i didnt get it properly. 
I want to send response like `O$#1`  then how can i send it with writeByte ?

**Comment by tananaev** [comment]
It sounds like you don't fully understand how Netty works. I would recommend to read Netty 3 documentation first.

**Comment by gauranggaurang** [comment]
Ok. Thanks.
