### ISSUE TITLE
Use api with python bravado

### ISSUE THREAD

**Issue by ly2ly** [tananaev/traccar#3267]
Hello,

I am beginner in python.
I want to call api from a python server with bravado but I can find any operationId swagger.json
to use as python method. How can I call the api information?
Can someone give an example?

**Comment by tananaev** [comment]
What is "operationId"?

**Comment by ly2ly** [comment]
OperationId is in a swagger.json: "Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions"... <br />
  See 	http://swagger.io/specification/#operation-object-36  <br />
With bravado client (https://github.com/Yelp/bravado) I can use these operationId as python method. <br />example: <br />in
```
client = SwaggerClient.from_url(
    'http://petstore.swagger.io/v2/swagger.json',
    http_client=http_client,
)
pet = client.pet.getPetById(petId=42).result()
```
you can see in the swagger.json
```
"/pet/{petId}":
    {"get":{
        "tags":["pet"],
        "summary":"Find pet by ID",
        "description":"Returns a single pet",
        "**operationId":"getPetById**",
        "produces":["application/xml","application/json"],
        "parameters":[{
             "name":"petId","in":"path",
             "description":"ID of pet to return",
             "required":true,
             "type":"integer",
             "format":"int64"}],
              ...```

I hope you should understand. So my goal is to use api in to get data from traccar api to a python framework (Odoo ERP) in order to store inside position data, devices, etc...

**Comment by tananaev** [comment]
I believe it's an optional field and Traccar doesn't provide it.

**Comment by ly2ly** [comment]
Hum so final goal is to call api data with python. Have you other solution to suggest?

**Comment by tananaev** [comment]
I'm not sure what the difficulty is. It's a standard REST API.

You can even find some samples in Traccar script. For example, take a look at the `test-integration.py` file.

**Comment by ly2ly** [comment]
hello, Yes I searched in the wrong direction.
Finally I find the python module "request" and I am able to send post, get and other command to the server throught http. Thanks for helping a beginner.
