### ISSUE TITLE
Pipeline optimization

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3268]
I see two places for optimization:
1. Distance calculation. We calculate it 4 times in the worst case
https://github.com/tananaev/traccar/blob/master/src/org/traccar/FilterHandler.java#L114
https://github.com/tananaev/traccar/blob/master/src/org/traccar/FilterHandler.java#L124
https://github.com/tananaev/traccar/blob/master/src/org/traccar/CoordinatesHandler.java#L43
https://github.com/tananaev/traccar/blob/master/src/org/traccar/DistanceHandler.java#L45

We can move `DistanceHandler` before `FilterHandler` and `CoordinatesHandler`, but there is one problem: If `CoordinatesHandler` get worked we need reset distance and undo total distance.
One option is split on `DistanceHandler` (before filter and coordinates) and `TotalDistanceHandler` (leave on current place)

2. Move reverse geocoder after filter and coordinates filter https://www.traccar.org/forums/topic/reverse-geocode-still-attempted-for-filtered-positions/

It will prevent unnecessary reverse geocoder requests(that usually cost money) and make address more consistence with coordinates if `CoordinatesHandler` get worked.

**Comment by tananaev** [comment]
Maybe we should just combine `DistanceHandler` and `CoordinatesHandler` into one handler?

Actually reverse geocoder also calculates distance to avoid extra requests, so we can probably just use `distance` there is `DistanceHandler` is first in the pipeline.

**Comment by Abyss777** [comment]
About second one...
https://github.com/tananaev/traccar/blob/master/src/org/traccar/BasePipelineFactory.java#L201
What is better? Move `filter` up before `geocoder`
````java
        if (distanceHandler != null) {
            pipeline.addLast("distance", distanceHandler);
        }

        if (filterHandler != null) {
            pipeline.addLast("filter", filterHandler);
        }

        if (geocoderHandler != null) {
            pipeline.addLast("geocoder", geocoderHandler);
        }
        pipeline.addLast("remoteAddress", new RemoteAddressHandler());

        addDynamicHandlers(pipeline);

        if (motionHandler != null) {
            pipeline.addLast("motion", motionHandler);
        }
````
or move `geocoder` down after filter?
````java
        if (distanceHandler != null) {
            pipeline.addLast("distance", distanceHandler);
        }

        pipeline.addLast("remoteAddress", new RemoteAddressHandler());

        addDynamicHandlers(pipeline);

        if (filterHandler != null) {
            pipeline.addLast("filter", filterHandler);
        }

        if (geocoderHandler != null) {
            pipeline.addLast("geocoder", geocoderHandler);
        }

        if (motionHandler != null) {
            pipeline.addLast("motion", motionHandler);
        }
````

The difference is what we will pass to dynamic handlers.

**Comment by tananaev** [comment]
Second option looks better for some reason, but I guess both are acceptable.

**Comment by Abyss777** [comment]
Closing this for now if there is no other ideas to pipeline optimization.
