### ISSUE TITLE
Battery level for osmand

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3274]
Traccar client report phone battery level as `&batt=` and it is stored as `KEY_BATTERY`. That is wrong, it should use `KEY_BATTERY_LEVEL`.

I'm not sure what is right, change server to store `&batt=` as `KEY_BATTERY_LEVEL` or change Traccar Client to send phone battery level as `&batteryLevel=`

What do you think?

**Comment by tananaev** [comment]
It should be handled on the server side. OsmAnd protocol is used not only by Traccar Client app.
