### ISSUE TITLE
protocol addition  request concox x1

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#3277]
Dear Anton,

concox same brand as gt06 has now released a new product, sharing the protocol for the same.  product is x1. and contains many new features including support for camera/pictures and multiple input and output sensors.

attached protocol document
[X1-GPRS Communication Protocol V1.3.pdf](https://github.com/tananaev/traccar/files/1092552/X1-GPRS.Communication.Protocol.V1.3.pdf)

**Comment by tananaev** [comment]
Send me an email if you want to discuss it.

**Comment by tananaev** [comment]
Protocol is implemented.
