### ISSUE TITLE
Meitrack protocol decoder, wrong value for temperature sensors

### ISSUE THREAD

**Issue by slachtar** [tananaev/traccar#3287]
Hello,
seems temperature calculation is wrong for meitrack protocol. I've installed an MVT600 tracker and I'm receiving the following attributes:
`'{"event":32,"sat":"9","gsm":"12","hdop":"1.0","odometer":"32960116","runtime":"28642834","mcc":605,"mnc":2,"lac":418,"cid":50794,"status":"0400","adc1":0,"adc2":0,"adc3":0,"battery":2665,"power":1083,"fuel":0.0,"temp0":3877,"distance":50.22,"totalDistance":3679.32}' }`

I'm expecting a value around 20 for temp0 attribute.
the protocol documentation states that when decoding, the first byte is the integer part of the temperature and the 2nd byte is the decimal part. Example: 000B51 //means sensor num0 has 11.81°C

But in /src/org/traccar/protocol/MeitrackProtocolDecoder.java I see something like:
`int value = Integer.valueOf(temp.substring(2), 16);` Line: 221

Another thing, is the T366 model supported, especially for temp sensor reading, because I don't see it in DeviceModel testing. http://www.meitrack.com/cd-download/Protocols/MEITRACK_T366G_GPRS_Protocol.pdf

Best Regards,

**Comment by tananaev** [comment]
I believe Traccar shows raw value reported by device. It doesn't calculate anything because formulas are different for different devices.

In the next release it will be possible to use calculated attributes to modify value.

As for T366, it's probably supported, but I'm not sure about temperature sensor. We might need to extend protocol decoder to support it.

**Comment by slachtar** [comment]
IMHO you should report sensor values as stated in protocol. I mean a floating value in celcius degrees, where integer part is byte1 and floating value in byte2.

**Comment by tananaev** [comment]
I have fixed the problem.

**Comment by slachtar** [comment]
Nice to hear that. I'll test and report findings.
Any server binary to share?

**Comment by tananaev** [comment]
You can compile it yourself or wait for the next official release.

**Comment by slachtar** [comment]
Great,
Thank you.
