### ISSUE TITLE
[How to] Device movement direction on map

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#3297]
When device is shown on embedded map with car or bus icon, it does not show the direction of movement as shown in the Traccar app. 

What needs to be done here so that car icon turns as vehicle turns on the road, as it turns in Uber or Ola app?

Thanks,
Kiran.

**Comment by tananaev** [comment]
Traccar does show direction on the map.

**Comment by kirantpatil** [comment]
Sir, but on embedded map with websockets, the icon is not turning, as shown in screenshot below. Even though the device moves back, left and right, the icon doesn't turn.

![screenshot from 2017-06-27 10 58 38](https://user-images.githubusercontent.com/1178055/27572143-cbf57742-5b27-11e7-8f00-43329b268e1b.png)

**Comment by tananaev** [comment]
What "embedded map" are you talking about?

**Comment by kirantpatil** [comment]
Sir, I am referring to devices shown using https://github.com/tananaev/traccar-web/tree/master/web/simple from https://github.com/tananaev/traccar/issues/2313

**Comment by tananaev** [comment]
There are no icons there, as far as I remember. What car and bus icons are you referring to in the first comment?

**Comment by kirantpatil** [comment]
Yes, I added car icon for testing purpose to marker in app.js as below.
```

 if (!marker) {
                            var device = devices.find(function (device) { return device.id === position.deviceId });
                            marker = new google.maps.Marker({
                                     position: myLatLng,
                                     map: map_asset,
                                     icon: '/assets/car.svg',
                                     title: device.name
                                  //   label: device.name
                         });

```

**Comment by tananaev** [comment]
Do you realize that your request doesn't make sense for official version of Traccar?

If you already modified the code, you can easily add rotation as well.

**Comment by kirantpatil** [comment]
Yeah, you are right, it is not feature request. Sorry for that.

Please let me know, how can I add rotation ?

**Comment by kirantpatil** [comment]
Do we get any angle information from the API ?

**Comment by tananaev** [comment]
Yes, you get course information in the same object where you get coordinates. Rotation can be easily set using openlayers library.

**Comment by kirantpatil** [comment]
Sir, Thanks. I will try it. Right now I am playing with Google api and Leaflet.

**Comment by chasgames** [comment]
@kirantpatil Did you manage to get this to work, the route and Heading? Any chance we can see your App.js

**Comment by kirantpatil** [comment]
I couldn't try it.
