### ISSUE TITLE
Null Pointer Exception when adding user through API

### ISSUE THREAD

**Issue by kaustubhlohiya** [tananaev/traccar#3302]
I am using traccar 3.11 along with MYSQL database. I have created a manager user using API with following data without a issue

[ readonly = 0, admin = 0, Expiration = 2017-12-31 05:30:00, userlimit = 3, disabled = 0, devicelimit = 10, devicereadonly = 0 ]

Now when this manager account tries to add a user to the database using the same API it throws a NULL pointer exception. i am passing the following parameters 

Method (POST) : api/users
Parameters:

[ disabled:"false" email:"user@gmail.com" expirationTime:"2017-08-31T00:00:00+00:00" name:"Test User" password:"password" phone:"9876543210" readonly:"true" ]

I am hitting the API using curl with following header and passing the traccar cookie as well
'Accept: application/json';
'Content-Type: application/json';

What really confuses me is that the same code works just fine for Admin but for Manager it gives a Null Pointer Exception. Any lead into this will be helpful

Thanks

**Comment by kaustubhlohiya** [comment]
I Just console logged the response of Curl and this is what i get

```
HTTP/1.1 400 Bad Request
Date: Wed, 28 Jun 2017 04:54:55 GMT
Content-Type: application/json
Access-Control-Allow-Headers: origin, content-type, accept, authorization
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Content-Length: 69
Server: Jetty(9.2.21.v20170120)

NullPointerException (PermissionsManager:192 < UserResource:64 < ...)
```

**Comment by tananaev** [comment]
Looks like there was a small problem in user permissions. Should be fixed now.

**Comment by kaustubhlohiya** [comment]
When is the updated version likely to be available ?

**Comment by tananaev** [comment]
Should be out in about two weeks.
