### ISSUE TITLE
How to identify trips in GT06n?

### ISSUE THREAD

**Issue by saurabhsksharma** [tananaev/traccar#3303]
Hi, I am trying to work with GT06n based device. Requirement is to create Trips. I need a unique identifier which I can get from device data so that I can use it to create Trips. Please let me know if any such thing is there.

**Comment by slachtar** [comment]
As far as I know, gt06n doesn't provide such info, neither traccar.
You've to manage it by yourself. A trip is a sequence (array) of positions you've to save and give a name too. So you can traverse the array and calculate trip distance, duration, avg speed, max speed, etc.

**Comment by tananaev** [comment]
I never heard of any device that provides unique ids for trips.

**Comment by saurabhsksharma** [comment]
Actually @tananaev, I had also work on Castel protocol. There I got "acc_on" attribute which is constant for each Trip. That is why I am trying to find something similar in this GT06n protocol. But as @slachtar said, I will have to manage Trips by myself. Anyways thanks for responding.

**Comment by tananaev** [comment]
You are basically talking about ignition value. It is available for many protocols. But I don't think you can call it an identifier.
