### ISSUE TITLE
meiligao protocol decoder doesn't report OBD data

### ISSUE THREAD

**Issue by slachtar** [tananaev/traccar#3304]
Hi,
I'm using an OBD tracker, protocol meiligao, all works fine for gps location.

The only problem is that I can't see OBD data, seems when you receive OBD data, you try to find last position and add obd data to it, which is not working in my case!!

Notice, I'm using the forwardurl feature and no position is saved locally except device's IMEI? Isn't last position saved in memory? Or I need to activate the insert positon and get last position queries into db?

If I really need to activate them, is there a way to configure traccar to delete positions every day for example, because the db gets huge quickly.

Best Regards,

**Comment by slachtar** [comment]
Update:
I added the insertPosition and select and update last position qry statements but still dont get obd  data forwarded. Is it a forwardurl missing config (i've added attributes to url), or a special case that requires your attention.
Regards

**Comment by tananaev** [comment]
It has nothing to do with last position. Can I see logs with OBD data?

**Comment by slachtar** [comment]
Nice to hear it has nothing with obd data.
I'll activate log and show it.
Thank you

**Comment by slachtar** [comment]
*With last gps position

**Comment by slachtar** [comment]
Here's the log I got, hope it helps
2017-06-28 23:05:41 DEBUG: [37B86314: 30008 < 196.184.236.169] HEX: 2424007f1092ffffffffff9999523232303534392e3030302c412c333533372e313231372c4e2c30313130302e303633332c452c362e34382c3139332c3238303631372c2c2a30357c302e387c32347c323030307c303030432c303030417c303235443030303230303833354437427c31357c3037303636424142f7310d0a

**Comment by slachtar** [comment]
It's a tk228 tracker.

**Comment by tananaev** [comment]
It's not an OBD message. It's a regular alarm message and it's decoded without any issues by the latest version of Traccar.

**Comment by slachtar** [comment]
Really strange, it's an obd tracker tk228, may be I got the wrong data packet from log.
Is obd data sent in separate packets?
Is it meiligao protocol, just to be sure?

**Comment by tananaev** [comment]
It is Meiligao protocol. I don't know if it's sent in separate messages. It depends on the device, I guess.

**Comment by slachtar** [comment]
Don't know if it's obd data, but I got also this in log:
2017-06-28 23:06:41 DEBUG: [37B86314: 30008 < 196.184.236.169] HEX: 242400111092ffffffffff5000a51d0d0a
2017-06-28 23:06:41 DEBUG: [37B86314: 30008 > 196.184.236.169] HEX: 404000121092ffffffffff400001ea370d0a

I'm sorry for disturbing you but have got it reporting obd data on supplier's tracking plateform.

**Comment by slachtar** [comment]
Forget last msg plz it belongs to another tracker.
