### ISSUE TITLE
Geofence Enable/Disable

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#3310]
Is there a way to disable a geofence without deleting it?

**Comment by tananaev** [comment]
You can unlink it from your device(s).

**Comment by jon-stumpf** [comment]
I have many devices and I have a geofence assigned to all of them.  If I want to temporarily disable this geofence, I would need to unlink the geofence from each device.  Similarly, I would need to link it to each device when I want it back.

Would you accept a pull request that provides an "enabled" attribute (default TRUE) that would provide the ability to disable a geofence without affecting the links to devices?

**Comment by tananaev** [comment]
Why can't just just use a group? All your devices will be in a single group. Then you link geofence to that group.

**Comment by jon-stumpf** [comment]
Was not aware I could do that.  Thanks.
