### ISSUE TITLE
Where save special event  (processing.copyAttributes.enable)

### ISSUE THREAD

**Issue by juanma2413** [tananaev/traccar#3312]
Anton, I hope you're well.
I have a gt06d (protocol gt06) I can read the opening of doors. The open-door message is not recorded in the database as an event.
With the option "processing.copyAttributes.enable" I can see it, but I need to store the event as if it were ignition for example. This is possible? thank you very much for your help

**Comment by tananaev** [comment]
What exactly can you see with copy attributes parameter?

**Comment by juanma2413** [comment]
Thank you very much for your attention, Anton. I solved the inconvenience with the configuration file traccar.xml. Congratulations on your project I will collaborate with him.
