### ISSUE TITLE
Confusing attribute temp

### ISSUE THREAD

**Issue by slachtar** [tananaev/traccar#3313]
Hi,
when using OBD, we receive attribute temp1 which is about engine temperature. We're receiving the same attribute when using external temperature sensor for example, which is confusing, I suggest to use a new prefix for obd temperature, for example obdTemp1 or engineTemp1.
What do you think?
Thank you

**Comment by tananaev** [comment]
If attribute key is "tempX", it probably means that protocol documentation doesn't specify what kind of temperature it is.

**Comment by slachtar** [comment]
For example for TK228 OBD, it returns tempX as engine temperature, the protocol docs states that the value is engine temperature which is read from obd data.
For meitrack MVT600, it returns also tempX as external temperature sensor and that's fine.
I'm displaying a dashboard to show engine temperature, I'm getting confusing, when reading attributes.tempX, I don't know if it's engine temperature to show on dashboard or it's external temperature to show in other reports.
I suggest to add the obd prefix like in obdSpeed.
What do you think?

**Comment by tananaev** [comment]
I need to see that protocol documentation.

**Comment by slachtar** [comment]
Yes, sure, here's the TK228 protocol documentation, It's working as meiligao protocol:

[TK228_CANBUS Data Communication Protocol.docx](https://github.com/tananaev/traccar/files/1121941/TK228_CANBUS.Data.Communication.Protocol.docx)

**Comment by slachtar** [comment]
I'm not sure if the attachement worked, 
Can you acknowledge reception documentation.

**Comment by tananaev** [comment]
That's not really a full protocol documentation. Also, it's a documentation for a single model. How do you know it's the same for other models?

**Comment by slachtar** [comment]
[GPRS_protocol_TK210_TK220_TK228.docx](https://github.com/tananaev/traccar/files/1122025/GPRS_protocol_TK210_TK220_TK228.docx)

**Comment by tananaev** [comment]
It says the same thing:
> CANBUS Data Format(specially for TK228)

**Comment by slachtar** [comment]
It's documentation from supplier.
It says "CANBUS Data Format(specially for TK228)" because the doc are for TK210 and TK220 which do not report OBD data, that's why they said that it applies only to TK228.
 
The device is working on port 5009 as meiligao protocol and it's reporting obd Data correctly, just the tempX attribute is confusing. 
I guess for all obd data, especially for confusing attributes like speed and temp, we should add the "obd" prefix which is true for all obd devices but the final decision is yours :)

**Comment by tananaev** [comment]
I have fixed the issue.

**Comment by slachtar** [comment]
Hi @tananaev 
nice fix, will test and report issues if any.
Thanks
