### ISSUE TITLE
TK228 OBD device

### ISSUE THREAD

**Issue by proarchdev1** [tananaev/traccar#3314]
I am trying to use traccar server connecting to OBD device TK228. I am providing the device identification number and its showing offline (even when the device is attached to the car and car is moving). 

Please help.

**Comment by slachtar** [comment]
Are you using port 5009? which is the correct one for TK228.
Try to activate logging and see if you receive data on that port.

**Comment by proarchdev1** [comment]
O!! Thanks for the quick reply. Do you mean to say that I have to change 8082 to 5009!! 

Relating logging it didn't log anything just saying the server started.

**Comment by tananaev** [comment]
Port 8082 is ONLY for web interface. For devices you should use port 5xxx. Check official website for more information. Please do some research before asking questions here.

**Comment by slachtar** [comment]
leave the 8082 which is for web interface as @tananaev said.
configure your device to send to your IP server, port 5009.
Regards

**Comment by proarchdev1** [comment]
Thank you Slachtar and Anton Tananaev. I was able to communicate the server with obd device. Your views were of great help. The last statement given by Slachtar helped me drive to my destination. 

Regards.
