### ISSUE TITLE
How to do login with hashedpassword and salt password in php

### ISSUE THREAD

**Issue by gauranggaurang** [tananaev/traccar#3316]
Hi , i want to create my own REST API with PHP and i am stuck at 1st step of login .

I have refer your forums - https://www.traccar.org/forums/topic/login-php-hash-and-salt/

But it wont work !!! how can i compare the hasedpassword with original text password ?

**Comment by tananaev** [comment]
You don't compare text password. You hash it first and then compare hashes.

**Comment by gauranggaurang** [comment]
Ok and how to hash password in php ? which method you have used for "hashedpassword" in user table ?

**Comment by tananaev** [comment]
I would recommend to search on forum and other github threads. I remember that this has been discussed before.

**Comment by gauranggaurang** [comment]
Ok. i have check it but not able to find any solution !!
which technology you have used for hashing password ?

**Comment by tananaev** [comment]
Traccar uses PBKDF2-HMAC-SHA1 algorithm. For more details check `Hashing.java` class.

**Comment by gauranggaurang** [comment]
Ok . Thanks

**Comment by alanvictorjp** [comment]
precisei recentemente, e aqui está uma solução.

```php
<?php
$password = 'minhaSenhaSegura';
$salt_bin = random_bytes(24);
$salt_hex = bin2hex($salt_bin);
$hash = hash_pbkdf2("sha1", $password, $salt_bin, 1000, 48, false);
echo "Senha: $password\n";
echo "Salt (hex): $salt_hex\n";
echo "Hash (hex): $hash\n";
?> 
```
