### ISSUE TITLE
Status Events do not depend on 'event.enable'

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3324]
Just noticed Status Handler has own switcher https://github.com/tananaev/traccar/blob/master/src/org/traccar/database/ConnectionManager.java#L51

And do not depend on global `event.enable`

https://github.com/tananaev/traccar/blob/master/src/org/traccar/BasePipelineFactory.java#L163

Is this intentional behavior? If yes, than we probably should enable it by default.

**Comment by tananaev** [comment]
It looks like you've added it in bae6692356872fcc093ce92ed37cba7d2e2f6d7f.

I don't think we need a separate switch. We can probably remove it.

**Comment by tananaev** [comment]
I see the problem. We removed separate booleans, but I guess missed out this one. I think we should use `event.enable` for all events.

**Comment by Abyss777** [comment]
Thanks

**Comment by renaudallard** [comment]
Could that also be responsible for the notifications. I upgraded to 3.13 and I don't get notifications anymore. Although, sending a test notification works, but notifications for events just don't.

**Comment by tananaev** [comment]
It can be the cause if you are not receiving status updates. Easily fixable by adding `event.statusHandler` to the config file.

**Comment by renaudallard** [comment]
Indeed, setting that parameter solved the issue I was having.
Thanks
