### ISSUE TITLE
run server with NetBean error.

### ISSUE THREAD

**Issue by zonhanoz09** [tananaev/traccar#3325]
![image](https://user-images.githubusercontent.com/20008948/27993553-136b20fa-64d7-11e7-9476-0a1965e37301.png)
I was running a server with netbean but could not.
Do not know what the problem is?
help me..

**Comment by tananaev** [comment]
No problem. Everything is working according to the log.

**Comment by zonhanoz09** [comment]
But when I build up does not show the web interface

**Comment by zonhanoz09** [comment]
https://www.traccar.org/build-in-netbeans/
I have followed the above steps. But it is like this
![image](https://user-images.githubusercontent.com/20008948/27993728-5e5f7712-64d9-11e7-9a63-4adb1db3ae1a.png)

**Comment by zonhanoz09** [comment]
The traccar server file lacks a web interface

**Comment by zonhanoz09** [comment]
![image](https://user-images.githubusercontent.com/20008948/27993775-77daf260-64da-11e7-9d5e-40c189a98014.png)
I did it

**Comment by tananaev** [comment]
I guess you figured it out, so I'm closing this issue.
