### ISSUE TITLE
Traccar 3.13 status.timeout ERROR

### ISSUE THREAD

**Issue by jboscosimj** [tananaev/traccar#3329]
The variable status.timeout in version 3.9 worked perfectly, I had 120 seconds and after this time the device turned red, but in version 3.13 it seems that sometimes the devices turn red in a short time (more or less 5 Seconds) and then they turn green, why?

**Comment by tananaev** [comment]
There is no need to spam everywhere with your question. Closing this issue. I have commented on the forum thread:

https://www.traccar.org/forums/topic/traccar-3-13-status-timeout-error/
