### ISSUE TITLE
Map Device fields and attributes to Computed Attributes

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3333]
It would be helpful if we implement mapping of device fields and attributes in Computed Attributes.

We should do it carefully to not decrease some security aspects.

**Comment by tananaev** [comment]
I think it can be optional in the config.

What security problems do you see in adding device attributes?

**Comment by Abyss777** [comment]
At least we should not map whole device object, may be will map with some prefix, like `deviceXxx`.

`password` might be stored in attributes, also I believe somebody does not want share device IMEI to everybody.

I thought it over, looks like we do not get much security leaks if user can link computed attribute to device he already can read everything from device itself.

**Comment by tananaev** [comment]
Yes, I think to start with we can just map all the attributes. I suggest we just do the same thing as with positions; just map everything directly. Attribute names are selected by users, so we don't care much about duplicates (position attributes should take precedence though).
