### ISSUE TITLE
Installation instructions - Essential information missing

### ISSUE THREAD

**Issue by tsk1979** [tananaev/traccar#334]
Hi Anton
I was able to install traccar, but it did not work. So I decided to install OPENGTS. Their user guide walked me through all the packages which are pre-requisites. I installed all pre-req(java/ant/tomcat.....) and instead of installing opengts, decided to give traccar a shot. It worked!!
I guess on the installation page, we need a list of packages which are needed for traccar to run.
Can you please make an edit to the page and list pre-requisites?

**Comment by tananaev** [comment]
All instructions have been updated some time ago.
