### ISSUE TITLE
Filter Maxspeed problem

### ISSUE THREAD

**Issue by 5of9** [tananaev/traccar#3342]
Do you have an idea how this can happen with <entry key='filter.maxSpeed'>30000</entry> set:
Its a 4300km jump in 5 seconds, should get filtered, because in 5 seconds a jump of 77km is the maximum possible with 30000knots!?
```
| 45214 | wondex   |        2 | 2017-07-11 10:40:33 | 2017-07-11 10:40:30 | 2017-07-11 10:40:30 |      | 48.066075 | 11.552966 |      586 |       0 |     82 | 10 Bavariafilmpl., Grünwald, BY, DE  | {"sat":14,"event":"2","distance":0.0,"totalDistance":1.97271758E7,"ip":"89.204.135.168","motion":false}        |        0 | null    |
| 45215 | wondex   |        2 | 2017-07-11 10:40:38 | 2017-07-11 10:40:36 | 2017-07-11 10:40:36 |      |        10 |  3.002836 |      586 | 16.1987 |     76 | Unnamed Road, Borgou, BJ             | {"sat":14,"event":"2","distance":4312595.84,"totalDistance":2.403977164E7,"ip":"89.204.135.168","motion":true} |        0 | null    |
```

**Comment by tananaev** [comment]
Are you sure you have enabled filtering?

**Comment by 5of9** [comment]
Yes, the duplicate filter works:
2017-07-11 19:02:23  INFO: Position filtered by Duplicate filters from device: 1000000010 with id: 2

**Comment by 5of9** [comment]
My settings:
<entry key='filter.enable'>true</entry>
<entry key='filter.invalid'>true</entry>
<entry key='filter.future'>300</entry>
<entry key='filter.duplicate'>true</entry>
<entry key='filter.maxSpeed'>500</entry>
I changed it now to 500 and this happend today again:
| 46667 | wondex   |        2 | 2017-07-12 13:46:34 | 2017-07-12 13:46:04 | 2017-07-12 13:46:04 |      | 48.539073 | 12.151051 |      404 |       0 |    164 | 1 Mühlenstraße, LA, BY, DE     | {"sat":12,"event":"2","distance":0.0,"totalDistance":2.847209758E7,"ip":"89.204.135.251","motion":false}        |        0 | null    |
| 46668 | wondex   |        2 | 2017-07-12 13:46:35 | 2017-07-12 13:46:24 | 2017-07-12 13:46:24 |      |         8 | 22.017663 |      404 | 18.3585 |     72 | RR 21, Haute-Kotto, CF         | {"sat":12,"event":"2","distance":4607140.43,"totalDistance":3.307923801E7,"ip":"89.204.135.251","motion":true}  |        0 | null    |
| 46669 | wondex   |        2 | 2017-07-12 13:48:19 | 2017-07-12 13:46:04 | 2017-07-12 13:46:04 |      | 48.539043 | 12.150996 |      404 |       0 |    164 | 1-3 Mühlenstraße, LA, BY, DE   | {"sat":12,"event":"2","distance":4607138.24,"totalDistance":3.768637625E7,"ip":"89.204.135.251","motion":false} |        0 | null    |

**Comment by socstur** [comment]
I strongly believe there's a bug in the maxSpeed filter code. I have tried setting it to 1 and nothing gets filtered out. I'm not very good at coding but I'll try to debug that section of the code. If I find something I'll report.

**Comment by tananaev** [comment]
I have found the problem. Basically it worked before, but the value was 1000 times higher. So, if you set speed limit to 1 knot, it would actually be 1000 knots. Fixed now.

**Comment by socstur** [comment]
Thanks for taking a look at this Anton...I'll test it out and report back.

**Comment by socstur** [comment]
Hi Anton,
               I think the maxSpeed filtering is not working quite yet. Let me know if I'm wrong but I have this in my config file.

    <entry key='filter.enable'>true</entry>
    <entry key='filter.maxSpeed'>0.0001</entry>
    <entry key='filter.distance'>399</entry>

I do not see any filtering by maxSpeed. I then manually edited filterMaxSpeed(Position position, Position last) to return true. I still do not see any maxSpeed filtering in my logs or on the web platform. Also the "filterMaxSpeed" variable is always showing "130" value regardless of what value I put in my config file. Please let me know if I'm doing something wrong. 

    private boolean filterMaxSpeed(Position position, Position last) {
        if (filterMaxSpeed != 0 && last != null) {
            double distance = position.getDouble(Position.KEY_DISTANCE);
            long time = position.getFixTime().getTime() - last.getFixTime().getTime();
            return true;
        }
        return false;
    }

**Comment by tananaev** [comment]
You can only use whole numbers as `filter.maxSpeed` values.

**Comment by 5of9** [comment]
The filter works with values 1000times smaller than befor! I use 25 and it stops the jumps to africa.

**Comment by socstur** [comment]
@5of9 are you running 3.13 released code or the GitHub code?

**Comment by 5of9** [comment]
I use 3.13 but the github code is fixed and should work with 1000 times higher values

**Comment by socstur** [comment]
ok thanks...looks like don't get the huge gps jumps anymore taking into account the value is 1000 larger,

**Comment by gustavofcalmeida** [comment]
I'm confused. What is the unit that is used in the maxSpeedFilter? knot or 1000 knot?

I mean, if I put 200, I'm filtering positions faster than 200 knots or 200000 knots?

**Comment by tananaev** [comment]
@gustavofcalmeida, if you are using latest version it should be knots.

**Comment by Chalanero** [comment]
Hi, I'm a novice in this, I have the same error that they are commenting, my gps103 team reports badly on different occasions, I read that I have to change some values in "filter.maxSpeed". my query is: where do I find the file where I change this? /opt/traccar/conf/default.xml .... is this ???

**Comment by tananaev** [comment]
Before asking questions you should probably read documentation on the official website:

https://www.traccar.org/configuration-file/

**Comment by Chalanero** [comment]
I have this problem when asking for reports, I read the documentation but I think I am doing something wrong.
this add to the configuration file dafault.xml

 <entry key='filter.enable'>true</entry>
        <entry key='filter.invalid'>true</entry>
        <entry key='filter.duplicate'>true</entry>
        <entry key='filter.maxSpeed'>250</entry>
the error is in the image .. 
https://ibb.co/nFaiMw

**Comment by tananaev** [comment]
I would recommend you to create a new thread on forum and provide raw data from logs for the example that you show on the screenshot.
