### ISSUE TITLE
shell-init: error retrieving current directory: getcwd: cannot access parent directories

### ISSUE THREAD

**Issue by Johntaa** [tananaev/traccar#3343]
Hello;
I am trying to test the new version 3.13 on Ubuntu 64 Virtual machine , and got this error
```
server@ubuntu1:~$ sudo ./traccar.run
Creating directory out
Verifying archive integrity...  100%   All good.
Uncompressing traccar  100%
/usr/bin/java
shell-init: **error** retrieving current directory: getcwd: cannot access parent directories: No such file or directory
++++++++++ YAJSW SET ENV ++++++++++
pwd: **error** retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: **error** retrieving current directory: getcwd: cannot access parent directories: No such file or directory
openjdk version "1.8.0_131"
................................................
```
although Installation complete until we got **traccar server installed**  but the server is not stable .
Notice: this installation tested two times on one server with the same result, and one time on other server but the same error came out.

there is no change or remove to any directory in the two servers (As google search results thought about the reason)

**Comment by Johntaa** [comment]
****

**Comment by tananaev** [comment]
What do you mean by not stable? And how is it related to the installation errors?

**Comment by Johntaa** [comment]
not working directly as the old releases, until rebooting
first run   will give error like "traccar changed .. location" use systemctl to do ... "Cannot generate again"
cannot connect to remote mysql , using the exact xml file as the running version which is 3.11

**Comment by Johntaa** [comment]
no errors in the log files other the the mysql connection error, So I don't know if it is save to proceed with this version or wait sometime ?

**Comment by tananaev** [comment]
What command do you run that gives you "traccar changed... location"?

If there are MySQL connection errors, it means that there is something with your database, network or configuration.

**Comment by Johntaa** [comment]
trying to start traccar before rebooting : sudo service traccar start ,throw this warning
==== AUTHENTICATION COMPLETE ===
Warning: traccar.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**Comment by tananaev** [comment]
Use scripts from "bin" folder instead.

**Comment by Johntaa** [comment]
sudo /opt/traccar/bin/startDaemon.sh
sudo service traccar status ------->Failed

 traccar.service - LSB: yajsw wrapper for Traccar
   Loaded: loaded (/etc/init.d/traccar; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-07-12 06:33:51 EDT; 2min 32s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4901 ExecStop=/etc/init.d/traccar stop (code=exited, status=0/SUCCESS)
  Process: 4772 ExecStart=/etc/init.d/traccar start (code=exited, status=0/SUCCESS)
 Main PID: 4787 (code=exited, status=143)

Jul 12 06:33:51 tracker traccar[4901]: Jul 12, 2017 6:33:51 AM org.rzo.yajsw.os.posix.PosixService getAppPid
Jul 12 06:33:51 tracker traccar[4901]: INFO: app pid file: /run/wrapper.java.traccar.pid
Jul 12 06:33:51 tracker traccar[4901]: Jul 12, 2017 6:33:51 AM org.rzo.yajsw.os.posix.PosixService stopProcess
Jul 12 06:33:51 tracker traccar[4901]: INFO: stop daemon app with pid -1
Jul 12 06:33:51 tracker traccar[4901]: Jul 12, 2017 6:33:51 AM org.rzo.yajsw.os.posix.PosixService getPid
Jul 12 06:33:51 tracker traccar[4901]: INFO: wrapper pid file: /run/wrapper.traccar.pid
Jul 12 06:33:51 tracker traccar[4901]: Service traccar stopped
Jul 12 06:33:51 tracker systemd[1]: Stopped LSB: yajsw wrapper for Traccar.
Jul 12 06:33:51 tracker systemd[1]: traccar.service: Unit entered failed state.
Jul 12 06:33:51 tracker systemd[1]: traccar.service: Failed with result 'exit-code'.

**Comment by tananaev** [comment]
I'm completely lost now. As I said, you should NOT use "service" command. Use ONLY scripts from bin folder.

**Comment by Johntaa** [comment]
Exactly did what you said for starting traccar , but for status there is no script in bin folder

**Comment by tananaev** [comment]
Don't use it. If something doesn't work, check logs.

**Comment by Johntaa** [comment]
I don't know why I shouldn't use  service traccar status , also /etc/init.d/traccar status will not show any thing about status. 
this is for a fresh installation and before rebooting the system.
after rebooting I can use those commands -> service traccar status , with no errors.
So I think the problem requires rebooting to be solved.

**Comment by tananaev** [comment]
I guess we can keep it here for now, but I have installed Traccar on multiple machines without any problems. I don't use status command though.

**Comment by Johntaa** [comment]
rebooting the system will solve the issue , even the command service traccar status is OK

**Comment by Johntaa** [comment]
not after rebooting the problem is still there . But **SOLVED**
 I am running the traccar server in a QEMU  virtualization environmentas as a virtual machine , one of the disabled options for this virtual machine was "KVM Hardware Virtualization" . After enabling this option all the error messages completely disappeared and all commands running as expected . this may give you a clue to a code problem. thank you
