### ISSUE TITLE
Sender identification missing in SMS attributes?

### ISSUE THREAD

**Issue by jpmens** [tananaev/traccar#3344]
I have configured Traccar to connect to a simple SMPP server using the following configuration in `traccar.xml`:

```xml
<entry key='sms.smpp.enable'>true</entry>
<entry key='sms.smpp.host'>127.0.0.1</entry>
<entry key='sms.smpp.port'>2777</entry>
<entry key='sms.smpp.destTon'>5</entry>
<entry key='sms.smpp.destNpi'>14</entry>
```

SMS transmission works very well, but I'm missing some sort of identifier which indicates which user or device (`uniqueId`) initiated the transmission of this SMS. This is the data I get:

```json
{
  "body": {
    "mandatory_parameters": {
      "priority_flag": 0,
      "source_addr": "",
      "protocol_id": 0,
      "replace_if_present_flag": 0,
      "registered_delivery": 0,
      "dest_addr_ton": "alphanumeric",
      "source_addr_npi": "unknown",
      "schedule_delivery_time": "",
      "dest_addr_npi": "internet",
      "sm_length": 8,
      "esm_class": 0,
      "data_coding": 0,
      "service_type": "",
      "source_addr_ton": "alphanumeric",
      "sm_default_msg_id": 0,
      "validity_period": "",
      "destination_addr": "0987654321-xx",
      "short_message": "hello world"
    }
  },
  "header": {
    "command_status": "ESME_ROK",
    "command_length": 54,
    "sequence_number": 2,
    "command_id": "submit_sm"
  }
}
```

Is that information not available in the communication to the SMPP server at all, or have I simply not found the correct setting to configure?

If the former, would it be possible to add that? I'm thinking in terms of billing for transmitted SMS for a particular user/device. 

On a related note, the server statistics obtainable via the REST interface consistently report `mailSent` and `smsSent` as 0 (actually the last four values shown here are always 0). Is that a bug?

```json
  {
    "id": 30,
    "attributes": {},
    "captureTime": "2017-07-11T22:00:23.000+0000",
    "activeUsers": 4,
    "activeDevices": 9,
    "requests": 384,
    "messagesReceived": 2442,
    "messagesStored": 2059,
    "mailSent": 0,
    "smsSent": 0,
    "geocoderRequests": 0,
    "geolocationRequests": 0
  }
```

**Comment by tananaev** [comment]
SMPP is used to send simple text messages. What kind of information are you expecting and in which field?

**Comment by jpmens** [comment]
Of course; I hadn't thought it through.

Ideally the pyaload would contain device `uniqueId` and the user identifier with the text to be transmitted.

Is this maybe something I could add in a template? Say I transmit JSON and unpack on the SMPP server side?

```
{
  "d" : "deviceId",
  "u" : "userId",
  "t" : "hello world"
}
```

**Comment by tananaev** [comment]
Yes, you can include it in the template.

**Comment by jpmens** [comment]
I've tried this in an Online event template:

```
(d=$device.uniqueId) [u=$event.userId]
```

The first one works. The second doesn't ...
Is there a documented list of template variables somewhere?

**Comment by Abyss777** [comment]
`user`/`userId` is not passed to template at the moment. May be it make sense to do that.

Context initialization is happen here https://github.com/tananaev/traccar/blob/master/src/org/traccar/notification/NotificationFormatter.java#L40

Also you can determine user by destination address.

**Comment by jpmens** [comment]
For posterity, I solved it with `(d=$device.uniqueId) [p=$device.phone]`. Thank you.

**Comment by victorregoz** [comment]
hi @jpmens, How did you host an SMPP server? where you able to send commands from the traccar web platform to the GPS? Thanks.
