### ISSUE TITLE
Osmand protocol: Change of id parameter is ignored

### ISSUE THREAD

**Issue by Franky1** [tananaev/traccar#3353]
Just tested and played around with the Osmand protocol with Postman as source.
When i sent osmand http GET messages to traccar server with fixed id parameter, everything was received well and shown on the web interface under this id.
Then i changed the id parameter of the http GET messages, but the tracking data is still assigned to the old id and shown on the web interface, as if it was received from the old id.
Therefore i assume that the id parameter is somehow ignored and maybe bind to the source IP or TCP Session instead???

**Comment by tananaev** [comment]
Device id is cached with TCP session for performance reasons. You can set "decoder.ignoreSessionCache" to "true" in the config file if you want to change that behaviour.

**Comment by Franky1** [comment]
Thanks for the quick reply and your explanation!
Awesome!
I will close this issue.
