### ISSUE TITLE
Disabling protocol doesn't work?

### ISSUE THREAD

**Issue by TwizzyDizzy** [tananaev/traccar#3355]
Hi Anton,

I just adjusted my configuration for an easier upgrade path and now only have keys that differ from default.xml.

I only want to enable one protocol via

    <entry key='osmand.enable'>true</entry>

... in traccar.xml, still listeners for all other protocols are started when starting traccar

Even when, for example, explicitly disabling a protocol via

    <entry key='supermate.enable'>false</entry>

the supermate protocol handler is started:

    root@myhostname:/opt/traccar/conf# netstat -tulpen  | grep 5108
    tcp        0      0 0.0.0.0:5108            0.0.0.0:*               LISTEN      1001       18491933    27923/java

The last paragraph on https://www.traccar.org/configuration-file/ leads me to believe, that it should work the way I'm trying to disable it.

Any clue?

Cheers
Thomas

**Comment by tananaev** [comment]
That's outdated information. To disable port, you should remove it from config file.

**Comment by TwizzyDizzy** [comment]
Well... be that as it may: Even with only 

    <entry key='osmand.enable'>true</entry>

in traccar.xml and a totally vanilla `default.xml` traccar starts all listeners for all protocols. But I only want this one listener above.

**Comment by tananaev** [comment]
As I said, you have to remove port from the config to disable it.

**Comment by TwizzyDizzy** [comment]
Ah! Removing it from `default.xml` does work indeed. I was under the impression that one doesn't want to modify `default.xml`, as it represents the default and one can override every value in `traccar.xml`.

**Comment by tananaev** [comment]
Usually we don't recommend editing it, but for disabling ports it's the only option at the moment.

**Comment by TwizzyDizzy** [comment]
Alright, that explains everything. Thank you very much!
