### ISSUE TITLE
help with mvn package latest code

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3364]
Hi Anton,
               I pulled the latest github code and tried  building with "mvn package" to install on another machine for testing. Everything goes well and I'm able to generate an installer for another machine but I'm still getting the old version of the code. When I issue "mvn package" it seems to build 3.12-SNAPSHOT. 

How can I build with the latest source code? Do I need to edit "pom.xml" file and what goes in there to build the latest code.
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building traccar 3.12-SNAPSHOT
[INFO] ------------------------------------------------------------------------
```
Thanks

**Comment by tananaev** [comment]
Please check https://github.com/tananaev/traccar/pull/3354.
