### ISSUE TITLE
how to calculate time and distance?

### ISSUE THREAD

**Issue by gauranggaurang** [tananaev/traccar#3368]
Hi , i am using `api/reports/trips` and i am getting data like:
```
        deviceId: 1,
        deviceName: xyz,
        distance: 1536.5099999997765,
        duration: 369000,
        ....other parameters!!
```
Now how to convert this duration into minutes ?? and distance into Km ?

**Comment by tananaev** [comment]
Distance is in meters. Duration is in milliseconds.

**Comment by gauranggaurang** [comment]
Thanks.
