### ISSUE TITLE
403 - Forbidden Error

### ISSUE THREAD

**Issue by nisarzahid** [tananaev/traccar#3370]
Hi Anton,

I have setup the new traccar  v3.13 source code for both server and web using IntelliJ IDEA. Set the debug enabled for web. Server started running but when I tries opening localhost:8082, I am  getting 403-Forbidden. I think it is something to do with traccar-web directory. I am using default config for h2 database. I was running previous version of traccar very well. Would you help please?

**Comment by tananaev** [comment]
There should be no difference with previous versions. Try to debug `WebServer` class.

**Comment by nisarzahid** [comment]
Thanks,

I am able to run it by editing default.xml
<entry key='web.path'>./traccar-web/web</entry>

Previous version of web was correctly with
<entry key='web.path'>./traccar-web</entry>

**Comment by tananaev** [comment]
Probably you used `debug.xml` config before. Not sure what you are using now.
