### ISSUE TITLE
LBS with opencellid / Mozilla API key contribution

### ISSUE THREAD

**Issue by mineus55** [tananaev/traccar#3371]
Does traccar upload LBS+GPS data to opencellid/mozilla servers periodically as well?

**Comment by tananaev** [comment]
It does not make requests to geolocation providers if GPS location is available.

**Comment by mineus55** [comment]
I got that part. It only requests if GPS data is invalid.

But instead of requesting data from the providers, is traccar also capable of contributing LBS data to the providers? As far as I understand, OCID and MLS database rely on crowd-sourcing and somewhat expect the users with API key to contribute to the database somehow. I wonder if my API key will be blocked for continuously requesting data from OCID while never sending them data.

**Comment by tananaev** [comment]
Traccar doesn't upload any data that has location info. I haven't heard of anyone getting blocked, but I guess it's a risk.

**Comment by mineus55** [comment]
Very well. Thanks.
