### ISSUE TITLE
GT06 repeats last position data when ACC low

### ISSUE THREAD

**Issue by vithanagevms** [tananaev/traccar#3378]
receiving same location data after ACC low. 
is this normal or it suppose to change the time by each data row.

i just attached grepped log and position rows.

[traccar-gt06n.txt](https://github.com/tananaev/traccar/files/1166653/traccar-gt06n.txt)

**Comment by tananaev** [comment]
It is normal. Traccar takes last known location and time if device hasn't provided any.

**Comment by vithanagevms** [comment]
but device is sending same data again and again, it fills the data base with same data, only different is server time and device time, other than every records are same for each rows.  

example: this is repeating rows for 7/21/2017 8:59 


 id 	 protocol 	 deviceid 	 servertime 	 devicetime 	 fixtime 	 valid 	 latitude 	 longitude 	 altitude 	 speed 	 course  ...
1713898	gt06	774	7/21/2017 21:41	7/21/2017 21:41	7/21/2017 8:59	1	-14.23184333	35.08268444	0	5.93953	17	
1713017	gt06	774	7/21/2017 21:36	7/21/2017 21:36	7/21/2017 8:59	1	-14.23184333	35.08268444	0	5.93953	17	
1712132	gt06	774	7/21/2017 21:31	7/21/2017 8:59	7/21/2017 8:59	1	-14.23184333	35.08268444	0	5.93953	17	
1712080	gt06	774	7/21/2017 21:31	7/21/2017 21:31	7/21/2017 8:59	1	-14.23184333	35.08268444	0	5.93953	17

**Comment by tananaev** [comment]
What's the question? If you don't want duplicates, it's possible to filter them out.

**Comment by vithanagevms** [comment]
thanks for the clarification. i was thinking that this because of device didn't get the proper response to the location data. but i understood, thanks
