### ISSUE TITLE
Unable to find Mail Templates

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#3379]
I have the following configured in config.xml:
```xml
<entry key='mail.templatesPath'>/opt/traccar/templates/mail</entry>
```
The directory and its contents are readable by all.  However, I keep getting errors in my log file.  This configuration used to work (v3.11-ish).
```
2017-07-22 01:21:08  WARN: Unable to find resource '/opt/traccar/templates/mail/deviceUnknown.vm' - ResourceNotFoundException (... < NotificationFormatter:71 < *:84 < NotificationMail:111 < *:133 < ...)
```
Here is the exception being thrown:
```
Exception in thread "Thread-23" org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource '/opt/traccar/templates/mail/unknown.vm'
         at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474)
         at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352)
         at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533)
         at org.apache.velocity.app.VelocityEngine.getTemplate(VelocityEngine.java:392)
         at org.traccar.notification.NotificationFormatter.getTemplate(NotificationFormatter.java:75)
         at org.traccar.notification.NotificationFormatter.formatMailMessage(NotificationFormatter.java:84)
         at org.traccar.notification.NotificationMail.sendMailSync(NotificationMail.java:111)
         at org.traccar.notification.NotificationMail$1.run(NotificationMail.java:133)
         at java.lang.Thread.run(Thread.java:748)
```
I am using the latest commit.

Any hints?

**Comment by tananaev** [comment]
OMG, please use Github markdown. Triple-back-ticks will properly format any logs or config that you want to show.

**Comment by tananaev** [comment]
What happens if you run this command:
```
cat /opt/traccar/templates/mail/deviceUnknown.vm
```

**Comment by jon-stumpf** [comment]
I will read up on Github markdown.  Running the command, I get the output of the file.

**Comment by tananaev** [comment]
What, why are two exceptions different:
```
/opt/traccar/templates/mail/deviceUnknown.vm
/opt/traccar/templates/mail/unknown.vm
```

**Comment by jon-stumpf** [comment]
I am trying to setup a new device.  I have correctly entered the IMEI and assigned it to a user.  I have confirmed that the device has the proper APN, IP, and port.  I have another identical device already sending information on the same APN, IP, and port.  The only difference is that this device was created months ago (when I was running an earlier version of traccar).

I am getting the deviceUnknown.vm error messages in the log defined in the XML file.  When the exception is caught in NotificationFormatter.java, it tries to read unknown.vm which also fails and this is written to stderr and not the log defined in the XML file.

- jss

**Comment by tananaev** [comment]
I'm not sure what causes the issue. Try to open file from Java code and see if it works.

**Comment by jon-stumpf** [comment]
Same behavior

**Comment by tananaev** [comment]
OK, I just realized what you are doing wrong. There are two parameters

- `templates.rootPath` - this should point to the `templates` path
- `mail.templatesPath` - this should point to `mail` path

Why do you change values anyway? It sound like default it exactly what you want.

**Comment by jon-stumpf** [comment]
I suspect that I am not clear on how the finished artifacts should be deployed to the server.  I am reading **package.sh** to become more familiar.  Any reference to a document would be welcome.

(Please bear with my long explanation.)

On Linux, I follow the practice that daemons run in their own directory under **/var/run** - i.e., **/var/run/traccar**.  This directory records the PID and captures stdin and stderr in separate files.  This information is not preserved across reboots.  I put all log data in a directory on **/var/log** - i.e., **/var/log/traccar**.  This log information is preserved across reboots.

I install traccar under /opt/traccar with a common structure:

- **bin** (SH files to start/stop traccar)
- **etc** (XML config files)
- **lib** (JAR files)
- **log** --> /var/log/traccar
- **run** --> /var/run/traccar

Additional static directories for traccar include: **schema**, **templates**, and **web**.  This does not follow the [FHS](http://www.pathname.com/fhs/pub/fhs-2.3.html) strictly (i.e., **/var/opt**) because I generally prefer to have **/opt** packages follow the rules that OS packages follow.

Given the above, I generally use absolute paths as the CWD of a running process are different than that of the static information it requires and the directories for variable data.  I saw that the PATHs in the configuration files were all relative but assumed that I could use absolute PATHs.

Is it expected that all paths in the configuration are relative to CWD of the running program?

- jss

**Comment by jon-stumpf** [comment]
I have downloaded traccar-linux-3.13.zip and am studying what it does.

**Comment by tananaev** [comment]
Path to the mail template is relative to the root templates path. All other paths in Traccar can be relative or absolute.

**Comment by jon-stumpf** [comment]
Found it.  Note that **templates.rootPath** is not in the Configuration File documentation (https://www.traccar.org/configuration-file/).  It appears out of date.

**Comment by tananaev** [comment]
I will update it at some point, thanks.
