### ISSUE TITLE
Feature request: geocoding minimum time and distance

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3380]
Hi All,
         With the limits placed on geocoding request from google and other sources it'll be beneficial if we  have some control over the number of requests sent to the servers. I'm thinking a configuration parameter that sets a minimum time and minimum distance between geocoding requests. If these set time and distance are not met then previous geocode request can be reused and server does not get a hit.

**Comment by tananaev** [comment]
There is already a config parameter that's called "geocoder.reuseDistance". The value is in meters.

**Comment by socstur** [comment]
Thanks for the quick response Anton. I'll take a look at "geocoder.reuseDistance". Do you see any benefit to also having a minimum time limit?

**Comment by tananaev** [comment]
Not really. What minimum time do you think is reasonable?

**Comment by socstur** [comment]
Hi Anton,
                  The minimum time will not be fixed and it can be set in  configuration file. I think this will enable you to equally share the number of requests in a 24hr period among your devices. Also the device will not need to move for its address to be updated if the time limit is reached. With "geocoder.reuseDistance", the address only update when distance limit is reached. Let's say I set it to 2miles and the device travels  1mile from the last update and stops indefinitely. The address will never update but if it also has a time limit it'll eventually update when time limit is reached.

**Comment by tananaev** [comment]
Sorry, your reasoning doesn't make sense to me. Distance should be set to something like 50 meters to avoid requests when device is not moving. You should never set it to value as big as 2 miles.

**Comment by socstur** [comment]
Hi Anton...I was only using the 2miles as an example. But if the value is set small like 50m and you have vehicles that travel a lot then the limit will be reached fairly quickly. I have devices that travel 150+ miles in a day and a single vehicle can exhaust the limit in a few hours. A time limit will be just another parameter to help users manage usage of the geocoder requests.

**Comment by tananaev** [comment]
I don't see any point in geocoder if only 1 out of say 10 messages would have a valid value.

**Comment by socstur** [comment]
It'll be beneficial in updating the address of a device if it has stopped at a location for a long time and also another parameter to manage usage of geodocer limits besides distance alone.

**Comment by tananaev** [comment]
Sorry, but it still doesn't make sense to me. Why would you want to update address if device stopped?
