### ISSUE TITLE
traccar.sh passes two arguments to tracker-server.jar

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#3382]
While reviewing **setup/other/traccar.sh**, I noticed that it passes two arguments to **tracker-server.jar**:
>`nohup java -jar $PATH_TO_JAR $PATH_TO_CONF /tmp 2>> /dev/null >> /dev/null &`

on lines 18 and 46 (i.e., **./conf/traccar.xml** and **/tmp**).  However, checking _Context.init()_ in **Context.java**, only the first argument (i.e., the configuration file) is used.

Is this unused argument from previous versions?

And, when using this method to start traccar,

1. From which directory should it be started?  **/opt/traccar**?
2. Which user should start it?  **root**?

**Comment by tananaev** [comment]
I'm not actually sure what it's doing there. Probably we don't need `/tmp` there.

1. Yes, but if you provide absolute paths everywhere, then it doesn't really matter.
2. I believe you don't need **root** to run Traccar unless you want to use ports with restricted access (ports below 1024).

**Comment by jon-stumpf** [comment]
Thanks.
