### ISSUE TITLE
Traccar.xml :deviceId and :uniqueId

### ISSUE THREAD

**Issue by esteves67** [tananaev/traccar#3387]
Hello Mr. Anton

Is it possible when a device is being created in the **`devices`** table, specific in the **`id`** column, (Using the traccar original front end, and not manually),
That it gets inserted in that column the **`:uniqueId`** instead of the **`:deviceId`**, 
the deviceId is like " 1, 2, 3, 4, 5, 6, 7 " and increasing according to the last entry, 
and the :uniqueId could be any number like example: " 9645 ", in that case it would be the number that the person types in the window of create device, below the Device Name.

Much thanks

**Comment by tananaev** [comment]
I read your comment 3 times and I still don't understand what you are asking for. `deviceId` is a number; `uniqueId` is a string. You can't use one instead of the other.

**Comment by esteves67** [comment]
Sorry, when creating a device (values get inserted in `traccar.devices`), the value that get inserted in `id column` (database) is the `deviceId`,  i want to use `uniqueId` instead of `deviceId`.

**Comment by tananaev** [comment]
As I explained, those two are completely different things with different data types. You can try to convert `uniqueId` into an integer and use it as `deviceId` (possibly with some code modifications), but it doesn't really make much sense.

**Comment by esteves67** [comment]
Thank you
