### ISSUE TITLE
How to recover deleted device

### ISSUE THREAD

**Issue by argokask** [tananaev/traccar#3393]
Hi. 

I noticed that even if you are no admin rights user you still can delete devices as you wish. Is it possible to turn off that users can not do that?

Another question is that, if that happens then is it somehow possible to recover that device with all GPS locations data because all that data still exists in server log files. 

Thank you!

**Comment by argokask** [comment]
Inside logs folder i see GPS tracker data sent to the server, but is there also log about what changes has made in server by users and andmin. If yes then i coud find out who deleted my device. 

I got answer to my first question. I found out that here is "Readonly" button for that purpose.

**Comment by tananaev** [comment]
You can make user "readonly" or "device readonly" to stop him from removing devices.

As for recovering data, you can take a look at `recover.py` script in tools folder, but make sure you know what you are doing. You need to understand Python language.

**Comment by tananaev** [comment]
There are no logs about changes to devices.

**Comment by argokask** [comment]
Ok, thank you !
