### ISSUE TITLE
Teltonika- How to extract IMEI from login bytes

### ISSUE THREAD

**Issue by jkhasiza** [tananaev/traccar#3403]
Hi, 
I am decoding protocol of Teltonika. 
I am receiving following bytes in the login packet. 
`00 0F 33 35 36 31 37 33 30 36 34 38 33 34 32 30 38` (17 bytes)
It represents IMEI number : `356173064834208`.
How can I convert the byte array to IMEI number in the JAVA?

Thanks in advance.

**Comment by tananaev** [comment]
Traccar already does it. Check `TeltonikaProtocolDecoder` source code for more information.

**Comment by jkhasiza** [comment]
Thanks for your help..
Closing this issue.
