### ISSUE TITLE
Dynamic geofencing (suggestion)

### ISSUE THREAD

**Issue by Materie62** [tananaev/traccar#3408]
Hi, I use Traccar for a long time now and I'm very pleased with your work! Please, please keep up the good work!
As a suggestion (not sure if this is already possible, if so let me know) I would like to introduce dynamic geofencing. For this I wrote a (C) program that queries the Traccar MySQL database every ten seconds or so in order to find out the current position of my car. Whenever the car moves out of the, in the C program defined geofence area, the program send me a email that the car is moving. Nothing special. However when the C-program detects a new steady position (i.e. car is parked) it creates a new geofence around it's current position and mails me the current position. The program considers a new steady position after the car stays motionless after a certain time ( 5 min. or so). This steady state period is used the rule out traffic jams. The new position is then the new/current geofence area. This dynamic geofencing helps me notifying that the car is moving without me......
Hope the suggestion is clear. Let me know if not.

Greetings.

**Comment by tananaev** [comment]
Yes, it pretty clear. Not sure how to detect parking though.

There were also similar suggestions. For example some people have Traccar Client on their phones and they want a notification if their car moves when phone is not in the close proximity, which means someone else is driving.

**Comment by Materie62** [comment]
You can't detect parking (I guess) so one has to assume that when the car is not moving for 5 minutes or so  the car is parked. It could mean however that when you're stuck in a traffic jam and not moving within this "parking period" you receive some additional notifications. But then again I rather have some extra "false" notifications then being "surprised" and finding out the car is taken aboard within a two hour shopping period....

**Comment by tananaev** [comment]
There is already movement event. I guess we can just improve it.

**Comment by Materie62** [comment]
Interesting. Do you mean by improving to included a time out period (or parking detection)?

**Comment by tananaev** [comment]
Yes, that's one option.

**Comment by Materie62** [comment]
Well ok! I'm curious for your solution. Please keep me posted.

**Comment by tsmgeek** [comment]
Some trackers will report ACC status, this is a good indication of the car/bike being stopped if the ACC circuit is turned off.

**Comment by Materie62** [comment]
Thanks all for chipping in ideas. I'm not sure if dynamic geofencing will become a new buzz word or that it already exists. But I do hope it finds a place in Traccar.
Just for your information I use an old cell phone. I was a bit concerned that car trackers would consume lots of power. I use my car not that much. Measuring the power consumption of some cell phones I found out that there's a lot of difference in power consumption. At this moment I use a Samsung Galaxy SII+ that consume on average less then 40mA/h (including the 12V -> 5V adapter). Given a car battery capacity of 100Ah *only* the cell phone would last for 100 days (not included the idle car power consumption). Also the build in cell phone battery makes sure the cell phone will continue even if cut of from the car battery. And when in the neighborhood of a wifi point your cell phone data costs will be limited. I do advise to install a firewall on your cell phone and block Google updates. Only traccar data on a 1 minute interval will use about 40 MB/month. One disadvantage is that you don't have tsmgeek ACC status or motor shutdown options.

**Comment by tsmgeek** [comment]
The tracker I am currently playing with (TK116) goes down to 30ma when it is fully charged and once the GPS has shutdown due to no movement, its a direct wire all in one unit.

I like the idea myself. How much work would it be to implement in J. Have you got a repo with your project?

The TK unit I am playing with can forward received messages from SMS to the server, it can be used to expand on the SMS functions that already exist, ie SMS to make a geofence etc.

**Comment by Materie62** [comment]
Hi tsmgeek, the TK116 looks nice. I'll keep this in mind, it might come handy. Make sure that whenever you measure the power consumption that you average over a longer period of time (several hours). Only then you know how much a device consumes. Making a radio connection uses a lot of power. Measuring current in between these high surges might mislead you of the true long duration power consumption. 

I'm not sure how much time a J implementation would take. As I explained before I wrote a C program that queries the Traccar MySQL database (not the default H2 database). The idea is that you constantly check the traccar coordinates. When you see that the coordinates are stable, for let's say 5 minutes, the car is presumed parked. From that moment you define your new geofence location. When the car moves out of the new geofence you give a notification the car is moving. When the coordinates are stable again you notify the car is parked again and so on. Basically the concept is not that difficult. I'm not sure how difficult it would be to program this in J. I would love to share my C-code however I'm still working on it and it looks very, very messy. I would be ashamed to publish....

**Comment by tsmgeek** [comment]
@Materie62 
Update the TK116 goes under <8ma once movement has not been detected for about 2mins.
Your 40Mb data usage is way to high for 60s sample times, should be under 5MB for a month, I calculate about 25-30M for 10s sample interval and always moving, you may have a minimum charge for data usage which causes this unfortunately.

@Abyss777 
#3410 was a step into the direction to have some sort of timer based events but seems it was not merged in, was there any subsequent PR that did cover it? I saw there was issue with using timers but this would be the best way but would only be a timer if user wanted there to be dynamic geofencing and if there was no motion or ACC was off.

**Comment by Materie62** [comment]
Hi tsmgeek,
if the TK116 goes below 8mA after 2min. does this mean that the TK116 doesn't transmit coordinates to a server until it detects movement again?
Strange that you have such low data consumption compared to the 40Mb I see. Hmmm.... Not that it really matters. I have a sim only 250 Mb subscription for €2.50 / month. Could you elaborate the way you did your data load calculation? Could there be a difference between your TK116 and a cell phone with the Traccar client.
BTW we are getting off topic here. Should we move the discussion?

**Comment by tsmgeek** [comment]
The TK turns off the GPS and only sends heartbeat packets every 3 mins (defined) to keep TCP connection, also sends location at that time. As soon as any movement is detected or ACC on then it starts sending regularly based on defined interval.

Can you share with us your code for the dynamic fencing.

**Comment by Materie62** [comment]
Ok, but when sending a heartbeat packet a GSM link is needed meaning the GSM transmitter/receiver of the TK116 is activated. This means serious power needs, sometimes even 1W of GSM transmitter power.
I used a Fluke 189 Multimeter that can monitor/calculate the average current use over a longer period (hours if needed). With this average current you can predict how long a tracker will last on your car battery.
I'll clean up the C code I've and post it. However I'm pressed for time so please be patient.

**Comment by tsmgeek** [comment]
Remember that between the 3 mins the GSM is not sending anything so is in Low power mode. You will see is get down to 6ma then spike for a split second to 10ma. When the unit is fully operational it's still only using max 70ma, I've got it on a motorbike and it lasts for a month or so before battery is too low to start

**Comment by Materie62** [comment]
Yes, I understand that in your case only ever 3 minutes the TK116 is transmitting and awakes from it's < 8mA "sleepmode". However the 70mA every three minutes, even short spikes, increase the average use.
In my case when using a fully charged cell phone with a traccar heart beat of one minute the average current use is 34 mA/min. This includes low power mode, a few mA, and the (short spike) transmitting period, higher power use. 
In your case, after one month your motor batt. capacity in lowered to a too low level. Lets assume a motor battery has a capacity of 11.5Ah. One month is 30 day x 24 hours = 720 hours. 11.5 Ah / 720 = 16mA, which might be your average current use.... Now please be aware that this is a napkin calculation. The capacity of your battery depends on environment temperature, quality, etc., etc. However it gives you a hint how long you could use the tracker on a battery.

**Comment by tsmgeek** [comment]
The spike on transmit in sleep does not go anywhere near 70mA, that is when GPS is in full active tracking mode which it is not when in sleep, it switches to LBS instead.
