### ISSUE TITLE
Error creating users

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#3411]
@Abyss777, there seems to be some problem with creating new users after our changes to SQL scripts. If you try to register a new user from login or as an admin, you get following error:
```
NULL not allowed for column "HASHEDPASSWORD"; SQL statement:
INSERT INTO users (expirationTime, phone, zoom, timezone, token, disabled, attributes, longitude, latitude, userLimit, deviceReadonly, readonly, distanceUnit, deviceLimit, name, coordinateFormat, email, admin, twelveHourFormat, speedUnit, map) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23502-196] - JdbcSQLException (... < QueryBuilder:477 < DataManager:455 < BaseObjectManager:87 < ...)
```

**Comment by tananaev** [comment]
There is also this thread that might be related to our changes:

https://www.traccar.org/forums/topic/traccar-3-13-fail-to-start-with-mysql/

**Comment by Abyss777** [comment]
Got the problem, need some time to solve it. Something should be rethought.

**Comment by Abyss777** [comment]
We add/update device in two requests: standard and extended fields, but user we add/update in three requests standard, extended and both type of fields. Going to make `extended` variable "3-valued".

**Comment by tananaev** [comment]
Shouldn't we just always include "extended" fields if it's an insert action?

**Comment by Abyss777** [comment]
If we do so, we will allow set `device.lastUpdate` via API on device creation I think it is not very good.

**Comment by tananaev** [comment]
If user wants to create a device with invalid `lastUpdate`, it's his own problem, right? It's not really a security or any other issue.
