### ISSUE TITLE
Email SMTP auth default not set

### ISSUE THREAD

**Issue by tsmgeek** [tananaev/traccar#3417]
https://github.com/tananaev/traccar/blob/master/src/org/traccar/notification/NotificationMail.java#L71

Seems that if you have not got mail.smtp.auth set it will throw exception, why not default this to false?

**Comment by tananaev** [comment]
Good point, but I have even better idea. Can we just set it based on the presence of username and password?

@Abyss777, what do you think?

**Comment by tsmgeek** [comment]
That to me seems good, I cant see any reason to need auth without username/password.

**Comment by Abyss777** [comment]
I'll check if we can remove it at all

> To use SMTP authentication you'll need to set the mail.smtp.auth property (see below) or provide the SMTP Transport with a username and password when connecting to the SMTP server.
