### ISSUE TITLE
Mail template include

### ISSUE THREAD

**Issue by briggz84** [tananaev/traccar#3422]
I have been making some changes tp the default templates. I have a file htmltemplate.vm that I try to include as part of alarm.vm. I have this file located inside the Template folder and Template/mail. It contains basic HTML tags which will make up the basis for the rest of the template files.

I have tried both #parse and #include. However nothing happens and there is no errors on the wrapper.log file that I can work with?

**Comment by tananaev** [comment]
I would recommend to debug the code and read Apache library documentation. I don't think we have tried includes in templates.

**Comment by briggz84** [comment]
Thanks, after further testing. I can confirm both include and parsing of external files does in fact work, the file must be included under the template root folder as per Velocity documentation. The file path must also be relative.

Example:
`#parse("./mail/example.txt")`
