### ISSUE TITLE
missing computed attributes

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3435]
Hi All,
         I am running on latest traccar 3.13, I had created a couple of computed attributes but they seem to have disappeared. The only place I see references of them now is under "settings" ->"users" ->"computed attributes". But under "settings" ->"computed attributes" where they were created its empty. Anyone know what couple be the issue?

![image](https://user-images.githubusercontent.com/15850216/29187690-48ab5c2c-7dd6-11e7-964f-d6cb12b130f8.png)

![image](https://user-images.githubusercontent.com/15850216/29187954-1e4b5260-7dd7-11e7-8fd9-f22205b27235.png)

**Comment by tananaev** [comment]
You need to link them to your user. Tick those checkboxes.

**Comment by socstur** [comment]
Hi Anton,
               Thanks for the quick response. The linking is not an issue here. When I go to settings, then computed attributes they are not showing up there(this is the first image); This is where I can edit them if necessary but nothing shows up there. They only show up under users where I can link to users(they cannot be edited here). They also do not show up under devices (image below).

![image](https://user-images.githubusercontent.com/15850216/29192394-df00b1bc-7de6-11e7-8eb6-53a91a9d9e20.png)

**Comment by tananaev** [comment]
Your problem is exactly with linking attributes to your user. Why are you saying "no"?

**Comment by socstur** [comment]
Hi Anton,
              The problem is the computed attributes I created earlier are not showing up under computed attributes anymore. When I go to settings then computed attributes I should be seeing all the computed attributes I have created. They have all disappeared from there.

**Comment by tananaev** [comment]
I have already explained what happened and how to fix it. You have to LINK those attributes to your user account.

**Comment by socstur** [comment]
Ok thanks. I can see them now after linking to admin account. Does this mean these attributes will apply to all the devices since all the devices are linked to the admin account?

**Comment by tananaev** [comment]
No, it means that admin has access to those attributes. Please read documentation.

**Comment by socstur** [comment]
ok thanks
