### ISSUE TITLE
MICTRACK MP10 Pet Tracker not decoding

### ISSUE THREAD

**Issue by visiondrive** [tananaev/traccar#3436]
Mictrack MP10 Pet Tracker- advised it uses H02 protocol and port 5013 but message is displayed as follows with no decoding.  This is the whole of the message copied below.
[MP10-Protocol.pdf](https://github.com/tananaev/traccar/files/1216919/MP10-Protocol.pdf)

```
2017-08-11 14:17:24  INFO: [6CD89A2B] connected

2017-08-11 14:17:24 DEBUG: [6CD89A2B: 5013 < 120.22.172.248] HEX: 5b33472a323730363130333034392a303030392a4c4b2c302c302c39385d

2017-08-11 14:17:54  INFO: [6CD89A2B] disconnected

2017-08-11 13:55:10 DEBUG: [B315FE37: 5013 < 120.22.65.2] HEX: 5b33472a323730363130333034392a303030392a4c4b2c302c302c39385d
```
Which is :
```
[3G*2706103049*0009*LK,0,0,98]
```

Protocol doc attached

**Comment by tananaev** [comment]
I'm not sure who advised you, but it's not H02. It's Watch protocol, so correct port is 5093. Device id is 2706103049.

**Comment by visiondrive** [comment]
I know - I just worked it out too!

Followed your steps and found watch….5093.


Sorry and thanks for an awesome product!


Regards

[cid:96999E65-F250-454C-9DEE-B175E5FDDCA0@netgear.com]



VISIONDRIVE In-Vehicle Drive Recorders - Protect yourself, your family and your property

VISIONDRIVE PTY LTD ABN 13 158 841 288
John Asson em   sales@visiondrive.net.au<mailto:sales@visiondrive.net>
PO BOX 506 wb    www.visiondrive.net.au<http://www.visiondrive.net.au>
VARSITY LAKES QLD 4227 mb   +61 (0) 419 225 722
AUSTRALIA fx     +61 (0) 7 3112 4117

On 11 Aug 2017, at 3:04 pm, Anton Tananaev <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure who advised you, but it's not H02. It's Watch protocol, so correct port is 5093. Device id is 2706103049.
