### ISSUE TITLE
channel.getPipeline().get(HttpRequestDecoder.class)  null all the time

### ISSUE THREAD

**Issue by AymanElarian** [tananaev/traccar#3437]
hello my test service receive data from devices but it doesn't go throw decodePosition as it break on
getDeviceSession due to channel.getPipeline().get(HttpRequestDecoder.class) ==null ??

what is the main reason for that ?
>>>
```
 public DeviceSession getDeviceSession(Channel channel, SocketAddress remoteAddress, String... uniqueIds) {
      
        if (channel != null && channel.getPipeline().get(HttpRequestDecoder.class) != null
                || Context.getConfig().getBoolean("decoder.ignoreSessionCache")) {
```

**Comment by tananaev** [comment]
It's there so we ignore session cache for HTTP-based protocols. I don't see how that is an issue. How did you determine that it's the cause of your problem?

**Comment by AymanElarian** [comment]
i use Wialon IPS  to fwd all server devices to my test server , it keep don't insert to db , so i start reverse until i found that it don't go throw this condition 
[//i can print remoteAddress here 
 if (channel != null && channel.getPipeline().get(HttpRequestDecoder.class) != null
                || Context.getConfig().getBoolean("decoder.ignoreSessionCache")) {
// i can NOT print remoteAddress here ](url)

i dont have decoder.ignoreSessionCache in config , and also channel is not null

**Comment by tananaev** [comment]
Your explanation doesn't make any sense. It seems like you don't understand the code at all. I would recommend you study it more before many claims like this.
