### ISSUE TITLE
Event forwarding is not sending positions

### ISSUE THREAD

**Issue by categulario** [tananaev/traccar#3446]
Is there something I need to activate in order to have positions sent? I can see that `EventForwarder.java:68` needs position to be not null and tried to track the function calls to find where it's being called but couldn't find anything.

I'm receiving the webhook with event and device information, but the position key is not being set even though the device and the event specify positionId

**Comment by tananaev** [comment]
What event are you receiving? I would recommend to put a breakpoint `EventForwarder` and see what happens.

**Comment by categulario** [comment]
`deviceOnline` is one of the events that I'm receiving. My device is here in my desktop so no motion is produced. Is it possible to have the position from a `deviceOnline` event?

the log says

    2017-08-14 17:23:43  INFO: [074C1663] id: 1927, time: 2017-08-14 17:23:41, lat: 20.60705, lon: -103.39961, speed: 0.0, course: 134.6

so I know there is a position somewhere

**Comment by tananaev** [comment]
No, connection status events never have positions.

**Comment by categulario** [comment]
Also, I'm observing a strange phenomenon where only the first events after starting the server are reported immediatly (via the eventforwarder), and then some events are reported only when I kill the traccar server.
