### ISSUE TITLE
Show automatically registered devices on map

### ISSUE THREAD

**Issue by categulario** [tananaev/traccar#3451]
I enabled the `<entry key='database.registerUnknown'>true</entry>` setting and I'm listening to forwarded events which says this is working, but I can't see the devices on the map. Any clue?

I also tried to manually register my device wondering if that could make it appear but the response is an integrity constraint violation which says that my device is registered, I just can't see it

**Comment by tananaev** [comment]
By default automatically registered devices are not link to any user account. If you think about, it would be weird if they were. You have to manually link your device. You can do it from admin user.

**Comment by categulario** [comment]
Ok, I kind of found out how to manage devices, althought I'm receiving 404 whenever I try to link a user and a device, but will debug that.

Is it possible to contribute to the documentation?

**Comment by tananaev** [comment]
Of course. All contributions are welcome.

**Comment by dexterhussain** [comment]
If devices are not linked to any account then will it show in admin account?

**Comment by tananaev** [comment]
Yes, it will show in Settings > Users > Devices.

**Comment by dexterhussain** [comment]
thanks alot.

**Comment by categulario** [comment]
is there a repository for the docs? I can't find them in traccar or traccar
web

**Comment by tananaev** [comment]
Documentation is available on the official website.

**Comment by dexterhussain** [comment]
what does this mean?
<entry key='database.ignoreUnknown'>false</entry>

**Comment by tananaev** [comment]
Please read official documentation before asking questions:

https://www.traccar.org/configuration-file/

**Comment by categulario** [comment]
I mean for contributing, as I asked before

El 18 ago. 2017 04:34, "Anton Tananaev" <notifications@github.com> escribió:

Documentation is available on the official website.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tananaev/traccar/issues/3451#issuecomment-323307544>,
or mute the thread

**Comment by dexterhussain** [comment]
sorry @tananaev  I read it later. Thanks alot

**Comment by tananaev** [comment]
@categulario, you can send documentation to me by email to integrate into website. It has to be a simple properly formatted HTML file.

**Comment by categulario** [comment]
:/ sounds complicated for everyone.
