### ISSUE TITLE
GT06 issue -  How to reply in case of bulk login packets

### ISSUE THREAD

**Issue by jkhasiza** [tananaev/traccar#3452]
Hi,
I am receiving following packet when device is connected to server. It contains 3 login packet.
``` 
78 78 0D 01 03 51 60 80 85 04 51 64 00 67 4E F2 0D 0A 78 78 0D 01 03 51 60 80 85 04 51 64 00 68 B6 05 0D 0A 78 78 0D 01 03 51 60 80 85 04 51 64 00 6A 95 17 0D 0A
```
Which one serial number I need to send in the response as acknowledgement?

Thanks in advance

**Comment by jkhasiza** [comment]
Problem I am facing is that, some of the devices are acknowledging reply for first packet, while others are acknowledging to last packet.

**Comment by tananaev** [comment]
I would acknowledge all of them.

**Comment by jkhasiza** [comment]
Behavior of device is uncertain. It is getting disconnected, if I acknowledge all or latest or oldest packet. 
Shall I acknowledge all in single packet or write each response to socket one by one?

**Comment by tananaev** [comment]
It shouldn't matter. It's a TCP protocol, so it should be treated as a stream of data, not packets.

**Comment by jkhasiza** [comment]
Here is the scenario, that I am facing
I received data as 
78 78 0D 01 03 58 73 50 70 58 14 74 00 D1 A2 01 0D 0A 78 78 0D 01 03 58 73 50 70 58 14 74 00 D2 90 9A 0D 0A 78 78 0D 01 03 58 73 50 70 58 14 74 00 D3 81 13 0D 0A

I replied as 
78 78 05 01 00 D1 0F 51 0D 0A
78 78 05 01 00 D2 3D CA 0D 0A
78 78 05 01 00 D3 2C 43 0D 0A

Then I received
Invalid byte length -1
Device disconnected

**Comment by tananaev** [comment]
Where did you receive it? Can I see logs?

**Comment by jkhasiza** [comment]
I am not using traccar code.
I'm using blocking Socket for maintaining connection.
Here is snippet of my code:

                    ios = clientCon.getInputStream();
                    dOut = new DataOutputStream(clientCon.getOutputStream());
                    if (ios != null && dOut != null) {
                        clientCon.setSoTimeout(socketTimeOut);
                        byte[] buf = new byte[1024];
                        while (true) {
                            int n = ios.read(buf); // here server is receiving 3 login msg
                            if (n < 0) {
                                LOG.error("Invalid byte length {}", n);
                                break;
                            }
                            LOG.info("byte length is {}", n);
                            printBytes(buf, n);
                            List<byte[]> msgList = splitMsg(buf, n);
                            int totalSize = msgList.size();
                            for (byte[] msg : msgList) {
                                    byte protocol = getProtocol(msg);
                                    MSG_TYPE msgType = protocolVsMSGType.get(protocol);
                                    if (msgType != null) {
                                        LOG.info("Message type is {}", msgType.toString());
                                        if (msgType == MSG_TYPE.LOGIN) {
                                            byte[] loginReply = prepareLoginReply(loginMsg.getSerialNum());
                                            LOG.info("Login reply");
                                            printBytes(loginReply, loginReply.length);
                                            dOut.write(loginReply);
                                            dOut.flush();
                                        }
                              }
                      }

**Comment by tananaev** [comment]
If you are not using Traccar code, why are you asking in Traccar repository? I'm closing this issue as it has nothing to do with the project.

We offer premium support if you need it. Check website.
