### ISSUE TITLE
How To Remove Register Button ?

### ISSUE THREAD

**Issue by yudhaprimadiansyah** [tananaev/traccar#3458]
i have to remove Register button in Front page to prevent my clients to add his own devices, but i got confusing by web app files that im not understood at all.. is that ext JS ? i have removed Register Function in Login.js but no effect.. please help me.. im very n00b in js Scripting..

**Comment by tananaev** [comment]
Looks like you haven't read the guide before creating the issue.

**Comment by yudhaprimadiansyah** [comment]
so sorry but i really confused :(

**Comment by tananaev** [comment]
[Contributing to Traccar](https://github.com/tananaev/traccar/blob/master/.github/CONTRIBUTING.md)
