### ISSUE TITLE
Feature request: long jumps filtering

### ISSUE THREAD

**Issue by perseptron** [tananaev/traccar#3461]
Very nice work guys, but to my mind we need one more filtering option. 
There is some issue when gps send some coordinates with status valid but its far from true. It would be awesome if we had filter that throw out data where distance from previos point is grater than indicateted in this parameter. Thanks a lot.

Спасибо огромное за проделанную работу. Есть предложение добавить фильтр, который отбрасывал бы точки, расстояние между которыми больше чем указано в параметре конфигурации. (также возможно придется добавить второй параметр который бы указывал единицу времени на который расспространяется первый параметр , например расстояние за 1 час не может быть больше 200 км).

**Comment by tananaev** [comment]
Such filter already exists. It's called "filter.maxSpeed".

**Comment by perseptron** [comment]
Oh, thanks. I thought, that filter works only with velocity data device send, not with calculated by server.

**Comment by perseptron** [comment]
that works properly in 3.14
