### ISSUE TITLE
Feature Request: xmpp notifications

### ISSUE THREAD

**Issue by albertusgeyser** [tananaev/traccar#3463]
Xmpp notifications to clients.
Openfire server support.

**Comment by oliv3** [comment]
+1
What's the reason for openfire ? 
Traccar is a client in that case, should work with any server

**Comment by albertusgeyser** [comment]
Because of smartphones people can install xmpp client on their phone and notifications can be send without cost instead of sms. You correct that traccar will be client to for instance to an xmpp server like openfire, but I can also send broadcasts to different clients and also billing info to individual clients.

**Comment by tananaev** [comment]
There is a plan to implement push notifications, so I don't see much point in XMPP option.

**Comment by albertusgeyser** [comment]
How will this work?

**Comment by tananaev** [comment]
Notifications will be sent to Traccar Manager app.
