### ISSUE TITLE
Feature Request: Category 3D markers icons.

### ISSUE THREAD

**Issue by albertusgeyser** [tananaev/traccar#3464]
Category 3D marker icons (cars, trucks ...)

**Comment by tananaev** [comment]
You have to explain what you mean by that.

**Comment by albertusgeyser** [comment]
Markers shows as 3d vehicles. Some customers likes to see their car as a 3d car and owners of trucks like to see horse and trailer and smaller trucks as different 3d image to see what kind of truck is where and then go into detail. 

More detailed category images to choose from as well.

**Comment by tananaev** [comment]
Any screenshots of what you want it to look like?

**Comment by albertusgeyser** [comment]
https://image.freepik.com/free-vector/cars-collection-in-top-view_23-2147514134.jpg

**Comment by tananaev** [comment]
How is that a 3D?

**Comment by albertusgeyser** [comment]
Sorry :( saw this on another paid tracking app and looked good.

**Comment by tananaev** [comment]
There is no plan to change current icons, but you can always replace them with whatever you want. Just make sure they are in the same format and have same IDs inside.
