### ISSUE TITLE
changes in jSON data

### ISSUE THREAD

**Issue by saranshchat** [tananaev/traccar#3466]
I want to remove positionId from the attributes list using api/devices url. Can you suggest me method to how I can do this.

**Comment by tananaev** [comment]
If you just want to remove it from JSON, you can use `@JsonIgnore` annotation.

**Comment by saranshchat** [comment]
Thanks reply but where I have to use this annotation means in which api

**Comment by tananaev** [comment]
I would recommend you to read about Java annotations and look at existing usages of the annotation in the code.

**Comment by saranshchat** [comment]
I have read the code and go through every corner but I am not getting the result. Please just if you can give me a hint

**Comment by tananaev** [comment]
I have provided all hints possible. If you are still not able to find it, you should learn some Java before attempting your modifications.

**Comment by tsmgeek** [comment]
From what ive read, I am guessing you find the Devices Model and add `@JsonIgnore` (looks like you can also use `@JsonIgnoreProperties` at the top of the class and just define all the props you want to ignore) just above the property declaration that you do not want to be included in Json output then compile and publish the new jar.
What I do not think is possable is doing this at runtime, but I do not know enough about the project yet but that would be a nice feature or even user level dependent json output.

Here is information on those methods for Jackson I found.
http://www.davismol.net/2015/03/10/jackson-json-difference-between-jsonignore-and-jsonignoreproperties-annotations/

**Comment by saranshchat** [comment]
Thanks all for your help...
