### ISSUE TITLE
sms command list

### ISSUE THREAD

**Issue by lucas-big** [tananaev/traccar#3470]
hi anton,

First congratulations for the project

Can I create a list of sms commands for the devices

It would be faster to send.

**Comment by tananaev** [comment]
There is already a feature request for custom commands somewhere.

**Comment by lucas-big** [comment]
Can I send sms while the device is offline

Sorry for the terrible english

Thank you very much for the quick response

**Comment by tananaev** [comment]
Yes, you can.

**Comment by lucas-big** [comment]
How can I enable sms sending for offline devices.

When the devices are not online the check box turns off

**Comment by tananaev** [comment]
If device is offline it automatically sends via SMS, assuming SMPP server is configured.

**Comment by lucas-big** [comment]
I'm referring to custom commands.
When the device goes offline the checkbox turns off.

como posso deixar ele sempre ativado mesmo o dispositivo estando offline.

**Comment by tananaev** [comment]
Screenshot please.

**Comment by lucas-big** [comment]
SORRY . ALL PERFECT.
