### ISSUE TITLE
VT1000 some alarts not functing

### ISSUE THREAD

**Issue by vithanagevms** [tananaev/traccar#3477]
VT1000 device alarms not functioning well, I'm using port 5009 meiligao protocol (traccar 3.9 version). seems like they haven't decode. Like ignitionOn/Off harshbreak/acceleration, is there any specific reason for this or can this be done? 
I can see SOS, power alarms are working fine. this device has inbuilt alarm functions as well as OBD reader connection port. 
thanks.

**Comment by tananaev** [comment]
I would need HEX messages where you expect to see missing alarms, and protocol documentation.

**Comment by vithanagevms** [comment]
[GPRS Communication Protocol 7.0 (new） VT1000 .pdf](https://github.com/tananaev/traccar/files/1253560/GPRS.Communication.Protocol.7.0.new.VT1000.pdf)

Here i have attached the protocol document.
in the installation document, i can see we are connecting Ignition wire (ACC) to Input 4 (0x04 - ignitionOn, and  0x34 fot IgnitionOff),
as well as you can see some of the command we can send to the device. (for Engine Stop, Output 1)
Set authorization RFID, 

Alarm code Definition
=0x01 SOS button is pressed / Input port 1 close
=0x02 2nd button (Call B) is pressed / Input port 2 close
=0x03 3rd button (Call C) is pressed / Input port 3 close
=0x04 Input port 4 close
=0x05 Input port 5 close
=0x11 Over speed alarm
=0x12 movement alarm
=0x13 Geo fence alarm
=0x31 SOS button is released/Input port 1 open
=0x32 Call B button is released/Input port 2 open
=0x33 Call C button is released/Input port 3 open
=0x34 Input port 4 open
=0x35 Input port 5 open
=0X50 external power cut
=0x72harsh braking
=0x73 harsh acceleration
=0x75 camera error
=0x74 lose oil
=0x76 add oil
=0x14 impact alert


Thanks.

**Comment by tananaev** [comment]
I would need HEX as well.

**Comment by vithanagevms** [comment]
Hi,
here some hex codes, 
2424005a201708211fffff9934303030382c303030307c3131313132302e3030302c412c313534382e323436392c532c30333530332e363931332c452c302e30322c3330362e32332c3236303831372c2c2c412a373451c90d0a


2424005a201708211fffff9934303030302c303030307c3131313232302e3030302c412c313534382e323437312c532c30333530332e363930332c452c302e30352c3135342e34312c3236303831372c2c2c412a373964620d0a

Input 4 Open or Close
 2424007b201708211fffff99553131313432302e3030302c412c313534382e323530372c532c30333530332e363837312c452c302e30312c3232312e33312c3236303831372c2c2c412a37397c302e39367c313136342e307c303030307c303030302c303030307c3030303030303239367c303030303088cf0d0a
 2424005a201708211fffff9934303030302c303030657c3131313434392e3030302c412c313534382e323530302c532c30333530332e363836372c452c302e30322c3133362e39362c3236303831372c2c2c412a3744c75c0d0a

**Comment by tananaev** [comment]
I have added some new alarms, but I don't see anything about ignition.

**Comment by vithanagevms** [comment]
ignition should be input 4 
thanks 
![Uploading vt1000 Capture.PNG…]()

**Comment by tananaev** [comment]
Where does it say that?

Also, it seems like you didn't wait for the image to load.

**Comment by vithanagevms** [comment]
![vt1000 capture](https://user-images.githubusercontent.com/13207363/29741727-50e6c2ca-8a72-11e7-84ea-ae550694c660.PNG)

installation diagram.

**Comment by tananaev** [comment]
Where is diagram from? Can I see official documentation?

**Comment by vithanagevms** [comment]
Here i have attached the User Manual. 

[User Manual of GPS Tracker VT1000 _Topshine_(V4.3).pdf](https://github.com/tananaev/traccar/files/1253683/User.Manual.of.GPS.Tracker.VT1000._Topshine_.V4.3.pdf)

**Comment by tananaev** [comment]
It seems like it's just one example. It's not guaranteed that input4 will be connected to ignition.

**Comment by vithanagevms** [comment]
If we are not getting one of them as ignition, we are missing that important alert.
1-3 inputs are negative inputs, 4,5 are only positive inputs, so we must connect ignition to 4 or 5.
this is my propose as supplier guidance, (SOS button also connected to input 1)
thanks.

**Comment by tananaev** [comment]
Does "open" in documentation mean that input is active?

**Comment by vithanagevms** [comment]
Yes, open means vehicle is on state. (input percent ). sorry late reply.

**Comment by tananaev** [comment]
I have added support for inputs.

**Comment by vithanagevms** [comment]
Thank you, 
Did you add to the V3.9, can i get the jar file if possible.

**Comment by tananaev** [comment]
Not sure if you are familiar with software versioning, but nothing is ever added to existing versions. You need to wait for a next version of build from source yourself.
