### ISSUE TITLE
traccar.server table not found

### ISSUE THREAD

**Issue by parveenkumardeeva** [tananaev/traccar#3478]
```
Table 'traccar.servers' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:433 < *:317 < DataManager:357 < PermissionsManager:82 < ...)
```
I think the issue is in the line number 217 in the DataManager class where an extra "s" is attached to the table name for the query. In other place it's only server instead of servers.

**Comment by tananaev** [comment]
It should be "servers" everywhere. If it's not, then you are using some outdated files.

**Comment by parveenkumardeeva** [comment]
Pardon me If I'm wrong but still in your latest schema changelog files it's still server everywhere.
Does I'm forgetting some new configuration because just few weeks ago it was working fine?

**Comment by tananaev** [comment]
If you are using latest code, you have to take latest configuration file as well.

**Comment by parveenkumardeeva** [comment]
Thanks. I do have latest files but due to some issue not running the latest configuration.
Again, thanks for your support

**Comment by parveenkumardeeva** [comment]
I have all the latest code and yeah found it. <renameTable oldTableName="server" newTableName="servers" />

But restarting service doesn't apply the required changes to DB. Any way to run changelog-3.14.xml again?

**Comment by tananaev** [comment]
Only by manually modifying changelog tables.
