### ISSUE TITLE
/api/devices GET by uniqueId returns all instead of filtered

### ISSUE THREAD

**Issue by rkscott** [tananaev/traccar#3480]
According to the [api reference](https://www.traccar.org/api-reference/#operation--devices-get) , we should be able to use the _uniqueId_ parameter to fetch a single device.

As an example, the following php function should be able to return a single device with passed $identifier.
(curl function left out for clarity)
```
function getDeviceByIdentifier($identifier,$cookie) {
        $data='uniqueId='.$identifier;
        return curl('/api/devices?'.$data,'GET',$cookie ,'',array());
}
```

The above function works, but returns an array of all devices instead of just one.

(note:  the related option of filtering on _id_ works... i.e.  `$data='id='.$identifier;`  returns a single device)

(note2: traccar server version is 3.13)

**Comment by tananaev** [comment]
The `uniqueId` parameter was added after 3.13 release, so it will be available in the next version.

**Comment by rkscott** [comment]
Thanks Anton, that makes sense :-)  I see the addition [here](https://github.com/tananaev/traccar/commit/2aaa4a5e00e801b9b310e42f538113dd83e60188)
