### ISSUE TITLE
Image/Photos supported tracker(with Camera) device compatible with traccar server

### ISSUE THREAD

**Issue by darshan2210** [tananaev/traccar#3482]
Hello Anton,

Please suggest the gps tracker device with camera that send the image with regular interval and already have compatibility and ready to use support in traccar server.

Thanks

**Comment by tananaev** [comment]
Please carefully read this:

https://github.com/tananaev/traccar/blob/master/.github/CONTRIBUTING.md

**Comment by tananaev** [comment]
If you carefully read the link, you will hopefully realise that you are asking in the wrong place. For questions you should use forum:

https://www.traccar.org/forums/

**Comment by darshan2210** [comment]
Ohhh.

Sorry for that. I will raise same in forum.

Thanks.
