### ISSUE TITLE
Filtering and events

### ISSUE THREAD

**Issue by perseptron** [tananaev/traccar#3483]
Is it possible not to filter data with some event in it? Because I miss all low battery alerts when vehicles not move. (I  have enabled distance filter)
Thanks.

**Comment by tananaev** [comment]
Are you using latest release?

**Comment by perseptron** [comment]
yes, traccar-linux-3.13.zip, but OS is FreeBSD 11

**Comment by tananaev** [comment]
Unfortunately it's not possible for distance filtering, only for duplicate.

**Comment by perseptron** [comment]
It's pity... Have you any plans to fix it ?

**Comment by tananaev** [comment]
It's not something to "fix", but we can consider changing logic or adding some extra configuration.

**Comment by perseptron** [comment]
There are some improvement in last release (Pi-release 3.14) regards to my question, as I understand:
"Filtering exception for alarms, which means that you won't miss any important events because of distance or other filtering."
But I'm still missing alarm events. Is there some new configuration parameters to handle the situation?
My config:

<entry key = 'filter.enable'>true</entry>
   <entry key = 'filter.duplicate'>true</entry>
   <entry key = "filter.distance">20</entry>
   <entry key = "filter.maxSpeed">90</entry>

   <entry key = "database.registerUnknown">true</entry>
   <entry key = "coordinates.filter">true</entry>
   <entry key = "coordinates.minError">5</entry>
   <entry key = "report.trip.minimalTripDuration">300</entry>
   <entry key = "report.trip.minimalTripDistance">500</entry>
   <entry key = "report.trip.minimalParkingDuration">300</entry>
   <entry key = "report.trip.greedyParking">true</entry>

Thanks

**Comment by tananaev** [comment]
You need to set `filter.skipAlarms` to `true` in the config file.

**Comment by perseptron** [comment]
Yes, it works now, many thanks

**Comment by tananaev** [comment]
Note that in the next release there will be a slight change to this functionality. Something to keep in mind when you upgrade.
