### ISSUE TITLE
GT06 Protocol Vibration Alarm wrongly put as Powercut

### ISSUE THREAD

**Issue by kaustubhlohiya** [tananaev/traccar#3485]
I have configured Concox Wetrack 2 with traccar and it uses GT06 Protocol. I have configured vibration alarm for the device to send the alert via SMS as well as to the Platform. However what weird is happening is that on vibration alarm, the device is sending a vibration SOS message (SMS) to my number but when i check with traccar its being shown as powercut alarm. 

I ran this scenario multiple times with same result. To every vibration alarm that device send i get a powercut alarm in traccar instead of vibration alarm. For understanding i am attaching a screenshot from my mobile phone with message sent by the device and the mysql event table entry. If you compare the time, it will be clear that device is sending Vibration Alarm and Traccar is inserting Powercut in the DB

![20170828_180633 1](https://user-images.githubusercontent.com/11457279/29773697-23f68718-8c1c-11e7-9d6b-9527908cb05a.png)

MYSQL ENTRIES: 

'9309', 'alarm', '2017-08-25 18:58:59', '19', '126279', NULL, '{\"alarm\":\"powerCut\"}'
'9389', 'alarm', '2017-08-25 19:06:03', '19', '127056', NULL, '{\"alarm\":\"powerCut\"}'
'9411', 'alarm', '2017-08-25 19:07:55', '19', '127227', NULL, '{\"alarm\":\"powerCut\"}'
'9955', 'alarm', '2017-08-25 20:31:07', '19', '133491', NULL, '{\"alarm\":\"powerCut\"}'
'9966', 'alarm', '2017-08-25 20:32:47', '19', '133597', NULL, '{\"alarm\":\"powerCut\"}'
'10096', 'alarm', '2017-08-25 20:57:56', '19', '134978', NULL, '{\"alarm\":\"powerCut\"}'

Can you please confirm and let me know if this is actually an bug or am i missing something.

**Comment by kaustubhlohiya** [comment]
While browsing through the Forum i think this issue is same as #3481 . Can you please confirm and tell me how to fix this if its the same as 3481

**Comment by tananaev** [comment]
If it's the same issue, the fix will be merged into the master branch soon.

**Comment by kaustubhlohiya** [comment]
I just updated to Traccar 3.14 and now Vibration Alarm is put as Geofence Enter. 

  | 12 | alarm | 2017-09-06 17:13:37 | 1 | 16 |   | {"alarm":"geofenceEnter"}
-- | -- | -- | -- | -- | -- | -- | --
  | 13 | alarm | 2017-09-06 17:15:18 | 1 | 20 |   | {"alarm":"geofenceEnter"}

These are actually Vibration Alarm sent by the device.

**Comment by tananaev** [comment]
It is already fixed. You can either build from source code or wait for next release.

**Comment by kaustubhlohiya** [comment]
Thanks.
