### ISSUE TITLE
Speeds not converted according to display units

### ISSUE THREAD

**Issue by 9662** [tananaev/traccar#3486]
### To reproduce

1. Log some data with Traccar
2. Display some of the data on-screen (e.g., reports, state, … doesn't matter)
3. Take note of the speed units and speed value, e.g., 50 kt
4. Change the speed units in the preferences
5. Refresh and look at the speed units and value again

### Actual results

The speed units have changed, but the value hasn't. E.g., where before it displayed `50 kt` now it may show `50 km/h`.

### Expected results

The speed values should be converted according to a) their original units and b) the display units. E.g., if a speed input was recorded as `25.7 m/s` it should be shown as `50 kt`, `92.5 km/h`, etc.

Tested with Traccar 3.13 on Linux.

**Comment by tananaev** [comment]
I just tested and it works for me.

**Comment by 9662** [comment]
Strange. Now it works for me too. 😛
