### ISSUE TITLE
Wrong speed with OsmAnd?

### ISSUE THREAD

**Issue by 9662** [tananaev/traccar#3487]
If I configure OsmAnd~ 2.7.5 online logging as follows:

`http://example.com:5055/?lat={0}&lon={1}&timestamp={2}&hdop={3}&altitude={4}&speed={5}& bearing={6}&id=666&trip=Test+2`

The speeds reported in Traccar are incorrect: it shows half the actual speed in km/h. For example, driving at 50 km/h results in values around 25 being displayed (see also #3486 concerning units). Driving at 70 km/h shows values around 35.

Car speeds were stable due to cruise control. Odometer speeds are unusually accurate (1 km/h slow). Speeds on OsmAnd are shown correctly as 50 km/h and 70 km/h (plus/minus GPS jitter).

**Comment by tananaev** [comment]
What units does OsmAnd send speed in? Traccar expects knots.

**Comment by 9662** [comment]
> What units does OsmAnd send speed in? Traccar expects knots

Metres per second. Not configurable, as far as I can tell.

**Comment by 9662** [comment]
I'm about to try this, see if works:
![computed-attribute-speed](https://user-images.githubusercontent.com/13080040/29816905-4dab4068-8cb6-11e7-9f06-b754527ad653.png)

The intention being to

**Comment by 9662** [comment]
Nichts! Ne srabotalo at all 😢
