### ISSUE TITLE
FR: user-configurable max zoom level

### ISSUE THREAD

**Issue by 9662** [tananaev/traccar#3489]
User story:

> As a custom map user, I need to be able to set a maximum (occasionally also minimum) zoom level appropriate to the level of detail of my map and intended usage (e.g., indoor tracking).

**Comment by tananaev** [comment]
Good point. It should be in web app repository though:

https://github.com/tananaev/traccar-web

**Comment by 9662** [comment]
Argh! Does GitHub support moving issues across repositories? I can't seem to be able to do that myself.

**Comment by tananaev** [comment]
No, but let's leave it here. It's OK.

**Comment by 9662** [comment]
👍

**Comment by 9662** [comment]
Related: #1340
