### ISSUE TITLE
TK06B GPS tracker, receiving connection request repeatedly

### ISSUE THREAD

**Issue by mkgangola** [tananaev/traccar#3492]

**Comment by tananaev** [comment]
Please provide description or close the issue.

**Comment by mkgangola** [comment]
This is first time I wrote in github... sorry for that missing part

I am trying to integrate TK06B GPS device tracker to my listener , I need help for below points
1. Protocol document , The one I have seems not correct
2. device keep sending connection request in every 10 sec repeatedly  to send the data to server , while my other tracker sends connection request only if somehow they disconnected due to nw or any other reason. 


Please suggest 

BR

**Comment by tananaev** [comment]
How is your question related to Traccar project?

As for protocols, you can find documents here:

https://www.traccar.org/protocols/

**Comment by mkgangola** [comment]
Resolved

**Comment by mkgangola** [comment]
resolved
