### ISSUE TITLE
Web Time Issue

### ISSUE THREAD

**Issue by yudhaprimadiansyah** [tananaev/traccar#3494]
Hello, Im using traccar 3.12 and i have time issue in traccar server.. i have configured all the devices to GMT+7 through SMS text, i have checked  the fix time in logfile and it seems correct.. but, when i look at the state tab > time section in web, it shows incorrectly.. even i set server config to GMT+7 it still not fixed my problem yet.. 
![image](https://user-images.githubusercontent.com/29807969/29905505-645d14c4-8e39-11e7-9d1c-f846b76ff394.png)

![image](https://user-images.githubusercontent.com/29807969/29905533-7b25aa0e-8e39-11e7-9e86-12ff914f86a1.png)

**Comment by tananaev** [comment]
Traccar expects UTC time, so you should configure your devices to report in UTC timezone.

**Comment by yudhaprimadiansyah** [comment]
yes, i have configured it to UTC+7 sir.. so sorry before, i meant UTC+7.. log files show correctly.. but not in web..

**Comment by tananaev** [comment]
`UTC` means `UTC+0`.

**Comment by yudhaprimadiansyah** [comment]
hmmm.. so i should setting up time in my devices to UTC ? or in web configuration.. thanks for fast respond :))

**Comment by tananaev** [comment]
Please read my comments more carefully.

**Comment by yudhaprimadiansyah** [comment]
ok.. im understand.. so sorry.. i have confused in last 3 days.. i hope it fixes my problem.. thanks..

**Comment by yudhaprimadiansyah** [comment]
but i think it has no problem with the devices .. it shows correctly.. it stored in my database, but when the web printout the time state it shows incorrectly..
![image](https://user-images.githubusercontent.com/29807969/29905928-a9634690-8e3b-11e7-8aca-e6e233b9df64.png)

**Comment by tananaev** [comment]
As far as I can see from your log screenshot, it's not correct. It's 7 hours ahead of server time.

**Comment by yudhaprimadiansyah** [comment]
yess server time has 7 hours time differences with my country sir :)) i put my server in AWS

**Comment by tananaev** [comment]
No, I think you don't understand. Server time has to match device time in the logs.

I already told you that you HAVE TO configure device to report UTC time. I'm not sure why you are arguing.

**Comment by yudhaprimadiansyah** [comment]
ok.. i have tried to fix the device time to match with the server.. and it fixed my problem.. thanks..... so sorry for that.. im an passive english so my english not enough... and im in confused... so i didnt focus..
