### ISSUE TITLE
Commands improvement

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3496]
I'm developing this https://github.com/tananaev/traccar-web/issues/568 and want to discuss some things related to server side.

Some devices have `devicePassword` to send command, we can set additional password parameter in command attributes every time or set it in device attributes ones. https://github.com/tananaev/traccar/blob/master/src/org/traccar/BaseProtocolEncoder.java#L31

Some other protocols require send IMEI like password https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Tk103ProtocolEncoder.java

- Can we implement function `initUniqueID` that will take `deviceUniqueId` if it is omitted in command attributes?

-  Some protocols need password, some imei, some nothing. To dynamically add password or imei field to command dialog we somehow need to notify web-part about it. I can't find simple way to do that. I see two options: always add password and uniqueId fields to send command dialog. Or opposite do not add this fields and take them only from device fields/attributes. What do you think?

**Comment by tananaev** [comment]
We never send `uniqueId` in attributes because it's already available on the server. Or am I missing something?

Password is more complicated, but I think we can just ask user to provide it in device attributes. It's possible to get it from command attributes as well, but this option is mostly for API use.

**Comment by Abyss777** [comment]
Oh, sorry, It is me who missed something. We already initialize `uniqueId` from device.

Got it for password, I incline to the same.

**Comment by Abyss777** [comment]
Another suggestion... now we are setting timezone (for command) in hours and pass in command attributes in seconds. But we already have list of all timezones names on web side and can make selection convenient for user.
We can pass timezone name from web side and convert it to necessary offset on server side. Just can't decide: introduce new attribute like `Command.KEY_TIMEZONE_NAME` or automatically detect `Command.KEY_TIMEZONE` string value. Or maybe even accept only timezone names.

**Comment by tananaev** [comment]
Agree in general. As for approach, whatever is easier and nicer is probably the right way.

**Comment by Abyss777** [comment]
All necessary server side changes for https://github.com/tananaev/traccar-web/pull/571 was implemented. Closing this.
