### ISSUE TITLE
Question: Supported Attributes per Device

### ISSUE THREAD

**Issue by parveenkumardeeva** [tananaev/traccar#3503]
Hi,

I have searched all issues regarding Attributes per Device but can't find the exact answer for the following questions.

1. How can we find total number of supported attributes per device via an API request?

2. What are computed attributes? Are computed attributes and attributes are same or we have to perform some operation to attach a particular attribute to a device?

Please give me a suitable link or any explanation.

For ex. 

I want to fetch the attributes of a Device or a particular protocol.
Let's take an example GT06 protocol. 
So, How can I access all the attributes so that I can map one attribute to another for the sake of convenience?

**Comment by tananaev** [comment]
1. There is no limit on number of attributes, if that's what you are asking.
2. There is official documentation on the official website.

There is no way to enumerate all attributes supported by a protocol. Also, device attributes are not the same as position attributes.

**Comment by parveenkumardeeva** [comment]
Thanks for the support. I got the exact point.
