### ISSUE TITLE
Spelling for word Satellites V 3.14

### ISSUE THREAD

**Issue by visiondrive** [tananaev/traccar#3506]
Can we get this corrected for the next release/update thanks.

Should read   Satellites

![satellites](https://user-images.githubusercontent.com/30918638/30098587-daa2af54-9325-11e7-863a-189d96ad8650.jpg)

**Comment by tananaev** [comment]
Fixed:

https://github.com/tananaev/traccar-web/commit/f819f04cc8fbc85c299ca647707364a2436d8987

Next time please use correct repository.

**Comment by visiondrive** [comment]
Sorry - thought I got the right one!

Regards

[cid:96999E65-F250-454C-9DEE-B175E5FDDCA0@netgear.com]



VISIONDRIVE In-Vehicle Drive Recorders - Protect yourself, your family and your property

VISIONDRIVE PTY LTD ABN 13 158 841 288
John Asson em   sales@visiondrive.net.au<mailto:sales@visiondrive.net>
PO BOX 506 wb    www.visiondrive.net.au<http://www.visiondrive.net.au>
VARSITY LAKES QLD 4227 mb   +61 (0) 419 225 722
AUSTRALIA fx     +61 (0) 7 3112 4117

On 6 Sep 2017, at 5:16 pm, Anton Tananaev <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed:

tananaev/traccar-web@f819f04<https://github.com/tananaev/traccar-web/commit/f819f04cc8fbc85c299ca647707364a2436d8987>

Next time please use correct repository.
