### ISSUE TITLE
Attribute types mixing

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3508]
I have found the problem, why web part always send all attributes as strings [Attribute.js#L29](https://github.com/tananaev/traccar-web/blob/master/web/app/model/Attribute.js#L29)
But looks like it is too late... server in some cases rely that it is string
Here for example [NotificationMail.java#L46](https://github.com/tananaev/traccar/blob/master/src/org/traccar/notification/NotificationMail.java#L46) it will fail on casting integer to string

On the other hand we handle both `"true"` and `true` here [ExtendedModel.java#L103](https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/ExtendedModel.java#L103)

I do not know what to do, on the one hand we should send correct attributes with correct types string/number/boolean from web client. On the other hand we have a lot of installations where already some values stored as strings and we should handle both correct and incorrect (should we?) variants.

**Comment by tananaev** [comment]
It would be great if we can save proper value types. Temporary (for a year or so?) we can handle both options on the server side and eventually we can stop supporting strings.

**Comment by Abyss777** [comment]
Closing as resolved in #3511
