### ISSUE TITLE
hello  I make our own server and write listener in php but its give me same value every time 

### ISSUE THREAD

**Issue by Himanshu1986R** [tananaev/traccar#3512]

**Comment by Himanshu1986R** [comment]
$address = 'ip';
$port = port;
// Create a TCP Stream socket
$sock = socket_create(AF_INET, SOCK_STREAM, 0); // 0 for  SQL_TCP
// Bind the socket to an address/port
socket_bind($sock, 0, $port) or die('Could not bind to address');  //0 for localhost
// Start listening for connections
socket_listen($sock);
while (true) {
	/* Accept incoming  requests and handle them as child processes */
	$client =  socket_accept($sock);
	
	$input =  socket_read($client, 1024000);

	echo $input.PHP_EOL;

	if($input) //check for imei number here
	{
		socket_write($client, "\x01");
		$output=socket_read($client, 1024000);
		
		var_dump(bin2hex($output));

} }

**Comment by tsmgeek** [comment]
ehh, how is this related to traccar?

**Comment by tananaev** [comment]
It's not, so I'm closing this.
