### ISSUE TITLE
FR: do not filter command results

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3513]
Command result usually comes without real position, we construct it from last one. It is very likely it will be filtered by duplicate or distance.
What do you think about adding new switch to exclude from filtering positions with command results? Like we do for alarms #3484

**Comment by tananaev** [comment]
How about more generic solution? For example, do not filter position if it has an attribute from a specified list.

**Comment by Abyss777** [comment]
Nice idea, what can be more flexible.
May be implement in the way how we do it in `CopyAttributes` https://github.com/tananaev/traccar/blob/master/src/org/traccar/processing/CopyAttributesHandler.java#L35 also with lookup device->group->config?

Frankly, I know what can be more flexible... it is JEXL expression instead of keys list, but it is overcomplicated... or?

**Comment by tananaev** [comment]
Yes, I think JEXL would be overkill, but the way copy attributes is implemented is fine IMHO.
