### ISSUE TITLE
Concox GT06 "Date Time" in the past always the same

### ISSUE THREAD

**Issue by harriswilliam** [tananaev/traccar#3515]
Hello, I am integrating the device Concox GT06 in our system and i am facing a problem:
**The Date time parameter is a past date, and is always the same.**  in every message

For example now it is 2017-09-08 17:28 , but the date coming from device is always 
**<11 08 08 11 14 24>**  that is  **2017-08-08 17:20:36**

Here is the complete Hex data coming from device:
**<78781f12110808111424c603f3f0c80118570611d54f025d030471003afe000d96e30d0a>**

What can cause this problem ? I have always rebooted the device with SMS command **RESET#**

Thanks in advance for your help

**Comment by tananaev** [comment]
You have to configure your device to report UTC time.

**Comment by harriswilliam** [comment]
Hello, Thanks for your answer.

The device is already configured to UTC+1 (my current location is Tunisia).

But the Date Time is always the **same in every messages** and is **a past date**.

**Comment by tananaev** [comment]
Device has to be configured to UTC which is UTC+0. If you see same old date, it probably means that either device sends old data for some reason (possibly no GPS signal) or it doesn't send any location data at all.

**Comment by harriswilliam** [comment]
Well.

We have just RESET the device and reconfigured it! and now it is OK, the device is sending actual date.
(what I doesn't understand is that I had made it last friday but it didn't solve the problem that day) 

Anyway; now the problem is solved.

**Comment by salk52** [comment]
> Hello, I am integrating the device Concox GT06 in our system and i am facing a problem:
> **The Date time parameter is a past date, and is always the same.** in every message
> 
> For example now it is 2017-09-08 17:28 , but the date coming from device is always
> **<11 08 08 11 14 24>** that is **2017-08-08 17:20:36**
> 
> Here is the complete Hex data coming from device:
> **<78781f12110808111424c603f3f0c80118570611d54f025d030471003afe000d96e30d0a>**
> 
> What can cause this problem ? I have always rebooted the device with SMS command **RESET#**
> 
> Thanks in advance for your help

Hi.
I have the same problem. How did you set Timezone. What was your solution?

Thanx
