### ISSUE TITLE
Event Based Data sending

### ISSUE THREAD

**Issue by Emad1995** [tananaev/traccar#3519]
Can we change Traccar-Client to implement Event based data sending to the server instead of Time based or is there something already something similar to this implemented already.

**Comment by tananaev** [comment]
What events are you talking about?

**Comment by zoogor** [comment]
events such as acceleration, deceleration, stopping, starting,if the driver takes a sharp turn,low battery and some others....

But I only need the data when such event take place other than that server shouldn't record the data sent by the client.Is this already implemented or will I have to do it manually and if I have to do it manually any suggestion how to do this.


Sorry for such a late reply and Thanks for the help in advance

**Comment by tananaev** [comment]
There are already events.

**Comment by zoogor** [comment]
and is there a way I can restrict my android client app to send update **only if** some events that i specify occur

**Comment by tananaev** [comment]
You need to be more specific.
