### ISSUE TITLE
distanceunit and speedunit issue in Traccar 3.14

### ISSUE THREAD

**Issue by kaustubhlohiya** [tananaev/traccar#3521]
Traccar API is throwing the following error after upgrading to 3.14 version

> Unrecognized field "distanceUnit" (class org.tracc…ce chain: org.traccar.model.User["distanceUnit"])

Also i can see that in database the fields have been removed. Please advise

**Comment by tananaev** [comment]
It has been removed. You need to use `distanceUnit` attribute instead.

**Comment by kaustubhlohiya** [comment]
The Web UI is also throwing the following error

Unrecognized field "distanceUnit" (class org.traccar.model.User), not marked as ignorable (20 known properties: "readonly", "deviceLimit", "name", "latitude", "phone", "admin", "userLimit", "zoom", "twelveHourFormat", "attributes", "deviceReadonly", "token", "id", "email", "longitude", "password", "map", "coordinateFormat", "disabled", "expirationTime"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@bdb08aa; line: 1, column: 167] (through reference chain: org.traccar.model.User["distanceUnit"])

**Comment by tananaev** [comment]
It means that you are using outdated web UI. I'm closing this. Please check everything properly before raising an issue.
