### ISSUE TITLE
/api/positions responds with Device access denied

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#3523]
Hello,

I upgraded my instance to latest version 3.14 of traccar.  
Using API's only to communicate with traccar. and everything had been working well before.

I am calling the `api/reports/events?`
and then with the positionId returned in the above api call, I query  `/api/positions`  with the positionId for the position details, it was working well until 3.13

However with 3.14 the `/api/positions` call is returning an error as follows.

When the user is a manager.
`Device access denied - SecurityException (PermissionsManager:276 < PositionResource:76 < ...)`

When the user is an end-user
`Manager access required - SecurityException (PermissionsManager:158 < *:270 < PositionResource:76 < ...)`

I have tried troubleshooting, Unable to figure out the cause.

**Comment by tananaev** [comment]
Most likely you are missing `Accept` header. I has been discussed and explained many times.
