### ISSUE TITLE
Feature request: Administrative Events

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3528]
I remember a few questions about how to know who added or changed a device or when a user log in or log out.
Like a solution we can write some Administrative Events in DB when user manipulate objects create/change/delete/link/unlink. User login, Distance reset, command sent (I know it is logged, but who sent is not)

Or may be just write them in log.

**Comment by tananaev** [comment]
I think we should separate any admin/user activity logging from other events. One exception might be commands because it is related to the device, but I'm not sure if we really need it to be separate.

Possibly logging all the information in the log file will be sufficient.
