### ISSUE TITLE
slight changes in Meitrack protocol

### ISSUE THREAD

**Issue by slachtar** [tananaev/traccar#3535]
Hi Anton,
Meitrack introduced slight changes in protocol version 3.
The changes seems to affect the way temperature sensor values are being calculated, indeed when protocol number is 3, the tempreature value should be translated to decimal then divided by 100 (please check page 8 of the attached official doc of meitrack).

For older protocol, we interpret the first two hex as decimal part and the next two hex as floating point part.

It applies to new trackers, like T366G.

Example of data received:
Example of data received from tracker:
in HEX:
```
2424563137372c3836333833353032363837313137332c4141412c33352c33342e3531363432382c31302e3437303136302c3137303931353135343034332c412c392c31322c36382c37342c302e392c392c313938383235392c3532353838322c3630357c327c303038437c30303037423541362c303230302c303030337c303030307c303030307c303141367c303537312c30303030303030312c2c332c303030302c3031304139322c3336302c3531312a37340d0a
```
in ascii:
```
$$V177,863835026871173,AAA,35,34.516428,10.470160,170915154043,A,9,12,68,74,0.9,9,1988259,525882,605|2|008C|0007B5A6,0200,0003|0000|0000|01A6|0571,00000001,,3,0000,010A92,360,511*74 
```

**010A92** is temp sensor number then its value.
Old protocol, tells that sensor number 1 (temp0 in traccar) value is 10.146 which is wrong.
Applying protocol 3, temp0 value is 0A92 which translates to 2706 decimal then divided by 100 and gives **27.06** which is the correct value tested in real life.

So we need to interpret differently depending on protocol number.

Best Regards,
[T366_MEITRACK_GPRS_Protocol--20170220.pdf](https://github.com/tananaev/traccar/files/1313722/T366_MEITRACK_GPRS_Protocol--20170220.pdf)

**Comment by tananaev** [comment]
The problem is that format is different for different devices and/or versions.

**Comment by slachtar** [comment]
Thank you Anton for the quick reply, as usual :+1: 
Everything thing works well on my side (position, speed, etc) except for temperature which is not detected.
According to meitrack, the new format applies only for protocol version number 3. Of course protocol version is included in data packet.

**Comment by tananaev** [comment]
To fix the problem I would need to know all possible formats.

**Comment by slachtar** [comment]
I don't know which information is missing, doesn't the document I attached include all formats for protocol number 3?
Please let me know if any other document/information is missing?

**Comment by tananaev** [comment]
Only for protocol number 3. As I said, I need all possible formats.

**Comment by slachtar** [comment]
Attached the protocol for older versions, which is already implemented in traccar.
I asked the question for meitrack and they send me the two files, this one for older trackers and the one I attached in the begining (attached again) for new trackers which include all formats.

[T366_MEITRACK_GPRS_Protocol--20170220.pdf](https://github.com/tananaev/traccar/files/1313890/T366_MEITRACK_GPRS_Protocol--20170220.pdf)
[Uploading MVT600 MEITRACK_GPRS_Protocol.pdf…]()

**Comment by slachtar** [comment]
I'm not very good in java coding, but may be you need to detect T366 model, like you did for other devices in https://github.com/tananaev/traccar/blob/c82fd979ad17ecfb7dd8f3e366c067b66f4cdabc/src/org/traccar/protocol/MeitrackProtocolDecoder.java

and then apply the new formula for that type of trackers when calculating temperature.

May be stupid, just a thought!

**Comment by tananaev** [comment]
I would probably need more official answer Meitrack. It seems like protocol is device-specific.

**Comment by slachtar** [comment]
Do you mind, if I put you in touch with meitrack engineers by email?

**Comment by tananaev** [comment]
Sure.
