### ISSUE TITLE
Dynamic IP

### ISSUE THREAD

**Issue by andi968** [tananaev/traccar#3536]
Hi Anton
I am using Traccar Manager on my iPad, my ISP supplies my service with a dynamic ip that recently changes every few days. The only way I have found to update the ip is to uninstall the app and reinstall it, which is a bit of a bind.
I have found Traccar Manager+ which allows you to change server at each log in, do you intend updating your version also to include this feature in the near future? I would prefer to use your app opposed to the other version.

**Comment by tananaev** [comment]
You should use dynamic DNS service instead of changing IP address every time.

**Comment by andi968** [comment]
I can not get theiPad Manager app to accept a dns  address ie “example.ddns.net” unlike the client app which after last update now accepts “http://example.ddns.net:5055” or am I missing something ?

**Comment by tananaev** [comment]
You are definitely missing something. What is your server URL?

**Comment by andi968** [comment]
Mercbit1.ddns.net

**Comment by tananaev** [comment]
Works for me just fine:

http://mercbits1.ddns.net:8082

**Comment by andi968** [comment]
Amazing, works 😀
Thanks for your support.
Can you edit out my server above please.
I notice there’s a few new apps on the App Store now that look very much like your hard work.

**Comment by tananaev** [comment]
Updated my comment.
