### ISSUE TITLE
Checks for Valid in event handlers

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3539]
I'm testing teltonika FMB920 and faced with problem that traccar does not detect motion/stop. The problem is that stopped positions device reports as not valid.

We have checks for Valid in some events handlers. I think we should remove them from handlers not related to coordinates:
- motion
- fuel drop

But about motion I have some doubts... On the one hand, if motion automatically calculated from speed it might be incorrect for invalid position, on the other hand if motion reported from device it is correct even if position is invalid.

@tananaev what do you think?

**Comment by tananaev** [comment]
Makes sense to remove check for fuel handler. For motion we can make it optional, similar to geolocation handler.
