### ISSUE TITLE
Error on URL

### ISSUE THREAD

**Issue by EasywareMX** [tananaev/traccar#3542]
Hi Anton, do you know why when i'm accessing to mobile version from mobile navigator or application, my traccar send error in URL. This is my url accessing: (Example) gps.mydomain.com/m/

the error come the firstime that I open the app, something like this;
 
gps.mydomain.com/m/**/JIWERJ/JASDsDFA/QUES**

I DON'T understand, then close the app and open again and it works fine. Some times it happens when i access by web to.

Please help me!

**Comment by tananaev** [comment]
I suspect that you are not using official version. There is no "/m/" path in official Traccar.

**Comment by EasywareMX** [comment]
Well you right, but, any help? :(

**Comment by tananaev** [comment]
My suggestion would be to use official Traccar. Otherwise I won't be able to help.

Closing as it's not related to the project.
