### ISSUE TITLE
error creating notification using latest github code

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3545]
Hi...I'm not sure if this is the correct location for this issue. I pulled the latest code from github and tried to use the per device notification by creating a new notification but I get the error below. This happens when I'm using an old database. Allowing traccar to generate a new database does not generate the error. Does this mean we cannot use an old database with this new feature or is there a way for traccar to add this database column to an older database so it doesn't throw the error?

![screen shot 2017-09-22 at 8 58 45 am](https://user-images.githubusercontent.com/15850216/30748183-174f1d6a-9f75-11e7-99d8-9e96df4b1a1d.png)

**Comment by tananaev** [comment]
In almost every release we make modifications to the database schema. It's done automatically using changelog files.

**Comment by socstur** [comment]
Do you have any recommendation on what to do to keep testing before the release?

**Comment by tananaev** [comment]
If you want to test it, you should create a separate changelog for every database modification that we do.

**Comment by socstur** [comment]
ok thanks

**Comment by socstur** [comment]
Hi Anton,
               Sorry to bother you again on this but I'm trying to get a better understanding of what is happening here if you can help me. It looks like 3.15 adds new tables to the traccar database...does this mean it won't work with databases from older versions of traccar? or the old database has to be migrated to a new one?

**Comment by tananaev** [comment]
As I said earlier, we change database all the time. It is automatically migrated from previous versions using Liquibase library.

**Comment by socstur** [comment]
ok got it, Traccar inserts the new tables into the old database. It all makes sense now. Thanks!
