### ISSUE TITLE
Handle MCC and MNC is incorrect

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3546]
We store MNC as `Integer` https://github.com/tananaev/traccar/blob/master/src/org/traccar/model/CellTower.java#L89

But we should not do it in this way. According to [Wikipedia](https://en.wikipedia.org/wiki/Mobile_country_code) it is
> the mobile network code consists of 2 or 3 decimal digits (for example: MNC of 001 is not the same as MNC of 01)

But for integer it is the same `1`
 
MCC is not so significant because fist digit `0` used only for test networks, but still...

**Comment by Abyss777** [comment]
Interesting, but all our geolocation api providers treat them as integer.

**Comment by Abyss777** [comment]
Why nobody cares of standards :worried:
https://developer.android.com/reference/android/content/res/Configuration.html#mnc
and at the same time https://developer.android.com/reference/android/telephony/TelephonyManager.html#getNetworkOperator()

**Comment by tananaev** [comment]
I think the most important question is whether it's possible to have conflicting MNC in the same country. I looked through wikipedia and it doesn't seems like there are any examples of that:

https://en.wikipedia.org/wiki/Mobile_country_code

Also in most APIs it's a number, so I suspect that we don't need to worry about it:

https://developers.google.com/maps/documentation/geolocation/intro

**Comment by Abyss777** [comment]
There are the same MNC in one country USA, but with different MCC.
OK, if it works in US and in Google, it is not that thing we should worry about. False alarm.
