### ISSUE TITLE
Not able to set IP in TK devices

### ISSUE THREAD

**Issue by jkhasiza** [tananaev/traccar#3549]
Hi,
I am using traccar server code for decoding TK103 devices.
I am not able to set IP and Port through sms in those devices.
SMS command is **ip +ip address+port +port number**, device is not responding to this command.

**Comment by tananaev** [comment]
How is it related to the server? If you want to ask your question do it on forum:

https://www.traccar.org/forums/forum/devices/

**Comment by jkhasiza** [comment]
Yes, this is not related to server.
I am looking for sms configuration for initial setup. Please share if you have it?
