### ISSUE TITLE
Email Server-wide Vs Per-user configuration

### ISSUE THREAD

**Issue by inghoward** [tananaev/traccar#3552]
I've noticed that when server-wide email configuration is done then Per-user don't work. Traccar always sends email using the default, not the user configured SMTP server. Is that the desired behavor?

A user might want to use their own SMTP server, not the default server-wide. Is that possible to change this behavior

**Comment by tananaev** [comment]
@Abyss777, do you remember if there was any specific reason we decided to prefer server config? Would you see any problem in reversing this?

**Comment by Abyss777** [comment]
If I'm not mistaken, we just considered two use cases:
- Traccar used in company, and it is configured by admin, per user configuration is unwanted
- Traccar is public service, and every user have to configure own smtp server.

I think we can add some switch in config to allow traccar use user configuration even if it has server one.

**Comment by tananaev** [comment]
There is already a flag to force server configuration, so we should probably change the priority to user config unless that flag is set.

**Comment by Abyss777** [comment]
There might be a use case when customer do not want force all settings and want not allow override smtp server. For example company with branches in different time zones or different countries.

**Comment by tananaev** [comment]
Force server settings is a separate flag and is disabled by default.

**Comment by Abyss777** [comment]
Yes, but it is used for determine timezone for reports and respected in web client for units and other user/server settings.

**Comment by tananaev** [comment]
I see three options:

1. Keep current behaviour of preferring config
2. Change behaviour to prefer user settings
3. Second one plus force flag

Third one seems like the best option. Any other options?

**Comment by Abyss777** [comment]
Yes, I think...

4. Second one with "Allow per user SMTP configuration" flag. False by default, but true in default config.

Because we do not have a way totally disable email notifications. I know one use case when traccar is the only server connected to internet, and email notifications can be considered as information leakage.
I understand that email costs much less than SMS, but there is other consequences of uncontrolled email sending, like pure sender reputation (SPAM) or network load or others.

**Comment by tananaev** [comment]
I guess that's also an option, but probably better to make it reverse like `mail.smtp.ignoreUserConfig`.

**Comment by Abyss777** [comment]
OK. I'll take it.
