### ISSUE TITLE
[Feature request] Stops report api

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#3554]
Hi,

There is no api to access stops report from the api document https://www.traccar.org/api-reference/.

Please add Stops report api.

If already added please close the issue.

Thanks.

**Comment by tananaev** [comment]
Official web app uses API, so there is an API. I just haven't updated the documentation yet. I would recommend you to check requests that web app sends to the server.

**Comment by kirantpatil** [comment]
Thanks @tananaev
