### ISSUE TITLE
Safari not displaying the expand cross correctly to change server properties

### ISSUE THREAD

**Issue by JohnnyDevine** [tananaev/traccar#3568]
I cannot change a user to 'ADMIN' in safari as the expand cross is not displayed correctly, its like that in a few other windows also....this is on high Sierra 13.1 and the server is Debian stretch. I had to do it on a windows 10 box

JD

**Comment by tananaev** [comment]
Screenshots please.

**Comment by JohnnyDevine** [comment]
Hi Anton, Sorry I should have included....
<img width="341" alt="screen shot 2017-10-06 at 08 10 56" src="https://user-images.githubusercontent.com/11890336/31266894-eefc0144-aa6d-11e7-9df0-c29a03330408.png">
JD

**Comment by JohnnyDevine** [comment]
I should also say, this was a clean install on a freshly built stretch machine with only the JRE installed as extras so really clean.

**Comment by tananaev** [comment]
The problem on Safari is a known one in ExtJS. We need to wait for a new version of the library.

**Comment by tananaev** [comment]
I have implemented a workaround:

https://github.com/tananaev/traccar-web/commit/329941595ebab576788bc5646389bd27ae6f614d
