### ISSUE TITLE
Time offset for each device

### ISSUE THREAD

**Issue by mclei** [tananaev/traccar#3572]
Please implement configurable time offset for each device. There are plenty of cheap Chinese GPS trackers with poor documentation where correct time zone is impossible to setup. Even when using multiple GT06 devices, it is not possible to configure this "globally" as each device sends different timezone timestamp.

So I think the best is to add device attribute with Time Offset, so I can specify different offset for particular device.

**Comment by SahuMohit** [comment]
Any Update regarding this ?

**Comment by tananaev** [comment]
Not as far as I know.

**Comment by SahuMohit** [comment]
@tananaev thanks

**Comment by Abyss777** [comment]
I'm thinking of this feature, we already have experience with users/server `timezone` attribute, it makes sens to implement device/group `timezone` attribute in the same way.
But we have old behavior with config parameter `[protocol].timezone` as offset in seconds.

We have already implemented functions to lookup attribute device->group->server or device->group->config. If we use first one server timezone may not fit to devices, if we use second one we get unneeded lookup `timezone` in config. I think use second one and additionally lookup `[protocol].timezone` in config for backward compatibility. Any other ideas?

**Comment by tananaev** [comment]
I agree with the second option to fallback to config. As for the value, how about we throw exception if it's in old format? It will force people to update their configs to start server. And in one of future releases (in a year or so) we can drop it completely.

**Comment by Abyss777** [comment]
Is it OK if we do not have per protocol timezone in future?

**Comment by tananaev** [comment]
I think it's even better if we can implement a more universal solution.

**Comment by Abyss777** [comment]
Hm...I also thought, we will get server attribute `timezone` it is mostly for reports and notifications, and config `timezone` for overriding devices timezone. Can it be confusing?

**Comment by tananaev** [comment]
I don't think so. We just need to use some clear key. For example `decoder.timezone` or something like that.

**Comment by Abyss777** [comment]
Hm, looks like GT06 basic devices report their timezone in login message https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/Gt06ProtocolDecoder.java#L401

As I understand it should be applied to all other messages from this device, what do you think about extending `DeviceSession` with timezone?

**Comment by tananaev** [comment]
I don't see any problem with it.
