### ISSUE TITLE
fixtime calculating

### ISSUE THREAD

**Issue by sergbbb** [tananaev/traccar#3573]
Hello.  I see this 
http://take.ms/TQK8E

Why fixtime every time changing ? Tracker send in UTC (GMT 0). 

Config:

`<entry key='filter.enable'>true</entry>`
`<entry key='filter.invalid'>true</entry>`
`<entry key='filter.zero'>true</entry>`
`<entry key='filter.duplicate'>true</entry>`
`<entry key='filter.distance'>35</entry>`
`<entry key='filter.future'>28800</entry>`

Thank you.

**Comment by tananaev** [comment]
Because you have time from future.

**Comment by sergbbb** [comment]
all normalized. Thank you!
