### ISSUE TITLE
Feature Request - Cradlepoint protocol, additional attributes in report/state sections 

### ISSUE THREAD

**Issue by ddubief** [tananaev/traccar#3581]
Add support for displaying additional values in output for state of connection and report on the Cradlepoint protocol. 

Currently, only RSSI is displayed, however additional data provided in the string is pertinent to use this data to identify dead spots with regards to the cellular modem's location. For instance, RSSI only measures the distance or received signal strength from the Cell tower. There is also reference numbers provided (RSRP/RSRQ) in the string which provides more beneficial information. Additionally the SERDIS field which specifies if the modem is connected to LTE/EVDO/HSPA, etc for service type. 

Having this data displayed at a minimum in an output report for route in a separate column would be quite helpful to anyone using this to track GPS position with cellular attachment.

**Comment by tananaev** [comment]
Please provide protocol documentation and message samples.

**Comment by ddubief** [comment]
# Example: 
# +12084014675,162658,4337.174385,N,11612.338373,W,0.0,,Verizon,,-71,-44,-11,, 
# +14063964266,15813,4333.62394,N,11636.23465,W,0.0,,Verizon Wireless,LTE,-107,-74,-11,,100.68.169.178 
# +14063964266,15816,4333.62398,N,11636.23467,W,0.0,,Verizon Wireless,LTE,-107,-74,-16,,100.68.169.178 
# +14063964266,15819,4333.62404,N,11636.23469,W,0.0,,Verizon Wireless,LTE,-107,-74,-16,,100.68.169.178

# Examining original code. Comma joined fields: 
# MDN or DISP_IMEI 
# Fix time 
# Latitude 
# Longitude 
# Speed Over Ground (Knots) 
# Track Angle (Degrees) 
# CARRID or HOMECARRID 
# SERDIS 
# RSRP 
# DBM 
# RSRQ 
# ECIO 
# modem WAN IP address (if any) 
#

**Comment by tananaev** [comment]
Why fix time has only 5 digits?

**Comment by ddubief** [comment]
Depending on the time of day if that is a zero we omit that from the string. 

For example. Later in the day: 
356526071010403,192312,4337.16939,N,11612.33720,W,0.0,4.9000000000000006,,,,,,, 
356526071010403,192315,4337.16939,N,11612.33723,W,0.0,4.9000000000000006,,,,,,, 
356526071010403,192318,4337.16939,N,11612.33724,W,0.0,4.9000000000000006,,,,,,, 
356526071010403,192321,4337.16938,N,11612.33724,W,0.0,4.9000000000000006,,,,,,,

or 

+12089821906,195632,4337.17210,N,11612.36203,W,0.0,312.6,Verizon Wireless,LTE,-71,-47,-7,,166.164.76.49 +12089821906,195632,4337.17210,N,11612.36203,W,0.0,312.6,Verizon Wireless,LTE,-71,-47,-7,,166.164.76.49 

I will get confirmation of that.

**Comment by tananaev** [comment]
OK, what happens in following cases:

1. 01:01:01
2. 00:00:01
3. 00:00:00

**Comment by ddubief** [comment]
I'm going to capture this tonight so I can get clarification, I believe for the hour field, we only pull the 0 in that sense. so in the above I'd expect to see the following:

01:01:01 = 10101
00:00:01 = 00001
00:00:00 = 00000

I will confirm this tonight however as the time resets I believe at midnight EST.

**Comment by ddubief** [comment]
To confirm, here is the switch after 24hr reset: 
356526070063940,235950,4337.19020,N,11612.34703,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,235951,4337.19019,N,11612.34703,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,235952,4337.19019,N,11612.34703,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,235953,4337.19018,N,11612.34703,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,235954,4337.19018,N,11612.34704,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,235955,4337.19017,N,11612.34705,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,235956,4337.19016,N,11612.34705,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,235957,4337.19014,N,11612.34706,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,235959,4337.19012,N,11612.34705,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,0,4337.19009,N,11612.34705,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,1,4337.19008,N,11612.34705,W,0.0,277.2,AT&T,,,-79,,-14.0,
356526070063940,2,4337.19008,N,11612.34705,W,0.0,277.2,AT&T,,,-79,,-13.0,
356526070063940,3,4337.19007,N,11612.34706,W,0.0,277.2,AT&T,,,-79,,-13.0,
356526070063940,4,4337.19006,N,11612.34707,W,0.0,277.2,AT&T,,,-79,,-13.0,
356526070063940,5,4337.19006,N,11612.34707,W,0.0,277.2,AT&T,,,-79,,-13.0,
356526070063940,6,4337.19005,N,11612.34707,W,0.0,277.2,AT&T,,,-79,,-13.0,
356526070063940,8,4337.19004,N,11612.34708,W,0.0,277.2,AT&T,,,-79,,-13.0,

Looks like it does not provide any leading 0's at all. so for your question above it would display as:

1. 01:01:01 = 10101
2. 00:00:01 = 1
3. 00:00:00 = 0

Thanks!

**Comment by tananaev** [comment]
I have updated decoder.

**Comment by ddubief** [comment]
Confirmed working for the display in the "State" field. 

![image](https://user-images.githubusercontent.com/32744757/31750803-7a20e6e2-b43f-11e7-9f7d-859938d0f4af.png)

**Comment by Abyss777** [comment]
@ddubief 
Do you have an official information explaining two fields: "carrid" and "serdis"?
As I understand "carrid" is short of "carrier id" but according to your examples it is not ID it is carrier full name.
"serdis" is more mysterious, according to google it is butterfly, but looks like a connection type in Cradlepoint protocol (LTE/EVDO/HSPA). May be it is short of something, but what?
