### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by kush0005** [tananaev/traccar#3583]
When i am sending the server command to device then the device replies  (Error; The platform addresses are Locked modify!). The imei of the device starts from 358899. Can you solve my issue?

**Comment by tananaev** [comment]
It sounds like device issue, not server. You should contact device vendor.

**Comment by kush0005** [comment]
Yeah i know it is not the issue of server. But is their any other solution for it?

**Comment by tananaev** [comment]
You can ask on forum, not here. Repository is only for server related questions.
