### ISSUE TITLE
Geofences

### ISSUE THREAD

**Issue by nelledge83** [tananaev/traccar#3586]
Hello, Thanks for your continued support.
I think this might be a issue.
Under devices i setup a column to display geofences but there always blank.
I included a screenshot of 1 truck located in a geofence but nothing is being displayed.
Am i missing something?
![image](https://user-images.githubusercontent.com/32579390/31728404-19b5006c-b3e1-11e7-8d1d-8390f94aa207.png)

**Comment by Abyss777** [comment]
Have you linked the geofence to the device?

**Comment by nelledge83** [comment]
That was what I was missing. Thanks
