### ISSUE TITLE
Sorting insert by time ? 

### ISSUE THREAD

**Issue by AymanElarian** [tananaev/traccar#3587]
hello , i have a problem that device msgs insert not sorted if come in same packet ? 
i know that it may be device problem

<img width="803" alt="screen shot 2017-10-18 at 9 01 33 pm" src="https://user-images.githubusercontent.com/364872/31737393-a243dfe6-b447-11e7-84a5-05d21971bc4d.png">

but any way to sort them before send to db to insert ?

**Comment by tananaev** [comment]
Can I see logs?

**Comment by AymanElarian** [comment]
sorry current service mode only show log on error  , so no log for it , for me i believe its because of send new msg  first  option from teltonika ,   so i am planing to sort positions before return by time ,  do you have an optimal method for that ?

**Comment by tananaev** [comment]
Can't you configure Teltonika to report in correct order. I recall there was an option like that.

**Comment by AymanElarian** [comment]
@tananaev  some time devices not accept configration for that via sms , any way to send this command via gprs once any device connect, i mean via protocol  it self not send command via api ?

**Comment by tananaev** [comment]
I'm not sure what you mean by sending via protocol. Traccar does support commands.

**Comment by AymanElarian** [comment]
i know that Traccar support commands, i mean 

hardcoding send command once device connect to Traccar via protocol teltonika , then 
send via gprs [setparam 1010 1] to force device to accept that config , as for us sms have some problems , 
![pasted image at 2017_10_14 04_46 pm](https://user-images.githubusercontent.com/364872/31741281-f420631e-b453-11e7-82e7-edd19e1f9301.png)

**Comment by tananaev** [comment]
There is no such functionality, but of course you can add anything you want to the source code.

**Comment by AymanElarian** [comment]
Thanks for your help can i ask 1 more question 

`    @Override
    public void channelConnected(ChannelHandlerContext ctx, ChannelStateEvent e) {
        Log.info(formatChannel(e.getChannel()) + " connected");
    }`

i am planning to add  a port from 
`ActiveDevice activeDevice = Context.getConnectionManager().getActiveDevice(deviceId);
            if (activeDevice != null) {
                activeDevice.sendCommand(command);
            }`

once channel connected , how to know that Channel teltonika protocol ? also any how to get channel deviceId so i can get  "Context.getConnectionManager().getActiveDevice(deviceId)"

**Comment by tananaev** [comment]
I'm not sure why you want to do it like that. Just add your code to the decoder when device is identified.

**Comment by AymanElarian** [comment]
Thank you @tananaev

**Comment by AymanElarian** [comment]
@tananaev 
i have done it can you please confirm if that mean it sent and accepted ?
`
2017-10-19 00:50:35 DEBUG: [AEEF903E: 12050 < 51.36.165.182] HEX: 000f333537343534303730313138333833
2017-10-19 00:50:35  INFO: device: 14729 ,Protocol:teltonika,ip /51.36.165.182:1025
2017-10-19 00:50:35  INFO: Sending gprsCommand setparam 1010 1 to 14729
2017-10-19 00:50:35  INFO: [AEEF903E] id: 357454070118383, command type: custom sent
2017-10-19 00:50:35 DEBUG: [AEEF903E: 12050 > 51.36.165.182] HEX: 00000000000000190c010500000011736574706172616d203130313020310d0a01000000e5
2017-10-19 00:50:35  INFO: gprsCommand setparam 1010 1 to 14729Sent
2017-10-19 00:50:35 DEBUG: [AEEF903E: 12050 > 51.36.165.182] HEX: 01
`

**Comment by tananaev** [comment]
You can see the raw HEX data. Please check it yourself.

**Comment by AymanElarian** [comment]
i mean 
2017-10-19 00:50:35 DEBUG: [AEEF903E: 12050 > 51.36.165.182] HEX: 01

01 mean sent ?

**Comment by tananaev** [comment]
Yes.
