### ISSUE TITLE
Android 8.0 and Traccar Manager / Chrome issues

### ISSUE THREAD

**Issue by Materie62** [tananaev/traccar#3596]
Hi,
I recently upgraded my Android cell phone to version 8.0.0. After the upgrade the Traccar Manager (v2.4) remains stuck when I open the app. It only shows the blue turning circle. Same happens when I try to open the Traccar website using the Chrome browser (v61.0.3163.98) on the cell phone.
However when using a Firefox web browser (v56.0) on the cell phone all works ok.
Do you know what could be wrong?

**Comment by tsmgeek** [comment]
This issue should be in the https://github.com/tananaev/traccar-web repo

**Comment by tananaev** [comment]
The issue is already fixed:

https://www.traccar.org/forums/topic/traccar-manager-on-android-wont-load/
