### ISSUE TITLE
GT06N Protocol SOS Alarm wrongly put as Geofence Enter Alarm

### ISSUE THREAD

**Issue by k30r88** [tananaev/traccar#3603]
I have configured Concox  GT06N Protocol. I have configured SOS alarm for the device to send the alert via SMS as well as to the Platform. However what weird is happening is that on SOS alarm, the device is sending a Geofence Enter to traccar platform. Can you help us ?

**Comment by tananaev** [comment]
Please provide protocol documentation and message samples with the alarm.

**Comment by socstur** [comment]
Hi Anton,
                I was going to open another issue but I think this one is similar to what I'm seeing with a Concox MT200 device; they are both using gt06 protocol. The problem packet is x26...it is an alarm packet but the alarm was for vibration(see image below for C8 before the 04 04). Traccar decoded it as geofence enter alarm. To help in debugging @k30r88 issue the alarm packet for GT06N is sent as x16. 
I have attached the decoding of both x26 and x16 below 

![image](https://user-images.githubusercontent.com/15850216/31957999-0849d6f2-b8b6-11e7-9fb0-dc634ece6134.png)


![image](https://user-images.githubusercontent.com/15850216/31958144-750bb72e-b8b6-11e7-9948-2b8f7383b74a.png)

![image](https://user-images.githubusercontent.com/15850216/31958347-05934f46-b8b7-11e7-8554-0cbab2f34b91.png)

**Comment by tananaev** [comment]
I would need sample in text format. I'm not going to manually type it in from your screenshot.

**Comment by socstur** [comment]
Hi Anton...here's a text of the sample screenshot

2017-10-24 12:04:55 DEBUG: [51654808: 5023 < 154.160.1.48] HEX: 78782526110a18110436cd009a50b1000221e8001d1e09026c01008c003b61c804040302014783840d0a
2017-10-24 12:04:55 DEBUG: [51654808: 5023 > 154.160.1.48] HEX: 78780526000ae8310d0a
2017-10-24 12:04:55  INFO: [51654808] id: 351608085125982, time: 2017-10-24 12:04:54, lat: 5.61845, lon: -0.07764, speed: 0.0, course: 286.0

**Comment by tananaev** [comment]
I get vibration alarm for your example.

**Comment by socstur** [comment]
that is correct...but traccar shows it as geofence enter alarm

**Comment by tananaev** [comment]
It work fine with the latest source code, so I recommend to wait for the next release if it doesn't work for you in 3.14.

**Comment by k30r88** [comment]
Dear @tananaev  
Sorry for late reply, here are log from our device : 
2017-10-23 14:51:29 DEBUG: [F440DC1C: 5023 < 116.206.29.3] HEX: 78782516110a170e3312ce00a95f3a0b7540b00050bf0901fe59233d000066640604010202feb8ba0d0a
2017-10-23 14:51:29 DEBUG: [F440DC1C: 5023 > 116.206.29.3] HEX: 787805160002e2d70d0a

Translation of Decoding First line : 
START:
78782516110a170e3312ce00a95f3a0b7540b00050bf0901fe59233d000066640604
THEN :
**0102 Alarm Language | SOS**
02fe
b8ba
0d0a
END

**Comment by k30r88** [comment]
@socstur yours is a bit different, your alarm is from vibration, ours is from SOS alarm,
but both show as geofence enter. @tananaev

**Comment by tananaev** [comment]
I asked for documentation.

**Comment by tananaev** [comment]
Have you tried it on latest code as I suggested above? I get SOS alarm as expected.

**Comment by k30r88** [comment]
OK,  meaning you have corrected this on your latest source code. We will wait for your 3.15 version. When will it be released ? Or perhaps you can share your nightly build version ?

**Comment by tananaev** [comment]
I don't have any dates. There are no nightly builds. If you don't want to wait you can compile yourself.

**Comment by k30r88** [comment]
OK @tananaev we will try. Thank you for your prompt reply

**Comment by socstur** [comment]
I can confirm latest code decodes alarm packet x16 with SOS alarm correctly. Tested on a TR06 which is very similar to GT06N. I sent SOS alarm with push button from device and traccar showed SOS Alarm.

Will try to test the vibration alarm as well.

**Comment by SudhakarDatt** [comment]
79790020940a08665510363566030404784356352821899111000004763557230383abce0d0a

can some one explain me about above packet,
