### ISSUE TITLE
any reson for [messagesstored] > [messagesreceived] ???

### ISSUE THREAD

**Issue by AymanElarian** [tananaev/traccar#3606]
Hello , thank you for your service,  it working great,  but on my test servers i have the following case 

any reson for that , ? how to start debug that case

**Comment by tananaev** [comment]
Some messages that don't have any useful information are not stored in the database. For example, heartbeat messages. It can also be because of the filtering, if you have it enabled.

**Comment by AymanElarian** [comment]
i know that but my problem is that saved messages to db larger than msgs received ? 
i am asking about that  , is that normal ? 
do you count packet with multi gps messages as 1 message
 or count it by each message in that packet ?

**Comment by tananaev** [comment]
That's also normal. Many devices report location in batches, so you can have one message that results in multiple location records in the database.

**Comment by AymanElarian** [comment]
ok great , thank you for your response
