### ISSUE TITLE
StatisticsManager checkSplit() fire many time in same SPLIT_MODE

### ISSUE THREAD

**Issue by AymanElarian** [tananaev/traccar#3614]
hello 

Statistics split it self each SPLIT_MODE
```java
        int currentUpdate = Calendar.getInstance().get(SPLIT_MODE);
```
but problem happen if in the same milisecond alot of registerMessageReceived() or registerMessageStored(long deviceId) fired , that make checkSplit called many times 
i have for 10 days,  about 400,000 rows ? for same 12:00 am

**Comment by tananaev** [comment]
Fixed the problem using atomic integer.
