### ISSUE TITLE
Stoppages in playback history

### ISSUE THREAD

**Issue by Codepeaker** [tananaev/traccar#3621]
Hello @tananaev  
I wanted to implement the stoppages in playback history and I have no idea where to look for it
Is this feature already implemented and if yes, then where can I find it 
Thanks

**Comment by tananaev** [comment]
I have no idea what you are talking about. What is playback history?

**Comment by Codepeaker** [comment]
HI @tananaev  sorry for the confusion but I was relating Trips to Playback history
and I was asking how to get stops between trips because I can't find any stops attribute in TripReport.java model
Thanks

**Comment by tananaev** [comment]
Relating? There is no playback in Traccar.

**Comment by Codepeaker** [comment]
Nevermind, I got my answer in Trips.java 
Thanks a lot for the support
