### ISSUE TITLE
update device table with device attributes keys ?

### ISSUE THREAD

**Issue by AymanElarian** [tananaev/traccar#3629]
hello , 

i want to  keep updated with device attributes keys like in1,in2,adc1 for each device and update it if new attributes  came , i need to update a column in devices table

how can i achieve that ?

**Comment by tananaev** [comment]
Where does new attribute come from?

**Comment by AymanElarian** [comment]
last  postion for example 

i have today input & adc1 then i config device to send also RFID 

so i need a column for all activated  attributes even if not in last position 

so after each msg position if new attributes add to device attributes list

**Comment by tananaev** [comment]
So you are talking about position attributes, not device attributes. Well, you can have a handler or something to add it.

**Comment by AymanElarian** [comment]
yes exactly position attributes , i was planing for handler but i just want to make sure if its not yet done ,before coding it ,  

Thanks @tananaev  for your support
