### ISSUE TITLE
Parallel access to the DB

### ISSUE THREAD

**Issue by samolapraga** [tananaev/traccar#363]
Hi Anton,

I am using tomcat6 as a servlet container for the web interface and the wrapper as a container for the tracker server app. However, i am facing an issue i was not able to solve by myself, which is how to get both to use the same DB. My problem is that i think that both the webserver and the wrapper are locking the DB exclusively, so it is either one or the other that are working at one time.

Can you please suggest how can i solve this issue(if it is an issue at all).

Thanks

**Comment by tananaev** [comment]
Closing as Traccar doesn't use GWT anymore.
