### ISSUE TITLE
unable to start after shutdown

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3631]
Hi Anton,
               Can you help me debug this startup issue? I stopped traccar and mysql to reboot system. Now I'm unable to start traccar. Below is the log from wrapper file. It looks to be a database issue, any suggestions on how to fix this so traccar can start?
```
WARNING|wrapper|Service traccar|17-11-07 12:43:04|YAJSW: yajsw-stable-12.09
...
FINEST|1132/0|Service traccar|17-11-07 12:43:09|	at org.traccar.database.GroupTree.getNodes(GroupTree.java:146)
FINEST|1132/0|Service traccar|17-11-07 12:43:09|	at org.traccar.database.GroupTree.getNodes(GroupTree.java:146)
FINEST|1132/0|Service traccar|17-11-07 12:43:09|	at org.traccar.database.GroupTree.getNodes(GroupTree.java:146)
INFO|wrapper|Service traccar|17-11-07 12:43:10|waitpid 1132 59136
INFO|wrapper|Service traccar|17-11-07 12:43:10|exit code posix process: 59136 application: 0
```

**Comment by tananaev** [comment]
Have you tried searching for an answer?

https://www.traccar.org/forums/topic/how-to-fix-a-cycle-in-groups/

**Comment by socstur** [comment]
Thanks Anton...I'll do my due diligence with the search next time.

Regards,
