### ISSUE TITLE
Filters are applied even if Alarms exist

### ISSUE THREAD

**Issue by tsmgeek** [tananaev/traccar#3633]
Not sure if bug or maybe it should just be handled different.

I have put a distance filter on but it seems that all alarms are now ignored as the position they post means that it gets ignored by the distance filter. Ie alarms for motion/ignition etc are all filtered.

Should alarms not bypass the filtering or some of it?

**Comment by tananaev** [comment]
Please do some research before raising issues: https://github.com/tananaev/traccar/pull/3514 https://github.com/tananaev/traccar/issues/3513

**Comment by tsmgeek** [comment]
https://www.traccar.org/configuration-file/ needs updating to show new config var

**Comment by tananaev** [comment]
It has not been release, so we shouldn't update it yet.
