### ISSUE TITLE
Api Connection Problems

### ISSUE THREAD

**Issue by djbo1982** [tananaev/traccar#3635]
Hello @tananaev @Abyss777 

As allways... thank for the hard working in traccar!!! we all ready contributing with money 3 times

First we need to know, if we go to used api and other background services, what folders we need to have in the traccar, because when we install the traccar we dont have the API folder

Second: i copy only the api folder to the traccar and try to connect to used the api with curl and create a session to test

curl -X POST -H "Content-Type: application/vnd.kafka.json.v1+json" --data '{"email":"admin", "password": "prueba"}' "xxx.xxxx.xxxx.xxxx:8086/api/session"

But we received HTTP 415 Unsupported Media Type - NotSupportedException (...)

what we are make bad???

we follow this post https://www.traccar.org/forums/topic/code-to-update-device-with-api/ because we go to create all with lavarel, but we dont know what happens

Hope you can helpme

**Comment by tananaev** [comment]
What is `Content-Type: application/vnd.kafka.json.v1+json`? Where did you get it from?

**Comment by djbo1982** [comment]
Is a example from console... about the folders, what folder i need to have? from github

**Comment by tananaev** [comment]
Documentation clearly says that you should use `application/x-www-form-urlencoded` content type for session. Why are you using something else? Please read documentation before raising any issues.

I also don't understand what folders you are talking about. You need to compile whole Java project. It includes API implementation.
