### ISSUE TITLE
Notifications not work on upgrade 3.14-Snapshot to version source in git

### ISSUE THREAD

**Issue by michaelloliveira** [tananaev/traccar#3637]
Hello Tannaev,

When upgrading from version 3.14 linux to the source (built) version of git you can no longer view user notifications through the API.

I used the URL:
http://127.0.0.1:8082/api/notifications/?{%22userId%22:%221%22}&_=1510601182784

Returns no value.

- Before using the new version the feature was working normally.
- The source code has not been modified.
- default.xml and traccar.xml that was in source's setup folder were used.

And sorry for my English.

**Comment by tananaev** [comment]
What do you have there after the question mark? Where did you a request like this?

**Comment by michaelloliveira** [comment]
Data is being passed this way:
http://127.0.0.1:8082/api/notifications/?{userId:1}
- Content-type is application / json
- I'm using admin user
- the method is POST
- the parameters are of type Object and sent through Jquery;


I use a web interface developed by me, it works in version 3.14-SNAPSHOT, the function searches the list of user notifications so that it can select which forms to receive. similar to tracarweb.

**Comment by tananaev** [comment]
There was never any option like that in official Traccar.

**Comment by michaelloliveira** [comment]
I am referring to this function of the traccarweb.
Even in traccarweb that comes along with the source of traccarserver also does not work. this data is not listed.

![notifications](https://user-images.githubusercontent.com/600484/32748198-a8419b6c-c8a2-11e7-87f9-26c2a69fb86d.jpg)

**Comment by tananaev** [comment]
What exactly doesn't work? It works for everyone else.

**Comment by michaelloliveira** [comment]
I had version 3.13, I upgraded to version 3.14. until then it was working correctly.

When I downloaded the current source, I built and upgraded that function stopped working.

Analyzing the code I realized that before the API worked in api/users/notifications, it is now only in /notifications.

I kept the parameters but the data stopped coming.

**Comment by tananaev** [comment]
API for notification has changed, but it doesn't change the fact that your query parameters never worked.

**Comment by michaelloliveira** [comment]
Exactly, they worked, until using the source version.

When I started using the source version:
- I changed from api / users / notifications to / api / notifications
- I kept the parameters.
and it did not work anymore.
Even to change the status of the notification, when used the POST method returns the error: HTTP 404 Not Found - NotFoundException (...)
- http://127.0.0.1:8082/api/notifications
userId = 1;
type = "textMessage";
web = true;
mail = false;
attributes = {};



I did a clean installation of the built version of the source, and in the log I submitted the error: Table 'traccar.user_notification' does not exist.

**Comment by tananaev** [comment]
If you want an example on how to use new API, you should look at the web app source code.

**Comment by michaelloliveira** [comment]
I did this, the swagger.json file helped a lot, but the function still does not work.

I will give up and wait for the version that is currently in the source to be released, until then I use the version that is available for installation.

Thanks for listening.

**Comment by tananaev** [comment]
Web app definitely works.
