### ISSUE TITLE
Send command to device

### ISSUE THREAD

**Issue by robertoalmeida** [tananaev/traccar#365]
I implemented the functionality to send the command to the device and would like to know if you want the code to implement.

Initially used protocol suntech.

----

Implementei a funcionalidade de enviar comando ao dispositivo e gostaria de saber se quer o código para implementar.
Inicialmente usei o protocolo suntech.

**Comment by Jeferex** [comment]
@robertoalmeida code doesn't work on newer versions. I've tried to do it with no success.

Has anyone updated the code to work on new versions?? If so, please share.

**Comment by tananaev** [comment]
Closing as a dupe of #7.

**Comment by wnieva** [comment]
I need to send engine cut command on a GV200 GPS. I have a table that captures the IMEI and the IP of the GPS but I do not know What is the command to cut engine by means of GPRS ... can someone help me?
Tnk u

**Comment by tananaev** [comment]
@wnieva, please don't comment on old closed threads.

**Comment by owaresabd** [comment]
could someone send me the code for sending command to coban TK105/B GPS Device?
