### ISSUE TITLE
How to get " 0038-------------------------FMU value " from Teletonika packet

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#3650]
Hi,

From the [source code](https://github.com/tananaev/traccar/blob/b2ed61db9d33324222c7cbdc5a133152ede0c1ac/src/org/traccar/protocol/TeltonikaProtocolDecoder.java), where can I find the FMU value decoded ?

I want to check its value by printing on UI or Log file.

Please find the attached FM1100 packet doc.
[Teltonika_FM1100.docx.pdf](https://github.com/tananaev/traccar/files/1490336/Teltonika_FM1100.docx.pdf)

Thanks,
Kiran.

**Comment by tananaev** [comment]
Each Teltonika value has an id. Please study the code and documentation before asking questions.

**Comment by kirantpatil** [comment]
We could see the id and value from the server log DEBUG message. Thanks.
