### ISSUE TITLE
Delete positions history

### ISSUE THREAD

**Issue by ninioe** [tananaev/traccar#3654]
Hi Anton,
When there is a null in positionId in one of the records in devices table the clear history feature is not working.

The solution:
inside the configuration file default.xml need to change this:

    <entry key='database.deletePositions'>
        DELETE FROM positions WHERE serverTime &lt; :serverTime AND id NOT IN (SELECT positionId FROM devices)
    </entry>

to:

    <entry key='database.deletePositions'>
        DELETE FROM positions WHERE serverTime &lt; :serverTime AND id NOT IN (SELECT positionId FROM devices WHERE positionId IS NOT NULL)
    </entry>

Thanks
Erez

**Comment by tananaev** [comment]
What database are you using?

**Comment by ninioe** [comment]
MySQL

‫ב-22 בנוב׳ 2017, בשעה 20:50, ‏‏Anton Tananaev ‏<notifications@github.com> כתב/ה:‬

**Comment by tananaev** [comment]
It's already fixed: https://github.com/tananaev/traccar/commit/d5ad3af86c6faa5d45b8724219bf06cdd58e3eed.
