### ISSUE TITLE
Is it possible to create Mutually exclusive admins on single server?

### ISSUE THREAD

**Issue by parveenkumardeeva** [tananaev/traccar#3655]
Hi Tananaev,

We can create multiple admin into a single server installation or DB.
For e.g:

A is an admin.
B is created by A as an admin.
But B can edit, delete the A and also it's Users etc.

Is it possible to create mutually exclusive admin without creating new server?

**Comment by tananaev** [comment]
No, but you can have two manager users that don't have access to each other. For such questions you should use forum, not GitHub.

**Comment by parveenkumardeeva** [comment]
Ok sorry, in future I'll take care for such type of questions.

But Manager user can't create new User on their own if he has not given admin permission.
I only wanted to give these permission to another user and should have access only to the users created by him. As far as I know , I think it's presently not possible?

**Comment by tananaev** [comment]
He can. That's the whole point of manager. You should probably read documentation before commenting.

**Comment by parveenkumardeeva** [comment]
Again, Thank you so much.
Found the mistake. As per doc _If manager has expiration time, he cannot set other users expiration time later than his own._
