### ISSUE TITLE
Supply config file

### ISSUE THREAD

**Issue by gmiskos** [tananaev/traccar#3656]
Hello Anton. I'm trying to build traccar server with netbeans. 

How we provide config file? Is ti at the repository at folder /setup? are we provide our own config file?

when i give as a parameter default.xml i get the error:
```
--- exec-maven-plugin:1.2.1:exec (default-cli) @ traccar ---
Exception in thread "main" java.lang.NullPointerException
	at org.traccar.Context.init(Context.java:373)
	at org.traccar.Main.main(Main.java:35)
```

**Comment by tananaev** [comment]
You provide your own config as a command line argument. You can use `setup/traccar.xml`, but obviously you need to fix paths.

**Comment by gmiskos** [comment]
Thank you very much! And then how do i run web traccar ?

**Comment by tananaev** [comment]
Put it in the correct folder and enable it in the config.

**Comment by tananaev** [comment]
You might also need to compile web app.

**Comment by gmiskos** [comment]
The correct folder means, inside traccar web folder ? Or in tomcat for example

**Comment by tananaev** [comment]
Traccar includes embedded web server. Please do some research before asking any question.

**Comment by gmiskos** [comment]
Thank you Anton and sorry for the inconvenience
