### ISSUE TITLE
Can't create or edit users: Invalid parameters or constraints violation

### ISSUE THREAD

**Issue by GrossoMoreira** [tananaev/traccar#3657]
Hi,

I just installed traccar and when using the web app, I try to create a user and I get:
```
Unrecognized field "distanceUnit" (class org.traccar.model.User), not marked as ignorable (22 known properties: "readonly", "limitCommands", "deviceLimit", "login", "name", "latitude", "phone", "admin", "userLimit", "zoom", "twelveHourFormat", "attributes", "deviceReadonly", "token", "id", "email", "longitude", "password", "map", "coordinateFormat", "disabled", "expirationTime"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@58185142; line: 1, column: 378] (through reference chain: org.traccar.model.User["distanceUnit"])
```
What should I do?

Thanks!

**Comment by tananaev** [comment]
You have incompatible back-end and web app.

**Comment by GrossoMoreira** [comment]
How can that happen if I checked out this git repo and ran setup/docker/build.sh ? What can I do to ensure compatibility? I did this:

git clone https://github.com/tananaev/traccar.git --recursive
cd traccar
sh ./setup/docker/build.sh

**Comment by tananaev** [comment]
Why are you using master branch? Unless you know what you are doing, you should use last stable tag.

**Comment by GrossoMoreira** [comment]
Ok, good point. Thanks for the tip, I'll try that!
