### ISSUE TITLE
Hoto configurate ruptela Eco 4 in a tracar platafotm, ad how to found te identificator number to do the regiter?

### ISSUE THREAD

**Issue by ramefx** [tananaev/traccar#3659]

**Comment by tananaev** [comment]
First of all, question should be in description, not in the title. Secondly, you should ask questions like this on the forum.

**Comment by ramefx** [comment]
It my first time to use this platafor to ask something sorry

**Comment by tananaev** [comment]
Ruptela uses IMEI as identification number. For details on configuring device you should contact device vendor or check device manual.

**Comment by ramefx** [comment]
ok i going to try it tank you
