### ISSUE TITLE
Eelink proto error

### ISSUE THREAD

**Issue by tsmgeek** [tananaev/traccar#3661]
https://github.com/tananaev/traccar/blob/818fff6daf87a9e90a225122d04dc8b93694a8c6/src/org/traccar/protocol/EelinkProtocolDecoder.java#L287

Response on my tracker has 'DateTime' not 'Date Time', is this firmware dependent?

**Comment by tananaev** [comment]
Not sure. Can you please provide a HEX example.

**Comment by tananaev** [comment]
Official response from vendor is that response with space is from older devices. Response without space is from newer devices. I guess it makes sense to support both.

**Comment by tsmgeek** [comment]
I've amended my PR to handle this situation.

I've got various units sourced a few months ago which explains that then.

Can a note be put on the protocol page that eelink units can be set to
newer protocol by sending SET,branch,1#, the older protocol has limited
data.

On 29 Nov 2017 01:44, "Anton Tananaev" <notifications@github.com> wrote:

Official response from vendor is that response with space is from older
devices. Response without space is from newer devices. I guess it makes
sense to support both.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tananaev/traccar/issues/3661#issuecomment-347724936>,
or mute the thread

**Comment by tananaev** [comment]
You can put that information somewhere on the forum for now.

**Comment by tsmgeek** [comment]
I have seen that the UDP header you are using is 0x454C (EL) but the specification says 0x4550 (EP).
Is there an error in spec docs?

**Comment by tsmgeek** [comment]
Also noticed that the UDP spec allows for multiple packages within a single datagram but it is not well documented and not sure under what circumstances this may happen.
Can traccar support multiple position packets being returned from the Decoder?

**Comment by tananaev** [comment]
I believe EP is the spec issue. Real device reports EL.

It's possible to implement multiple packets, but Traccar doesn't support it for eelink at the moment.
