### ISSUE TITLE
GPS bicycle tracker COBAN GPS305. Does any one test it on Traccar? Can´t find it on device list

### ISSUE THREAD

**Issue by TecSeguridad** [tananaev/traccar#3671]
Here is te Coban link http://www.coban.net/html/2013/12/26/2013122605122319508635.html

I don´t know what port or protocol should i use

Any one can help me? Thank You

**Comment by tananaev** [comment]
I would recommend you to read this:

https://www.traccar.org/clones/

Also questions like this belong on the forum.
