### ISSUE TITLE
Feature Request:  Sanity check for derived odometer/speed values.  New trackers start off with 7,000 miles.

### ISSUE THREAD

**Issue by pc500** [tananaev/traccar#3673]
When a Tk102 tracker comes online and it's first update does not have GPS signal, it sends lat/long as 0,0 (or at least traccar records it that way).  It puts me out in the middle of  the ocean.

Once they get signal, they report the correct location.

My Odometer then starts at nearly 7,000 miles within 5 seconds of powering on the device.

I'm not sure if this behavior is the fault of the tracker or not, but can we add some sanity checking to Odometer and Speed to make sure any values used for calculations are reasonable, and if not discard them?

**Comment by tananaev** [comment]
There is already a filtering for big jumps like this.

**Comment by pc500** [comment]
Thanks - 
Upon further examination, the distance under the Summary report appears correct, but it is not correct under the device information.  Is this intentional and indicates the filtering does not work on the device level data?

see screenshot:

![image](https://user-images.githubusercontent.com/33823824/33786287-614a4acc-dc1d-11e7-9ec8-881b31166421.png)

**Comment by tananaev** [comment]
You need to enable filtering. There is no filtering by default.
