### ISSUE TITLE
Per user request geocoding error

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3675]
Hi guys,
             I'm getting this error below when testing out the per user request geocoding. I'm running official release of 3.15.

![image](https://user-images.githubusercontent.com/15850216/33802233-00ac48ac-dd38-11e7-8598-066d5412f3e6.png)

**Comment by Abyss777** [comment]
Probably you have not configured or enabled `geocoder`
https://www.traccar.org/reverse-geocoding/
https://www.traccar.org/configuration-file/

**Comment by socstur** [comment]
you are right...I had geocoder disabled in traccar.xml. Its working as expected now. Very useful feature, Thanks!
