### ISSUE TITLE
Possible bug in new version 3.15?

### ISSUE THREAD

**Issue by algp** [tananaev/traccar#3676]
Hello!
I wish to apologize for my english. Thanks for reading me!

I update my own server from 3.14. 

First, I download the new zip, I unzip this, and install (withouth remove the 3.14 version).

When I try to access to the "Saved commands" menu, this appear:

![image](https://user-images.githubusercontent.com/17849219/33807927-59dc9f0c-ddde-11e7-82ed-cb7cea665dda.png)

I also tried remove all the files of traccar, and make a new installation, I get the same result..

Someone know if there is a problem with this menu?

Thank you very much! Greetings.

**Comment by tananaev** [comment]
I don't have any problems with accessing it. Tried Chrome, Firefox and Safari. No issues.

**Comment by tananaev** [comment]
Have you solved the problem? What was the issue?

**Comment by algp** [comment]
Hello,

Yes! It was a problem with browser cookies.

Thanks greetings.
