### ISSUE TITLE
Some types incompatibility in user attributes

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3679]
https://www.traccar.org/forums/topic/oshibka-v-pochtovom-otpravlenii-cherez-atributy-javalangboolean/

Mail attributes must be strings in backend https://github.com/tananaev/traccar/blob/master/src/org/traccar/notification/NotificationMail.java

But in the web client they have different types https://github.com/tananaev/traccar-web/blob/master/web/app/store/UserAttributes.js
boolean is boolean

What will we do? I think making them all strings on web side will decrease users ease of use.

**Comment by tananaev** [comment]
Of course the right thing is to allow boolean value, but we also need to think about backward compatibility.
