### ISSUE TITLE
Disable device in group

### ISSUE THREAD

**Issue by pareliuss** [tananaev/traccar#3686]
Im not able to disable device that is in a group.
I have to delete the group first, then disable the device.

**Comment by tananaev** [comment]
So what is the question? If you have access to a group, you have access to all devices in the group. It's by works like that by design.

**Comment by pareliuss** [comment]
I have admin rights and im trying to disable a device on a user.  when i click off one device on user xxxxx,  save and go out, and go back in again, the device is on again.
I have tryed to log in with user xxxxx account, same thing there.
I can add new devices, but not remove them.
am i missing somethig here?

**Comment by tananaev** [comment]
Please read my previous comment carefully.

**Comment by pareliuss** [comment]
So what you are telling me is, if i want to remove one device from a group, i have to delete the whole group name, remove one device, create the group again and add all the other devices back in the group? Thats the design?

**Comment by tananaev** [comment]
No, if you want to remove device from group you just remove it from group. I'm not sure why you would need to delete and re-create something for that.

**Comment by pareliuss** [comment]
Thats the problem. I cant remove it.
If there was a blank group field in device options, it be easy.
If i tick off one device from a group, it comes back on automaticly.

**Comment by tananaev** [comment]
I see the problem, but it's different from your original issue. As a workaround for now I can suggest to create a temporary group that is not linked to any user and use it instead of blank.

**Comment by pareliuss** [comment]
Thank you.

**Comment by tananaev** [comment]
Fixed the problem with clearing group field (https://github.com/tananaev/traccar-web/commit/aff5895a438c29ca3f16a5d2e19bcb81bce08529).
