### ISSUE TITLE
Error while updating device phone number

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3691]
Good day Fellas,
                         I starting getting this error when updating device phone number on 3.14. I have upgraded to 3.15 and the error is still there.  It usually goes away after I restart the server. Any idea what could be the issue? Besides the error below nothing else shows up in wrapper or tracker log files.         

![image](https://user-images.githubusercontent.com/15850216/34225168-064fb496-e58b-11e7-8126-b9b37b756e20.png)

**Comment by tananaev** [comment]
I have fixed the issue.

**Comment by socstur** [comment]
Thanks!
