### ISSUE TITLE
 fuel sensor of tk103

### ISSUE THREAD

**Issue by evigra** [tananaev/traccar#3692]
Goodnight
I have the fuel sensor of tk103.

How can I read the attribute?

I have version 3.7

I'm looking in
https://www.traccar.org/configuration-file/

I found
processing.copyAttributes

But they are I dont know how to add it in the configuration file
Besides not knowing what the list of attributes is.

For example "power,ignition,battery".

**Comment by tananaev** [comment]
I would recommend using search. There are some usage examples out there.

Also, questions like this should be on forum not GitHub.
