### ISSUE TITLE
Suggestion: new filter.maxDistance

### ISSUE THREAD

**Issue by Koopzington** [tananaev/traccar#3693]
we're using about 200 TK5000s and those tend to sometimes sens tracks being thousands of kilometres off.

I'd really love to see an additional filter which does the opposite of the distance filter by filtering out tracks when the distance between them is bigger than a set value.
```
private boolean filterMaxDistance(Position position, Position last) {
    if (filterDistance != 0 && last != null) {
        return position.getDouble(Position.KEY_DISTANCE) > filterDistance;
    }
    return false;
}
```
Related to #3067

**Comment by tananaev** [comment]
There is already a filtering parameter for that - `filterMaxSpeed`.

**Comment by Koopzington** [comment]
Indeed! I thought that the filterMaxSpeed would look at the speed values sent by the trackers for filtering but judging by the code it actually calculates the speed between 2 points! I can work with that!

Thanks!
