### ISSUE TITLE
Erase device - User issue

### ISSUE THREAD

**Issue by djbo1982** [tananaev/traccar#3701]
Good morning @tananaev @Abyss777 

This problem happens to me in different version of traccar!

When we try to erase a user or device the system say ¨communication problem¨ and the device or user appear again in the list. 

We review the database to see if the id dessapear, but not, still there. When past some time the device or user dessapear, but not allways.

Sometimes, like today, the user how´s make the action (erase) dont show again the device list in the UI, show that icon like a clock round and round but never appear the list of devices again.

We try to stop and restar the traccar service to see what happens but, that user still same, all work fine but not show the devices list

I am worry about this, and we evite to erase devices or user because this problem

I need your help

**Comment by tananaev** [comment]
1. Screenshot of the error message please.

2. What database are you using? If MySQL, make sure that it's using InnoDB engine.

**Comment by djbo1982** [comment]
@tananaev Hello... Happy new Year 2018

We use MySQL in a UBUNTU Server with redundancy ram and processor in a MS Azure Services, and other admin user or normal user work fine, only in this case the principal admin user dont work, but if we try with another user, this issue happens to, and same, that used don´t work

i got the pictures of the issue

I check different thinks in the interface, and i review the admin user, that i used to remove car or user, and i see no car are add to this user can see, but i try to add car but the mark desapeir!

If you need server access please ask

In this picture we can see the list of car empty and the icon around and around
 
![img_7300](https://user-images.githubusercontent.com/23691155/34462849-90d7a24e-ee1a-11e7-82d3-93218d430419.jpg)

Here the user list and select admin user

![img_7303](https://user-images.githubusercontent.com/23691155/34462852-b3f91776-ee1a-11e7-94b6-b255371754a8.jpg)

Here the car list of that user!!! no car check, and i try to add car select the checkbox but the mark desapear

![img_7304](https://user-images.githubusercontent.com/23691155/34462912-78c7a1c6-ee1b-11e7-91e1-a06f57427bae.jpg)

**Comment by tananaev** [comment]
You haven't commented on the most important part. Does your database use MyISAM or InnoDB?

**Comment by djbo1982** [comment]
Sorry @tananaev 

is InnoDB

**Comment by tananaev** [comment]
Was it InnoDB from the beginning? Do you have foreign keys in the database?

**Comment by djbo1982** [comment]
@tananaev 

I create from the begining InnoDB DB, as default, and this Database in the same of the system install from the begin. i dont make changes in the DB or the Traccar system

Remember, the other user can be handle all with out problem, this happens only in user hows erase devices, sometimes user or group

**Comment by tananaev** [comment]
What about second question? Why have you ignored it?

**Comment by djbo1982** [comment]
@tananaev Sorry... 

The rigth answers is: I dont know... i never touch the database or change nothing... i don´t have foreing keys!

**Comment by tananaev** [comment]
If you don't it means that you weren't using InnoDB.

**Comment by djbo1982** [comment]
@tananaev I am sure of InnoDB, see the picture of the database tables

![pantalla-immp](https://user-images.githubusercontent.com/23691155/34464373-60c5d514-ee4a-11e7-97b5-c57fbbb376ef.jpeg)

**Comment by djbo1982** [comment]
@tananaev You can see, i entry with another admin user and all car is listed

![pantalla2](https://user-images.githubusercontent.com/23691155/34464378-b4a2640e-ee4a-11e7-9510-a0048864a733.jpeg)

**Comment by tananaev** [comment]
If you don't have foreign keys it means you didn't have InnoDB when you installed Traccar.

**Comment by djbo1982** [comment]
Anton, MySql Install InnoDB as default... and i check and is fine, you as the creator of the command for create the tables of the database, know this create automatic foreing keys to connect to other tables because some information of the system are related

I make a SQL request

SELECT SUPPORT FROM INFORMATION_SCHEMA.ENGINES WHERE ENGINE = 'InnoDB'; and i received this picture

![pantalla3](https://user-images.githubusercontent.com/23691155/34464448-2d749562-ee4d-11e7-820f-e1378226d21d.jpeg)

**Comment by tananaev** [comment]
I don't know what you expect me to say. If it was InnoDB and you still don't have foreign keys, then someone must have removed them deliberately. If you don't have foreign keys it means your database is broken and it won't work properly.

**Comment by djbo1982** [comment]
@tananaev Anton, this happens to me, in different version of Traccar, allways this is my big scary when i go to erase a device, no body have access to my database only i, and is intact like the setup created. Only if you can, please review my database to check is all ok.

And the problem is not allways, i can erase 1 device and wait 2 hour and all is fine, but if i reload the page, or erase more than 1 device at the same time i get this problem

**Comment by djbo1982** [comment]
IF YOU WANT I CAN PAY YOU a hour of service...!! i dont have problem for this, but i need to know what happens with this issue

**Comment by tananaev** [comment]
I already told you what the problem is. You need foreign keys. If you don't have them, then your database is broken.

**Comment by djbo1982** [comment]
@tananaev @Abyss777  Hello again

I study the case of these for a wile, and i need to ask you:

When i erase a device, why the device is not erase instanly? this process need around 5 minutes to complete, and if we reload the page or close the pase before the device is erase, the system colapse!

I see in the database the issue is in the user_device, to solve the issue of no device in this, i erase the user in database and copy other one and put the old id of erase user, and this process erase all information in user_device... this permit to me can add again the device to the user with out problem.

I make many test and the problem happens in all case i erase a device and reload...

**Comment by tananaev** [comment]
I have explained multiple times what your problem is. It works fine for everyone else, including all demo and commercial servers.
