### ISSUE TITLE
Status Offline

### ISSUE THREAD

**Issue by smartfinderaus** [tananaev/traccar#3706]
Hi Traccar,

I tried to use my Mobile Traccar Client to send location message to one of the demon server. I have already set the server Ip and Port 5055 on my mobile and also add the device with specific identifier in the demo platform, but the status is always offline, that's strange ~~

**Comment by tananaev** [comment]
First of all, you should status screen in the app. Secondly, this is the wrong place to ask. You should forum for questions like this.
