### ISSUE TITLE
Communication failure on loading reports

### ISSUE THREAD

**Issue by gpproton** [tananaev/traccar#3708]
Good day Anton,

I have a particular group with more than 200 devices an i keep getting a communication error whenever i try pulling reports of more than 24 hours and my server RAM is 128GB i also have tried running traccar with 12GB configured as maximum memory heap for java but it's still not working.
I really will appreciate any suggestion on fixing the issue.

![comm_failure](https://user-images.githubusercontent.com/11395006/34733555-12973880-f569-11e7-999c-5b72242d2f7e.PNG)

**Comment by tananaev** [comment]
It likely indicates timeout. Every browser has a timeout for how long a network call can take. Your report is likely taking more than that, so you get this issue.

What report are you trying to make? How much data is there in 24 hours for 200 devices?

**Comment by gpproton** [comment]
Thanks Anton, it's ok now

I had to adjust my browser network timeout settings to get it to work.

For Mozilla firefox
visit *** then filter for network.http.connection-timeout increase from default of 90 to a higher value till desired result is achieved.

**Comment by tananaev** [comment]
Thanks for sharing. I'm closing this issues for now.

**Comment by moondoesoh** [comment]
It doesn't work. 
No matter how high I set the value, communication failure happens after 30 seconds of requesting the report.

I tried "web.timeout" configuration too. Same result.

**Comment by gpproton** [comment]
If you're using traccar 4.1 you can just email report to avoid this issue you can also edit web report timeout on style.js then recompile.

**Comment by moondoesoh** [comment]
Does the email report work properly.
I tried 3 days ago and it did work.
But now I am not getting any report email.
Any thought?
