### ISSUE TITLE
Adding custom POI

### ISSUE THREAD

**Issue by antontoto** [tananaev/traccar#3714]
Sorry, but i can write this only bu Russian now.

Предлагаем ввести функцию добавления точек ПОИ с выпадающим описанием при наведении, чтобы была возможность вставлять фото, телефон и ссылку. Желательно чтобы ПОИ можно было группировать и управлять их отображением для различных групп пользователей. Мы используем эту систему в автоклубе УАЗ Патриот Санкт-Петербург и предполагаем введение всех магазинов запчастей для наших машин, СТО партнеров. При проведении клубных мероприятий будем обозначать точки сбора, место расположения базового лагеря и т.п... Сейчас пока реализовали просто добавление таких точек как объектов мониторинга, что конечно же не удобно, и не дает возможность получить информацию по точке (телефон, адрес сайта...)...

**Comment by tananaev** [comment]
@Abyss777, would you have time to implement this? It has been requested several times before and it should be fairly easy to implement now that we have refactored the database and manager's code.

**Comment by Abyss777** [comment]
I'm not sure POI management worth to be handled by traccar interface and its DB.

What do you think about extending user/server model with something like "POI layer" and handle it like URL to additional vector layer like http://openlayers.org/en/latest/examples/kml.html

I know the result is not easy to change (directly in kml file or with additional interface) but I still believe POI should not be very changeable, also the benefit it is possible to link some external POI layers, from openstreetmap for example.

@antontoto а чем неудобно использовать геозоны для 
> обозначать точки сбора, место расположения базового лагеря и т.п...

?

@tananaev may be there is a reason to handle clicks or mouse overs on geofences to show additional information, description or other additional fields.

**Comment by antontoto** [comment]
По поводу геозон:
1. Они масштабируются и на карте всего города просто не видны, текстовое описание тоже.
2. Добавленные геозоны не видны всем пользователям, для их видимости надо зайти в настройки каждого пользователя и поставить ему галочку - это смертоубийственный процесс будет при кол-ве пользователей >30...

PS По поводу внешних слоев, не могу пока ничего сказать, я в этих вопросах не опытен, важен результат, на карте необходимые объекты, и нужно понимание как их туда добавлять. Согласен, что часто они меняться не будут, работа почти разовая.

**Comment by tananaev** [comment]
По поводу второго пункта. Если мы добавим POI, то у них естественно тоже будут права доступа.

**Comment by antontoto** [comment]
Это понятно, но наверняка это будет что-то типа "группа" для POI и однажды включив ее для пользователей, дальше все добавляемые в нее POI будут отображаться автоматически, а сейчас каждое POI требует установки галочки для каждого пользователя (это если геозоны использовать).

**Comment by tananaev** [comment]
Группы у нас только для устройств. Возможно @Abyss777 прав и лучше KML файлы использовать. Тогда по идее можно права выставлять на целый набор сразу.

**Comment by kirantpatil** [comment]
:+1:    for adding  external POI layers, from openstreetmap

**Comment by antontoto** [comment]
Антон, добрый день.
Я пытаюсь вникать в суть происходящего на github, но в силу давнего отсутствия опыта в английском языке не все улавливаю.:)
Я так понял, что вы что-то реализовали по kml  и судя по скриншоту, kml можно подключить на сервере статически, потом вы тали обсуждать вариант подключения kml файла по ссылкам от пользователей?
В каком сейчас состоянии вопрос, завершен или еще в процессе и главное, чтобы у нас в развернутой системе появился этот функционал, что нужно сделать, обновить сервер?

С уважением, Антон.

**Comment by tananaev** [comment]
Подключение файла будет по ссылке. Функциональность готова, так что вы можете либо собрать версию из исходников и использовать, либо ждать официального релиза и тогда обновлять.

**Comment by antontoto** [comment]
Антон, добрый день.
Вижу один, на первый взгляд явный баг. Не знаю, может он у вас уже описан где-то...
В браузере в таблице устройства, меняю сортировку на сортировку по последнему времени обновления, таким образом наверху у меня все те, кто онлайн. Кликаю на кого-то из них. Он подсвечивается и на карте значок увеличивается, но через несколько секунд таблица уезжает...

Пробовал играть с сортировкой, такое ощущение, что корректно обновление таблицы работает только при сортировке "по умолчанию"...

С уважением, Антон.

**Comment by tananaev** [comment]
Пришлите видео с проблемой.

**Comment by antontoto** [comment]
--
Отправлено из Mail.Ru для Android понедельник, 12 февраля 2018г., 22:23 +03:00 от Anton Tananaev  notifications@github.com :

**Comment by tananaev** [comment]
GitHub не принимает приложения из электронных писем, если это то что вы пытались сделать.

**Comment by antontoto** [comment]
--
Отправлено из Mail.Ru для Android
