### ISSUE TITLE
Server not starting after wrapper ping timeout

### ISSUE THREAD

**Issue by tsmgeek** [tananaev/traccar#3718]
I have had the server shutdown but not restart a few times. This is not being manually initiated.
```
INFO|25521/0|Service traccar|18-01-15 01:31:23|Missing wrapper ping within timeout of 30000
WARNING|25521/0|Service traccar|18-01-15 01:31:29|ping between java application and wrapper timed out. if this this is due to server overload consider increasing wrapper.ping.timeout
```
a few seconds later this shows in the main traccar log
```
2018-01-15 01:31:41  INFO: Shutting down server...
```
It does not seem to restart after, I thought the wrapper was meant to handle auto restarting.

**Comment by tananaev** [comment]
Most likely it means that server doesn't have enough resources.
