### ISSUE TITLE
What exactly does OsmAnd mean?

### ISSUE THREAD

**Issue by PBW99** [tananaev/traccar#3720]
I know that the "OsmAnd protocol" is used by Traccar.
Is "OsmAnd" here meant this?
(osmand.net/) (Onffline Mobile Maps and Navigation)
Or is it something else?

OsmAndProtocol is only used to receive data from the Mobile Device.
(The Android app only uses HTTP.)
And in order to show the map in real web UI, I know that only "OpenLayer Library" is used.
(https://openlayers.org/)

Why did you name it OsmAndProtocol?

**Comment by tananaev** [comment]
OsmAnd protocol is protocol that can be used to receive location data from [OsmAnd app](http://osmand.net/). That's historical reason for the name. I'm not sure why you are so concerned about it.
