### ISSUE TITLE
Notifications for groups show every enabled user notifications.

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#3735]
Hello,

If I create a group, and then try to add a notification to that group, the choice in the windows show me every enabled notifications for every other user in the system.

**Comment by tananaev** [comment]
Please provide a screenshot of the problem.

**Comment by renaudallard** [comment]
Here is it, the 3 unchecked ones are not mine but those from other users
![screen shot 2018-01-22 at 21 11 54](https://user-images.githubusercontent.com/478410/35242133-fd2e3f66-ffb8-11e7-89fe-6178935db62f.png)

**Comment by renaudallard** [comment]
Here it is, the 3 unchecked ones are not mine, but those from other users.
![screen shot 2018-01-22 at 21 14 07](https://user-images.githubusercontent.com/478410/35242222-3d745eca-ffb9-11e7-8b75-82d23c0b5a49.png)

**Comment by renaudallard** [comment]
I only noticed now that the title of the window with the notifications is titled 'Saved Commands'

**Comment by tananaev** [comment]
I also noticed it... fixed it already. Was a simple typo.

**Comment by Abyss777** [comment]
@renaudallard 
If you are admin or manager it is designed behavior.

**Comment by renaudallard** [comment]
I am admin indeed. Although I don't really see the point of being able to add other users notifications to my own groups.
But I will close this issue if it's designed behaviour.

**Comment by Abyss777** [comment]
Admin should be able to link any object to any object.

**Comment by renaudallard** [comment]
@Abyss777 could you check https://www.traccar.org/forums/topic/per-group-notifications/
