### ISSUE TITLE
typo in gui?

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3748]
Hi Guys,
            In 3.15 under settings--> groups . When you go to notifications it shows "Saved Commands" as the heading for the pop-up. See image below

![image](https://user-images.githubusercontent.com/15850216/35646241-228fc2ca-0694-11e8-8c07-f9b85bc4c3db.png)

**Comment by tananaev** [comment]
I believe this has already been fixed:

https://github.com/tananaev/traccar-web/commit/9f4ad022beaf7f2bc7a67a397d3c48c64e57e4a5
