### ISSUE TITLE
Trying to add a new device with new port on an external platform

### ISSUE THREAD

**Issue by aliasgermodi** [tananaev/traccar#3751]
Hello,

I am using your parsing code to create a platform. Its working great with all the default ports that you have provided. But when I am trying to add a new port, its not working.
Can you help me with the procedure. 

Thank you. Really appreciate your help

**Comment by tananaev** [comment]
There should be no difference what the port numbers are.

**Comment by aliasgermodi** [comment]
Thank you for the quick reply!

We tested by adding everything on the traccar platform, and its working perfectly. But when we add the same files on our platform, its not working.
Your platform has default.xml with all the ports and other settings, we have traccar.xml for that.
We are adding the new class files which are generated in the protocol folder and making the port changes in the .xml file. 
Is there any other files that I am supposed to make changes on my platform?

**Comment by aliasgermodi** [comment]
We are basically trying to add a new protocol using your protocol codes! and its working on the traccar platform when we run on local server, but the same changes are not working on our platform

**Comment by tananaev** [comment]
Then there is some problem with your platform. What does it have to do with Traccar?

**Comment by aliasgermodi** [comment]
We are basically trying to add a new protocol using your protocol codes! and its working on the traccar platform when we run on local server, but the same changes are not working on our platform

**Comment by tananaev** [comment]
I'm closing this thread as it's not related to Traccar open source project. If you need help with your project we provide paid consultation services. Check the official website if you are interested.
