### ISSUE TITLE
Queclink devices report external power in mV, not Volts

### ISSUE THREAD

**Issue by ckrey** [tananaev/traccar#3758]
External Power as currently converted by Gl200TextProtocolDecoder.java:

![bildschirmfoto 2018-02-06 um 15 37 00](https://user-images.githubusercontent.com/4027289/35865853-e2bae1d6-0b55-11e8-9298-a14c6f77aa3d.png)

![bildschirmfoto 2018-02-06 um 15 44 54](https://user-images.githubusercontent.com/4027289/35865702-80e1b3fe-0b55-11e8-9e46-e23e16c8ca1f.png)
![bildschirmfoto 2018-02-06 um 15 41 59](https://user-images.githubusercontent.com/4027289/35865810-d0832ce4-0b55-11e8-8f68-34e14ca0709d.png)

Queclink specs says it is transferred in milliVolts (this page is copied from the GV55 description, but it is the same for all other devices I know of):
![bildschirmfoto 2018-02-06 um 15 34 54](https://user-images.githubusercontent.com/4027289/35865917-0a122fd2-0b56-11e8-8ab6-73f6e9e552a4.png)

traccar Position expects Volts:
![bildschirmfoto 2018-02-06 um 15 42 55](https://user-images.githubusercontent.com/4027289/35865773-b30e5c60-0b55-11e8-8be9-07ad3088d54a.png)

**Comment by tananaev** [comment]
I have fixed the problem. Thanks for detailed information.
