### ISSUE TITLE
Reports communication error

### ISSUE THREAD

**Issue by karls4** [tananaev/traccar#3760]
When running a report through the front end the report fails and a error pops up saying communication error.

If i run the report by using the api the report exports fine.

Both methods are using chrome
```
api/reports/trips?_dc=1517943276906&groupId=1&groupId=2&groupId=3&groupId=4&type=allEvents&from=2018-01-01T00%3A00%3A00.000Z&to=2018-02-10T00%3A00%3A00.000Z&page=1&start=0&limit=25
```

**Comment by tananaev** [comment]
Have you checked browser developer console for more information about the error?

**Comment by karls4** [comment]
Can you give me some tips on what I should be looking for or where I should be looking at? Am I better running it in debug mode?

I just tried the routes report and it seems to export fine using the API but it is in Json I think

/api/reports/route?_dc=1517943276906&groupId=1&groupId=2&groupId=3&groupId=4&type=allEvents&from=2018-01-01T00%3A00%3A00.000Z&to=2018-02-10T00%3A00%3A00.000Z&page=1&start=0&limit=25

**Comment by tananaev** [comment]
You need to look for the error in network request through browser developer console.

**Comment by karls4** [comment]
Hi, running in debug mode there arent any errors in Chrome when i press f12 and look at the network tab.

I can provide you temporary access to the server if you want to have a look?

**Comment by tananaev** [comment]
Why are you talking about debug mode? Reproduce the issue and check developer console.

**Comment by karls4** [comment]
Sorry i mean using /debug.html

I have opened the developer console, ran the report, got the error on screen but the developer console does not report a error

**Comment by tananaev** [comment]
What do you mean there is no error. Please provide a screenshot of the network call in the developer console.

**Comment by karls4** [comment]
![error](https://user-images.githubusercontent.com/22108543/35884764-8febc000-0b83-11e8-8610-d70117211ea8.PNG)

**Comment by tananaev** [comment]
Your report is 13 MB of data which is just massive. You should never make reports like this. Most likely it just timed out in your browser.

**Comment by karls4** [comment]
Just to recap on this, I have changed the sql server from MS SQL to MySQL and the report performance has improved massively.
