### ISSUE TITLE
Possible bug in manager having limit commands enabled

### ISSUE THREAD

**Issue by parveenkumardeeva** [tananaev/traccar#3762]
If we have a manager and limit commands enabled for him then he/she can give limit commands permission to another user while creating/editing user. And also backend is saving it successfully.
<img width="329" alt="screen shot 2018-02-08 at 4 17 41 pm" src="https://user-images.githubusercontent.com/16252073/35969430-c6c896ba-0cec-11e8-9ce4-c008a07c49ed.png">
<img width="1280" alt="screen shot 2018-02-08 at 4 22 14 pm" src="https://user-images.githubusercontent.com/16252073/35969434-cca229d4-0cec-11e8-8042-28e5490efef1.png">

**Comment by tananaev** [comment]
@Abyss777, what do you think? Should be extend command limit to manager users?

**Comment by Abyss777** [comment]
I do not see much sense. What is the purpose?

We are applying other limits only for traccar service providers, to allow sell service with limits by users or groups.

**Comment by tananaev** [comment]
@parveenkumardeeva, please explain use cases.

**Comment by parveenkumardeeva** [comment]
No, I don't have any specific use case in my mind till now. Now I see it's specially designed for standard Users only.

But should it be marked to the manager ? Because in that case manager users have much more permission than manager.
Manager can't send/create commands if nothing is assigned to him but end users can. Isn't it a flow in the design of the system from the programming perspective?
I think manager always have limit commands disabled. 
What's your opinion?

**Comment by Abyss777** [comment]
> But should it be marked to the manager ? Because in that case manager users have much more permission than manager.

> I think manager always have limit commands disabled.

It is up to Admin who creates the Manager, we can't limit Admins in anything.

**Comment by parveenkumardeeva** [comment]
OK, @Abyss777 . Closing it now.
