### ISSUE TITLE
Bypass of filters for selected data.

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#3780]
Hello,
Would it be a good idea to add a feature to bypass filters  for some data in certain cases?

For example, I filter on an duplicate or invalid position, but I would like battery level to still update. This would allow to update battery level for trackers that don't move often or which are not able to get GPS signal at the moment.

**Comment by Abyss777** [comment]
There is `filter.skipLimit` (documented) parameter to bypass filter by time see documentation https://www.traccar.org/configuration-file/

Also there is `filter.skipAttributes` config/attribute to bypass filter if position contain attribute from the list.
It is reasonable to set it at least as `"result,alarm"` to not lose alarms and command responses.

If your device report battery level periodically (not every position) you can add `battery` or `batteryLevel` to this parameter.

**Comment by renaudallard** [comment]
`filter.skipAttributes` is not in the configuration-file page you linked. Is it a yet unreleased feature?

**Comment by Abyss777** [comment]
It was released some time ago, but unfortunately not documented yet.

**Comment by renaudallard** [comment]
I found it in the code just a few seconds before you replied :)
Thanks, so this is already implemented, no need to discuss it. Maybe it should just be added to the documentation.

**Comment by tananaev** [comment]
I have updated documentation:

https://www.traccar.org/configuration-file/
