### ISSUE TITLE
Vulnerable to brute-force attack

### ISSUE THREAD

**Issue by Obaid-ur-Rehman** [tananaev/traccar#3791]
Traccar server must have a mechanism to block the IP requesting a certain number of login request.
There must also be a captcha on login screen to prevent bots.

**Comment by tananaev** [comment]
I don't think it should be part of Traccar system. There are well established projects that you can use to secure your instance of Traccar. For example something like fail2ban.

**Comment by Obaid-ur-Rehman** [comment]
can you name a project that works in windows?

**Comment by Obaid-ur-Rehman** [comment]
Thank you
