### ISSUE TITLE
Cant login due to server error

### ISSUE THREAD

**Issue by DiegoGitHub1** [tananaev/traccar#3801]
When I try to login it either gives me this message 
<img width="385" alt="untitled" src="https://user-images.githubusercontent.com/20413942/37117609-7e4a5c6c-2230-11e8-91c6-c970b23b7003.png"> or just goes to the same page without an error message.

**Comment by tananaev** [comment]
Connection to your database has timed out.

**Comment by DiegoGitHub1** [comment]
What can be done about this? Cant access since yesterday from 2 different devices AND networks.

**Comment by tananaev** [comment]
You need to fix your database or network issues.

**Comment by DiegoGitHub1** [comment]
The thing is that I'm using the demo server to login so I can't change the database.

**Comment by DiegoGitHub1** [comment]
Should have mention that, sorry.

**Comment by tananaev** [comment]
Which demo server?

**Comment by tananaev** [comment]
I have restarted the server. It should be working now. Please don't raise tickets like this on GitHub in future. There is a forum for that. GitHub is only for development-related discussions.
