### ISSUE TITLE
The error is in this line of the script - traccar/setup/setup.sh

### ISSUE THREAD

**Issue by Turbovix** [tananaev/traccar#3804]
The error is in this line of the script - traccar/setup/setup.sh

During the installation it presents the following error:
```
./setup.sh: 25: /opt/traccar/bin/installDaemon.sh: source: not found.
```

**Comment by Turbovix** [comment]
Anton, I solved the problem by replacing the dot with "sh", hence the installation ended successfully, however with the following warnings:

---------- YAJSW SET ENV ----------
INFO: lib not found: /opt/traccar/lib/extended/glazedlists/glazedlists-1.8.0_java15.jar
INFO: lib not found: /opt/traccar/lib/extended/glazedlists/commons-beanutils-1.8.2.jar
INFO: lib not found: /opt/traccar/lib/extended/glazedlists/commons-beanutils-1.8.2.jar
INFO: lib not found: /opt/traccar/lib/extended/glazedlists/glazedlists-1.8.0_java15.jar
YAJSW: yajsw-stable-12.09
OS: Linux / 4.13.0-36-generic / amd64
JVM: Oracle Corporation / 1.8.0_161 // usr / lib / jvm / java-8-oracle / jre / 64
Mar 10, 2018 4:32:25 PM org.apache.commons.vfs2.VfsLog info
INFO: Using "/ tmp / vfs_cache" as temporary files store.

In the setup.sh file I made the following change:

```
#! / bin / sh

if what java &> / dev / null
then
  if java -jar test.jar
  then
    mkdir -p / opt / traccar
    cp -r * / opt / tract
    rm -r ../out
    rm /opt/traccar/setup.sh
    chmod -R go + rX / opt / tracar
    cd / opt / drive / bin /
    sh /opt/traccar/bin/installDaemon.sh
  else
    echo 'Java 7 or higher is required'
  fi
else
  echo 'Java runtime is required'
fi
```

**Comment by tananaev** [comment]
What operating system are you using?

**Comment by Turbovix** [comment]
Ubuntu 17.10 64bit

**Comment by tananaev** [comment]
Fixed the issue.
