### ISSUE TITLE
Traccar manager iOS and android

### ISSUE THREAD

**Issue by rodrigonpg** [tananaev/traccar#3808]
Hello,

It’s posible to add a “change server” button when traccar failed to connect server??

Many people can have dinamic IP and unique solution is uninstall and reinstall app for it

Thanks in advance!!

**Comment by tananaev** [comment]
If you have dynamic IP why not use dyn-DNS service?

**Comment by tananaev** [comment]
Also, why is this in the server repo and not Traccar Manager project?

**Comment by rodrigonpg** [comment]
thanks! and sorry, i didnt found where to write it. I just only followed "pull request" and "issue" links in the top.

**Comment by tananaev** [comment]
When you create a new issue there is a message explaining everything. Did you just ignore it?

**Comment by rodrigonpg** [comment]
I didn’t pay attention
