### ISSUE TITLE
[Feature request] Notification name - with/without calendar

### ISSUE THREAD

**Issue by zielonydomek** [tananaev/traccar#3812]
Hi Anton ,
I have problem with change of notification name and lack of column (maybe with checkbox) "calendar" on notification list. I have one notification with calendar and one without calendar. Both have the same name in notification list. Could you think about it ?

**Comment by zielonydomek** [comment]
Hi ! I found (maybe I do something wrong) problem with additional column. After (every time) I close dialog box and open next time the additional column "calendar" go out.

**Comment by zielonydomek** [comment]
I compile and minify WEB only. Is that problem (I dont't think so but I'am not "strong" in java independencies. ;)

**Comment by tananaev** [comment]
Web app update should be enough.

**Comment by zielonydomek** [comment]
Anton could you check it ?

**Comment by tananaev** [comment]
Check what?

**Comment by zielonydomek** [comment]
Problem : dialog box did not remember column checked and added to the grid. If I open dialog box "notifications" ones again is the "old" vie without added column "calendar" .

**Comment by tananaev** [comment]
I don't think dialog state is saved, so it will automatically reset. That's expected.
