### ISSUE TITLE
[Feature request] Per user event forwarding / simplify PUSH implementation

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3814]
Looks like this feature rather demanded
https://github.com/tananaev/traccar/issues/3164
https://github.com/tananaev/traccar/issues/3757
https://github.com/tananaev/traccar/issues/3707
and others

I see it as fourth transport (called "Push" may be) in user interface and simple POSTing json to configured URL on backend. I believe it is easy to implement some PHP/perl/ruby/whatever page to proxy it to desired push service or FCM or even SMS via http
Initially I thought about implementing it as fallback for SMS but I believe we need separate set of templates for formatting: most push services support "tittle" and we should not economize letters as with SMS, but still not so long as emails. And some services can handle links differently.

Also I think it would be useful to post some user details with such object, here is draft of json object to POST:
This part is extracted from user object:
- `login` (why not to integrate with LDAP)
- `email`
- `phone`
- `serviceId` (value of configured user attribute, I think some services distinguish users by token, jid, internal id or something)

This part is constructed with template:
- `tittle`
- `body`
- `link`

**Comment by tananaev** [comment]
We already have forwarding. Maybe we should just add a list of users with each event?

**Comment by Abyss777** [comment]
Yes it is the solution. Simplest for us. Formatting and other things will be up to developers.

**Comment by atiqsamtia** [comment]
I have implemented the FCM Push Notifications in traccar check my pull request here https://github.com/traccar/traccar/pull/4002
