### ISSUE TITLE
SMS notification length limit error?

### ISSUE THREAD

**Issue by socstur** [tananaev/traccar#3818]
Hi Anton,
               I sent a command to one of my devices and the respond back from the device was not able to be sent via SMS notification to my number. I checked the logs and I see this error below about PDU length limit. The message to be sent vis SMS is also show below in the INFO section. The SMS function itself works as commands to other devices respond back with notification from traccar server.
```
2018-03-21 19:30:14  WARN: A short message in a PDU can only be a max of 255 bytes [actual=318]; use optional parameter message_payload as an alternative - SmppInvalidArgumentException (... < SmppClient:219 < *:239 < ...)
2018-03-21 19:30:14  INFO: [3BFD3745] id: 35889905918xxxx, time: 2018-03-21 19:29:48, lat: x.68146, lon: -x.17410, speed: 0.0, course: 208.0, result: \00\00\00Battery:4.22V,NORMAL; GPRS:Link Up GSM Signal Level:Strong; GPS:Successful positioning; SVS Used in fix:12(13); , GPS Signal Level:46,40,30,35,42,22,30,37,44,17,35,36 ACC:ON; Defense:OFF; 
```
Regards,

**Comment by tananaev** [comment]
Looks like SMS is too long.

**Comment by socstur** [comment]
Can this be fixed to allow traccar to send sms without the limit? Error message seem to indicate using message_payload should fix this.

**Comment by tananaev** [comment]
It's not a Traccar issue. It's an SMS limit:

https://en.wikipedia.org/wiki/SMS#Message_size

**Comment by socstur** [comment]
It says multi-part messsges can be sent in the event the sms is too long. Can this be supported on traccar?

**Comment by tananaev** [comment]
@Abyss777, do you know if it's possible?

**Comment by Abyss777** [comment]
@socstur 
Please tell what version of traccar you are using, can't find relevant strings in code.

**Comment by tananaev** [comment]
If it's too much effort, I don't think we should over-complicate it.

**Comment by jaimzj** [comment]
Wanted to add a small feedback here, the number of SMS sent will now vary depending on length.. so will this be considered in Statistics or will each SMS irrespective of length be counted as 1 sms. ?

**Comment by Abyss777** [comment]
@jaimzj 
It is still one SMS on traccar side. Low level SMS count depend on many factors, not only text length but also data encoding. I do not think such complex calculations worth to be implemented.

**Comment by socstur** [comment]
Woow...great work guys and excellent response time. I’ll test it out and report back if there are any issues.
