### ISSUE TITLE
Concox MT-200 MOPLUS device is supported traccar?

### ISSUE THREAD

**Issue by cyberrider35** [tananaev/traccar#3826]
Hi. I have a questions

Concox MT-200 MOPLUS device is supported traccar?
Port Number? 
I have investigated, but have not reached a conclusion.
Have a good days.

**Comment by tananaev** [comment]
Use forum for questions. Also, you need to provide either message samples or protocol documentation to verify if it's supported.

**Comment by cyberrider35** [comment]
I understand my friend. Thank you. 
how can I learn message samples?
