### ISSUE TITLE
traccar customisation

### ISSUE THREAD

**Issue by conqug** [tananaev/traccar#387]
Any options for customising traccar? i.e specific icons on specific vehicle

currently tracking 4 vehicles, previously used (gps-trace) and liked the option for customisation

Is it possible to zoom on tracks automatically instead of logging into traccar and having to zoom manually to track

save map type ( i.e having google hybrid as default )

Thanks again

**Comment by tananaev** [comment]
For now the decision is to use OpenLayers.
