### ISSUE TITLE
customisation

### ISSUE THREAD

**Issue by kaplis77** [tananaev/traccar#391]
Any options for customising traccar? i.e specific icons on specific vehicle.

If you put mouse on tracking object you will see the information  about name, speed or unit is moving...
Are you plan it??

I know that everything need time, but if you wil make this improvements I am ready to send you the donation. 
Sorry for my english I hope you understand what I want to say.

**Comment by tananaev** [comment]
In the latest release you can select icon type for each device. You can also see all the information, including name, speed etc.
