### ISSUE TITLE
Android View Client App

### ISSUE THREAD

**Issue by cristianormoraes** [tananaev/traccar#392]
I'm thinking about developing an android app to show real-time positioning from traccar server, but I do not know what is the best way to retrieve the data, it would be a direct connection to the mysql database  or create a webservice on the server?

Any tips?

**Comment by catrucho** [comment]
Is there someone who has developed an Android apk to get and show positions from the server. The mobile web is not very friendly.
I am creating a python script to proxy between an chinese app ( the one that most of the chinese devices use) who uses soap to comunicate with traccar rest but as I am learning python at the same time is quite painful ( By the way I didn't code before in any language).
The script basically listen for connection from the apk in WDL, translate the request to rest, connect to traccar api rest, get the data, traslate it to wdsl and send it back
After a month I was able to login, see and follow a gps device in the app ( which uses google maps api).
But if the android apk for traccar is to be released in the near future I would stop working on this inmediately.
If no I would be forced to learn to program an Android apk, and if learning python is painfull I guess that android would be a year's task.
Thanks

**Comment by tananaev** [comment]
First of all, in the next release there will be more mobile-friendly web interface. You can already try it if you get server source code from GitHub.

Mobile apps for both Android and iOS are also in plans.

**Comment by hackerunet** [comment]
anton I have an apk developed look for google play app "ubicatugps"

**Comment by tananaev** [comment]
@hackerunet, it doesn't look like a native Android app. Is it a web view based app?

**Comment by tananaev** [comment]
Traccar now has mobile apps for both Android and iOS.
