### ISSUE TITLE
Real time via akka actors

### ISSUE THREAD

**Issue by freynoso** [tananaev/traccar#410]
Hi Anton.
I just made an aditional event handler who notify a play! web interface via akka actors. The play! backend send "locations" to the browser via Server Sent Events (in real time).
Do you have interest in such code? I have seen related issues, but i dont know if this "mix" of technologies fits yours preferences.

Regards
pd: sorry about my english

Quick links:
www.playframework.com
akka.io

**Comment by tananaev** [comment]
Traccar uses WebSockets connection in recent versions for real-time updates.
