### ISSUE TITLE
Outbound connection vs listener

### ISSUE THREAD

**Issue by sdhughes1** [tananaev/traccar#418]
I'm trying to test traccar with a Cisco router with onboard GPS. The device streams NMEA data when you connect to it (i.e. "telnet ip-address 2006")

Is there any functionality in traccar to connect to remote devices, rather than listen for connections? Is there a utility or wrapper which will do this for me?

The router seems to emit raw NMEA -- no device identifier, so traccar would probably have to use the IP address of the device as the identifier.

**Comment by tananaev** [comment]
Closing this as stale. I haven't heard any other requests for the same functionality since this thread.
