### ISSUE TITLE
Rastreador Modelo MXT 150 do fabricante MAXTRACK...como programar no Traccar ??

### ISSUE THREAD

**Issue by MarcelloCaires** [tananaev/traccar#432]
Srs,
Tenho alguns equipamentos do modelo MXT 150 - fabricante Maxtrack, que não encontrei na lista de rastreadores suportados pelo Traccar.

Vocês poderiam me informar se esse tipo de dispositivo funciona no Traccar ??

Att
Marcello
mcaires2012@gmail.com

**Comment by drecchia** [comment]
@MarcelloCaires  I have the protocol, but I do not believe its a good idea since the protocol is protected by a NDA and should not be published as opensource. Ive an private gateway with this protocol if your interested. Regards.

**Comment by lfcs** [comment]
@drecchia Pode me enviar o protocolo? Estou precisando.

**Comment by brenowd** [comment]
hi @drecchia send me please

**Comment by drecchia** [comment]
Hi, traccar has already implemented Mxt Protocol to decode tracking: https://github.com/tananaev/traccar/blob/master/src/org/traccar/protocol/MtxProtocolDecoder.java

**Comment by claytonmarinho** [comment]
Hi @drecchia.
I saw that MtxProtocolDecoder.java and also tried to decode in nodejs. Looks difficult but maybe there is some trick that i did not get on java code. Should you share some advice or like a name of this kind of buffer encode?

Thank you very much.

**Comment by drecchia** [comment]
@claytonmarinho The packet starts with 0x01 and ends with 0x04, so any occurrence of 0x01, 0x04, 0x10 hex in the body of the msg will be preceded by 0x10 and incremented by 32 ( decimal ). The values always have the same size, but they are not always present. There is a bitmap on the header that determine which data are in the packet.  

Regards.

**Comment by gustavofcalmeida** [comment]
@drecchia I believe Traccar has only partially implemented MXT protocol. I have an MXT-140 pointing to a Traccar server, configured to report every minute, but Traccar only receives messages every 7 minutes, also, every message is doubled.
I believe the ACK response to the tracker is yet to be implemented.

Regarding the "disclosure" of the protocol, the most important part -- the decoding -- is already disclosed and open source. Would it be real trouble to disclose the rest?

**Comment by drecchia** [comment]
Yes, probably there is something wrong with server ack. Wasnt me who implemented this protocol in traccar, If you have the docs, please send to tananav so it can be fixed.
