### ISSUE TITLE
GalileoSky speed problems and missing positions

### ISSUE THREAD

**Issue by christodupreez** [tananaev/traccar#447]
I'm using GalileoSky units and the speeds are all wrong. I'm comparing it with the data on Wialon and It almost seems that all the speeds are about 45% of what they should be.
Wialon / openGTS

65 / 35.2
78 / 42
108 / 58.3
109 / 59.01

I also noticed that there are fever positions in openGTS than in Wialon.

I suppose this is two different issues but both equally important.

Please help.

**Comment by tananaev** [comment]
Closing as stale. Please create a new thread if problem still exists.
