### ISSUE TITLE
Atrack AX5 extra info not saved

### ISSUE THREAD

**Issue by Birria** [tananaev/traccar#455]
(I wrote this in an other issue that was already closed)

I noticed one thing ..the AX5 is able to send some extra info about the vehicle as a string at the end, and saw in the especific processing jar that there is a variable that takes that info, but it seems it does not saves it to the database.

Could it be posible you make it save it to the Message field?

**Comment by tananaev** [comment]
Support for Atrack protocol has been extended to include decoding of long date format and all additional information.

**Comment by tananaev** [comment]
Extra data has been supported for Atrack protocol for some time now.
