### ISSUE TITLE
Add New Protocol for Maestro Micro Tracker

### ISSUE THREAD

**Issue by RNSolutions** [tananaev/traccar#465]
I have a Micro Tracker from Maestro Wireless Solutions. The device is setup to send data through a TCP connection. I have attached the link to the manual. Thanks.

Reports example for parser development
@123451234512345,531,DEMO,1,12.5,30,0,0,11/10/10,09:09:09,22.222222,114.141414,45.6,0.0,160.0,8,1,20!

link:
http://www.maestro-wireless.com/download-dp2

**Comment by tananaev** [comment]
Link does not work anymore.

**Comment by tananaev** [comment]
Closing as documentation is not available. If protocol is still required, please re-open and provide documentation.
