### ISSUE TITLE
[feature request] user management

### ISSUE THREAD

**Issue by sickmind** [tananaev/traccar#492]
Administrator can add devices on behalf of ordinary users.
Ordinary users that can not add / delete devices (or 3rd type of user account that have only view privileges)

**Comment by tufanbhattarai** [comment]
@hackerunet  could you please give me the link to view the php frontend source code of traccar so that i can get some idea to make my front end with PHP? I am working on that..

**Comment by hackerunet** [comment]
If you need traccar source code get.into traccar.org and check in the web
app, my front end is not traccar front end is mine and was made from
scratch. Traccar doesnt have a php based frontend as far as i know.

**Comment by tananaev** [comment]
User and device management is available in recent versions of Traccar server.
