### ISSUE TITLE
how to send a command to devices?

### ISSUE THREAD

**Issue by ellezerh** [tananaev/traccar#493]
hi,
i have commands table on database, when a user command for any device from traccar web server,  I want to send these commands to selected devices. 
how to do it. could you give me a clue?

**Comment by peluzza** [comment]
Maybe the solution is to create a proxy in the server machine, resending incoming data to traccar and sending commands to the tracker

**Comment by bernamaxim** [comment]
I have about 500 unit, I was using code to cut engine with configure resetDelay, and it works.

Thanks for @hackerunet and @tananaev for the advice.

**Comment by cabreu1981** [comment]
bernamaxim, please can you share the code, im using a GT06,
Regards.

**Comment by tananaev** [comment]
@cabreu1981, this is a very old thread. Traccar now supports commands, so there is no need for any workarounds.

**Comment by cabreu1981** [comment]
well when i send a command turn off/on engine to a gt06 device it only returns {}

**Comment by tananaev** [comment]
If you have some problems with API, please create a new issue instead of reviving this old thread.

**Comment by tananaev** [comment]
Command are supported. Closing this thread. If anyone has any questions, please create a new thread.
