### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by r4mZeS** [tananaev/traccar#513]
Hi, Anton!
I have a few questions for Traccar.
It would be really great if we could add their own POI and pics of the cars to the map. To facilitate the localization of the interface, must bind variables in the .war file to an external lang files. For example make a /lang directory and place langs files as a txt, xml, or some other files that could interact with variables from .war file. Also, would be nice if there was a possibility create your own themes using css and html markup. This step would help increase the amount of third-party themes for interface. Actually I want to say that Traccar wonderful product that has great potential and I want to say thank you for the development of this amazing tracking system!
I very much hope that my suggestions will be heard.
Thanks.

**Comment by nefertiti007** [comment]
It would be nice to have images of different type of vehicles/cars objects.
Where specially if its a vehicle, based on direction/course of travelling available in position the relevant image should be loaded to in the set direction.

I have achieved this in php custom front end, would be nice to have it in traccar as well.

**Comment by Abyss777** [comment]
@tananaev 

I'm thinking of images for different type of object and want to use "top view" images like this http://www.shutterstock.com/pic-309456359/stock-vector-car-icons-top-view-set-automobile-and-vehicle-vector-illuistration.html (just an example)
Main benefit of top view is that we can still show course (and it does not look stupid like with side view) 

There are two options:
1. Store pixel images as png, but we have to have 3 files with different colors(connection status) for every vehicle type. And can get some distortion on rotate and zoom.
2. Store vector images in one svg (may be even in js files as xml to easy access). But they have to be specially developed to change color.

Benefits on first option: 
- Images can be easily replaced and added just as files
Benefits of second option:
- All benefits of vector images and possibility to not hardcode color.

What is better you think? Or other ideas?
 Also, how we will store type of device image in DB? Extend model or use attributes?

**Comment by tananaev** [comment]
I'm for vector images. Top view sounds good to me.

It sounds like a major feature, so we can add a new column to the device table.

**Comment by r4mZeS** [comment]
I have another idea. I guess would be better use special traccar font based on vectors of the different cars for specific chars. It's not difficult to create it. In settings could be easily specify the size in pixels and a color for the font, the similar to how it's done in fontawesome. In the future that font will be possible to update, adding new types of vehicles such as tractor, atv, motorcycle, etc.. Imo, this solution has amazing flexibility and scalability.

**Comment by Abyss777** [comment]
@r4mZeS 
I'm not sure we can fill inner area of font glyph by custom color. Can we?

**Comment by r4mZeS** [comment]
@Abyss777 Sorry, I didn't quite understand what do you mean. We can use any color for any cars if we would use classes of stylesheet.

**Comment by Abyss777** [comment]
I mean get image like this and change green color to any other programmatically:
![1](https://cloud.githubusercontent.com/assets/5688080/19446684/63f7d5c6-94b3-11e6-99f2-09c305d0601f.png)
not this
![2](https://cloud.githubusercontent.com/assets/5688080/19446709/75e03c60-94b3-11e6-9899-044c1cce0bf4.png)
or this
![3](https://cloud.githubusercontent.com/assets/5688080/19446721/7cbd95c8-94b3-11e6-9a47-a025a08e8423.png)

**Comment by tananaev** [comment]
I don't think font would help with drawing on the map. Regular vector images (probably SVG) would be just as good, plus customizing them would be easier for end users.

**Comment by Abyss777** [comment]
I'm thinking over of POI functionality and, frankly, not fully understand the purpose.

Standart POIs are on the openstreetmaps already, like ATMs, museums, groceries and so on.

If somebody wants to mark some places on the map, like Home, Work, Mistress's House and so on, he can use geofences with benefits of enter/exit events.

Any thoughts are welcome.

**Comment by jaimzj** [comment]
@Abyss777  My thought on POI is a bit different, using geo-fence for the same is good. However POI can be like a small flag/pin on the map a specific location which is specific to a users application/need.

And unlike Geo-fence where you also need to display its radius and or borders, POI need not have a radius/area. thus displaying it on the live map while tracking and during route playback history display is easier.

POI can also be in future used to create notifications on proximity of device location to that particular POI.

POI Helps add customer markers/pins on map for any businesses and or application who would want to know where their target device is , assuming a admin has 100 devices roaming around a town, and everytime he knows one location within a city is his client 'x' he can mark it as client 'x' and next time the device is there everyone knows the device is visiting client 'x'. (when he has 100's of clients its difficult to make geo-fence for all clients, and more or less, the more the geo-fence the more processing) if its POI Markers, there need not be any events/triggers either. and easier to delete/add/rename etc

True it can be done via geo-fence, but the only benefit i see is POI does not have an area/radius, and displaying it on map takes up less real-estate.

**Comment by tananaev** [comment]
I agree with @Abyss777. I don't really see a good use case at this point. It would be nice if someone can point out an example where POIs would be necessary and geofences won't do the job.

**Comment by Abyss777** [comment]
Also, geofences not linked to devices do not cause server load, nothing is calculated.

> POI can also be in future used to create notifications on proximity of device location to that particular POI.

I do not see any difference with circle geofence here
