### ISSUE TITLE
Xexun xt-009 - lat/long OK but no altitude

### ISSUE THREAD

**Issue by nbonniere** [tananaev/traccar#545]
The Xexun xt-009 uses the same protocol as the TK102-2 (port 5000) which also contains altitude, but the altitude is displayed as 0 in the web interface. The lat/long is reported OK.

When a packet contains more than one fix, as it catches up with it's SD card memory, the data isn't parsed properly.

**Comment by tananaev** [comment]
Now the only port for Xexun devices is 5006.
