### ISSUE TITLE
Have a netty warning

### ISSUE THREAD

**Issue by scroller123** [tananaev/traccar#553]
Hello. 
After 2-3 days of starting the server, i got WARN:
2014-02-07 12:42:36  WARN: netty warning: Failed to accept a connection

And after that one of connected devices ceases response. After that history repeats and another device turning off. Etc at the end - all devices does not response.

**Comment by sebitoelcheater** [comment]
UPDATE:
You should be using
```
<entry key='gt06.timeout'>60</entry>
```
instead of
```
<entry key='gt06.resetDelay'>60</entry>
```
`resetDelay` is deprecated.
#1524

**Comment by erhv74** [comment]
In my case was a <entry key='meitrack.timeout'>60</entry> connecting to port 5020. This parameter solve an issue affecting the platform in a way of "too many open files" and "connections idle"
