### ISSUE TITLE
Traccar Server using SQL Server Connection Failed

### ISSUE THREAD

**Issue by anjumsohail** [tananaev/traccar#557]
I am trying to use SQL server database with Traccar using link below
http://www.traccar.org/docs/mssql.jsp
using below configurations :

<entry key='database.driverFile'>C:\sqljdbc4.jar</entry>
<entry key='database.driver'>com.microsoft.sqlserver.jdbc.SQLServerDriver</entry>
<entry key='database.dataSource'>com.microsoft.sqlserver.jdbc.SQLServerDataSource</entry>
<entry key='database.url'>jdbc:sqlserver://INT-MAJID;databaseName=VTS;user=sa;password=[password];</entry>
<entry key='database.user'>sa</entry>
<entry key='database.password'>[password]</entry>

but i get below error in log file.

INFO   | jvm 1    | 2014/02/11 15:00:06 | 2014-02-11 15:00:06.240:WARN:/:unavailable
INFO   | jvm 1    | 2014/02/11 15:00:06 | java.lang.ClassCastException: javax.naming.Reference cannot be cast to javax.sql.DataSource

plz assist.

**Comment by tananaev** [comment]
Instructions for the version 3.0 of Traccar can be found here:

https://www.traccar.org/ms-sql/
