### ISSUE TITLE
How to configure Teltonika devices via TCP ?

### ISSUE THREAD

**Issue by andromida** [tananaev/traccar#559]
Hi,
I know that Traccar does not support devices configuration. I want to know how can we configure a Teltonika device via TCP, may someone could do it.
I heart that is impossible to configure Teltonika devices via GPRS TCP, but the protocol document, they talk about remote configuration:

""" To initiate configuration process, configuration server sends binary initiation SMS (“Push” SMS) containing server host(ip address) and tcp port device should connect to and waits for TCP connection. Upon reception of “push” SMS, device tries to establish TCP connection to configuration server using GPRS. If TCP connection attempt succeeds, server sends out configuration data to device over established connection, device confirms configuration reception and configures itself. If device doesn't connect to server in TcpWaitTimeout time, server stops waiting for TCP connection, sends out configuration data using binary SMS, and waits for confirmation SMS from device. If confirmation SMS doesn't arrive in specified time, server assumes that configuration process failed. """

I did like they said but I got no response from the device

**Comment by tananaev** [comment]
Closing as stale. Feel free to re-open if some help is still required.
