### ISSUE TITLE
Edit the website name from traccar to another name

### ISSUE THREAD

**Issue by yoosouf** [tananaev/traccar#590]
Am not a Programmer 

please help me to Edit the website name from traccar to another name

let me know where to go to edit this

**Comment by selvagee** [comment]
Hi yoosuf,

how to unzip and again zip as a war format in traccar.html

**Comment by tananaev** [comment]
Latest release doesn't use `war` files any more. If you are using the old one, you should be able to use standard zip archive tools to unzip and zip the file again.

**Comment by bhekimadide** [comment]
Hi Tananaev

On the new version, where is the file that I need to modify to to change Traccar to "Something Else"?

Thank you for the great work

**Comment by tananaev** [comment]
Here is the file:

https://github.com/tananaev/traccar/blob/master/web/release.html

**Comment by bhekimadide** [comment]
You are awesome! thank you

**Comment by superservidor** [comment]
1) download the file traccar-web.war  to a local folder on your PC

2) Rename the file traccar-web.war  to traccar-web.war.zip

3) Extract the files from the file traccar-web.war.zip inside the same folder that contains the file traccar-web.war.zip

4) Edit the html files and change the Title

5) Delete the file traccar-web.war.zip

5) Compress all the files inside the folder to a file called traccar-web.war.zip

6) Change the name of the file traccar-web.war.zip to traccar-web.war

7) Upload the file again to the /opt/traccar folder

**Comment by tananaev** [comment]
@esurnet, please don't comment on old closed threads. If you have a question, create a new FORUM thread.
