### ISSUE TITLE
ContextPath should be a configuration option

### ISSUE THREAD

**Issue by diegopeinador** [tananaev/traccar#593]
Change org/traccar/http/WebServer.java:83 to look like:
webapp.setContextPath(properties.getProperty("http.contextPath", "/"));

Sorry, I don't have a Java environment to test this and make a proper pull request.

**Comment by pengc99** [comment]
Just wanted to follow up and see if this was implemented yet in the new version of the web app.

**Comment by tananaev** [comment]
Yes, with versions 3.0 and newer you can use Apache mod_proxy with Traccar server.
