### ISSUE TITLE
OBD GPS Trackers protocols implemented in Traccar?

### ISSUE THREAD

**Issue by maciekfreak** [tananaev/traccar#614]
Are in Traccar already implemented any protocols used in OBDII Trackers? 
If yes? Are this implemented protocols using any other received datas like acceleration, speed, fuel datas from canbus or only gps position?

Thanks,

**Comment by jlindqvist** [comment]
Hi again Anton,

I am trying to use traccar as a administration tool for car expense reimbursements to my company. To make that work I need to be able to calculate each trip from point A to point B for every single time I drive the car somewhere. Is this something that Traccar can or will support?

I might just have got the wrong idea of how to use the software or I still do not got the tracking with the TC68 working.

If of any help, feel free to login to my server and have a look yourself.

URL:	traccar.ekovis.se <http://traccar.ekovis.se/>
User:	admin
Pass:	admin2015

Thanks in advance and kudos for all the work put into the project so far!

Best regards,
Jonas Lindqvist

- - - - >> - - - - - - - - - - - - - >> - - - - - - >> 
 Jonas Lindqvist
 jonas.lindqvist@gmail.com

 US: +1 (415) 994-2761, SE: +46-70-3504969, FAX: +46-8-51989274
 PROFILE: www.linkedin.com/in/jonaslindqvist

 #Please consider the environment before deciding to print this e-mail

**Comment by tananaev** [comment]
Traccar will support it at some point, but unfortunately it doesn't support it yet.

As for TC68, I need log files to check what's wrong.

FIY, you emailed to GitHub which means any user on the internet can now access your server with admin rights, so I suggest you change passwords before someone else does it. If you want to send me private email you can find my address in the GitHub profile.

**Comment by betonme** [comment]
The protocol documentation including obd data description on page 7 chapter 1.3
http://www.gps-vehicle.com/download/gpsthai/MEITRACK_GPRS_PROTOCOL_V1.6.pdf
