### ISSUE TITLE
TK-Star (Chaser) - No incoming data

### ISSUE THREAD

**Issue by Rogge23** [tananaev/traccar#623]
Hello,

we've got a big problem with our gps-tracker "tkstar" or model "chaser". We don't know which protocol is the right protocol for our tracker or what's the main problem. We also tried to redirect all ports to 8888, but it still doesn't work. The server log detects no incoming data of the tracker or such similiar. But the tracker is working and is sending out his information every 30 seconds. 

The server is installed, like it's described in the instructions. Maybe anyone has an idea, which could be our main problem. If you need something to know more about the problem, please ask. It's our first try to install the traccar gps server.

Thank you very much!

Best regards,
Rogge

**Comment by johngamarra** [comment]
hi @Rogge23 could you help me what commands do you use to configure the tracker?

**Comment by tananaev** [comment]
Closing old thread.
