### ISSUE TITLE
Crowntech 3G GPS Tracker model TW-MD1101 or VSDTR3GPS 2WIN

### ISSUE THREAD

**Issue by study3ggsm** [tananaev/traccar#624]
Hello,
I have a 3G GPS Tracker model TW-MD1101 or VSDTR3GPS. Vendor Hong Kong Crown Technology or 2WIN. The message sent by tracker to IP address is as following:
Serial number + authorized number +GPRMC+ signal indicator
Remark：the part of GPRMC outputs according to the NMEA (National Ma2rine Electronics Association) , 0183.
You can add this protocol?
Thanks

**Comment by tananaev** [comment]
Traccar supports GPS device connection status, so you can see when was the last message received from your device.
