### ISSUE TITLE
how can we get distance travelled or total distance travelled.

### ISSUE THREAD

**Issue by jyotirbhandari** [tananaev/traccar#627]
@tananaev 

Hi Anton,

How can we get total distance travelled, like in opengts we have distanceKM field in EventData table.
 
Is it possible. I tried to integrate opengts database with traccar but device is not adding up, can that help me temporary to get distance travelled.

Please advice, as to how can I get distance travelled.

Regards
Jyotir

**Comment by potash18** [comment]
Hi,
If you're still interested I added this on my mysql server to calculate distance between points per device ID.
It can be done by creating an Insert Trigger and then using the following code:

```
CREATE DEFINER=`YOUR_DB_USERNAME`@`%` TRIGGER `OL_trg_IComputerDistance` BEFORE INSERT ON `positions`
 FOR EACH ROW Begin 
	Declare vnlatitude,vnlongitude,vdistance,volatitude,volongitude 

double;
    Declare vid, vidold, vdeviceid int;
    set vnlatitude = NEW.latitude;
    set vnlongitude = NEW.longitude;
    set vid = NEW.id;
    set vdeviceid = New.deviceid;
    set vidold = ( Select max(id) From positions where deviceid = vdeviceid); 
    If vidold >0 THEN
    	set volatitude = (Select latitude From  positions Where id = vidold);
        set volongitude = (Select longitude From  positions Where id = vidold);
     	set vdistance = acos(sin(volatitude)*sin(vnlatitude)+cos(volatitude)

*cos(vnlatitude)
                             *cos(vnlongitude-volongitude))*6371;
        set vdistance = radians(vdistance);
    Else 
    	Set vdistance = 0;
    End If;
    set new.distance = vdistance;
    
End

```

**Comment by tananaev** [comment]
@potash18, this is a pretty old thread. Since then Traccar has implemented distance calculation, so there is no need for triggers or other database-based solutions.
