### ISSUE TITLE
how can we restrict updating last postion if the car is stopped for long time in same location ?

### ISSUE THREAD

**Issue by jyotirbhandari** [tananaev/traccar#629]
@tananaev 

Hi Anton, 

how can we restrict updating last postion if the car is stopped for long time in same location ?
 In my opengts, I am started getting multiple pushpins in same location and that looks untidy.

I tried to modify private.xml - <Property key="map.minProximity">50</Property>,

But still I'm having multiple pushpins, can it be done by traccar dcs, and if yes can you tell me how can I do that.

I'm not a developer but if you can help me I can still make it work.

Regards
Jyotir

**Comment by tananaev** [comment]
Distance filtering can be used to implement this.
