### ISSUE TITLE
how to get statusCode opengts traccar integration ?

### ISSUE THREAD

**Issue by jyotirbhandari** [tananaev/traccar#638]
Hi 

The default value which is passed in integration of traccar and opengts for statusCode is 0, which is causing issue in opengts, status in reports and is showing none in all.

How can we get correct statusCode in order to get values.

 Note : http://www.traccar.org/docs/opengts.jsp the statusCode value is passed 0 

Regards
Jyotir

**Comment by satbikkel** [comment]
@tananaev : So, how does server know that status is for example InMotion?

if speed of tracker > 3 km/h  and digital input is true (acc) then car is moving so 0xF112 (dec: 61714) is writen in the database op opengts.

if tracker digital input (acc of car) is true for the first time and speed < 3 km/h, status is startMotion.0xF111(dec: 61713).

if digital input is false and last status is inMotion, status is stopMotion

**Comment by tananaev** [comment]
Ignition status is not available for all devices and if we just use speed parameter there would be too many errors.

**Comment by sq9njj** [comment]
Can you tell me how to setup status code for opengts ? I want to have startmotion if previous speed value was less then 1km/h and present is more then 1km/h, in motion when previous speed was >1 and current >1 and stop motion if previous >1 and current <1. How to make it work ?

**Comment by tananaev** [comment]
I don't think there is an easy way to check previous speed value, but to check current value you can do following (change is in bold):

<pre>&lt;entry key='database.insertPosition'&gt;
    START TRANSACTION;
        UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastUpdateTime = UNIX_TIMESTAMP(NOW()) WHERE imeiNumber = RIGHT(CONCAT('000000000000000', :deviceId), 15);
        SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = RIGHT(CONCAT('000000000000000', :deviceId), 15);
        INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, creationTime, address)
        VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), <b>IF(:speed &gt; 1, 61714, 61716)</b>, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', UNIX_TIMESTAMP(NOW()), :address);
    COMMIT;
&lt;/entry&gt;</pre>

**Comment by sq9njj** [comment]
Can you help me how to get StartMotion and StopMotion status without checking for previous speed value? As far as now I use tk102 clone and there is no ignition check signal output :( Is there any way to do it ??

**Comment by sq9njj** [comment]
My config now is:

    START TRANSACTION;
            SELECT @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM FROM Device WHERE imeiNumber = :device_id;
            SELECT @distance := ((ACOS(SIN(@lastLatitude * PI() / 180) * SIN(:latitude * PI() / 180) + COS(@lastLatitude * PI() / 180) * COS(:latitude * PI() / 180) * COS((@lastLongitude - :$
            UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastOdometerKM = @odometer + @distance, lastUpdateTime$
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = :device_id;
            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, creationTime, address)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), IF(:speed > 1, 61714, 61716), :latitude, :longitude, :speed * 1.852, :course, :altitude, '', @distance, @odometer + @distanc$
        COMMIT;

maybe it's possible to make lastspeedvalue ??

**Comment by tananaev** [comment]
Does OpenGTS database have last speed value stored somewhere?

**Comment by sq9njj** [comment]
I think not, but is it possible to make something like this ?? Where do I make mistake

       START TRANSACTION;
            SELECT @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM FROM Device WHERE imeiNumber = :device_id;
            SELECT @lastSpeed := speedKPH FROM EventData WHERE accountID = @accountID AND deviceID = @deviceID ORDER BY timestamp DESC LIMIT 1;
            SELECT @distance := ((ACOS(SIN(@lastLatitude * PI() / 180) * SIN(:latitude * PI() / 180) + COS(@lastLatitude * PI() / 180) * COS(:latitude * PI() / 180) * COS((@lastLongitude - :$
            UPDATE Device SET lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:time), lastOdometerKM = @odometer + @distance, lastUpdateTime$
            SELECT @accountID := accountID, @deviceID := deviceID FROM Device WHERE imeiNumber = :device_id;
            IF (:speed > 1) AND (@distance = 0) THEN
             SELECT @fakeStatus := 61713
              ELSE IF (:speed > 1) AND (@distance > 0) THEN
                SELECT @fakeStatus := 61714
              ELSE IF (:speed < 1) AND (@distance > 0) THEN
                SELECT @fakeStatus := 61715
              ELSE
                SELECT @fakeStatus := 61716
            END IF
            INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, creationTime, address)
            VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:time), @fakeStatus, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', @distance, @odometer + @distance, UNIX_TIMESTAMP$
        COMMIT;

**Comment by tananaev** [comment]
I guess it's possible, but querying EventData table on every insert can affect performance.

**Comment by sq9njj** [comment]
This config I've shown in my last post does not work. Can you tell me where I've made mistake ?

**Comment by tananaev** [comment]
Your SQL query is cut on the right (I assume by text editor). I need to see full query.

Also, what error message do you get with this query?

**Comment by sq9njj** [comment]
problem is the IF END IF section. I can't restart traccar with his code :(

**Comment by tananaev** [comment]
Instead of your IF statements try this:
<pre>SELECT @fakeStatus := CASE
    WHEN (:speed > 1) AND (@distance = 0) THEN 61713
    WHEN (:speed > 1) AND (@distance > 0) THEN 61714
    WHEN (:speed < 1) AND (@distance > 0) THEN 61715
    ELSE 61716
END;</pre>

**Comment by tananaev** [comment]
You can also check #1131.

**Comment by nokiado** [comment]
<entry key='database.insertPosition'>
    START TRANSACTION;
       
        SELECT @lastIgnitionValue := ignitionIndex,  @lastBatteryLevel := lastBatteryLevel, @accountID := accountID, @deviceID := deviceID, @lastSpeedKPH := lastValidSpeed, @lastLatitude := lastValidLatitude, @lastLongitude := lastValidLongitude, @odometer := lastOdometerKM FROM Device WHERE imeiNumber = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2);
        
        SET @alarmpos := LOCATE('alarm', :attributes) + 7;

        SELECT @ignitionval := CASE
           WHEN (@alarmpos > 0) AND (SUBSTR(:attributes, @alarmpos, 1) = 't') AND SUBSTRING(:attributes, LOCATE('ignition', :attributes, @alarmpos) + 10, 1) = 't' THEN 1
           ELSE @lastIgnitionValue
        END;

        SELECT @powerval := CASE
           WHEN (@alarmpos > 0) AND (SUBSTR(:attributes, @alarmpos, 1) = 't') THEN  SUBSTRING(:attributes, LOCATE('power', :attributes, @ignitionpos) + 7, 1)
        ELSE @lastBatteryLevel
        END;

        SELECT @fakeStatus := CASE
        	WHEN (@lastIgnitionValue = 0) AND (@ignitionval =1) THEN 62465
            WHEN (@ignitionval =1) AND (:speed &lt; 3)THEN 61718
		    WHEN (:speed &gt; 3) AND (@lastSpeedKPH &lt; 3) THEN 61713
            WHEN (:speed &gt; 3) AND (@lastSpeedKPH &gt; 3) THEN 61714
            WHEN (:speed &lt; 3) AND (@lastSpeedKPH &gt; 3) THEN 61715
            WHEN (:speed &lt; 3) AND (@lastSpeedKPH &lt; 3) THEN 61717
            ELSE 61717		    
		END;
		
		SELECT  @distance := 1.609344 * 3956 * 2 * ASIN(SQRT( POWER(SIN((@lastLatitude - :latitude) *  pi()/180 / 2), 2) +COS(@lastLatitude * pi()/180) * COS(:latitude * pi()/180) * POWER(SIN((@lastLongitude - :longitude) * pi()/180 / 2), 2) ));

		SET @lastOdometer := @odometer + @distance;

		UPDATE Device SET ignitionIndex = @ignitionval,  lastBatteryLevel = @powerval, lastValidLatitude = :latitude, lastValidLongitude = :longitude, lastGPSTimestamp = UNIX_TIMESTAMP(:fixTime), lastUpdateTime = UNIX_TIMESTAMP(NOW()), lastValidSpeed = :speed * 1.852, lastOdometerKM = @lastOdometer   WHERE imeiNumber = SUBSTRING(CAST(:deviceId AS CHAR(32)), 2);

        INSERT INTO EventData (accountID, deviceID, timestamp, statusCode, latitude, longitude, speedKPH, heading, altitude, rawData, distanceKM, odometerKM, creationTime, address)
        VALUES (@accountID, @deviceID, UNIX_TIMESTAMP(:fixTime), @fakeStatus, :latitude, :longitude, :speed * 1.852, :course, :altitude, '', @distance, @lastOdometer, UNIX_TIMESTAMP(NOW()), :address);
    COMMIT;
</entry>
