### ISSUE TITLE
Traccar stop decoding the info received from xexun TK 103-2 (Stop working)

### ISSUE THREAD

**Issue by milci199** [tananaev/traccar#648]
Dear Anton, Hello:
I have traccar working with 2 devices, one of them doesn't work (Issue #555) and I have given up with that one. But the second one (Xexun TK 103-2) worked fine till 3 weeks ago when sudenly it has stopped working, It first did this: 3 weeks ago, just stopped working, I checked the "tracker-server.log" file and aparently it received the info sent by the device, at that time I reinstalled the program and worked fine again till 2 days ago, when it has decoded last time the info, as in the first episode, the info keeps coming, but it is not decoded anymore. I tried to fix it by reinstalling it again and nothing.

**Comment by tananaev** [comment]
Closing as stale. If problem still exists, please reopen.
