### ISSUE TITLE
Position lost when database (mysql) is down.

### ISSUE THREAD

**Issue by Gerry69** [tananaev/traccar#658]
Hi, Tananaev
I have this issue:
I have traccar server and mysql database linked, if database is down, i lose positions, because the gps device (Teltonika) once it has received ack from traccar server delete position record. It is possible than traccar do test connection to database before to send ack to gps device? Or in other ways try to write in database before to send ack to device? Otherwise, if database is down, can traccar server save data to a text file, the goal would be to recovery data after than the database is on line.

Sorry for the bad english...

Gerry

**Comment by tananaev** [comment]
There is a script that you can use to recover data from the log file:

https://github.com/tananaev/traccar/blob/master/tools/recover.py
