### ISSUE TITLE
NS mark

### ISSUE THREAD

**Issue by marcwlux** [tananaev/traccar#681]
Hi,
Does someone has experience with the NS mark units?

http://www.nomadicsolutions.biz/prod.php?lg=fr&id=32

I think that they have a own protocol or can made compatible to Intellitrac X1.
For information, these units run on battery up to 8 months.
I can't find any doc now.
thanks
Marc

**Comment by tananaev** [comment]
Closing as stale. If you still have some questions, please create a new thread or reopen this one.
