### ISSUE TITLE
GT09B is sending position rarely

### ISSUE THREAD

**Issue by sachitad** [tananaev/traccar#683]
Hi,

I am using GT09B gps tracking device using GT06 protocol. The device is sending the position only sometimes. The tracking device is set to send the location every 10 seconds. I am receiving HEX code of the device:
```
2014-04-25 15:50:48 DEBUG: [5023 <- 188.71.220.30] - HEX: 78780a1340066400010005da510d0a
2014-04-25 15:50:48 DEBUG: [5023 -> 188.71.220.30] - HEX: 787805130005afd50d0a
in every 10 seconds but not the position. What is wrong?
```
Thank you so much for this great software.

**Comment by tananaev** [comment]
Traccar has been supporting status messages for GT06 protocol for some time now.
