### ISSUE TITLE
Server System Requirements Recommendation

### ISSUE THREAD

**Issue by andriasmelianus** [tananaev/traccar#690]
Hi,
I build the web as per my requirements and I use this library. I know that I can not use the regular shared hosting, because we need to open some ports to allow the communication between tracker and server.
I prefer to use the Virtual Private Server (VPS). <b>But I would like to know what is the minimum system requirement to run this library and my web as per your recommendation.</b>

And if you don't mind, can you explain how do we turn off the vehicle machine through the website if the tracker is ported on a car?
I am very new to these stuffs. :grin: 
Thanks..

**Comment by inghoward** [comment]
Hello Tananaev. Congratulations for your great job.
I know you have said some times that a minimum is 1Gb is necessary to manage a small amount of devices, but how much is that? I know is a difficult answer, but some estimated amount would be appreciated. How much is that, 10, 50, 100 devices?
What is the configuration of the server where you have tested 10k devices?
Thanks for your answers

**Comment by tananaev** [comment]
Small number of devices is probably 100 or slightly more. For 10k devices client used something like 16GB, but you don't really need that much. Probably 8GB or even 4GB would do.

**Comment by tananaev** [comment]
I would just recommend to try different options. You can easily get VPS from Amazon or Azure and pay per hour rate to test drive the server and see if it's enough to handle the load.

**Comment by kuldiplive** [comment]
1)Lease-web VPS also have solid performance , I have used their NL and 
SG datacenters  quite solid performance.
with Lease-web only thing is that you cannot directly upgrade / 
downgrade VPS,  you have to buy new vps only.
Proivdes : basic firewall from customer portal.

2) https://joesdatacenter.com/  I used their servers for testing , they 
offer dedicated box at cheap rate I rate them 3.5 / 10
To use them you need to be solid linux admin , also need to buy 
secondary HDD for raid 5 .
My hdd got crashed  but was on raid 5 so saved.

Note : Above hosts are unmanaged .


------ Original Message ------

**Comment by tananaev** [comment]
My point was not about picking the best VPS provider. It was about the fact that with some providers you can hire a VM for a day or even less to test which configuration is best for you.
