### ISSUE TITLE
Send commands

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#7]
Very useful feature to be able to send command from server to tracker. It can be used to configure tracker. First of all add background support for this feature (through jetty servlet), later add some buttons to web interface (it is probably separate issue).

**Comment by drecchia** [comment]
Im general, the command have a type and the data, the you gonna need mount the preamble, header and apply some byte encoding. The order is tracker dependent. For first successul tracking for each channel, you may save the serial to match when sending the command. Regars.

**Comment by jokopitoyo** [comment]
I have apply control GPS over web.... for some  device and work well..

For server:
1. Save every channel into Map collection 
     class GPSInfo{
            Int id;
            Channel channel;
            Map<GPSCommand> listCommand;
     }
2. Create Thread to check if command available, if channel still alive send, else process another command
Web :
1. define general command inside web like "POSITION","RESTART","CUTENGINE","RESUMEENGINE"
2. define gps type every device
3. convert general command to spesific command by gps type.

**Comment by tananaev** [comment]
Do you have any code to share?

**Comment by jokopitoyo** [comment]
Currently i develop using Netty 4.0.25, totally different with your style, but if youhave interest i will send by email..

**Comment by tananaev** [comment]
I am interested; email address is in profile. Thanks.

**Comment by effumachi** [comment]
Hi @hackerunet May u send me an example of your code? tks

**Comment by hackerunet** [comment]
Example of what code? Please refresh my memory!!

**Comment by effumachi** [comment]
@hackerunet Code to send command to devices through traccar
