### ISSUE TITLE
Delete Logs

### ISSUE THREAD

**Issue by bernamaxim** [tananaev/traccar#721]
Can Traccar delete logs automatically? Because its too waste my harddisk space, my logs still here since 2012

**Comment by tananaev** [comment]
Command that I'm using to set up automatic log removal on Linux machines:

```sh
printf '#!/bin/sh\nfind /opt/traccar/logs/ -mtime +5 -type f -delete\n' > /etc/cron.daily/traccar-clear-logs && chmod +x /etc/cron.daily/traccar-clear-logs
```

It keeps last 5 days.
