### ISSUE TITLE
Integration with APRS network

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#749]
For more info see:
http://www.aprs-is.net/

**Comment by tananaev** [comment]
Closing for now. Please comment if you are interested in this.

**Comment by dorianwoolger** [comment]
Hi very intrested in this, is it something that has been done? Mainly looking to take APRS data into Traccar. Possibly from a private APRS-IS server.

**Comment by tananaev** [comment]
Nothing has been done so far.

**Comment by dorianwoolger** [comment]
Many thanks for the quick reply. Are there plans to include this intragration? If so do you have an idea of timescale?

**Comment by tananaev** [comment]
There is no plan at the moment, but if you are interested in sponsoring the work we can discuss it.
