### ISSUE TITLE
Variation of VT310 by Meigalio VT1000

### ISSUE THREAD

**Issue by Doluci** [tananaev/traccar#755]
Hello Tananaev,
I have a VT1000 made by a china company TopShine. It is compatible to VT310 protocol wise but when I connect it to Traccar, it does work but not able to get the additional RFID data that comes at the end of the input data. How can I modify the existing VT310 parser to include this information in the other information field of the database,. I am using mysql under ubuntu linux.  I have the protocol documentation from the manufacturer adn it looks almost like that for VT310 except the addition of the RFID capability

**Comment by tananaev** [comment]
I have implemented RFID support for VT1000. If anyone is interested I can provide a binary file for testing.

**Comment by princeuchendu** [comment]
Hello Tananaev,
Is this same one you added for me for a fee or is it a different
implementation that I can benefit from as I still have your earlier code?

**Comment by tananaev** [comment]
This time it's a universal solution.

**Comment by pquevedo** [comment]
I have some topshine protocols please send me an email pquevedoe@gmail.com

**Comment by tananaev** [comment]
My email address is in profile.

**Comment by tananaev** [comment]
I'm not sure if you realize, but you didn't send me a personal email. You posted a comment on github. If you want to send a personal email, check my profile for email address.

**Comment by pquevedo** [comment]
Hello how are you doing? I am interested in information about 4g tracking
equipmemt . Can you sen me the update catalog?
Greetings
