### ISSUE TITLE
Old GPS coordinates in logfiles

### ISSUE THREAD

**Issue by Geert1969** [tananaev/traccar#762]
Hello,
Since a few days now whenever our S911 Lola sends new GPS coordinates to Traccar also old coordinates are written into the log files.
This causes that the database is not being updated and the device cannot be traced in Traccar Web.
Would this be the device who sends those old coordinates or has it another cause?
Thank you very much for your help.
Best Regards,
Geert

**Comment by tananaev** [comment]
Closing as stale. Feel free to comment if any updates.
