### ISSUE TITLE
Trying to create a CALAMP Decoder

### ISSUE THREAD

**Issue by joselovb** [tananaev/traccar#774]
I'm sorry if I bother you, but I'm trying to implement a CalAmp LMU2720 decoder.

This device uses UDP for connecting and it needs an ACK message so it can keep tracking. 

The problem I have is:

I am not sending an ACK the right way. I am using the method  MessageEvent.getChannel() and then I try to write the ACK message in this channel. The channel address I get is 0.0.0.0:1741 so I get an ACK error.

Also i am working usin a firewall that redirects my public IP Addres to my server using nat, i don't think this is the problem because i with the CELLOCATOR decoder is working like charm.

If you could guide or help me a little I will be very grateful.

Thanks on advance

**Comment by tananaev** [comment]
CalAmp protocol is now supported in Traccar. See https://github.com/tananaev/traccar/commit/662b552ba75c874ca1f1d67310f7004eb5da1991.

**Comment by joselovb** [comment]
Wow.

Thats Great!

Atte.


Ing. José Carlos Valdivia Bedregal

RPC: 994704447
RPM: #624006
Movistar: 959009988
