### ISSUE TITLE
Odometer in MVT340

### ISSUE THREAD

**Issue by yiyoMX** [tananaev/traccar#822]
Hi Anton I've installed the integration of traccar with opengts, I setted up a Meitrack MVT340, and its reporting its coordinates and altitude, but the odometer field has no data, does traccar supports the odometer in this or any devices?
Tanks, best regards!

**Comment by luckyif** [comment]
Hi Anton , please help i have the same situation . 
Only TK103 tracker. What do odometer to work?
Thanks!

**Comment by tananaev** [comment]
Please provide message samples from your device.

**Comment by luckyif** [comment]
HEX: 283032373034333035323030304252303031353035303941343835332e393131394e30323434352e30383637453030302e31323132393334302e3030303030303030303030304c303030303030303029

**Comment by tananaev** [comment]
Your device sends 0 as odometer value.

**Comment by luckyif** [comment]
That does not work I do?

**Comment by tananaev** [comment]
This is decoded message (<a href="https://www.traccar.org/hex-decoder/">hex decoder</a>):
<pre>(027043052000BR00150509A4853.9119N02445.0867E000.12129340.000000000000L<b>00000000</b>)</pre>

I have highlighted the odometer value. As you can see it's 0 which probably means that your device doesn't support it.

**Comment by luckyif** [comment]
Thanks!

**Comment by luckyif** [comment]
And how to make sure that the data recorded only at certain times? For example from 10.00 to 20.00?

**Comment by tananaev** [comment]
Traccar doesn't have such functionality, but maybe you can set up your device to send only in certain time of day.

**Comment by luckyif** [comment]
How can i delete data from a table EventData in the last 3 hours?

**Comment by tananaev** [comment]
Something like this (I recommend doing backup first if you have any important data in the database):
<pre>DELETE FROM EventData WHERE timestamp &gt; DATE_ADD(NOW(), INTERVAL -3 HOUR);</pre>
