### ISSUE TITLE
Orion OBDtrac support

### ISSUE THREAD

**Issue by jcmwc** [tananaev/traccar#832]
Firstly congratulations for your work.
I use Traccar for Teltonika boxes (FM 1000 and FM 1010) and it works very well.
I just recovered boxes OBDtrac Orion.
http://www.oriontech.com.tw/obdtrac.htm
I would like to add a listerner in Traccar, but I admit that my java skills are old.

this is a link with all doc for protocol : http://madewithcaffeine.com/file/Orion.zip

If you could help me it would be a pleasure. I can configure a device to an ip and port if necessary.

Sorry for my english (I'm french)

For information i am currently using mysql, and i had to change the size of fields other
WARN: Data truncation: Data too long for column 'other' at row 1 - com.mysql.jdbc.MysqlDataTruncation (MysqlIO.java:4230)

**Comment by tananaev** [comment]
Closing as stale. If it's still relevant, please re-open.
