### ISSUE TITLE
steps for traccar setup

### ISSUE THREAD

**Issue by hssnkd** [tananaev/traccar#845]
hi all,
I need help
I installed the traccar server on windows server2008 with public IP address
and I had login by browser with this IP:Port  " 74.208.96.177:8082   " with admin/admin.
My GPS device name AVL05 or 06 and the messages that I sent to SIM card are:
```
*000000,011,net.asiacell.com,,#
*000000,018,300,999#
*000000,015,0,74.208.96.177,5005#
*000000,016,1#
```
After that I add the IMEI for GPS in traccar server.
The problem I cloud not see my GPS .
Is all those steps right ?
Please I need help

**Comment by raliam** [comment]
When I installed the Traccar software in windows 10, which host number should I use instead of 8082 to synch up with traccar client? and how to configure firewall with this?
Regards

**Comment by tananaev** [comment]
@raliam, have you looked at the dates on this thread? Please never comment on an old closed thread.

As for your question, port for Traccar Client is always 5055 by default.

**Comment by raliam** [comment]
Okay dear;
Regards!
