### ISSUE TITLE
How to modify Gl200 protocol to pass cell information without GPS coordinates

### ISSUE THREAD

**Issue by Robbt** [tananaev/traccar#856]
This is a question regarding the Gl200ProtocolDecoder. 
When the device reports and doesn't have a GPS coordinate it still passes useful information such as Cell phone tower etc which can be used to geolocate it via a Mobile Location Provider in OpenGTS, but Traccar doesn't correctly validate the information because of missing fields.

So my question is what is the best way to modify the ProtocolDecoder code to validate the rest of the fields when those are blank.

I'll probably play around and see what answers I can come up with, right now I'm thinking I might have to modify the pattern RegEX.
```java
 private static final Pattern pattern = Pattern.compile(
            "\+RESP:GT...," +
            "[0-9a-fA-F]{6}," +                 // Protocol version
            "(\d{15}),._," +                   // IMEI
            "(\d_)," +                         // GPS accuracy
            "(\d+.\d)," +                     // Speed
            "(\d+)," +                         // Course
            "(-?\d+\.\d)," +                 // Altitude
            "(-?\d+\.\d+)," +                // Longitude
            "(-?\d+\.\d+)," +                // Latitude
            "(\d{4})(\d{2})(\d{2})" +        // Date (YYYYMMDD)
            "(\d{2})(\d{2})(\d{2})," +       // Time (HHMMSS)
            "(\d{4})," +                       // MCC
            "(\d{4})," +                       // MNC
            "(\p{XDigit}{4})," +               // LAC
            "(\p{XDigit}{4})," +               // Cell
            "(?:._,(\d{1,3}),\d{14},)?" +     // Battery
            "._");
```
Here is an example of the translated hex code received with no GPS coordinates.
```
+RESP:GTFRI,120113,555564055560555,,1,1,1,,,,,,,,0282,0380,f080,cabf,6900,79,20140824165629,0001$
```
vs.
```
+RESP:GTFRI,120113,555564055560555,,1,1,1,9,0.1,0,23.3,-83.0653212,40.282310,20140824225604,0282,0380,f080,cabf,6900,75,20140824225604,0001$
```
But it looks like a bit of processing would need to happen to also pull the Date/Time from the end of the field after the battery as well, as that data is missing from the report with no GPS coordinates as well.

So any advice as to the best way to approach this would be appreciated. I'm thinking I could strip down some of the validation on the RegEx to simply look for comas vs. validating the data but there might be a better way that I'm not thinking of or problems associated with that approach.

Thanks.

**Comment by nwohaibi** [comment]
Sorry to bring up an old discussion ..
Is there a way to log all non-gps messages to the database or a file?
thanks in advance

**Comment by tananaev** [comment]
They are logged in the file (`tracker-server.log`).
