### ISSUE TITLE
Invalid lat long jumps on GPS protocols

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar#865]
Hi anton, I was wondering if you have added any validation method inside protocols to avoid inserting invalid positions, such jumps can be validated with some basic phisics, like acceleration or speed formulas..

**Comment by nitinzambani** [comment]
HI

**Comment by tananaev** [comment]
@nitinzambani, that's a very big distance. It must be device firmware issue.

**Comment by nitinzambani** [comment]
hi
that's what i also think, but 1 thing which bothers me is these jumps are to 1 location only and not to any random location, i have added the snap of map, here vehicle is going from A to B and its jumping in between to location c many times. this is just 15 min travel  
![map](https://cloud.githubusercontent.com/assets/16347581/12975019/8bbe7e5a-d0de-11e5-9f92-779e127ff24c.JPG)

any idea

**Comment by tananaev** [comment]
What device are you using?

**Comment by nitinzambani** [comment]
device name is GT02a, and its protocol is TK103

**Comment by nitinzambani** [comment]
more over all the devices started troubling all most same time..!,
i have attached an txt file with data of position table for single device
the last column is what i have added to calculate distance from last location 
you wiill see for few locations its showing distance as 23136 meters...!
i m getting no idea how do i trouble shoot this problem...
[mp.txt](https://github.com/tananaev/traccar/files/126292/mp.txt)

**Comment by tananaev** [comment]
Are you using your own server. I need logs (tracker-server.log) to investigate the problem. Also, I would recommend to open another issue on GitHub for your problem.

**Comment by nitinzambani** [comment]
HI tananaev, 
thanks ..
yes i m using own server ,
 i have created a another issue with number #1720 , 
and attached the log file also
due to size limitation i have truncated the log file and it contains data till 4:30 pm 
and the positions table data also for the same time , so its easy to match with each other
