### ISSUE TITLE
GPS tracker Simulator

### ISSUE THREAD

**Issue by fulup-bzh** [tananaev/traccar#889]
For info,

I wrote a GpsTracker simulator, that hopefully could be useful to others. The concept is pretty simple,
1) you create a GPX route with a navigation plotter like OpenCPN, a real GPS device, or one line with http://www.visugpx.com/editgpx
2) you start the simulator and ask to push/server data to your server/client.

The simulator generate intermediary point depending on requested speed and tic time. The output flow is NMEA but if needed it could easily be change to something else.  This simulator is shipped as a part of a bigger project, but it works in standalone independently of the rest of the project. It uses node.js and can be downloaded from: 
    https://www.npmjs.org/package/gpsdtracking

Note: I developed this simulator for my own test of my gpsdtracking. While I started with traccar, I choose to shift to something more lightweight. Hosting Java apps is not as easy as it should for me.

**Comment by tananaev** [comment]
Closing. Feel free to post this information on the official forum, if you want.
