### ISSUE TITLE
TLT-2H new GPRS protocol

### ISSUE THREAD

**Issue by hcniet** [tananaev/traccar#893]
Dear.

There are an new protocol for TLT-2H/2HU/2HS/2N with support to GPRS commands and 2-way communication.

https://www.dropbox.com/s/zzcqp2py07pppb7/Communication%20Protocol.pdf?dl=0

Best Regards

Henrique

**Comment by JucianoC** [comment]
Hello guys, how to configure this tracker to work in 2-way keep link?
