### ISSUE TITLE
How to send data from my gps device (built it myself) to traccar

### ISSUE THREAD

**Issue by dkingftorts** [tananaev/traccar#902]
I have developed a gps device (with sim900A and skg13c) and there is an option to assign an IP address and port to send GPRS packets (containing the GPS data parsed from NMEA strings). Now as I have figured out, I need to create a public IP, install something called a webserver on it and keep a port open on listening mode to recieve data from the GPRS device. With your experience, can you help me out, with the easiest way to do the same; to send data from the GPS tracker to a database and then onto a map (with Traccar)

**Comment by tananaev** [comment]
Closing as stale. If this thread is still relevant, please reopen.
