### ISSUE TITLE
More data from GOT10 (OBD2)

### ISSUE THREAD

**Issue by vzoltan** [tananaev/traccar#907]
Hi, i just found your traccar project, and it works fine with my GOT10 device.

Would you please add obd2 features to your webserver/database/interface like, the GOT10 device has in its original webinterface here. http://www.keelin.com.cn/

Here is the communication protocol pdf, and if you need i can provide whireshark dump files.
http://www.eelink.com.cn/uploads/datasheet/EELINK_Terminal_Communication_Protocol_V1.8.4_EN.pdf

**Comment by piresbruno** [comment]
Hi vzoltan,

Do you have the latest firmware for your device, or do you know where to get it?


Thanks,
Bruno

**Comment by vzoltan** [comment]
Hi, i have no idea what is the version of the firmware i use. How can i check it?

Az iPademről küldve

2015. ápr. 19. dátummal, 12:45 időpontban Bruno Pires <notifications@github.com> írta:

**Comment by piresbruno** [comment]
Hi,

Send an SMS to the device with the text "VERSION#"

**Comment by piresbruno** [comment]
Do you have access to Eelink http://keelin.com.cn or http://www.sky200.com platforms?

**Comment by vzoltan** [comment]
It has no credit on it, wont answear :)

**Comment by piresbruno** [comment]
Thanks anyway :)

**Comment by vzoltan** [comment]
What version do you have and what is the difference between versions?

**Comment by piresbruno** [comment]
The device has v1.8.4 and i need to install v1.8.5 to have access to the DTC fault codes

**Comment by vzoltan** [comment]
Mine is:
SYSTEM:M5000_V1.8.8
VERSION:MXAPP_V1.8.9
BUILD_Sep 25 2014 18:53:52


update command is:
UPGRADE,C4_EXT.exf,www.sky200.com,69#


size is about 91kb

**Comment by luca-saggese** [comment]
Hello vzoltan,
would you share the upgrade file? i'm getting always timeout when trying to update, and i'm stuck with a faulty 1.8.4 version that is draining my car battery.

Thanks

**Comment by vzoltan** [comment]
i dont have an upgrade file.
i just sent the command via sms to the device and it updated itself.
but that was 2 years ago.
