### ISSUE TITLE
Unknown protocol

### ISSUE THREAD

**Issue by markobgd** [tananaev/traccar#916]
HI 
I got tracker imei:354188030032584 it is kind of tk102 but it doesn't follow tk102 communication protocol, not even close. 

here is sample packets:
```
0000: 78 78 0D 01 03 54 18 80 30 03 25 84 00 09 D4 76           xx...T..0.%....v
0010: 0D 0A               

0000: 78 78 0A 13 C0 00 64 00 01 00 08 9F 53 0D 0A                xx....d.....S..

0000: 78 78 1F 12 0E 0A 09 05 20 06 C7 04 CD 3D 0C 02           xx...... ....=..
0010: 30 94 A2 00 34 97 00 DC 05 00 3F 00 04 C6 00 07           0...4.....?.....
0020: A3 37 0D 0A      

0000: 78 78 1F 12 0E 0A 09 05 1F 24 C6 04 CD 3D 60 02           xx.......$...=`.
0010: 30 94 94 00 34 97 00 DC 05 00 3F 00 04 C6 00 06           0...4.....?.....
0020: 00 45 0D 0A 
```
Can you recognize this protocol ? 

Big thanks

**Comment by realyte** [comment]
Hello I'm ploblema to put the tracker E3 in traccar am using version 3.7 the server receives the hex package and even with traduzer in hexdecode
www.traccar.org/hex-decoder/ more traccar naum updated tracker.

I'm using port 5056 EasyTrack

Below my logs:
11.01.2016 17:04:08 DEBUG: [2E8497B2: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c48422c412c3130306230322c3033303430372c38306436646230612c38316163633561642c303030302c313833382c30303430303030302c31362c36322c303030302c3962382c30230d0a
11.01.2016 17:04:12 DEBUG: [2E8497B2: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c4d51230d0a
11.01.2016 17:04:42 DEBUG: [2E8497B2: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c4d51230d0a
11.01.2016 17:04:58 DEBUG: [2E8497B2: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c48422c412c3130306230322c3033303433392c38306436646230612c38316163633561642c303030302c313833382c30303430303030302c31362c36302c303030302c3962382c30230d0a
11.01.2016 17:05:12 DEBUG: [2E8497B2: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c4d51230d0a
11.01.2016 17:05:42 DEBUG: [2E8497B2: 5056 <186227158250] HEX: 2a45542c3335383135353130303035333033362c4d51230d0a
01.11.2016 17:05:57 INFO: [2E8497B2] disconnected

Can someone help me ?

Wagner Vieira

**Comment by tananaev** [comment]
@realyte, it's easytrack protocol, port 5056 in Traccar. Please next time create a new issue instead of commenting on an old one.

**Comment by gcpaladino** [comment]
how to parse data in php or golang?
