### ISSUE TITLE
Label for position marker

### ISSUE THREAD

**Issue by strebrah** [tananaev/traccar#926]
Hi, 

I don't know if the following topic is directly related; https://github.com/tananaev/traccar-web/issues/140  
But I have the following question; 

Would it be possible to implement a label under the (current) position marker of a GPS tracker?  
It would look something like this; http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.9/markerwithlabel/examples/basic.html

That way its easier to keep track of multiple GPS trackers on the map.

website; https://code.google.com/p/google-maps-utility-library-v3/
source: http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/

Thanks in advance.

**Comment by tananaev** [comment]
This has been available in official Traccar for a while.
