### ISSUE TITLE
Support for VT808 protocol

### ISSUE THREAD

**Issue by krish222** [tananaev/traccar#932]
Hi experts, I am dealing with this a Chinese vendor called HUABAO (http://www.huabaogps.com/). Their trackers use a protocol called VT808 which is provided by China Department of transport. Can you please advise if traccar server supports this protocol and which port I should configure for the same on the server side?

Thanks
Krish

**Comment by sandroacoelho** [comment]
Hi @krish222. I think that I have finished the implementation. Could you help me in the tests? If yes,  please email me  (sandroacoelho@gmail.com) and then I will send the server, port and a user and password. Thank you!

**Comment by yopyhi** [comment]
Hi Sandro, did you finally get to test the protocol? I have one. Can I be of any help?

**Comment by sandroacoelho** [comment]
Hi @yopyhi
I have tested the HUABAO traccar protocol  with @Chris10014 in Brazil  and it works.From now, I need a time to refactor it because @tanaev didn't accept the code.

Best,

**Comment by Mattolo** [comment]
Hi, are there any news for the JT808 protocol? I have many devices that currently use it. 
Thank you so much for your availability

**Comment by erickjohne** [comment]
Dear Colleagues, 

Just checking before creating a new post if the protocol JT808 is now supported on traccar?

Thank you

**Comment by tananaev** [comment]
Have you tested it?

**Comment by erickjohne** [comment]
Hi Anton,

Not yet because I will need to import them first,
So i was wondering, if this is already working, otherwise i will go for a
different tracker , as we will buy a huge volume,

**Comment by tananaev** [comment]
I would recommend getting a sample first and testing it. That would me my recommendation even if you knew that the protocol is compatible.

**Comment by erickjohne** [comment]
Will do so, Anton
Many thanks,
