### ISSUE TITLE
traccar server

### ISSUE THREAD

**Issue by gonenmustafa** [tananaev/traccar#936]
hi I read all the comments about traccar server, I download traccar for windows and traccar server which as soon as I download and run the traccar, server automatically comes in the traccar file. I can run traccar in the localhost:8082 with no problem. I wanna run it on my computer server. I did load the apache server and checked it runs.. I made my external ip static and my computer ip static.. and over my static computer ip I did forward ports (80, 443, 5005). so I don't know where to put traccar server files?? to run over my computer server.. seems like it I create a server and did everything right.. I want to be able to reach to my computer server to open traccar.. how that works pls help help

**Comment by tananaev** [comment]
Closing as stale. Feel free to reopen if there are still some questions.
