### ISSUE TITLE
DataManager interface

### ISSUE THREAD

**Issue by hallmark9** [tananaev/traccar#954]
First of all, thank you for the great work. However, I think eliminating the interface "DataManager" and using a DataManager super class instead is a step backward. Let me explain my case:

I don't save data in the database. Instead, I stream the data to a remote webservice, therefore, I had my own MyDataManager class which implemented the old DataManager interface. This worked beautifully and made your code very extensible because I don't have to make code changes elsewhere.

Now you removed the interface so I had to work around this by extending your new "DataManager" class in order to avoid changing tons of code that reference "DataManager". However, the new "DataManager" is so closely coupled with database operations in mind, making it so hard to maintain/modify MyDataManager. For example, lots of new "DataManager" methods now throw "SQLException" and MyDataManager has to have the same signature even though it has nothing to do with SQL (because it's a webservice streamer). At the same time, it cannot throw ConnectException unless modify the method signature of its superclass DataManager.

So please reconsider bringing back an interface for extension purpose? Thanks again.

**Comment by hallmark9** [comment]
Anton,

I noticed there's quite significant code refactoring going on with the current version...Maybe it's a good time to consider the DataManager interface refactor as well? Thanks.

**Comment by tananaev** [comment]
By refactoring you mean bringing back interface?

**Comment by hallmark9** [comment]
Yes please, if that's not against the general design/architecture.

**Comment by tananaev** [comment]
I think it's a good idea because I need it anyway for unit testing.

**Comment by tananaev** [comment]
I am planning to work on this issue some time soon. I also have sort of related issue #1131.

Basically, I want to implement a handler which will forward positions to some HTTP service. Can you give more details on your HTTP service and what your requests look like? I guess you are interested in GPS data and you don't need Traccar web interface, correct?

**Comment by hallmark9** [comment]
Thanks for getting on this. I've no particular requirement for the interface. Just make it generic and not DB coupled (like SQLException...) and can be used for anyone to extend to any other data consumers. One basic method is sufficient for my web service: 
public void addPosition(Position position) throws Exception;

Issue #1131 seems to require more specific to data format and could be a sub-interface of the above.

Thanks again.

**Comment by tananaev** [comment]
How do you get the list of registered devices? From web service as well or from database?

So if I implement a separate handler with a single method `addPosition`, would that be enough for you?

**Comment by hallmark9** [comment]
Web service manage the devices so there's no need to manage it in traccar.

A single addPosition() should be enough but please make sure code elsewhere references this interface only, not any implemented classes. You can add other methods as you see needed.

**Comment by hallmark9** [comment]
One more thing, in web services case, a local db is not needed. Would it be possible to add a key in the traccar.xml to bypass all the db code added in v3.0 such as dataManager.initDatabaseSchema() and dbCache.init()? 

Sorry if I am asking too much but architecturally there should be a way to make traccar a lightweight proxy (without local db), just as in v2.x. And, DataManager interface should capture only the high-level methods relevant to "data" only, not to "database". I am not an expert in designing this just thinking you might be able to think this through. Thanks again!

**Comment by tananaev** [comment]
Now if you want to forward data to some web service you need to implement your own `IdentityManager` class and add instance of `BaseDataHandler` to the pipeline.

Regarding `BaseDataHandler`, you can use new `WebDataHandler` class or implement your own version if default implementation is not enough.
