### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#974]
Is there a reason you don't tag your release commits?

**Comment by tananaev** [comment]
I tagged all recent versions of Traccar and Traccar Client.

**Comment by jon-stumpf** [comment]
Thank you.

On Thu, Jan 22, 2015 at 5:15 PM, Anton Tananaev <notifications@github.com>
wrote:

> Closed #974 <https://github.com/tananaev/traccar/issues/974>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tananaev/traccar/issues/974#event-223349330>.
>



-- 
- jss
