### ISSUE TITLE
Script for enfora MT4000

### ISSUE THREAD

**Issue by etrace** [tananaev/traccar#993]
I would appreciate if somebody could give me a script for an enfora MT4000, I just purchased the device and I have not been able to make it work with Traccar

Best regards

Martin

**Comment by rmatamoros2015** [comment]
hi, does anyone has the script for the Enfora 4000 they can e-mail or send to me? please and thank you

**Comment by etrace** [comment]
This script makes the device report @ 5 minutes = 3600 SECONDS

 

AT

AT&F

AT&W

AT

AT+CGDCONT=1,"IP","PUT HERE THE APN","",0,0      

AT%CGPCO=1,"REPLACE HERE WITH APN USER NAME,REPLACE HERE WITH APN PASSWORD",0

AT$FRIEND= 1,1,"SERVER IP",5008,3

AT$TCPAPI=1

AT$TCPIDLETO=3600

AT$TCPRETRYTO=300

AT$wakeup=1,28

AT$EVTIM1=300

AT$EVENT=12,1,12,1,1

AT$EVENT=12,3,43,1,0

AT$EVENT=12,3,52,0,4166

AT$EVENT=14,0,0,0,0    

AT$EVENT=14,3,52,0,4166

AT$areg=2

ATS0=2

AT&W

AT$RESET

 

Best regards

 

Martin

**Comment by rmatamoros2015** [comment]
etrace, thank you very much for the script, although i just looked the model of my device and is actually MT4100 or rtt2201 will the script should be the same? if not, does anyone has the script for the MT4100 model? is TRACCAR compatible with this model? thank you all again for your help

**Comment by etrace** [comment]
I dont know if they are the same, you can try with the script that I sent you

 

regards

 

Martin

**Comment by rmatamoros2015** [comment]
Martin thank you for your response, quick question is the parser/decoder for this supposed to be getting the data in binary or ASCII? Thank you

Robert Matamoros  Ray's Trash service, Inc.
Network Administrator
317-539-9837 (w)  | 800-531-6752 (w)  |  317-539-7022 (f)
rmatamoros@raystrash.com<mailto:rmatamoros@raystrash.com>  |  www.raystrash.com<http://www.raystrash.com>

"THE ONLY PRODUCT WE HAVE TO SELL IS SERVICE!"

P Please consider the environment before printing this email

**Comment by rmatamoros2015** [comment]
so i got the device to send the data, but i'm getting a " WARN: Enfora decoder failed to find IMEI " how did you guys fixed this issue? thanks

**Comment by tananaev** [comment]
Currently Traccar supports only ASCII format.

**Comment by rmatamoros2015** [comment]
I got it to work, thanks


On Jul 23, 2015, at 5:26 PM, Anton Tananaev <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently Traccar supports only ASCII format.

—
Reply to this email directly or view it on GitHub<https://github.com/tananaev/traccar/issues/993#issuecomment-124244459>.

________________________________
The information contained in this e-mail message is privileged, confidential and protected from disclosure and discovery. If you are not the intended recipient , any dissemination, distribution, copying, or making available to be copied is strictly prohibited. If you think you have received this e-mail message in error, please alert the sender about the error. Thank you; we will extend the same courtesy. Any inconvenience to you for misdelivered messages is regretted.

*** Please consider the environment before printing this email. ***

**Comment by ahmedrkhedr** [comment]
hi any chance for 2238 enfora

**Comment by tananaev** [comment]
If it can send data in GPRMC format, you should be able to make it work with Traccar.

**Comment by gurudath** [comment]
I want to send only UDP packets  , how do i configure it? can anyone help me out . I am using MT4000

**Comment by tananaev** [comment]
Server side doesn't require any configuration. Not sure about device.

**Comment by tananaev** [comment]
Closing as stale. Please create a new issues if there are still some problems or questions.
