### ISSUE TITLE
just plotting long and lat location on your map without needing to send device packet data to your system

### ISSUE THREAD

**Issue by trackingcentral** [tananaev/traccar#994]
Hi 

I have downloaded the traccar software to my server

my devices already report to my server and i have a listener in place to capture the packets and my sql database stores the packet data received including separate long / late time etc for each event 

is it possible for me to simply use your mapping so that i can pass sets of long / lat co ordinates from my sql server to have those long and lats appear on the mapping page of your system 

so at this stage all i need is to be able to plot the actual locations stored on my sql database on a map

**Comment by dcontrerasr** [comment]
Hi, I'm starting with traccar and see you've progressed very well with your project. I want to make something like your project, you can help? I'm from chile and my name is Darwin.

**Comment by tananaev** [comment]
@dcontrerasr, Traccar is completely open source, so you can take it as a base for your project.

**Comment by trackingcentral** [comment]
I have only started with traccar

I am yet to implement it as I still need to understand how I can have it running on my own server as I have my own sql database where all my data needs to be stored.

The only screen I really need to display is the flitting of the location and the reserve geo coding so that it converts the long / lat to physical addresses

Traccar does not support geo fences however you can work around that as long as you can determine the long / lat of the centre of the fence and know the radius you want to set for your fence. Using both radius and Long / Lat of centre of fence allows you to use in a specific formula for measuring distance between 2 point and this will tell you if a location is inside out outside a geo fence



Claude Raiola
www.TrackingCentral.com.au
1300 255 990

"TrackingCentral is a registered NDIS Provider of Assisted Technology products and services for NDIS participants across Australia"

**Comment by trackingcentral** [comment]
Hi

Just wondering where traccar sources is location data for reverse geo coding of long / lay

Claude Raiola
www.TrackingCentral.com.au
1300 255 990

"TrackingCentral is a registered NDIS Provider of Assisted Technology products and services for NDIS participants across Australia"

**Comment by tananaev** [comment]
Traccar supports two reverse geocoding providers:
1. Google Maps API
2. Nominatim server

**Comment by trackingcentral** [comment]
So do the traccar users  still need a paid Google maps Api license subscription ???

Claude Raiola
www.TrackingCentral.com.au
1300 255 990

"TrackingCentral is a registered NDIS Provider of Assisted Technology products and services for NDIS participants across Australia"

**Comment by tananaev** [comment]
No, you don't. But there is a limit of 1000 requests per day or something like that, so if you have many devices it's better to host own Nominatim server.

**Comment by trackingcentral** [comment]
Nominatim server ???

I am wanting to avoid the $12,000 per annum licence fee from Google

Claude Raiola
www.TrackingCentral.com.au
1300 255 990

"TrackingCentral is a registered NDIS Provider of Assisted Technology products and services for NDIS participants across Australia"

**Comment by tananaev** [comment]
Nominatim is a free and open source server that uses OpenStreetMaps data:
http://wiki.openstreetmap.org/wiki/Nominatim
